### ISSUE TITLE
echo + php 5.4 new instance

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#1000]
Here is the diff before / after php-cs-fixer:

```diff
-    echo (new Process("$baseCommand purge queue name=$queue"))->mustRun()->getOutput();
+    echo(new Process("$baseCommand purge queue name=$queue"))->mustRun()->getOutput();
```

IMHO, the space should not be removed in this case.

What do you think ?

**Comment by GrahamCampbell** [comment]
This looks like a bug. It's probably caused by the fact we're treating echo as a function and treating the brackets as belonging to that rather than being wrapped around the new Process.

**Comment by keradus** [comment]
Yeah, it's a bug. Could you propose a fix for it ?

**Comment by lyrixx** [comment]
I think I'm not able to provide a fix. Sorry.

**Comment by sstok** [comment]
Detect if the first MeaningfulToken after the `(` is a new should be possible?
Which is actually a good candidate for a Transformer.

`CT_BRACE_CLASS_INSTANTIATION_OPEN` ? Better naming more then welcome :)

**Comment by keradus** [comment]
Nice idea!
Feel free to send a PR with it ;)

**Comment by sstok** [comment]
Any idea for a better name? Its a bit long and verbose :)

**Comment by keradus** [comment]
It won't be used frequently.
Braces are so overloaded and the discriminated name should be verbose to be unambiguous.

The name is cool for me.

**Comment by sstok** [comment]
OK, will get working on a PR then :+1:

**Comment by keradus** [comment]
Thanks ;)
2.0 imo ?

**Comment by sstok** [comment]
I'm OK with 2.0

**Comment by sstok** [comment]
#1006

**Comment by keradus** [comment]
Closing due to merge of #1006 (into 2.x line)

**Comment by lyrixx** [comment]
Thanks ;)
