### ISSUE TITLE
ruleset

### ISSUE THREAD

**Issue by Zakarisz** [FriendsOfPHP/PHP-CS-Fixer#1013]
Hello

Is there any plan to use a PHP_CodeSniffer ruleset.xml file to define the fixers to apply ?

**Comment by keradus** [comment]
this is not PHP_CodeSniffer and we won't use it's ruleset.xml file.
If you want to create your own configuration please use `.php_cs` file as mentioned in readme.

**Comment by Zakarisz** [comment]
The readme say 
***If you are already using PHP_CodeSniffer to identify coding standards problems in your code, you know that fixing them by hand is tedious, especially on large projects. This tool does the job for you.***

IMHO, you should not mention this tool if you don't want to work with.

**Comment by keradus** [comment]
And this say nothing about using two tools together ;)

**Comment by Zakarisz** [comment]
"If you use PHP_CodeSniffer, you will find something to fix in your code. It is tedious to fix it by hand so we did a tool to do it automatically, but don't use both together".
Funny philosophy !

**Comment by ceeram** [comment]
Both tools can be used together, although there would be no real benefit to that. The description you provided, just explains that the other tool only points out the errors and you had to fix them by hand (in previous versions), this tool fixes them right away. So it is only mentioned to explain the value of php-cs-fixer. As said you can use a configuration file to define which rules to apply, just not the .xml file used by the other tool.

**Comment by keradus** [comment]
everything is explained, closing
