### ISSUE TITLE
Order use fixer, subpackages after main ones

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1016]
I don't know if everyone agrees nor if there is a PSR rule for it (don't think so), but;
I was looking at some fixed code (run Fixer on master) and I was expecting something like this:

```php
use abc\ba;
use abc\Bar;
use abc\aaaaaa\bbb;
use Zoo\Bar;
```

but found something like this:

```php
use abc\aaaaaa\bbb;
use abc\ba;
use abc\Bar;
use Zoo\Bar;
```

Should the fixer take subpackages into account?

**Comment by keradus** [comment]
The fixer was supposed to order uses alphabetically and it done it.
I don't like proposed one, it's not intuitive for me.

**Comment by GrahamCampbell** [comment]
I don't like this idea either. The current behaviour is much better imo.

**Comment by SpacePossum** [comment]
:+1:  thanks!
