### ISSUE TITLE
phpstorm comments code with // at the beginning of line

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#1019]
when commenting code  phpstorm comments code with // at the beginning of the line and when phpcs runs it corrects only the first line apparently. We either don't do it at all or we correct more than one line.

```php
<?php

class Example
{
     public function getGoalChoices(CaseId $caseId)
     {
-//        'query_builder' => function (GoalRepository $repository) use ($options) {
+        //        'query_builder' => function (GoalRepository $repository) use ($options) {
 //        return $repository->createQueryBuilder('g')
}
```

**Comment by cordoval** [comment]
@GrahamCampbell does your upcoming fixer also fixes this?

**Comment by GrahamCampbell** [comment]
@cordoval No. My fixers only deal with the contents of T_DOC_COMMENT, not the other comments.

**Comment by GrahamCampbell** [comment]
This doesn't look like a bug imo though. This is the indentation fixer saying you must correctly indent your function bodies.

**Comment by keradus** [comment]
See no reason why not to indent whole multiline comment.
Could you send a patch?

**Comment by cordoval** [comment]
you are asking @GrahamCampbell right? :older_man: 

If you are tell me that, then can you elaborate at least where can I start trying my patch?

**Comment by GrahamCampbell** [comment]
> Could you send a patch?

@cordoval I assume @keradus wants you to send a fix since you're affected by this bug.

**Comment by keradus** [comment]
To be honest - I would be happy if any one of you could. Just can't handle all of them myself.

First should be decision about solution - to ignore comment or indent whole comment body.
Then - find a fixer which has that bug.
Next one is add a testcase to prove that bug in SomeFixerTest class.
And finally fix is it SomeFixer ;)

**Comment by cordoval** [comment]
there should be a cookbook with approaches to solve issues like this. Thank you @GrahamCampbell @keradus I will try but no promises i am pretty busy but trying to get back to the FOSS arena again.

**Comment by keradus** [comment]
We have one for creating a new fixer.
Please, based on new experience you gain could you propose it? For a regular contributor it is obvious and he won't mention everything what is needed.

**Comment by sstok** [comment]
This seems to be caused by the IndentationFixer, try disabling this to confirm.

I don't think we can actually change this, you can (temp) disable this fixer or not run the CS fixer when you are experimenting ;)

**Comment by keradus** [comment]
> I don't think we can actually change this

Could you elaborate this please?

**Comment by sstok** [comment]
Well, if we change this then the fixer will no longer indent comments (including the simple `//`), detecting if this commented code is possible but will slowdown the fixer.

I meant changing the behavior ;) (*working late makes me a dull boy*), the wrong indenting of comments must be fixed either way. Unless anyone else is willing to fix this I will take a stab at this in the weekend.

**Comment by keradus** [comment]
We could fix it:

```diff
class Example
{
     public function getGoalChoices(CaseId $caseId)
     {
-//        'query_builder' => function (GoalRepository $repository) use ($options) {
+        //        'query_builder' => function (GoalRepository $repository) use ($options) {
-//        return $repository->createQueryBuilder('g')
+        //        return $repository->createQueryBuilder('g')
}
```

**Comment by gharlan** [comment]
> when commenting code phpstorm comments code with // at the beginning of the line

OT, just a little note: You can change this in settings (Editor / Code Style / PHP / Other / Line comment at first line).

**Comment by cordoval** [comment]
closing since i think i rather not write comments to complicate things.
