### ISSUE TITLE
Update Symfony/CS/Fixer/Symfony/WhitespacyLinesFixer to support any line with trailing space

### ISSUE THREAD

**Issue by vijaycs85** [FriendsOfPHP/PHP-CS-Fixer#1021]
Is there any reason why we don't strip trailing space on all lines. As per Drupal, we have this as a standard https://www.drupal.org/coding-standards#indenting. If there isn't any real reason, Symfony/CS/Fixer/Symfony/WhitespacyLinesFixer can be extended to support this.

**Comment by keradus** [comment]
Is it a case of trailing_spaces vs whitespacy_lines?
If not please provide an example

**Comment by vijaycs85** [comment]
Thanks for the quick response.

yep, didn't realise it exist.

**Comment by keradus** [comment]
PSR2 allows lines that contains only whitespaces, therefore there is a fixer to remove them as well ;)

Glad to be helpful
