### ISSUE TITLE
Chaining problem

### ISSUE THREAD

**Issue by vschoener** [FriendsOfPHP/PHP-CS-Fixer#1022]
Hi, 

I just use this tool for my business project to correct PSR norm (cause a part of my team is not able to apply it properly for now) and I met a little bug after its usage. Here is the example : 

Methode without PHP CS Fixer usage : 

    /**
     * @return $this
     */
    public function process()
    {
        $this->
            syncCustomer()->
            resetState()->
            syncQuotatisCustomer()->
            resetState()->
            syncBuyerCustomer()->
            resetState()->
            syncWinningPayAndSponsors();

        return parent::process();
    }

And after use it : 

    /**
     * @return $this
     */
    public function process()
    {
        $this->
            syncCustomer();
        resetState()->
            syncQuotatisCustomer()->
            resetState()->
            syncBuyerCustomer()->
            resetState();
        syncWinningPayAndSponsors();

        return parent::process();
    }
As you see, the chaining call has been broken.
BTW, if there is any best practice to write chaining properly, let me know.

Regards

**Comment by GrahamCampbell** [comment]
It's because you have your `->` in the wrong place. They're meant to be starting each line, not ending it.

**Comment by vschoener** [comment]
Thank you for the advice, I'll apply this correctly for our future
development.

Le ven. 20 févr. 2015 à 11:49, Graham Campbell <notifications@github.com> a
écrit :

It's because you have your -> in the wrong place. They're meant to be

**Comment by keradus** [comment]
One way or another the fixer should not add a `;` there.
I can not duplicate it, on which version are you working and what is your configuration (perhaps default one) ? Could you provide example with biggest context, maybe it will allow to reproduce it.

**Comment by vschoener** [comment]
Hi @keradus,

My PHP version is : PHP 5.4.36
The PHP CS Fixer is the last version available. ( 1.5 ?)

Do you need a part of my file ?

**Comment by keradus** [comment]
That would be great @vschoener , I can't duplicate the issue.
Try to create minimal PHP file, on which the error occurs
