### ISSUE TITLE
List of conflicting fixers

### ISSUE THREAD

**Issue by cmodijk** [FriendsOfPHP/PHP-CS-Fixer#1023]
I think it should be in the docs wich fixers conflicts with other fixer. An example of this are the  `concat_without_spaces` and `concat_with_spaces` both do the opposite thing. I don't know which other are out there but I think the are there.

**Comment by GrahamCampbell** [comment]
I already proposed this, and it's getting done in 2.0.

**Comment by GrahamCampbell** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/910.

**Comment by cmodijk** [comment]
Sorry!
