### ISSUE TITLE
alternative config file

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#1027]
would be cool if php-cs-fixer supported a `.php` extension, besides current [.php_cs](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v1.5/Symfony/CS/Console/Command/FixCommand.php#L301)

the reason for this is that file type detection would be correct:
1) subversion auto properties setting proper mime type
2) various editors and IDE's that use *.php glob for syntax hiliting
3) ...

i  guess it should use `.php_cs`, if that is not found, try `.php_cs.php`

**Comment by keradus** [comment]
Any other opinion?

We already have `.php_cs` and `.php_cs.dist`, then having `.php_cs.php` and `.php_cs.dist.php` is pointless.

We also have `.php_cs.cache`, which is json, but not with json extension.

These files shouldn't be changes ofter, and if someone want he could always teach his IDE etc to treat them like regular php file.

Personally I would not change it. It is a config file, not a regular php file.

**Comment by keradus** [comment]
Very wel,.. closing then.

**Comment by glensc** [comment]
meh. pointless? i explained the "point".

you could make previous names deprecated and stick to new naming scheme.

i listed only two points where it can go wrong, there are more places where file should be treated as php not text file (typeless file?)

**Comment by glensc** [comment]
please reconsider adding `.php` extension support as well.

currently even default finder doesn't pick up `.php_cs` file to process it, not to mention the earlier file type by extension detection pointed out earlier by other tools.

also `.php_cs.cache` is not json, it's [PHP serialized](http://php.net/serialize) data.

**Comment by SpacePossum** [comment]
>also .php_cs.cache is not json, it's PHP serialized data.

On 1.x line [yes](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/FileCacheManager.php#L147) on 2.x [no](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Cache/FileHandler.php#L61). So you are both right :)

`.php_cs.dist` support is also on 2.x only ([ref.](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2157)). 

With `.php_cs` and `.php_cs.dist` it is clear which files should be tested for first and if both found which one should be used and which one ignored.
When adding other options like `.php_cs.php` and/or `.php_cs.dist.php` I wonder how the order of testing should be. 

.php_cs | .php_cs.dist | .php_cs.php | .php_cs.dist.php | use
---------- | ----------------- | ---------------- | ---------------------- | ---------
             |                      |                      |                            | build in default config
             |                      |                      |                         1 | .php_cs.dist.php
             |                      |                   1 |                            | .php_cs.php 
             |                      |                   1 |                         1 | .php_cs.php 
             |                  1  |                      |                            | .php_cs.dist
             |                  1  |                      |                         1 | ?
             |                  1  |                   1 |                            | ?
             |                  1  |                   1 |                         1 | ?
          1 |                      |                      |                            | .php_cs
          1 |                      |                      |                         1 | ?
          1 |                      |                   1 |                            | ?
          1 |                      |                   1 |                         1 | ?
          1 |                   1 |                      |                            | .php_cs
          1 |                   1 |                      |                         1 | ?
          1 |                   1 |                   1 |                            | ?
          1 |                   1 |                   1 |                         1 | ?

(to be clear, I'm not against the idea of adding the `.php` version of the configuration file(s), but am I wondering how this would work)

**Comment by glensc** [comment]
where can i read how `.php_cs` and `.php_cs.dist` are currently handled?

- are they "merged" and in what order?
- are they "used on first pick"?

**Comment by glensc** [comment]
as for new policy, depends what does the project recommend itself to use: `.php_cs` or `.php_cs.php` and based on that can probably think of priority of the files.

**Comment by SpacePossum** [comment]
>where can i read how .php_cs and .php_cs.dist are currently handled?
> * are they "merged" and in what order?
> * are they "used on first pick"?

The configuration files are not merged in any way. The `ConfigurationResolver` searches for candidate configuration files [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Console/ConfigurationResolver.php#L341). It selects the first valid candidate [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Console/ConfigurationResolver.php#L409) to use.
My vote for priority would be: `'user input'`, `php_cs`, `php_cs.dist`, `php_cs.php`.

**Comment by glensc** [comment]
@SpacePossum i'm ok with your proposal, as long as the list includes `.php` extension :)

also if the extensionless form is to be deprecated, there should be `.php_cs.dist.php` in the list as well.

**Comment by keradus** [comment]
big :-1: for adding next and next extension. if `.php_cs` is used defined and `.php_cs.dist` is repo defined, then adding extension should be to both of them, not only one of them. and that would make 4 files to choose from. pointles.
big :-1: for removing already support for already existing .

@glensc, I can see your point.
But seriously, issue was raised 1.5 years ago and got no support from comunity.

**Comment by glensc** [comment]
@keradus if you omit the deprecation part, you will have same amount of filenames to check. but i do not think it's wise idea.

and "pointless" is very lame to say, i've explained several times the problem. this application is not some high performant server that needs every bit of optimization. and i'm sure there are even more "pointless" code already in the repository, if one really wishes to pick on the topic.

**Comment by glensc** [comment]
and speaking of lameness, then `.php_cs` [is not even processed](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1027#issuecomment-252388703) by php-cs-fixer!

**Comment by glensc** [comment]
@SpacePossum never use branch links (like `master`) when referring to code with line numbers. use commit hash or some tag  to make permalinks :). 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1027#issuecomment-258096095

the line numbers are already off by now.

**Comment by keradus** [comment]
again, having 2 more files to support without any difference in functionality against current ones is no go, as it will bring confusion which ones will be used.
again, nobody deny value of your points, but you just didn't get any support from community for 1.5 years. think about it.

**Comment by glensc** [comment]
what community? it's only you here! i'm sure nobody browses closed issues!

**Comment by GrahamCampbell** [comment]
I think what we have is fine.

**Comment by glensc** [comment]
please re-consider to add config with `.php` to default search list, so dogfooding can happen: the phpcs config itself should also be applied the fixer rules!

**Comment by glensc** [comment]
Great stuff, the .php extension is now used in 3.0:
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0-rc.1/UPGRADE-v3.md
