### ISSUE TITLE
Feature request: read .php_cs from the current working directory

### ISSUE THREAD

**Issue by ezzatron** [FriendsOfPHP/PHP-CS-Fixer#1031]
On large code bases, it's quite nice to be able to fix just one sub-path at a time:

    php-cs-fixer fix src/Foo

Unfortunately, this completely ignores my `.php_cs` file in the project root. Since my preferred code style is significantly different to the default, it completely changes everything in `src/Foo`, which is very frustrating. It's also very easy to do by accident.

Could the `.php_cs` file always be read from `.` rather than the supplied path? Or perhaps fall back to `.` if no `.php_cs` file is found in the supplied path?

**Comment by ceeram** [comment]
You can for now use the `--config-file` option to ensure the correct config file to be used when running on specific folder. Hope this helps.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by keradus** [comment]
on 2.0@dev line you can have both `.php_cs.dist` config and your own `.php_cs` (excluded from repo, to work locally), where you can choose only that dirs that you want to handle.

**Comment by parkertr** [comment]
I'm not sure you guys understand what Ezzatron is saying.  This is directly related to the following issue - https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/302

If you run php-cs-fixer from the root directory of a project and specify a path within that project to fix then it ignores the .php_cs file in the project root.
