### ISSUE TITLE
List of conflicting fixers

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1033]
See #910 for details.

~~fixer A turns off fixer B:~~
~~- BlanklineAfterOpenTagFixer -> NewlineAfterOpenTagFixer~~
~~- RemoveTrailingSpacesFixer -> TrailingSpacesFixer~~
~~- RemoveTrailingSpacesFixer -> WhitespacyLinesFixer~~

fixer A and B can't be run together
- PhpdocVarToType and PhpdocTypeToVar 
- LongArraySyntaxFixer and ShortArraySyntaxFixer
- ConcatWithSpacesFixer and ConcatWithoutSpacesFixer
- UnalignEqualsFixer and AlignEqualsFixer
- UnalignDoubleArrowFixer and AlignDoubleArrowFixer

**Comment by GrahamCampbell** [comment]
You're missing a load of fixers from this list.

**Comment by GrahamCampbell** [comment]
Both concatenation fixers conflict with each other, and the "type to var" and "var to type" fixers conflict too. Not sure what else conflicts.

**Comment by keradus** [comment]
I didn't say it is a full list, just need some place to keep it.

**Comment by gharlan** [comment]
* LongArraySyntaxFixer vs. ShortArraySyntaxFixer

**Comment by gharlan** [comment]
* ConcatWithSpacesFixer vs. ConcatWithoutSpacesFixer

**Comment by keradus** [comment]
thanks, updated

**Comment by GrahamCampbell** [comment]
I did say this earlier. :)

> Both concatenation fixers conflict with each other

**Comment by GrahamCampbell** [comment]
single_blank_line_before_namespace and no_blank_lines_before_namespace conflict too.

**Comment by GrahamCampbell** [comment]
unary_operators_spaces and logical_not_operators_with_spaces

**Comment by GrahamCampbell** [comment]
i think our unary_operators_spaces should be updated not to change `!`.

**Comment by GrahamCampbell** [comment]
logical_not_operators_with_spaces also potentially conflicts with what ever fixer it is that ensures things are pushed up against the side of opening brackets in if stataments.

**Comment by keradus** [comment]
> unary_operators_spaces and logical_not_operators_with_spaces

ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1306#issuecomment-122811837
(about similar `LogicalNotOperatorsWithSuccessorSpaceFixer`)

When `unary_operators_spaces` is run first there is no conflict.


> I think our unary_operators_spaces should be updated not to change !.

Why is that? `!` is unary operator and should be fixed by `unary_operators_spaces` fixer.


> logical_not_operators_with_spaces also potentially conflicts with what ever fixer it is that ensures things are pushed up against the side of opening brackets in if statements.

Any specific fixer in mind?

**Comment by GrahamCampbell** [comment]
> Any specific fixer in mind?

D'no, that's why i didn;t quote it's name.
