### ISSUE TITLE
The fixer adding trailing commas in multiline arrays should take heredoc and nowdoc into account

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#1040]
```php
$test = array('foo', <<<TWIG
foo
bar
baz
TWIG
    , $twig);
```

for this code, the trailing comma fixer considers this array as multiline because of the newline whitespace after the heredoc. However, the only reason this newlines is here is because of PHP restrictions forcing to put it here. Except for that, the array was meant to be single-line (with a multiline string in it).
This code is a shorter version of code used in the Twig testsuite, found because of a fabbot.io report: https://github.com/twigphp/Twig/blob/19f8d073aaf7cadf6218d88c9f651657cfda9211/test/Twig/Tests/Node/ModuleTest.php

I think that this case should not force the trailing comma (it should force it if other elements not using heredoc are followed by newlines of course, or if there is a newline after the comma which is after the heredoc)

**Comment by keradus** [comment]
Fixed in #1048
