### ISSUE TITLE
Exit status should be 0 if there are no errors

### ISSUE THREAD

**Issue by nesl247** [FriendsOfPHP/PHP-CS-Fixer#1041]
The way I have it is that php-cs-fixer is run in a pre-commit hook to automatically correct any formatting. Right now, because of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/158, it seems that any changes cause it to return a 1 instead of a 0. If there are no errors, why is this returning a 1? Making changes means it completed the job successfully.

If anything, please add an option to allow for proper exiting, or the opposite, to allow for improper exiting as it is today.

Again, the purpose of php-cs-fixer is to FIX stuff, not just to verify there are no changes needed.

**Comment by GrahamCampbell** [comment]
> Making changes means it completed the job successfully.

No, I disagree. If changes were required, than the cs checks have failed.

**Comment by nesl247** [comment]
I'm not sure I understand you. How did anything fail if all I am running it for is to automatically format the code? The purpose is to allow developers to code in whatever style they want, and then on commit, it will automatically format it before it is committed.

Nothing failed in this scenario. php-cs-fixer gets run to do the formatting, it finds stuff to format, and does so. I can understand if --dry-run is used, and then it would exit 1 because there are changes required.

**Comment by ceeram** [comment]
exit 0 makes sense to me, as the command fixed incorrect code. The command
itself finished succesfully.

php.net: `The status 0 is used to terminate the program successfully`

2015-03-03 20:52 GMT+01:00 Harrison Heck <notifications@github.com>:

**Comment by ceeram** [comment]
exit 0 makes sense to me, as the command fixed incorrect code. The command itself finished succesfully. php.net: `The status 0 is used to terminate the program successfully`

**Comment by stof** [comment]
@GrahamCampbell This tool is not a CS checker. It is a CS fixer. so it would indeed make sense to exit 1 only in dry-run mode (or in case a specific option is passed)

**Comment by keradus** [comment]
We also `exit(1)` when error occurs (like too old PHP).
We should return different exit code for reporting need of fixing in dry-run mode.

:+1: for idea itself. Could anyone prepare a patch ?

**Comment by keradus** [comment]
Closing due to merge of #1078

**Comment by JoyceBabu** [comment]
Currently PHP-CS-Fixer returns 0 if `--dry-run` is not specified, even when some files were skipped due to syntax errors. Shouldn't it return a non-zero value when a file was skipped?

The fixer was expected to fix the file, but it was not fixed. Isn't that an error condition?
