### ISSUE TITLE
Better configuration file option

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1068]
I want to use the fixer in PhpStorm as "External Tool". I use these settings:

![screenshot 2015-03-20 11 41 36](https://cloud.githubusercontent.com/assets/330436/6749988/23302d6a-cef6-11e4-8d6c-e0ac9d7c3b60.png)

I'm using a shortcut (`alt+cmd+s`) for a macro "Save and fix". So I'm fixing single files (the currently editing file).

Now I want to achieve that the fixer is using the first actually existing config file of this list:

* `<project-root>/.phpcs`
* `<project-root>/.phpcs.dist`
* `~/.phpcs`

So I could use the fixer for all my projects.

Any idea, how we could achieve this? Maybe by giving an array for `--config-file` and the fixer uses the first one that exists?

**Comment by vinkla** [comment]
This would be a great feature! The parameter field could currently become a bit cluttered when adding custom fixers. I've replace the default format shortcut to run the macro. Since it's not necessary anymore.

Is there a way to trigger the macro when typing? Similar to the default formatter in PhpStorm.

**Comment by jakoch** [comment]
Good idea! `php-cs-fixer fix` could use `.phpcs` or `.phpcs.dist` from the same dir or one level up.
When installed via composer, the fixer resides in /bin - often the config is in the project root dir, one level up.

**Comment by gharlan** [comment]
> same dir or one level up

I would say: current working dir (independent of the location of php-cs-fixer)

**Comment by vinkla** [comment]
Though, it would be great if you could but it in your home folder `~/.phpcs` to use as a default. Like how GIT handles a `.gitignore` file.

**Comment by gharlan** [comment]
Yes, "current working dir" is just a solution for the first two points of my list (`<project-root>/.php_cs(.dist)?`).

**Comment by keradus** [comment]
I am against .php_cs in local home dir. The configuration is very project related and even when sb use same configuration for all of his projects we must not assume that every collaborator will have that config too, and when it will be inside project then we may not assume anything.

**Comment by GrahamCampbell** [comment]
I'm with @keradus here. I don't like the idea.

**Comment by gharlan** [comment]
For projects shared with others I agree: There always should be a project specific configuration file.

The purpose of the global configuration is non-shared code, code only I'm working with.
Now you could say: Why a cs fixer for this? Just do it in your style.
As I know there is the fixer, often I type in short form like:

```php
if($cond)
    foo();
else
    bar();
```

Then press `alt+cmd+s` (see first post), and I get the braces and spaces etc.
And for this I would like to set my personal global configuration.

But I accept your no's. Are they only against the global config in home directory or also against the change concerning the current working dir?
At the moment the project configuration is not used when executing something like `php php-cs-fixer fix Symfony/CS/Fixer`..

**Comment by keradus** [comment]
lack of interest

**Comment by vinkla** [comment]
@gharlan I don't know how you solved having global configuration but [here is my approach](https://github.com/vinkla/dotfiles/blob/master/bin/fix). I create a custom `fix` tool that downloads my config from a GitHub gist and applies it to the current directory. This also works in PhpStorm, just replace `php-cs-fixer` with the `fix` tool if you want to use it there as well.
