### ISSUE TITLE
Missing test cases for function/const imports

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1084]
Afaik we do not have any test case for these imports:

```php
use function Foo\bar;
use const Foo\BAZ;
```

The "function" and "const" parts are tokenized as `T_FUNCTION` and `T_CONST`, so they may break fixers using these tokens.
And we should check `UnusedUseFixer` and `OrderedUseFixer`.

**Comment by GrahamCampbell** [comment]
Good point. Hmmm.

**Comment by gharlan** [comment]
To avoid side effects in fixers using T_FUNCTION and T_CONST we could add a transformer for these special uses.

**Comment by GrahamCampbell** [comment]
Yeh, nb. new transformers must go into 2.0. Also, every transformer we add has a performance overhead, so we need to be sure they are the best way to do it.

**Comment by keradus** [comment]
After rewritting Transformers (2.x line) the performance overhead is not so big.
Yes, they should be discriminated into new custom tokens.

@gharlan , could you take care of it, previously adding missing cases for our fixers ?

**Comment by keradus** [comment]
Closing after merge of #1107
