### ISSUE TITLE
The code comments [@return] will word wrap.

### ISSUE THREAD

**Issue by dzgrief** [FriendsOfPHP/PHP-CS-Fixer#1085]
##### For example:
```
/**
 * encrypt string
 * @param  string $key        [description]
 * @param  string $distracter [description]
 * @return string             [description]
 */
public function encrypt($key, $distracter = null)
{
}
```

##### Will convert

```
/**
 * encrypt string.
 *
 * @param string $key        [description]
 * @param string $distracter [description]
 *
 * @return string [description]
 */
public function encrypt($key, $distracter = null)
{
}
```

**Comment by keradus** [comment]
What with it?
I see a proper work made by `phpdoc_order`

**Comment by dzgrief** [comment]
PHP-CS-Fixer execution object should be the code itself, as for the format of the code comments should not change.Now the code comments also formatted, so look not beautiful.

**Comment by keradus** [comment]
Comments are parts of code and we take care of them heavily.
Just like we follow PSR-2 we follow PSR-5 (PHPDoc DRAFT).

If you do not want to have `T_DOC_COMMENT` changed then simply don't use `phpdoc_*` fixers ;)

**Comment by dzgrief** [comment]
Ok, I get what I want effect, thank you
