### ISSUE TITLE
1.6 Regretion With Extra New Lines

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1091]
![image](https://cloud.githubusercontent.com/assets/2829600/6814564/9c11bb3e-d277-11e4-9096-095e8db4122a.png)

Not 100% sure what's causing this. My hunch is one of the namespace lines fixers is fixing too much.

**Comment by keradus** [comment]
NS fixer should not fiddle between methods

**Comment by GrahamCampbell** [comment]
Yeh, that's what I thought, but I can't think of anything else atm. I'm trying to work it out, lol...

**Comment by keradus** [comment]
btw, please check 1.5 too

**Comment by GrahamCampbell** [comment]
Though, this file in the screenshot has no "namespace" in it.

> btw, please check 1.5 too

Will do soon.

**Comment by GrahamCampbell** [comment]
> Though, this file in the screenshot has no "namespace" in it.

Could that be the issue?

**Comment by GrahamCampbell** [comment]
Ok, it looks not to be the namespace fixers. All off and still persists. :(

**Comment by gharlan** [comment]
ExtraEmptyLinesFixer?

**Comment by GrahamCampbell** [comment]
> ExtraEmptyLinesFixer?

Maybe...

**Comment by GrahamCampbell** [comment]
Let me see. My bad if it is...

**Comment by GrahamCampbell** [comment]
So sorry guys!

**Comment by keradus** [comment]
:beer: @gharlan ;)

**Comment by gharlan** [comment]
:)
