### ISSUE TITLE
eof_ending fixer doesn't like windows style new lines

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1092]
Surely if a file ends in a windows style new line, that still counts as ending in a new line of some sort, so no fixes should be made?

**Comment by SpacePossum** [comment]
The `eof_ending fixer` is PSR-2 and PSR-2 also states `All PHP files MUST use the Unix LF (linefeed) line ending.` Therefor I think the `windows style new line` should not be supported. 
The exception is when using the `windows style new line` outside of PHP, for example at the end of a file after the `?>` tag. To support this I created https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1193

**Comment by keradus** [comment]
Closing due to merge of #1193
