### ISSUE TITLE
Replace <?= with <?php echo

### ISSUE THREAD

**Issue by vinkla** [FriendsOfPHP/PHP-CS-Fixer#1095]
Does this fixer already exists? If not, maybe we could implement it?

**Comment by keradus** [comment]
why closed? :)

**Comment by vinkla** [comment]
Sorry accident.

**Comment by keradus** [comment]
go ahead ;)
:+1: for idea ;)

**Comment by vinkla** [comment]
I'll try to add this :) What about `Symfony\CS\Fixer\Contrib\ForceLongTagFixer`?

**Comment by keradus** [comment]
`ShortEchoTagFixer`
