### ISSUE TITLE
Multiline Annotation

### ISSUE THREAD

**Issue by digitalkaoz** [FriendsOfPHP/PHP-CS-Fixer#1096]
as ORM Annotation can get quite long, we indent them like this:
```php

    /**
     * @ORM\ManyToMany(
     *  targetEntity="\Dl\Component\DomainModel\Product\Value\AbstractValue", 
     *  cascade={"persist","remove"}
     * )
     * @ORM\JoinTable(
     *  name="Product_Value",
     *  joinColumns={@ORM\JoinColumn(name="product_id", referencedColumnName="id", onDelete="CASCADE")},
     *  inverseJoinColumns={@ORM\JoinColumn(name="value_id", referencedColumnName="id", onDelete="CASCADE")}
     * )
     */
    private $foo;
```

sadly the fix totaly scrambles it. is there a common convention on this, so a fixer could be written?

**Comment by GrahamCampbell** [comment]
I don't know of any conventions. But I did add some docblock and annotation stuff to php-cs-fixer not long ago: https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.7/Symfony/CS/DocBlock.

**Comment by digitalkaoz** [comment]
will try out the 1.7 branch...

**Comment by GrahamCampbell** [comment]
It's on the 1.5 and 1.6 branch too btw.

**Comment by GrahamCampbell** [comment]
We just don't mess with the indentation of this stuff because lots of people have lots of different ways of doing things.

**Comment by digitalkaoz** [comment]
ah yeah, imported annotation are completely untouched?

**Comment by digitalkaoz** [comment]
there are still some weird changes:

```diff
    /**
      * @var Collection<Value>|Value[]
      * @ORM\ManyToMany(
-     *   targetEntity="\Dl\Component\DomainModel\Product\Value\AbstractValue",
-     *   inversedBy="externalAliases"
-     * )
+     *                                targetEntity="\Dl\Component\DomainModel\Product\Value\AbstractValue",
+     *                                inversedBy="externalAliases"
+     *                                )
      */
     private $values;
```

**Comment by digitalkaoz** [comment]
it has todo with a missing newline between `@var Very\Long\ClassName\So\The\Rest\Will\Be\Indented` and the `@ORM` Annotation

**Comment by GrahamCampbell** [comment]
This is a bug with @fabpot's alignment fixer.

**Comment by keradus** [comment]
@digitalkaoz @GrahamCampbell 
please, could you take a look at #1209 ?

**Comment by digitalkaoz** [comment]
it looks like its fixed...

**Comment by keradus** [comment]
hurray ;)
