### ISSUE TITLE
Only exit with exit code 1 when --dry-run option is present

### ISSUE THREAD

**Issue by Addvilz** [FriendsOfPHP/PHP-CS-Fixer#1099]
The current behavior is to always exit with exit code 1 if something is fixed. This behavior is not desired, as it breaks automation tools. As stated in PR #173, this is nice for use in CI, however, it also makes sense to use php-cs-fixer with --dry-run in CI to not to modify artifacts, therefore, I suggest fallowing changes to the current behavior:

* Without --dry-run:
  * exit code is not 1 only if there was an error state
  * exit code 0 in all other cases
* With --dry-run:
  * exit code 1 when something was to be fixed
  * exit code 0 when nothing to fix

**Comment by gharlan** [comment]
duplicate..
issue: #1041 
pr: #1078

**Comment by Addvilz** [comment]
Dammit, how did I miss this?
Issue closed.
