### ISSUE TITLE
Multiline function call

### ISSUE THREAD

**Issue by mrsinham** [FriendsOfPHP/PHP-CS-Fixer#111]
Hi,

First I will say that I love php cs fixer, very useful to pass codesniffer tool. I have some problem with a codesniffer validation that cs fixer dont fix, it is this one :

  32 | ERROR | Opening parenthesis of a multi-line function call must be the
     |       | last content on the line
  33 | ERROR | Multi-line function call not indented correctly; expected 16
     |       | spaces but found 29
  33 | ERROR | Closing parenthesis of a multi-line function call must be on a
     |       | line by itself

For this kind of code :

``` php
$this->myFunction()->thatDo('lipsus',
                             array('foo' => $bar));
```

Can php cs fixer have an option to fix this kind of code ? 

Thanks for this tool anyway !

**Comment by Sharlyll** [comment]
Hi all,

I am a newbue, so pardon my mant questions.


I have 2 domains in my hosting account. I notice that when installing fixer in domain A, it automatically defaults to the home directory and installs fixer there.
I have composer.phar installed in each domain, 
I am installing via composer.phar globally,
I am installing via ssh

My questions: 
1) How do i install Fixer in each domain inside public_ html folder without it defaulting to the home directory which is outside the public_html folder?

Please tell how to use this command correctly?

$ php php-cs-fixer.phar fix /path/to/dir


Thanks a lot!

**Comment by SpacePossum** [comment]
Hi @Sharlyll,

I'm a bit confused about your question to be honest. I think it is not related to this issue right?
For the installing question, if I get it right you want the tool installed on a hosting account which hints towards a production (and/or staging) environment. I would advice against installing the tool on such system, it is meant to be a developers tool and possibly integrated into a CI setup. That aside, you can install the tool as phar on any location you want. You probably follow the install instructions which are meant for one global install of the tool on a development environment, that why it is suggested to install it in `usr/local/bin`.

**Comment by Sharlyll** [comment]
Hi @SpacePossum,
thanks for the response! its indeed not related to this issue (I wasn't sure where to ask)
your explanation makes sense to me now. I needed the Fixer for magento2 installation. its now been sorted by my hosting. if i have any more questions, i will create a new thread.
thanks!

**Comment by SpacePossum** [comment]
best of luck! :+1:

**Comment by ddctd143** [comment]
Looks like this issue still is open. Any PR for this ?

**Comment by keradus** [comment]
you are more than welcome to propose one !

**Comment by julienfalque** [comment]
Closing as #2440 was merged.

**Comment by coreation** [comment]
I want to refrain from opening up a new issue because this seems to be solved, so i'll post my question here:

```
$x = Class::where([
   'arg' => 'foo',
   'arg2' => 1,
   'role' => 'bar',
])
    ->whereNotIn('id', [1, 2, 3])
    ->function();

This seems like it's faulty, however when I look at the indentation, it seems to be following the rule that a chained function call on a new line. However if you pass the parameters inline, then this becomes a bit weird... is there a standard that covers this type of use case, or do I play around with the settings to have the chained call not being indented?
```
