### ISSUE TITLE
PhpdocParamsFixer PHP Notice:  Undefined offset: 3 in exceptions

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1111]
Hi all,

When running the PhpdocParamsFixer on a class like this:

```php
<?php
namespace Test;

use Silex\Application;


class TestDatabase {

	/**
	 * @return resource Doctrine\DBAL\Connection or null if not found
	 * */
	public static function getTest()
	{
		return null;
	}
}
```

It throw this to the console:
`PHP Notice:  Undefined offset: 3 in /home/seb/work/Correspondent/vendor/fabpot/php-cs-fixer/Symfony/CS/Fixer/Symfony/PhpdocParamsFixer.php on line 101`

(please not this isn't real code, I deleted everything to scope down the problem).

Love to help, but I cannot find the problem :(

Running into this on latest phar release and on "fabpot/php-cs-fixer": "1.6",  PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39)

**Comment by GrahamCampbell** [comment]
Probably because of that dodige end to the docblock. Also, you do realise your docblock is totally invalid to any ide, or even a person reading it?

This is totally invalid!
```php
    /**
     * @return resource Doctrine\DBAL\Connection or null if not found
     * */
```

Valid version:
```php
    /**
     * We're returning a resource of a db connection, if possible.
     *
     * @return resource|\Doctrine\DBAL\Connection|null
     */
```

**Comment by keradus** [comment]
But still it would be really cool to not raising notice on weird docblock

**Comment by GrahamCampbell** [comment]
NB, this fixer isn't one of mine. It was too confusing for me to rewrite when I did the phpdoc stuff. :)

**Comment by keradus** [comment]
Relax, nobody blames you ;)

**Comment by GrahamCampbell** [comment]
> Relax, nobody blames you ;)

lol. I was just saying I don't know the internals of this fixer, so I'm little use trying to fix it. :)

**Comment by SpacePossum** [comment]
@GrahamCampbell I'm aware of the comments being invalid. I just inherited a (large) code base with all kind of oddities. Im trying to clean that up now using the PHP-CS-Fixer.
Thanks for the comments @GrahamCampbell and @keradus, very fast :)

**Comment by keradus** [comment]
Closing due to merge of #1114
