### ISSUE TITLE
DocBlock alignment after the curly brace  

### ISSUE THREAD

**Issue by cmodijk** [FriendsOfPHP/PHP-CS-Fixer#1121]
The following code is alignment my DocBlock to the left instead of in the function. 

This code
```
class MyController
{
    /**
     * @param Request $request
     * @param null    $id
     */
    public function editAction(Request $request, $id = null)
    {
        /**
         * @var EntityRepository $repository
         */
        // Ophalen van project of nieuw maken
        $repository = $this->getDoctrine()->getRepository('RefurlDataBundle:Blacklist');
        ... other code
    }
}
```

Becomes this
```
class MyController
{
    /**
     * @param Request $request
     * @param null    $id
     */
    public function editAction(Request $request, $id = null)
    {
/**
 * @var EntityRepository $repository
 */
        // Ophalen van project of nieuw maken
        $repository = $this->getDoctrine()->getRepository('RefurlDataBundle:Blacklist');
        ... other code
    }
}
```

This stated to happen when we upgraded to the 1.6 version. If i move the DocBlock to an other place in the function this does not happen.

**Comment by GrahamCampbell** [comment]
We need to see the "other code" please. That's quite important.

**Comment by keradus** [comment]
Also, what version are you using? 1.6?

**Comment by cmodijk** [comment]
@keradus Yes, we are using the 1.6 release

@GrahamCampbell I have updated the comment it happens when there is an // comment after the /** block if i remove the // block is does not happen.

**Comment by GrahamCampbell** [comment]
Your docblock is actually invalid then. A docblock MUST document something. It cannot document a comment.

**Comment by cmodijk** [comment]
Tnx! We fixed this.
