### ISSUE TITLE
Upon fixing a file, should it check the file again?

### ISSUE THREAD

**Issue by navitronic** [FriendsOfPHP/PHP-CS-Fixer#1124]
I have recently run into some issues fixing code that introduces more issues with the code and the caching mechanism.

As an example, we allow PHP-CS-Fixer to remove unused use statements. When it does this, if there was only a single use statement, it will leave two blank lines after the namespace declaration and before the beginning of the class.

If we were to rerun the fixer, it will pick this up as an error.

However as the file has been added to the cache from the previous run and it hasn't changed since then, the second run doesn't see the file as needing to be checked, so skips over it.

So, my question is, could the fixer be rerun against the file to check for further errors introduced by the initial fixing? 

Does this seem like a sane approach?

**Comment by keradus** [comment]
File after fixing must not need another fixing.
Please provide sample file for which the bug occurred.

**Comment by navitronic** [comment]
Given the following class:
```
<?php

namespace Foo\Bar;

use Abc\Def;

class Baz {
}
```

Running the `unused_use` fix will leave:

```
<?php

namespace Foo\Bar;


class Baz {
}
```

Which fails for the `line_after_namespace` rule.

**Comment by navitronic** [comment]
This is my current config file:

```php
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in(__DIR__ . "/src");

return Symfony\CS\Config\Config::create()
    ->level(\Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers([
        'unused_use',
        'remove_lines_between_uses',
        'short_array_syntax',
        'whitespacy_lines',
        'ternary_spaces',
        'standardize_not_equal'
    ])
    ->finder($finder)
    ->setUsingCache(true);
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting. We just need to change the fixer orders internally.

**Comment by navitronic** [comment]
Happy to help.

However, changing the order of the fixers feels like it's only treating this one instance, whereas rerunning the fixer to check for issues will cover all possible conflicts, including the cases where people are defining all their fixers manually.

It also prevents problem files from hitting the cache with issues present.

**Comment by keradus** [comment]
We do greatly deal with order of fixers to prevent need of refix and cache issues.
Indeed, this is a bug with order, probably easy to fix.
If one define fixers manually then we still take care of order, and if one create his own custom fixer then he must set a valid priority by himself.

**Comment by GrahamCampbell** [comment]
@keradus Maybe we just need a list of all the fixers in a fixed order, instead of the crap we have now were we try to deal with priorities. Then it can be obvious what's going on.

**Comment by keradus** [comment]
Relations like "run after" are cool for me. But in facts we have it currently via priorities

**Comment by GrahamCampbell** [comment]
> But in facts we have it currently via priorities

Yeh, I think that's a bad idea, because it allows us to forget about fixers, leading to this bug.

**Comment by keradus** [comment]
The bug behind this issue is that `unused_use` fixer create `T_WHITESPACE` tokens one after another.

**Comment by gharlan** [comment]
So the bug exists only in master branch? (Because in other branches the token collection is not reused, so it does not matter if there are `T_WHITESPACE` tokens one after another.)

**Comment by keradus** [comment]
The bug exists on 1.x line too, because the tokens collection is reused there as well.

**Comment by gharlan** [comment]
Ah ok, didn't know that :D

**Comment by keradus** [comment]
Closing due to merge of #1149

**Comment by navitronic** [comment]
Thanks for looking into this and providing a fix. :+1: 

Much appreciated.
