### ISSUE TITLE
Fatal error: Class undefined: Symfony\CS\Fixer\Contrib in phar://php-cs-fixer.phar/Symfony/CS/Fixer.php on line 77

### ISSUE THREAD

**Issue by andybeak** [FriendsOfPHP/PHP-CS-Fixer#1127]
Downloading and running the phar throws this error.

Fatal error: Class undefined: Symfony\CS\Fixer\Contrib in phar://php-cs-fixer.phar/Symfony/CS/Fixer.php on line 77

**Comment by stof** [comment]
this looks really weird. can you give some details about your PHP version ?

**Comment by andybeak** [comment]
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

I think that probably answers the question... Let me try with php itself :)  Thanks man

**Comment by stof** [comment]
Looks like either the phar is doing weird things in HHVM, or the SPL iterators are.

**Comment by keradus** [comment]
next bug of HHVM, could you report it to hhvm @andybeak please ?
