### ISSUE TITLE
Cannot install PHP-CS-Fixer 1.6 from Homebrew

### ISSUE THREAD

**Issue by Glavin001** [FriendsOfPHP/PHP-CS-Fixer#1133]
I have Homebrew version 0.9.5, PHP 5.6.7, and PHP-CS-Fixer 1.2

I am trying and unable to install the latest PHP-CS-Fixer (after the pull request https://github.com/Homebrew/homebrew-php/pull/1639 to Homebrew, which simply updated from 1.2 to 1.6).

Here is what is logged:

```bash
$ brew install php-cs-fixer
==> Installing php-cs-fixer from homebrew/homebrew-php
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
==> Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/archive/v1.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php-cs-fixer-1.6.tar.gz
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Iterator RecursiveIteratorIterator returned a path "/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description" that is not in the base directory "/private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/src"' in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php:9
Stack trace:
#0 /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php(9): Phar->buildFromDirectory('src')
#1 {main}
  thrown in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php on line 9
Error: No such file or directory - php-cs-fixer.phar
```

Personally I am not a PHP developer and only use this package for my package https://github.com/Glavin001/atom-beautify so I am unable to assist much and do not know about the inner workings of PHP package managers and PHP-CS-Fixer.

I wanted to create this in hopes that someone recognized this issue and I could update PHP-CS-Fixer.

Thank you in advance!

**Comment by keradus** [comment]
Hi!
Thanks for writing.
Please report it directly to homebrew. We simply cannot fix their bug here.

What we can is to offer installing via composer or downloading ready to use .phar file ;)

**Comment by Glavin001** [comment]
> Please report it directly to homebrew. We simply cannot fix their bug here.

I thought the problem may have been actually with the PHP code in PHP-CS-Fixer:

> PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Iterator RecursiveIteratorIterator returned a path "/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description" that is not in the base directory "/private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/src"' in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php:9
Stack trace:
#0 /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php(9): Phar->buildFromDirectory('src')
#1 {main}
  thrown in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php on line 9
Error: No such file or directory - php-cs-fixer.phar

Installing 1.2 with Homebrew works, and [the only change from Homebrew's perspective is changing the version number](https://github.com/simplechris/homebrew-php/commit/b5b753d886a766d41fca83a1038b30c25297e819) and downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/archive/v1.6.tar.gz instead of https://github.com/FriendsOfPHP/PHP-CS-Fixer/archive/v1.2.tar.gz
Sounds like a breaking change in PHP-CS-Fixer (or PHP installation) issue to me.
[And Homebrew uses Composer to install, I believe.](https://github.com/simplechris/homebrew-php/blob/b5b753d886a766d41fca83a1038b30c25297e819/Formula/php-cs-fixer.rb#L15)

However, I'll post to Homebrew and hopefully someone can help, but I kind of doubt it :stuck_out_tongue: . It's unfortunate: this means that Mac users using Homebrew will not be able to install PHP-CS-Fixer until this is resolved, *by someone*.

**Comment by keradus** [comment]
Stack you provided assures me that this is a bug of homebrew - they are not paths of PHP CS Fixer.

homebrew causes a lot of problems, this is not the first time.
I strongly advise mac users to simply use composer or download .phar version

**Comment by Glavin001** [comment]
Bummer. Thanks for your help!
