### ISSUE TITLE
Fixer To Remove Comments From Return Annotations Would Be Cool

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1136]

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
no spec, no answer for ping, closing

**Comment by GrahamCampbell** [comment]
`@return string Some thing.` -> `@return string`

**Comment by keradus** [comment]
feel free to propose a PR

**Comment by GrahamCampbell** [comment]
I'll do one in June. Please keep the issue open. ;)

**Comment by keradus** [comment]
I heard it so many times :(
there were no support for this issue from community, for that I will leave it as is.
nevertheless, if you would have proposal, feel free to present it.

**Comment by GrahamCampbell** [comment]
Probably won't remember. Anyways, if nobody else is interested them, who cares. :trollface:

**Comment by keradus** [comment]
you cared asking for reopening ticket that got no answer for 2 years ;)
