### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1141]
https://i.starbs.net/RRX8

The movement of that comment.

**Comment by gharlan** [comment]
Please add a more verbose title. It is the third time that I look into this issue because I've forgotten what the issue is about.

And I would say the movement should not be happen.

**Comment by keradus** [comment]
Which fixer is doing that? Please send a minimal test case as real code, not img.

**Comment by SpacePossum** [comment]
>Please add a more verbose title. It is the third time that I look into this issue because I've forgotten what the issue is about.

2nd that :)

**Comment by keradus** [comment]
```php
<?php

$a = [
    'explain' => [// FOO: bar
        1 => 2,
    ],
];
```

**Comment by keradus** [comment]
```php
<?php

$a = [
    'explain' => [// FOO: bar
        1 => 2,
    ],
];
```
works great.

Sadly closing as cannot reproduce.
