### ISSUE TITLE
Remove double `ConfigurationResolver` class from master

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1154]
cc @keradus 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/ConfigurationResolver.php
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Console/ConfigurationResolver.php

**Comment by GrahamCampbell** [comment]
Done: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/ac26fe21011444f5af8fc62fd43d3b54dc773cb6. This can be closed now.

**Comment by SpacePossum** [comment]
:+1:  thanks all :)
