### ISSUE TITLE
Fixer update PHP annotation (SF2 routing)

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#1155]
Here is the diff before / after:

```diff
 /**
  * @Route("/account")
  * @Template()
+ *
  * @Method("GET")
  */
 class UserController extends Controller
```

**Comment by stof** [comment]
I think this is the same root cause than #1147: The fixer treats ``@Method("GET")`` as if it was the ``@method`` phpdoc rather than a complex annotation.

**Comment by keradus** [comment]
@lyrixx Please see #1204 ;)

**Comment by keradus** [comment]
Closing due to merge of #1204

**Comment by lyrixx** [comment]
Thanks
