### ISSUE TITLE
Lowercasing namespace ?

### ISSUE THREAD

**Issue by ptcong** [FriendsOfPHP/PHP-CS-Fixer#1161]
I'm using laravel 5, all classes stored in *app/*, and its namespace is *App*. I want to keep the folder name lowercase, but namespace with SuddlyCase. 
In composer i have 
```
"psr-4": {
			"App\\": "app/"
		}
```
But after run phpcsfixer with PSR-2, namepsaces become to *app*, it seem not ok.
Is it right ? 
Is possible if i don't want to change *app* folder or namspace to other name ?

**Comment by keradus** [comment]
Hi. PSR0 force you to name dir 1-1 as you name a namespace, ant PSR2 follows PSR0, that is why you see that change.
If you really don't want to follow PSR0 dictation and PSR4 recommendation just disable PSR0 fixer

**Comment by stof** [comment]
@keradus in this case, the code is following PSR-4

**Comment by GrahamCampbell** [comment]
It's because the folder is app and the namespace is App.

**Comment by GrahamCampbell** [comment]
In L5 apps, you are meant to change the namespace to something more appropriate anyway.

**Comment by keradus** [comment]
@stof in PSR4 it is only a recommendation, I agree. It is only a hard rule for PSR0. Therefore, if one breaks PSR0 he should consider disabling PSR0 fixer, didn't he ? :)

**Comment by stof** [comment]
@keradus the (unsafe) PSR-0 fixer is enabled by default, and many people are not aware of that. This is what causes most issues.

**Comment by xroot** [comment]
even I have added -psr0 to the array passed to fixers function with my .php_cs file I still get the namespace App renamed to app within laravel 5.1 .

**Comment by GrahamCampbell** [comment]
That can't be true. You must be not loading the config file correctly.

**Comment by xroot** [comment]
this is my .php_cs file <br />
```
<?php

    $finder = Symfony\CS\Finder\DefaultFinder::create()
        ->exclude('vendor')
        ->exclude('tests')
        ->exclude('storage')
        ->exclude('resources')
        ->exclude('public')
        ->exclude('database')
        ->exclude('config')
        ->exclude('bootstrap')
        ->in(__DIR__)
    ;

    return Symfony\CS\Config\Config::create()
        ->setUsingCache(true)
        ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
        ->fixers(array(
            '-psr0',
            'blankline_after_open_tag',
            'braces',
            'concat_without_spaces',
            'double_arrow_multiline_whitespaces',
            'duplicate_semicolon',
            'elseif',
            'empty_return',
            'encoding',
            'eof_ending',
            'extra_empty_lines',
            'function_call_space',
            'function_declaration',
            'include',
            'indentation',
            'linefeed',
            'join_function',
            'line_after_namespace',
            'list_commas',
            'logical_not_operators_with_successor_space',
            'lowercase_constants',
            'lowercase_keywords',
            'method_argument_space',
            'multiline_array_trailing_comma',
            'multiline_spaces_before_semicolon',
            'multiple_use',
            'namespace_no_leading_whitespace',
            'no_blank_lines_after_class_opening',
            'no_empty_lines_after_phpdocs',
            'object_operator',
            'operators_spaces',
            'parenthesis',
            'remove_leading_slash_use',
            'remove_lines_between_uses',
            'return',
            'self_accessor',
            'short_array_syntax',
            'short_echo_tag',
            'short_tag',
            'single_array_no_trailing_comma',
            'single_blank_line_before_namespace',
            'single_line_after_imports',
            'single_quote',
            'spaces_before_semicolon',
            'spaces_cast',
            'standardize_not_equal',
            'ternary_spaces',
            'trailing_spaces',
            'trim_array_spaces',
            'unalign_equals',
            'unary_operators_spaces',
            'unused_use',
            'visibility',
            'whitespacy_lines',
        ))
        ->finder($finder);
    ?>
```

**Comment by xroot** [comment]
its placed in the root of the application

**Comment by GrahamCampbell** [comment]
What command are you running though?

**Comment by GrahamCampbell** [comment]
Also, why are you enabling fixers already enabled by the psr2 level?

**Comment by xroot** [comment]
Thanks for your response , check the screenshot , also tell me the best configuration I can use , I was following an article and I have used their .php_cs file configuration, I have no idea what I have enabled or not 
![screen shot 2015-08-26 at 22 44 56](https://cloud.githubusercontent.com/assets/2453950/9507204/69e7d480-4c44-11e5-93d1-b73e065562ec.png)

**Comment by GrahamCampbell** [comment]
Yeh, you must NOT include the "level" argument. Doing that makes php-cs-fixer ignore the config file completely.

**Comment by xroot** [comment]
ok let me remove it and try again :)

**Comment by xroot** [comment]
@GrahamCampbell : Didn't work :(

**Comment by xroot** [comment]
@GrahamCampbell : than it working now

**Comment by keradus** [comment]
So, is everything clear now and ready to close? Or sth is still not working?

**Comment by xroot** [comment]
for me works perfect you can close it . :)

**Comment by gharlan** [comment]
double close? ;)

**Comment by keradus** [comment]
aaaaa, mea culpa :D I saw a lot of discussion and think it's still open :D

**Comment by ptcong** [comment]
Ya, you can close it now.

**Comment by GrahamCampbell** [comment]
It's already closed?

**Comment by BlazeNikhilesh** [comment]
I am facing the same problem. Can you guys help me out? 
How can I configure .php_cs file?
Can I use the file posted by @anouarabdsslm ?

**Comment by ptcong** [comment]
@BlazeNikhilesh  when you use `-psr0` fixer will not automatic rename your class name to equal with filename and also not rename your namespace from `App` to `app`
