### ISSUE TITLE
Issues of `unused_use`, `spaces_cast`

### ISSUE THREAD

**Issue by ptcong** [FriendsOfPHP/PHP-CS-Fixer#1162]
I just use this fixers, but found some problems.
**With unused_use**
```php
<?php
use PDO;
class Database
{
...
    /**
     * Set PDO fetch mode.
     *
     * @param int $mode
     *
     * @return int last mode before changed
     */
    public function setFetchMode($mode)
    {
        $fetchMode = $this->getConnection()->getFetchMode();

        $this->getConnection()->setFetchMode($mode);

        return $fetchMode;
    }
...
}
```
In above code, i don't use PDO class, just used in phpdoc, but this fixer don't remove `use PDO`

**With spaces_cast**
```php
$var = true;
if(!$var) {
}
```
After run this fixer, the code should be come
```php
$var = true;
if(! $var) {
}
```
But nothing happened.

**Comment by GrahamCampbell** [comment]
> After run this fixer, the code should be come

No it shouldn't? The `!` is NOT a cast. Look at our tests.

**Comment by ptcong** [comment]
Ya, i see. but issue [1] is right ?

**Comment by keradus** [comment]
IMO NOT. We are looking for imported classes in phpdoc too, that way when, for example, an annotation rely on imported class it will still work, eg ORM model.
Closing.

In the future please send one issue per one potential bug.
