### ISSUE TITLE
question bug? the change of escaped characters?

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#1166]
I have a method like this that got changed:

``` php 
 protected function getEventAlias($input)
     {
         if (is_object($input)) {
             $input = get_class($input);
         }
 
-        $bits = explode("\\", $input);
+        $bits = explode('\\', $input);
 
         return array_pop($bits);
     }
```

I wonder if in some instances these changes can actually break things if they are not equally functional?

**Comment by sstok** [comment]
They are functionally equal as `'\'` will escape the single quote so they do the same :+1:

**Comment by cordoval** [comment]
:blush: thanks for the quick reaction you rock :metal: @sstok 

:older_man:
