### ISSUE TITLE
Skip fixers question

### ISSUE THREAD

**Issue by sol-hiqdev** [FriendsOfPHP/PHP-CS-Fixer#1171]
I want symfony level but skip some of fixers.
Can I configure to skip some fixers through .php_cs?

**Comment by SpacePossum** [comment]
Yes you can. Hereby a quote from the `readme`

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.8/README.rst

(search for `blacklist` and you should be OK :)  )
-----------------

You can also blacklist the fixers you don't want by placing a dash in front of the fixer name, if this is more convenient,
using ``-name_of_fixer``:

.. code-block:: bash

    php php-cs-fixer.phar fix /path/to/dir --fixers=-short_tag,-indentation

When using combination with exact and blacklist fixers, apply exact fixers along with above blacklisted result:

.. code-block:: bash

    php php-cs-fixer.phar fix /path/to/dir --fixers=linefeed,-short_tag





For question please join the team on https://gitter.im/  :)

**Comment by keradus** [comment]
Closing ;)
