### ISSUE TITLE
Indentation not affecting class level, yet method level works.

### ISSUE THREAD

**Issue by FunTimeCoding** [FriendsOfPHP/PHP-CS-Fixer#1172]
When I fix this:

```php
<?php

class TestMain
{
  public function main()
  {
    echo 'Hello';
  }
}
```

I get this:

```php
<?php

class TestMain
{
  public function main()
  {
      echo 'Hello';
  }
}
```

Note how the `echo 'Hello';` line became properly indented, but not the function head and braces themselves.

**Comment by keradus** [comment]
Thank you for your report!
Anyone willing to fix this ?

**Comment by keradus** [comment]
@FunTimeCoding please take a look at #1205

**Comment by keradus** [comment]
Closing due to merge of #1205

**Comment by FunTimeCoding** [comment]
Thank you very much.
