### ISSUE TITLE
Output exceptions when verbosity level is increased

### ISSUE THREAD

**Issue by evert** [FriendsOfPHP/PHP-CS-Fixer#1176]
I'm getting exceptions on several files (internal error), but I don't see a way to further debug those errors.

I assume that there's an exception being caught, it would be great if I could see it.

**Comment by keradus** [comment]
Yes, they are hidden for end-user.
Please, take a look into [ErrorsManager](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.8/Symfony/CS/ErrorsManager.php)

**Comment by evert** [comment]
Do you have any additional documentation about using that?

**Comment by keradus** [comment]
No (just one that's inside file itself), this is class just to store that info you saw on console.
When I want to debug I just add some dumping in `report` method.

BTW, in 2.x version I would like to have some autogenerated bug reports with all info that is not needed for end-user, but essential to fix it.
