### ISSUE TITLE
Make methods proptected in VisibilityFixer

### ISSUE THREAD

**Issue by evert** [FriendsOfPHP/PHP-CS-Fixer#1177]
Our CS is largely similar to PSR-2 with some differences.

I'd love to re-use this file:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.8/Symfony/CS/Fixer/PSR2/VisibilityFixer.php

Literally the only thing I need to change is that you _must_ omit `public` from methods. I could do this by overriding one method, but because they are all private, I'm required to copy the entire file.

**Comment by keradus** [comment]
:-1:
Firstly, there are internals, not public ones. Outside of the interface. It's not part of API and therefore we don't want to promise their interfaces.
Secondly, I strongly encourage you to not break PSR.

**Comment by evert** [comment]
Thanks for the advice, but I don't really see following PSR-2 as important.

I'm just saying that these files would be even more useful, if we got access to some of them. I ended up copying a lot of it, which was a bit frustrating, and will also be frustrating if these change in the future. A simple change from private to protected makes this a lot more sane.

Why stand in the way of people using your code in ways you didn't anticipate?

**Comment by keradus** [comment]
> A simple change from private to protected makes this a lot more sane.

Changing it is not a simple change and forget it, it is giving a promise that this is interface that we will not change in the future without doing a BC break. And that methods is outside the interface we promise to keep.


> Why stand in the way of people using your code in ways you didn't anticipate?

One may do whatever he want with code, I just want to keep "inner" repo clean and suggest people to use better solutions.

In your case, maybe just use `visibility` fixer as-is, and then run second fixer that removes all `T_PUBLIC` tokens ?

**Comment by evert** [comment]
That could be a decent solution, I will look into it. Thank you!

**Comment by keradus** [comment]
Great ;)
Then just remember to set priority inside `getPriority` method ;)

Ready to close?

**Comment by evert** [comment]
Thanks again, I'll do that.
