### ISSUE TITLE
no_empty_lines_after_phpdocs overwrites single_blank_line_before_namespace

### ISSUE THREAD

**Issue by leofeyer** [FriendsOfPHP/PHP-CS-Fixer#1178]
The `single_blank_line_before_namespace` fixer is overwritten by the `no_empty_lines_after_phpdocs` fixer. The result is no empty line before the namespace declaration:

This works:

```php
<?php

namespace Foo;
```

But this does not:

```php
<?php

/**
 * Copyright
 */
namespace Foo;
```

The single blank line before the namespace is removed. This could maybe solved by running the `no_empty_lines_after_phpdocs` before the `single_blank_line_before_namespace` filter?

**Comment by leofeyer** [comment]
The following patch fixes the issue here (not deeply tested!).

Class `Symfony\CS\Fixer\Symfony\SingleBlankLineBeforeNamespaceFixer`, add in line 45:

```php
    /**
     * {@inheritdoc}
     */
    public function getPriority()
    {
        // should be run after the NoEmptyLinesAfterPhpdocsFixer
        return -10;
    }
```

**Comment by GrahamCampbell** [comment]
Chaning the order is bad because it's getting fixed then unfixed.

**Comment by GrahamCampbell** [comment]
@leofeyer Your phpdoc is wrong. You should be using `/*` style insead of `/**`.

**Comment by leofeyer** [comment]
@GrahamCampbell You are right. Thanks for the heads-up.
