### ISSUE TITLE
OperatorsSpacesFixer fails if type-hinted arguments are passed by reference

### ISSUE THREAD

**Issue by leofeyer** [FriendsOfPHP/PHP-CS-Fixer#1182]
Here's the test code with the correct formatting:

```php
class A
{
    public function ok($name, &$file)
    {
    }
    public function nok($name, SplFileInfo &$file)
    {
    }
}
```

After running the fixer, here's what the code looks like:

```php
class A
{
    public function ok($name, &$file) // <-- still no space between & and $
    {
    }
    public function nok($name, SplFileInfo & $file) // <-- one space between & and $
    {
    }
}
```

Since the behavior is not consistent depending on whether the argument is type-hinted or not, I assume that this is a bug.

**Comment by kim07** [comment]
:+1:

**Comment by gharlan** [comment]
Yes it is a bug. 

We have this token sequence:

```
T_STRING [T_WHITESPACE] '&' [T_WHITESPACE] T_VARIABLE
```

The problem is, the following statement has the same token sequence:

```php
if (MY_CONSTANT & $myVariable) {}
```

And in this statement `&` is a binary operator, so the spaces are correct here.

(Array (`T_ARRAY`) and callable (`T_CALLABLE`) type hints are not affected.)
