### ISSUE TITLE
Link to How to configure a PHPStorm is not working

### ISSUE THREAD

**Issue by rokerkony** [FriendsOfPHP/PHP-CS-Fixer#1183]
Hi guys,
the link to How to configure a PHPStorm on the bottom of Readme file is not working.
I tried all other links in Readme and except PHPStorm are all fine.

**Comment by SpacePossum** [comment]
Thanks for reporting. 
I don't know why or how long the blog site over at `arnolog.net` is down. In the mean time this one might work: http://tzfrs.de/2015/01/automatically-format-code-to-match-psr-standards-with-phpstorm/?
It would be nice to have some docs over @ http://cs.sensiolabs.org/ for this :)

**Comment by keradus** [comment]
Closed due to merge of #1202
