### ISSUE TITLE
Method argument list must be one per line, fixer missing?

### ISSUE THREAD

**Issue by rokerkony** [FriendsOfPHP/PHP-CS-Fixer#1184]
Hi guys, 
is there a fixer for this psr2 rule? Especially last part with the must statement.

`Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line.`

Exactly first code should be changed to the second:

``` php
public function aVeryLongMethodName(
    ClassTypeHint $arg1, &$arg2, array $arg3 = []
) {
```

``` php
public function aVeryLongMethodName(
    ClassTypeHint $arg1,
    &$arg2,
    array $arg3 = []
) {
```

**Comment by keradus** [comment]
There is no such a fixer yet. But it would be cool to have it!
Do you want to help with creating it?

**Comment by rokerkony** [comment]
ok,
working on it :)
https://github.com/rokerkony/PHP-CS-Fixer/tree/feature-new-fixer-oneline-method-argument

**Comment by keradus** [comment]
Cool to hear that!
You can open PR with WIP flag before finishing the work to get quick response

**Comment by rokerkony** [comment]
Hi, do I have rights to mark PR as WIP? I can't see any possibility to change labels.

**Comment by SpacePossum** [comment]
I don't think you can. You can update the title of a PR you've opened and at '[wip]' in front of it. Little workaround that is accepted :)

**Comment by julienfalque** [comment]
Closing as #2440 was merged.
