### ISSUE TITLE
NoEmptyLinesAfterPhpdocsFixer conflicts with SingleBlankLineBeforeNamespace

### ISSUE THREAD

**Issue by slavcodev** [FriendsOfPHP/PHP-CS-Fixer#1188]
It would be nice if you increase priority for `NoEmptyLinesAfterPhpdocsFixer`, so that it is executed before.
Because now it conflicts with `SingleBlankLineBeforeNamespace` and remove blank line after File-level docblock and before namespace.

Thanks.

**Comment by keradus** [comment]
Please provide test case what code is before, what code is after and what should be

**Comment by slavcodev** [comment]
Code before
```php
<?php

/**
 * Demo file.
 */

namespace Acme\Service;
```

Code after
```php
<?php

/**
 * Demo file.
 */
namespace Acme\Service;
```

config of tool
```bash
php-cs-fixer fix ./Service/Demo.php --level=psr2 --fixers=no_empty_lines_after_phpdocs,single_blank_line_before_namespace
```

**Comment by GrahamCampbell** [comment]
This is the 3rd time this has been reported. You comment is wrong. IT MUST be `/*` style, not `/**`. You can't put phpdoc on a namespace...

**Comment by gharlan** [comment]
It isn't a docblock for the namespace, but for the file: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#4-basic-principles

**Comment by GrahamCampbell** [comment]
Hmm, some of our fixers are wrong then.

**Comment by GrahamCampbell** [comment]
the phpdoc to comment fixer is wrong

**Comment by slavcodev** [comment]
@gharlan right :+1:  I'm trying to write docblock for file, followed by blank line and then namespace

**Comment by GrahamCampbell** [comment]
I think that formatting is wrong though.

**Comment by GrahamCampbell** [comment]
The correct formatting would look like this imo: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/ClassLoader/ApcClassLoader.php

**Comment by gharlan** [comment]
> The correct formatting would look like this imo: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/ClassLoader/ApcClassLoader.php

Imo this is not incorrect, but there is no file-level docblock. It is a regular comment. ;)

**Comment by slavcodev** [comment]
@GrahamCampbell what exactly wrong in format that I want? Can you explain more? Do you mean the comment for file should be `/*` style?

**Comment by GrahamCampbell** [comment]
> comment

Yes. "comments" MUST be `/*`. `/**` is NOT a comment, that's special phpdoc.

**Comment by slavcodev** [comment]
So, I don't want to write a comment. I want to write special phpdoc for whole file

**Comment by GrahamCampbell** [comment]
Yeh, that's where php-cs-fixer has made a mess. It's not that the fixers conflict, it's that all our fixers assume that those type of doc are not allowed.

**Comment by slavcodev** [comment]
Yes, I noticed also

- The `header_comment` add blank line between `<?php` and this file docblock w/o `newline_after_open_tag`
- No blank line between this file docblock and use statements block

**Comment by ktomk** [comment]
@GrahamCampbell: According to FIG ([ref](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#4-basic-principles)):

~~~
<?php
/**
 * This is a file-level DocBlock
 */
~~~

there is a file-level DocBlock and many users want a single empty line after it. Normally it is followed by the namespace.

From the many other tickets it looks like some folks over here were eager to highlight that the first comment in the file per the file-comment MUST be with  a single asterisk but that has never been the case with Javadoc and it's derivates like Phpdoc. I fear with so much passion running into details this is now a major blocker to get this fixed straight away? Right now when I want to have cs-fixer watch over my PSR-2 code I don't have any other option than changing the code with a single asterisk comment on top instead of the two I have in the one or other code-base (it's pretty common to have the file-level doc-block comments with two asterisks).

Is the project aware of this problem and what would be advisable to get some traction on this (minor in my eyes) flaw that is eating the single empty line after the file-comment and before the namespace line?

**Comment by GrahamCampbell** [comment]
Yeh, I know, but we don't support that yet. The spec is not accepted anyway, and at it's current rate, I don't think it ever will.

**Comment by ktomk** [comment]
Well, it's accepted practice and from existing specs, totally fine.

Ppersonally I've used both ways in the past, it is just that there is a lot of code with double asterisk and also the empty line before the file comment, no idea where that originates from but it's not an issue with the fixer so I don't care.

Any idea how to bring a solution forward within php-cs-fixer? Maybe hint the first comment as being a file-level comment? As it's common for header comments? I do see the ambiguity, but for namespace and use lines, they normally don't have any doc-block, so this should be easy to detect, isn't it?

**Comment by SpacePossum** [comment]
On the master version of the project both '/*' and '/**'' can be configured and used as header comment (of a file) (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Comment/HeaderCommentFixer.php#L26).
So this will be in for version 2.x. 
Controlling with space around the header, for example 
[PHP open tag]
[white space]
[declare strict statement]
[white space]
[file-header]
[namespace]
[white space]
[class-doc]

etc. is discussed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2062

Feel free to send a PR to fix this :)

**Comment by ktomk** [comment]
Nice. Any plans for a release? Because why patch if it works in master already? :)

**Comment by keradus** [comment]
I really want to have support for PHP 7 (#1119) at least for 2.x, maybe even PHP 7.1 (#2090)

**Comment by keradus** [comment]
@SpacePossum , could we close it as implement on 2.x, or something is missing ?

**Comment by SpacePossum** [comment]
I think a part of the issues raised here are fixed (comment vs. PHPDoc header), others are well described and discussed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2062#issuecomment-231527391
So I think we close this as duplicate.

**Comment by bweston92** [comment]
This just got me too.
