### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#1189]
```
Files that were not fixed due to internal error:
```

I am getting this a lot and have no idea where to locate or troubleshoot

have tried -vvv but the output barely changes, any way to troubleshoot?

**Comment by keradus** [comment]
Try to dump input of https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.9/Symfony/CS/ErrorsManager.php#L58

**Comment by cordoval** [comment]
ok thanks, would be nice to trigger this via a flag no?

**Comment by keradus** [comment]
feel free to send PR

**Comment by cordoval** [comment]
I will troubleshoot if i have time but cannot commit to anything right now :older_man:
