### ISSUE TITLE
Undefined offset: 5 in /vendor/fabpot/php-cs-fixer/Symfony/CS/Fixer/Symfony/PhpdocParamsFixer.php on line 99

### ISSUE THREAD

**Issue by opichon** [FriendsOfPHP/PHP-CS-Fixer#1190]
When running php-cs-fixer on a large bundle I get the error above. I appreciate that this is likely to be caused by an error in the docs, but it is impractical to verify all the docs in a large code base.

Is there anyway for php-cs-fixer to include some indication of where the error occurred? Just the class name would be useful.

**Comment by keradus** [comment]
Please, could you show file which you were trying to fix and your configuration?

**Comment by opichon** [comment]
No I am afraid I cannot. This is the point I am raising in this issue. I cannot give you the file, because it could be one of hundreds in the bundle I am applying php-cs-fixer to. 
I am asking if php-cs-fixer can at least tell me which file is causing the error. Presumably, php-cs-fixer knows which file it is parsing when the error occurs, so if it can report this, I can then review the docs in that file and fix them.

**Comment by keradus** [comment]
That way please take a look at #1189

**Comment by opichon** [comment]
After running php-cs-fixer on each sub-directory in my bundle, it appears that the problems come from the Model/om directory generated by Propel ORM. This directory, of course, contains the largets number of files in the whole bundle. Given that these are generated files, not version-controller, the phpdocs dont matter much.
 
Nevertheless, the error messages output by php-cs-fixer would be much more useful if they would indicate the file where the error occurred.

**Comment by keradus** [comment]
It does:
```bash
$ php php-cs-fixer fix testdir
Fixed all files in 0.325 seconds, 4.750 MB memory used

Files that were not fixed due to errors reported during fixing:
   1) testfile.php
```

**Comment by opichon** [comment]
In my case, no such thing was reported. Instead, it reported a list of files with the message "Fixed all files in ..." -- after quote a few "undefined offset ..." error messages. Perhaps it is fixing the files despite the Undefined offset" errors. But in that case, why are the messages output at all?

**Comment by keradus** [comment]
Maybe it was only a native PHP warning, not an error/exception.
One can make hard debugger by showing each file name when start fixing it, and search when the warn will occur on console.
Don't know how to help more without knowing the codebase on which that warn appears :(

**Comment by keradus** [comment]
@opichon 
Could you out #1210 ? With it you should be able to have that report.
After that you will know wich file is cousing the notice/error and we can work on that bug

**Comment by keradus** [comment]
Closing after the dead of the discussion
