### ISSUE TITLE
Unalign double arrow is not in the Symfony CS?

### ISSUE THREAD

**Issue by Anahkiasen** [FriendsOfPHP/PHP-CS-Fixer#1194]
I see the `unalign_double_arrow` fixer is listed at being `symfony` level, however the [actual document](http://symfony.com/doc/current/contributing/code/standards.html) makes no mention of this rule. Shouldn't it be part of the `contrib` level?

**Comment by keradus** [comment]
Hi!
This rule is part of Symfony's CS guide, it's hidden here:
> Imitate the existing Symfony 

Be aware that any fixer on Symfony's level is not placed in that level without coordination with Symfony itself. Also, all fixers on Symfony's level (like unalign fixers) are checked on all Symfony's PRs (take a look at Symfony's `.php_cs` file)

**Comment by GrahamCampbell** [comment]
@Anahkiasen Yeh, this is definitely part of symfony. Someone from sensio labs even contacted me to ask me what I thought about that rule, and they got back to me later saying they'd decided to make all array not aligned in symfony.
