### ISSUE TITLE
[2.0] Make Fixers Final

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1200]
What do people think about making the fixer classes final on the master branch?

**Comment by SpacePossum** [comment]
Is this to stop people from extending the fixers or is there another reason (benefit) to do this?

**Comment by GrahamCampbell** [comment]
The fixers aren't meant to be modified through extension. That's why we have them full of private methods, not protected methods. We have some public methods needed for php 5.3 compat, and people seem to be trying to change things through that design floor. I think we should make the classes final to make it clear that they're not designed for that, and it also allows us to make breaking changes to methods that appear public but aren't meant to be.

**Comment by keradus** [comment]
:+1:

BTW, [blogpost](http://ocramius.github.io/blog/when-to-declare-classes-final/) by @Ocramius

**Comment by SpacePossum** [comment]
Thank you for your POV on this @GrahamCampbell :)

**Comment by SpacePossum** [comment]
( @keradus maybe put this one on the 2.0 Milestone ? )

**Comment by keradus** [comment]
Totally for it :+1:

**Comment by GrahamCampbell** [comment]
How far off 2.0 are we? This would be something better applied close to the release date.

**Comment by keradus** [comment]
[That far.](https://github.com/FriendsOfPHP/PHP-CS-Fixer/milestones/v2.0)

Not so tough to do it now - just need to add a test for every fixer that check if fixer is final ;)

**Comment by GrahamCampbell** [comment]
Yeh, sounds like a good idea. :)

**Comment by keradus** [comment]
Would you be so kind and help with it ? :)
That would be really great!

**Comment by GrahamCampbell** [comment]
Should be quite a fast one to do. Can send a PR if you like?

**Comment by keradus** [comment]
That would be great ;)

**Comment by GrahamCampbell** [comment]
PR incoming. I've not tried these tests locally, so we'll see what happens. :)

**Comment by keradus** [comment]
Thanks ;)
