### ISSUE TITLE
[Proposal] Don't use the minor version number in the main development branch

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#1203]
Using a branch named ``1.9`` means that as soon as you release the minor version, all PRs need to be changed to target ``1.10`` (and so on).
This also means that any branch which still has PRs targetting it cannot be removed, increasing the number of useless branches in the repo.

I suggest using a single ``1.x`` branch for the 1.x development (as done in Twig), allowing to release minor versions as often as you want without creating a mess with branches

**Comment by gharlan** [comment]
:+1:

**Comment by keradus** [comment]
What about having bugfixes for latest stable `1.x` and merging new features for new dev `1.x` at same time ?

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
`1.x` seems like a bad name for a branch. How does composer know what minor version it's associated with when you ask for `1.10.*@dev`?

**Comment by GrahamCampbell** [comment]
@keradus Is has a good point in that we're maintaining the current minor release along side the upcoming minor release, and the next major release at the same time. That's 3 versions, not just 2.

**Comment by gharlan** [comment]
Some ideas:

master, 1.x, 1.8
or
master, next, current
or
master, features, bugfixes
or
...

The goal is to have one feature branch that is not changed after a new 1.(x+1) release.

**Comment by GrahamCampbell** [comment]
I think our current branching system is just fine.

**Comment by GrahamCampbell** [comment]
We just release more frequently than say, symfony.

**Comment by gharlan** [comment]
> We just release more frequently than say, symfony.

That is the reason, why I would like to change the branching system. ;)
Symfony is using the same system like we do here at the moment.

**Comment by keradus** [comment]
Goal is great!
But... following Twig is a little to less for us (after @GrahamCampbell) and I dislike idea of naming current stable as `stable`, `bugfixes` etc, not so cute as simply version and need little more fun with composer (again, as @GrahamCampbell told).
I need to think deeper about it ;)

**Comment by gharlan** [comment]
> I need to think deeper about it ;)

Yeah, there's no hurry. ;)

**Comment by keradus** [comment]
Just don't stop discussion because of it ;P

**Comment by SpacePossum** [comment]
I like @stof proposal, but maybe I need to think about it deeper as well.

For example:
>How does composer know what minor version it's associated with when you ask for 1.10.*@dev?

wouldn't this be possible through tags?

**Comment by keradus** [comment]
> wouldn't this be possible through tags?

aren't tags work for `@stable` only ?

**Comment by gharlan** [comment]
Afaik Composer would handle a `1.x` branch like `1.x-dev`.
And this could be aliased as `1.9.x-dev` etc.

https://getcomposer.org/doc/articles/aliases.md#branch-alias

> You may also alias a comparable version (i.e. start with numbers, and end with .x-dev), but only as a more specific version. For example, 1.x-dev could be aliased as 1.2.x-dev.

(I'm not sure if that would work..)

**Comment by GrahamCampbell** [comment]
> And this could be aliased as 1.9.x-dev etc.

You can't alias `1.x` because it's already a valid version.

**Comment by GrahamCampbell** [comment]
`1.9` branch is treated as `1.9.x-dev` by packagist.

**Comment by keradus** [comment]
by composer too

**Comment by gharlan** [comment]
> You can't alias 1.x because it's already a valid version.

Hmm, did you read the citation above?

**Comment by gharlan** [comment]
Another idea, something like:

2.0
master (alias to 1.9.x-dev)
1.8

**Comment by GrahamCampbell** [comment]
@gharlan Yeh, that might be a better model actually.

**Comment by GrahamCampbell** [comment]
> Hmm, did you read the citation above?

It looks wrong to me - I tried to alias a branch named 1.x fairly recently to see what happened, and it didn't work.

**Comment by gharlan** [comment]
> I tried

When? It should be possible since January: https://github.com/composer/composer/pull/3480

**Comment by GrahamCampbell** [comment]
Not a composer issue - it was a packagist issue. Packagist was listing it aliased incorrectly.

**Comment by GrahamCampbell** [comment]
Composer reads data from packagist doesn't it?

**Comment by keradus** [comment]
I think all solutions have some shortcomings.
I decided to leave it as is to have no need to aliasing the branches.
IMO the best way to manage branches is simply do not allow PR to hang too long.

Thank you all for discussion.
