### ISSUE TITLE
[Question] Do we want to exit with non-zero if invalid files were detected prior to fixing?

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1211]
Question: do we want to exit with non-zero if invalid files were detected prior to fixing?

If we do, one of possible solution is #1179 (thanks to @localheinz)

The discussion was tricky and brings no consensus so far.

If I get it right...
:+1: by @localheinz, @SpacePossum, @GrahamCampbell, @dericofilho, @fabpot 
:-1: by @keradus, @gharlan

Any other thoughts?

// cc @fabpot @Seldaek @stof @sstok @ceeram @dericofilho

**Comment by dericofilho** [comment]
@keradus thanks for inviting to have a say on that. My opinion is :+1: 

Rationale: Return codes can mean many things. Unix tradition says 0 is success, anything else is failure - but it does not offer a convention of meaning of codes. I would suggest along the lines:

0 - Perfect Success
-1 - Some linting failed before fix
-2 - Some fixer failed during execution
(by virtue of powers of two it also means that)
-3 - Some linting failed before fix _and_ some fixer failed during execution.

Any statistic of success or failure, which would explain the -1 or -2, could be redirected to stderr (or the current standard in PHP CS Fixer).

**Comment by fabpot** [comment]
If we go down this road (which I like), we should not use random return values as they have pre-defined meaning. See http://www.tldp.org/LDP/abs/html/exitcodes.html for instance.

**Comment by localheinz** [comment]
@keradus 

I really appreciate you opening up this issue, this really made my day today . . . !

**Comment by dericofilho** [comment]
@fabpot These codes are meaningful for bash. I dispute their validity for this kind of application. But, if any other more compatible standard is available, I am for it.

**Comment by keradus** [comment]
> I really appreciate you opening up this issue, this really made my day today . . . !

As I told before @localheinz , I do really appreciate all ideas and I am willing to merge them if we all, as a community, want it - even if I, personally, wouldn't like it. It is just better to figure it out what we want, especially when we have different opinion, before coding it down ;)
Really happy to see #1179 opened!

**Comment by keradus** [comment]
> If we go down this road (which I like), we should not use random return values as they have pre-defined meaning. See http://www.tldp.org/LDP/abs/html/exitcodes.html for instance.

@fabpot That is why we won't use `1` and `2` exit code, they are reserved. Sadly, I wont find any nice standarized codes for our case (even under Windows' exit code list). So we just use non-reserved ones.

**Comment by keradus** [comment]
Very well, then I think we have a decision.
One thing that is left it to think about returning exit status codes.

**Comment by SpacePossum** [comment]
:+1: happy to see this is getting forward!

**Comment by localheinz** [comment]
@keradus @dericofilho @fabpot @SpacePossum 

I'm ready to update the PR whenever you have decided on a suitable exit code!

**Comment by dericofilho** [comment]
@localheinz I defer to @keradus decision.

**Comment by keradus** [comment]
I think we should not use reserved exit status (like `1` or `2`).

What about using bit flags? Then everyone can check both if sth was fixer and if some input files was invalid. What do you think?

--------------------------

It could be sth like:
set `4` for invalid files
set `8` for fixed files

```php
<?php

$changed = true;
$invalid = true;

$exitStatus = 0;

if ($invalid) {
    $exitStatus |= 4;
}

if ($changed) {
    $exitStatus |= 8;
}

return $exitStatus;
```

**Comment by localheinz** [comment]
Any news on this one? Would be awesome if this could make it into `2.0`!

**Comment by GrahamCampbell** [comment]
@keradus I like that approach, provided we define constants for those statuses.

**Comment by keradus** [comment]
Then I think we reached an agreement here ;)

**Comment by SpacePossum** [comment]
cool, lets go for it! :)

**Comment by nesl247** [comment]
My opinion probably doesn't matter, but I personally don't want anything but an exit code of 0 when it fixes things. The entire purpose of the tool (in my opinion) is to fix things. Thus if it works, why is it showing a failure state?

**Comment by keradus** [comment]
Thank you for your opinion. Every opinion does matter.
After #1179 we return 0 on non-dry run and different statuses in dry run (when everything is ok, sth need to be fixed, sth is invalid at the start).
I think this is the best compromise we could achived here.

**Comment by nesl247** [comment]
That's perfect then.

**Comment by keradus** [comment]
But be aware of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1179#discussion_r33547538 .
But still no problem. If you really want to try fix files with syntax and don't have fail status on normal run on that files just disable linter.
But I strongly discourage you to do that...
