### ISSUE TITLE
PHP-CS-Fixer should not remove $variables in comments

### ISSUE THREAD

**Issue by opennota** [FriendsOfPHP/PHP-CS-Fixer#1213]
php-cs-fixer 1.8 "fixes" the following file by removing `$user` and the preceding space:

```
<?php
/**
 * @var string = $user->login
 */
?>
```

The result of running `php-cs-fixer fix`:

```
<?php
/**
 * @var string =->login
 */;
```

```
$ php-cs-fixer --version
PHP CS Fixer version 1.8 by Fabien Potencier (93c723f)
```

**Comment by GrahamCampbell** [comment]
That's because your phpdoc there is totally invalid.

**Comment by GrahamCampbell** [comment]
The following is valid:

```php
<?php

class User
{
    /**
     * The login details.
     *
     * @var string
     */
    public $login;
}
```

**Comment by opennota** [comment]
@GrahamCampbell 
So what exactly the fixer tried to do with this phpdoc?

**Comment by GrahamCampbell** [comment]
> So what exactly the fixer tried to do with this phpdoc?

Your "phpdoc" is invalid, so the results are undefined. If you want it to be a "comment", then you need to start it with `/*` instead of `/**`. The two are not the same.

**Comment by opennota** [comment]
> Your "phpdoc" is invalid, so

So the fixed should either fix it, or leave it alone.

**Comment by GrahamCampbell** [comment]
> So the fixer should either fix it, or leave it alone.

No, I disagree. We can't fix something that's total rubbish.

**Comment by GrahamCampbell** [comment]
NB, the fixer doing this is `phpdoc_var_without_name`, so you can disable it if you don't like it.

**Comment by opennota** [comment]
@GrahamCampbell
> NB, the fixer doing this is phpdoc_var_without_name, so you can disable it if you don't like it.

Thanks, that will do me.
