### ISSUE TITLE
Hacklang CS Fixer?

### ISSUE THREAD

**Issue by skyzyx** [FriendsOfPHP/PHP-CS-Fixer#1215]
Is there an interest in, or work underway to, implement support for Hack in addition to PHP?

**Comment by GrahamCampbell** [comment]
I doubt this will ever happen. We've already discussed dropping support for HHVM at all as it is.

**Comment by keradus** [comment]
:-1: too.
hack is different language

**Comment by funivan** [comment]
:-1:

**Comment by sstok** [comment]
:-1:

**Comment by keradus** [comment]
Closing due to discussion.
Sorry
