### ISSUE TITLE
RuntimeException is thrown when invoked via Composer scripts

### ISSUE THREAD

**Issue by raphaelstolt** [FriendsOfPHP/PHP-CS-Fixer#1218]
When fixes are applied to the code base via a Composer script the following error / exception bubbles up:
```bash
$ composer cs-fix .
Loaded config from "/Users/stolt/Work/git-forks/foobar/./.php_cs"
   1) src/Foo.php
Fixed all files in 8.121 seconds, 8.500 MB memory used
Script php-cs-fixer fix handling the cs-fix event returned with an error



  [RuntimeException]
  Error Output:



cs-fix [--dev] [--no-dev] [args1] ... [argsN]

```
When no fixes are applied the script runs w/o any errors.

The following excerpt shows the relevant composer json entries:
```json
"require-dev": {
  "phpunit/phpunit": "4.6.*",
  "mockery/mockery": "0.9.*",
  "fabpot/php-cs-fixer": "^1.8"
},
"scripts": {
  "cs-fix": "php-cs-fixer fix"
}
```
I also tried multiple variants (e.g. `php-cs-fixer fix .`, `php-cs-fixer fix`, and `php-cs-fixer fix . --config-file=.php_cs`) for the `cs-fix` script configuration, all resulting in the same error message. 

PHP version of the host system is `5.4.11` and Composer is at version `69210d5bc130f8cc9`.

**Comment by keradus** [comment]
inside `composer.json`:
```
    "scripts": {
        "cs-fix": "php-cs-fixer fix . -vv"
    },
```

calling from console:
`composer cs-fix`

-----------------------------

The above is working like a charm.
Tested on
```
PHP 5.6.3 (cli) (built: Nov 12 2014 17:18:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
```
and stable PHP CS Fixer v1.7 version. (even before 1.8 :D)

Do you have a repo with that problem anywhere public ?

**Comment by raphaelstolt** [comment]
Still faulting for me, even in `-vv` mode. 

Yeah trying it to get it running with / from the `composer.json` of [Construct](https://github.com/jonathantorres/construct).

**Comment by keradus** [comment]
Could you open a PR with changes into composer.json / composer.lock please ?

**Comment by raphaelstolt** [comment]
Created a [branch](https://github.com/raphaelstolt/construct/tree/composer-scripts-phpcs) on my fork.

**Comment by keradus** [comment]
In that project in composer.lock there is no php-cs-fixer installed.
Therefore when you run composer's script it don't find it.

**Comment by keradus** [comment]
When I run `composer update` it install `PHP CS Fixer` and your script command start working

**Comment by raphaelstolt** [comment]
Ok did also a `composer update` and also pushed latest `composer.lock` into branch of fork. Did your script command run fix coding style violations? Error does only bubble up (for me) when some are found otherwise not.

**Comment by raphaelstolt** [comment]
Tried it on another machine, same problemo.

```bash
PHP 5.6.0 (cli) (built: Aug 31 2014 02:33:55)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

**Comment by keradus** [comment]
I got the reason, please wait a sec

**Comment by keradus** [comment]
So.
For 1.x line in fix-mode (no `--dry-run` flag) we return `0` when every file is OK and `1` when fixer changed anything.
On 2.x line in fix-mode we always return 0 (thanks to https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/398cccac72b10edde1ef8fb4ff0aaeb4280cc401).
As we changed exit status it changed the interface so it went to 2.x line, which is not stable yet.

What I can propose for you is to wait for 2.x@stable or use experimental 2.x@dev.

**Comment by raphaelstolt** [comment]
Ok than I'm waiting for the 2.x@stable. Thanks for the effort.

**Comment by phofmann-trust** [comment]
Workaround:

    "scripts": {
        "cs-fix": "php-cs-fixer fix . -vv || /bin/true"
    },

**Comment by raphaelstolt** [comment]
@phofmann-trust Works like a charm. :+1:

**Comment by jonsa** [comment]
I know this i closed but I'm just adding for reference since this was on the top 5 of my googling for
```composer script runtime exception```

Using the hints above I came up with this on Windows.
```json
"scripts": {
    "cs-fix": "php-cs-fixer fix . -vv || php -r \"return 0;\""
}
```

But this should probably be done on composer level and I've open a [feature request](https://github.com/composer/composer/issues/5281) to see what can be done.
