### ISSUE TITLE
unused_use Fixer not detecting unused uses.

### ISSUE THREAD

**Issue by bskart** [FriendsOfPHP/PHP-CS-Fixer#1228]
In the following minimised example i would expect that FooBaa\Baa\Foo is unused and gets removed. But it does not happen, the regular expression falsely detects Foo to be used.

```php
<?php

namespace FooBaa;

use FooBaa\Baa\Foo;

class Baa
{
    public function buildResponse()
    {
        return ['foo' => 'baa'];
    }
}
```

In this example it works to detected that FooBaa\Foo is unused and removes it:

```php
<?php

namespace FooBaa;

use FooBaa\Foo;

class Baa
{
    public function buildResponse()
    {
        return ['foo' => 'baa'];
    }
}
```

**Comment by keradus** [comment]
Please see #1254

**Comment by bskart** [comment]
Sorry missed the answer for some time, Yes those tests replicate my problems.

Probably not that easy to solve with only regex.

**Comment by keradus** [comment]
Closing due to #1254 discussion.
It's better to have false negative (not fix everything) instead of false positive (fix too much)
