### ISSUE TITLE
Proposal: Multiples files parameters

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1230]
Could be awesome to run php-cs-fixer on some selected files like this:

```bash
php-cs-fixer fix src/path/to/file01.php src/path/to/file02.php src/path/to/file03.php 
```

Any chance to get this feature?

Thanks.

**Comment by GrahamCampbell** [comment]
You can do this by configuring a .php_cs file.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Yes. But this not what I want to do. :-)

I use php-cs-fixer on a script with dynamic files so I have to pass it as arguments.

**Comment by gharlan** [comment]
> Could be awesome to run php-cs-fixer on some selected files like this

:+1:

**Comment by Strate** [comment]
:+1:

**Comment by maZahaca** [comment]
:+1: Cool feature. Waiting for it!

**Comment by funivan** [comment]
:+1:

**Comment by keradus** [comment]
Closing due to #1903
