### ISSUE TITLE
namespace capitalization

### ISSUE THREAD

**Issue by FunTimeCoding** [FriendsOfPHP/PHP-CS-Fixer#1236]
When I fixed my project
```php
namespace FunTimeCoding\PhpSkeleton\Test\Unit\Framework;
```
became
```php
namespace FunTimeCoding\PhpSkeleton\test\Unit\Framework;
```
even though my comopser.json says
```json
    "autoload": {
        "psr-4": {"FunTimeCoding\\PhpSkeleton\\": "src/"}
    },
    "autoload-dev": {
        "psr-4": {"FunTimeCoding\\PhpSkeleton\\Test\\": "test/"}
    },
```

The t in \Test\ became lower caps, which breaks some tests because helper classes cannot be found anymore.

What would be the correct behavior? Should I restructure my project to better fit PSR?

Example file, with history and everything:

https://github.com/FunTimeCoding/php-skeleton/blob/3744835cdc153c2f8fddcf9923e37296694a1ddb/test/Unit/LanguageExample/HttpRequestMediaWikiWebClientTest.php

**Comment by GrahamCampbell** [comment]
You need to disable the psr0 fixer because you're not using psr0.

**Comment by FunTimeCoding** [comment]
I see. This is also being discussed in #858.

**Comment by FunTimeCoding** [comment]
I specified a config in my project now.

https://github.com/FunTimeCoding/php-skeleton/blob/f656da35f0e98f95d1a203acb7987065eaa99270/.php_cs

Guess that means this issue can be closed?

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by FunTimeCoding** [comment]
Thank you very much.

**Comment by keradus** [comment]
BTW, you don't need to exclude `vendor` dir manually @FunTimeCoding

**Comment by FunTimeCoding** [comment]
Oh, helpful.
