### ISSUE TITLE
echo is not actually function

### ISSUE THREAD

**Issue by fisharebest** [FriendsOfPHP/PHP-CS-Fixer#1237]
From the [PHP documentation](http://php.net/echo),

> echo is not actually a function (it is a language construct), so you are not required to use parentheses with it. echo (unlike some other language constructs) does not behave like a function

In, `FunctionCallSpaceFixer.php`, T_ECHO is included in the list of functions to be fixed.

A consequence is that

`echo ($a == $b) ? 'foo' : 'bar';`

gets fixed to 

`echo($a == $b) ? 'foo' : 'bar';`

To further illustrate that these parentheses are part of the expression, rather than part of the `echo`, note that `echo();` is invalid, since `()` is not a valid expression.

Question: should `echo` (and those other language constructs that do not take parentheses) be included in this fixer?

**Comment by GrahamCampbell** [comment]
What verion?

**Comment by fisharebest** [comment]
```
$ php-cs-fixer --version
PHP CS Fixer version 1.8.1 by Fabien Potencier (c1e28e9)
```

**Comment by GrahamCampbell** [comment]
Looks like a bug to me. :)

**Comment by funivan** [comment]
I create pull request to fix this bug. But there is another solutions. Possible the right way would be to change `FunctionCallSpaceFixer::getFunctionyTokens`  remove `T_ECHO` `T_INCLUDE` and etc.

**Comment by funivan** [comment]
@keradus  in what stage is this issue?

**Comment by keradus** [comment]
ref #1266

**Comment by keradus** [comment]
Closing due to merge of #1266
