### ISSUE TITLE
Disable xdebug speedup 2x or 3x the execution

### ISSUE THREAD

**Issue by Maks3w** [FriendsOfPHP/PHP-CS-Fixer#1239]
When xdebug is disabled the performance of the tool is dramatically better.
Minimum 2x and normally more than 3x better.

I don't know if it possible to automatically disable xdebug from the php script it self. If possible then will be great

**Comment by keradus** [comment]
xdebug is disabled by default.
If one turn it on he want to have it on and I don't think we should change his env locally for time of PHP CS Fixer script run.
And I don't know anyone who has xdebug on as his default setting for whole dev working...

**Comment by GrahamCampbell** [comment]
I agree with @keradus.

**Comment by sstok** [comment]
Maybe just inform that xdebug is enabled? I actually misconfigured this once and started to notice that my data disk was getting a bit full :monkey_face: (due to all profiling data).

**Comment by keradus** [comment]
But what you say is connected with whole PHP things you do, not only PHP CS Fixer.
You want to have that notice on every PHP code you run?

**Comment by keradus** [comment]
Have that said, I have no issue with putting such an notice into PHP CS Fixer, just, personally, don't need it myself ;)

**Comment by SpacePossum** [comment]
maybe on `-vvv` only?

**Comment by GrahamCampbell** [comment]
Including it in a higher up level of verbosity would be better IMO.

**Comment by GrahamCampbell** [comment]
Maybe `-vv`?

**Comment by SpacePossum** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
Is xdebug default activated on Travis? If yes, could be nice to deactivate it with php-cs option or at least, add a note about that on the cookbook.

**Comment by stof** [comment]
yes (except on PHP 7 which is not supported yet by XDebug). But XDebug profiling/debugging is not enabled. Only the better var_dump and error reporting and the code coverage

**Comment by Soullivaneuh** [comment]
> But XDebug profiling/debugging is not enabled.

@stof So we won't get Travis quicker if we disable it, isn't it?

**Comment by stof** [comment]
Well, you could get Travis quicker if you stop collecting code coverage (enabling code coverage adds overhead, much more than just having the extension sitting there). But you would loose some information.

Disabling XDebug entirely (if code coverage is dropped) could make it a bit quicker as well, but not much (especially given the size of the testsuite)
