### ISSUE TITLE
php_cs_fixer_on_save doesn't work

### ISSUE THREAD

**Issue by moon0326** [FriendsOfPHP/PHP-CS-Fixer#1240]
Hi,

Somehow my phpcs plugin stopped working.

I've turned on the debug and this is what I got.

[Phpcs] Linter found 0 errors
[Phpcs] Sniffer found 21 errors
reloading /Users/myuser/Code/laravelkr/app/Http/Controllers/HomeController.php

I have "php_cs_fixer_on_save": true in my config, but somehow the plugin doesn't run it.

How can I fix this?

**Comment by moon0326** [comment]
Sorry, wrong repository;;;

**Comment by keradus** [comment]
yeah
