### ISSUE TITLE
Add support for https for: http://get.sensiolabs.org/php-cs-fixer.version

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1242]
Please add HTTPS support for: http://get.sensiolabs.org/php-cs-fixer.version
It will give a bit more security/trust about the downloaded release :)

ping @fabpot

**Comment by stof** [comment]
Currently, get.sensiolabs.org is hosted as a static website on S3 according to the DNS resolution. S3 does not support custom SSL (they support SSL for their own domain name only). Adding SSL would require using CloudFront on front of the S3.

**Comment by GrahamCampbell** [comment]
> Adding SSL would require using CloudFront on front of the S3.

Or you can use cloudflare for free. :)

**Comment by stof** [comment]
This could be an option too

**Comment by SpacePossum** [comment]
Maybe this one was a bit to `meta` since the community cannot help out here.
