### ISSUE TITLE
Getting I-invalid file syntax if php.exe folder is not included in path (Windows 7)

### ISSUE THREAD

**Issue by jatubio** [FriendsOfPHP/PHP-CS-Fixer#1253]
Hi,

I'm using php-cs-fixer trough one .bat file on windows:

```
"D:\DevApps\PHP5.6.6\php.exe" "%~dp0php-cs-fixer.phar" --verbose fix --config-file=.php_cs
```

On running, i get always:

```
I
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 0.081 seconds, 3.000 MB memory used
```

The problem seems to be that i have not included `D:\DevApps\PHP5.6.6\` folder on windows path variable.

If i include them or change .bat file to:

```
set PATH=%PATH%;"D:\DevApps\PHP5.6.6"
"D:\DevApps\PHP5.6.6\php.exe" "%~dp0php-cs-fixer.phar" --verbose fix --config-file=.php_cs
```

All is working ok.

May be, this old issue it's about same problem: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1191

**Comment by keradus** [comment]
what is the output of `"D:\DevApps\PHP5.6.6\php.exe" "%~dp0php-cs-fixer.phar" --version` ?

**Comment by jatubio** [comment]
It's the last version: ```PHP CS Fixer version 1.8.1 by Fabien Potencier (c1e28e9)```

**Comment by keradus** [comment]
You have not specified path in CLI command, I assume you have `.php_cs` file in that dir ?

**Comment by jatubio** [comment]
I get the same if i run a simple fix (without using .php_cs file) like:

```
"D:\DevApps\PHP5.6.6\php.exe" "D:\DevApps\Phar\php-cs-fixer.phar" --verbose fix "app\Entities\Boletin.php"
```

You can see my .php_cs file here: https://gist.github.com/jatubio/dfbebf73ea79f9f72e02

**Comment by jatubio** [comment]
Yes, i have put .php_cs in the root of my project and running PHP-CS-Fixer
from them.

2015-06-13 13:30 GMT+02:00 Dariusz Rumiński <notifications@github.com>:

> You have not specified path in CLI command, I assume you have .php_cs
> file in that dir ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1253#issuecomment-111701349>
> .
>



-- 
“Lo importante no es llegar al destino. Lo importante es saber disfrutar
del camino.” *Juan Antonio Tubío*

Dá el primer paso para aprender a disfrutar del camino:
http://www.tumasmas.es
LinkedIn: http://es.linkedin.com/in/jatubio

**Comment by keradus** [comment]
Closing due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1146 .
To take advantage of autofinding php executable please use 2.x@dev or wait for it's stable.
If you want to use 1.x stable please add php to your paths or disable linting
