### ISSUE TITLE
[PSR-2] Namespace issues

### ISSUE THREAD

**Issue by camiant** [FriendsOfPHP/PHP-CS-Fixer#1264]
``` php
<?php namespace App\Models;
```

using "--level=psr2", namespace remains on the same first line of "<?php" and namespace "App\Models" becomes "app\Models"

``` php
<?php namespace app\Models;
```

any suggestions?

**Comment by GrahamCampbell** [comment]
It's not a psr-2 rule to move it. It just says that if it is moved, there should be a blank line first.

**Comment by GrahamCampbell** [comment]
Adding this symfony level fixer to the mix should do what you want though: `single_blank_line_before_namespace`.

**Comment by camiant** [comment]
"single_blank_line_before_namespace" doesn't work using level=psr2.. needs
symfony

2015-06-14 23:21 GMT+02:00 Graham Campbell <notifications@github.com>:

**Comment by GrahamCampbell** [comment]
No, I'm saying, you need to enable this fixer yourself...

**Comment by camiant** [comment]
--level=symfony seems to do everything I need.

1) moves namespace on separate line
2) removes unused uses statements
3) puts opening braces on the next line

thanks.

2015-06-14 23:21 GMT+02:00 Graham Campbell <notifications@github.com>:

**Comment by GrahamCampbell** [comment]
I wasn't suggesting using the symfony level, though if it does what you want, that's fine. Please close this.
