### ISSUE TITLE
Align equals only for constant

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1268]
Would be great to have one fixer based on this one: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.10/Symfony/CS/Fixer/Contrib/AlignEqualsFixer.php

But only for constants.

Sample:

``` php
class Foo
{
    const MY_CONSTANT      = 1;
    const ANOTHER_CONSTANT = 2;
    const I_LIKE_IT        = 3;

    public function bar($thing)
    {
        $myThing = $thing;
        $myOtherThing = $thing;
    }
}
```

**Comment by GrahamCampbell** [comment]
And an unalign fixer would be good too. :)

**Comment by keradus** [comment]
IF that could happen then instead of writing second fixer to do part of first one - the first one should be splitted into many that don't make same changes

**Comment by Soullivaneuh** [comment]
> the first one should be splitted into many that don't make same changes

I agree. I will work on that on my next free time with splitting it with BC of course.

> And an unalign fixer would be good too. :)

Yes of course! ;-)

**Comment by Soullivaneuh** [comment]
@keradus is should be done on `1.10` or `master`?

**Comment by keradus** [comment]
> I will work on that on my next free time with splitting it with BC of course.

If you could please try to recreate that fixers based on tokens only.

> is should be done on 1.10 or master?

splitting A into B, C and D on 1.x, then removing A on 2.x

**Comment by Soullivaneuh** [comment]
> If you could please try to recreate that fixers based on tokens only.

What do you mean? Can you provide samples of "good" and "bad" fixers? Thanks.

**Comment by Soullivaneuh** [comment]
@keradus I'm not sur for fixer name.

For constant, I would create a `AlignConstantEqualsFixer` but for the other, I don't know.

Maybe `AlignCodeEqualsFixer`?

**Comment by keradus** [comment]
Align fixer works greatly on code content - https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Contrib/AlignEqualsFixer.php
and it need to reset the code `$tokens->setCode($content);`, which calls whole tokenizer.

Unalign fixer works only on tokens - https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Symfony/UnalignEqualsFixer.php
(no need to call tokenizer!)

**Comment by keradus** [comment]
Closing as a cleanup.
Reason: inactivity and closed state of connected PR.
