### ISSUE TITLE
Suggestion of new feature: Show name and path of invalid files

### ISSUE THREAD

**Issue by jatubio** [FriendsOfPHP/PHP-CS-Fixer#1270]
Hi,

When i get one message like this:

```
D:\Proyectos\Repositorios_Git\Laravel\Salud Digital\sdf>pflaravel -vvv
Loaded config from ".php_cs"
FII
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) tests\functional\boletin\BoletinControllerStoreTest.php (method_argument_space)
Fixing time per file:
[0.002 s] app\Console\Commands\Inspire.php
[0.001 s] app\Console\Kernel.php
[0.001 s] app\Events\Event.php
(...)
```

I can't get the names of 'I' (invalid) files. I tried with `-v`, `-vv` and `-vvv` without results.

Show invalid files would be great.

**Comment by funivan** [comment]
We can see files with errors at the bottom. My command: `./console.php cs:fix --dry-run --diff -vvv`
```
.EI..
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.021 s] Controller/Domains.php
[0.030 s] Controller/SpamRegs.php
[0.018 s] Controller/Banners.php
[0.023 s] Controller/SpamIps.php

Fixed all files in 0.095 seconds, 8.250 MB memory used

Files that were not fixed due to internal error:
   1) Controller/SpamRegs.php
```

Possible it will be better to see all files list with time and statuses. For example
```
[0.021 s] .  Controller/Domains.php
[0.030 s] E  Controller/SpamRegs.php
[0.018 s] E  Controller/Banners.php
[0.023 s] I  Controller/SpamIps.php

```

**Comment by keradus** [comment]
Showing files that didn't changed is pointless to me, why you want to show them ?

**Comment by jatubio** [comment]
Yes, @funivan, i like something like this :)

@keradus, i you think that there is no need to show files that didn't changed, why show the `I` about them? I think it's better have one option to see what files are ignored or don't nothing about them (not even `I`). Now, for example, i have some projects with a lot of files. And, when I run PHP-CS-Fixer on them, I get a `I` in then last file and I'm very curious to know what they are. Since projects seems to run perfectly (Although having one file with 'invalid file sintax').

**Comment by funivan** [comment]
Other way is eventDispathcer. 
We can modify  `FixerFileProcessedEvent ` add information about file to event and allow user to register some listeners from outside. 
```php
$fixCommand = new FixCommand(null, $config);
  $fixCommand->getEventDispatcher()->addListener(FixerFileProcessedEvent::NAME, function (FixerFileProcessedEvent $event) {
    if ($event->getStatus() == FixerFileProcessedEvent::STATUS_INVALID) {
      echo 'Show file info';
    }
  });
```

**Comment by SpacePossum** [comment]
>Showing files that didn't changed is pointless to me, why you want to show them ?

I use it for two reasons:
* timings
* check that all files I want to fix are in and files I won't be fixed aren't (so basically to check if I configured my `Finder`  correctly).

**Comment by keradus** [comment]
OK, I'm convinced

**Comment by jatubio** [comment]
@keradus, Nice! :+1: 

Thank you

**Comment by SpacePossum** [comment]
@funivan
>Other way is eventDispathcer. 
>We can modify FixerFileProcessedEvent add information about file to event and allow user to register some listeners from outside.

cool idea https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1247 ;)

**Comment by lukasoppermann** [comment]
Is this going to be merged? I would really appreciate it.

**Comment by keradus** [comment]
I can see no PR for this request, so nothing to be merged yet.

**Comment by lukasoppermann** [comment]
Sorry. ;) I thought this reference one was a pr.

**Comment by funivan** [comment]
@keradus PR  https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1289
I can close it and create new one, according to your comment https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1289#issuecomment-118792354
Subscribe to events outside of the fixer is good alternative for more verbosity. How do you think, I'm  on the right way?

**Comment by keradus** [comment]
Please see #1247, especially https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1247#issuecomment-111476648
