### ISSUE TITLE
You must call one of in() or append() methods before iterating over a Finder.

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfPHP/PHP-CS-Fixer#1271]
I'm getting error below when running `bin/php-cs-fixer fix`.

 > [LogicException]                                                               
 > You must call one of in() or append() methods before iterating over a Finder.

**composer.json**
```
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/", "SymfonyStandard\\": "app/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "jms/serializer-bundle": "0.13.0",
        "knplabs/knp-paginator-bundle": "2.4.2"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "doctrine/doctrine-fixtures-bundle": "2.2.0",
        "doctrine/data-fixtures": "1.1.1",
        "phpspec/phpspec": "2.2.1",
        "behat/behat": "2.5.5",
        "behat/mink-extension": "1.3.3",
        "behat/mink": "1.5.0",
        "behat/symfony2-extension": "1.1.2",
        "behat/mink-selenium2-driver": "1.1.1",
        "behat/mink-browserkit-driver": "1.1.0",
        "behat/mink-goutte-driver": "1.0.9",
        "guzzle/guzzle": "3.9.2",
        "guzzlehttp/guzzle": "5.0.2",
        "phing/phing": "2.11.0",
        "fabpot/php-cs-fixer": "1.9",
        "squizlabs/php_codesniffer": "2.3.2",
        "coduo/php-matcher": "1.1.6"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.7-dev"
        }
    }
}
```

**Comment by SpacePossum** [comment]
Are you using a custom config file? Typically this message is a result of using a default Finder without a (target) directory set.
(not the best exception message I must say btw.)

**Comment by BentCoder** [comment]
What do you mean by
> Are you using a custom config file?

**Comment by SpacePossum** [comment]
If you run the fixer with the `--config-file` option or with a `.php_cs` file in your project.

**Comment by BentCoder** [comment]
I got you. I just created the file below and it work fine. Thank you the hint.

```
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in('src');

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    ->fixers(['-yoda_conditions', 'short_array_syntax', '-phpdoc_align'])
    ->finder($finder);
```

**Comment by SpacePossum** [comment]
happy to hear it works :+1: :)

**Comment by keradus** [comment]
When you didn't have config file before the you needed to pass dir via
command argument, like `php-cs-fixer fix dir`

**Comment by edrush** [comment]
Is this behaviour only related to Mac? Didn't experience this issue on Windows.

**Comment by besingamkb** [comment]
im getting the same issue. 

```
mbesinga@mbesinga:~/php/calculator$ bin/php-cs-fixer fix 
Loaded config default.
Using cache file ".php_cs.cache".

In Finder.php line 623:
                                                                                 
  You must call one of in() or append() methods before iterating over a Finder.  
                                                                                 

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]

```

**Comment by keradus** [comment]
try the same solution, @besingamkb 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1271#issuecomment-113629828

**Comment by besingamkb** [comment]
@keradus I notice that I have .php_cs.cache so I cp it intoo .php_cs and I got this by running the same command 

`The config file: "/home/mbesinga/php/calculator/.php_cs" does not return a "PhpCsFixer\ConfigInterface" instance. Got: "integer".`

**Comment by keradus** [comment]
of course.. those are 2 different files.... you replace one with another...

**Comment by besingamkb** [comment]
fixed by running this instead. `bin/php-cs-fixer fix .`

**Comment by aryashreep** [comment]
You can fix this by running below command
`vendor/bin/php-cs-fixer fix . --config .php_cs`

**Comment by COil** [comment]
When upgrading to 3.x, you can have the error because the default file is different : it must be now `.php-cs-fixer.dist.php` (I had .php_cs.dist  before).

**Comment by njoguamos** [comment]
> When upgrading to 3.x, you can have the error because the default file is different : it must be now `.php-cs-fixer.dist.php` (I had .php_cs.dist before).

Updated to .php-cs-fixer.dist.php buy still failing. I will investigate further.

**Comment by SpacePossum** [comment]
:+1:  feel free to ask us questions about config setup here https://gitter.im/PHP-CS-Fixer/Lobby as well, might be faster

**Comment by sebastiaanluca** [comment]
> > When upgrading to 3.x, you can have the error because the default file is different : it must be now `.php-cs-fixer.dist.php` (I had .php_cs.dist before).
> 
> Updated to .php-cs-fixer.dist.php buy still failing. I will investigate further.

Same issue here. Upgraded to 2.19, then 3.0. Command fails on 3.0 because it can't find the config file (and without a configuration file, you need to explicitly pass the directory you want to check, resulting in the cryptic error above).

```
$ vendor/bin/php-cs-fixer fix

Loaded config default.

In Finder.php line 611:

  You must call one of in() or append() methods before iterating over a Finder.
```

Can't figure out why it won't read the config file though.

**Comment by VincentMeziane** [comment]
I faced this problem too, after a short research i found this UPGRADE-v3.md file, just rename your file as described and it'll be good 

Rename of files
---------------

| 2.x              | 3.0                      | Description                            |
| ---------------- | ------------------------ | -------------------------------------- |
| `.php_cs`        | `.php-cs-fixer.php`      | Configuration file (local)             |
| `.php_cs.dist`   | `.php-cs-fixer.dist.php` | Configuration file (to be distributed) |
| `.php_cs.cache`  | `.php-cs-fixer.cache`    | Cache file                             |

**Comment by SpacePossum** [comment]
>I'm on PHP CS Fixer 3.0.0-beta.2 

on the linked issue there is this [comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5758#issuecomment-862598496):

> You are using `3.0.0-beta.2` where the new config file name is [not available](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0-beta.2/src/Console/ConfigurationResolver.php#L517-L520), update to `3.0.0` and it will work

please try if that works for you, if not please create a new issue to make it more easy to keep track of outstanding issue, thanks!

**Comment by AmirHoseinBahrami** [comment]
i used custom config and i set value for $routeDirectories that does not exist. fixed it and fixer work correctly.
thanks https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1271#issuecomment-113629828

**Comment by HenkPoley** [comment]
I notice that following the documentation still gives you the `does not return a "PhpCsFixer\ConfigInterface" instance. Got: "integer".` error message.

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/ae7075a0597e66d7f964848d2cab5ba5344d3ab2/doc/config.rst

Maybe the current format is specified somewhere?

**Comment by keradus** [comment]
can you create an example mini-repo that reproduces the issue? i failed to reproduce myself.
if you can reproduce in mini-repo, please raise it and link to it as a separated issue report. thanks!

**Comment by Parkerhiphop** [comment]
> fixed by running this instead. `bin/php-cs-fixer fix .`

Thanks! I solved my CI error with your solution.

**Comment by alimohamedac** [comment]
guys>>
'no_unused_imports' => true, 
doesn't remove anything!!!!

**Comment by icethenet** [comment]
just noticed for me it was it didn't write the config file:  .php-cs-fixer.dist.php in the base_dir of symfony 7.2 If you find this error yourself then just make the file and add this:
```
<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
    ;


return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony'=> true,
    ])
    ->setFinder($finder)
    ;

```
