### ISSUE TITLE
windows php-cs-fixer not working

### ISSUE THREAD

**Issue by johannes-z** [FriendsOfPHP/PHP-CS-Fixer#1276]
I installed php-cs-fixer globally via composer on windows. The file resides in `C:\Users\Johannes\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer`. I'm able to call it in the console via `php-cs-fixer`. I tried a minimal example (see code below) with the following command:

`> php C:\Users\Johannes\AppData\Roaming\Composer\vendor\bin\php-cs-fixer fix test.php`

### Code:
```php
<?php
function add($a,     $b) {
  return $a +$b; }
echo   add(1,2);
```

### Expected Result:
```php
<?php

function add($a,     $b)
{
    return $a + $b;
}
echo   add(1, 2);
```

But it ultimately didn't even touch the file - the code is completely in it's original state. This is the output that is printed after running the command:
```
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd "../fabpot/php-cs-fixer"
BIN_TARGET="`pwd`/php-cs-fixer"
cd "$SRC_DIR"
"$BIN_TARGET" "$@"
```

**Comment by GrahamCampbell** [comment]
Maybe due to line endings?

**Comment by johannes-z** [comment]
I tried CR+LF, LF and CR. No changes though.

**Comment by sstok** [comment]
`C:\Users\Johannes\AppData\Roaming\Composer\vendor\bin\php-cs-fixer` this is the shell version for Linux and the Git terminal,

Try executing `C:\Users\Johannes\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat` (without php at the beginning).

To execute the PHP script: `php C:\Users\Johannes\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer`

**Comment by johannes-z** [comment]
Running the .bat works. Thanks for the help.
