### ISSUE TITLE
Cache Files That Failed Linting

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1290]
Would it not make sense to skip linting files that haven't changed since the last run and failed linting the last time?

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Liniting is relatively expensive. :)

**Comment by localheinz** [comment]
@GrahamCampbell 

Anything speeding up the whole thing is great!

:rocket:

**Comment by keradus** [comment]
It won't speed it much - usually you don't have invalid files in your repo ;)
But yeah, it is a good move ;)

**Comment by SpacePossum** [comment]
:+1: good idea!  :)

**Comment by funivan** [comment]
:+1:

**Comment by keradus** [comment]
Ref #1317

**Comment by keradus** [comment]
Any news on that?

**Comment by keradus** [comment]
Closing due to no interest on that and non trivial implementation that would be both nice for developer and end user.
