### ISSUE TITLE
Cache in a separate directory

### ISSUE THREAD

**Issue by dunglas** [FriendsOfPHP/PHP-CS-Fixer#1291]
Travis only support [caching whole directories](http://docs.travis-ci.com/user/caching/#Arbitrary-directories).

As PHP CS Fixer is often used in dry run mode to check CS in Travis builds, storing the cache in a separate directory will allow to drastically speed up builds.

**Comment by gharlan** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#using-php-cs-fixer-on-travis

But you need 2.0.

**Comment by dunglas** [comment]
I've missed that. Thank you!
