### ISSUE TITLE
phpdoc_to_comment considers anonymous functions as nonstructural elements

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#1300]
According to http://www.phpdoc.org/docs/latest/glossary.html#term-structural-elements a function is a structural element, but phpdoc_to_comment doesn't think so.
For example, it replaces /** with /* in the following code:
```php
/**
 * Returns task snippet.
 *
 * @param Task $task Task model.
 *
 * @return string Task snippet.
 */
$fields['description'] = function ($task) {
    return $task->getSnippet();
};
```

**Comment by GrahamCampbell** [comment]
Yeh, you can't document a closure like that.

**Comment by GrahamCampbell** [comment]
`function` in that link doesn't mean closure.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell I don't see that statement in that link. I see "function" in structural elements collection. And a closure **is** a function.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell btw, my IDE (PhpStorm) is totally OK with generating and understanding DocBlocks for closures.

**Comment by GrahamCampbell** [comment]
> And a closure is a function.

No it's not. It's a callable object.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell so is function.

**Comment by GrahamCampbell** [comment]
> so is function.

No. Objects that are "invokable" are not functions.

**Comment by GrahamCampbell** [comment]
http://3v4l.org/t96cV

**Comment by GrahamCampbell** [comment]
Something is either an object, or a function, but not both.

**Comment by gharlan** [comment]
http://3v4l.org/qSfYo

**Comment by GrahamCampbell** [comment]
It's still not a function.

```
'ReflectionFunction::__construct expects a string or a Closure
```

**Comment by GrahamCampbell** [comment]
Generated if I do this: http://3v4l.org/n8VsR.

**Comment by GrahamCampbell** [comment]
PHP is allowing users to do reflection on closures in this way for ease of use.

**Comment by gharlan** [comment]
> It's still not a function.
> 
> ReflectionFunction::__construct expects a string or a Closure

I don't read " and a Closure is not a function" ??

> PHP is allowing users to do reflection on closures in this way for ease of use.

Where can I read this?

For me an anonymous function is a function. It is represented by an closure object.

**Comment by GrahamCampbell** [comment]
Let's not get bogged down here please, since, it makes f all difference anyway.

My point is that it's a stupid idea to allow documentation like this. Consider the following:

```php
$callbacks = [function () {}, function () {}];
````

How do you document that?

**Comment by keradus** [comment]
I think the correct question here is _how_ to document any closure.

**Comment by gharlan** [comment]
I agree that it can be difficult to add a docblock for some closures.

But why should we prohibit closure docblock where it is possible?

**Comment by GrahamCampbell** [comment]
It's difficult for any closure. It's totally non-obvious what the phpdoc is actually associated with.

**Comment by gharlan** [comment]
And by the way:

```php
$callbacks = [
    /**
     * @param string $a
     **/
    function ($a) {}, 

    /**
     * @param bool $b
     **/
    function ($b) {}
];
```

**Comment by gharlan** [comment]
I wouldn't use that, but imo the fixer should accept it.

**Comment by GrahamCampbell** [comment]
Is this stuff in PSR-5. If not, we shouldn't support it.

**Comment by GrahamCampbell** [comment]
All our phpdoc stuff follows that spec (or needs fixing to do so - headers, etc).

**Comment by gharlan** [comment]
> Is this stuff in PSR-5. If not, we shouldn't support it.

Then we have to clarify if a closure is a function. ;)

**Comment by GrahamCampbell** [comment]
> Then we have to clarify if a closure is a function. ;)

If they don't actually say that closures can be documented, then we should assume not.

**Comment by GrahamCampbell** [comment]
Closures are a special case in all senses.

**Comment by gharlan** [comment]
My opinion: If they don't actually say that closures can not be documented, then we should assume yes, because closures are functions.

I seems we have to wait for some more opinions. ;)

**Comment by GrahamCampbell** [comment]
I'd assume no. Nothing should be assumed.

**Comment by ceeram** [comment]
PSR-5 was the guideline for this fixer. [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#4-basic-principles) states: `A DocBlock MUST directly precede a "Structural Element"`

This means in the following code example the structural element is not the anonymous function but the variable `$fields` (or perhaps even `$fields['desciption']`?):
```
/**
 * Returns task snippet.
 *
 * @param Task $task Task model.
 *
 * @return string Task snippet.
 */
$fields['description'] = function ($task) {
    return $task->getSnippet();
};
```

In the other code example phpdoc does precede the closure, but a closure should not be considered a structural element:
```
$callbacks = [
    /**
     * @param string $a
     **/
    function ($a) {}, 

    /**
     * @param bool $b
     **/
    function ($b) {}
];
```

**Comment by GrahamCampbell** [comment]
> a closure should not be considered a structural element:

Yeh. :)

**Comment by GrahamCampbell** [comment]
So basically, PSR-5 does say that closures cannot have PHPDoc associated with them.

**Comment by EvgenyOrekhov** [comment]
So sad.
