### ISSUE TITLE
PHP7 support? I-invalid file syntax for every file

### ISSUE THREAD

**Issue by rdlowrey** [FriendsOfPHP/PHP-CS-Fixer#1301]
When I try to use the fixer on PHP7 code every file reports as invalid. Is there a timeframe in place for full PHP7 support (or perhaps this is in a dev branch of which I'm unaware)? I'm currently running the 1.9 release.

Thanks for your time.

**Comment by keradus** [comment]
Hi!
We have start adding some support for PHP7 syntax (ref #1119) and have no timeframe for that.
After said that, this is so great that we lint file before chenging it to just ignore files that we do not understand.
