### ISSUE TITLE
Changing The Header Comment Doesn't Flush The Cache

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1305]

**Comment by GrahamCampbell** [comment]
Would you accept https://github.com/StyleCI/PHP-CS-Fixer/commit/fece53088695e5c5d8649d9ed751b8d169a85e28 in a pull request?

**Comment by keradus** [comment]
Nice to catch that!
For me showed solution is hacky one - because it work's only on that one configuration and if we add configuration to other fixers then you will need to do this hack over and over again.
I have in mind bigger change which will solve this as well - but on 2.x line.

**Comment by GrahamCampbell** [comment]
> For me showed solution is hacky one

Yeh, I know. That's why I didn't PR it.

> I have in mind bigger change which will solve this as well - but on 2.x line.

Looking forward to it. :)

**Comment by keradus** [comment]
Closing due to merge of #1383
