### ISSUE TITLE
Add ImportGlobalClassesFixer

### ISSUE THREAD

**Issue by webmozart** [FriendsOfPHP/PHP-CS-Fixer#1309]
I'd like to see a fixer that adds import statements for fully-qualified global classes.

Input:

``` php
class MyClass
{
    public function doSomething()
    {
        $date = new \DateTime();
        // ...
    }
}
```

Output:

``` php
use DateTime;

class MyClass
{
    public function doSomething()
    {
        $date = new DateTime();
        // ...
    }
}
```

**Comment by GrahamCampbell** [comment]
This fixer would have to be marked as risky since it could break the code if it causes a class name conflict with another class in that namespace.

**Comment by Soullivaneuh** [comment]
For PHP native class, some projects use `\` notation.

So I think this should have two fixers: one for vendor classes and one for native PHP classes. Or options for 2.x.

> This fixer would have to be marked as risky since it could break the code if it causes a class name conflict with another class in that namespace.

In case of multiple definition, this should be skipped. Maybe with a warning message.

**Comment by keradus** [comment]
you can't detect if there is class with same short-name but in different namespace

**Comment by SpacePossum** [comment]
>For PHP native class, some projects use \ notation.

for that I would like to have a fixer that does the reverse of the proposed fixer :)

**Comment by Soullivaneuh** [comment]
> for that I would like to have a fixer that does the reverse of the proposed fixer :)

Well, yes and no. For my case, I would like to use @webmozart proposition fixer **only** for vendor classes, not native.

The reverse won't solve my issue AFAIK.

**Comment by keradus** [comment]
btw, how would you like to guess is the class native or just a global defined user class?

**Comment by SpacePossum** [comment]
>you can't detect if there is class with same short-name but in different namespace
>btw, how would you like to guess is the class native or just a global defined user class?

well you could (guessing is always possible ;) ) , but not by looking at the tokens only, you would have to do more SCA kind of stuff which is out of scope of the fixer. So I know this is prop. not going to happen, although it would be nice to have, please ignore my comment :)

**Comment by keradus** [comment]
You can't do that if you don't get whole code.
Ups, I will ignore your comment :D

**Comment by sstok** [comment]
See also https://github.com/StyleCI/StyleCI/issues/550 for my suggestion on detecting classes ;)

**Comment by teohhanhui** [comment]
I'm also interested in the reverse. It should help enforce this rule in the Symfony Coding Standards:

> Add a use statement for every class that is not part of the global namespace.

Or in other words (**my interpretation**, but also obvious from the example and the codebase):

> Never add a use statement and always add a leading backslash for classes in the global namespace.

**Comment by SpacePossum** [comment]
done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4355
