### ISSUE TITLE
Double arrows aren't alligned correctly

### ISSUE THREAD

**Issue by Dgame** [FriendsOfPHP/PHP-CS-Fixer#1310]
Consider this code:
```php
$arr = [
                'foo' => 'bar',
            'quatz'             => 'test'
        ];
```

I would expect that `foo`and `bar` are equally aligned  (on the indentation of `quatz`) and that the double arrows are also equally aligned on the indentation of `quatz`'s double arrow.
But I got this:
```php
        $arr = [
                'foo'           => 'bar',
            'quatz'             => 'test'
        ];
```

edit:
What I would have expected would be this:
```php
$arr = [
	'foo'   => 'bar',
	'quatz' => 'test',
];

```

**Comment by GrahamCampbell** [comment]
That is technically aligned correctly, and this is a duplicate I think.

**Comment by GrahamCampbell** [comment]
It's just not aligned to the minimum possible.

**Comment by Dgame** [comment]
Sorry if that is a duplicate, I probably missed it. Would it be possible to align it to the minimum?

**Comment by gharlan** [comment]
discussion is here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1273

**Comment by gharlan** [comment]
and here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1055
