### ISSUE TITLE
RFC: Allow to fix only modified files

### ISSUE THREAD

**Issue by Strate** [FriendsOfPHP/PHP-CS-Fixer#1325]
The most frequent use-case for fixer is fixing style before commit files. So, it would be really cool, if fixer could detect modified files by itself. Now I should write something like:

```
hg status -n | xargs php-cs-fixer fix --config-file=.php_cs
```
Much better is
```
php-cs-fixer fix --modified
```

**Comment by keradus** [comment]
By modified I assum you meant modified in VCS ? Then the tool need to support git, mercurial, svn etc... and what if there is no VCS?
Then I suggest you to use tools integrated with your VCS like https://github.com/sjparkinson/static-review or https://github.com/sk-/git-lint for local run or fabbot.io / StyleCI for run as a service.

Also, PHP CS Fixer has his own cache to not lint file if it was not changed afted previous fixing.

**Comment by Strate** [comment]
> By modified I assum you meant modified in VCS ?

Yes.

> Then the tool need to support git, mercurial, svn etc... 

Yes, of course :) Implementing it does not seems to be hard.

> and what if there is no VCS?

Throw an error

> or https://github.com/sk-/git-lint 

Looks interesting, thanks!

> Also, PHP CS Fixer has his own cache to not lint file if it was not changed afted previous fixing.

This means that at least one time project should be scanned by the Fixer. For my project it takes for 50 minutes, and it should do every developer in my company.


Of course I can share .sh file, it enough for us, but I just want to make the Fixer better and easier to use for end users.

**Comment by GrahamCampbell** [comment]
We already do this though through caching.

**Comment by GrahamCampbell** [comment]
It's basically the same.

**Comment by GrahamCampbell** [comment]
We only check files changing since the last run.

**Comment by keradus** [comment]
> For my project it takes for 50 minutes, and it should do every developer in my company.

Great (and not, so big project as one repo ;P). Treat it as initial fix, enable cache, fix project, and commit changes. Then - next fix will fix only changed files.

I think idea behind your proposition is good, but we should keep things small and simple - PHP CS Fixer works without repo and it's great, learning it to work with repos indeed, isn't the hardest thing to do. But if there are already so many projects that fulfill this purpose, and do it in better way (eg works not only for PHP) - why not to simply use them ?

**Comment by keradus** [comment]
Next one solution is to use precommit hook, eg https://github.com/zendframework/zf2/blob/release-2.4/README-GIT.md#pre-commit-hook-optional

**Comment by GrahamCampbell** [comment]
Or use a hosted service :trollface:.

**Comment by Strate** [comment]
> Great (and not, so big project as one repo ;P). Treat it as initial fix, enable cache, fix project, and commit changes. Then - next fix will fix only changed files.

There is a few problems.

1. Initial fix. What if code was born in 2007, and almost whole project written when no psr was. Some mainainers do not want to fix whole project, because it could break code.

2. New developer starts to work in a company. He clones repo, and he should to do initial fix. And he should wait 50 minutes for cache warming up.

Both of problems fixed by fixing only modified files.

> we should keep things small and simple

I am agree with you. Really. But I am also think that utility should be a little closer to end user. Maybe we can add some recipes to README file?

**Comment by GrahamCampbell** [comment]
> New developer starts to work in a company. He clones repo, and he should to do initial fix. And he should wait 50 minutes for cache warming up.

Existing users can share their cache with the new ones.

**Comment by funivan** [comment]
You can write tiny script to fix only modified files. For example on bash.
This solution can be implemented in 1 minute.
:-1:

**Comment by gharlan** [comment]
:-1:

**Comment by keradus** [comment]
Closind due to discussion.

@Strate idea itself is great and even we like to fix only modified files. We just think that this could be solved better than inside the tool itself.
