### ISSUE TITLE
Can not beautify selected PHP script

### ISSUE THREAD

**Issue by biji** [FriendsOfPHP/PHP-CS-Fixer#1326]
Dear PHP-CS-Fixer dev,

Would you please help why PHP-CS-Fixer can not beautify selected part of PHP file?

I also reported here:
https://github.com/Glavin001/atom-beautify/issues/453

**Comment by stof** [comment]
I don't know what you mean with "beautify PHP file"

**Comment by keradus** [comment]
You could fix file, you cannot fix selected part of it.
We use tokenizer to analyse code, and it cannot work on random part of it.
