### ISSUE TITLE
[Proposal] Ordering Traits

### ISSUE THREAD

**Issue by vinkla** [FriendsOfPHP/PHP-CS-Fixer#1334]
Lets say I've included two traits within my class and I want to order them by name.

**Before:**

``` php
use SerializerTrait, DispatchesJobs;
```

**After:**

``` php
use DispatchesJobs, SerializerTrait;
```

Don't know if this will be a problem PHP-wise? Otherwise it would make a good feature.

**Comment by stof** [comment]
I think this might change the behavior of the code if 2 traits are defining a method with the same name

**Comment by vinkla** [comment]
If two traits insert a method with the same name, isn't a fatal error is produced? If the conflict is not explicitly resolved?

http://stackoverflow.com/a/25064632/4801875

**Comment by gharlan** [comment]
I would like to see trait equivalents of `MultipleUseFixer` and `OrderedUseFixer` (namespace usages).

```php
use SerializerTrait, DispatchesJobs;

// After MultipleUseTraitFixer
use SerializerTrait;
use DispatchesJobs;

// After OrderedUseTraitFixer
use DispatchesJobs;
use SerializerTrait;
```

**Comment by theofidry** [comment]
Yeah a fatal error is thrown so the order of the traits shouldn't have an impact.

**Comment by keradus** [comment]
:+1: for feature, but it also must support aliasing and resolving conflicts.

**Comment by SpacePossum** [comment]
bit similar but we could also order the interfaces a class implements by name...

**Comment by JarJak** [comment]
Bump

**Comment by ntzm** [comment]
@JarJak the best way of getting this implemented is to have a crack at it yourself! If you need any pointers feel free to as in the Gitter chat

**Comment by SpacePossum** [comment]
added in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4701 by @julienfalque :)
