### ISSUE TITLE
Add PSR-5 link to the CONTRIBUTING.md#projects-standards

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#1335]
phpdoc_to_comment should replace `/**` with `/*` in the following code, but it doesn't:
```php
/** @var Task $task */
$task = $metaGroup[$attr];
```

**Comment by GrahamCampbell** [comment]
No it shouldn't.

**Comment by GrahamCampbell** [comment]
That fixer only fixes phpdoc where it should be a comment.

**Comment by GrahamCampbell** [comment]
Look at the tests.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell phpdoc_to_comment states "Docblocks should only be used on structural elements."
According to http://www.phpdoc.org/docs/latest/glossary.html#term-structural-elements structural elements are:
* namespace
* require(_once)
* include(_once)
* class
* interface
* trait
* function (including methods)
* property
* constant

A variable is not a structural element.
Looks like the tests should be fixed too.

**Comment by GrahamCampbell** [comment]
Hmmmm. Also, we're not using phpdoc.org. That stuff is out of date. We're using their PSR-5 PR.

**Comment by gharlan** [comment]
> We're using their PSR-5 PR.

And there are variables in the list of structural elements: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#3-definitions

**Comment by GrahamCampbell** [comment]
Yeh, so our fixer behaves correcty.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell @gharlan You are right, sorry. Please put this link in the main README.

**Comment by EvgenyOrekhov** [comment]
@GrahamCampbell @gharlan I mean link to the PSR-5.

**Comment by keradus** [comment]
Link to PSR5 in readme? Why?

**Comment by GrahamCampbell** [comment]
Yeh, I don't think this is required. If anyone is interested in what phpdoc standard we're using, they can read the source code of php-cs-fixer. I mentioned it quite a lot in the phpdoc classes we've got.

**Comment by keradus** [comment]
I think we could add it here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/CONTRIBUTING.md#projects-standards

**Comment by EvgenyOrekhov** [comment]
@keradus +1

**Comment by SpacePossum** [comment]
@keradus +1 ;) 

> If anyone is interested in what phpdoc standard we're using, they can read the source code of php-cs-fixer.

Sure, but would it hurt to list it else where as well?
For example people who get to know the tool through http://cs.sensiolabs.org/ won't see the code that fast. Listing the features and standards there would be great for people who are looking around for a CS fixer, lets not make it hard by telling them to look at the code.

**Comment by EvgenyOrekhov** [comment]
@SpacePossum +1, according to John Resig's words, a great user documentation was one of the reasons jQuery became so popular. All other libraries that bit the dust had the "they can read the source code" mind-set.

**Comment by ceeram** [comment]
How about extending the description here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/PhpdocToCommentFixer.php#L81

to something along the lines:
`'Docblocks should only be used on structural elements as defined in PSR-5.'`

**Comment by ceeram** [comment]
btw, the link to phpdoc.org is also used in the [fixer docblock](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/PhpdocToCommentFixer.php#L100) itself. Variables are not separately mentioned in the list on that page, however the examples very well show how to use phpdoc with variables correctly. Imo it would not hurt to document that the fixer will make the code PSR-5 compliant to avoid confusions.

**Comment by GrahamCampbell** [comment]
> btw, the link to phpdoc.org is also used in the fixer docblock itself.

That was a mistake then and needs removing.

**Comment by ceeram** [comment]
Why is that a mistake? its from the same author as PSR-5?

**Comment by GrahamCampbell** [comment]
Yes, but the two specs are actually not the same.
