### ISSUE TITLE
eof_ending extra empty line feed

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#1336]
PHP-CS-Fixer inserts extra line feed at the end of the file if the previous line has a one-line comment.
Input:
```php
<?php
//comment
<-- empty line feed
```
Output:
```php
<?php
//comment
<-- empty line feed
<-- empty line feed
```

**Comment by keradus** [comment]
Is it still occurs on 2.x@dev ?

**Comment by EvgenyOrekhov** [comment]
@keradus you mean the latest commit on the master branch? No, there is no such problem at that version.

**Comment by keradus** [comment]
I thought so, great to hear that!

On 2.x line we have few new transformers that affect all logic about tokens, eg [WhitespacyCommentTransformer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Tokenizer/Transformer/WhitespacyCommentTransformer.php) for comments/docs and it's not trivial to backport it into 1.x line.

Please, use 2.x@dev line or wait for 2.0@stable
