### ISSUE TITLE
is_null fixer

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#1338]
what you think of fixer that changes:

- `is_null($foo)` to  `$foo === null`
- `!is_null($foo)` to `$foo !== null`

I know ZF1 did such change in some past, and `is_null` looks like function call, while the other is just comparison. probably generates less cpu cycles as function call overhead is omitted.

**Comment by keradus** [comment]
Closing as duplicate, please see #1304
