### ISSUE TITLE
Ternary operator - extra spaces

### ISSUE THREAD

**Issue by ffsantos92** [FriendsOfPHP/PHP-CS-Fixer#1342]
Before:
 ```php
$result = ((isset($test)?true:false;
```
After:
```php
$result = ((isset($test) ? true : false;
```
=====================
Before:
```php
$result = ((isset($test)      ? true : false;
```
After:
```php
$result = ((isset($test)      ? true : false;
```
So, the problem is related with extra white spaces removal.

**Comment by keradus** [comment]
Yes, it is that by design: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/TernarySpacesFixer.php#L90

Question here (to all of us) - do we want to change multiple single-line whitespaces into single whitespace?
And leaving multi-line intact

**Comment by gharlan** [comment]
> Question here (to all of us) - do we want to change multiple single-line whitespaces into single whitespace?
> And leaving multi-line intact

I would like it.

**Comment by stof** [comment]
@keradus I think removing useless multi-spaces should be a dedicated fixer

**Comment by keradus** [comment]
yeah @stof, indeed that would be the best solution

**Comment by ffsantos92** [comment]
I agree with @stof.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by r3oath** [comment]
Has this fixer been implemented yet? I couldn't find it initially, but if it hasn't I may write it myself. Sick of jumping into projects where there's mental usage of unnecessary white space.

If I wrote it, it would naturally transform a line such as

`if  ( $something->isTrue()  && $something->isLegit( $var1,   'hello') )  {`

into 

`if ($something->isTrue() && $something->isLegit($var1, 'hello')) {`

**Comment by SpacePossum** [comment]
I don't think this has been done and I think would be welcome :) 

For MD, try the block
```
```php
```

for example

```php
 if ( $something->isTrue() 

&&

 $something->isLegit( $var1, 'hello') ) {
```

**Comment by SpacePossum** [comment]
ping @keradus this has been done, the TernarySpacesFixer will remove extra spaces after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2079
