### ISSUE TITLE
Fixer "Method argument space" and no space after typehint

### ISSUE THREAD

**Issue by JakeFr** [FriendsOfPHP/PHP-CS-Fixer#1343]
Hello,
The fixer "Method argument space" don't add space (if missing) between the type hint and the variable. I try with both 1.10 and 2.*@dev.
```php
function foo(array$bar)
{
}
```
It would nice to fix this sample code.
I can't find an explicit rule about the need for this space in PSR-2 (§4.4) but all the samples have it.
So it could be a new fixer?

**Comment by keradus** [comment]
:+1: for new fixer

**Comment by localheinz** [comment]
:+1:

**Comment by keradus** [comment]
Please, take a look at #1349

**Comment by JakeFr** [comment]
Great! Thanks a lot!
