### ISSUE TITLE
Indentation fixer -  Wrong indentation

### ISSUE THREAD

**Issue by ffsantos92** [FriendsOfPHP/PHP-CS-Fixer#1344]
The issue was reported in StyleCI/StyleCI#534.

Since [StyleCI](https://github.com/StyleCI/StyleCI/) uses PHP-CS-Fixer it's better to reference the issue here.

The problem is when the class' code has an indent of 4 spaces and one method has 5 spaces. The `indentation` fixer just fails to fix these lines with 5 spaces.

**Comment by evert** [comment]
Noticed this too +1

**Comment by keradus** [comment]
Thank you for report. Could you send a PR with fix for that please?

**Comment by keradus** [comment]
Your report @ffsantos92 is no longer accessible. Could you quote full report?

**Comment by GrahamCampbell** [comment]
I closed it on that repo anyway, and expected a full report to have been put here. Seems it hasn't...

**Comment by julienfalque** [comment]
Hi @ffsantos92, I know this issue is pretty old but is it possible for you to somehow check whether #2849 fixes it?
