### ISSUE TITLE
PHP-CS-Fixer Truck Factor

### ISSUE THREAD

**Issue by gavelino** [FriendsOfPHP/PHP-CS-Fixer#1345]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **PHP-CS-Fixer** and obtained a value of **2**.

The developers responsible for this TF are:

Dariusz Rumiński - author of 63% of the files
Graham Campbell - author of 21% of the files

To validate our results, we would like to ask **PHP-CS-Fixer** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **PHP-CS-Fixer**?

(b) Do you agree that **PHP-CS-Fixer** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **PHP-CS-Fixer** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by keradus** [comment]
Hi!
I can see that you post same post to so many repos... we're one of them, cool.

First of all you should consider one aspect for your study - time frame. As you can see at [contributors](https://github.com/FriendsOfPHP/PHP-CS-Fixer/graphs/contributors) page there are different main authors in different frames. Repo has been originally created by Fabien Potencier, then, rewritten by me, then, Graham introduced bunch of new files around one specific goal (PSR5 support). I am also curious about Fabien's TF - he created repo, it wouldn't exists without him, but he let the community to continue to project.

Then, you could also look on the changelog - https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/CHANGELOG.md . There you can see a lot of other contributors, and two mentioned by you may not be the main ones.

----------------------------------

> (a) Do you agree that the listed developers are the main developers of PHP-CS-Fixer?

In some time frame it would be true for sure. But now - I woudn't be so sure. For example my part in the project is mainly administrating it, review proposed changes and merge it. Coding part is very little.

> (b) Do you agree that PHP-CS-Fixer will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

No.

> (c) Does PHP-CS-Fixer have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

In case of lost 2 developers mantioned by you - or any other - I think no. The project has good documentation and great code coverage.

----------------------------------

But, all of that is just my point of view ;)
Closing as not a real issue, but still feel free to further discuss !

**Comment by gavelino** [comment]
Thank you.
