### ISSUE TITLE
Unbalanced parentheses in DocBlock cause error

### ISSUE THREAD

**Issue by samuelwilliams** [FriendsOfPHP/PHP-CS-Fixer#1347]
I found a nice little edge case. If (for whatever reason) a DocBlock has unbalanced parentheses, PHP-CS-Fixer will error out and not be able to process that file. Example: 

[https://gist.github.com/samuelwilliams/ef214991b5d74a203d64](https://gist.github.com/samuelwilliams/ef214991b5d74a203d64)

```php
<?php
/**
 * {@link http://www.ietf.org/rfc/rfc1035.text)
 */
$someVar = 'hello';
```

`php-cs-fixer fix ./TestFile.php --dry-run --diff`

```txt
Fixed all files in 0.158 seconds, 6.500 MB memory used

Files that were not fixed due to internal error:
   1) ./TestFile.php
```

Can this behaviour be reasonably expected? There are legitimate reasons why one would want unbalanced parentheses in one's DocBlock, for instance: `The parameter should be on [0, 10)`.

**Comment by keradus** [comment]
It's not a case when one has unbalanced brackets anywhere in docs, but when one has invalid inline tag.

**Comment by samuelwilliams** [comment]
Fair point. But is this the expected functionality, or should the nature of the error be raised at the end instead of a blanket "nope"?

**Comment by GrahamCampbell** [comment]
I've seen this error before too.

**Comment by keradus** [comment]
See #1425
