### ISSUE TITLE
Can I change the space indentation length?

### ISSUE THREAD

**Issue by rugk** [FriendsOfPHP/PHP-CS-Fixer#1353]
Maybe this is not the right place to ask such a question, but it would still be nice if you could answer me.

Can I change the space indentation length? So can I e.g. use 2 spaces indentation instead of 4?
I've read the Readme but found nothing like this. I just found ways to disable the check completely.

**Comment by GrahamCampbell** [comment]
No. There's no easy way.

**Comment by GrahamCampbell** [comment]
You'd have to disable a few fixers to lot of fixers if you want to use wrong indentation.

**Comment by rugk** [comment]
Okay, thanks for the information.

**Comment by istavros** [comment]
in VSCode I changed `->setIndent("\t")` to `->setIndent("  ")` and I have 2 spaces for indentation.

**Comment by keradus** [comment]
original issue was raised 2 years ago, back then we didn't supported that ;)
