### ISSUE TITLE
Extra spaces fixer

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#1354]
I'd love to have a fixer that removes all extra spaces except for indentation.
Before:
```php
function    sum($a,     $b)      {
    return       $a    +       $b;
}
```
After:
```php
function sum($a, $b) {
    return $a + $b;
}
```

**Comment by keradus** [comment]
You have so many rules here...
For sure it should be done by many fixers - and we already do it (well, maybe not all spaces, but part of it for sure).
Then, we could just have a group with all of that fixers.

**Comment by EvgenyOrekhov** [comment]
@keradus Maybe this fixer should have only two rules:
1. do not fix indentation
2. replace all adjoint multiple spaces with one
So it would work like:
Before:
```php
function    sum    (     $a   ,     $b       )       {
    return       $a    +       $b              ;
}
```
After:
```php
function sum ( $a , $b ) {
    return $a + $b ;
}
```

**Comment by keradus** [comment]
Considering CS the `after` version is as bad as `before` one.

**Comment by EvgenyOrekhov** [comment]
@keradus I don't think there are many codebases that have so many spaces all over the code, and basically I want a fixer that would fix `return $a  + $b;` to `return $a + $b;`.
I think this fixer with these two simple rules is easy to implement and it would play very nice when used in combination with other fixers.

**Comment by keradus** [comment]
So what you want is a fixer similar to `operators_spaces` that trim extra spaces.
Great fixer indeed!

**Comment by SpacePossum** [comment]
I think all the cases from the examples here are fixed now :)
