### ISSUE TITLE
Getting error wrong file name all time when I'm using stdin

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfPHP/PHP-CS-Fixer#1355]
PHP CS Fixer version 1.10
cat ./src/RM/Response.php | php ./bin/php-cs-fixer fix --diff -
````bash
   1) stdin.php
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       
      -class Response extends RM\Response
      +class stdin extends RM\Response
````

**Comment by keradus** [comment]
You should turn off PSR0 fixer.
It was also already disabled by default in 2.x line.

Also, it would be great to disallow run of that fixer (return false in `supports` method) if input file is StdInFile.

**Comment by keradus** [comment]
@maZahaca please try #1356

**Comment by maZahaca** [comment]
Thanks!

**Comment by keradus** [comment]
Closing due to merge of #1356
