### ISSUE TITLE
it's too slow

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [FriendsOfPHP/PHP-CS-Fixer#1357]
php-cs-fixer needs 540 seconds on my project with ~37000 lines of PHP code and ~500 PHP files. That's 9 minutes. That's more than my current full jenkins job with functional tests that run in a web browser and recreate an sqlite inmemory DB for every test.

Somebody (TM, me?) might find something by running php-cs-fixer with profiling enabled?

**Comment by keradus** [comment]
The worst part is tokenizing.
Try enabling cache.

**Comment by funivan** [comment]
Probably version 2.0 will be faster)

**Comment by keradus** [comment]
Or best option for me... run under PHP7 ;)

PHP CS Fixer on Travis we run phpunit and run whole code in dry-run. Take a look at times:
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/builds/76778771 :D

**Comment by sstok** [comment]
54 seconds! wow :scream:

**Comment by keradus** [comment]
And most of it is composer+phpunit, php-cs-fixer in dry-run is 16.987s :D
