### ISSUE TITLE
Several files as income to the fix method

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfPHP/PHP-CS-Fixer#1359]
Hi, I got a problem here.
I use fixer as a pre-commit hook. As income I have several php files.
I wanted to pass few files to the FIX method, not a path. 
Right now I have to run fixer for each file, it took a lot of resources, much more if it can be as a one process.
Version 1.10

Is it possible to add delimiter like a "," to the [path] param, to give an ability to pass single and several paths

**Comment by gharlan** [comment]
-> #1230

**Comment by keradus** [comment]
Closing as duplicate
