### ISSUE TITLE
Consistent naming convention for sniffs

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfPHP/PHP-CS-Fixer#1360]
Currently the sniffs have no naming convention
Some are named after what should be fixed (what is wrong), others are named after what the result should be (what is right).

    "no_blank_lines_after_class_opening"
    // fine

    "join_function"
    // should be
    // "implode_function"

    "double_arrow_multiline_whitespaces" 
    // should be 
    // "double_arrow_no_multiline_whitespace"
    
    "spaces_before_semicolon"
    // should be
    // "no_spaces_before_semicolon" or "semicolon_no_spaces_before"

etc

I think that should be more consistent, they should all be named after what the expected outcome is, so it is intuitively clear what those "fix". Currently one needs to read the documentation text to know if its positive or negative (pre or post).

Also the important keyword should be at the beginning (as 2nd of 2nd example).

**Comment by gharlan** [comment]
-> #889

**Comment by GrahamCampbell** [comment]
Yeh, please close this.

**Comment by dereuromark** [comment]
Closing in favor of other ticket.
