### ISSUE TITLE
Can I specify max line length?

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfPHP/PHP-CS-Fixer#1361]
Can I specify max line length?

**Comment by GrahamCampbell** [comment]
No.

**Comment by maZahaca** [comment]
Can it be implemented? Do you have any doubts ?

**Comment by GrahamCampbell** [comment]
Would be very hard to implement fully.

**Comment by divined** [comment]
It implemented in the phpcbf

**Comment by vishwarajanand** [comment]
Can [FixerInterface](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/FixerInterface.php#L50) be used?
Pls comment if anyone tried!

**Comment by henryfoster** [comment]
Any update on this one?

**Comment by keradus** [comment]
PHP CS Fixer is not having such functionality. If you want to have it available, please contribute and open a PR adding such a feature.
