### ISSUE TITLE
Possibility to use fixer for part of file

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfPHP/PHP-CS-Fixer#1365]
Hi,
I'm working on the precommit hook which uses fixer.
It would be great to use fixer for a part of the file, for example:
php-cs-fixer fix file.php:13-20;45-50

Is that possible, hard to do?

**Comment by GrahamCampbell** [comment]
Would be very hard to do.

**Comment by GrahamCampbell** [comment]
The entire file must be used to get the correct context.

**Comment by GrahamCampbell** [comment]
And then the entire file must be changed.

**Comment by GrahamCampbell** [comment]
What you could do is just discard changes made outside that area after running php-cs-fixer on the whole file.

**Comment by keradus** [comment]
Closing due to discussion

**Comment by maZahaca** [comment]
I use it for showing diff, not for real fixing. It's not clear to parse diff output
