### ISSUE TITLE
Alignment get messed up when docblock is present

### ISSUE THREAD

**Issue by abhimanyu003** [FriendsOfPHP/PHP-CS-Fixer#1371]
Alignment get messed up when docblock is present

**Code before cs-fixer**

``` php
    /**
     * @param $param
     * @return mixed
     */
        public function length($string)
    {
        return strlen($string);
    }
```

**Code after cs-fixer**

``` php
    /**
     * @param $param
     * @return mixed
     */
        public function length($string)
        {
            return strlen($string);
        }
```

command used `php-cs-fixer fix --level=psr2 File.php`

**Comment by GrahamCampbell** [comment]
I don't think that's a bug? That looks like the correct behaviour. The indentation of the function was matched with the definition.

**Comment by abhimanyusharma003** [comment]
May be I didn't explain it properly.

Please check these two files 

* Before cs-fix https://gist.github.com/anonymous/21b3eee6f6d3e54390fa
* After cs-fix https://gist.github.com/anonymous/c411cd0a2e509b2728a7

`methodFirst` is properly indented in both the files.

Please check what happen to `methodSecond` and `methodThird` after you run cs-fix, they are not aligned with the with the `methodFirst`

**Comment by GrahamCampbell** [comment]
You did explain it right, and I don't think this is a bug.

**Comment by abhimanyusharma003** [comment]
Is there any way align all the methods of class when the doc block is present. They only align whey doc is not there.

**Comment by GrahamCampbell** [comment]
I agree our fixers don't fix all cases, but that's not really a bug.

**Comment by GrahamCampbell** [comment]
We just need more fixers.

**Comment by svenax** [comment]
Of course it is a bug. The indentation fixer should *fix* incorrect indentation, no?

**Comment by GrahamCampbell** [comment]
No, It just matches the function body with that of the definition.

**Comment by GrahamCampbell** [comment]
That is "fixing" it.

**Comment by svenax** [comment]
OK. I still think it is a bug. When there are no comments present, the indentation is normalized a expected:
```php
class test
{
public function one()
{
}

          public function two()
            {
            }
}
```
is formatted as
```php
class test
{
    public function one()
    {
    }

    public function two()
    {
    }
}
```
When there are comments though, the indentation is not normalized, e.g.:
```php
class test
{
// Comment
public function one()
{
}

          // Comment
          public function two()
            {
            }
}
```
is formatted as
```php
class test
{
    // Comment
public function one()
{
}

          // Comment
          public function two()
          {
          }
}
```

That to me is not expected behavior.

**Comment by abhimanyusharma003** [comment]
@svenax :heavy_plus_sign: :one:

**Comment by keradus** [comment]
Thank you for report. Could you send a PR with fix for that please?

**Comment by GrahamCampbell** [comment]
Is this still happening?

**Comment by SpacePossum** [comment]
>Is this still happening?

it is on master atm

**Comment by SpacePossum** [comment]
still relevant on 2.2

**Comment by keradus** [comment]
Fixed, will be released soon. thanks to @julienfalque !
