### ISSUE TITLE
Fixer not Working

### ISSUE THREAD

**Issue by sunel** [FriendsOfPHP/PHP-CS-Fixer#1385]
when i run the fix command nothing happens to the file but the out shows 

```shell
php-cs-fixer fix

Fixed all files in 0.026 seconds, 5.250 MB memory used
``` 
i purposely created a php files with many cs issue and tried to fix it but the files had no changes

the version that i use is ``` "fabpot/php-cs-fixer": "^1.10" ```

**Comment by keradus** [comment]
what about `php-cs-fixer fix -vvv` ?
