### ISSUE TITLE
ArrayElementSpaceFixer

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1386]
An equivalent for [MethodArgumentSpaceFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/PSR2/MethodArgumentSpaceFixer.php) for array elements would be fine.

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Closing due to merge of #1484
