### ISSUE TITLE
Problem to install on windows ):

### ISSUE THREAD

**Issue by sajaddp** [FriendsOfPHP/PHP-CS-Fixer#1402]
Hello,
I reading document Repeatedly but I could not install PHP-CS-Fixer on my windows ):
please help me to install that step by step

**Comment by keradus** [comment]
Is any error occurs? "not working" didn't tell much

**Comment by sajaddp** [comment]
For install php-cs-fixer.phar i create a .bat file with this code:
``@php "%~dp0php-cs-fixer.phar" %* ``
and run it. ( such as another phar file that i installd before)
but when i use Atom packages I get the error message is not installed.


Unfortunately, I can not speak English very good ):

**Comment by sajaddp** [comment]
I change my code and setting of Atom's package and my problem fixed.
