### ISSUE TITLE
Braces fixer removes empty lines after class opening

### ISSUE THREAD

**Issue by viktorasp** [FriendsOfPHP/PHP-CS-Fixer#1404]
Before:
```php
class simpleTestClass
{

    private $foo;

    private $bar;
}
```

After running PSR-2 level fixer "braces" fixes it to:
```php
class simpleTestClass
{
    private $foo;

    private $bar;
}
```

According to #567, #874, #890 - it was fixed and #885 made extra lines removal into a separate fixer. However I'm running CS v.1.10 and my code is still getting "fixed". Is there any reason why a default PSR2 fixer removes those lines?

**Comment by GrahamCampbell** [comment]
Are you 100% sure you're not running at symfony level? Can I see the command you ran and your .php_cs file please?

**Comment by viktorasp** [comment]
Config:
```php
return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->finder($finder)
;
```

Output after running "php php-cs-fixer.phar fix --config-file=config.php_cs -vvv":
```
Loaded config from "config.php_cs"
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) testClass.php (braces)
Fixing time per file:
[0.128 s] testClass.php
```

**Comment by GrahamCampbell** [comment]
What happens if you just run `php php-cs-fixer.phar fix src --level=psr2`?

**Comment by viktorasp** [comment]
It is exactly the same:
```
php php-cs-fixer.phar fix . --level=psr2 -vvv
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) testClass.php (braces)
Fixing time per file:
[0.130 s] testClass.php

Fixed all files in 0.132 seconds, 4.500 MB memory used
```

**Comment by viktorasp** [comment]
And just to be sure about the version being used:
```
PHP CS Fixer version 1.10 by Fabien Potencier (8e21b4f)
```

**Comment by keradus** [comment]
Reason: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/84d9fb5ca8cd51bf671f187c8bc17d685225b630

**Comment by keradus** [comment]
@viktorasp see #1478
