### ISSUE TITLE
Renaming namespace.

### ISSUE THREAD

**Issue by bweston92** [FriendsOfPHP/PHP-CS-Fixer#1406]
The PHP CS Fixer is renaming my namespaces.

```
<?php
$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in('src')
    ->in('tests');

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->finder($finder);
```

Runniing
```
D:\fundbay.co.uk\application\libs\lib-tracking>php-cs-fixer fix --diff --dry-run
Loaded config from "D:\amce\.php_cs"
   1) TestCase.php
      ---------- begin diff ----------
      --- Original
+++ New
@@ @@
 #Warning: Strings contain different line endings!
 <?php

-namespace AMCE\Tests\Tracking;
+namespace AMCE\tests\Tracking;

 class TestCase extends \AMCE\Tests\Shared\TestCase
 {
 }


      ---------- end diff ----------

Fixed all files in 0.319 seconds, 4.000 MB memory used

```

I cannot find a rule in the PSR-2 guidelines suggest this.

**Comment by GrahamCampbell** [comment]
> I cannot find a rule in the PSR-2 guidelines suggest this.

I can. This is PSR-0. Please disable the psr0 fixer and you're sorted.

**Comment by GrahamCampbell** [comment]
> #Warning: Strings contain different line endings!

You need to checkout your code using unix style line endings too.

**Comment by bweston92** [comment]
Really? http://www.php-fig.org/psr/psr-0/




—

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by stof** [comment]
The issue in your case is that your file does not follow PSR-0 but PSR-4. So applying the PSR-0 fixer can break things

**Comment by bweston92** [comment]
Ok well nowhere in http://www.php-fig.org/psr/psr-0/ does it mention this.




Yes I'm following PSR-4 so will update the '.php_cs' file accordingly.



—

**Comment by GrahamCampbell** [comment]
> Ok well nowhere in http://www.php-fig.org/psr/psr-0/ does it mention this.

Yes it does...

**Comment by GrahamCampbell** [comment]
It says your folder structure must be `tests/AMCE/Tests/Tracking`. Only PSR-4 allows `tests/Tracking`.

**Comment by bweston92** [comment]
That's fine as a rule, but actually strip "Tests" is bad. So if I have "MyCi\Tests\PhpUnitRunner" which is valid you're telling me it will be replaced?m to "MyCi\tests\PhpUnitRunner" there is a lot of examples where Tests might not relate to test cases but part of a valid structure.



—

**Comment by GrahamCampbell** [comment]
Basically, what you want is PSR-4, and that's fine. Just don't try and use the PSR-0 level fixer. :)

**Comment by GrahamCampbell** [comment]
This issue should be closed, especially since the psr0 fixer is disabled by default in php-cs-fixer 2.x.

**Comment by bweston92** [comment]
@GrahamCampbell thanks for your help. I would of been wondering for quite some time.
