### ISSUE TITLE
PhpdocIndentFixer creates invalid comment syntax leading to comments being printed out

### ISSUE THREAD

**Issue by phofmann-trust** [FriendsOfPHP/PHP-CS-Fixer#1407]
PhpdocIndentFixer creates invalid comment syntax leading to comments being printed out.

The following code should not be modified:
```
<?php /** @var Foo $foo */ ?>
```
But it gets changed to:
```
<?php/** @var Foo $foo */ ?>
```

Because there is no white space after <?php the whole line will be printed out by PHP. So after running php-cs-fixer it is possible that there are PHP comments in between the HTML on a website / in the output of a program.

Test case for Symfony/CS/Tests/Fixer/Symfony/PhpdocIndentFixerTest.php PhpdocIndentFixerTest::provideDocblocks
```
        $cases[] = array('<?php /** @var Foo $foo */ ?>');
```

**Comment by phofmann-trust** [comment]
This also seems to happen for the following code:
```
<?php /** foo */ ?>
```

**Comment by keradus** [comment]
Hi!
Thank you for reporting!

Which version are you using?
(You may find it out by running `php-cs-fixer --version`)

**Comment by phofmann-trust** [comment]
Oh, not the latest one - it's 1.9.3.

**Comment by keradus** [comment]
Could you be so nice and test it out on newest 1.x@stable and 2.x@dev ?

**Comment by GrahamCampbell** [comment]
I'd assume it's broken on both.

**Comment by phofmann-trust** [comment]
I could quickly test 1.10. There it's broken too.

**Comment by SpacePossum** [comment]
@phofmann-trust this should now be fixed on the 1.10 branch, could you give it another try?
(not the phar version yet ;) )

**Comment by keradus** [comment]
Closing due to merge of #1407

**Comment by phofmann-trust** [comment]
I tried out 1.10, it works now. Thanks! :+1:
