### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by DavidGarciaCat** [FriendsOfPHP/PHP-CS-Fixer#1408]
Hey there,

Usually I run these commands on my projects:

```
$ bin/php-cs-fixer fix features
$ bin/php-cs-fixer fix --fixers=-visibility spec
$ bin/php-cs-fixer fix src
```

IMO display a progress bar, displaying how many files have been processed, or maybe the %, will be great. At this moment I am working with thousand of files, and I don't know how long need to wait before run other commands.

What do you think abut this?

Best,

**Comment by GrahamCampbell** [comment]
Hmm, well we iterate files without knowing the "count" if you will, so we don't know the progress.

**Comment by DavidGarciaCat** [comment]
Maybe we can add a `count()` at the beginning, just to know that, and keep the developer up to date about the % completed.

If there is another developer that knows better than me where can be applied, IMO this update can help. If there are no other developers to handle this, I can review the code, but will take more time, just because I will need to review the code first.

**Comment by funivan** [comment]
% at any point can change in different ranges. You can see 30% and then 15% so :-1: 
How many files have been processed is not so important IMHO.

**Comment by GrahamCampbell** [comment]
Yeh, :-1: for having to load the entire list of files into memory at once.

**Comment by GrahamCampbell** [comment]
Well, or double iterating...

**Comment by DavidGarciaCat** [comment]
OK if you think this is not so important, closing this issue now

**Comment by keradus** [comment]
TBH I would like to have that feature as alternative to "dot" progress indicator.

**Comment by DavidGarciaCat** [comment]
IMO I think this can be a very useful feature (maybe can display this if we pass an argument).
Any other comment about this?

**Comment by flip111** [comment]
You can:

1. always count all the files up ahead
2. optionally always count all the files up ahead (with command line flag)
3. only count all the files up ahead once, then after cache this number. On the next run your estimate might be a bit off if you added or deleted a file.

**Comment by SpacePossum** [comment]
closing as https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2591 has been merged, the new options for the process view should be enough
