### ISSUE TITLE
Tokenizer as a standalone component

### ISSUE THREAD

**Issue by soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1409]
The Tokenizer of this project is good and could be useful elsewhere IMO.

Would be nice to separate it on a standalone component.

What do you think?

**Comment by keradus** [comment]
Out of curiosity... what is your scenario to use Tokenizer without PHP CS Fixer?

ref #565

**Comment by Soullivaneuh** [comment]
Well, that's a little and crappy use case for me: I have a dependency with another library just for configuration set on constants but I can't add it because of higher PHP version constraint.

So I have to make a command that download the file, parse it with Tokenizer and recreate it with the needed format.

**Comment by keradus** [comment]
If I get you right - downgrade PHP source code ? :D

**Comment by Soullivaneuh** [comment]
I would prefer to say : Keep support for devs using old and crappy PHP versions. ;-)

**Comment by boekkooi** [comment]
Another option would be to allow a project like [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) to use the same Tokenizer or in my case I could maybe use it for something like [PHP-CS-Checker](https://github.com/boekkooi/PHP-CS-Checker)

**Comment by julienfalque** [comment]
I think it's not worth it: the internal tokenizer is tightly linked to how PHP CS Fixer works, making it a separate package would mostly increase maintainance costs for no real gain. One can use [nikic/php-parser](https://packagist.org/packages/nikic/php-parser) or simply have another `token_get_all()` wrapper.
