### ISSUE TITLE
Is there any way to configure cs-fixer so that all braces will be placed on new line?

### ISSUE THREAD

**Issue by TatzyXY** [FriendsOfPHP/PHP-CS-Fixer#1411]
Not sure if it is here the right place to ask this questions. Its my first post here on github please dont destory me when its wrong.

Bad code:

``` php
class Main               {
    public function                     test() {
        if ($test == 'test')         {
        echo 'test';
        } else {
        echo 'test';
        }
    }
}
```

it will be converted to this, its better...:

``` php
class Main
{
    public function test()
    {
        if ($test == 'test') {
            echo 'test';
        } else {
            echo 'test';
        }
    }
}
```

but I need this:

``` php
class Main
{
    public function test()
    {
        if ($test == 'test')
        {
            echo 'test';
        } 
        else 
        {
            echo 'test';
        }
    }
}
```

**Comment by keradus** [comment]
Currently there is no such a fixer to move braces in a way breaking PSR rules.

**Comment by TatzyXY** [comment]
@kredus I know PSR is good and needed but in big project there are own styleguids or opinions about it. Sometimes you are forced to follow other styleguides like PSR. So it would be awesome if you guys would implement such a feature even if it breaks PSR a bit.

Thank you for your incredible fast answer.

**Comment by keradus** [comment]
I do not said that this fixer wouldn't be accepted.
You asked is there a way - no there is not, currently. Just because we had focused on PSR, not any styleguide anyone can get on his mind ;)
The main criteria for rule to be accepted is if it will be used widely. So we prepared rules not only for PSR, but Symfony too, even some ZF2 etc.

If you want you can prepare such a fixer and we will gladly help with it. If you want to - start by reading the cookbook ;)

**Comment by GrahamCampbell** [comment]
Maybe we need to just make our braces fixer more configurable, and maybe even split it up, instead of just adding a new fixer?

**Comment by TatzyXY** [comment]
@GrahamCampbell This would be very cool. We are following PSR almost only our braces in our project are handeled a bit different than PSR suggest it. Not K&R, We use Allman.

Making the braces fixer a little bit configurable would fix all my needs.

**Comment by GrahamCampbell** [comment]
Yeh, sure. I've wanted that before too, but it's easier said than done. The braces fixer is pretty complex. :)

**Comment by keradus** [comment]
Ref #823
