### ISSUE TITLE
PHP minimum version for 2.0

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1412]
Just for curiosity: Did you decide of which PHP minimum version PHP-CS-Fixer will require for 2.0?

If yes, which version will be?

Regards.

**Comment by keradus** [comment]
PHP CS Fixer 2.x will not change required PHP version.
It is due to fact that after release of 2.x the 1.x line will not be supported.

**Comment by Soullivaneuh** [comment]
Thanks for the explanation.
