### ISSUE TITLE
Lambda in array issue

### ISSUE THREAD

**Issue by FranBar** [FriendsOfPHP/PHP-CS-Fixer#1418]
fix  --level=psr2
<pre>
$array = array(
    'closure' => function ($param1, $param2) {
        return;
    }
);
</pre>
Actual result of the above code:
<pre>
$array = array(
    'closure' => function($param1,
    $param2) {
        return;
    },
);
</pre>
Expected result:
<pre>
$array = array(
    'closure' => function ($param1, $param2) {
        return;
    }
);
</pre>
I think the commas are detected as part of the array rather than the function arguments

**Comment by keradus** [comment]
File:
```php
<?php

$array = array(
    'closure' => function ($param1, $param2) {
        return;
    }
);

```

Lets try to reproduce:
```bash
D:\GIT\fork\PHP-CS-Fixer (1.10)
λ php php-cs-fixer fix 1 --dry-run --diff -vvv --level=psr2
.
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
```

```bash
D:\GIT\fork\PHP-CS-Fixer (1.11)
λ php php-cs-fixer fix 1 --dry-run --diff -vvv --level=psr2
.
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
```

```bash
D:\GIT\fork\PHP-CS-Fixer (master)
λ php php-cs-fixer fix 1 --dry-run --diff -vvv --rules=@PSR2
.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
```

I cannot duplicate the bug...

**Comment by FranBar** [comment]
This does not show errors  and the behavior is expected:
<pre><?php

$array = array(
    'closure' => function ($param1, $param2) {
        return;
    }
);</pre> 
(No EOF at the end)

I think the problem lies elsewhere ... I'm still puzzled.

**Comment by GrahamCampbell** [comment]
What line endings did you have?

**Comment by FranBar** [comment]
I'm sorry. Almost certainly my problem.

Possibly my file system is corrupt, now everything is erratic behavior.

**Comment by GrahamCampbell** [comment]
@FranBar Please could you close this.

**Comment by FranBar** [comment]
I use KDevelop and I created a wrapper with an external script for php-cs-fixer, I also allows you to format only a selected part of the text:
<pre>
#!/bin/bash

if [ ! -n "$1" ]; then
  cat > /tmp/.formatter.input
else 
  cat $1 > /tmp/.formatter.input
fi

php-cs-fixer fix /tmp/.formatter.input --level=psr2 --quiet

echo '' >> /tmp/.formatter.input
cat /tmp/.formatter.input
rm /tmp/.formatter.input;
</pre>

I tried another machine and it works perfectly.

**Comment by keradus** [comment]
Tokenizer is unstable when working on only part of code.

**Comment by FranBar** [comment]
It is certain that my hard drive is dead, I will make sure that test when the non-system failures.

In principle on a clean install on another machine it seems to work properly.

Thank you.
