### ISSUE TITLE
Symfony don't like the new method separation fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1421]
See https://github.com/symfony/symfony/pull/15890. The issue is adding the extra newline between a non-doc comment and a method definition.

**Comment by keradus** [comment]
feel free to send a PR ;)

**Comment by GrahamCampbell** [comment]
Sure. Just putting this here to remind me, or to let anyone else jump in if they get a chance to look at it before me.

**Comment by SpacePossum** [comment]
With the PR containing fixes merged they (Symfony) like the `MethodSeparationFixer` in its current form :)
I would like to suggest to close this issue
