### ISSUE TITLE
Unable to add custom fixers

### ISSUE THREAD

**Issue by krmarien** [FriendsOfPHP/PHP-CS-Fixer#1436]
When I try to add custom fixers like this:

    $finder = Symfony\CS\Finder\DefaultFinder::create()
        ->in(__DIR__);

    $config = Symfony\CS\Config\Config::create()
        ->fixers(
            array(
                'single_use'
            )
        )
        ->finder($finder);

    $config->addCustomFixer(new Litus\CodeStyle\Fixer\SingleUseFixer());

    return $config;

The contents of `$fixers` in the `fix` function of `Symfony\CS\Fixer` still contains the default fixers.

**Comment by keradus** [comment]
what version are you using ?

**Comment by krmarien** [comment]
I'm using 6fd5cb64fade985dc189e6601c20e743ac846afd, a commit of 11 days ago

**Comment by keradus** [comment]
Then you are using code from `2.x@dev` version but config file fox `1.x@stable`
