### ISSUE TITLE
Get the php-cs-fixer.phar per release

### ISSUE THREAD

**Issue by javaguirre** [FriendsOfPHP/PHP-CS-Fixer#1445]
Hi!

Is there a way of getting the `php-cs-fixer.phar` per release? I've seen in the releases page we have the source code, which is nice, but It would be nicer If we could also have the `phar` built in the release, a unique url to the `php-cs-fixer.phar` file to download.

Thank you!

**Comment by keradus** [comment]
You can download the newest stable version from site.
If you want specific version use composer.

**Comment by javaguirre** [comment]
@keradus I can't just use composer If I want to package It for [Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/php-packages.nix#L121).

What would be the best solution then?

**Comment by stof** [comment]
@keradus a solution could be to attach the phar as an additional file in the github releases. This is what we do in Behat for instance

**Comment by javaguirre** [comment]
That's the solution in [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/releases) and how I created the package for It.

It might not seem a big deal, but It could be helpful since the installation process would be faster and well versioned.
