### ISSUE TITLE
A class with a property/constant value which contains __DIR__ is not fixed

### ISSUE THREAD

**Issue by rybakit** [FriendsOfPHP/PHP-CS-Fixer#1446]
```php
// Foo.php

class Foo
{
    const BAZ = __DIR__.'/baz';

    function bar()
    {
        return "bar";
    }
}
```

Running

```sh
$ php-cs-fixer --level=symfony --dry-run --diff fix Foo.php
```

outputs

```sh
Fixed all files in 0.080 seconds, 5.750 MB memory used
```

After removing the `__DIR__` constant it starts outputting the expected result:

```
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       <?php

       class Foo
       {
           const BAZ = '/baz';
      -
      -    function bar()
      +
      +    public function bar()           {
      -        return "bar";
      +        return 'bar';
           }
       }

      ---------- end diff ----------
```

**Comment by SpacePossum** [comment]
Support for expressions in class consts was added in 5.6 (https://wiki.php.net/rfc/const_scalar_exprs)
Can you tell me what version of PHP you are running the fixer on and which version of the fixer itself are you using?
Could you run the command again with `-vvv` and check if it reports any relevant debug information?

**Comment by rybakit** [comment]
Indeed, it's probably due to the PHP version mismatch. I tried to fix code written for php 5.6 under php 5.4. PHP CS Fixer version 1.10.1.

The output with `-vvv`:

```sh
I
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.075 s] /private/tmp/Foo.php

Fixed all files in 0.076 seconds, 5.750 MB memory used
```
It would be nice to output that file checking was skipped/aborted due to the invalid syntax, as the current message a bit misleading.

**Comment by keradus** [comment]
The thing that you want is exactly what the `I` status is.

**Comment by rybakit** [comment]
@keradus My concern is that the message is not accurate, it gives the false impression that everything is OK, when, in reality, all "fixed" files could have an invalid syntax.

**Comment by keradus** [comment]
Invalid input is not fault of tool, if the file has syntax then it cannot be fixed, it is simply ommited.
And a message like `all files that are good and contain no syntax errors were fixed` overwhelmed.

**Comment by rybakit** [comment]
> And a message like all files that are good and contain no syntax errors were fixed overwhelmed.

For example, in non-verbose mode PHPUnit outputs:
> OK, but incomplete, skipped, or risky tests!
Tests: 158, Assertions: 160, Skipped: 1.

I personally find that this message is clear and informative without being overwhelmed.
Anyway, please fill free to close this issue if you disagree.

**Comment by keradus** [comment]
That may be an option too.
Please, send a PR.

**Comment by rybakit** [comment]
Please check https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1464.

**Comment by keradus** [comment]
great, will see !
