### ISSUE TITLE
Incorrect PSR2 fix on anonymous functions

### ISSUE THREAD

**Issue by tdely** [FriendsOfPHP/PHP-CS-Fixer#1451]
Using the level PSR2 in some cases incorrectly fixes anonymous functions by removing spaces between the 'function' keyword and the following opening parenthesis:
```
-register_shutdown_function(function() {
+register_shutdown_function(function () {
```
This is incorrect as the rule is to not allow spaces between the function name and following opening parenthesis.

**Comment by keradus** [comment]
Please read the PSR2 carefully.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#6-closures
> Closures MUST be declared with a space after the function keyword

The rule you are referring to stands for function *name*, while closure doesn't have name at all.

**Comment by GrahamCampbell** [comment]
> This is incorrect as the rule is to not allow spaces between the function name and following opening 

That's not a "function" though. :)

**Comment by tdely** [comment]
Maybe I could have worded that better. However, the behavior I encountered and reported is still contrary to the PSR2 standard, as you yourself quoted:
> Closures MUST be declared with a space after the function keyword

Thus if I write the following in my code ```register_shutdown_function(function () {```
PHP-CS-Fixer should NOT change this to ```register_shutdown_function(function() {```

The original diff I posted was pretty confusing though, I had to re-read it myself now, sorry about that.

**Comment by keradus** [comment]
Could you send a PR with a test case that proves the bug?
It works for me:
https://github.com/keradus/PHP-CS-Fixer/commit/3827b84da191aa2cc6e752f88febc4364c96bdb3

**Comment by tdely** [comment]
The original code I used is gone but I've tried my best recreating the issue without success. I'll close the issue cause the PHP-CS-Fixer works properly.
Sorry for wasting your time.
