### ISSUE TITLE
Laravel 5.1 --level=psr2 is renaming the namespace

### ISSUE THREAD

**Issue by faralimite** [FriendsOfPHP/PHP-CS-Fixer#1458]
Hello,
I'm using php-cs-fixer in Sublime and after saving a controller file the first letter from namespace is lowercase. From namespace App\Http\Controllers to namespace app\Http\Controllers;

I found a solution to add a new line "app\\": "app/" inside composer.json:

    "autoload": {
        "classmap": [
            "database"
        ],        
        "psr-4": {
            "App\\": "app/",
            "app\\": "app/"
        }
    },

It is a best practice to use this solution?

Regards,
Radu

**Comment by GrahamCampbell** [comment]
NOR a bug.

**Comment by GrahamCampbell** [comment]
You MUST disable the psr0 fixer since you are not using psr0.

**Comment by GrahamCampbell** [comment]
> "app\\": "app/"

That is definitely wrong.

**Comment by faralimite** [comment]
How can I disable the psr0 fixer?
Right now I have:

    "php_cs_fixer_additional_args": {
        "--level": "psr2",
    },

Many thanks

**Comment by faralimite** [comment]
I found a solution using a config file for Laravel.
https://gist.github.com/jatubio/dfbebf73ea79f9f72e02

Thank you.
