### ISSUE TITLE
Change namespace case

### ISSUE THREAD

**Issue by oscarotero** [FriendsOfPHP/PHP-CS-Fixer#1459]
Hello.
In my php project, I have the `App` namespace configured to lookup into `app` folder. So I have this in my composer.json file:
```json
{
	 "autoload": {
		"psr-4": {
			"App\\": "app/"
		}
	}
}
```

But php-cs-fixer converts all these namespaces to lowercase, so for example `App\Controllers\Index` becomes to `app\Controllers\Index`.
Is there any way to avoid that? Maybe php-cs-fixer could parse composer.json files to know what namespaces are correct or not.

**Comment by keradus** [comment]
Please, take a look: #1458 . It's the same question.

**Comment by oscarotero** [comment]
Ok, thank you.

**Comment by keradus** [comment]
Glad to help
