### ISSUE TITLE
[Proposal] duplicate array indexes fixer

### ISSUE THREAD

**Issue by wandersonwhcr** [FriendsOfPHP/PHP-CS-Fixer#1469]
Hello!

Yesterday I was developing my application and I had some problems with a `git merge` in an `array` definition. Example:

`array` configuration before `git merge`:
```php
<?php
return array(
    // ...
    'default' => array(),
    // ...
);
```

`array` configuration after `git merge --no-ff issue-1`:
```php
<?php
return array(
    'config' => array(
        'a' => true,
    ),
    // ...
    'default' => array(),
   // ...
);
```

`array` configuration after `git merge --no-ff issue-2`:
```php
<?php
return array(
    'config' => array(
        'a' => true,
    ),
    // ...
    'default' => array(),
    // ...
    'config' => array(
        'b' => true,
    ),
);
```

Capturing  configuration, PHP defined an `array` with this structure:

```php
$config = array(
    'config' => array(
        'b' => true,
    ),
    'default' => array(),
);
```

Boom. Configuration for `$config['config']['a']` was undefined. So, after 1 hour, I found the problem (hehe), duplication of indexes in `array` definition.

Can you create a fix for this problem, like merging duplicate indexes?

```php
<?php
return array(
    'config' => array(
        'a' => true,
        'b' => true,
    ),
    // ...
    'default' => array(),
    // ...
);
```

PS: If we have duplicated subindexes, do a recursive merge?

**Comment by keradus** [comment]
Big :-1:
It's an issue of wrong merging, or in more general issue with wrong coding.
It's not about style at all.

**Comment by wandersonwhcr** [comment]
Hum... OK, now I see, it's work for PHPMD.

Thank you!

**Comment by keradus** [comment]
:+1: for Mess Detector!
