### ISSUE TITLE
array value inside a double quoted string replaced incorrectly

### ISSUE THREAD

**Issue by michield** [FriendsOfPHP/PHP-CS-Fixer#1472]
The code

```
<?php

$string['message'] = 'construction';
$text = "this is a ${string['message']} that is valid".PHP_EOL;
echo $text;
```

is converted to 

```
<?php

$string['message'] = 'construction';
$text = "this is a ${stringarray('message')} that is valid".PHP_EOL;
echo $text;
```

when using the command

**php-cs-fixer fix File.php --fixers=long_array_syntax**

_php-cs-fixer -v
PHP CS Fixer version 1.10.1_

**Comment by GrahamCampbell** [comment]
What, really?

**Comment by michield** [comment]
indeed, and it should be marked bug

~$ php File.php 
this is a construction that is valid
~$ php-cs-fixer fix --fixers=long_array_syntax File.php 
   1) /home/michiel/File.php
Fixed all files in 0.058 seconds, 5.750 MB memory used
~$ php File.php 
PHP Fatal error:  Call to undefined function stringarray() in /home/michiel/File.php on line 15

**Comment by GrahamCampbell** [comment]
@keradus https://3v4l.org/ZkjcW

**Comment by keradus** [comment]
So ugly...

**Comment by keradus** [comment]
See #1479

**Comment by keradus** [comment]
Closing due to merge of #1479
