### ISSUE TITLE
phpdoc_short_description - Do not a add a dot at the end of a list

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1475]
(question)

For example

```php
    /**
     * Support for:
     * - classes
     * - traits 
     */
```

gets fixed to:
```php
    /**
     * Support for:
     * - classes
     * - traits.
     */
```

I think this is not correct and the fixer should not touch `list items`. It would be tricky to detect lists since I don't think PSR 5 has defined a format for this.
For example:
```
- [item 1]
- [item 2]
```

```
* [item 1]
* [item 2]
```

```
1 [item 1]
2 [item 2]
```

```
III - [item 1]
IV - [item 2]
```

etc.

Any thoughts?

**Comment by keradus** [comment]
The problem here is that this is not a valid PHPDoc. Short descr must be in one line. Here is only long descr, while short one is missing. That is what causes an error.

**Comment by SpacePossum** [comment]
Ah I see, thanks! :+1:

**Comment by keradus** [comment]
It would be great to detect if docblock has a short-descr and if not do not modify long descr.

**Comment by GrahamCampbell** [comment]
This is not a bug.

**Comment by GrahamCampbell** [comment]
```
Support for:
     * - classes
     * - traits 
```

That's not a valid short description. You must modify it so that that becomes the long description.

**Comment by GrahamCampbell** [comment]
Essentially, us fixing this in this way allows you to identify the areas where your phpdoc is wrong, and you can fix them yourself by adding a better short description.

**Comment by keradus** [comment]
It's not a bug, but couldn't we check if short description is valid, and if no just leave it alone?

**Comment by GrahamCampbell** [comment]
> It's not a bug, but couldn't we check if short description is valid, and if no just leave it alone?

Well, it IS valid.

**Comment by GrahamCampbell** [comment]
Putting a fullstop where we did is correct.

**Comment by keradus** [comment]
very well.
