### ISSUE TITLE
[FR] @link to @see fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1476]
PSR 5 `@link` is deprecated in fav. of `@see`.
(https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#810-link-deprecated)

Would a fixer for this be welcome here?

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
@keradus Yet another reason why we should have the var to type fixer abstract. :trollface:

**Comment by GrahamCampbell** [comment]
We can just use that fixer to fix this case too.

**Comment by keradus** [comment]
No, it is not a reason to create abstraction for `var-type`. An abstraction could be for common functionality, not for different rules. Yep, you could extract common code that replaces tags.
