### ISSUE TITLE
Suggested new fixer: ShortCast

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfPHP/PHP-CS-Fixer#1480]
A fixer we use as custom one, which is worth becoming a contrib one (as there is already a fixer for fixing `@return/param boolean/integer` to `bool/int`).
So this completes it for consistency:

```php
/**
 * Fixer ShortCast
 *
 * @author Mark Scherer
 */
class ShortCastFixer extends AbstractFixer
{

    /**
     * @var array
     */
    public static $matching = [
        '(boolean)' => '(bool)',
        '(integer)' => '(int)',
    ];

    /**
     * @param \SplFileInfo $file
     * @param string $content
     *
     * @return string
     */
    public function fix(\SplFileInfo $file, $content)
    {
        $tokens = Tokens::fromCode($content);
        foreach ($tokens as $index => $token) {
            // Don't use !!
            if ($token->getContent() === '!' && $tokens[$index - 1]->getContent() === '!') {
                $tokens[$index - 1]->setContent('');
                $tokens[$index]->setContent('(bool)');
                continue;
            }

            // Don't use long form
            if ($token->isCast()) {
                $content = $token->getContent();
                $key = strtolower($content);

                if (isset(self::$matching[$key])) {
                    $tokens[$index]->setContent(self::$matching[$key]);
                }
            }
        }

        return $tokens->generateCode();
    }

    /**
     * @return int
     */
    public function getPriority()
    {
        return -100;
    }

    /**
     * @return int
     */
    public function getLevel()
    {
        return FixerInterface::NONE_LEVEL;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return 'Use short forms (bool) and (int) for casts and do not use !!.';
    }

}
```

**Comment by GrahamCampbell** [comment]
Maybe we need the same deal with have with the phpdoc fixers, so "Integer" can be fixed to "int" too?

**Comment by dereuromark** [comment]
And then extract that from the existing fixer? Because currently this is already fixed along with the other doc block changes. But I agree, it would be better to separate those two things.

**Comment by keradus** [comment]
Please, could you send a PR?

**Comment by GrahamCampbell** [comment]
Kind of hard to totally abstract, since the phpdoc fixer also includes fixes for sudo types, like "numeric", or "mixed".

**Comment by dereuromark** [comment]
Wanted to first get a "OK, sounds useful" and maybe some preliminary feedback, like if the suggested name sounds OK. But then a PR should be possible very soon.

**Comment by keradus** [comment]
> Use short forms (bool) and (int) for casts and do not use !!.

Should be two fixers ;)

**Comment by SpacePossum** [comment]
Or 1 with config options ;)

**Comment by keradus** [comment]
boolean/bool is explicitly cast
!! is implicitly cast

I think that changing implicitly cast to explicitly cast should be separated

**Comment by SpacePossum** [comment]
ah, I misread, I thought two fixers for `(bool)` and `(int)`, but I get it now ;)

**Comment by dereuromark** [comment]
Any naming ideas for them?

* ShortCast (for boolean=>bool and integer=>int) / NoCastAliases  / RemoveCastAliases
* NoImplicitCast (for !! => bool)

?

**Comment by dereuromark** [comment]
I see that @SpacePossum already started on the ImplicitCast one.
The other code can be found [here](https://github.com/php-fig-rectified/psr2r-fixer/blob/master/src/Fixer/ShortCastFixer.php) in case anyone wants to get a head start on the 2nd part of the cast fixer.

**Comment by SpacePossum** [comment]
I think this can be closed, since https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1613 is merged :)

**Comment by keradus** [comment]
thanks ;)
