### ISSUE TITLE
allow Symfony 3.0

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfPHP/PHP-CS-Fixer#1491]
related to https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/49

**Comment by GrahamCampbell** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1281.

**Comment by gharlan** [comment]
fixed by #1510

**Comment by keradus** [comment]
indeed
