### ISSUE TITLE
Items of the @property tag should be aligned vertically

### ISSUE THREAD

**Issue by ffsantos92** [FriendsOfPHP/PHP-CS-Fixer#1492]
I'm using the fixer:
- phpdoc_align (all items of the `@param`, `@throws`, `@return`, `@var`, and `@type` phpdoc tags must be aligned vertically).

But why not include also all items of the `@property` tag?

**Comment by drAlberT** [comment]
:+1:  `@property` should be aligned too

**Comment by keradus** [comment]
feel free to collaborate ;)

**Comment by julienfalque** [comment]
Closing as #2649 was merged.
