### ISSUE TITLE
[WIP][PSR-12] Declare strict_types is incorrectly reformatted

### ISSUE THREAD

**Issue by EspadaV8** [FriendsOfPHP/PHP-CS-Fixer#1494]
I realise this is a little early since PHP 7 isn't out yet and PSR-12 is still in progress, however, I thought it might be good to start some issue since I couldn't find any on here already.

With the following code

```php
<?php
declare(strict_types=1);

class Test
{
}
```

php-cs-fixer will currently insert a space between `declare` and the opening `(` brace. According to the current PSR-12 document (https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#example) there shouldn't be a space between.

Updating the fixer while it's still in draft would potentially be a pointless ping-pong back and forth but it would be nice if there were some work around that could be used in the meantime.

**Comment by keradus** [comment]
yeah, if it added a space than it's a bug

**Comment by keradus** [comment]
@EspadaV8 could you work on a fix?

**Comment by EspadaV8** [comment]
I can give it a go, although I've not worked with tokenisers before. I tracked it down to the `fixSpaceAroundToken` method in the `BracesFixer` class. Would the best way to be to add a check just for the `strict_types` line? Other instances of using `declare` should probably follow the usual formatting rules (or should all `declare`s not have a space?

Here we don't want any spaces

```php
<?php
declare(strict_types=1);

class Test
{
}
```

But this should be formatted similar to `if`s, `while`s, etc.

```php
declare(ticks=1) {
    // entire script here
}
```

```php
declare (ticks=1) {
    // entire script here
}
```

**Comment by nesl247** [comment]
They've updated the PSR-12 doc to include the formatting requirement: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#declare-statements-namespace-and-use-declarations

It is always the same, no spaces.

**Comment by keradus** [comment]
Thanks!

ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1495#issuecomment-159739190

**Comment by EspadaV8** [comment]
Closing because of e797b2e7
