### ISSUE TITLE
Feature request: print vs echo

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1502]

**Comment by Soullivaneuh** [comment]
Be careful that `print` and `echo` have some tiny differences.

For example: 

```php
// Because echo does not behave like a function, the following code is invalid.
($some_var) ? echo 'true' : echo 'false';

// However, the following examples will work:
($some_var) ? print 'true' : print 'false'; // print is also a construct, but
                                            // it behaves like a function, so
                                            // it may be used in this context.
```

Source: http://php.net/manual/en/function.echo.php

**Comment by keradus** [comment]
OMG....

**Comment by Soullivaneuh** [comment]
Yes, I agree. I was curious: Why we have both functions for the same thing? Well, not "really" the same. :-)

`echo` to `print` may be easy to do because I did not found any special indication on the man page.

But for `print` to `echo`, this could be more tricky. ;-)

**Comment by keradus** [comment]
And I think more usefull woud actually be changing print into echo.

**Comment by Soullivaneuh** [comment]
> And I think more usefull woud actually be changing print into echo.

Yes. Too bad, it's the hardest. :-P

Found another differences (Do you feel the joy?!):

> The differences are small: echo has no return value while print has a return value of 1 so it can be used in expressions. echo can take multiple parameters (although such usage is rare) while print can take one argument. echo is marginally faster than print.

Source: http://www.w3schools.com/php/php_echo_print.asp

**Comment by Soullivaneuh** [comment]
More detailed explanation: http://stackoverflow.com/a/234255

**Comment by keradus** [comment]
You know it so well... I think you want to make that fixer ! :D That's great ;P

**Comment by gharlan** [comment]
Maybe the `PreIncrementFixer` is helpful: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/PreIncrementFixer.php

(post-increments can be changed only if the return value is not used.)

**Comment by Soullivaneuh** [comment]
> You know it so well... I think you want to make that fixer ! :D That's great ;P

Ha ha ha!

![image](https://cloud.githubusercontent.com/assets/1698357/11148908/f28b4a92-8a1f-11e5-9b7b-2ad95bd2dd83.png)

More seriously, before starting to write this fixer, we have to know how to manage the special cases.

If a `print` to `echo` (or reverse) could not be changed "as is", what should we do? Two solutions:

1. Quick: Just ignore them.
2. Harder but more complete: Rewrite the code. E.g., for `echo` to `write`, if `echo` has multiple arguments, write multiple `write` instead.

What do you think?

> Maybe the PreIncrementFixer is helpful: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/PreIncrementFixer.php
>
> (post-increments can be changed only if the return value is not used.)

@gharlan Indeed, this could be a inspiration to take.

**Comment by keradus** [comment]
if change `print` to `echo` won't change anything - do it, if it would change the logic - don't touch it

**Comment by gharlan** [comment]
> if change print to echo won't change anything - do it, if it would change the logic - don't touch it

:+1:
