### ISSUE TITLE
whitespacy_lines removes space also from non-blank lines

### ISSUE THREAD

**Issue by JanisE** [FriendsOfPHP/PHP-CS-Fixer#1506]
It seems to me that "whitespacy_lines" removes trailing whitespace from both blank lines (containing only whitespace) and non-blank lines (what "trailing_spaces" is doing).

E.g. 
```php
<?php

$r = 5 +6;	
	
$t = true> 9;	

```

gets formatted to 

```php
<?php

$r = 5 +6;

$t = true> 9;

```

All tabs removed. Is that by design or a bug? From the description it seemed that these to formatters should not overlap.

**Comment by SpacePossum** [comment]
can provide what version of the Fixer you are using and your config?

**Comment by JanisE** [comment]
Yes, sorry!

```
$ php-cs-fixer --version
PHP CS Fixer version 1.10.2 by Fabien Potencier (e8b3c4e)
$ php-cs-fixer fix test.php --config-file conf.php_cs 
Loaded config from "conf.php_cs"
   1) /home/janis/Projekti/testfixer/test.php
Fixed all files in 0.037 seconds, 6.250 MB memory used
$ cat conf.php_cs 
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in(__DIR__)
;

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::NONE_LEVEL)
    ->fixers(array('whitespacy_lines'))
    ->finder($finder)
;
```

**Comment by SpacePossum** [comment]
Thank you for the info (and sorry for getting back to you for 10 days), I can confirm this behavior.
@keradus tested on 1.11, could you tag this one as a bug? :)

**Comment by keradus** [comment]
marked as requested

**Comment by SpacePossum** [comment]
thank you :+1:  :)

**Comment by JanisE** [comment]
Thank you for the improvements! (When does the next version become available?)

**Comment by keradus** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1559 should close v1.10.3
