### ISSUE TITLE
multiline_array_trailing_comma ads comma noise

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfPHP/PHP-CS-Fixer#1507]
I got `, ` noise added where it should not have happened
```php
$x = [
    1 => 2,
    3 => [1, 3]]
```
becomes
```php
$x = [
    1 => 2,
    3 => [1, 3], ]
```

but it should stay as it is. A trailing comma may only be added if there is not a bracket following directly afterwards. A different fixer would have to take care of fixing the array structure first.

The whole idea of using this fixer, if anything, would be to keep diffs minimal, by making sure the line above does not change when adding a row.
But here this is not the case, there should be no such comma and space added as long as there are brackets following.

**Comment by keradus** [comment]
please share result of `php-cs-fixer --version`

**Comment by dereuromark** [comment]
PHP CS Fixer version 1.10.2

**Comment by dereuromark** [comment]
It is also happening with arrays like

			$x = [
				[1, 2, 3]];

**Comment by keradus** [comment]
Code should be 
```php
$x = [[1, 2, 3]];
```

or
```php
$x = [
    [1, 2, 3],
];
```

The half-way multiline-array is still multiline and I would keep that comma addition

**Comment by dereuromark** [comment]
But it should not add it automatically, not without a different fixer fixing the array structure first IMO.

**Comment by dereuromark** [comment]
I can understand your point though.
I guess we will have to live with that then or remove that fixer. Thx.

**Comment by keradus** [comment]
or simply fix that messy array in code itself ;)
