### ISSUE TITLE
Question: More than one line around methods

### ISSUE THREAD

**Issue by petrjirasek** [FriendsOfPHP/PHP-CS-Fixer#1509]
Hello,

I would like to ask you if it is possible to set a number of blank lines around methods?

For example, if I use Symfony standard, I have this:

```php
public function methodA()
{

}

public function methodB()
{

}

public function methodC()
{

}
```

I would like to have this (two blank lines):

```php
public function methodA()
{

}


public function methodB()
{

}


public function methodC()
{

}
```

Is there any fixer to do this? Thank you for your answer.
Petr

**Comment by SpacePossum** [comment]
Hi Petr,

At the moment there no such fixer that does that, nor one that can be configured to do that.
You can take a look at the `MethodSeparationFixer` (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Symfony/MethodSeparationFixer.php) to see how it can be done. 
That fixer will ensure there is one blank line above and below a method with respect to comments, PHPDocs and the position of the method in the class (last or first position exceptions).

**Comment by keradus** [comment]
btw, why you want to have double empty line? is it a standard of some framework or just your own?

**Comment by petrjirasek** [comment]
Thank you for your comments.

@keradus For example Nette framework uses double empty line, you can see some of his coding style here https://github.com/nette/tracy/blob/master/src/Tracy/BlueScreen.php and I have seen a lot of libraries using that style. I know that symfony standard uses one empty line but I wonder if it is possible to do that.

**Comment by keradus** [comment]
I'm not stopping you to extend the fixer, I was just curious ;) Thx

**Comment by SpacePossum** [comment]
would a config option about the amount of blank lines to be set by the `fixerbe welcome

**Comment by keradus** [comment]
I have no interest in that, but also won't block it if it really needed for more than 1 person

**Comment by SpacePossum** [comment]
I think this one is answered; it can be done by adding configuration options to the current `MethodSeparationFixer`. However for a PR to pass to introduce it to the codebase more people would have to show interest and someone has to provide such a PR.
(currently there are none and with question answered I suggest to close this one)

**Comment by keradus** [comment]
Closing. If one would like to have it please help the matter by sending a PR ;)
