### ISSUE TITLE
Ditch `@type` Stuff

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1521]
After the other phpdoc stuff I'm working on has gone through, I need to send a PR to the master branch to remove the `type` annotation from the list of valid types in the `Tag` class, and to remove the `var_to_type` contrib fixer.

**Comment by keradus** [comment]
looks like already done.

**Comment by GrahamCampbell** [comment]
Not done.

**Comment by keradus** [comment]
No? I didn't found it on master branch.
Feel free to prepare the change and send a PR.

**Comment by GrahamCampbell** [comment]
Both fixers remain:

1. https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Phpdoc/PhpdocTypeToVarFixer.php
2. https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Phpdoc/PhpdocVarToTypeFixer.php

---

The proposal I had was to remove them both once we got to a point where nobody cared about type or had it used anywhere/

**Comment by keradus** [comment]
The proposal you had was to remove one of them. If you want - feel free to send a PR.
But if your proposal is to wait for PSR-5 to be approved (like in 3 months? 6 months? year? never?), then it's pointless to keep the issue open. It could be recreated after year, if after that time we will be willing to finally make that change.

**Comment by GrahamCampbell** [comment]
I don't think it'll ever go through TBH. :/

**Comment by keradus** [comment]
so no reason to wait with this issue for PSR-5, right ?
