### ISSUE TITLE
Filename beginning with numbers produces internal error

### ISSUE THREAD

**Issue by tristanbettany** [FriendsOfPHP/PHP-CS-Fixer#1522]
This is an interesting one I came across today.

A filename beginning with numbers produces an internal error, remove the numbers and everything works fine. 

Maybe a more descriptive error in the internal error output could be handy? Took a while to find the cause of this.

Thanks :)

**Comment by SpacePossum** [comment]
Hi,
Could you provide some more details. I tried to reproduce the problem, but failed to do so, see below.

```
possum@outerspace:~/work/PHP-CS-Fixer$ php php-cs-fixer fix --dry-run 123.php -vvv
Loaded config from "/home/possum/work/PHP-CS-Fixer/.php_cs"

Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.000 s] /home/possum/work/PHP-CS-Fixer/123.php

Fixed all files in 0.001 seconds, 5.500 MB memory used

possum@outerspace:~/work/PHP-CS-Fixer$ php php-cs-fixer fix --dry-run 123_abc.php -vvv
Loaded config from "/home/possum/work/PHP-CS-Fixer/.php_cs"
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) /home/possum/work/PHP-CS-Fixer/123_abc.php (eof_ending, header_comment)
Fixing time per file:
[0.055 s] /home/possum/work/PHP-CS-Fixer/123_abc.php

Fixed all files in 0.056 seconds, 6.250 MB memory used
````

can you tell which version of the fixer you use, which file name caused the problem (and maybe your PHP version as well?).

**Comment by tristanbettany** [comment]
~ $ php-cs-fixer -vvv fix ./015_test.php
E
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.480 s] /home/tristan.bettany/./015_test.php

Fixed all files in 0.483 seconds, 6.750 MB memory used

Files that were not fixed due to internal error:
   1) /home/tristan.bettany/./015_test.php

**Comment by tristanbettany** [comment]
Code Inside file:

```
<?php

namespace Fuel\Migrations;

class Test
{
  public function up()
  {
    try
    {
      echo 'Code';
    }
    catch (\Exception $e)
    {
      echo 'Error';
    }
  }
}
```

**Comment by tristanbettany** [comment]
Changing the numbers at the beginning of the file doesnt seem to help, only removing them makes it work for me. Using the version installed from the website this morning so it should be the latest version.

~ $ php-cs-fixer -V
PHP CS Fixer version 1.10.2 by Fabien Potencier (e8b3c4e)

**Comment by keradus** [comment]
The problem here is that psr0 fixer try to follow the PSR here and change your class name to match file name. And one cannot start name of class with digits. So the after-fixing linting fails.

Psr0 fixer should be changed to ignored files with names starting with numbers.

**Comment by keradus** [comment]
@tristanbettany please take a look #1537
