### ISSUE TITLE
Add fixer for assertArray(Not)HasKey to PhpUnitConstructFixer

### ISSUE THREAD

**Issue by mbrodala** [FriendsOfPHP/PHP-CS-Fixer#1525]
Things the following could be fixed to use `assertArrayHasKey('key', $value)` or `assertArrayNotHasKey('key', $value)`:

* `assertTrue(isset($value['key'])`
* `assertFalse(isset($value['key'])`

Notice that things like `assertTrue(isset($value['nested']['key'])` must not be changed to avoid PHP notices in case of undefined indices.

**Comment by SpacePossum** [comment]
That would not work I think, the behaviour of `isset` and `has key` is not the same.
For example:

```php
$test = array('a' => null);
$this->assertArrayHasKey('a', $test);
$this->assertTrue(isset($value['key']));
```

first one passes, second fails.

**Comment by mbrodala** [comment]
Hm, you are totally right here since that's the exact difference between `isset()` and `array_has_key()`. Thus this would inadvertently break tests. Forget about this one then. :-)
