### ISSUE TITLE
Feature request: echo/print/case without parentheses

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1539]
similar to `IncludeFixer`: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Symfony/IncludeFixer.php

```php
echo('foo');
print('foo');

switch ($foo) {
    case('bar'): 
        // ..
        break;
}
```

to:

```php
echo 'foo';
print 'foo';

switch ($foo) {
    case 'bar': 
        // ..
        break;
}
```

**Comment by SpacePossum** [comment]
This would be 3 fixers I guess @keradus ?

Little note for myself for test cases:
```php
$a = 5.1;
$b = 1.0;
switch($a) {
    case (int) $a < 1 : {
        echo 'leave alone';
        break;
    }
    case ($a < 2)/* test */: {
        echo 'fix 1';
        break;
    }
    case (3) : {
        echo 'fix 2';
        break;
    }
    case /**/(/**/ // test
        4
        /**/)//
        /**/: {
        echo 'fix 3';
        break;
    }
    case (((int)$b) + 4.1): {
        echo 'fix 4';
        break;
    }
    case ($b + 1) * 2: {
        echo 'leave alone';
        break;
    }
}
```

**Comment by keradus** [comment]
if `echo` and `print` would be the same then it could be one fixer for printing and one for `case`, if not - 3 indeed.

**Comment by GrahamCampbell** [comment]
Maybe we need a fixer to remove all comments :P
To be honest, why do we need them. If the code is any good, phpdoc will do the trick. :P

**Comment by Soullivaneuh** [comment]
> if echo and print would be the same then it could be one fixer for printing and one for case

I'm :+1: for a `echo`/`print` parenthesis fixer and one another for `case`.

**Comment by Soullivaneuh** [comment]
PRs for this issue:

* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1544
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1548

**Comment by gharlan** [comment]
@Soullivaneuh thanks!

**Comment by gharlan** [comment]
new feature request: same fixer for `clone`/`return`/`yield` :)

**Comment by keradus** [comment]
the logic between #1544 and #1548 is the same (I didn't expect they will be that much similar), things that are different:
- isGivenKind argument
- disallowed token after block end

after some unification:

```php
        $loops = [];
        $loops[] = ['lookupTokens' => array(T_CASE),'forbiddenSuccessors' => array(':')];
        $loops[] = ['lookupTokens' => array(T_PRINT, T_ECHO),'forbiddenSuccessors' => array(';', array(T_CLOSE_TAG))];

        foreach ($tokens as $index => $token) {
            foreach ($loops as $loop) {
                if (!$token->isGivenKind($loop['lookupTokens'])) {
                    continue;
                }
    
                $nextTokenIndex = $tokens->getNextMeaningfulToken($index);
    
                if (null === $nextTokenIndex || !$tokens[$nextTokenIndex]->equals('(')) {
                    continue;
                }
    
                $blockEndIndex = $tokens->findBlockEnd(Tokens::BLOCK_TYPE_PARENTHESIS_BRACE, $nextTokenIndex);
                $blockEndNextIndex = $tokens->getNextMeaningfulToken($blockEndIndex);
    
                if (!$tokens[$blockEndNextIndex]->equalsAny($loop['forbiddenSuccessors'])) {
                    continue;
                }
    
                $tokens[$nextTokenIndex]->clear();
                $tokens[$blockEndIndex]->clear();
            }
        }
```

I bet next keywords would have same logic, so IMO it should be one fixer like `remove_unneeded_control_parenthesis`

**Comment by Soullivaneuh** [comment]
> I bet next keywords would have same logic, so IMO it should be one fixer like `remove_unneeded_control_parenthesis`

It depends if users want to separate fixers usage or not.

But yes, logic could be done on a common class.

Maybe can you merge one of them then I can update others with common code?

**Comment by Soullivaneuh** [comment]
And other question: Parentheses around `case` IS PSR-2. But what about the rest?

**Comment by keradus** [comment]
Non of the fixers were merge as non of them been reviewed.
Just replace all PR of fixers with same code with one new PR.

**Comment by keradus** [comment]
> It depends if users want to separate fixers usage or not.

that's why we my configure the fixer.

**Comment by Soullivaneuh** [comment]
> that's why we my configure the fixer.

Yes, but this is only available on master, isn't it?

> Just replace all PR of fixers with same code with one new PR.

Will do that with a common abstract fixer. Fixers could be merge on master after that.

**Comment by Soullivaneuh** [comment]
And you didn't answer to my question: Parentheses around `case` IS PSR-2. But what about the rest?

**Comment by keradus** [comment]
> > that's why we my configure the fixer.
>
> Yes, but this is only available on master, isn't it?

No it is not: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/.php_cs#L12
It is less comfortable, but still possible.


> > Just replace all PR of fixers with same code with one new PR.
> 
> Will do that with a common abstract fixer. Fixers could be merge on master after that.

Why the master?


> Parentheses around case IS PSR-2. But what about the rest?

Sadly, have no time now to check it on my own.

**Comment by Soullivaneuh** [comment]
> No it is not: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/.php_cs#L12
> It is less comfortable, but still possible.

Well, this method is going to be remove and will make some trouble with @GrahamCampbell StyleCI application IMO.

> Why the master?

I was not clear. I mean fixers could be merge onto one with options an master.

>> Parentheses around case IS PSR-2. But what about the rest?

> Sadly, have no time now to check it on my own.

So for the moment, it's a good reason to separate fixers with common code abstract class.

I nearly finish the refactor.

**Comment by keradus** [comment]
> Well, this method is going to be remove and will make some trouble with @GrahamCampbell StyleCI application IMO.

Yes, the interface on 2.x line has changed, that's why it is MAJOR bump. There is really no need to create 5 fixers that do the same.
About StyleCI - then raise an issue for StyleCI...

> I was not clear. I mean fixers could be merge onto one with options an master.

They could be combined on 1.x too.


> So for the moment, it's a good reason to separate fixers with common code abstract class.

Even if one keyword could be fixed on PSR and one not - then keep all PSR as default. Voila!

**Comment by keradus** [comment]
ref #1550
