### ISSUE TITLE
Feature request: `case`: no space before ":"

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1542]
```php
switch ($foo) {
    case 'bar' : break;
    // fixed to:
    case 'bar': break;
}
```

**Comment by Soullivaneuh** [comment]
Is that related to any PSR/convention?

**Comment by SpacePossum** [comment]
The example here:
http://www.php-fig.org/psr/psr-2/#5-2-switch-case..

show no space, however there is no rule defined it seems.

**Comment by Soullivaneuh** [comment]
@SpacePossum the rules are implicit:

> Note the placement of parentheses, spaces, and braces.
