### ISSUE TITLE
mt_rand -> random_int fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1547]
This is actually symfony 2.8's standard, due to the polyfill stuff.

**Comment by GrahamCampbell** [comment]
For that reason, we probably have to put it in the contrib level.

**Comment by SpacePossum** [comment]
how is that possible `random_int` is PHP 7 and symfony 2.8 supports PHP 5.3.9 https://github.com/symfony/symfony/blob/2.8/composer.json#L19 ?

**Comment by GrahamCampbell** [comment]
> how is that possible random_int is PHP 7 and symfony 2.8 supports PHP 5.3.9

Symfont 2.8 use symfony's polyfill stuff that defines that function for us.

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/symfony/blob/2.8/composer.json#L29

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/polyfill-php70/blob/master/composer.json#L20

**Comment by GrahamCampbell** [comment]
https://github.com/paragonie/random_compat/blob/master/lib/random_int.php

**Comment by SpacePossum** [comment]
ah I see, pretty cool stuff, thanks for the details :)
so `contrib` and `risky` makes sense ;)

(unless we make it possible to hint to the fixer that it is ok to generate PHP 7 code.. then this would not be risky and could be on Symfony level)

**Comment by stof** [comment]
IMO, we should still consider it as risky and contrib level

**Comment by GrahamCampbell** [comment]
> IMO, we should still consider it as risky and contrib level

Yeh, I agree, since it's not something used on swiftmailer, or symfony 2.3.

**Comment by kalessil** [comment]
Covered by #1617
