### ISSUE TITLE
Tag for Symfony@^3.0

### ISSUE THREAD

**Issue by mmoreram** [FriendsOfPHP/PHP-CS-Fixer#1553]
Could you please tag this application in order to allow people update their composer with symfony3 compatibility, please? :)

Thanks!

**Comment by GrahamCampbell** [comment]
Symfony 3's not released yet.

**Comment by mmoreram** [comment]
No is not, but some of us are testing it. Just being permissive is something we've working on for the last days...

`^2.7` => `^2.7|^3.0`

**Comment by mmoreram** [comment]
@GrahamCampbell btw, Symfony3 is released somehow

https://github.com/symfony/symfony/releases/tag/v3.0.0-BETA1

**Comment by GrahamCampbell** [comment]
Not a stable release yet.

**Comment by mmoreram** [comment]
Yeah, thanks for that information.

**Comment by GrahamCampbell** [comment]
Anyway, the 1.11.0 release isn't too far of. Nagging for it to be released isn't really very helpful. Please close this.

**Comment by mmoreram** [comment]
Nagging? I'm just asking for a tag release, and you say I'm nagging?
How we say in Catalan... "Bon vent maco!"

**Comment by GrahamCampbell** [comment]
I think https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1541 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1527 are definitely getting merged before the release. Potentially some others though too.

**Comment by mmoreram** [comment]
https://en.wikipedia.org/wiki/Continuous_delivery

**Comment by GrahamCampbell** [comment]
This is short cycles. As I said, stop being impatient. :P

**Comment by GrahamCampbell** [comment]
We're at the user review stage before release atm.

**Comment by GrahamCampbell** [comment]
If you're fine using unrelased symfony, then go ahead and use `1.11.*@dev` here. It's pretty solid IMO.

**Comment by Soullivaneuh** [comment]
@mmoreram Just why not installing php-cs-fixer on your global env instead of per project?

**Comment by mmoreram** [comment]
@Soullivaneuh because my project is an open source project, and if I do that, then each time a developer applies the fixer will do it with a different version of the code (same as PHPUnit), and this is something that has already carried me some problems indeed...

**Comment by Soullivaneuh** [comment]
Just adding a `.php_cs` confil file on project should do the trick, isn't it?

BTW, PHPUnit and PHP-CS-Fixer are tools that can be installed globally by developers.

Those ones does not necessary want to have such dependencies on projects IMHO. ;-)

**Comment by keradus** [comment]
PHPUnit as project dependency? wow...

**Comment by mmoreram** [comment]
@keradus https://github.com/laravel/laravel/blob/master/composer.json#L14, for example.

If I use in my tests Prophecy for mocking objects, then I have to make sure that PHPUnit is `>=4.5.0`. Same for this library. If my code follow an standard introduced in some version, then I need to make sure that all developers applies the right version of the library (yes, we have a .php_cs file, but if you want to make sure nothing changes, then you need to define your Fixers one by one there... and this is not that good...)

Yes, some libraries to add (less than 3 seconds) on development. But with that, I can create a composer script for testing and for fixing just after composer update is done. Less installation, less complications, and the project is ready to go easier and faster. Technology is not always for technicians...
