### ISSUE TITLE
Feature request: "\n" to PHP_EOL

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1561]
For cross platform compatibility, it's better to use `PHP_EOL` constant instead of `\n`.

So this:

``` php
echo "This is a line with a new line at end\n"
echo "\n\n\n"
echo 'Single quote sentence'."\n"
```

Would be converted to this:

``` php
echo "This is a line with a new line at end".PHP_EOL
echo PHP_EOL.PHP_EOL.PHP_EOL
echo 'Single quote sentence'.PHP_EOL
```

This fixer should be run **before** `single_quote`.

I take example with linux `\n`, but we have to think about windows string constants.

**Comment by GrahamCampbell** [comment]
> For cross platform compatibility, it's better to use PHP_EOL constant instead of \n.

TBH, I don't agree there. I prefer consistent output on all systems, so I'd always hardcode the line ending.

**Comment by gharlan** [comment]
> TBH, I don't agree there. I prefer consistent output on all systems, so I'd always hardcode the line ending.

Agree.
So I would not vote :-1: on that fixer, but it should be in contrib level and marked as risky.
And I don't need that fixer. ;)

**Comment by Soullivaneuh** [comment]
Would not use `\n` on Windows break the output?

I'm ok for contrib fixer (This is where I wanted to put it), but why mark this as risky?

**Comment by GrahamCampbell** [comment]
> Would not use \n on Windows break the output?

You can just use `\r\n` and windows and linux will both display a single newline... I think. I never really care about windows compatibility much when I'm writing code, even though I'm using Windows to write the code. :P

**Comment by stof** [comment]
@Soullivaneuh it depends what is receiving the output. And many places dealing with ``\n`` may not be about outputting (for instance something splitting the source code into lines), in which case forcing to use PHP_EOL would *break* the code on Windows (as you can have LF newlines in the code).
Btw, this is a real bug: PhpSpec 2 suffered from this bug in its error rendering (which displays a file except) in the first 2.0 releases

**Comment by Soullivaneuh** [comment]
Ok so could be risky. Thanks, will think about it.

**Comment by SpacePossum** [comment]
Hi @Soullivaneuh and thanks for the suggestion.
Looking at the feedback from the community I think the fixer would not be popular enough for it to be part of the fixers provided by this repo. Secondly I think the `riskyness` of the fixer would be higher than we would like the fixers in this repo to be.
Therefor I'm closing this ticket. Thank you for the suggestion and talking to us, feel free to comment on this some more.

**Comment by jorismak** [comment]
as example - and I'm necroposting, I know - the textarea html spec says line endings should be normalized to LF. I see a lot of people coding it as PHP_EOL, which is then wrong _if_ you are on Windows. In this case, you want a hardcoded \n, so just writing \n instead of PHP_EOL would be the _better_ code.

So blindly replacing newlines to PHP_EOL sounds risky to me.
