### ISSUE TITLE
Spacing of Tokens of a for-loop should be one space

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1564]
```php
<?php
for($i=0;$i<4;--$i) {
    
}
```

to

```php
<?php
for($i = 0; $i < 4; --$i) {
    
}
```

http://www.php-fig.org/psr/psr-2/#5-4-for

for ref:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1518#discussion_r46253083

We need a fixer (fixing spaces around ";" in for-loop) for this ;)

**Comment by gharlan** [comment]
I would also like if this is fixed:

```php
for ( $i = 0 ; $i < 4 ; --$i ) {}
```

**Comment by SpacePossum** [comment]
agreed :)
working on a fixer at the moment

**Comment by keradus** [comment]
Please, finish the opened one first ;)

**Comment by SpacePossum** [comment]
>Please, finish the opened one first ;)

no worries, I'm on my max of the open PRs/issues I can handle right now ;)

**Comment by SpacePossum** [comment]
When using `unalign_equals`, `spaces_before_semicolon` ,` parenthesis`
and updating the `OperatorsSpacesFixer` to fix to max one space fixing (with or without linebreak), we only need a fixer for `; --$i ` to `;--$i`.
So... does anyone know why the `OperatorsSpacesFixer` ensures one space but does not remove extra spacing?

What would be nice in the future is to move the logic of, for example `unalign_equals`, to a trait, that way we could create a new fixer, like a `loop` fixer, that is atomic (i.e. you don't need to run the `unalign_equals` on all the code), without code duplication. Just thinking out loud here ;)

**Comment by keradus** [comment]
Loop fixer must not call `unalign_equals` on code itself. And remove few spaces only inside loop condition isn't hard.

> So... does anyone know why the OperatorsSpacesFixer ensures one space but does not remove extra spacing?

By design, since some don't want extra spaces to be removed.

**Comment by SpacePossum** [comment]
>Loop fixer must not call `unalign_equals` on code itself. 

I figured ;)

>And remove few spaces only inside loop condition isn't hard.

Prop. not, but for adding spacing it is a bit more complex. My point is, the `unalign_equals` has the exact code I need, so I'll prop. copy paste it, which is not like DRY.. but since we cannot put that code in a trait the other option would be extending, which makes not much sense and would only work for the logic of one fixer.

>By design, since some don't want extra spaces to be removed.

fair enough :)

**Comment by keradus** [comment]
> for adding spacing it is a bit more complex

???
find the loop, get content between `(` and `)`, add `[T_WHITESPACE, ' ']` after `;` if needed, done.

**Comment by SpacePossum** [comment]
>???
>find the loop, get content between ( and ), add [T_WHITESPACE, ' '] after ; if needed, done.

```
<?php
for($i=0;$i<4;--$i) {

}
```

there is spacing needed after `>` as well in this example. So the fixer should do that otherwise the fixer won't be atomic, i.e. you cannot fix loops without using multiple fixers.

**Comment by keradus** [comment]
then it's still extra easy, can't see why you want to use `unalign_equals` here! :|

**Comment by SpacePossum** [comment]
I want to use the logic of the fixer (not the fixer itself),
because it does this:

```php
for ($i =      0;$i < 4;--$i) {
```

```php
for ($i = 0;$i < 4;--$i) {
```

which we need and no other fixer does (afaik)

**Comment by keradus** [comment]
`unalign_equals` is one of smallest fixers here, and if you would like to use it inside new one then you would need to extend unalign_equals. pointless.

second thing is that `unalign_equals` will already remove extra spaces here. and other fixers will add spaces around `=` and so on... 

the things that are indeed to do:
- check if there is a fixer for:
```diff
-for ( $i = 0 ; $i < 4 ; --$i ) {}
+for ($i = 0 ; $i < 4 ; --$i) {}
```
- create a fixer for:
```diff
-for ($i = 0 ;$i < 4 ;--$i ) {}
+for ($i = 0; $i < 4; --$i) {}
```

**Comment by SpacePossum** [comment]
Yes, so the approach for PSR 5.3, 5.4 and 5.5 is not one (atomic) fixer, but using multiple fixers that all do a little and do that little on all the code and not just loops. Fine by me :)

**Comment by keradus** [comment]
a little but in more places, then you have an atomic not in favour of place, but of rule ;)
