### ISSUE TITLE
NewlineAfterOpenTagFixer - add to symfony level

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1568]
I would like to add the fixer to symfony level.
(checked symfony master branch: no issues.)

If you agree: 1.12 or 2.0?

**Comment by keradus** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/CONTRIBUTING.md#quick-guide
2nd point

**Comment by stof** [comment]
it makes sense to have it at the symfony level. :+1: from me.

**Comment by keradus** [comment]
See the following fixers:
* blankline_after_open_tag
* newline_after_open_tag

**Comment by keradus** [comment]
blankline works great when you don't have content in same line as open tag, like `<?php $foo = 1;`
newline will be problematic for templates

**Comment by keradus** [comment]
(sorry for accidentally closing)

**Comment by stof** [comment]
ah indeed. The Symfony level indeed has blankline, which is what we want.

**Comment by gharlan** [comment]
> See the following fixers:
> 
> * blankline_after_open_tag
> * newline_after_open_tag

Oh ok :D

Then `newline_after_open_tag` is useless, because `blankline_after_open_tag` does the same and more ;)

> blankline works great when you don't have content in same line as open tag, like <?php $foo = 1;
> newline will be problematic for templates

both fixer check for monolithic php.

> https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/CONTRIBUTING.md#quick-guide
> 2nd point

I was not sure if it is a bc break to move the class.

**Comment by keradus** [comment]
> Then newline_after_open_tag is useless, because blankline_after_open_tag does the same and more ;)

Nope, please take a closer look to examples in tests. they are quite different and one doesn't cover second.


> > blankline works great when you don't have content in same line as open tag, like <?php $foo = 1;
> > newline will be problematic for templates
> 
> both fixer check for monolithic php.

Template like `<?php echo "foo"; ?>` isn't monolitic, but since it's template change proposal to multiline version was rejected. This is why second fixer goes to contrib level. (Symfony follows that rule in most places, but not everywhere - and doesn't want to follow it everywhere)

**Comment by gharlan** [comment]
> Nope, please take a closer look to examples in tests. they are quite different and one doesn't cover second.

The only difference I could found: newline_after_open_tag checks that there is at least one newline after open tag, blankline_after_open_tag checks for one blank line.

Both fixer ignore non-monilithic files, one-line files and files container short open tag.

So imo newline_after_open_tag is useless, when using blankline_after_open_tag.

> Template like <?php echo "foo"; ?> isn't monolitic

It is monolithic, but it is ignored by both fixer because it's a one-liner.

**Comment by keradus** [comment]
BlanklineAfterOpenTagFixer will do it, but NewlineAfterOpenTagFixer wont:
```diff
 <?php
+
 $foo = true;
```

NewlineAfterOpenTagFixer will do it, but BlanklineAfterOpenTagFixer wont:
```diff
-<?php $foo = true;
+<?php
+$foo = true;
 $bar = false;
```

So any of the fixer does both.



> It is monolithic

Yeah, wrong shortcut of mine :D


> but it is ignored by both fixer because it's a one-liner.

Oh, then indeed, please run `NewlineAfterOpenTagFixer` on Symfony 2.3 and show the diff :D

**Comment by gharlan** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1030#issuecomment-76395777

> Right, they are not conflicting indeed, but doesnt make sense to run both, as the other one, does what this one does, plus a bit more

---



> NewlineAfterOpenTagFixer will do it, but BlanklineAfterOpenTagFixer wont:
> 
> -<?php $foo = true;
> +<?php
> +$foo = true;
>  $bar = false;

hmm? https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Tests/Fixer/Symfony/BlanklineAfterOpenTagFixerTest.php#L74-L83

> Oh, then indeed, please run NewlineAfterOpenTagFixer on Symfony 2.3 and show the diff :D

```
$ php-cs-fixer fix --fixers=newline_after_open_tag -vv
Loaded config from "[...]/symfony/.php_cs"
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 7.620 seconds, 16.250 MB memory used
```

**Comment by keradus** [comment]
why........................ :|


In that case, if it is that BlanklineAftertOpenTag covers NewlineAfterOpenTag, and first one is already on Symfony, there is no need to move second one there

**Comment by gharlan** [comment]
> In that case, if it is that BlanklineAftertOpenTag covers NewlineAfterOpenTag, and first one is already on Symfony, there is no need to move second one there

Yes, that's the reason why I've closed this. ;)

**Comment by keradus** [comment]
haha :dancer: 
ok, great, sorry for confusion :/

**Comment by gharlan** [comment]
no prob ;)
