### ISSUE TITLE
Travis: symfony versions

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1582]
At the moment we are using this matrix:

PHP | Symfony
--- | ---
5.3 | 2.x (lowest)
5.4 | 2.8
5.5 | 3.0
5.6 | 2.8 and 3.0
7.0 | 3.0
hhvm | 3.0

Why are we running PHP 5.6 with Symfony 2.8 and 3.0, but PHP 5.5 and 7.0 only with Symfony 3.0?
It does not make sense to me.

**Comment by keradus** [comment]
Once, when Symfony 3 wasn't stable, we have run Symfony 3.0 only on PHP 5.6.
Now it could be simplified, good point!
