### ISSUE TITLE
Broken method_argument_default_value fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1587]
Just tested this out on Laravel. The first change is wrong, but the second one is fine.

![image](https://cloud.githubusercontent.com/assets/2829600/11692490/9a9e1f08-9e97-11e5-8817-4bdd674c6c1b.png)

**Comment by keradus** [comment]
Please send a test case ready to copy-paste instead of images :/

**Comment by keradus** [comment]
anything like used version would be great ;) I have strong feeling it is only on 2.x line
