### ISSUE TITLE
Broken class_definition fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1588]
This class needed fixing, but the fix it did was wrong.

![image](https://cloud.githubusercontent.com/assets/2829600/11692620/5471c966-9e98-11e5-81fe-747d7569d795.png)

**Comment by keradus** [comment]
What the fixer was is good. this class has multilined interfaces so he move each interface to separate line.
We just don't have a fixer that will indent the interfaces list, which is outside of `class_definition` scope.

**Comment by SpacePossum** [comment]
imho this is not a bug but a feature request for a indent fixer, but I'm biased since I puzzled the fixer together ;)

**Comment by keradus** [comment]
> **indentation [PSR-2]**
> Code MUST use an indent of 4 spaces, and MUST NOT use tabs for indenting.

**Comment by keradus** [comment]
new one will be needed

**Comment by SpacePossum** [comment]
new fixer, or add functionality to the current fixer?

**Comment by SpacePossum** [comment]
please update the title @GrahamCampbell :)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
at least I close tickets with some comments why @GrahamCampbell ;P

**Comment by GrahamCampbell** [comment]
Someone else can feel free to open a new issue and/or address this. I've lost interest in this one I'm afraid. I've already got plenty of other issues to address.
