### ISSUE TITLE
Split strings with comments concat_without_spaces --level=symfony

### ISSUE THREAD

**Issue by ABM-Dan** [FriendsOfPHP/PHP-CS-Fixer#1589]
I have a string structured like 
```php
<?php
        $longString = '*'
            .'*****'
            .'*****'
            .'*****'
            // Comment about next line
            .'*****'
            // Other comment
            .'*****'
            .'*****'

            .'*****'

            .'*****'
            .'*****'

            .'*****';
```
When running the fixer at symfony level, it gets "cleaned up" to this
```php
<?php
        $longString = '*'
            .'*****'
            .'*****'
            .'*****'
            // Comment about next line
.'*****'
            // Other comment
.'*****'
            .'*****'

            .'*****'

            .'*****'
            .'*****'

            .'*****';
```
Is this supposed to happen??

**Comment by SpacePossum** [comment]
Hi,
Could you provide the version of the Fixer you are using?
And did you indent the lines with spaces or tabs and are you using Windows linebreaks (`\r\n`) ?

**Comment by ABM-Dan** [comment]
Version 1.11
Windows line-breaks
indenting with spaces (the example fits)

I did not try to isolate to reproduce, but the example is very close to the original.

**Comment by GrahamCampbell** [comment]
We don't support windows line breaks. Some fixers assume unix only.

**Comment by ABM-Dan** [comment]
Switched to unix linebreaks, bug remains.

**Comment by ABM-Dan** [comment]
Updated the example, you can copy and paste that into a php file and replicate the error.

**Comment by SpacePossum** [comment]
confirmed bug on 1.12 @ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1590 for proof (no fix (yet ;) ) )

This fixer suffers from the missing transformer that is on master that makes a trailing line break after a comment a white space token (and I found another little bug as well ;) )

**Comment by keradus** [comment]
@SpacePossum is it working on 2.x line ?

**Comment by SpacePossum** [comment]
yes it does, the transformer seems to do the trick in this case

**Comment by ABM-Dan** [comment]
This is still occurring.

**Comment by SpacePossum** [comment]
I guess you tried on 1.11.6? The fix is done after that release, so you've to wait for that one (1.11.7) or run the fixer from source. Let me know if it is still an issue :)

**Comment by ABM-Dan** [comment]
Oh yeah, I thought .6 was the correct version.
