### ISSUE TITLE
Exit status code without --dry-run

### ISSUE THREAD

**Issue by uuf6429** [FriendsOfPHP/PHP-CS-Fixer#1593]
As a result of the issue #158, `php-cs-fixer` exits with a value of 1 when changes are found, regardless if `--dry-run` was specified or not.

Ideally, when `--dry-run` is disabled and the status is non-zero it should either mean an error occurred, or some issues cannot be fixed automatically.

**Comment by ktomk** [comment]
@uuf6429: Perhaps you can resurrect it, to which that time existing issue did you refer to?

**Comment by SpacePossum** [comment]
@ktomk please open a new issue/report if you want to discuss this, a lot has changed the last 2 years so this issue is no longer relevant. Thanks!
