### ISSUE TITLE
align_double_arrow doesn't recognize separate arrays

### ISSUE THREAD

**Issue by cryode** [FriendsOfPHP/PHP-CS-Fixer#1596]
I'm not sure if it's possible or worth it to fix this, given the original syntax is not something most developers would choose to use. I figured I'd share this anyway and let the project maintainers decide.

Original code:

```php
$array = array_merge(['foo' => 'bar'], [
    'fizz' => 'buzz',
    'php-cs-fixer' => 'is great!',
    'hello' => 'world',
]);
```

Command:

```bash
$ php-cs-fixer fix csfix.php --fixers="align_double_arrow"
```

Actual result:

```php
$array = array_merge(['foo' => 'bar'], [
    'fizz'                  => 'buzz',
    'php-cs-fixer'          => 'is great!',
    'hello'                 => 'world',
]);
```

Expected result:

```php
$array = array_merge(['foo' => 'bar'], [
    'fizz'         => 'buzz',
    'php-cs-fixer' => 'is great!',
    'hello'        => 'world',
]);
```

**Comment by SpacePossum** [comment]
Hi,
Thanks for the detailed report, could you give the version of the PHP-CS-Fixer you are using as well?

**Comment by GrahamCampbell** [comment]
I think this was fixed in 1.10.2 or something close to that version.

**Comment by cryode** [comment]
Thank you for reminding me about the version. The issue I was having was on version 1.10.2. I updated my global Composer install to 1.11 and am now getting the expected result. Looks like this was indeed resolved previously!

Thank you for your time, and a great product. Cheers.

**Comment by SpacePossum** [comment]
good to hear :)  :+1:
