### ISSUE TITLE
OrderedUseFixer - Ordering is off

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1598]
Input:
```php
use Foo\Bar\FooBar as FooBaz;
use Zoo\Bar, Zoo\Tar;
use Symfony\Annotation\Template;
use Foo\Bar\Foo as Fooo, Foo\Bir as FBB;

use Symfony\Doctrine\Entities\Entity;
```

Fixed to:
```php
use Foo\Bar\Foo as Fooo;
use Foo\Bar\FooBar as FooBaz, Foo\Bir as FBB;
use Symfony\Annotation\Template;
use Symfony\Doctrine\Entities\Entity, Zoo\Bar;

use Zoo\Tar;
```

Expected:
```php
use Foo\Bar\Foo as Fooo;
use Foo\Bar\FooBar as FooBaz, Foo\Bir as FBB;
use Symfony\Annotation\Template, Symfony\Doctrine\Entities\Entity;
use Zoo\Bar, Zoo\Tar;
```

Please note: I don't mind/want the merging of imports, but splitting `use Zoo\Bar, Zoo\Tar;` up and add one part the `Symfony` `use` is kind of odd.

**Comment by keradus** [comment]
Fixer does not sort lines and does not remove empty line between fixer. Its sort imported classes in way they are written down.

The input code has 2 multi-import statement, your "expoected" has 3. Input code has 5 lines, yours hase 4.

Fixing is good. For other rules (like remove empty line, explode multi-import statements) use other fixers ;)

**Comment by SpacePossum** [comment]
I don't mind the white spacing ;)

I still don't see why `use Zoo\Bar, Zoo\Tar;` is made into two parts.

**Comment by gharlan** [comment]
Are you sure that your are not using the MultipleUseFixer (psr2)?

**Comment by keradus** [comment]
@SpacePossum , take a look at this:
```php
use Foo\Bar\FooBar as FooBaz;
use Zoo\Bar, Zoo\Tar;
use Symfony\Annotation\Template;
use Foo\Bar\Foo as Fooo, Foo\Bir as FBB;

use Symfony\Doctrine\Entities\Entity;
```

is treated like:
```php
use SLOT_1;
use SLOT_2, SLOT_3;
use SLOT_4;
use SLOT_5, SLOT_6;

use SLOT_7;
```

Then, all imports are taken from slots, sorted and put it back to slots. Without changing anything else, like you suggest (eg combining 2 T_USE into one)

**Comment by SpacePossum** [comment]
Thanks for the details @keradus :+1:  :)
I can see why this is done like this and is done well :+1: 

I was thinking a bit more on it and wanted to ask you would find of this RFC (maybe as configuration option or opening up the Fixer so it would be possible to implement another sorting algorithm):

input
```
[A,Z]
[W,E]
[Y]
[B, C]
[D]
[F, G, H]
```
step 1, sort the lines;
```
[A,Z]
[B, C]
[D]
[F, G, H]
[W,E]
[Y]
```

step two, check lines for mulitple input, if not sorted break those up;
```
[A]
*[Z]
[B, C]
[D]
[F, G, H]
[W]
*[E]
[Y]
```
sort the lines again:
```
[A]
[B, C]
[D]
[E]
[F, G, H]
[W]
[Y]
[Z]
```

**Comment by keradus** [comment]
I think there is no need for that.
Split multiple import into single import, then sort. One import per line in alphabetic order.

**Comment by SpacePossum** [comment]
thanks, will think about it,
