### ISSUE TITLE
PhpdocOrderFixer - order?

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1602]
Current PhpdocOrderFixer produce the following order:

``` php
/**
 * @param
 *
 * @throws
 *
 * @return
 */
```

What is the reason of keeping that order, not the param-return-throws ? Is is standardized by PSR?

**Comment by keradus** [comment]
cc @GrahamCampbell

**Comment by keradus** [comment]
btw
Files that does not follow that order for Symfony repo (2.3 branch) - 224.
Files that does not ollow param-return-throws order - 18.

**Comment by GrahamCampbell** [comment]
param-throws-return is implied by PSR-5, and is actually the lexical ordering.

**Comment by GrahamCampbell** [comment]
It also makes sense to me because you throw before you return. ;)

**Comment by keradus** [comment]
> param-throws-return is implied by PSR-5

could you ref that?

**Comment by GrahamCampbell** [comment]
All there examples are in that order, I think?

**Comment by keradus** [comment]
I can see only _one_ example with `@return` and `@throws` annotations.
And nothing in text about it.

**Comment by GrahamCampbell** [comment]
Well, even if all their examples constitutes one example, that's still all of them. I also never said it was written in words. It's just inferred.

**Comment by keradus** [comment]
Damn it... it would be great to standardize it on PSR level

**Comment by GrahamCampbell** [comment]
It might be cool to make this configurable though.

**Comment by GrahamCampbell** [comment]
I personally think symfony should change it's order though. ;P

**Comment by keradus** [comment]
Think so too. That is why I asked for any refs ;)

**Comment by GrahamCampbell** [comment]
I assume symfony has that order, because that would be the lexical order.

**Comment by GrahamCampbell** [comment]
Where does symfony put deprecated tags though? Is that in lexical order, just any order?

**Comment by GrahamCampbell** [comment]
Maybe we just need a new fixer, that puts all tags in lexical order?

**Comment by keradus** [comment]
I would :-1: for that

**Comment by GrahamCampbell** [comment]
Well, why just order those 3 tags, when you could define an ordering for every tag, if symfony does actually have such an ordering.

**Comment by keradus** [comment]
:-1: for order tags in alpha order.
:+1: for order tags in arbitrary order (which may be configured in alpha, but also in different, even custom, eg allowing to pass a list showing the order or function to compare two tags which one should be first)

**Comment by keradus** [comment]
Conclusion:
configuration is required for a fixer, which specifies which tags should be ordered using what order.

Anyone willing to help with it is more than welcome.

**Comment by localheinz** [comment]
> What is the reason of keeping that order, not the param-return-throws ? Is is standardized by PSR?

I think a valid reason for the existing order is this

* a method has input (`@param`)
* a method has ouput (`@return`)
* something can go wrong _after_ accepting the input and _before_ returning the output; an exception can be thrown

Not sure of that was the reasoning behind it, or if @mvriel wants to chime in (sorry!), but I can imagine that this could well be it.

For reference, see 

* https://phpdoc.org/docs/latest/references/phpdoc/tags/throws.html#examples
* https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#719-throws

**Comment by SpacePossum** [comment]
How about the fixer also order `@param` annotations based on the method/function signature (this order is as proposed in the discussion in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2385)?

**Comment by keradus** [comment]
I would rather have 2 fixers:
- one to sort different annotations order, keeping order of same annotations, here, sorting order is defined by user
- sort `param` annotations, order is defined by function prototype

one may run later, but not first rule

**Comment by UksusoFF** [comment]
Any updates for this?

**Comment by kubawerlos** [comment]
@UksusoFF can you check if this [PhpdocParamOrderFixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers) works for you? If so I'd make a PR to add it here.

**Comment by UksusoFF** [comment]
> @UksusoFF can you check if this [PhpdocParamOrderFixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers) works for you? If so I'd make a PR to add it here.

This works but only with `@param`.

**Comment by BenMorel** [comment]
Still no news here?

**Comment by Nuboskill** [comment]
Any news?

**Comment by kubawerlos** [comment]
@BenMorel @Nuboskill looks like it's still waiting for someone to do it.

**Comment by mvriel** [comment]
It seems I never responded to this thread despite being summoned by @localheinz. Let me make up for that by responding now.

phpDocumentor itself does not prescribe a preferred order. In userland, it is common that `@return` follows `@param`, but the position of `@throws` seems to vary from project to project. 

I _personally_ prefer the `@returns` at the end of the DocBlock and the `@param` to be first in the sequence. But the only justification I have for this is that I am used to that and in my mind, it clicks as being input and output nodes of the node that you are documenting.

The above should really be taken as a personal preference and not a recommendation from phpDocumentor
