### ISSUE TITLE
Possible PSR-0 Fixer Bug

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1603]
If the class is renamed such that it conflicts with an import, then we're going to produce a file with invalid syntax when linted. We should skip such cases.

**Comment by keradus** [comment]
Good point. For now the only safeguard is to lint file at the end (we already can do it!).
Also, fixer is risky, so...

But yeah, its worth to check in fixer!

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
> we're going to produce a file with invalid syntax when linted.

Not on the new linter, though, the file will still be broken.

**Comment by keradus** [comment]
The "possible bug" ~report is there for almost a year.
Closing.
If anyone is able and willingly to reproduce/fix it, a PR will be appreciated !

**Comment by GrahamCampbell** [comment]
It's not a possible bug, it's a real bug, and one that've reproduced in the way that I described.

**Comment by SpacePossum** [comment]
maybe provide that in PR form as failing test and if you've time a fix as well?
