### ISSUE TITLE
Performance Analysis

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1604]
As PHP-CS-Fixer grows, it's definitely getting slower. I think we need to look at which fixers are the slowest. Maybe just run them one by one on symfony, then note the results. Basically, it would be good if we could mark certain fixers as "slow".

**Comment by GrahamCampbell** [comment]
Also, one thing we could do is link the Docblock class to the actual token, then only re-parse it if it's content was changed, instead of parsing each phpdoc token multiple times during execution.

**Comment by GrahamCampbell** [comment]
Or, even if we ran fixers together, it might cool to have one kind of way to collect performance details for each fixer.

**Comment by GrahamCampbell** [comment]
If such a thing were to be done, I'd be happy to collect the metrics from StyleCI over a period of a week or something, and report back. That should be a fair bit of data.

**Comment by stof** [comment]
It would be great to work towards releasing the v2, which is intended to be faster thanks to the candidate-based checking

> Also, one thing we could do is link the Docblock class to the actual token, then only re-parse it if it's content was changed, instead of parsing each phpdoc token multiple times during execution.

@GrahamCampbell or adding a cache for the docblock parsing (similar to cache for the code parsing). but anything related to caching docblock parsing would require ensuring that fixers avoid corrupting this cache, to avoid breaking other fixers.

**Comment by SpacePossum** [comment]
>It would be great to work towards releasing the v2, which is intended to be faster thanks to the candidate-based checking

:+1:   
also for not re-tokenizing the code which is a great performance gain :)

**Comment by keradus** [comment]
Actually, first we should measure the performance difference using _same_ fixers on 1.x and 2.x line.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell or adding a cache for the docblock parsing (similar to cache for the code parsing). but anything related to caching docblock parsing would require ensuring that fixers avoid corrupting this cache, to avoid breaking other fixers.

Yeh, the idea is that any fixer that modified the contents of the doc token would flush the cache.

**Comment by stof** [comment]
> also for not re-tokenizing the code which is a great performance gain

this is already the case in most cases in 1.x (thanks to the Tokens cache). What we actually avoid in 2.x is stringifying the tokens again and again

**Comment by GrahamCampbell** [comment]
I'm not talking about tokenization, I'm talking about parsing in our "DocBlock" classes.

**Comment by keradus** [comment]
Closing due to #1872

If one want to improve performance even more he is more than welcome !
