### ISSUE TITLE
[FR] Backtick fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1611]
I find the backtick execution operator (http://php.net/manual/en/language.operators.execution.php) one of the most functionality hiding features in PHP.
Any opions on changing something like;

``` php
<?php
$output = `ls -al`;
echo "<pre>$output</pre>";
?>
```

to

``` php
<?php
$output = shell_exec('ls -al');
echo "<pre>$output</pre>";
?>
```

**Comment by GrahamCampbell** [comment]
:+1: for having this fixer

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
