### ISSUE TITLE
Async Linting

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1612]
Just a thought, but could we save time after fixing each file by making it's linting asynchronous instead of waiting for it to complete before fixing the next file?

**Comment by GrahamCampbell** [comment]
Could we even start async linting the next files before we even get to them too?

**Comment by GrahamCampbell** [comment]
Maybe just iterate one file ahead?

**Comment by gharlan** [comment]
> Maybe just iterate one file ahead?

tried it, the performance gain is more than 20% on my machine. :)

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
Actually I had been thinking about sth more for a long time. To fix whole thing using parallel pool manager independent of env. But that would take a lot of work.
And simplifying it to just proc_open will require heavy app initialization.

So idea of making things async, even in small part, is big :+1:

**Comment by GrahamCampbell** [comment]
What if we were to try do a proper job of making things async. What would you think of using react? https://github.com/reactphp/react

**Comment by SpacePossum** [comment]
or guzzle? any opinions about one or the other?

**Comment by GrahamCampbell** [comment]
What? Guzzle? No?

**Comment by GrahamCampbell** [comment]
We need things like this: https://github.com/reactphp/child-process.

**Comment by keradus** [comment]
big :-1: for using processes for anything other than linting (which one way or another need to be run in separated process)

**Comment by keradus** [comment]
creating new process is not the only way to make things async, but I agree it is the easiest one to implement

**Comment by GrahamCampbell** [comment]
> big :-1: for using processes for anything other than linting

That's not what I'm suggesting.

**Comment by GrahamCampbell** [comment]
I'm going to have a play around wit this.

**Comment by keradus** [comment]
We have it done, closing

**Comment by GrahamCampbell** [comment]
This still isn't actually done though?

**Comment by GrahamCampbell** [comment]
We're not linting the files after fixing in an async way.

**Comment by keradus** [comment]
We have few attempts and one was merged. Feel free to send PR for improving it.
Thread was already dead for 3-4 months, no need to keep it alive IMO.

**Comment by cweiske** [comment]
This here was merged: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/1666

**Comment by Wirone** [comment]
> This here was merged: #1666

Yeah, 8 years ago 😅. You achieve the Archaeologist badge!
