### ISSUE TITLE
Speed up AppVeyor

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1644]
> Is there not something else better out there? AppVeyor is always slow as hell.

AppVeyor could be a lot faster if we start to cache env (php + composer + phpunit).

**Comment by keradus** [comment]
cc @GrahamCampbell

**Comment by stof** [comment]
> AppVeyor could be a lot faster if we start to cache env (php + composer + phpunit)

Composer is already cached (except it does not use the cache yet, because it never managed to install from dist to create the cache, but #1641 would change it).

Caching chocolatey installs would indeed help (not sure if there is an easy way for that)

**Comment by stof** [comment]
ah, maybe you meant caching the download of the phar. Is it really what takes time ?

**Comment by keradus** [comment]
> Caching chocolatey installs would indeed help (not sure if there is an easy way for that)

It can be done for all portable applications. (PHP is one of them)

> ah, maybe you meant caching the download of the phar. Is it really what takes time ?

yes, I meant phars ;)
A bit... mainly setting up the connection.

**Comment by SpacePossum** [comment]
@keradus do you have plans to do this or could we close this one and move it to the backlog?

**Comment by keradus** [comment]
At least it is running again
