### ISSUE TITLE
Exit code 1 multiple meanings

### ISSUE THREAD

**Issue by uuf6429** [FriendsOfPHP/PHP-CS-Fixer#1651]
First of all, I'd like to point out that there are some general questions regarding the exit code (for example issue #1211).

Recently, I was passing a Windows path as a lone argument by mistake, causing a `CommandNotFoundException` because "There are no commands defined in the "C" namespace.".
What was not expected (and in fact caused me some trouble) is the fact that the exit code at this point was 1, which was assumed to mean that "something got fixed but everything is fine", since the [docs seem to say so](https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes).

From one side, it would be nice to have the exit code properly and finally sorted out. On the other hand, I'm slightly concerned that there may be more of the scenario mentioned above... in my case, for example, it would mean that code is committed without fixes whenever the tool doesn't run correctly for whatever reason.

**Comment by keradus** [comment]
Exit codes are revised on 2.x line (cannot do it on 1.x due to not breaking BC).
Thank you for your report @uuf6429 and sorry to keep you waiting for response!

**Comment by uuf6429** [comment]
Ok, fair enough. And no problem re waiting.
