### ISSUE TITLE
[2.x] Conflict between ParenthesisFixer and SpacesAfterSemicolonFixer

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#1655]
Example code:

```php
for ($i = 0; $i < $count;) {
}
```

`SpacesAfterSemicolonFixer` adds a space after last `;`, `ParenthesisFixer` removes it.
This only happens on 2.x. On 1.x the `ParenthesisFixer` does not remove the space.

Example from our codebase:
[1.12 (with space)](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/19b3a016a825b3ba255a4a5790cd7011997c67f4/Symfony/CS/Fixer/Symfony/MethodArgumentDefaultValueFixer.php#L128)
[2.x (without space)](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/e66847bbd397026233bde4500c76c7c997ffa5e7/src/Fixer/Symfony/MethodArgumentDefaultValueFixer.php#L130)

**Comment by gharlan** [comment]
```
$ php php-cs-fixer fix --rules=parenthesis,spaces_after_semicolon -v src/Fixer/Symfony/MethodArgumentDefaultValueFixer.php
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) src/Fixer/Symfony/MethodArgumentDefaultValueFixer.php (spaces_after_semicolon)
Fixed all files in 0.113 seconds, 6.000 MB memory used

$ php php-cs-fixer fix --rules=spaces_after_semicolon,parenthesis -v src/Fixer/Symfony/MethodArgumentDefaultValueFixer.php    
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) src/Fixer/Symfony/MethodArgumentDefaultValueFixer.php (parenthesis)
Fixed all files in 0.120 seconds, 6.000 MB memory used
```

**Comment by keradus** [comment]
Then, the question is do we want to have that space or not ;)

**Comment by gharlan** [comment]
I do not want it.

**Comment by SpacePossum** [comment]
Should the `SpacesAfterSemicolonFixer` be updated not to add the space, or should this be solved by fixer priorities tweaking?

**Comment by gharlan** [comment]
> Should the SpacesAfterSemicolonFixer be updated not to add the space

:+1:

**Comment by GrahamCampbell** [comment]
I disagree that it's a priority issue. We don't really want a situation where one fixer makes a change, then another reverts it. We should just update the first fixer to not make that change for that case surely?

**Comment by gharlan** [comment]
> I disagree that it's a priority issue.

Nobody said that. @SpacePossum has asked a question, and I agree with you. ;)

Could we add tests to avoid those conflicts generally? 
(Found this case by chance..)

**Comment by SpacePossum** [comment]
I want the space :)

>Could we add tests to avoid those conflicts generally? 

we could create an integration tests for all combinations using all not conflicting fixers using input code with as much as possible PHP features that is correctly formatted. If we ran the tests the fixers should not have changed the code, nor changed back the fixed code of another fixer configured.

**Comment by gharlan** [comment]
> I want the space :)

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#54-for
"Note the placement of parentheses..."
It is not totally clear, but I think the space is not allowed by PSR-2.

**Comment by SpacePossum** [comment]
the example shows a space after the second `;`, so yeah.. it is not totally clear ^-^

**Comment by keradus** [comment]
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#5-control-structures

> There MUST NOT be a space before the closing parenthesis


we should not allow for space after last `;` in `for` statement

**Comment by SpacePossum** [comment]
check, so this is a bug report on `SpacesAfterSemicolonFixer` :)

**Comment by keradus** [comment]
want fix it ?:)

**Comment by SpacePossum** [comment]
typing now ;)

**Comment by keradus** [comment]
great! thanks ;) I think we will have 1.11.1 today ;)

**Comment by keradus** [comment]
fixed on 1.x by #1684
