### ISSUE TITLE
Broken switch case fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1656]
This should break the fixer:

```php
        switch ($json['type']) {
            case 'zikula-module':
            case 'zikula-theme':
            case 'zikula-plugin':
                break;
            default;

                return false;
```

**Comment by SpacePossum** [comment]
maybe put this case in the test of the fixer and into a PR and we all see it break ;)

**Comment by GrahamCampbell** [comment]
I didn't have much time so I just dumped it into an issue. Later on, I'll add a test case and look into why it's actually failing.

**Comment by keradus** [comment]
To put some more valid code:
```php
switch($foo) {
    case '123';
    case '456';
        return 1;
    default;
        return 2;
}
```

the problem is that case may be followed by `;` as well, and we look for `:` only

**Comment by SpacePossum** [comment]
can be closed :)

**Comment by keradus** [comment]
thx
