### ISSUE TITLE
Case statement semicolon to colon fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1658]
Ref #1656.

**Comment by keradus** [comment]
?

**Comment by GrahamCampbell** [comment]
Both semicolons and colons are valid, but what if we have a cs rule that says we want colons only?

**Comment by keradus** [comment]
Oh, a feature request, lack of any descr give me the expression that this is just another bug report.

:+1:

**Comment by GrahamCampbell** [comment]
Sorry about that. ;)

**Comment by SpacePossum** [comment]
can be closed ;)

**Comment by keradus** [comment]
thx
