### ISSUE TITLE
Change "risky" to "heuristic"

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1665]
This description better fits fixers that might incorrectly change the case of a function, but without technically breaking the code.

**Comment by keradus** [comment]
:-1:
http://www.merriam-webster.com/dictionary/heuristic

**Comment by GrahamCampbell** [comment]
That definition is crap. Heuristic has a specific meaning in computer science.

**Comment by GrahamCampbell** [comment]
https://en.wikipedia.org/wiki/Heuristic_(computer_science)

**Comment by GrahamCampbell** [comment]
Heuristic perfectly fits what we're doing here.

**Comment by GrahamCampbell** [comment]
> That definition is crap.

Infact, that's literally the worst definition I've ever seen!

**Comment by GrahamCampbell** [comment]
Ping @keradus.

**Comment by keradus** [comment]
1-1, great to have any other thoughts.

**Comment by SpacePossum** [comment]
>This description better fits fixers that might incorrectly change the case of a function, but without technically breaking the code.

These fixers are not (and should not IMO) be marked as `risky`. Not sure if it is worth it to add the option to mark fixers are being `heuristic` as long as we only have one case (i.e. changing the fixer description would result in the same output without the overhead), so I'm -1 on this.
