### ISSUE TITLE
unneeded "else" or "elseif" remover

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1672]
### Fixer request.

Before:

```php
<?php

function stuffs($foo, $bar, $baz)
{
    if ($foo) {
        return $bar;
    } elseif ($baz) {
        return $foo;
    } else {
        return $baz;
    }
}
```

After:

```php
<?php

function stuffs($foo, $bar, $baz)
{
    if ($foo) {
        return $bar;
    }

    if ($baz) {
        return $foo;
    }

    return $baz;
}
```

**Comment by SpacePossum** [comment]
I think I've a fixer for the useless `else` case in a heavily hacked PHP-CS-Fixer. There are some TODO's on that one... here are some thoughts ;)
- it must ran before the useless return fixer
- the useless return fixer should be able to deal with multiple useless returns after each order (current missing feature)
- it must ran before any kind of empty line / trailing whitespace fixer
- it must ran before any indenting fixer
- it must detect the useless else correctly for not being risky, which includes detecting the use of `GOTO` within the overall structure the `else` is defined in

**Comment by SpacePossum** [comment]
another unneeded case
```php
if ($a) {
    throw new \Exception('');
} else {

}
```

**Comment by gharlan** [comment]
same for `continue` and `break`

**Comment by gharlan** [comment]
> it must detect the useless else correctly for not being risky, which includes detecting the use of GOTO within the overall structure the else is defined in

could you give an example with `goto` where code behavior would change?

**Comment by SpacePossum** [comment]
I cannot, I'm not sure why I put that as a TODO in my code .. ... .

**Comment by gharlan** [comment]
first after reading I thought "good point", but after more thought I could not find an example ;)

**Comment by SpacePossum** [comment]
the "elseif" is still valid, although hard to make ;)
