### ISSUE TITLE
Bug with class method and docblock indentation

### ISSUE THREAD

**Issue by akalongman** [FriendsOfPHP/PHP-CS-Fixer#1679]
When I format code like:
```php
class Test
{
/**
* Add an element to an array using "dot" notation if it doesn't exist.
*
* @param  array   $array
* @param  string  $key
* @param  mixed   $value
* @return array
*/
public static function add($array, $key, $value)
{
if (is_null(static::get($array, $key))) {
static::set($array, $key, $value);
}

return $array;
}

}
```
Method and docblock not indented inside class. Why?
I'm using psr2 format (```php-cs-fixer fix --level=psr2 Test.php```)

**Comment by keradus** [comment]
to help us debugging, please check your version:
`php-cs-fixer --version`

**Comment by akalongman** [comment]
Yes, sorry.
```PHP CS Fixer version 1.11 by Fabien Potencier (bd3ec2c)```

**Comment by keradus** [comment]
Thanks.
Isn't it #1196 ? (last comment)

**Comment by akalongman** [comment]
Yes, seems like that

**Comment by keradus** [comment]
I thought that too, I'm closing your issue in favor of older one.
We need to check it on 2.x line (on 2.x we change a way of dealing with comments).

**Comment by akalongman** [comment]
@keradus where are 2.x version? When will be released?

**Comment by keradus** [comment]
2.x is on master branch. Whenever we will finish [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/milestones/v2.0)
