### ISSUE TITLE
PhpDoc: no extra empty lines

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1686]
Target: 1.x line

Code before:

``` php
<?php

/**
 * Description.
 *
 *
 * @var int
 */
$foo = 1;
```

Code after:

``` php
<?php

/**
 * Description.
 *
 * @var int
 */
$foo = 1;
```

**Comment by GrahamCampbell** [comment]
We already have a fixer that nearly does that.

**Comment by keradus** [comment]
Updated feature specification to not partially duplicate `PhpdocTrimFixer`

**Comment by GrahamCampbell** [comment]
I didn't originally add a fixer like this on purpose because the integration testing across lots of php repos showed that sometimes multiple lines breaks where indeed wanted, say when using complex markdown or code examples inside the phpdoc.

**Comment by keradus** [comment]
It should not touch content of part of docblock (like annotation/description/summary), but the space between them.
And even if we could not reach that - the fixer would be useful for some repos ;)

**Comment by GrahamCampbell** [comment]
Sure. This should be quite easy to implement.

**Comment by keradus** [comment]
```php
/**
 * Summary.
 *
 *
 * Description.
 *
 *
 * @var int
 *
 *
 * @return int
 */
$foo = 1;
```

Extra blank line shall be removed after Summary and after Description.
One between annotations is already removed by `phpdoc_separation`, probably it shall not do it anymore and it shall be done only by new fixer.

**Comment by julienfalque** [comment]
Why reopening the issue?

**Comment by SpacePossum** [comment]
because I think there are still cases where PhpDoc's have extra empty lines which can/should be removed. Example:

```php
final class ClassKeywordRemoveFixerTest extends AbstractFixerTestCase
{
    /**
     * @param string      $expected
     * @param null|string $input
     *
     *
     *
     *
     * @dataProvider provideFixCases
     */
    public function testFix($expected, $input = null)
    {
        $this->doTest($expected, $input);
    }
}
```

**Comment by keradus** [comment]
would you be fine guys to trim any consecutive blank lines, not only ones after summary/description ?
(as one, single fixer, no config)

**Comment by keradus** [comment]
ref #3802
