### ISSUE TITLE
[RFC] ClassDefinitionFixerTest - add tests for anonymous classes (PHP7)

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1691]

**Comment by Isinlor** [comment]
+1 seems like fixing and sniffing for anonymous classes is broken.

**Comment by SpacePossum** [comment]
Hi @Isinlor, do you have an example of what goes wrong? it will make it easier to start fixing things :)

**Comment by jmalloc** [comment]
I have an example of broken formatting if it's helpful:

```php
rit('can invoke coroutine provider', function () {
    $result = yield new class implements CoroutineProvider
 {
     public function coroutine() : Generator
     {
         return '<ok>';
         yield;
     }
 };
    expect($result)->to->equal('<ok>');
});
```

Source: https://github.com/recoilphp/recoil/blob/master/test/suite-functional/functional.strand.spec.php#L35

It seems that the indenting is "one level too low", and there is an additional space, such that opening brace of the class is indented by one space, and the `coroutine()` method is indented 5 spaces.

Also, some classes that contain anonymous classes have started being skipped altogether:

```
vendor/bin/php-cs-fixer fix
Loaded config from "/Users/james/Documents/GitHub/recoilphp/recoil/.php_cs"
Fixed all files in 4.832 seconds, 8.000 MB memory used

Files that were not fixed due to internal error:
   1) src/React/ReactKernel.php
   2) test/suite-functional/functional.strand.spec.php
```

All this code is in [recoilphp/recoil](https://github.com/recoil/recoil) and can be reproduced by running `make prepare` from a fresh clone.

**Comment by SpacePossum** [comment]
@jmalloc thanks for the report. You reports covers several issue which have to be dealt with in multiple PRs I think. I curious about the last `Files that were not fixed due to internal error`, can you give me the version of the fixer (I fail to reproduce the internal error locally ATM)

**Comment by jmalloc** [comment]
The version appears to be the latest tag - `PHP CS Fixer version 1.11.2`.

**Comment by SpacePossum** [comment]
closed by;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1894 and 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1947
