### ISSUE TITLE
[FR] ExitToDieAliasFixer (and v.v. by config)

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1692]
feature request, I would like to have a fixer to changes all `exit` calls to `die` (and prop. v.v. for other people ;) )

**Comment by keradus** [comment]
isn't die alias for exit ?

**Comment by SpacePossum** [comment]
It is (they have the same token id), it is a language construct to it is not picked up by the `AliasFunctionsFixer`.

**Comment by keradus** [comment]
then I would simply convert alias to non-alias (not v.v.) in `AliasFunctionsFixer`.

**Comment by SpacePossum** [comment]
:+1:

**Comment by gharlan** [comment]
:-1: because it is not a function.

**Comment by SpacePossum** [comment]
Other opions? I like a diff. name (i.e. dedicated fixer) because (as @gharlan stated) it is not a function.

**Comment by keradus** [comment]
I think that @gharlan refuse to incorporate it into `alias_functions`. Create a new fixer then ;)

**Comment by SpacePossum** [comment]
New fixer it is :)

btw. I would like to add configuration options to normalize the default usage; 
```php
exit("");
exit('');
exit(0);
exit();
exit;
```

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
