### ISSUE TITLE
Adds an empty line to small files

### ISSUE THREAD

**Issue by rugk** [FriendsOfPHP/PHP-CS-Fixer#1697]
PHP-CS-Fixer adds an (additional) empty line to some (short) files.

Before:
```php
<?php
/**
 * @author rugk
 */

define('TREE', 'apple');
// a comment

```

After:
```php
<?php
/**
 * @author rugk
 */

define('TREE', 'apple');
// a comment


```

Version: `PHP CS Fixer version 1.11.1 by Fabien Potencier (2c9f829)`

level: PSR2
active fixers:
> 'concat_with_spaces', 'short_array_syntax', 'standardize_not_equal',
              'phpdoc_params', 'operators_spaces', 'duplicate_semicolon',
              'remove_leading_slash_use', 'align_equals', 'phpdoc_params',
              'single_array_no_trailing_comma', 'phpdoc_indent', 'phpdoc_scalar',
              'phpdoc_short_description', 'phpdoc_to_comment', 'phpdoc_trim',
              'phpdoc_types', 'print_to_echo', 'self_accessor', 'single_quote',
              'spaces_cast', 'ternary_spaces', 'phpdoc_order'

**Comment by rugk** [comment]
From what I saw this may have to do with the fact that the last line ends with a commend.

**Comment by GrahamCampbell** [comment]
Ah, yes. PHP must be absorbing that last newline into the comment token.

@keradus Is this something we can deal with at the transformer level. Is it something we already have done in 2.x?

**Comment by GrahamCampbell** [comment]
@rugk Is this still happening in 2.x?

**Comment by rugk** [comment]
2.x? I do not know that such a version exists. Where can I find it? From what I see v1.11.1 is the latest version.

**Comment by GrahamCampbell** [comment]
Yeh, you'll need to download 2.x dev from github. No phar builds exist.

**Comment by GrahamCampbell** [comment]
@keradus It might be cool to have nightly phar builds though for the 3 maintained branches we have.

**Comment by rugk** [comment]
And which [branch](https://github.com/FriendsOfPHP/PHP-CS-Fixer/branches) should I use to download this? I can see no `2.x` branch.

**Comment by GrahamCampbell** [comment]
master

**Comment by rugk** [comment]
Just tried it and indeed it seems to be fixed with the current dev version.

**Comment by GrahamCampbell** [comment]
This issue can be closed then. :)

**Comment by SpacePossum** [comment]
>This issue can be closed then. :)

we don't want this fixed on 1.x line?

**Comment by rugk** [comment]
Possibly we want... 😄

**Comment by GrahamCampbell** [comment]
> we don't want this fixed on 1.x line?

No, we don't. =

**Comment by GrahamCampbell** [comment]
This fix was only made on 2.x because it's non-trivial to make on 1.x.

**Comment by rugk** [comment]
Okay...

**Comment by keradus** [comment]
Comments are tricky as `// foo\n` is treaten by PHP's tokenizer as one token - `T_COMMENT`.
And even `// foo\n___` (_ is space) is treaten as 2 - `T_COMMENT` and `T_WHITESPACE`, but `\n` is still part of first token.
That is why we have created transformer to move that `\n` into following `T_WHITESPACE` (or create one if missing). If one want to make a fix for that on 1.x line it would be merged, but for me there is no need to spend time on it.

BTW, 2.x@dev can be installed by composer as well (`^2@dev`).
