### ISSUE TITLE
Fixer class broken

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1698]
Line 18 `use Symfony\Component\Finder\Finder;` won't work because of a conflict. I get:

```
PHP Fatal error:  Cannot use Symfony\Component\Finder\Finder as Finder because the name is already in use in /home/ubuntu/PHP-CS-Fixer/src/Fixer.php on line 18
```

No idea why travis hasn't picked this up!

**Comment by keradus** [comment]
Always good to know the version ;)

**Comment by GrahamCampbell** [comment]
Very latest commit.

**Comment by GrahamCampbell** [comment]
master

**Comment by keradus** [comment]
It;s od since is works for me locally for both 1.x and 2.x.

I'm using `PHP 5.6.8` and `PHP 7.0.0RC8`

**Comment by GrahamCampbell** [comment]
It shouldn't work though. Look at it, there's clear a naming conflict.

**Comment by keradus** [comment]
I see the conflict. Then it works on my env. That's why it's odd. Probably for the same reason it works on Travis.

**Comment by GrahamCampbell** [comment]
I assume it depends what order the classes are loaded. What happens if you turn on code coverage?

**Comment by keradus** [comment]
no difference

**Comment by GrahamCampbell** [comment]
Oh, this has highlighted the fact that the finder class is never used because your env never loaded it.

**Comment by GrahamCampbell** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1699.
