### ISSUE TITLE
Iterating file twice when provided path twice.

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1706]
When we set the path that should be fixed in both places (config file + [CLI](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Console/Command/FixCommand.php#L360)) tool will iterate through both paths separately, even if those are the same path.

Maybe not a bug, but it will slow down the tool if one use it that way (and I found that it is very common) - an no notice to user is show that he is doing sth wrong, and the fixing part tooks twice much as it should (since it is indeed fixing every single file twice).

I think it was originally reported by @GrahamCampbell as problem connected with symlinks, but we cannot reproduce it then.

**Comment by GrahamCampbell** [comment]
I just use the following patch:

```
diff --git a/src/Fixer.php b/src/Fixer.php
index f020827..2e3acdb 100644
--- a/src/Fixer.php
+++ b/src/Fixer.php
@@ -137,12 +137,20 @@ public function fix(ConfigInterface $config, $dryRun = false, $diff = false)
             $config->getRules()
         );
 
+        $processed = array();
+
         foreach ($config->getFinder() as $file) {
-            if ($file->isDir() || $file->isLink()) {
+            $name = $this->getFileRelativePathname($file);
+
+            if (isset($protected[$name])) {
                 continue;
             }
 
-            $name = $this->getFileRelativePathname($file);
+            $processed[$name] = true;
+
+            if ($file->isDir() || $file->isLink()) {
+                continue;
+            }
 
             $this->stopwatch->start($name);
 
```

**Comment by keradus** [comment]
Yes I saw that in StyleCI fork.

Even with that it's still iterating through every files twice.
The user call is bad, bad still we could do sth with it.

If we won't go with any other solution I would go that way indeed, but I have a strong feeling that it is fixing the symptom, not the reason :(

**Comment by GrahamCampbell** [comment]
> but I have a strong feeling that it is fixing the symptom, not the reason :(

Yeh, it absolutely is. I just needed a fast hack to fix the worst effect of it.

**Comment by keradus** [comment]
ref 1c9a7f4
