### ISSUE TITLE
declare() is seen as a control structure

### ISSUE THREAD

**Issue by Seldaek** [FriendsOfPHP/PHP-CS-Fixer#1709]
I think it makes sense in the case where you use it like:

```
declare () {
   ...
}
```

But for example:

```
declare(strict_types=1);
declare(ticks=100);
```

Will get reformated right now as:

```
declare (strict_types = 1);
declare (ticks = 100);
```

And I don't really think that's correct, at least not the space after declare. As it's clearly used like a function in this case.

**Comment by keradus** [comment]
We are adding a space? There should not be a space at all.

What version are you using?

ref #1495

**Comment by Seldaek** [comment]
I was just coming back to say.. it works with latest so never mind me :)

**Comment by keradus** [comment]
Great to hear!
