### ISSUE TITLE
phpdoc_to_comment bug?

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1715]
using 2.x

```php
/**
 * @var Foo
 */
$foo = createFoo();
```

should this really be treated as not phpdocblock ?

**Comment by GrahamCampbell** [comment]
In these sorts of cases, I think we should actually delete the entire thing rather than converting it to a normal comment.

**Comment by keradus** [comment]
Why you should consider it as invalid docblock then ?
It gives one great typehinting information.

**Comment by drAlberT** [comment]
I have a similar issue .. I think this can be a bug.

# test n°1

source:
![screen shot 2016-06-10 at 10 34 03](https://cloud.githubusercontent.com/assets/1442700/15958626/05a7d2ea-2ef7-11e6-8073-2415f7de28db.png)

corrected into:
![screen shot 2016-06-10 at 10 34 32](https://cloud.githubusercontent.com/assets/1442700/15958637/1ad41e76-2ef7-11e6-9fe1-c5fefa1f5382.png)

# test n°2

source:
![screen shot 2016-06-10 at 10 37 13](https://cloud.githubusercontent.com/assets/1442700/15958711/6c989c3c-2ef7-11e6-9b07-a53a4a44ee42.png)

corrected into:
![screen shot 2016-06-10 at 10 37 34](https://cloud.githubusercontent.com/assets/1442700/15958716/71cf6e4c-2ef7-11e6-86b4-beb3c53393fe.png)


Every time **only the first one** is treated as a DocBlock

**Comment by GrahamCampbell** [comment]
Not a bug.

**Comment by drAlberT** [comment]
OK, I trust your answer ... but can you explain why? ... thanks

**Comment by GrahamCampbell** [comment]
Because phpdoc must follow a structural block. That is not valid. You should use class constants if you want doc.

**Comment by keradus** [comment]
and the first one is not touched as it's recognized as file-level doc, right ?

**Comment by GrahamCampbell** [comment]
> and the first one is not touched as it's recognized as file-level doc, right ?

Ish. Our file level stuff is broken too anyway.

**Comment by keradus** [comment]
BTW, any answer for https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1715#issuecomment-177475696 ?

**Comment by drAlberT** [comment]
So, what about this [doc](https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_elements.pkg.html#procedural) about procedural elements ? .. I'm confused

**Comment by SpacePossum** [comment]
>So, what about this doc about procedural elements ? .. I'm confused

thats on `phpdoc` and prop. not on PSR5 (which is kind of followed here), I like `phpdoc` better in this case btw.

**Comment by GrahamCampbell** [comment]
phpdoc.org is not widely used. See PSR-5.

**Comment by drAlberT** [comment]
So, as per [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) the right way to document a define should be

```php
/** This is the FOO description. */
define('FOO', 'Foo value');
```

right?

**Comment by GrahamCampbell** [comment]
> So, as per PSR-5 the right way to document a define should be

No? It says you can't put doc on those.

**Comment by drAlberT** [comment]
I'm starting to feel stupid :(

![screen shot 2016-06-10 at 16 50 04](https://cloud.githubusercontent.com/assets/1442700/15968255/7246bab8-2f2b-11e6-9e6b-a5b6f4f2a3ab.png)

**Comment by keradus** [comment]
constant:

```php
class Foo
{
    const BAR = 1;
}
```

it's not the same like `define("foo", "bar")` in global level

**Comment by GrahamCampbell** [comment]
That's **not** a constant. This is a constant:

```php
<?php

class Foo
{
    /**
     * Valid PHPDoc.
     *
     * @var string
     */
    const STUFF = 'FOO';
}

**Comment by GrahamCampbell** [comment]
@keradus We posted at the same time. :)

**Comment by keradus** [comment]
;)


@GrahamCampbell 
BTW, any answer for https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1715#issuecomment-177475696 ?

**Comment by GrahamCampbell** [comment]
> It gives one great typehinting information.

Well, no, not really. The type can already be infered. It's a constant, so cannot change.

**Comment by keradus** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1715#issue-129483212

there is no constant here ...

**Comment by GrahamCampbell** [comment]
Meh, well, I didn't write that fixer. I don't disagree that's not useful.

**Comment by keradus** [comment]
On the very beginning you said to remove whole comment ...

**Comment by drAlberT** [comment]
ok got the point .. sorry and thanks for the patience.

What I think is buggy is the fact that the first define is not touched .. I already have a file-level docblock at the beginning of the file .. so what is the difference from the 1st define and the next one?

@GrahamCampbell eeh you are a `!!guy` ("I don't disagree that's not useful") .. just joking ;)

**Comment by SpacePossum** [comment]
>!!guy

we have fixer for that case; (bool) guy

back to topic, I think both the case from @keradus and all of those from the screenshots of @drAlberT are correct. Someone should tweak the fixers

**Comment by GrahamCampbell** [comment]
> On the very beginning you said to remove whole comment ...

Meh. Maybe you convinced me. ;P

**Comment by mcfedr** [comment]
It seems @drAlberT comments about `define` are confusing the matter, the reason the bug is was open, removing docblock from variables, is a bug.

**Comment by SpacePossum** [comment]
There are not removed, but changed to a comment. You can switch off the `phpdoc_to_comment` fixer and it should be fine.

**Comment by keradus** [comment]
The case is why 
```php
/**
 * @var Foo
 */
$foo = createFoo();
```
is considered as invalid phpdoc...

**Comment by mcfedr** [comment]
Why is that invalid?

It seems this test https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Tests/Fixer/Symfony/PhpdocToCommentFixerTest.php#L180 checks for this

This was converted to a comment to me
```
/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require_once __DIR__.'/../app/autoload.php';
```

**Comment by keradus** [comment]
using v1.12.1
```php
/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require_once __DIR__.'/../app/autoload.php';
```
is not modified by `PhpdocToCommetFixer`
but this would:
```php
/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require_once __DIR__.'/../app/autoload.php';
```

Then, it's the same case as my initial.

**Comment by mcfedr** [comment]
Yes, I double check, it was edited the first time I ran fixer by `phpdoc_var_without_name` and the second time by `phpdoc_to_comment`
