### ISSUE TITLE
trailing_spaces fixer returns internal error

### ISSUE THREAD

**Issue by christopherowen** [FriendsOfPHP/PHP-CS-Fixer#1716]
if I scan any php file with the currently released homebrew php-cs-fixer, it will return an "Internal Error".

If I set --fixers=-trailing_spaces then the files will be fixed successfully.

**Comment by keradus** [comment]
Please, provide the following information:
- version of tool (eg `php-cs-fixer --version`)
- example of file, on which the error occurs

**Comment by christopherowen** [comment]
PHP CS Fixer version 1.11 by Fabien Potencier

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ cat test.php 
<?php

echo "stuff.";
MacBook-Pro:projects home$ php-cs-fixer fix test.php 
Fixed all files in 0.021 seconds, 4.000 MB memory used

Files that were not fixed due to internal error:
   1) /Users/home/projects/test.php

**Comment by christopherowen** [comment]
finally:

MacBook-Pro:projects home$ php-cs-fixer fix test.php --fixers=-trailing_spaces
   1) /Users/home/projects/test.php
Fixed all files in 0.039 seconds, 4.000 MB memory used

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ php --version
PHP 7.0.2 (cli) (built: Jan  7 2016 10:40:26) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by keradus** [comment]
PHP5: https://travis-ci.org/keradus/PHP-CS-Fixer/builds/105489126#L173
PHP7: https://travis-ci.org/keradus/PHP-CS-Fixer/builds/105489720#L180

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ curl http://get.sensiolabs.org/php-cs-fixer-v1.11.phar -o php-cs-fixer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 77 1260k   77  974k    0     0  11930      0  0:01:48  0:01:23  0:00:25     0curl: (18) transfer closed with 292485 bytes remaining to read

MacBook-Pro:projects home$ chmod +x php-cs-fixer 
MacBook-Pro:projects home$ ./php-cs-fixer fix test.php 
PHP Fatal error:  Uncaught PharException: phar "/Users/home/projects/php-cs-fixer" has a broken signature in /Users/home/projects/php-cs-fixer:29
Stack trace:
#0 /Users/home/projects/php-cs-fixer(29): Phar::mapPhar('php-cs-fixer.ph...')
#1 {main}
  thrown in /Users/home/projects/php-cs-fixer on line 29

Fatal error: Uncaught PharException: phar "/Users/home/projects/php-cs-fixer" has a broken signature in /Users/home/projects/php-cs-fixer:29
Stack trace:
#0 /Users/home/projects/php-cs-fixer(29): Phar::mapPhar('php-cs-fixer.ph...')
#1 {main}
  thrown in /Users/home/projects/php-cs-fixer on line 29

**Comment by keradus** [comment]
```bash
D:\GIT\fork\PHP-CS-Fixer (issue-1716)
λ curl http://get.sensiolabs.org/php-cs-fixer-v1.11.phar -o php-cs-fixer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1260k  100 1260k    0     0   361k      0  0:00:03  0:00:03 --:--:--  361k

D:\GIT\fork\PHP-CS-Fixer (issue-1716)
λ php php-cs-fixer fix test -vvv
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) file.php (single_quote)
Fixing time per file:
[0.446 s] file.php

Fixed all files in 0.451 seconds, 4.000 MB memory used
```

**Comment by christopherowen** [comment]
is there a method by which I could tease out what the 'Internal Error' is from the homebrew installed version?

**Comment by keradus** [comment]
I don't use homebrew so don't know.
Could you just clone the repo using composer?

**Comment by christopherowen** [comment]
I would be happy to follow any instructions you have.

**Comment by keradus** [comment]
do you have composer on your machine?

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ composer --version
Composer version 1.0.0-alpha11 2015-11-14 16:21:07

**Comment by keradus** [comment]
Oh, even better - git ?

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ git --version
git version 2.5.4 (Apple Git-61)

**Comment by keradus** [comment]
```
git clone git@github.com:keradus/PHP-CS-Fixer.git
cd PHP-CS-Fixer
git checkout issue-1716_b
php php-cs-fixer fix path_to_file.php
```

**Comment by christopherowen** [comment]
MacBook-Pro:projects home$ git clone git@github.com:keradus/PHP-CS-Fixer.git
Cloning into 'PHP-CS-Fixer'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by keradus** [comment]
Try with this then:
`git clone https://github.com/keradus/PHP-CS-Fixer.git`

**Comment by christopherowen** [comment]
MacBook-Pro:PHP-CS-Fixer home$ php php-cs-fixer fix ~/projects/test.php 
Fixed all files in 0.021 seconds, 4.000 MB memory used

Files that were not fixed due to internal error:
   1) [1] /Users/home/projects/test.php: ErrorException: implode() expects exactly 2 parameters, 1 given in /Users/home/projects/PHP-CS-Fixer/Symfony/CS/Fixer/PSR2/TrailingSpacesFixer.php:53
Stack trace:
#0 [internal function]: {closure}(2, 'implode() expec...', '/Users/home/pr...', 53, Array)
#1 /Users/home/projects/PHP-CS-Fixer/Symfony/CS/Fixer/PSR2/TrailingSpacesFixer.php(53): implode(Array)
#2 /Users/home/projects/PHP-CS-Fixer/Symfony/CS/Fixer.php(209): Symfony\CS\Fixer\PSR2\TrailingSpacesFixer->fix(Object(SplFileInfo), '<?php\n\necho 'st...')
#3 /Users/home/projects/PHP-CS-Fixer/Symfony/CS/Fixer.php(151): Symfony\CS\Fixer->fixFile(Object(SplFileInfo), Array, false, false, Object(Symfony\CS\FileCacheManager))
#4 /Users/home/projects/PHP-CS-Fixer/Symfony/CS/Console/Command/FixCommand.php(377): Symfony\CS\Fixer->fix(Object(Symfony\CS\Config\Config), false, false)
#5 /Users/home/projects/PHP-CS-Fixer/Users/home/projects/PHP-CS-Fixer/vendor/symfony/console/Command/Command.php(256): Symfony\CS\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/home/projects/PHP-CS-Fixer/Users/home/projects/PHP-CS-Fixer/vendor/symfony/console/Application.php(787): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/home/projects/PHP-CS-Fixer/Users/home/projects/PHP-CS-Fixer/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\CS\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/home/projects/PHP-CS-Fixer/Users/home/projects/PHP-CS-Fixer/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/home/projects/PHP-CS-Fixer/php-cs-fixer(44): Symfony\Component\Console\Application->run()
#10 {main}

**Comment by keradus** [comment]
It's fun, as it may have only one parameter: http://php.net/manual/en/function.implode.php

**Comment by keradus** [comment]
Example from php-src:
https://github.com/php/php-src/blob/php-7.0.2/ext/standard/tests/strings/implode.phpt#L12

**Comment by christopherowen** [comment]
what do you recommend as my next course of action?

**Comment by keradus** [comment]
I think it is your env problem, it works on 7.0.2:
https://travis-ci.org/keradus/PHP-CS-Fixer/builds/105489720#L105

**Comment by christopherowen** [comment]
This is happening due to the php taint module.

Disabling taint stops this error.
