### ISSUE TITLE
Brace style

### ISSUE THREAD

**Issue by christopherowen** [FriendsOfPHP/PHP-CS-Fixer#1717]
Is it possible to change the default function brace style?

The default style places the open brace on a new line, but I prefer if the brace is on the same line as the function keyword.

**Comment by keradus** [comment]
No it is not. Braces fixer follows PSR-2.
If you want please feel free to send PR with that feature.

**Comment by christopherowen** [comment]
okay, thanks.

**Comment by jtojnar** [comment]
Proposed fix in #2459
