### ISSUE TITLE
Fixing a file excluded in the .php_cs config file should not occurs

### ISSUE THREAD

**Issue by tifabien** [FriendsOfPHP/PHP-CS-Fixer#1719]
I'm faced to a problem with [GrumPHP](https://github.com/phpro/grumphp) when I run php-cs-fixer task.

I created a .php_cs config file. In this config I excluded some autogenerated files. The problem is that when I run codestyle checks it fails on these autogenerated files. 
Behind the scene the command executed is the following : 
`vendor/binphp-cs-fixer --dry-run --config-file=.php_cs --verbose fix app/autoload.php` 

This `app/autoload.php` file is present in my config file
```<?php

return Symfony\CS\Config\Config::create()
    ->setUsingCache(true)
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    ->fixers(array('ordered_use'))
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in(__DIR__)
            ->notPath('app/autoload.php')
    )
;
```
Is there a reason why .php_cs config file is not took into account when we invoke php-cs-fixer command with a specific file in param?

**Comment by GrahamCampbell** [comment]
Not path cannot include a filename, it strictly means a path.

**Comment by GrahamCampbell** [comment]
Maybe you want `notName('autoload.php');`?

**Comment by tifabien** [comment]
Same result if I change notPath to notName.

It seems not path can accept filenames. it is the case in [Symfony/symfony](https://github.com/symfony/symfony/blob/master/.php_cs) repo

**Comment by keradus** [comment]
This is other problem.

When you say that you want to fix `app/autoload.php` file by CLI argument, then yout finder from .php_cs file is overridden with path provided in console.

Do we want to somehow combine it? That could be a bit messy...

**Comment by tifabien** [comment]
Indeed this could be a bit tricky to understand...
But this also is a bit heavy to check the whole project in the case of a pre-commit hook check.

How could we check files individually by applying .php_cs rules ?

**Comment by keradus** [comment]
Yeah, I faced that too. I think that to achieve it we need to change the way of dealing with finder.

**Comment by tifabien** [comment]
I agree :+1: 
Maybe we could introduce an new CLI option `--force` in order to overwrite finder if a file is provided.

**Comment by keradus** [comment]
:-1: for 3 places to set same thing...
It would be just a hack...

Again, we already overriding the finder, that is the point...

**Comment by tifabien** [comment]
Understood.
I'll try to find a hack for my use case !

Thanks for your help and for your great work !

**Comment by keradus** [comment]
I would like to allow for such user case directly inside the tool ;)
I have few thoughts about that, but need to try them.

**Comment by tifabien** [comment]
I'm eager to see :)

**Comment by vyshkant** [comment]
> I'll try to find a hack for my use case !

@tifabien Did you finally find the solution?

**Comment by tifabien** [comment]
@vyshkant Take a look at the path-mode option in CLI. If you pass the intersection value it will handle config + file passed.
See : https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage
