### ISSUE TITLE
NoShortBoolCast rename was incorrect

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1720]
It doesn't tell you what it actually does.

**Comment by keradus** [comment]
Go ahead and send PR ;)

**Comment by GrahamCampbell** [comment]
Well, I d'no what would be a good name. That's why I'm opening this for discussion first. ;)

**Comment by keradus** [comment]
so constructive ;)

**Comment by GrahamCampbell** [comment]
yeh, well :P

**Comment by SpacePossum** [comment]
```
There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton
```

^-^

**Comment by SpacePossum** [comment]
Maybe `ExplicitBoolCastFixer` or `LongBoolCastFixer` ?

**Comment by gharlan** [comment]
`DoubleNotOperatorToBoolCastFixer`
`NoDoubleNotOperatorFixer`
`NoNotNotFixer`
`VeryUglyBoolCastHackToOrdinaryBoolCastFixer`
...

**Comment by GrahamCampbell** [comment]
> VeryUglyBoolCastHackToOrdinaryBoolCastFixer

Seems legit.

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Closing due to lack of community interest for too long.
