### ISSUE TITLE
not_operators_with_space_fixer vs not_operator_with_successor_space

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1721]
Inconsistent naming here. One of them uses the plural, operators, while the other does not.

**Comment by keradus** [comment]
Please send a PR.

**Comment by GrahamCampbell** [comment]
Which one do you prefer as the "correct" one?

**Comment by keradus** [comment]
For me both ways are fine

**Comment by GrahamCampbell** [comment]
Remind me to do this tomorrow. ;)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Sent a PR.
