### ISSUE TITLE
Was the phpdoc_no_simplified_null_return rename an error

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1723]
It looks like you tried to rename the `return` fixer, and accidently caught the end of this fixer too?

**Comment by keradus** [comment]
good catch!

**Comment by keradus** [comment]
Should go back to `phpdoc_no_empty_return`

**Comment by GrahamCampbell** [comment]
I think so, yes.

**Comment by keradus** [comment]
Closing thanks to #1728
