### ISSUE TITLE
whitespacy_lines forgotten about during renaming

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1724]

**Comment by keradus** [comment]
Please extend your statement.

Shortcuts thought are often understood only by the authors.

I so no plan about renaming `whitespacy_lines` in #889 .

If what you want is to propose a rename of that rule - please feel free to do so ;)

**Comment by GrahamCampbell** [comment]
How about `no_blank_line_whitespace`.

**Comment by keradus** [comment]
`no_whitespace_in_blank_line` ?

**Comment by GrahamCampbell** [comment]
Sure.

**Comment by keradus** [comment]
Could you send a PR?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by keradus** [comment]
Cool, thanks ;)

**Comment by keradus** [comment]
As PR wasn't linked - closing thanks to #1729
