### ISSUE TITLE
Fixer to enforce declare(strict_types=1); in all files

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1726]

**Comment by keradus** [comment]
Risky :D

**Comment by GrahamCampbell** [comment]
Indeed.

**Comment by GrahamCampbell** [comment]
I have a codebase that already has this though, so, for that use case, this fixer would be useful to make sure i don't forget it on new files, for example, rather than for a codebase conversion.

**Comment by keradus** [comment]
I'm already for it ;)

**Comment by GrahamCampbell** [comment]
> have a codebase that already has this though

That doesn't mean I've written the fixer btw, it means I have a codebase that has every file with strict type hints in. :trollface:

**Comment by keradus** [comment]
Finally every php7 project should have it

**Comment by gharlan** [comment]
:+1:

**Comment by Seldaek** [comment]
Please see #1921
