### ISSUE TITLE
Question: phpdoc and trailing spaces

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1727]
Could trimming trailing spaces inside PHPDoc could change meaning of code?
In other words, if we had such fixer would it be risky ?

cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Trimming trailing "space" or "tab" characters from lines should not change the behaviour of phpdoc and should be safe.

**Comment by keradus** [comment]
For now we have (following 1.x names):

> **trailing_spaces [PSR-2]**
> Remove trailing whitespace at the end of non-blank lines.

> **whitespacy_lines [symfony]**
> Remove trailing whitespace at the end of blank lines.

I would add:
`phpdoc_no_trailing_spaces` for PHPDocs purpose

and maybe, at some time:
`force_no_trailing_spaces` that will remove trailing whitespace from all places, but that may be risky.
```php
<?php

$content = 'foo    
bar';
$content === "foo    \nbar"; // true
```

**Comment by GrahamCampbell** [comment]
> force_no_trailing_spaces that will remove trailing whitespace from all places, but that may be risky.

I like that fixer. Useful even if it's used as a guide to find those places in a code base where we can tweak it so as not to need the trailing whitespace if it were to change the behaviour.

**Comment by gharlan** [comment]
> force_no_trailing_spaces that will remove trailing whitespace from all places, but that may be risky.

yes, would be risky. But I would like that fixer, too. :+1:
