### ISSUE TITLE
Move no_trailing_whitespace_in_comment to @PSR-2

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1738]
I would move this fixer to PSR-2 leve, due to PSR rule:
> Remove trailing whitespace at the end of non-blank lines.

Comments are not-blank lines, so the fixer follows PSR2

**Comment by GrahamCampbell** [comment]
Seems legit. :+1:

**Comment by TomasVotruba** [comment]
:+1:
