### ISSUE TITLE
Incorrect file headers

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1740]
We have `This file is part of the PHP CS Fixer.` atm, but it should just be `This file is part of PHP CS Fixer.`

**Comment by keradus** [comment]
it was that way. there is the one tool

**Comment by GrahamCampbell** [comment]
It's incorrect grammar because it's a proper noun.

**Comment by keradus** [comment]
Good point, thank you.
