### ISSUE TITLE
[FR] Add minimal Fixer version to configuration

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1749]
It would be useful, especially with 2.x coming up, to add the option to allow the minimal Fixer version to the configuration. That way we can warn the user in a nice way that the Fixer be used is not compatible with the configuration used, atm we show something like `X fixer does not exists/found`  .

**Comment by keradus** [comment]
it is?
after namespace change it should crash on non-existing class

**Comment by SpacePossum** [comment]
Indeed and that is even more sad for 1 to 2 updaters... let me think about it.
My case is like; if a new fixer is added to, lets say, 1.12 and I add it to the configuration of my projects.
If some one would run a fixer at 1.11 it would get a `unknown fixer` kind of exception. So even it won't stop 2.x from crashing when using it with a 1.x config, it would be nice for x.x to x.x+1 updates in the future don't you think?

**Comment by keradus** [comment]
If one use 2.x with 1.x config then it would crash before dealing with fixers.

I didn't get part `x.x to x.x+1`

**Comment by SpacePossum** [comment]
I'll think and try some things out for 1.x to 2.x configuration issues and feedback.

For `1.x to 1.x+1`;
As example, lets take a look at the upcoming 1.12 :)
- on 1.12 a new fixer is added
- we update the configuration file of a project to use the fixer
- someone runs 1.11 with the configuration
- doesn't work, the feedback to the user is that the fixer is not known

What I would like to improve is the feedback to user; from `unknown fixer` to; `this configuration only works with 1.12 and up, please run "self-update"`.

**Comment by GrahamCampbell** [comment]
Maybe use composer's semver package and have the config specify a version constraint for max flexibility?

**Comment by SpacePossum** [comment]
the check can be done inside the configuration file itself, so no need for this.
