### ISSUE TITLE
feature request for HeaderCommentFixer

### ISSUE THREAD

**Issue by jakoch** [FriendsOfPHP/PHP-CS-Fixer#1754]
Hi there, i have a suggestion:

the HeaderCommentFixer should also take `/**` on the first line of the header comment into account:

    /**
     * ...
     */
   
Currently a new header comment using `/*` on the first line is added on top of the old one (using dev).

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by SpacePossum** [comment]
Could you point out the PR this report duplicates? (1297 or 1473?)

**Comment by jakoch** [comment]
Reference?

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1297
