### ISSUE TITLE
PHPDocSeparationFixer - Proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1760]
Basically, I want a fixer to ensure there is exactly one blank phpdoc line above the first annotation if there are other non-blank lines above it. In otherwise, we're ensuring that any summary forms always have a blank line after them, then the tags follow.

Example pre/post-conditions:

``` php
/**
 * FOO
 * @bar 123
 */
```

``` php
/**
 * FOO
 *
 * @bar 123
 */
```

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by SpacePossum** [comment]
ping @GrahamCampbell , a year already passed, time flies! Like to see this one added :)

**Comment by SpacePossum** [comment]
I think this is done, please leave a commit if not!
