### ISSUE TITLE
PHPDoc appending dot

### ISSUE THREAD

**Issue by umpirsky** [FriendsOfPHP/PHP-CS-Fixer#1771]
I noticed some edge case with appending dots in phpdoc:

```diff
/**
-     * This method will do:
+     * This method will do:.
```

**Comment by keradus** [comment]
You have invalid phpdoc summary section. You have only description. Fix your documentation to have summary section first, then keep your list of action in description section.

**Comment by umpirsky** [comment]
@keradus Yes, you are right. Thanks.

**Comment by SpacePossum** [comment]
Well technically, PSR 5 (ATM) states:
```
 It is RECOMMENDED for Summaries to span a single line or at most two but not more than that.
[...] or two sequential line breaks
```

So having:
```php
/***
 *  This method will do:
 *  1 - something
 *
 * Summary: more details
 */
public function myMethod(){}
```

is correct and we don't fix it correct ^-^

**Comment by keradus** [comment]
```
D:\GIT\fork\PHP-CS-Fixer (1.12)
λ cat b\x.php
<?php
/**
 *  This method will do:
 *  1 - something
 *  2 - sth more
 *
 * Summary: more details
 */
function myMethod()
{
}

D:\GIT\fork\PHP-CS-Fixer (1.12)
λ php php-cs-fixer fix b --diff -vv
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) x.php (phpdoc_short_description)
      ---------- begin diff ----------
      --- Original
+++ New
@@ @@
 <?php
 /**
  *  This method will do:
  *  1 - something
- *  2 - sth more
+ *  2 - sth more.
  *
  * Summary: more details
  */
 function myMethod()
 {
 }


      ---------- end diff ----------
```

**Comment by SpacePossum** [comment]
that proves the point of the `or` doesn it,

**Comment by SpacePossum** [comment]
but than again, I'll PR sth for this in the near future ;)

**Comment by keradus** [comment]
I'm still not seeing an issue. Fixer put dot at end of summary, regardless of it's number of lines.

**Comment by keradus** [comment]
@SpacePossum, please remember that this is Symfony level fixer that is to put missing dot. It's not PSR level fixer that put dot/add empty line, depending on some magic.

**Comment by SpacePossum** [comment]
Indeed I forgot it is a Symfony fixer and not PSR, thanks for the reminder :)
So it is a valid PHPDoc oc. to PSR5, just not oc. to Symfony standard. I agree, the fixer works as defined, no issue here :)

>I'm still not seeing an issue. Fixer put dot at end of summary, regardless of it's number of lines.

I still like to have a PSR5 fixer as alternative, one that leaves the multi lines a alone, so I'll work on it. It is not depending on some magic btw,  the rule it pretty clear. If it is multi line, than no dot is required (for example for listing, which is following just plain English grammar rules). Adding the empty line is also PSR5, so maybe I put some effort into a new fixer for that as well ;)

**Comment by keradus** [comment]
that was my magic - if ones phpdoc misses both - full stop and double empty line, we need to choose in which way it would be fixed.

Maybe use existing fixer and allow to configure it ?

**Comment by GrahamCampbell** [comment]
I don't think this needs to changed. I surveyed over 100 open source repos when I originally wrote these fixers to check their behaviour.
