### ISSUE TITLE
Term 'php' not recognized

### ISSUE THREAD

**Issue by txmodxoops** [FriendsOfPHP/PHP-CS-Fixer#1774]
Hi

The path is correct E:\wamp\www\xoops-2.5.8> php .\php-cs-fixer.phar fix .\htdocs\modules, after two days of formatting the PC, no longer works. I thought I was not installed composer, instead makes the same mistake.

I use for this Windows PowerShell ISE

**Comment by GrahamCampbell** [comment]
Not a bug.

**Comment by txmodxoops** [comment]
In what forum I ask?

**Comment by txmodxoops** [comment]
I'm Sorry!
I think my computer is acting up after several attempts, it works now
