### ISSUE TITLE
Maybe seperate the fixers by namespace on the readme

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1778]
Now that they're split up into categories, it might be nice to use them. Maybe add getCategory to the interface like getName, and start utilizing it on the readme, etc?

**Comment by SpacePossum** [comment]
:+1: , just why not use annotations in the Fixer-descriptions and not add more methods to the interface?

**Comment by keradus** [comment]
if `getCategory` would be only for readme file purpose then :-1: for that method

**Comment by gharlan** [comment]
for readme we could just use the namespace part.

**Comment by keradus** [comment]
Also, it would be nice to mention about configuration part of fixer...

**Comment by GrahamCampbell** [comment]
> for readme we could just use the namespace part.

:-1: for the same reason we have a getName method even though we technically don't need it because it's interred by the class name.

**Comment by keradus** [comment]
`getName` is needed for `FixerFactory` to choose fixers based on ruleset.
It's needed especially for custom fixers.

It's not the same as category.

**Comment by keradus** [comment]
Closing as this ticket is really old and we have no conclusion.
I still would appreciate to have a cleanup of our README file.
