### ISSUE TITLE
PSR5

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1785]
Is anyone willing to create PSR5 ruleset?

**Comment by GrahamCampbell** [comment]
PSR-5 is not a code style standard.

**Comment by GrahamCampbell** [comment]
All it does is define what the annotations mean. None of our fixers are "PSR5" fixers.

**Comment by keradus** [comment]
It define how documentation should looks like. Things like summary with trailing dot and so on.

**Comment by GrahamCampbell** [comment]
> It defines how documentation should looks like. Things like summary with trailing dot and so on.

Does it? The spec explicitly says:

![image](https://cloud.githubusercontent.com/assets/2829600/13107874/d1a908da-d567-11e5-901e-3984580ec2b3.png)

**Comment by SpacePossum** [comment]
>It defines how documentation should looks like. Things like summary with trailing dot and so on.

.

>Does it? 

Yes;

>A Summary MUST end with either
> - a full stop (.) followed by a line break

so yes, we could create some PSR5 fixers :)

**Comment by GrahamCampbell** [comment]
Hmmm.

**Comment by GrahamCampbell** [comment]
The spec seems a bit contradictory then.

**Comment by GrahamCampbell** [comment]
If we follow the spec, then we shouldn't add full stops there, because by definition of the spec, it's not a short description unless it was a fullstop, if we the spec is giving definitions, not cs advice.

**Comment by keradus** [comment]
so let us call the ruleset "some_random_PHPDoc_rules_that_will_make_your_docblocks_looks_more_like_PSR5_proposal_suggests_they_should"

**Comment by gharlan** [comment]
@keradus which fixers would you add to the rule set?

**Comment by keradus** [comment]
sth like
- no_trailing_whitespace_in_comment
- no_empty_lines_after_phpdocs
- no_empty_phpdoc
- phpdoc_inline_tag
- phpdoc_scalar
- phpdoc_short_description
- phpdoc_trim
- phpdoc_type_to_var
- phpdoc_types
- phpdoc_var_without_name
- phpdoc_order

**Comment by gharlan** [comment]
then I agree to @GrahamCampbell that it should not be named PSR5.

**Comment by SpacePossum** [comment]
why not call it is PSR5, these fixers do not violate the PSR5 rules do they?

**Comment by gharlan** [comment]
> these fixers do not violate the PSR5 rules do they?

Why not PSR2? "They do not violate PSR2 rules." ;)
They don't fix rules defined in PSR5, so they should not exist in a rule set with name "PSR5".

**Comment by SpacePossum** [comment]
>They don't fix rules defined in PSR5, so they should not exist in a rule set with name "PSR5".

some do, don't they? For example: `phpdoc_inline_tag`

Expected
`* {@inheritdoc test} b`
Input
`* {{@inheritdoc    test}} b`

Matches PSR5; 
**5.PHPDoc format**
`inline-tag         = "{" tag "}"`

**Comment by gharlan** [comment]
> some do, don't they?

That's the reason why I've asked @keradus which fixers he would add to that rule set.
When there are only fixers matching PSR5 rules, I'm ok with the name.

**Comment by Fleshgrinder** [comment]
PSR-5 is still work in progress and you should not start implementing anything as of yet. Please wait for its final release.

**Comment by keradus** [comment]
We are not implementing PSR-5. We already implemented a lot of phpdoc fixers for frameworks (eg Symfony). As the rules are nice, some of them matches PSR-5 proposal.

**Comment by GrahamCampbell** [comment]
> Please wait for its final release.

That makes no sense. There is NO docblock standard that's widely used out there, so we've chosen PSR-5.

**Comment by Fleshgrinder** [comment]
It is fine if you create generic fixers based on whatever but you should back up from creating fixers with the name of PSR-5 or any of its experimental stuff.

PSR-5 is based on phpDocumentor, you may want to have a look at its official documentation on the usage of most of its tags.

**Comment by GrahamCampbell** [comment]
> you may want to have a look at its official documentation on the usage of most of its tags.

I think phpdocumetor's original spec isn't very good, and nobody does half the stuff it says.

**Comment by Fleshgrinder** [comment]
I cannot judge that because I never used it. However, I am involved in PSR-5 and it is a highly controversial PSR because it is driven by the people from phpDocumentor. I can only beg you to keep away from it until it is finished; note well that [it is currently totally on ice](https://groups.google.com/forum/#!topic/php-fig/X2N17_qGKiI).

**Comment by keradus** [comment]
Closing due to discussion.
