### ISSUE TITLE
No longer works in netbeans

### ISSUE THREAD

**Issue by twifty** [FriendsOfPHP/PHP-CS-Fixer#1789]
The Netbeans IDE is dependent on the output being well formed XML. But, the current implementation detects if the xdebug extension is loaded and prints a warning, before outputting the XML.

I think the best way to handle this is to add a new option '--using-xdebug' to suppress the warning.

**Comment by SpacePossum** [comment]
The warning is intended to be send to stdErr and therefor should be ignored by Netbeans IDE (and all other clients). Could you confirm the warning is send to stdErr?
Are you sure this is the issue and not other output that is written to stdOut while it shouldn't?

**Comment by keradus** [comment]
Plugins should rely on stdOut, not stdErr.
No option to hide the warning is needed.

**Comment by GrahamCampbell** [comment]
This is a netbeans bug and should be closed.

**Comment by twifty** [comment]
The problem appeared to be on my end. I don't know how or why, but that warning was always output in the terminal.
