### ISSUE TITLE
Newline being added between opening tags and declare(strict_types=1)

### ISSUE THREAD

**Issue by nesl247** [FriendsOfPHP/PHP-CS-Fixer#1793]
Using version 1.12 (latest commit as of opening this issue), php-cs-fixer is adding a newline between the opening PHP tag and the declare statement. Unless something changed in PSR-12 that I don't recall, this shouldn't be happening. I know PSR-12 hasn't been adopted yet, but I believe most people are keeping with this style at the moment.

Expected:

```
<?php
declare(strict_types=1);
```

Actual:

```
<?php

declare(strict_types=1);`
```

**Comment by SpacePossum** [comment]
The fixer doesn't do anything for/with PSR-12 atm AFAIK.
Do you have the `blankline_after_open_tag`-fixer enabled? (it is by default on Symfony level)

**Comment by nesl247** [comment]
Yes I do because I want that if declare isn't there for whatever reason.

**Comment by GrahamCampbell** [comment]
The actual result is correct.

**Comment by GrahamCampbell** [comment]
Example fille that's been through php-cs-fixer: https://github.com/GrahamCampbell/Matrices/blob/v0.2.0-alpha/src/Operations/MatrixOfMinorsOperation.php.

**Comment by nesl247** [comment]
Well it isn't correct according to PSR-12 (https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) which I guess is not being supported by php-cs-fixer at the moment.

**Comment by GrahamCampbell** [comment]
> Well it isn't correct according to PSR-12

That standard is not accepted yet, and I recon it'll get changed to leave a newline once more people have actually looked at the standard.

**Comment by GrahamCampbell** [comment]
Can this be closed? I seem to remember something happening about this?

**Comment by SpacePossum** [comment]
Not fixed, discussion is here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2062.
What is fixed that the strict type fixer will no longer move the declaration, but this is just step one of many.

**Comment by GrahamCampbell** [comment]
Ah, right. :)

**Comment by keradus** [comment]
Closing due to discussion moved somewhere else.
