### ISSUE TITLE
Annotation broken after running the fixer

### ISSUE THREAD

**Issue by dmaicher** [FriendsOfPHP/PHP-CS-Fixer#1794]
We have some @Security annotations on our Controllers in Symfony.

This is the changeset from the fixer run with `php-cs-fixer fix -v --level=symfony src/`:

```php
 /**
  * @Security(expression="
-    is_granted('ROLE_COMPETITION_MENU') and
-    is_granted('RCP_REVIEWS_EXT')
-  ")
  */
 class CompetitionController extends Controller
 {
```

So after it we end up with the quite invalid syntax of:

```php
/**
 * @Security(expression="
 */
class CompetitionController extends Controller
{
```

Version:

```
PHP CS Fixer version 1.11.1 by Fabien Potencier (2c9f829)

**Comment by SpacePossum** [comment]
Thank you for the report. Confirmed on 1.12 (dev) as well.
The fixer that does this `phpdoc_trim`, so while we look into it you could disable that one in the mean time.

**Comment by dmaicher** [comment]
Thx for the info ;) Disabled that fixer temporarily until the problem is solved :+1:

**Comment by keradus** [comment]
BTW, why there are no start at every line of PHPDoc?

**Comment by dmaicher** [comment]
@keradus  That's indeed a valid question. I guess my phpdoc is actually not quite valid in the first place?

The problem is if I start every line with an asterix then the annotation parser is confused:

```php
/**
 * @Security(expression="
 *   is_granted('ROLE_COMPETITION_MENU') and
 *   is_granted('RCP_REVIEWS_EXT')
 * ")
 */
class CompetitionController extends Controller
```

==>
```
Unexpected token "operator" of value "*" around position 3. 
```

I would like to split it across multiple lines though. We have some controllers with even more logical ands for the expression.

**Comment by keradus** [comment]
@GrahamCampbell your participation would be appreciated

**Comment by GrahamCampbell** [comment]
It's because the phpdoc here is invalid. It's missing `*` at each line.

**Comment by GrahamCampbell** [comment]
@keradus, @dmaicher leave it with me and I'll sort this out.

**Comment by keradus** [comment]
Thank you @GrahamCampbell !

**Comment by keradus** [comment]
(btw, even without * tokenizer treat the token as doc_comment)

**Comment by GrahamCampbell** [comment]
> (btw, even without * tokenizer treat the token as doc_comment)

Yeh, it keeps accepting chars until we reach a closing phpdoc.

**Comment by GrahamCampbell** [comment]
Our annotation fixers made a bad assumption that that leading `*` is always there on each line.

**Comment by GrahamCampbell** [comment]
Maybe we just need to add a fixer to fix that, then allow the others to keep that assumption?

**Comment by keradus** [comment]
no, because, as in this case, it would change the meaning of annotation

**Comment by GrahamCampbell** [comment]
How would it? As I understand it, the one without the `*` is invalid phpdoc by PSR-5?

**Comment by keradus** [comment]
ok.

ref: `In case a DocComment spans multiple lines then every line MUST start with an asterisk (*) that SHOULD be aligned with the first asterisk of the opening clause.`

**Comment by dmaicher** [comment]
So will this be fixed or do I have to update my comments? :)

**Comment by keradus** [comment]
As it's invalid DocComment it's hard for fixer to modify it. Please update your comment or turn of that fixer.
