### ISSUE TITLE
[FR] Multi line conditional fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1795]
Fixer should add line breaks if missing

expected

``` php
<?php

if (
    $a &&
    $b &&
$c 
) {

}
```

input

``` php
<?php

if ($a &&
    $b &&
$c ) {

}
```

Fixer should place the operators at the end of the line (not sure if this should be done by the same fixer)

expected

``` php
<?php

if (
    $a && 
    $b &&
    $c
) {

}

```

input

``` php
<?php

if (
    $a
    && $b
    && $c
) {

}
```

I think both rules are not part of any PSR

**Comment by keradus** [comment]
> not sure if this should be done by the same fixer

I can see 2 fixers here. And even better - one with configuration (left | right)

**Comment by SpacePossum** [comment]
sounds like a plan :)

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
