### ISSUE TITLE
[RFC] Multi line array is made single line

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1796]
expected
```php
<?php
$a = array(
    1, 
    2, 
    3, 
    4, 
    $a, 
    $c, 
    7
);
```

actual
```php
<?php
$a = array(
    1, 2, 3, 4, $a, $c, 7,
);
```

input
```php
<?php
$a = array(
    1
, 2
, 3
, 4
, $a
, $c
, 7
);
```

On 1.12, fixers applied: `array_element_no_space_before_comma`, `multiline_array_trailing_comma`

**Comment by keradus** [comment]
@SpacePossum it is a feature request or bug report ?

**Comment by SpacePossum** [comment]
Well if you have the input and use `array_element_no_space_before_comma` it will remove the line breaks. While the line breaks are some form of `space` I would like to change it to act as described as above. Let me know what branch to target when I start on this one.

**Comment by keradus** [comment]
I cannot suggest the branch as I cannot understand the RFC completely.

`array_element_no_space_before_comma` remove spaces before comma, so it did it's job quite nice.

**Comment by SpacePossum** [comment]
Another example :)

input 
```php
<?php
$a = array(
     1  // my test comment, my test comment, my test comment
    ,2  // my test comment, my test comment, my test comment
    ,3  // my test comment, my test comment, my test comment
    ,4
    ,$a /* comment */
    ,$c
    ,7  // my test comment, my test comment, my test comment
);
```

```php
<?php
$a = array(
     1  // my test comment, my test comment, my test comment
, 2  // my test comment, my test comment, my test comment
, 3  // my test comment, my test comment, my test comment
, 4, $a /* comment */, $c, 7,  // my test comment, my test comment, my test comment
);
```

I don't like the new location of `$c` and  `7`. Its not that the fixer is wrong, but maybe we need a new fixer to add line breaks after this fixer?

**Comment by keradus** [comment]
Woudn't it add lines here as well?
```php
$a = [1, 2, 3];
```
?

**Comment by SpacePossum** [comment]
Lets see what the rule should be.
If an array is multi line:
* each array element should be on its own line  (fixer should ran after the current), or;
* comma that is separating elements should be on the same line as the first element if separates (fixer should ran before the current)

what do you think?

**Comment by keradus** [comment]
> each array element should be on its own line (fixer should ran after the current)

```php
$a = [
    1, 2, 3, 4, 5, 6, .....
    11, 22, 33, 44, ....
];
```


> comma that (...)

So, a this issue is feature request ;)

**Comment by SpacePossum** [comment]
indeed.. very good case...  I think this one will end up low on my todo list ;)

**Comment by SpacePossum** [comment]
Thinking about it; this can be done in a way more generic way, fixing all kinds of ',' related things.
I prep. a `spaces after comma` and a `spaces before comma` and we'll see if I'm think OK ;)

**Comment by keradus** [comment]
For now we have 14 open PRs from you.
Please, may both of us focus to finish them first.

**Comment by SpacePossum** [comment]
:+1:

**Comment by SpacePossum** [comment]
closing because of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1860
