### ISSUE TITLE
no_trailing_whitespace_in_comment -> no_trailing_whitespace_in_comments

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1797]
no_trailing_whitespace_in_comment -> no_trailing_whitespace_in_comment**s**

**Comment by keradus** [comment]
most of our names are using single form

**Comment by GrahamCampbell** [comment]
Not really, depends on what they are saying.

**Comment by gharlan** [comment]
All `_in_` fixers:

```
// singular
no_trailing_comma_in_list_call
no_trailing_comma_in_singleline_array
no_trailing_whitespace_in_comment
no_whitespace_before_comma_in_array
trailing_comma_in_multiline_array
whitespace_after_comma_in_array

// plural
no_whitespace_in_blank_lines

**Comment by SpacePossum** [comment]
I'm for `no_whitespace_in_blank_lines -> no_whitespace_in_blank_line` and -1 on renaming `no_trailing_whitespace_in_comment`.
Best to be tagged for 2.0 if we want to rename anything here.

**Comment by keradus** [comment]
@SpacePossum could you send a PR?

**Comment by keradus** [comment]
Closing thanks to #2013
