### ISSUE TITLE
Caching broken in the latest e8a84e3380ada463d9b0042e264200f9696e3cc7

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1799]
Every file is missing the cache for me. Ubuntu 15.10, PHP 7.0.3. PHP-CS-Fixer e8a84e3380ada463d9b0042e264200f9696e3cc7.

**Comment by keradus** [comment]
Does the problem occur when cache file is generated on e8a84e3380ada463d9b0042e264200f9696e3cc7 version ?

**Comment by GrahamCampbell** [comment]
It doesn't work after multiple runs, and I assume the first run on e8a84e3 will generate a cache for itself for the next run, right, so, no, it's still broken?

**Comment by gharlan** [comment]
Can not confirm here. On second run all files are skipped.

**Comment by GrahamCampbell** [comment]
I've tracked down the bug. It wasn't caused by this repo. Sorry for the noise.
