### ISSUE TITLE
Feature request to add a fixer for ordering use statements by length

### ISSUE THREAD

**Issue by kabirbaidhya** [FriendsOfPHP/PHP-CS-Fixer#1801]
I think it would be a nice to have a new fixer `ordered_use_by_length` in the package that organizes the `use` statements in the code by it's length to make the code look cleaner. 

Suppose we have this block of code: 

``` php
use Agent\Entity\Organization;
use Agent\Entity\Person;
use Auth\Entity\User;
use Crm\Creator\LeadCreator;
use Crm\Entity\CommercialRealEstateSpaceRequirement;
use Crm\Entity\Lead;
use Crm\Entity\LeadRole;
use Crm\Query\AvailableLeadStatusQuery;
use Crm\Query\CummingsUsersQuery;
use Crm\Query\Lead\ArchivedDetailsQuery;
```

And when applied it would change it to:

``` php
use Crm\Entity\Lead;
use Auth\Entity\User;
use Agent\Entity\Person;
use Crm\Entity\LeadRole;
use Crm\Creator\LeadCreator;
use Agent\Entity\Organization;
use Crm\Query\CummingsUsersQuery;
use Crm\Query\AvailableLeadStatusQuery;
use Crm\Query\Lead\ArchivedDetailsQuery;
use Crm\Entity\CommercialRealEstateSpaceRequirement;
```

I'm aware that there is already a fixer named `ordered_use` in `php-cs-fixer` but that orders the statements alphabetically. So, it's different as this is to **organize it by length**. 

I would suggest this new fixer to be named as `ordered_use_by_length` or `organize_use_by_length`. 

I know, not everybody would agree with this as many people rather stick with just ordering it alphabetically. But IMHO I think it would be nice to have this new feature as in big classes, it reduces code readability and cleanliness if we only organize it alphabetically. In our codebase we are doing it manually. 

Anyway, if you guys agree I can submit a  PR.

**Comment by SpacePossum** [comment]
Hi,
I wouldn't use the ordering you propose, however there have been request to change the order-logic of this fixer before. So if this was to be done, maybe we could open up the fixer a bit. Allowing people to write there own sorter by allowing to extend the class or allow to configure a `sorter`-object (just typing some ideas)? I'm not in fav. of having a new fixer for this case.

**Comment by keradus** [comment]
I disagree with reasoning. Ordering alphabetically increase readability as it groups by vendors, then packages, then modules and so on.

Question here: does anyone else need to sort `use` statements by length?

**Comment by GrahamCampbell** [comment]
> Question here: does anyone else need to sort use statements by length?

Yes, Laravel.

**Comment by GrahamCampbell** [comment]
I was going to write this fixer myself, but it ended up being harder than I thought, lol.

**Comment by gharlan** [comment]
> to make the code look cleaner.

for me it is ugly as hell. ;)
ordering by vendor and packages is much cleaner for me.

But if laravel uses this, I think the fixer `ordered_use` should be configurable.

**Comment by kabirbaidhya** [comment]
Yes, I know a lot of people who'd prefer this, especially those using laravel. But I also agree there are lots of people who rather prefer doing it alphabetically. So, I don't want to argue on that as it's all about personal preference and I don't think it should be enforced. 

Anyway, I think it's better to have a rather configurable option to choose what kind of ordering you want to do in your code, the default could be alphabetically as it's more mainstream.

**Comment by keradus** [comment]
Could you propose a PR with that option for our ordering fixer?

**Comment by GrahamCampbell** [comment]
NB Laravel;s ordering is quite specific. Order first by length, then alphabetically for those of the same length. That makes things a bit harder...

**Comment by kabirbaidhya** [comment]
@keradus Yes, I can do the pull request to add option to allow ordering it also by length in addition to what we have in the existing `ordered_use` fixer.

**Comment by DarkaOnLine** [comment]
+1

**Comment by noamcore** [comment]
So, this will be added or not?

**Comment by SpacePossum** [comment]
@noamcore if someone writes a PR that will modify the existing fixer to do this when configured, sure it will :)
you might want to check with @pbkyriak, author of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1803

**Comment by powelski** [comment]
+1 for this feature! It's Laravel's convention to keep `use` by length and same length entries are ordered alphabetically.

**Comment by keradus** [comment]
you are more than welcome to bring PR for it !

**Comment by DarkaOnLine** [comment]
@keradus , I would like to make a PR for this fixer, but before I begin I have few questions:

- Why #1803 was rejected ? For me, it looks like good idea to use abstract class and then extend it in two different fixers.
- You suggested that "this fixer should not be new fixer but the option for existing one", but how it could be done ? Can you show me an example how can I pass an option to the fixer ?

**Comment by keradus** [comment]
> Why #1803 was rejected ?

sadly, because of
> Closing due to wrong approach and lack of authors interest

--------

config:
1.x example: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/ddac737e1c06a310a0bb4b3da755a094a31a916a/Symfony/CS/Fixer/Symfony/UnneededControlParenthesesFixer.php#L63
2.x example: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/ControlStructure/NoUnneededControlParenthesesFixer.php#L63 (same fixer)

**Comment by DarkaOnLine** [comment]
@keradus Can you please take a look at this. Am I going in the right direction or not ?

https://github.com/DarkaOnLine/PHP-CS-Fixer/blob/feature-ordered_use_by_length/Symfony/CS/Fixer/Contrib/OrderedUseFixer.php

https://github.com/DarkaOnLine/PHP-CS-Fixer/blob/feature-ordered_use_by_length/Symfony/CS/Tests/Fixer/Contrib/OrderedUseFixerTest.php#L590

**Comment by keradus** [comment]
Please just open a PR with WIP, it would be easier to see the changes.

**Comment by DarkaOnLine** [comment]
Done #2148

**Comment by SpacePossum** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2280 has been merged, so the FR here has been done. Thanks @DarkaOnLine
