### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1802]
Besides the PR's/issues assigned to the 2.0 roadmap, are there any big things still open now the renaming has been done?

I was wondering because of (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1628#issuecomment-191183515);

>For now merging a single fixer from 1.x line to 2.x line could take about 30 minutes...

I know I'm the worst in PR counts, but maybe we should start thinking about a feature freeze on 1.x (or at least no more new fixers?). More and more has to be done to upgrade a Fixer from 1.x to 2.x.
I'm happy to move my PR's to target master, I'm just wondering what everyone else thinks ^-^

Ps.
I know of one issue/bug on the 2.x that is not on 1.x which is related to the `no_extra_consecutive_blank_lines` fixer, I'll focus on that.

**Comment by keradus** [comment]
The roadmap is in issues/PR and is completed. I had few more thoughts what could be done on 2.x line but that could be done on 2.1 as well.

Please do not retarget your existings PRs.
Please do the fix ;)
Features on 1.x line will be frozen as soon as we will have 2.x released.

**Comment by SpacePossum** [comment]
all clear, thanks! :)
