### ISSUE TITLE
Empty line before namespace is always added

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#1804]
With this [configuration file](https://github.com/concrete5/concrete5/blob/develop/.php_cs), the latest version of php-cs-fixer (1.11.2) always adds an empty line before the initiial `namespace` line, even if the configuration says it should not.

With version 1.11.1 and lower it was working fine.

**Comment by GrahamCampbell** [comment]
Hmmm. https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v1.11.1...v1.11.2

**Comment by GrahamCampbell** [comment]
Do you have a file header comment? Can you paste an example file in here please?

**Comment by mlocati** [comment]
Try running both versions with the configuration file I linked above against https://github.com/mlocati/addon_community_translation/blob/master/package/src/Service/Editor.php

**Comment by gharlan** [comment]
The blankline is added by `blankline_after_open_tag`.

**Comment by SpacePossum** [comment]
>The blankline is added by blankline_after_open_tag.

...which has the same priority as `no_blank_lines_before_namespace`. My guess the problem is there, I'll have a look.

**Comment by gharlan** [comment]
Neither one. They are conflicting, this should be solved by #910, not by priorities.

**Comment by SpacePossum** [comment]
There are in cases where there is a file with a namespace directly after an open tag. 
For other files these are not conflicting, so it still make sense to have both fixers applied on a project with files with diff. structures.
