### ISSUE TITLE
Don't rename PHP classes inside their own class as 'self'

### ISSUE THREAD

**Issue by iadj** [FriendsOfPHP/PHP-CS-Fixer#1805]
When calling a PHP class nested inside its own class, i.e. `Model::findOne();` inside `Model.php (PHP Class: Model)`, Beautify automatically rewrites the code as `self::findOne();`. This doesn't work for all frameworks (i.e. Yii2), therefore rendering Atom Beautify useless when used in combination with PHP frameworks.

**Comment by gharlan** [comment]
Could you give us some more details why it is not working?

**Comment by jeroenvdgulik** [comment]
You can use the `-self_accessor` to make it not rewrite to self

**Comment by keradus** [comment]
One could, but we still would like to know why it would break the code, as stated

**Comment by gharlan** [comment]
@ladj maybe you can give us an example class?

**Comment by gharlan** [comment]
ping @ladj

**Comment by keradus** [comment]
Closing for now. @iadj, if you will be able to provide code snippet that is broken by fixer please create new issue.
