### ISSUE TITLE
Adjust PhpUnitDedicateAssertFixer priority on 2.x line

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1817]
Fixer must be run after `no_alias_functions`
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1792#issuecomment-194758297

**Comment by keradus** [comment]
@SpacePossum please, could you take care of this ?

**Comment by SpacePossum** [comment]
will do :)
(please tag the issue as 2.0 so it shows up for the 2.0 release)

**Comment by keradus** [comment]
done
