### ISSUE TITLE
Enabling no_empty_comment fixer with single_blank_line_before_namespace adds empty line between header comment and namespace

### ISSUE THREAD

**Issue by localheinz** [FriendsOfPHP/PHP-CS-Fixer#1822]
When enabling the `no_empty_comment` fixer and when having enabled the `single_blank_line_before_namespace`, running `php-cs-fixer` adds an empty line  between header comment and namespace.

Generally, here's what I do, since I've been waiting for a release of `2.0.0` since #1076:

* regularly, I update `fabpot/php-cs-fixer`, pinning it to a commit in the `master` branch
* explicitly disable or enable fixers (if interesting)
* tag `refinery29/php-cs-fixer-config` so we can use a unified configuration across our projects

## Steps required to reproduce

* updated from https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/1121cf0...535e239 (see https://github.com/refinery29/php-cs-fixer-config/pull/70), which - without enabling any additional fixers - results in removing an empty line between header and namespace
* enabled `no_empty_comment` fixer (see https://github.com/refinery29/php-cs-fixer-config/pull/73), which results in adding an empty line between header and namespace again

:information_desk_person: Not sure if I'm doing it wrong, but I have experienced this a couple of times now when updating `fabpot/php-cs-fixer`, and to me it is unclear what the expected result actually should be with the set of fixers enabled as they are. We are using this configuration both in open and closed source projects, and I figured that with the combination of fixers

* with a header comment given and the `header_comment` fixer enabled, the `single_blank_line_before_namespace` should not kick in
* with no header comment given and the `header_comment` fixer enabled, the single_blank_line_before_namespace` should kick in

**Comment by keradus** [comment]
## quick note for myself
could be connected to #1813, needs further discovery

**Comment by SpacePossum** [comment]
Thanks for the report @localheinz 
I'm pretty sure this is indeed related to 1813 since the fixers listed are not related. Having a set of fixers by level/set with one or more additional rules triggers the new way of sorting (which is correct), causing the priority issue that was previously unnoticed.
Easy way to check would be to ran the tool with any other additional fixer than `no_empty_comment`, I'm pretty sure it will cause the same line adding issue.

**Comment by localheinz** [comment]
Had another look, it could actually be that this is somehow related to having both

* `no_blank_lines` and
* `single_blank_line_before_namespace`

enabled, which, of course, doesn't make a lot of sense (also see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1033#issuecomment-118671524). 

It would be nice if `php-cs-fixer` warned you about using conflicting fixers, though, what do you think?

**Comment by keradus** [comment]
Indeed. Any help is appreciated: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/910

**Comment by SpacePossum** [comment]
>no_blank_lines

which one do you mean? 
(`no_blank_lines_after_class_opening` or `no_blank_lines_before_namespace`)

**Comment by localheinz** [comment]
@SpacePossum 

Ha, my bad - updated my comment above.
