### ISSUE TITLE
broken return fixer removal

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1830]
If there are no braces, then a mess can happen...

```php
<?php

if ($foo) 
    bar();
else
    return;

foo()
```

This valid code gets broken...

**Comment by SpacePossum** [comment]
```php
<?php

if ($foo) 
    bar();
else
    return;

foo()
```

Which fixer is breaking this example? (NoUselessReturnFixer #1832 only checks inside methods/functions and only for the last tokens, so it shouldn't be that fixer...)

**Comment by GrahamCampbell** [comment]
Ah, yeh. Take my example code, and put it inside a method. I meant to do that when i wrote the example.

**Comment by GrahamCampbell** [comment]
New example:

```php
<?php

class Foo
{
    public function bar()
    {
        if ($baz)
            return $this->baz();
        else
            return null;
    }

    public function baz()
    {
        //
    }
}
```

**Comment by GrahamCampbell** [comment]
the return null fixer fixes the return null to just return, and then the return fixer removes the return, thus causing a syntax error with the unexpected brace

**Comment by SpacePossum** [comment]
I messed up the comment to auto close this issue I think (@ https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1836), anyway, @keradus this one can be closed now :)

**Comment by keradus** [comment]
thanks for reminder and closing ;)
