### ISSUE TITLE
linting issue

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1831]
Fixing a file with linting turned off, then turning linting on, but not flushing the cache causes issues because php-cs-fixer is now regarding that file with invalid syntax as fine, because it skipped linting it, even though the previous run of php-cs-fixer broke the file.

**Comment by GrahamCampbell** [comment]
The issue is we consider the null linter to have linted the file. We need to change that concept to introduce the concept of skipping linting instead.

**Comment by keradus** [comment]
I prefer to have NullLinter instead of skipping linting. It simplify code a lot.
Why not add information which linter was used to cache file?

**Comment by GrahamCampbell** [comment]
I guess that will do the equivalent thing.

**Comment by GrahamCampbell** [comment]
@keradus I've implemented your idea here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1845.

**Comment by keradus** [comment]
Closing due to merge of #1845
