### ISSUE TITLE
[Question] phpDoc package tag removal.

### ISSUE THREAD

**Issue by Maikuolan** [FriendsOfPHP/PHP-CS-Fixer#1833]
Currently, PHP-CS-Fixer seems to remove the phpDoc package tag from the phpDoc page-level block.

For example, if I run this through the fixer:

```
<?php
/**
 * Example file.
 *
 * @package Foo/Bar
 */

echo 'Hello World.';
```

It produces this:
```
<?php
/**
 * Example file.
 */
echo 'Hello World.';
```

I'm new to using PHP-CS-Fixer, and discovered this behaviour upon attempting to use it for the first time tonight. Can somebody explain this behaviour to me? Is this intentional, or is this a bug?

Thanks.

**Comment by GrahamCampbell** [comment]
This is intended since `@package` has no use in today's php apps. It was only ever meant to be used to simulate namespaces on php 5.2.

**Comment by Maikuolan** [comment]
Cool, cool. Thanks for the explanation; That answers my question. :-)

I'll close this issue.

**Comment by SpacePossum** [comment]
Ps: kindly note @Maikuolan if you want (or need) to keep those tag, you can disable the `phpdoc_no_package` fixer (either in the configuration or as commandline argument).
