### ISSUE TITLE
sort method of class

### ISSUE THREAD

**Issue by kodermax** [FriendsOfPHP/PHP-CS-Fixer#1835]

**Comment by SpacePossum** [comment]
Not sure what you want here, but please have a look at:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1628

(kindly note this fixer is available only on master)

**Comment by keradus** [comment]
@kodermax please provide any description...

**Comment by keradus** [comment]
Closing due to merge of #1628
