### ISSUE TITLE
Method named "use" not handled correctly

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#1837]
PHP-CS-Fixer incorrectly makes the following edit for the declaration of a method named `use`:
```patch
-    public function use()
+    public function use ()
```

**Comment by keradus** [comment]
Could you share version of PHP CS Fixer and configuration?

**Comment by sebastianbergmann** [comment]
I am using version 1.11.2 and it looks like the `bracers` fixer is to blame.

**Comment by gharlan** [comment]
I think it is related to #1772.
We could use `TOKEN_PARSE` flag, so we would get `T_STRING` token here instead of `T_USE`.

**Comment by keradus** [comment]
`TOKEN_PARSE` is only on PHP7

**Comment by SpacePossum** [comment]
>TOKEN_PARSE is only on PHP7

the issue here is only for PHP7, since the code is not valid for >7  (https://3v4l.org/udmus)

**Comment by gharlan** [comment]
yes. the code is only valid on php 7, too.
we could use the flag on php 7 to fix the php 7 issues.

**Comment by gharlan** [comment]
please also look at my comments in #1772 
(it seems that the flag enables something similar to linting)

**Comment by keradus** [comment]
Closing in favour of #1959, which is combining multiple threads of same issue (#1772, #1837, #1945).
Thank you @sebastianbergmann, @gharlan, @SpacePossum for discussion so far! Please, move forward discussion (if any) to new thread.
