### ISSUE TITLE
[Feature] [PSR-2] One class property declared per statement

### ISSUE THREAD

**Issue by phansys** [FriendsOfPHP/PHP-CS-Fixer#1839]
[PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#42-properties) states the following:
>There MUST NOT be more than one property declared per statement.

So, multiple properties declarations in one statement should be separated in one declaration per statement:
```php
class Foo
{
    protected $bar, $baz = false;
}
```
Must be transformed in:
```php
class Foo
{
    protected $bar;
    protected $baz = false;
}
```
EDITED.

**Comment by keradus** [comment]
Actually the output should be:

```php
class Foo
{
    protected $bar;
    protected $baz = false;
}
```

**Comment by phansys** [comment]
You're right @keradus, I never tested the behavior. I thought that the value was inherited.
Thank you for pointing it, I'm updating the example.

**Comment by phansys** [comment]
#1889 was merged, closing.
