### ISSUE TITLE
Latest 2.x cached performance very poor

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1842]
After the latest changes, the performance when all files are cached is much worse than before. Easily 20x slower than it was before on a code base ~400 files.

**Comment by Anahkiasen** [comment]
I'm observing the same thing on my end, with a full cache it takes a very long time to go through a moderately-sized codebase, used to be a lot faster. I may be wrong thought, may just be my memory, but I definitely got that impression too.

**Comment by GrahamCampbell** [comment]
I think I see the bug. Missing import...

**Comment by GrahamCampbell** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1843.

**Comment by GrahamCampbell** [comment]
Hmmmm. My pull request doesn't seem to fix the issue though. Maybe I was being too optimistic. ;(

**Comment by GrahamCampbell** [comment]
For reference, it's taking php-cs-fixer 16 seconds to go through my codebase, now, whereas before, it was more like 0.3 seconds.

**Comment by GrahamCampbell** [comment]
Slept on it, and have got a second set of fixes that, together with my first PR, should fix this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1844.

**Comment by GrahamCampbell** [comment]
WTF! Even after those PRs, it's still broken!

**Comment by keradus** [comment]
Closing due to merge of #1843 and #1847
