### ISSUE TITLE
LOCK_EX fails error

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1854]
On some filesystems (eg NFS) requiring LOCK_EX fails, which crash the cache mechanism.

error is `Exclusive locks are not supported for this stream`

**Comment by GrahamCampbell** [comment]
Hmmm.

**Comment by GrahamCampbell** [comment]
Maybe we should see what other fileystem abstraction libraries do?

**Comment by keradus** [comment]
I think we could just use this: https://github.com/symfony/filesystem/search?utf8=%E2%9C%93&q=LOCK_EX , but I didn't tried it yet. Usually I work on different FS and it's hard for me to reproduce the error

**Comment by SpacePossum** [comment]
The search doesn't bring up any code anymore, I couldn't find any logic with \in SF/filesystem dealing with LOCK_EX. How about just removing the lock, do we really need it?

**Comment by keradus** [comment]
I don't mind.

what would @localheinz says, our cache expert?

**Comment by SpacePossum** [comment]
ping @localheinz :)
