### ISSUE TITLE
1.12 should be the repo default branch rather than 1.11

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#1857]
1.11 is an old maintenance version now

**Comment by keradus** [comment]
1.12 have few compatibility additions for 2.x line, eg new Config/Finder, and we already have few issues reported that docs saying to use non-existing class. (as one use 1.12 docs for 1.11 tool).

Why do you find it problematic to have latest stable as default branch?

**Comment by stof** [comment]
The issue is that almost no PR should target 1.11, as it is a bugfix-only branch. so making it the default branch opens the door for mistakes

**Comment by keradus** [comment]
On the other side, that would be always a mistake of one men, the one who does the merges.
And mistake of docs not-matching stable version affects many people

**Comment by GrahamCampbell** [comment]
Just set master as default. :trollface:

**Comment by keradus** [comment]
Closing due to discussion.
