### ISSUE TITLE
[FR] Remove @return from constructor PHPDocs

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1859]
Any thoughts about of this fixer/change is welcome?

**Comment by GrahamCampbell** [comment]
We already have a fixer to remove return vid annotations.

**Comment by SpacePossum** [comment]
Do those fix cases like there?

```php
class A
{
    /**
     * @return A
     */
    public function __construct()
    {
    }
}
```

**Comment by GrahamCampbell** [comment]
Well, that phpdoc is incorrect, because constructors return whatever you return from them, and that one there is `void`. I know there was some controversy over this for PHP 7.1, and I really hope their shitty idea of forcefully changing what those magic methods return doesn't actually make it throgh.

**Comment by SpacePossum** [comment]
>Well, that phpdoc is incorrect,

indeed, that is why I would like to have fixer that removes the `@return` from constructors, these have no value IMHO

**Comment by SvenRtbg** [comment]
@GrahamCampbell Constructors don't return anything - that's what makes them special in PHP. The instance of the class is already created, the constructor merely has the chance to initialize some fields or trigger some action, but you'll never see this code assinging `null` to $expectedNull:

    class ThatClass {
    public function __construct() {
        return null;
    }
    // ...
    $expectedNull = new ThatClass();

Some people add an `@return` annotation stating the return value would be "ThatClass", which is also wrong, but does point less into the wrong direction. However, IDEs evaluating annotations might get convinces that a constructor with a `@return` annotation but without an actual `return` statement might contain bugs.

I'd support the code fixer to offer the removal of `@return` annotations from constructors.

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
