### ISSUE TITLE
Verbose setting > Show which fixer changed a file

### ISSUE THREAD

**Issue by ruudk** [FriendsOfPHP/PHP-CS-Fixer#1874]
It would be really nice to see which fixer changed the file and how. Sometimes it's hard to know which fixer did it.

Running `php-cs-fixer fix --dry-run --diff --verbose` shows me all the fixers that actually did something with the file, but also the fixers that didn't change anything at all.

**Comment by keradus** [comment]
Then what fixes you get? all?

Please, provide example with php file, configuration, version of tool and output.

**Comment by SpacePossum** [comment]
Closing as the question for details has been open for almost a year.
