### ISSUE TITLE
malformed phpdoc causes exception

### ISSUE THREAD

**Issue by astletron** [FriendsOfPHP/PHP-CS-Fixer#1877]
Using 1.11.2.  Attempting to fix a file with the following content causes an exception.  Please don't ask me how the inline docs got into such a state.

    <?php
    
    class Sponsor
    {
        /**                                                                                                 * Sets assetDir.                                                                       
         *                                                                                                  * @param  string $assetDir                                                             
         * @return string                                                                                    */
        public function setAssetDir($assetDir = null)
        {
            $this->assetDir = $assetDir;
            return $this;
        }
    }

**Comment by GrahamCampbell** [comment]
That file has invalid syntax, and linting should fail anyway?

**Comment by keradus** [comment]
Yep, invalid file, we don't want to touch it at all.
If tool fail during linting or during fixing (if you don't have linter enabled) that's good.
Fix your file syntax, PHP CS Fixer won't do it for you.

**Comment by astletron** [comment]
Understood that PHP CS Fixer isn't intended to fix invalid syntax.  Certainly not expecting you to fix EVERYTHING.  ;)

I guess this is really more of a feature request/idea.  It would be useful to (at least me, probably others) to get a "your phpdoc is invalid" message rather than just a general "there was an exception processing this file" message.  Looking over other issues, this may be a duplicate of #1176.
