### ISSUE TITLE
One semicolon per line

### ISSUE THREAD

**Issue by 1e0ng** [FriendsOfPHP/PHP-CS-Fixer#1897]
I got the following code and would like to know if there is a way to change it to multi-lines with each line only containing one semicolon?

```
<?php
 chdir('../'); define('IS_UC', true); $_GET['g'] = 'Member'; $_GET['m'] = 'Ucenter'; require './index.php';
```

Expected:

```
<?php
chdir('../');
define('IS_UC', true);
$_GET['g'] = 'Member';
$_GET['m'] = 'Ucenter';
require './index.php';
```

Does this make sense? If it does, I would like to code this fixer and submit a pull request.

**Comment by SpacePossum** [comment]
PSR2
>There MUST NOT be more than one statement per line.

So yes, this would make sense :)
Please check the pr's/issue's since IIRC someone did start on a fixer for this.

**Comment by keradus** [comment]
funny fact here: `braces` already does it, but only for code that is under at least 1-level of braces :d

**Comment by julienfalque** [comment]
See #4885.

**Comment by SpacePossum** [comment]
This one can be closed after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6458 which added rule `no_multiple_statements_per_line` that does what is requested here.
