### ISSUE TITLE
Fix only part of file

### ISSUE THREAD

**Issue by ajax13** [FriendsOfPHP/PHP-CS-Fixer#1902]
Hey, is it possible to fix(or show how to fix) only part(from and to a specific line) of file?
For exemple: 
`php-cs-fixer --verbose --dry-run --diff fix /path/to/file --from:[LineNumber] --to:[LineNumber]`

**Comment by keradus** [comment]
No, as tokenizer must know whole file context to tokenize the code.
Then, at line 2.x we even drop tracking the line numbers.

**Comment by GrahamCampbell** [comment]
I don't see this being possible to easily (or even not easily) implement given the way php-cs-fixer works at the moment.

**Comment by keradus** [comment]
And actually not that big benefit it would bring, as tool follows philosophy "follow standard everywhere or nowhere". So, in this specific case, whole file or nothing.

**Comment by GrahamCampbell** [comment]
I think the application is perhaps similar to an earlier request we had regarding fixing actual diffs.

**Comment by GrahamCampbell** [comment]
I could be wrong. Maybe another application would be in order to skip lines you want to exclude the cs rules on? Jaybe the application of skipping fixers on certain lines would be possible to implement?

**Comment by gharlan** [comment]
#1365

**Comment by keradus** [comment]
Closing as duplicate, thank you @gharlan
