### ISSUE TITLE
Weird replacement notice following abandonment of fabpot/php-cs-fixer

### ISSUE THREAD

**Issue by localheinz** [FriendsOfPHP/PHP-CS-Fixer#1922]
When installing locally, the following notice is generated

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use Use friendsofphp/php-cs-fixer instead instead.
Generating autoload files
```

💁 Notice

```
Use Use friendsofphp/php-cs-fixer instead instead.
```

When you look at https://packagist.org/packages/fabpot/php-cs-fixer, you can see this as well:

![screen shot 2016-05-27 at 16 32 23](https://cloud.githubusercontent.com/assets/605483/15611015/a01c2f30-2428-11e6-904a-2f63c73cac71.png)

Not quite sure if this is a `composer/composer` or `composer/packagist` issue, so opening a ticket here.

**Comment by GrahamCampbell** [comment]
Looks like a composer/packagist bug. ;)

**Comment by GrahamCampbell** [comment]
We've not left a custom message I don't think?

**Comment by gharlan** [comment]
> When you look at https://packagist.org/packages/fabpot/php-cs-fixer, you can see this as well:

And the link to the new package has no href tag.

**Comment by Seldaek** [comment]
Yeah we just assume that people put package names in there not sentences. I corrected it.

**Comment by localheinz** [comment]
@Seldaek 

👍
