### ISSUE TITLE
Wrong namespace fix for symfony tests

### ISSUE THREAD

**Issue by cprn** [FriendsOfPHP/PHP-CS-Fixer#1924]
The following directories structure is in accordance to current Symfony conventions:
```
.
└── tests
    └── Bar
        └── Foo.php
```

This is how namespace should be declared in `Foo.php` according to 2nd example in [manual](http://symfony.com/doc/current/book/testing.html#unit-tests):
```php
<?php

namespace Tests\Bar;

class Foo
{
}
```

Running `php-cs-fixer fix --level=symfony .` changes namespace casing which breaks some functionalities:
```php
namespace tests\Bar;
```

**Comment by localheinz** [comment]
@cprn 

Are you using the PSR-0 fixer?

Noticed this problem a while ago when the PSR-0 fixer was still enabled by default.

Disabling it solved the problem.

**Comment by GrahamCampbell** [comment]
Yeh, this issue can be safely closed. Your codebase is not PSR-0, so please don't run the PSR-0 fixer. I have written a PSR-4 for us (well, I say I wrote it, while my name is on the PR, the code is pretty similar to the PSR-0 fixer, so thanks to the original contributors ;D).

**Comment by cprn** [comment]
@GrahamCampbell @localheinz But shouldn't `--level=symfony` disable PSR-0 and make sure PSR-4 is enabled for me?

**Comment by GrahamCampbell** [comment]
Yes, that's the case in 2.x. We can't change it in 1.x for BC reasons.

**Comment by keradus** [comment]
Closing due to discussion
