### ISSUE TITLE
Add HTML output --format option

### ISSUE THREAD

**Issue by mablae** [FriendsOfPHP/PHP-CS-Fixer#1928]
It would be nice to be able to output a selfcontained HTML Report
with some nice CSS Styling and maybe JS collapsed boxes. 

The gulp-csslist-report plugin could be taken as an example. 

These file could then be handled and shown within the CI Pipeline (Jenkins and Others)

**Comment by keradus** [comment]
Instead of non-standardized HTML page I would go with standard format readable by CI GUIs, eg JUnit: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1825

**Comment by mablae** [comment]
Okay, please close then. XLST transform still possible with XML

**Comment by keradus** [comment]
great to agree on that!
