### ISSUE TITLE
Support turning off the anonymous function part of the braces fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1932]
It would be really good if this could be configured to turn off part that messes with code like this:

```php
$foo = function () {};
```

**Comment by gharlan** [comment]
Please not. It is PSR-2.
We also do not accept things like `class Foo {}`.

**Comment by keradus** [comment]
:+1:
I agree with @gharlan , exceptions are not good

**Comment by GrahamCampbell** [comment]
Well, who's to say everyone wants to follow PSR-2 to the letter. I know a lot of people who are happy to put code like this in their tests.

Could we have the exception being for if there are no tokens between the opening and closing brace, to keep it simple? ie, we still fix `function () { return 'bar'; };`, but we don't change `function () {};`.

**Comment by keradus** [comment]
Closing as there were no votes up and issue is really old.

**Comment by GrahamCampbell** [comment]
There's still a lot of demand for this. I have people asking for this every week.

**Comment by GrahamCampbell** [comment]
I'm happy to implement it, but only if it's wanted.

**Comment by keradus** [comment]
Feel free to implement the change to let the behaviour be configurable, then open a PR.
