### ISSUE TITLE
[FR] Transformer for open tag

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1933]
Currently the open tag `<?php\n` get tokenized as;
```json
{
    "id": 374,
    "name": "T_OPEN_TAG",
    "content": "<?php\n",
    "isArray": true,
    "changed": false
}
```
Suggest to tokenize to two tokens;
```json
{
    "id": 374,
    "name": "T_OPEN_TAG",
    "content": "<?php",
    "isArray": true,
    "changed": false
}
{
    "id": 377,
    "name": "T_WHITESPACE",
    "content": "\n",
    "isArray": true,
    "changed": false
}"
```

If the next token after the open token is a whitespace token the whitespace tokens should be merged into one.

**Comment by keradus** [comment]
so far it was 1 or 2 fixers affected by this.
is it worth to always normalize it ?

if it won't be needed for more transformers then it's not needed to pay transformation cost.

**Comment by SpacePossum** [comment]
You're right, lets park this until needed for the fixer itself and more common cases.
