### ISSUE TITLE
php-cs-fixer.phar

### ISSUE THREAD

**Issue by mambax7** [FriendsOfPHP/PHP-CS-Fixer#1935]
Why is the link: http://get.sensiolabs.org/php-cs-fixer.phar 
links to a:
PHP CS Fixer version 2.0-DEV 
Where can I find the current stable version 1.11.3

**Comment by gharlan** [comment]
ref #1925

**Comment by SpacePossum** [comment]
duplicate:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1925#issuecomment-222225044
@see https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases

**Comment by SpacePossum** [comment]
```
 wget http://get.sensiolabs.org/php-cs-fixer-v1.11.phar -O php-cs-fixer
````

**Comment by mambax7** [comment]
Thank you!

**Comment by keradus** [comment]
Closing as duplicate, contacted with @fabpot on last Friday
