### ISSUE TITLE
Broken concat_without_spaces and full_opening_tag combination

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1937]
Using the latest php-cs-fixer 2.x, enable only the following two fixers: `concat_without_spaces` and `full_opening_tag`, and then with the following valid file, php-cs-fixer breaks it...

**Input:**

```php
<?

$foo =. "bar";
```

**Output:**

```php
<?php

$foo =."bar";
```

PHP now says:

```
Syntax error, unexpected '.' on line 3.
```

**Comment by gharlan** [comment]
The file (input) is not valid!

**Comment by GrahamCampbell** [comment]
LOL, yes indeed. PHP 7's linter said it was valid because short tags were disabled.
