### ISSUE TITLE
no_unneeded_control_parentheses changing code behaviour

### ISSUE THREAD

**Issue by jsor** [FriendsOfPHP/PHP-CS-Fixer#1942]
Running with `no_unneeded_control_parentheses => true` (2.0-DEV) turns

```php
$var = clone ($obj1 ?: $obj2);
```

into 

```php
$var = clone $obj1 ?: $obj2;
```

which changes code behaviour.

**Comment by GrahamCampbell** [comment]
Oh dear, yes. Could result in a fatal error if we try to clone `null` there too. Thanks for the report.

**Comment by keradus** [comment]
Exists on 1.11 as well.
@Soullivaneuh please, could you take a look ?

**Comment by Soullivaneuh** [comment]
Yes. And I supposed that:

```php
$var = clone ($obj1 ? $obj1->getSubject() : $obj2);
```

Should not be changed too, right?
