### ISSUE TITLE
Group use declarations causes internal error

### ISSUE THREAD

**Issue by jaszczurek** [FriendsOfPHP/PHP-CS-Fixer#1944]
This is not working:
http://php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.group
"Files that were not fixed due to internal error"

**Comment by GrahamCampbell** [comment]
Yes, these are known not to be supported by php-cs-fixer.

**Comment by GrahamCampbell** [comment]
> ref: #1119

They are listed in there as todo.

**Comment by SpacePossum** [comment]
ping @jaszczurek the fixer should no longer run into an internal error, it might not fix the CS as you want yet. Could you give it another try?

**Comment by SpacePossum** [comment]
@keradus this one can be closed, issue was fixed and no feedback from reporter

**Comment by keradus** [comment]
I think it's fixed indeed, sad we cannot get a confirmation from @jaszczurek .
Closing as fixed
