### ISSUE TITLE
Remove `JSON_NUMERIC_CHECK` from `Token::toJSON`

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1950]
Example:
```php
<?php
        $token = new Token(array(
            T_STRING,
            'abc'
        ));

        $a = $token->toJson();
        var_dump($a);

        $token = new Token(array(
            T_STRING,
            '1e4000'
        ));

        $a = $token->toJson();
        var_dump($a);
        die;
```

result:
```
string(106) "{
    "id": 308,
    "name": "T_STRING",
    "content": "abc",
    "isArray": true,
    "changed": false
}"
bool(false)
```

on;
`PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) `

**Comment by keradus** [comment]
could it fail for real piece of code ?

**Comment by SpacePossum** [comment]
well depends; if you use the fixer in another project and have token of 2nd type and rely on the JSON method yes, but currently within the fixer project we are OK.

**Comment by keradus** [comment]
OK, I put it in another words.

Could you provide valid PHP code example, that will produce that error for `Tokens::fromCode($example)->toJson()` ?
If so, we should add that test and fix `toJson`. If not, we may add validation to Token construtor (but that could grately decrease our performance, and may not be that much needed)

**Comment by SpacePossum** [comment]
We should be OK using `Tokens::fromCode`, so lets close this :)

**Comment by keradus** [comment]
great to hear!
thanks ;)
