### ISSUE TITLE
PHPUnit 5.4 Warnings

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1951]
![image](https://cloud.githubusercontent.com/assets/2829600/15794414/78e8bedc-29e2-11e6-8480-41ba0640a95f.png)

**Comment by GrahamCampbell** [comment]
Note that the replacement method was only added in PHPUnit 5.4 too.

**Comment by keradus** [comment]
Fix in in RTM state, closing for cleanup
