### ISSUE TITLE
--level

### ISSUE THREAD

**Issue by OxGroup** [FriendsOfPHP/PHP-CS-Fixer#1952]
$ php-cs-fixer fix ./ --level=psr2

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--level" option does not exist.                    
                                                          

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--] [<path>]...

$ php-cs-fixer --version
PHP CS Fixer version 2.0-DEV by Fabien Potencier and Dariusz Ruminski (d0d76b4)

**Comment by GrahamCampbell** [comment]
This was removed in 2.x. Please read the upgrading guide.

**Comment by keradus** [comment]
Closing due to discussion
