### ISSUE TITLE
Wrong version on downloads?

### ISSUE THREAD

**Issue by cedricziel** [FriendsOfPHP/PHP-CS-Fixer#1966]
When downloading the phar from `http://get.sensiolabs.org/php-cs-fixer.phar`, the current version is 1.11.4 where it was before a version with the `--rules` argument existent. - Presumably a build from master.

I just discovered this when a build using the `--rules` argument failed. (https://travis-ci.org/GoogleCloudPlatform/php-docker/builds/135836382)

What are we supposed to to over there? Is this an accident or intended?

Backlink: GoogleCloudPlatform/php-docker#109

**Comment by GrahamCampbell** [comment]
Is http://get.sensiolabs.org/php-cs-fixer.phar not still 2.x? See the previou iussues.

**Comment by SpacePossum** [comment]
`http://get.sensiolabs.org/php-cs-fixer.phar` being `2.dev` was an accident, as we pref. to serve the latest stable on that URL. It is now serving `11.4` (the latest stable).

If you want to keep using `2.dev` (at your own risk) I'm not sure were you can download that one (you can build it yourself).

**Comment by cedricziel** [comment]
Current version:
`PHP CS Fixer version 1.11.4 by Fabien Potencier (eeb280e)`

Alright. Thank you for the prompt answers - very appreciated!

**Comment by keradus** [comment]
@GrahamCampbell I fixed it this morning, during release of 1.11.4

**Comment by keradus** [comment]
@SpacePossum as usuall, `http://get.sensiolabs.org/php-cs-fixer-v%VERSION%.phar`, so `http://get.sensiolabs.org/php-cs-fixer-v2.0.0-alpha.phar`

**Comment by SpacePossum** [comment]
thanks! I tried `http://get.sensiolabs.org/php-cs-fixer-v2.dev.phar`  ^_^
