### ISSUE TITLE
v1.11.4 phar is broken for old PHP

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#1968]
`PHP Parse error:  syntax error, unexpected 'self' (T_STRING) in phar:///var/lib/jenkins/bin/php-cs-fixer/vendor/symfony/process/Process.php on line 538`

refs https://github.com/GoogleCloudPlatform/php-docker/issues/111#issuecomment-224297453

**Comment by GrahamCampbell** [comment]
Looks like the phar was built without respecting the min php version.

**Comment by GrahamCampbell** [comment]
There is an easy fix...

**Comment by GrahamCampbell** [comment]
BUT, it will break testing on symfony 3...

**Comment by GrahamCampbell** [comment]
@keradus See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1969. It will stop the phar getting built with symfony 3 dependencies that need php 5.5.9.

**Comment by SpacePossum** [comment]
Thanks! 
The SF 3 req. shouldn't be a problem right? Since 1.11 doesn't require SF 3.x we can release a phar with 2.x packages?
