### ISSUE TITLE
Class keyword fixers

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1975]
Doc ref: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

My proposal is to create two fixers:
- [ ] `class_keyword`: Replace string like `'Foo\Bar'` by `Bar::class` and add the corresponding import.
- [x] `class_keyword_remove`: Replace all `Foo::class` by the string namespace, like `'Foo\Bar'`. #1985

The first one will be executed only if possible. Example with `'Foo\Bar'`, if a `Bar` class is already imported, this won't do nothing.

Those fixers have to be executed before `ordered_imports`.

Note: Be aware of classes with double dashes: `'Foo\\Bar\\Class'`

Edit: If you think you will need those fixers, vote :+1: on this message.

**Comment by GrahamCampbell** [comment]
Adding the corresponding import might not be possible due to conflicts.

**Comment by GrahamCampbell** [comment]
> class_keyword_remove: Replace all Foo::class by the string namespace.

Resolving these is non-trivial.

**Comment by Soullivaneuh** [comment]
> Adding the corresponding import might not be possible due to conflicts.

Read my sentence after the list. :wink: 

> Resolving these is non-trivial.

What do you mean?

**Comment by greg0ire** [comment]
>     Resolving these is non-trivial.

Probably that the fixer won't work it all cases. However I think a fixer doing a "best effort" would spare a lot of time to people not getting why the tests fail on the legacy branch of the project they are contributing to. And that's the lucky case when there are tests of course.

**Comment by Soullivaneuh** [comment]
> Probably that the fixer won't work in all cases.

`class_keyword_remove` works in all cases for now: #1985

> However I think a fixer doing a "best effort" would spare a lot of time

It will for `class_keyword`. Of course namespace conflict could happen, in this case the fixer can:

* Do nothing
* Use `::class` but with not high level namespace. E.g.: `Foo\Bar::class` instead of `Bar::class`

**Comment by keradus** [comment]
@Soullivaneuh 
no need to thumb up your own proposal ...

**Comment by GrahamCampbell** [comment]
lol

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh 
> no need to thumb up your own proposal ...

Sorry but it's a vote, right? So I voted. :wink:

**Comment by keradus** [comment]
@Soullivaneuh , do you have a safe way to implement second fixer?

**Comment by GrahamCampbell** [comment]
It's impossible to implement safely in any way that isn't total garbage (ie, you could alias all imports to some long random string). People could define classes more than one per file, or in any non-PSR way, so there really is no way to guess, even if we could look around at the filenames in the current folder.

**Comment by keradus** [comment]
depends, you may have it working safely in only few cases, that why I asked what @Soullivaneuh has on his mind

**Comment by Soullivaneuh** [comment]
@keradus I was thinking about add the `'Foo\Bar'` string simply to the import list and add the `::class` keyword.

Obviously, it will be a risky fixer because a string can contain slashes without meaning this is a class name usage. Maybe we can propose an `ignore_strings` option.

**Comment by keradus** [comment]
big :-1: for that solution.

```php
$myDirs = [
    'Foo\Bar',
    'Foo\Baz`,
];
```

would be modified into:

```php
use Foo\Bar;
use Foo\Baz;
$myDirs = [
    Bar::class,
    Baz:class,
];
```


`ignore_strings` option to provide array of strings that is supposed to be ignored? then you would make codebase worst first, then ask user to verify the output and store all the exceptions, clear the repo state and apply the fixer once more :/

**Comment by GrahamCampbell** [comment]
👎 For this fixer.

**Comment by keradus** [comment]
on the other side, this is possible:
```php
use Foo\Bar;
use Foo\Baz;
$myDirs = [
    'Foo\Bar',
    'Foo\Baz`,
];
```

would be modified into:

```php
use Foo\Bar;
use Foo\Baz;
$myDirs = [
    Bar::class,
    Baz:class,
];
```

**Comment by Soullivaneuh** [comment]
@keradus Yes, this is exactly what I would like to do.

Indeed, if no corresponding namespace is included, we have nothing to do.

Another example for global namespace:

```php
$stdClass = '\StdClass';
```

Can be moved to:

```php
$stdClass = \StdClass::class;
```

**Comment by TomasVotruba** [comment]
You can try `string` => `::class` in practise. I've added it as a part of [Symplify\CodingStandard]( https://github.com/Symplify/CodingStandard#class-references-should-be-used-over-string-for-classes-and-interfaces)

[![image](https://user-images.githubusercontent.com/924196/28240992-d37b4dc6-698b-11e7-897e-37b9f73eace4.png)](https://github.com/Symplify/CodingStandard#class-references-should-be-used-over-string-for-classes-and-interfaces)

Any [feedback or issue](https://github.com/Symplify/Symplify/issues/new) appreciated.

[Class is here](https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Php/ClassStringToClassConstantFixer.php).

**Comment by keradus** [comment]
Closing due to #2918. if we could get this done, it will be done in PR. if not, both PR and ticket will be closed anyway.
