### ISSUE TITLE
Single line class and method declaration fixers

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1976]
Those fixers should be on the Symfony group according to the [coding standards](http://symfony.com/doc/current/contributing/code/standards.html#structure):

> * Declare the class inheritance and all the implemented interfaces on the same line as the class name;
> * Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;

- [x] Class declaration: #1979 
- [x] Method declaration: #1980

**Comment by SpacePossum** [comment]
>Those fixers 

we don't have those ^-^

**Comment by Soullivaneuh** [comment]
> > Those fixers

> we don't have those ^-^

Oh, really? :trollface:

**Comment by keradus** [comment]
Closing due to merge of #2155 and existence of #1980
