### ISSUE TITLE
Multiple argument isset refactor fixer

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1977]
Isset cans take several arguments.

So a code line like this:

``` php
if (isset($criteria['date']) && isset($criteria['date']['query']) && isset($criteria['date']['params']))
```

Can be turned to this:

``` php
if (isset($criteria['date'], $criteria['date']['query'], $criteria['date']['params']))
```

I don't think the fixer will be risky, will be?

**Comment by SpacePossum** [comment]
this can indeed be done, :+1:   for the idea :)

**Comment by Soullivaneuh** [comment]
@keradus On which group this should be added? Symfony? Contrib? CaptainObvious?

We should definitely create a CaptainObvious one. :trollface:

**Comment by Soullivaneuh** [comment]
BTW, the same can be done for `unset`.

Before:

```php
unset($foo);
unset($bar);
```

After:

```php
unset($foo, $bar);
```

**Comment by keradus** [comment]
We already have `combine_consecutive_unsets`

**Comment by keradus** [comment]
Closing due to merge of #3012
