### ISSUE TITLE
anonymous function return type breaks fixer

### ISSUE THREAD

**Issue by digitalkaoz** [FriendsOfPHP/PHP-CS-Fixer#1981]
```php
        $pimple['decode_worker'] = function (Container $pimple) : Worker\Worker {
            return new Worker\DecodeWorker();
        };
```

will be fixed into 

```php
        $pimple['decode_worker'] = function (Container $pimple) : Worker\Worker {
            return new Worker\DecodeWorker();
        }
```

but only if i turn of linting...

if i remove the return type everything works fine

**Comment by GrahamCampbell** [comment]
We don't support files that use return typehints.

**Comment by GrahamCampbell** [comment]
See the existing issue please.

**Comment by digitalkaoz** [comment]
mh it works in all other classes as expected...

**Comment by digitalkaoz** [comment]
im using the 2.0 branch btw

**Comment by keradus** [comment]
Thank you @digitalkaoz for your report.
We are not yet fully supporting PHP 7, but we are working on it, last one is to handle semi-reserved keywords.
Closing as duplicate of #1119. Please, feel free to help bringing PHP 7 syntax support ;)
