### ISSUE TITLE
Proposal not to not support phpdoc format array<string, int>

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1984]
We currently don't support this, and I think we never should. It's a stupid syntax, and conficts with https://wiki.php.net/rfc/generics.

**Comment by Soullivaneuh** [comment]
I don't use it but I think it's recognized by IDEs and used to specify what is in the array.

> It's a stupid syntax

Why?

> and conficts with https://wiki.php.net/rfc/generics.

In which cases? BTW, you are talking about PHP 7 only.

**Comment by SpacePossum** [comment]
PSR 5 doen't provide an alternative.
Link to generics is not about PHPDocs.
I don't see an issue.

**Comment by GrahamCampbell** [comment]
The syntax is stupid because `<string, int>`, to me, doesn't indicate, ok, put strings and ints wherever you want, it indicates, string, then int, with some intrinsic meaning, where the order matters. One such use is generics.

**Comment by keradus** [comment]
PSR5 specify it quite well and there is only one way of understanding it.
`Collection<VAL>` for collection of items of VAL type
`Collection<KEY, VAL>` for collection of items of VAL type indexed by KEY type.

Which in fact is just like referred proposal: `Entry<KeyType, ValueType>`

--------------

I don't see any value for dropping this syntax (even if we don't support it everywhere yet). If you don't like the syntax just don't do it. I, often, whenever possible, just create dedicated class for my collection. But in rare cases when that wound't be good I use `array<string, Foo>` which provides more information than `Foo[]`.
If you don't like that syntax - just don't use it ;)

---------------

btw, ref. proposal is 5 months old, last modified 6 weeks ago, not big interest in it...

**Comment by GrahamCampbell** [comment]
> Collection<VAL> for collection of items of VAL type
> Collection<KEY, VAL> for collection of items of VAL type indexed by KEY type.

Oh, I see! I like that then. But, see what I mean about misunderstanding it, and actual use of it being low?

**Comment by keradus** [comment]
I found it very useful for assoc arrays or doctrine collections ;)
