### ISSUE TITLE
unused_use [symfony] bad behavior

### ISSUE THREAD

**Issue by ctf0** [FriendsOfPHP/PHP-CS-Fixer#1986]
example
```php
<?php

namespace App\Http\Controllers;

use App\Something;
use App\Http\Controllers\Controller;

class FooController extends Controller
{
 ...
}
```
currently both of the use statements will be deleted, while `use App\Http\Controllers\Controller;` should be kept.

using **homebrew/php/php-cs-fixer: stable 1.11 (bottled)**

**Comment by keradus** [comment]
You don't need to import class that is inside same namespace.

**Comment by GrahamCampbell** [comment]
Yeh, no bug.

**Comment by ctf0** [comment]
oki doki, many thanx then :)

**Comment by keradus** [comment]
btw, it may be nice to rename fixer to not lead to that misunderstanding
Then, we could also make it configurable, as it's very easy to apply configuration as the separated ideas (remove not used imports / remove not needed due to same namespace imports) are separated in code as well.

**Comment by ctf0** [comment]
@keradus 👍  for the short description of the fixer

**Comment by keradus** [comment]
Sorry, didn't get that one. What do you mean ?

**Comment by ctf0** [comment]
i meant adding short description under fixers to make it easier for the users to understand how its gonna effect their code.

**Comment by keradus** [comment]
Feel free to send PR to change `getDescription` ;)

**Comment by ifeltsweet** [comment]
Would be nice to have a fixer that does not remove imports in the same namespace because we like to keep a visual map of all used classes at the top of the file and it also helps with refactorings and searching.

**Comment by SpacePossum** [comment]
@ifeltsweet please create a new issue for your request, this one has been closed for a long time so not all responses might still be valid, thanks!
