### ISSUE TITLE
inline namespaces to move namespaces up top

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#1996]
is there a fixer that moves all inline long namespaces on a codebase to the top and shortens the names automatically?

**Comment by SpacePossum** [comment]
You mean something like;
expected;
```php
    use Symfony\CS\Tokenizer\Tokens;

    public function a()
    {
        $a = new Tokens();
    }
```
input:
```php
    public function a()
    {
        $a = new \Symfony\CS\Tokenizer\Tokens();
    }
```
No, there isn't one here.

**Comment by cordoval** [comment]
will there be ever one?

**Comment by keradus** [comment]
You are welcome to contribute @cordoval !

**Comment by cordoval** [comment]
would be terrific, i have no time now but will certainly look if you help me

**Comment by keradus** [comment]
This could be nice for a start:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/COOKBOOK-FIXERS.md

**Comment by FraGoTe** [comment]
+1

**Comment by GrahamCampbell** [comment]
:-1: We have no way to do this without potentially breaking the code due to collisions with existing class names in the same namespace.

**Comment by cordoval** [comment]
it should be a controlled run rather than a totally automated thing, i can go and fix some left overs for sure, it is just so tedious sometimes

**Comment by cordoval** [comment]
@GrahamCampbell usually the use scenario is that the people choose really separate class names so even if i try to create collisions there is none. So this fear should be remedied with a stern warning about this or just have the fixer not do the changes when in doubt, for everything else it should tackle the refactor. Does this option sound better?

**Comment by cordoval** [comment]
i went and solved it by hand since phpstorm had the feature so closing.

**Comment by voku** [comment]
@cordoval where is the feature in phpstorm? I didn't find it. :-/
