### ISSUE TITLE
Space after array language construct

### ISSUE THREAD

**Issue by Gemmu** [FriendsOfPHP/PHP-CS-Fixer#1997]
As PSR2 states:
> Control structure keywords MUST have one space after them; method and function calls MUST NOT.

According to php.net manual `array` is a language construct, not a method or function call. Therefor it could be that the format `$thing = array ();` is more appropriate than `$thing = array();`

In my opinion the array construct should be removed from the FunctionCallSpaceFixer.php.

**Comment by keradus** [comment]
> According to php.net manual `array` is a language construct

could you ref that?
ref : http://php.net/manual/en/function.array.php

even from url - "function array"

**Comment by SpacePossum** [comment]
```
Note:
array() is a language construct used to represent literal arrays, and not a regular function.
```

its on the page, however I still pref. `array()`

**Comment by keradus** [comment]
so, sth like `not a regular function` but still `odd type of function` ? :)

**Comment by gharlan** [comment]
> In my opinion the array construct should be removed from the FunctionCallSpaceFixer.php.

I agree here. It is not a function, so it should be removed.

(but I wouldn't write `array ()`)

**Comment by Gemmu** [comment]
Around the php.net's examples it has been used as `array()` and `array ()`. The PSR doesn't mention any 'language constructs' or how they should be presented.

Should it be moved from the PSR2 to those contrib level fixers? And should the fixer fix it to with or without the space? I'm not really sure about that. 

On a personal note, I have been using the extra space just to differentiate it from functions. Not sure about the benefits on that one, but maybe it goes something like this:

1. Add space after `array`
2. ...
3. Profit

**Comment by SpacePossum** [comment]
don't fix other language construct calls like `unset ($a)` as well?

**Comment by gharlan** [comment]
I would say yes. We could add another fixer for them.
(But it is not a strong opinion here, it is ok for me when we handle them like functions, because I want to use same style for them anyway, and it is also symfony coding style.)

**Comment by Gemmu** [comment]
Should all the language constructs (with[out?] spaces) be moved under symfony then? As the psr2 doesn't really say anything about these language constructs. Only about functions and control structure keywords.

**Comment by gharlan** [comment]
I see three variants:

1. We do not change anything
2. We make the fixer configurable (fix function-like language constructs, or not), the option would be enabled only in symfony level
3. We remove language constructs from the fixer and and add a new fixer for them in symfony level. There could be another fixer for using spaces after language constructs in contrib level.

**Comment by keradus** [comment]
I think that actually that was the idea of PSR2 to treat them the same way.
But I agree it's not well documented.

If somebody really need to have that space we could split them, but is there really a need for that ?

**Comment by Gemmu** [comment]
Well if the spirit of the PSR2 is that the language constructs must be treated like functions then it's all right by me to use the FunctionSpaceFixer. The guide itself leaves too much room for interpretation, and in my opinion should be fixed, but that's another project.

**Comment by SpacePossum** [comment]
>, but that's another project.

You might want to propose it for PSR12
https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md

I think calls to language constructs should be the same as function and method calls, i.e. without the space, so no changes needed.

**Comment by keradus** [comment]
So, ticket ready to be closed ?

**Comment by Gemmu** [comment]
Yep,
