### ISSUE TITLE
Fix indentation in OOP Nesting

### ISSUE THREAD

**Issue by citosid** [FriendsOfPHP/PHP-CS-Fixer#2000]
Is there a way to fix this:

``` php
$object->method()
       ->another()
       ->oneMore();
```

And turn it into this:

``` php
$object->method()
    ->another()
    ->oneMore();
```

The difference is that, according to [This Link](http://pear.php.net/manual/en/rfc.cs-enhancements.splitfunccall.php) when nesting, we should have only 4 spaces in the line under, not in the same column the first `->` was added.

**Comment by keradus** [comment]
Wow, PEAR standards... someone is still using them :D

One way or another, I like it the second way, a fixer would be nice for it.
Could you work on it please?

**Comment by citosid** [comment]
@keradus we are not using them fully, we are using PSR-2 and PSR-4, but this standard from PEAR is nice, the code is more readable, and I could not find anything in PSR.

I could, do you have any suggestion on how to do it?

**Comment by keradus** [comment]
if the first token of line is `->` then check indentation of prev line, add one level of deep to it and fix current line indentation, if needed

Also, please check README and CONTRIBUTING files

**Comment by keradus** [comment]
Closing as #3063 bringing this feature is already released for ages.
We simply forgot to close this feature request ;)
