### ISSUE TITLE
fapbot/php-cs-fixer is abandoned, yet it's in the readme

### ISSUE THREAD

**Issue by slikts** [FriendsOfPHP/PHP-CS-Fixer#2008]
In README.md:

> $ ./composer.phar global require fabpot/php-cs-fixer

Meanwhile: https://packagist.org/packages/fabpot/php-cs-fixer

> This package is abandoned and no longer maintained. The author suggests using the friendsofphp/php-cs-fixer package instead.

**Comment by SpacePossum** [comment]
Hi!
Thanks for reporting!
Currently the PHP-CS-Fixer is being moved from `fabpot` to `FriendsOfPHP` on packagist (its been done on github for a while). This will be finalized when 2.0 is released as stable. The warning you get is just a bit premature. 
For ref.: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2006 (and others)

**Comment by slikts** [comment]
This came up for me because `./composer.phar global require fabpot/php-cs-fixer` does not work on Windows; running it results in "Could not find package fapbot/phab-cs-fixer at any version for your minimum-stability (stable)". Meanwhile, friendsofphp/php-cs-fixer worked.

**Comment by gharlan** [comment]
> "Could not find package fapbot/phab-cs-fixer at any version for your minimum-stability (stable)"

who is `fapbot` and what is a `phab-cs-fixer`? ;)

**Comment by slikts** [comment]
Good questions.
