### ISSUE TITLE
PHP7 new custom tokens

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2015]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1989#issuecomment-227204801

```php
<?php
use some\a\{ClassA, ClassB, ClassC as C};
use function some\a\{fn_a, fn_b, fn_c};
use const some\a\{ConstA, ConstB, ConstC};
```

I would like to introduce 2 new custom tokens for given `function` and `const`.
Any thoughts ?

**Comment by gharlan** [comment]
good idea! #1107 ;)

**Comment by keradus** [comment]
hahahahaha :dancer:

**Comment by SpacePossum** [comment]
didn't know... .0.o ... we going to need make some (big) changes on the master version of #1989 .....

**Comment by keradus** [comment]
Yep, I will handle it during merging to 2.x.
I'm just waiting for that WIP flag to be removed ;)
