### ISSUE TITLE
PHP7 unicode escape update

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2016]
```php
echo "\u{26C4}";
```

**Comment by keradus** [comment]
OK, actually I'm confused what was the syntax on 5.x, if there were any ?

**Comment by SpacePossum** [comment]
I don't think there is on >7 and the new feature is something inside a string (literal), so I'm not sure how what support could or should add?

**Comment by keradus** [comment]
I was (wrongly) thinking that there is some equivalent notation for PHP5. I cannot find any now.
They add a feature to handle unicode in 7, not change the syntax for it.

In that case, closing.
