### ISSUE TITLE
Binary cast fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2021]
expected

``` php
<?php
$binary = (binary)"binary string";
```

input

``` php
<?php
$binary = b"binary string";
```

**Comment by keradus** [comment]
PHP7 only, right ?

**Comment by SpacePossum** [comment]
this is valid on the 5.x line as well (I think 4 even)

**Comment by GrahamCampbell** [comment]
PHP 5.2.1 and upwards.

* https://3v4l.org/pJAEF
* https://3v4l.org/dEutW

**Comment by SpacePossum** [comment]
I'll reopen as soon as we know if https://wiki.php.net/rfc/deprecations_php_7_2 makes it,
if so than we can safely remove all the binary casts (in all syntax forms) all together (and I think safely on all PHP versions).
