### ISSUE TITLE
PHP-CS-Fixer leaves a temporary file at the root of the project

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2022]
When using the 1.11.4 version, a ``cs_fixer_tmp_...`` file stays at the root of the project at the end of the run

**Comment by GrahamCampbell** [comment]
It does try to remove it. It just silences any errors when it does I think?

**Comment by stof** [comment]
Well, I ran the tool several times, and it left such a file for each run. So the logic trying to remove it seems broken.

In case this matters, I was using PHP 5.6 when running it

**Comment by GrahamCampbell** [comment]
Is it possible your file viewer was locking the file so PHP couldn't delete it? Try removing the `@` from the `unlink`?

**Comment by keradus** [comment]
It would be great if you could play with it @stof, I can't reproduce it

**Comment by adawolfa** [comment]
I have experienced this as well, files named `cs_*.tmp` appeared in my working directory when fixer failed. I am pretty sure this is caused, at least in my case, by `Symfony\Component\Filesystem\Filesystem` class, which is used by `LintManager`. The `Filesystem` class removes temporary files in destructor, which will not get called occasionally (when an exception occures, etc).

**Comment by GrahamCampbell** [comment]
If it's a fatal error that occurs, then I'd expect this since PHP does not execute object destructors when a fatal error occurs.

**Comment by keradus** [comment]
We could register shutdown function. That would solve the issue. The only tricky part would be to create utest for it

**Comment by GrahamCampbell** [comment]
Yeh, that's exactly it. :/

**Comment by keradus** [comment]
@adawolfa could you please send a PR to solve the issue ?

**Comment by adawolfa** [comment]
@keradus Will do soon.

**Comment by tgabi333** [comment]
+1 with version 1.12
