### ISSUE TITLE
PhpdocAnnotationWithoutDotFixer removes '...' step by step

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#2027]
```php
/**
 * @param string $foo Foo, e. g. "bar", "baz", ... 
 */
```

`PhpdocAnnotationWithoutDotFixer` removes the '...' one by one. So you have to run the fixer 3 times to remove all dots.

**Comment by keradus** [comment]
Actually, the `...` should not be removed.
People often use `...` (3 chars) instead of `…` (1 char). The later one is handled correctly, the first one is not.

Do you want to send a bugfix for it ?

**Comment by GrahamCampbell** [comment]
@keradus We should probably just update this fixer to trim any and all punctuation, zero or more instances of the end.

**Comment by keradus** [comment]
Why not trim trailing dot if it is not directly preceded by another dot ?

**Comment by gharlan** [comment]
I could send a bugfix next week

**Comment by GrahamCampbell** [comment]
What about other variants of punctuation?
