### ISSUE TITLE
Fixer for missing root namespaces in @expectedException

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#2028]
From https://github.com/symfony/symfony/issues/19237

> I noticed this at the workflow component and decided to do a quick scan
> 
> Im talking about `@expectedException \Exception` vs. `@expectedException Exception`. Without `use` statements the latter works for phpunit but breaks editor click-throughs, at least phpstorm.
> 
> Searched with `@expectedException\s+[^\\\s]` with 34 results on master (not checked for `use` statements). Perhaps something to automate?
> 
> Not sure about [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerNameParserTest.php#L111) one :-)

I would be nice if we can force consistent behaviour, i.e. convert everything to use statements, _or_ everything to FQCN's without use statements.

**Comment by SpacePossum** [comment]
I would like this a lot :)
This fixer should be marked as risky I think, for example:
```php
    /**
     * @expectedException UnexpectedValueException
     */
    public function testRegisterFixerWithOccupiedName()
    {
        a();
    }
```

when fixed to:

```php
    /**
     * @expectedException \UnexpectedValueException
     */
    public function testRegisterFixerWithOccupiedName()
    {
        a();
    }
```

if `a()` would throw;
```php
namespace My\Poor\Named\Exception;

class UnexpectedValueException extends \Exception
{
}
```

then the behavior is changed.

**Comment by ro0NL** [comment]
Well... if `a()` throws `\My\Poor\Named\Exception\UnexpectedValueException` it should be 

`@expectedException \My\Poor\Named\Exception\UnexpectedValueException`

**or**

```
use My\Poor\Named\Exception\UnexpectedValueException
@expectedException UnexpectedValueException
```

**Comment by GrahamCampbell** [comment]
PHPUnit does not read impors.

```
use My\Poor\Named\Exception\UnexpectedValueException
@expectedException UnexpectedValueException
```

That will expect `UnexpectedValueException` not `My\Poor\Named\Exception\UnexpectedValueException`.

**Comment by SpacePossum** [comment]
indeed
```php
<?php
namespace My\Poor\Named\Exception;

class InvalidArgumentException extends \Exception
{

}

class MyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException InvalidArgumentException
     */
    public function testException()
    {
        a();
    }
}

function a()
{
    throw new \InvalidArgumentException();
}
```

this works. 
Resolving the FQCN of the `@expectedException` class might be tricky though.

**Comment by ro0NL** [comment]
> PHPUnit does not read imports.

Are you sure?! This affects symfony tests wich arent breaking currently :confused: or these are false positives right now.. which would be quit.. eh.. shocking.

One more thing; this also affects `@throws` but i havent checked for incorrect occurrences yet.

**Comment by SpacePossum** [comment]
if you change
```php
throw new \InvalidArgumentException();
```
to 
```php
throw new InvalidArgumentException();
```
you'll see that PHPUnit handles the exception without FQCN checking well

**Comment by keradus** [comment]
also, when possible (depends on PHPUnit version) I would suggest to use `->expectException`

**Comment by GrahamCampbell** [comment]
I don't think Sebastian has any plans to add this sort of thing to PHPUnit in the future.

**Comment by ro0NL** [comment]
To clearify, does this mean current tests are invalid?

I.e. is [this](https://github.com/symfony/symfony/blob/f29d46f29b91ea5c30699cf6bdb8e65545d1dd26/src/Symfony/Component/Asset/Tests/PackagesTest.php#L60) test a false positive?

**Comment by GrahamCampbell** [comment]
That test works because Symfony\Component\Asset\Exception\LogicException extends LogicException.

**Comment by ro0NL** [comment]
Exactly.. but this is not intended right afaik. I.e. a false positive... @fabpot  what about that?

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/symfony/pull/19243

**Comment by ro0NL** [comment]
From https://github.com/symfony/symfony/pull/19243

> - FQCN annotations from phpunit should be fully qualified (root namespace is optional, but pragmaticly prefered now for editors and is less error prone whenever phpunit alters (IMHO))
> - FQCN annotations from phpdoc can be fully qualified (with root namespace) or partial (with use statement)

My consensus so far..

**Comment by keradus** [comment]
partial is working? I dont think so

**Comment by ro0NL** [comment]
By "partial" i mean relative, i.e.;

```php
namespace A;
use Foo\Bar\Partial;
//@return Partial (Foo\Bar\Partial)
```

or

```php
namespace B;
//@return Partial (B\Partial)
```

vs

```php
namespace C;
//@return \Root
```

This is valid PHP, ie. also how PHP7 return-types _work_. Based on the symfony testsuite i assumed `@expectedException` follows the same logic. For consistency i would say always declare the root namespace (`\`) for `@expectedException` (there can be no confusion also). But i dont really mind, i just think the tests should be fixed ASAP :)

**Comment by GrahamCampbell** [comment]
> By "partial" i mean relative, i.e.;

Well, really, you mean "aliased". That's what's actually going on.

**Comment by ro0NL** [comment]
Yes. Which reminds me.. does it need to resolve, eh, aliases, i.e.
```php
use Foo\This as That;
//@expectedException That
```

This should probably never occur for `@expectedException` as your test will fail, but if the fixer is really generic it could be useful other FQCN annotations.

**Comment by keradus** [comment]
Big :-1: for using FQCN for other annotations.
for given example of `@return` - it's not needed. Strict typehinting in PHP7 (outside the comment) don't need to use FQCN as well, and mixing the notation in typehint and doctyping will not looks nice.

PHPUnit 4, as old enough, don't handle not-FQCN names in that annotation, but it also drops it in favor of ->expectException. So for that, if one want to make fixer to deal with phpunit annotation - go ahead, but I see no value in changing it for all annotations

**Comment by ro0NL** [comment]
> but it also drops it in favor of ->expectException
url?

Anyway, `$this->expectException(\InvalidArgumentException::class);` should definitely be preferred. Forget the generic stuff, as `expectedException` cannot be compared to other annotations this way.

So indeed.. this is not a real codestyle fixer. However it could fixup your tests producing false unintended false positives. Do you see any value in that, or is out of scope for PHP-CS-Fixer?

**Comment by keradus** [comment]
> url ?

https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions

**Comment by keradus** [comment]
As told before, checking if annotation for `@expectedException` is FQCN would be fine, but I'm against that part:
> but if the fixer is really generic it could be useful for other FQCN annotations.

**Comment by keradus** [comment]
just let it be configurable and everybody will set up his own annotations, don't assume it for him, like changing `@return` annotation by default

**Comment by ro0NL** [comment]
configurable == generic imo. Ie. im not talking about 1 fixer that does everything, but a _reusable_ fixer. But like i said, forget the generic stuff, its not my point.

For now, my concern is expectedExcception producing (unintended) false positives. However, technically we cant assume the user's intention;

```php
use Foo\Something
//@expectedException Something
```
Is intended to work as "test for `\Something`" or "test for `\Foo\Something`"? Considering `class \Foo\Something extends \Something`.

And im not sure its a CS thingy anyway, however we could provide a fixer that resolves **or** removes the unneeded uses for `@expectedException`.

**Comment by keradus** [comment]
> a fixer that resolves or removes the unneeded uses for @expectedException

resolve - like adding `\` on the beginning - good
resolve - like guessing that you are using imported class and you should not rely on import - tricky and a lot of false positives
Conclusion: configure two things: annotations that are modified and way of modification (only add missing `\` or resolve import as well)

remove - I don't get it, remove what ?

> Which is... risky :)

Yes, we have risky fixers. Even with special flag that they are risky ;)

**Comment by ro0NL** [comment]
remove - never mind (UnusedUseFixer :)).

> Yes, we have risky fixers. Even with special flag that they are risky ;)

I thought this was a little too risky ^^

How would you name the fixer?

**Comment by keradus** [comment]
In the end I would only add missing `\` and not trying to resolve imported class to FCCN, as utests written that way shouldn't work at the first place (excepting inheritance cases).

What about `PhpUnitExpectedExceptionAlwaysWithLeadingSlash` ? name is long, but rule is very specific .

**Comment by SpacePossum** [comment]
I agree with @keradus description on what the fixer should do. 

`PhpUnitExpectedExceptionWithDefaultNamespace`
but I wouldn't down vote the other name suggestion  ;)

**Comment by SpacePossum** [comment]
@ro0NL do you have plans to work on this?

>also, when possible (depends on PHPUnit version) I would suggest to use ->expectException instead of annotation

I wouldn't advise it @ see https://github.com/sebastianbergmann/phpunit/issues/2074#issuecomment-183472385

**Comment by ro0NL** [comment]
No, im not ;-) point was the (unintended) false positives in the symfony codebase. By now, i hope they are aware of it.
