### ISSUE TITLE
"no whitespaces between offset accessors"

### ISSUE THREAD

**Issue by phansys** [FriendsOfPHP/PHP-CS-Fixer#2035]
Input:
```php
<?php
$foo [0] [1]   [2] = 3;
$bar = $foo [0] [1]   [2];
$baz [0]
     [1]
     [2] = 3;
$foobar = $foo {0} [1]   {2};
$withComments [0] // here is a comment
     [1] // and here is another
     [2] = 3;
```
Expected:
```php
<?php
$foo[0][1][2] = 3;
$bar = $foo[0][1][2];
$baz[0][1][2] = 3;
$foobar = $foo{0}[1]{2};
$withComments [0] // here is a comment
     [1] // and here is another
     [2] = 3;
```

**Comment by keradus** [comment]
multiline should be addressed as well
`{` for indexes too

**Comment by phansys** [comment]
@keradus, I've added more use cases, but really I don't know what to do in some cases, by instance, if there are comments between these accessors.

**Comment by keradus** [comment]
For sure not remove them ;) I will ignore whitespaces between `]` and `[` if there is comment between.

**Comment by SpacePossum** [comment]
@keradus can be closed since https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2089 has been merged :)

**Comment by keradus** [comment]
thanks
