### ISSUE TITLE
Inconsistency between systems

### ISSUE THREAD

**Issue by mnabialek** [FriendsOfPHP/PHP-CS-Fixer#2043]
This is quite strange issue. I have project that I'm running on Docker. I've installed on Windows latest version, same in Docker machine. However on Windows I'm not getting all the errors fixed whereas on Linux I do.On Linux I've also got this "Files that were not fixed due to internal error:" error (which shows the file with problem) whereas on Windows this error does not happen. Is it normal or maybe something in broken and causes inconsistency in verifying files?

**Comment by keradus** [comment]
No, it shouldn't.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2042#issuecomment-230360160

**Comment by mnabialek** [comment]
Ok, so the question is what is going on? I believe other developer using Windows got some files fixed and I haven't on Windows (but have in Linux) - I'm talking about exact same files. I've also removed cache file manually just to make sure it's not a cache problem but it seems it isn't. Is there any way there's some strange bug?

I've updated to latest v.1.12 dev branch and on windows I've got something like this:

In all above steps I'm running `php-cs-fixer --verbose fix` command

1) I've run 1.12.dev on Windows. I've got something like this:

> .......F........FF...........................I............................FI......I.F...............F.............F......F.....F...................F.....F....F...........FIF.....................F....F
.......F....F.....F....F....FFF.......II..II.........FF..........I..F...F..........I.....F

So some files were fixed, some were invalid

2) I've run 1.12 dev on Windows. I've got something like this:

> IIIIIIIIIIIIII

So I'm getting Invalid file syntax, but php-cs-fixer shows no details

3) For exactly same files I run fixer on Linux (after fixing on Windows) and I'm getting something like this:

> ...........................................................................F......................................................................................................................................................FFFF........................................................F...FF.....................F.................F......

4) Now I again run fixer on Linux and I'm getting nothing so it seems now everything is correct.

Exact output for this is:

> Loaded config from "/usr/share/nginx/html/.php_cs".
> 
> Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
> Fixed all files in 2.289 seconds, 6.000 MB memory used

So it seems somehow that on Windows php-cs-fixer is not able to fix. Upgrading into 1.12-dev as you see haven't changed this. This is exact same as on 1.11.4

**Comment by keradus** [comment]
As you could imagine without information about the files we cannot guess anything.

Please, took one `F` and one `I` file from your Windows run.
make sure there are not modified on Unix.

on both env, run: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2042#issuecomment-230360160

Also, `-vvv` could be a bit helpful during running the `fix` command.

---------------------------

BTW, be extra sure that the reason is not that GIT your Windows converts unix line endings for Windows one and then you are running PHP CS Fixer to convert them back to unix

**Comment by mnabialek** [comment]
@keradus I probably now what's happening, in file that is not fixed on Windows, I use scalar type hinting introduced in PHP 7. On Windows I have PHP 5.6.0 installed, whereas on Linux I have PHP 7. So the question is - does php-cs-fixer needs PHP version installed in same version as files that are checked? If I remove int type hinting, now the file is correctly fixed on Windows

In requirements there is only info about 5.3.6 version. If version of PHP should be exact same, I would recommend adding this into readme because many developers are using virtual machines and probably many might have such situation.

There is also a problem with `-vvv` option, If I use it on list of files on Windows I'm getting this file listed like so:

> [0.027 s] Models\Notification.php
> ...
> Fixed all files in 1.226 seconds, 5.250 MB memory used

There is no a single warning/failure that file cannot be verified and without this second php-cs-fixer on Linux I wouldn't even know that for example this exact file causes any problem. It would be better if it was displayed somewhere with info that file is in incorrect PHP version or something like this.

**Comment by keradus** [comment]
Maybe we introduced the invalid list only on 2.x then, don't remember.

To run the tool you need PHP 5.3.6.
To fix the file - you need PHP version that supports file syntax you are using. If you want to fix PHP7 file using PHP5... c'mon...
Tool won't error on that file (`E`rror), it will just ignore file with unknown syntax (`I`gnore).

**Comment by mnabialek** [comment]
To be honest I was never thinking how php-cs-fixer is fixing files, but I thought it does not need the same PHP version. I would rather expect it's parsing only PHP file (as text) without need to have the same version, but now it's clear for me it does need the same version.

**Comment by keradus** [comment]
Again, it _DOES NOT_ need the same version.
For running the tool - 5.3.6+.

For fixing files - at least the version of PHP that started supporting syntax used in given file, for each of them individually.

If you have:
- file_a.php - using 5.6 syntax, you will have it fixed on PHP 5.6+|7+ 
- file_b.php - using 7.0 syntax, you will have it fixed on PHP 7+

So if you have only that 2 files you still can run the tool on 5.6, but it will handle only files with recognized syntax - so file_a.php.
Of course on PHP 7 you will get better results, as it will recognize more files.

In the end, if you would have project written for 5.2, then you may use PHP 5.3.6+ to fix it,

**Comment by mnabialek** [comment]
Yeah, this is what I mean - to fix all files you need to have PHP version installed in at least same version as those files syntax .

**Comment by SpacePossum** [comment]
>to fix all files you need to have PHP version installed in at least same version as those files syntax .

More or less, as the fixer lints the files some new syntax elements might be a problem (for example with PHP7(.1)), but for a lot of PHP minor releases this hasn't been an issue.
I would say it fair to expect that when you have code that you cannot run because it relies on new features on some env.; it cannot be fixed in that env. either.

> many developers are using virtual machines

Typically devs. run a higher PHP version on their dev. setup than the version on their VM. Using VM's  for projects req. older PHP versions is a very good idea. I just cannot think of a reason why someone wants to dev. on 5.x and use a VM on 7 and not the other way around. Or stated diff. why someone would setup/use an dev. enviroment _lower_ than the PHP version developing for. Beside this fixer a lot of other development tools like SCA's (based on tokens) and such will not be helpful as well.
But sure it can happen.

I agree we could improve the error/warning messaging especially on `-vvv` level, its just that no one got the time to do it so far.

**Comment by mnabialek** [comment]
@SpacePossum The reason is than I'm on Windows platform and cannot set up here easy many things as for example supervisor etc whereas in virtual machine I can have almost everything same as on live Linux server. And it's not only PHP version but also MySQL so it's more convenient to use virtual machines for that. I'll of course update to PHP 7 on local machine too.

**Comment by keradus** [comment]
`choco install php -version 7.0.5` ;P

**Comment by mnabialek** [comment]
Never used choco before, need to check :)

**Comment by SpacePossum** [comment]
> choco install php -version 7.0.5 ;P

: D

ps. just run the fixer on the VM and you are all set! :)  best of luck!
pps. Snippet from my provision bash script for VMs
```bash

if command_exists php-cs-fixer ; then
	php-cs-fixer selfupdate
else
	wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer
	chmod a+x php-cs-fixer
	mv php-cs-fixer /usr/local/bin/php-cs-fixer
	php-cs-fixer -V
fi
```

**Comment by mnabialek** [comment]
@SpacePossum This is exactly what I was doing when talking about Linux in this thread :)
