### ISSUE TITLE
Unable to disable unalign_equals filter

### ISSUE THREAD

**Issue by hackel** [FriendsOfPHP/PHP-CS-Fixer#2052]
I'm trying to figure out how to configure php-cs-fixer to use the align_equals fixer in addition to the default Symfony config.  Here is my .php_cs:

```php
$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in(__DIR__ . '/app')
    ->exclude(__DIR__ . '/app/storage');

return Symfony\CS\Config\Config::create()
    ->fixers(['-unalign_equals', 'align_equals'])
    ->finder($finder);
```

In this case, unalign_equals still gets applied.  If I add `--fixers=align_equals` on the command-line, it works fine.  Am I missing something here?

I'm running php-cs-fixer 1.11.4 on PHP 7.0.8.

**Comment by hackel** [comment]
Hmm.  I've tried it with just the file name, and adding `-vv` and `--diff` to try to figure out what is going on.  I just tried to set `--config-file` (even though I'm using the default .php_cs), and that seemed to use the fixers from the config file, however it ignored the filename I specified on the cli and started processing the entire path defined in the config!

Is this actually the intended behaviour?  I expected it to work more like phpunit  and similar tools, where specifying a file or directory on the cli will override what is in the config.

**Comment by GrahamCampbell** [comment]
Yeh, it's intended. I think it was changed a bit on 2.x though. @keradus?

**Comment by regularjack** [comment]
I'm having a similar problem, `-unalign_double_arrow` is ignored. My config looks like this:

```php
return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    ->fixers(['-unalign_double_arrow'])
;
```

The only cli arg being passed is the path to the config file.

Using version 1.12.0 on PHP 7.0.

**Comment by SpacePossum** [comment]
are you sure the `unalign_double_arrow` still is applied and not some other fixer does changes you didn't expect?
You can check by passing the `-vvv`, at the end it will list the fixers applied.

**Comment by regularjack** [comment]
You're right @SpacePossum, after running with `-vvv` I could see that `operators_spaces` was being applied. Adding `'-operators_spaces'` to the config fixes it.

This is kind of un-intuitive, but I guess making fixers not step over each other is not an easy problem to solve.

**Comment by SpacePossum** [comment]
>however it ignored the filename I specified on the cli and started processing the entire path defined in the config!
>Is this actually the intended behaviour?

I wish it wasn't, but it has been discussed and I'm not sure where the community stands ATM

>Adding '-operators_spaces' to the config fixes it.

This is indeed an unwanted side effect of a change I've made.
Not sure what the fix should be, IIRC @keradus and @GrahamCampbell had a discussion about it when I was AFK for a few weeks.

**Comment by GrahamCampbell** [comment]
I'd say we need to just remove the unalign double arrow and equals fixers in 2.x, and add config to the operator spaces fixer,

**Comment by GrahamCampbell** [comment]
That said, `=` and `=>` aren't really operators in the same sense as `+`?

**Comment by SpacePossum** [comment]
Not sure what you mean. These only differ. in the sense that some people want to align those, or is there something else?
I add the exceptions to the `operators_spaces` on 1.11/1.12 and then we can discuss master after that.

**Comment by keradus** [comment]
> I'd say we need to just remove the unalign double arrow and equals fixers in 2.x, and add config to the operator spaces fixer.

just saw it, :+1:, I proposed the same in @SpacePossum fix PR


> That said, `=` and `=>` aren't really operators in the same sense as `+`?

They are

**Comment by SpacePossum** [comment]
@keradus this one can be closed because of merge of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2164

**Comment by keradus** [comment]
Thanks !
2164 didn't link this issue ;)
