### ISSUE TITLE
ClassDefinitionFixer incorrectly fixes valid multi-line "implements" sections with only one interface

### ISSUE THREAD

**Issue by ezzatron** [FriendsOfPHP/PHP-CS-Fixer#2053]
In [PSR-2 section 4.1. Extends and Implements](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#41-extends-and-implements):

> Lists of implements MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one interface per line.

But `ClassDefinitionFixer` currently only allows multi-line `implements` definitions when there is more than 1 interface name. This additional restriction is **not** part of the PSR-2 spec.

The relevant code can be found on [this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/5de5794c0409982c5ed36aaa1546d2fa6d5fdf24/src/Fixer/ClassNotation/ClassDefinitionFixer.php#L76):

```php
if ($implementsInfo['numberOfInterfaces'] > 1 && $implementsInfo['multiLine']) {
```

This bug is currently causing issues with the use of multi-line `implements` definitions that are long because of the length of class names, and not the number of implemented interfaces:

```php
class VeryLongClassNameWithLotsOfLetters extends AnotherVeryLongClassName implements
    VeryLongInterfaceNameThatIDontWantOnTheSameLine
{
}
```

The above is erroneously "fixed" to become:

```php
class VeryLongClassNameWithLotsOfLetters extends AnotherVeryLongClassName implements VeryLongInterfaceNameThatIDontWantOnTheSameLine
{
}
```

I tried to create a PR, but ran into some issues with an existing test case that broke. I was not sure of the intent of the test case, so I thought it better just to report the bug instead.

**Comment by SpacePossum** [comment]
Thanks for reporting!
I cannot recall I took this case into consideration when writing the fixer, so yes this could be a valid bug report. Feel free to open your PR including the failing test case, please add [WIP] in the title and tag me, happy to help you out :)

**Comment by ezzatron** [comment]
Okay, no worries.

**Comment by sharifzadesina** [comment]
This is same with more than one interface.

**Comment by SpacePossum** [comment]
@ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2155

**Comment by keradus** [comment]
Closing due to merge of #2155
