### ISSUE TITLE
Bug in lowercase_keywords with PHP7

### ISSUE THREAD

**Issue by tgabi333** [FriendsOfPHP/PHP-CS-Fixer#2070]
It seems that PHP7 does not fix `Foo:CLASS` to `Foo:class`

See: https://github.com/tgabi333/PHP-CS-Fixer/commit/b797c5469a305f32ec998a4355038e507a7fcef6 and https://travis-ci.org/tgabi333/PHP-CS-Fixer/builds/143955227

**Comment by GrahamCampbell** [comment]
That's not a lowercase keyword in the same sense that `true` and `false` is?

**Comment by SpacePossum** [comment]
It is a keyword, but used for something else than `true` and `false`,
for ref.: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

Since the introduction all methods of casing of `::class` are allowed (https://3v4l.org/c2ogC), so this can be fixed by a fixer.

**Comment by GrahamCampbell** [comment]
Ok, right. :+1: for adding this to the existing fixer then.

**Comment by tgabi333** [comment]
It is currenlty works for PHP5 but not for PHP7

**Comment by tgabi333** [comment]
Here is the problem: https://3v4l.org/YYNPS

Came with this commit: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/0668080d9dbfa31b0b61badf94a7c4b0bc5e5004

**Comment by SpacePossum** [comment]
so the token for `class` changed from T_CLASS to T_STRING on PHP7... hmm :)
thanks for the info!
btw. do you plan for writing a PR to fix this on the PHP-CS-Fixer?

**Comment by tgabi333** [comment]
I would love to help you. I'm still investigating the root problem. Found this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/search?utf8=%E2%9C%93&q=CT_CLASS_CONSTANT

**Comment by SpacePossum** [comment]
I think the root might be that the custom CT_CLASS_CONSTANT token type is not listed as keyword here;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Tokenizer/Token.php#L264
(but I didn't look into it in depth to see what might happen if it was added)

**Comment by tgabi333** [comment]
I found too, thank you @SpacePossum , tomorrow i will create a proper PR for this. 

https://travis-ci.org/tgabi333/PHP-CS-Fixer/builds/143990898

**Comment by keradus** [comment]
remember, 1.11 for bugfix.
