### ISSUE TITLE
ignoring remove_lines_between_uses fixer is useless

### ISSUE THREAD

**Issue by mmoreram** [FriendsOfPHP/PHP-CS-Fixer#2074]
Having this .php_cs file...

``` php
<?php

return Symfony\CS\Config\Config::create()
    // use SYMFONY_LEVEL:
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    // and extra fixers:
    ->fixers(array(
        'concat_with_spaces',
        'multiline_spaces_before_semicolon',
        'short_array_syntax',
        '-remove_lines_between_uses',
        '-empty_return',
        '-phpdoc_var_without_name',
        '-phpdoc_to_comment',
    ))
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in('src/')
            ->in('tests/')
    )
;
```

all spaces between my use statements are removed, even if the fixer `remove_lines_between_uses` are explicitly disabled.
After debugging a little bit the application, I've discovered that there is a fixer that is not doing what really has to do.

From the documentation...

* single_line_after_imports [PSR-2]
Each namespace use MUST go on its own line and there MUST be one blank line after the use statements block.

This fixer is removing my empty lines, and it shouldn't.

**Comment by SpacePossum** [comment]
Hi thanks for reporting,

could you provide the following;
```
$ php -v
$ php-cs-fixer -v
```

**Comment by mmoreram** [comment]
I'm using version 1.11

**Comment by keradus** [comment]
@mmoreram please check out #2077 ;)
