### ISSUE TITLE
Dot after :

### ISSUE THREAD

**Issue by umpirsky** [FriendsOfPHP/PHP-CS-Fixer#2083]
PHPDoc fixer adds triling dot even when sentence ends with `:`:

Before:
```
/**
 * Example list:
 *
 * - item1
 * - item2
 */
```

After:

```
/**
 * Example list:.
 *
 * - item1
 * - item2
 */
```

**Comment by keradus** [comment]
Your PHPDoc Description must be after Summary, which is missing in your case. Add missing Summary.

**Comment by SpacePossum** [comment]
This is because of the `phpdoc_short_description` so you might want to switch it off. The rule is based on [PSR5] (https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#51-summary).

**Comment by umpirsky** [comment]
OK, thanks!
