### ISSUE TITLE
exclude folders does not work

### ISSUE THREAD

**Issue by tniemann** [FriendsOfPHP/PHP-CS-Fixer#2094]
Hi,

i just updates and to the newest version.
But now my excluded folders are srill scaned and fixed.

This is how my .php_cs file locks like located in the root:

```
$finder = PhpCsFixer\Finder::create()
    ->exclude(['web', 'var'])
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'full_opening_tag' => false,
    ])
    ->finder($finder)
;
```

How can i avoid to scan specified folders?

Regards,
Thomas

**Comment by keradus** [comment]
```bash
php -v
php-cs-fixer -v
```
?

**Comment by tniemann** [comment]
PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58) 
PHP CS Fixer version 2.0-DEV by Fabien Potencier and Dariusz Ruminski

and i use Symfony 3.2.1

Thx.

**Comment by keradus** [comment]
> also, what is the full CLI command you are using ?

**Comment by tniemann** [comment]
vendor/bin/php-cs-fixer -v fix .  from the root

**Comment by tniemann** [comment]
i installed it via composer

**Comment by keradus** [comment]
is it 
`vendor/bin/php-cs-fixer -v fix .` from the root
or
`vendor/bin/php-cs-fixer -v fix` . from the root

(so if dot is a part of command or not) ?

**Comment by tniemann** [comment]
yes.. dot is a part of the comment

**Comment by SpacePossum** [comment]
try with `-vvv --dry-run`, I suspect your config file is not used (the `-vvv` should state it does)

**Comment by keradus** [comment]
Then you are specifying the path in your config file, and then override it via CLI param.
either don't specify it via CLI param (as it's `current dir` and not sth more precise), or use `--path-mode=intersection` param to make intersection of your config path and CLI arg path.

**Comment by SpacePossum** [comment]
the `dot` is part of the comment on github, not of the bash command I believe

**Comment by tniemann** [comment]
ok.. got it. Solved!! Thx.
