### ISSUE TITLE
Request: Support for custom template formats (Blade)

### ISSUE THREAD

**Issue by hackel** [FriendsOfPHP/PHP-CS-Fixer#2099]
This may be considered outside of the scope of this project, but I didn't see it mentioned anywhere yet so I thought I would throw it out there.  It would be really useful if there was a way to define custom php start/end tags for compatibility with various contemplating systems.  My use-case is Laravel Blade.  I've been trying to clean up one old project in particular and it has a lot of code like this:
```blade
{{ Form::label ('month', 'Expiration Date', array("class" => "col-md-5 required") )  }}
```
If there was a way I could tell php-cs-fixer to treat {{ }} as if it was equivalent to <?= ?>, then it could do things like convert that array to short-syntax, replace the double-quotes, fix the spacing, etc.:
```blade
{{ Form::label('month', 'Expiration Date', ['class" => "col-md-5 required']) }}
```

I'm not sure if there's a way to implement this as a custom fixer, since I would still want it to apply all of the other fixers I have enabled, just within those tags as well.

**Comment by keradus** [comment]
In general - no.
We are using native PHP tokenizer / linter, and for it given code sample is not PHP code as well.
You cannot easily hook into them to modify the allowed opening tags.
So, the general answer is no - PHP CS Fixer will not do what you ask.

For that, you would have to create a custom fixer that will replace `{{` with `<?php` and `}}` with `?>`, that will run before all fixers, and second one which would do the revers and run after all fixers.
Actually, you could do it outside PHP CS Fixer as well.

**Comment by hackel** [comment]
Ahh, okay that makes sense.  Perhaps it could replace `{{` with e.g. `<?php/*@blade-start*/` or something so that only those specific tags would be converted back at the end.  It would screw up the character counts, unfortunately, but I suppose that's a small price to pay.

**Comment by keradus** [comment]
Depends do you want to run the fixer then on all files on only on those templates.
I would say that blindly changing `{{` into opening tags could be problematic and may have some risky edge cases, so I would do it in separate run, but in the end it is up to you ;)

As said before, translating non-php into php is not a job for this tool, it needs to be handle outside.
Therefore closing due to discussion.
