### ISSUE TITLE
multiple_use analogue for traits

### ISSUE THREAD

**Issue by Strate** [FriendsOfPHP/PHP-CS-Fixer#2103]
As for now, therer is seems no rule, which forces each use of trait be on separate line:

``` php
class Some
{
  use SomeTrait, OtherTrait;  
}
```

should be reformatted by the rule to:

``` php
class Some
{
  use SomeTrait;  
  use OtherTrait;
}
```

**Comment by SpacePossum** [comment]
indeed, check 1.12 and master and both don't do that, nice FR!

**Comment by phansys** [comment]
I think it could be added as an option at "single_class_element_per_statement" fixer.

**Comment by SpacePossum** [comment]
or maybe `single_import_per_statement`? not use....

**Comment by keradus** [comment]
`single_class_element_per_statement`
trait import is not element of class. it's an instruction to import some elements

**Comment by SpacePossum** [comment]
check and agreed :)
`single_class_element_per_statement` it is, anyone got time to pick this up?

**Comment by keradus** [comment]
I think you not understand my comment in a way I hope to express, sorry.
I'm against making it in `single_class_element_per_statement`, as import trait statement is not element of class itself.

**Comment by SpacePossum** [comment]
I did misread indeed,  new fixer than?

**Comment by keradus** [comment]
I would say that having some other opinions would be great ;)

**Comment by keradus** [comment]
@Strate are you interested in creating PR for this feature request ?

**Comment by Strate** [comment]
@keradus I hope, but I am not sure that I'll have enought spare time for this. So, let keep it vacant :)
