### ISSUE TITLE
Formatting "} else if (..) { }"  into an "} else { if () { } }"

### ISSUE THREAD

**Issue by larsengel** [FriendsOfPHP/PHP-CS-Fixer#2107]
Hey everyone, 
I executed the following fixers in my project:  
- short_tag
- encoding
- braces
- indentation
- line_after_namespace
- visibility

Unfortunately the fixers did the following to my else ifs:

**Before:**
```php
if ($name == '-api') {
...
} else if ($name == '-target_dir') {
...
} else if ($name == '-version') {
...
} else if ($name == '-unsafe' && $params[++$i] == 1) {
...
}
```
**After:**
```php
if ($name == '-api') {
...
} else {
   if ($name == '-target_dir') {
   ...
   } else {
      if ($name == '-version') {
      ...
      } else {
         if ($name == '-unsafe' && $params[++$i] == 1) {
         ...
         }
      }
   }
```

Is this a whised behavior?

Best Regards,

Lars

**Edit:**

- Version: PHP CS Fixer version 1.11.6 by Fabien Potencier (41dc93a) 
- I executed the fixer with the following command: `sudo php php-cs-fixer.phar fix <path_to_project> --fixers=short_tag,braces,line_after_namespace,visibility`

**Comment by keradus** [comment]
Please provide the version you are using, CLI command and config file (if there is one)

**Comment by GrahamCampbell** [comment]
Looks correct to me. If you enable the elseif fixer too, it won't do this.

**Comment by keradus** [comment]
yep, braces is adding missing braces for new scope, and else is creating a scope, in your case you have only one thing in that scope - `if`.

**Comment by natewiebe13** [comment]
Is there a way to prevent this from happening without using the elseif fixer?

We need to still specify that braces should be on the same line, and want to use `else if`

**Comment by keradus** [comment]
no, after `else` you have a block which shall be wrapped with braces. `if` is already part of that block (and it creates it's own block)

**Comment by natewiebe13** [comment]
Would you be open to a merge request for the elseif fixer that had a setting to use `else if` instead of `elseif`?

**Comment by keradus** [comment]
changing behaviour of `elseif` fixer won't affect `braces` fixer, and you originally asked about changing behaviour of `braces` fixer.
on now, you are talking about other thing? if so, my personal vote would be :-1: as it would violate PSR, but you would have to convince community, not me.
