### ISSUE TITLE
Broken short array syntax fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2116]
Ther short array syntax fixer after the latest commit also unalings the equals too...

**Comment by SpacePossum** [comment]
Can you provide an example?

**Comment by GrahamCampbell** [comment]
I think this is actually caused by the transformer changes. https://github.com/laravel/framework/pull/14681/commits/c0305b4dab922b6da7c235a6484f654dcda8b6e7

**Comment by keradus** [comment]
Please provide specific version (what is latest commit? at least which line) and minimal code sample that describes issue.

**Comment by GrahamCampbell** [comment]
Broken on master branch. Not broken 18 days ago on master.

**Comment by GrahamCampbell** [comment]
Unrelated to the short array syntax fixer. Happens with double arrow unalign turned off and with short array syntax turned off.

**Comment by keradus** [comment]
To be honest I have no idea what is the bug you are trying to report. To messy, too few information.
Please create a PR with utests. Or even with a fix.

**Comment by GrahamCampbell** [comment]
laravel/framework@c0305b4

The above happened with zero config changes. The unalign double arrow fixer was not turned on.

**Comment by GrahamCampbell** [comment]
I'll try and send a proper bug report once I get time. Sorry this one was really shitty.

**Comment by keradus** [comment]
ping @GrahamCampbell
