### ISSUE TITLE
Conflicting fixers

### ISSUE THREAD

**Issue by petski** [FriendsOfPHP/PHP-CS-Fixer#2123]
Consider this test-file:

```php
<?php
$short = ['a', 'b', 'c'];
$long  = array('a', 'b', 'c');
```
This would fix the $long-array to a short syntax:

`$ php-cs-fixer fix . --level none --fixers='long_array_syntax,short_array_syntax' --verbose --dry-run --diff`

This would ALSO fix the $long-array to a short syntax: (note that I updated the order of fixers):

`$ php-cs-fixer fix . --level none --fixers='short_array_syntax,long_array_syntax' --verbose --dry-run --diff`

(I suspect the fixers are handled in an alphabetical order.)

I would suggest to display a warning (or even throw an exception?) in case fixers "collide"/"conflict" with each other.

Use cases: 

- concat_without_spaces vs concat_with_spaces
- align_double_arrow vs unalign_double_arrow
- align_equals vs unalign_equals
- short_array_syntax vs long_array_syntax

**Comment by GrahamCampbell** [comment]
This has already been implemented on 2.x. :)

**Comment by petski** [comment]
This is amazing :) I can confirm this feature exists in 2.0.0-alpha:

```bash
$ wget http://get.sensiolabs.org/php-cs-fixer-v2.0.0-alpha.phar -O php-cs-fixer
$ chmod +x php-cs-fixer
$ ./php-cs-fixer fix --dry-run --diff . --rules 'short_array_syntax,long_array_syntax'
                                                   
  [UnexpectedValueException]                       
  Rule contains conflicting fixers:                
  - "short_array_syntax" with "long_array_syntax"  
```
If we'll ever meet, first drink is on me :)
