### ISSUE TITLE
Space between the declare statement and parenthesis

### ISSUE THREAD

**Issue by nikolaposa** [FriendsOfPHP/PHP-CS-Fixer#2125]
`brace` CS fixer is adding needless space between the `declare` and parenthesis. I was able to reproduce this behavior on version **1.11.6**.

Expected:
```php
declare(strict_types=1);
```

Actual:
```php
declare (strict_types=1);
```

**Comment by keradus** [comment]
Please, could you check 1.12@dev ?

**Comment by nikolaposa** [comment]
Seems fine on 1.12.

**Comment by sstok** [comment]
Works on master also 👍
