### ISSUE TITLE
Problem running php-cs-fixer on windows

### ISSUE THREAD

**Issue by Med-Seif** [FriendsOfPHP/PHP-CS-Fixer#2126]
I tried to launch php-cs-fixer on wondows 7 x64 and I always an error "php CLI error".
I inspected the error in windows events observer and I found that it was related to "MSVCR90.dll" module error.
My php version is 5.3.8.0

Thank you in advance

**Comment by keradus** [comment]
I use the tool heavily on Windows platform and it works like a charm.
It looks like your php env is not installed properly or your VS libraries are messy.

Update your env and try again.

**Comment by keradus** [comment]
(BTW, our Windows CI is working as well ;) )

**Comment by Med-Seif** [comment]
Thank you, You're right I re-installed Xampp and worked fine now

They installed Xampp not directly in C:\
