### ISSUE TITLE
Use HTTPS for downloads & website

### ISSUE THREAD

**Issue by rugk** [FriendsOfPHP/PHP-CS-Fixer#2127]
You should use HTTPS for both http://cs.sensiolabs.org/ and get.sensiolabs.org.
Currently anyone can MITM the download of this `.phar` file and inject malicious code.

**Comment by keradus** [comment]
should be changed since 1.11.5: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/c7d50c5feb2b0de88f4a852871b58f8bcc37536b

looks like webpage is outdated

**Comment by rugk** [comment]
Yes, it seems to be this way. Also HTTPS is not configured correctly on these sites:
* https://cs.sensiolabs.org/ (wrong cert, only valid for security.sensiolabs.org, www.security.sensiolabs.org, and mixed content errors)
* https://get.sensiolabs.org/ (no server found)

Downloading the files from GitHub is okay, but also the sensiolabs sites should use HTTPS.
