### ISSUE TITLE
Generic.Functions.FunctionCallArgumentSpacing

### ISSUE THREAD

**Issue by designermonkey** [FriendsOfPHP/PHP-CS-Fixer#2130]
I have set `phpcs` to ignore this setting, yet I cannot prevent fixer from 'tidying' it up.

What is the corresponding fixer so I can exclude it?

**Comment by keradus** [comment]
I would say you wanted to ask that question on `PHP CodeSniffer` repo, not `PHP Coding Standards Fixer`. Closing.

**Comment by designermonkey** [comment]
Why do I need to ask it there, when it is an issue with the fact that cs fixer is not allowing me to exclude the setting?

I am asking if there is a specific fixer I can exclude that would not fix this setting. For example:

```
--fixers=-function_call_argument_spacing
```

which does not exist.

This request is wholly about the fixer, not `phpcs` itself, which is working as expected.

**Comment by GrahamCampbell** [comment]
What made you think it would have the same name?

**Comment by keradus** [comment]
@designermonkey you provided information that you are using `phpcs` and give rule from `phpcs`...
very well, provide a code snippet you are fixing, actual and expected output, PHP CS Fixer version, configuration file and CLI command you are using.

**Comment by keradus** [comment]
Sadly, this issue report provide non information what you want to achieve. Missing answer for requested information is not helping as well. Referring to another tool setting won't help us well.
For all that - closing, again.

What you should do is to read the README file and take a look what are our current fixers. Also, you could check with rules were applied on your code.
`method_argument_space` may or not be the fixer you are looking for.
