### ISSUE TITLE
PHP 5.3 Phar Broken

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2134]
As travis shows.

**Comment by GrahamCampbell** [comment]
> PHP Parse error:  syntax error, unexpected T_STRING in phar:///home/travis/build/FriendsOfPHP/PHP-CS-Fixer/box.phar/src/vendors/symfony/process/Process.php on line 538

https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/152603392

**Comment by GrahamCampbell** [comment]
This is because you're building the phar with perfer lowest, instead of just saying you need PHP 5.3 compatible dependency resolution. The two are not the same thing.

**Comment by GrahamCampbell** [comment]
Worse than that, you're pulling in buggy insecure dependencies too. ;(

**Comment by keradus** [comment]
yep, I noticed that :/

**Comment by keradus** [comment]
one thing is to fix it, but I would say more important is to prevent it to happen again

**Comment by GrahamCampbell** [comment]
One fix could be to require that securing repo that prevents insecure deps getting loaded. The second thing to do would be not to use prefer-lowest. Why do we need that. Just use the normal install on PHP 5.3, because, let's face it, PHP 5.3.9 deps will still work for us on PHP 5.3.3. That's exactly what composer does when it builds it's phars.

**Comment by keradus** [comment]
but you are talking about fix (which I agree with), not the protector to not have it happen again.

**Comment by keradus** [comment]
> One fix could be to require that securing repo that prevents insecure deps getting loaded.

totally not related

> The second thing to do would be not to use prefer-lowest. Why do we need that. [...]

We need that to check if min version we are saying we do support we support indeed.
But we do not use prefer-lowest for building phar. only for running utests and fix command

**Comment by keradus** [comment]
The fail is actual on box part, not in our code

**Comment by GrahamCampbell** [comment]
I'd say it's our fault 100%.

**Comment by keradus** [comment]
Based on what ?
It's box issue, I just confirmed it: https://github.com/box-project/box2/issues/151
I will move building phar file to 5.6, then it will work. (But that's only workaround, box issue is still there)

**Comment by GrahamCampbell** [comment]
I thought that syntax error was in our deps, not boxes?

**Comment by keradus** [comment]
no, error is from box.phar/vendors/...

**Comment by GrahamCampbell** [comment]
Hmmm.
