### ISSUE TITLE
Broken fixing

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2135]
The following file when fixed at the symfony level results in invalid syntax:

```
<?php
return [
    
    /*
     * |--------------------------------------------------------------------------
     * | Default Broadcaster
     * |--------------------------------------------------------------------------
     * |
     * | This option controls the default broadcaster that will be used by the
     * | framework when an event needs to be broadcast. You may set this to
     * | any of the connections defined in the "connections" array below.
     * |
     */
    
    'default' => env('BROADCAST_DRIVER', 'pusher'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [
        
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_KEY'),
            'secret' => env('PUSHER_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => []
        ]
        //
        
        ,
        
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default'
        ],
        
        'log' => [
            'driver' => 'log'
        ]
    ]
]
;
```

I guess it's due to that comma and the comment just above the word redis.

---

I'll provide more useful information at the weekend:

* A minimal fixer set to use.
* A minimal test case.

**Comment by keradus** [comment]
Please also provide version of the tool, PHP and even the fix ;)

**Comment by GrahamCampbell** [comment]
PHP 7.0.3, and the tool version is the commit one before that completely broken commit on the master which made it unusable. :trollface:

**Comment by GrahamCampbell** [comment]
> completely broken commit on the master which made it unusable. :trollface:

Try turning off the double arrow unalign fixer and using the symfony level on the current master. You'll see that it still unaligned double arrows.

**Comment by keradus** [comment]
don't you refer different issue now? we still waiting for more information about it, even better - if only you could reproduce it you could just fix it as well.
reports like "sth is not working" isn't useful :D

**Comment by GrahamCampbell** [comment]
Yeh, I know, lol. I just don't have time to properly look into it today. I'll provide proper information at the weekend. :)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
Not enough information, cannot do anything with this issue.
Closing as reported doesn't care... :/
