### ISSUE TITLE
Fixer cookbook missing implementation of abstract methods.

### ISSUE THREAD

**Issue by g105b** [FriendsOfPHP/PHP-CS-Fixer#2136]
When following https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/COOKBOOK-FIXERS.md step by step, the last point of step 1 can't be completed (`php php-cs-fixer readme > README.rst`) as the following error message is displayed:

```
PHP Fatal error:  Class Symfony\CS\Fixer\Contrib\RemoveCommentsFixer contains 
2 abstract methods and must therefore be declared abstract or implement the 
remaining methods (Symfony\CS\FixerInterface::fix, Symfony\CS\FixerInterface
::getDescription) in PHP-CS-Fixer/Symfony/CS/Fixer/Contrib/RemoveCommentsFixer.php
on line 11
```

I will raise a PR shortly.

**Comment by SpacePossum** [comment]
@keradus : closing due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2197 ;)

**Comment by keradus** [comment]
thanks
