### ISSUE TITLE
Fix readme : fabpot/php-cs-fixer -> friendsofphp/php-cs-fixer

### ISSUE THREAD

**Issue by jfx** [FriendsOfPHP/PHP-CS-Fixer#2146]
In README.rst file, composer installation part :
Modify 
`./composer.phar global require fabpot/php-cs-fixer`
to
`./composer.phar global require friendsofphp/php-cs-fixer`

**Comment by GrahamCampbell** [comment]
Please see the 1.12 or master branches.

**Comment by keradus** [comment]
Already done, closing

**Comment by jfx** [comment]
Sorry, I didn't notice that default branch was not master or last release.

**Comment by keradus** [comment]
no problem ;)
