### ISSUE TITLE
operators_spaces brakes array double arrows

### ISSUE THREAD

**Issue by damnedest** [FriendsOfPHP/PHP-CS-Fixer#2151]
Since 1.11.7 operators_spaces fixes arrays double arrow.

Before
```
<?php
array(
    'value'             => null,
    'values'            => null,
    'default_value'     => null,
    'required'          => false,
    'transformations'   => $this->getDefaultTransformations(),
);
```
After
```
<?php
array(
    'value' => null,
    'values' => null,
    'default_value' => null,
    'required' => false,
    'transformations' => $this->getDefaultTransformations(),
);
```

I think that operator fixer should not affect arrays since aligment in arrays is something more complex.

**Comment by keradus** [comment]
ref: may or may not be connected with not-fully prepared report #2135

Please, provide CLI command you are using (with all args), config file and PHP version.

**Comment by GrahamCampbell** [comment]
Not related to that issue, but might be to my other one.

**Comment by GrahamCampbell** [comment]
I'll close up all my garbage bug reports and replace them with real ones soon, I promise. :)

**Comment by damnedest** [comment]
I started fixer only with operators_spaces, so he gives problems.

**Comment by keradus** [comment]
Too many spaces around operators are trimmed thanks to #2092

If you want to have them aligned, use `align_double_arrow` fixer.

```
D:\GIT\fork\PHP-CS-Fixer ((detached from v1.11.7))
λ php php-cs-fixer --version
PHP CS Fixer version 1.11.7 by Fabien Potencier

D:\GIT\fork\PHP-CS-Fixer ((detached from v1.11.7))
λ php php-cs-fixer fix investigate\ --dry-run --diff --fixers=operators_spaces,align_double_arrow
   1) test.php
      ---------- begin diff ----------
      --- Original
+++ New
@@ @@
 <?php
 array(
-    'value'             => null,
-    'values'            => null,
-    'default_value'     => null,
-    'required'          => false,
-    'transformations'   => $this->getDefaultTransformations(),
+    'value'           => null,
+    'values'          => null,
+    'default_value'   => null,
+    'required'        => false,
+    'transformations' => $this->getDefaultTransformations(),
 );


      ---------- end diff ----------

Checked all files in 1.374 seconds, 6.000 MB memory used

```

**Comment by damnedest** [comment]
But I don't want to realign my arrays. operators_spaces is doing some job with arrays witch it shouldn't do.

**Comment by keradus** [comment]
why you want to have extra 2 spaces?

**Comment by damnedest** [comment]
Basically problem is that this fixer brakes more complex aligments like this:
```
<?php
'phone' => array(
    'title'     => 'Phone',
    'type'      => 'text',
),
'url_id' => array(
    'title'     => 'Url ID',
    'type'      => 'text',
    'lower'     => true,
    'trim'      => true,
    'regexp'    => '#^[a-z_0-9-]+$#i',
    'computed'  => true,
),
```

All I want is that this operator won't affect arrays, because for align arrays we have "align_double_arrow". Maybe I'm wrong.

**Comment by keradus** [comment]
It's hard to have fixer for binary operators, and then say fix all operators except `=>`, why not except `||` as well? or `+`, or anything? hardcoded exception is tricky to explain to users and maintain.

For aligning we have separated fixer, as we don't want to align all operators (and aligning for `=>` or `=` has different logic).

Why this is broken btw?

```
keradus@Lap:~/github/PHP-CS-Fixer$ php php-cs-fixer fix --fixers=operators_spaces,align_double_arrow --dry-run --diff test.php 
Loaded config from "/home/keradus/github/PHP-CS-Fixer/.php_cs".
   1) /home/keradus/github/PHP-CS-Fixer/test.php
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       <?php
       
       $arr = array(
           'phone' => array(
      -        'title'     => 'Phone',
      -        'type'      => 'text',
      +        'title' => 'Phone',
      +        'type'  => 'text',
           ),
           'url_id' => array(
      -        'title'     => 'Url ID',
      -        'type'      => 'text',
      -        'lower'     => true,
      -        'trim'      => true,
      -        'regexp'    => '#^[a-z_0-9-]+$#i',
      -        'computed'  => true,
      +        'title'    => 'Url ID',
      +        'type'     => 'text',
      +        'lower'    => true,
      +        'trim'     => true,
      +        'regexp'   => '#^[a-z_0-9-]+$#i',
      +        'computed' => true,
           ),
       );
       
      
      ---------- end diff ----------

Checked all files in 0.092 seconds, 6.000 MB memory used
```

------------------------

Also, if really needed, you could prepare a PR that will allow `operators_spaces` to not fix some operators (so any configured operators, not only `=>`).

**Comment by GrahamCampbell** [comment]
This is only happening due to the bug causing it to be unaligned first...

**Comment by GrahamCampbell** [comment]
Turn off both align fixers and it still gets unaligned.

**Comment by GrahamCampbell** [comment]
> operators_spaces is unaligning any operators

That seems wrong?

**Comment by keradus** [comment]
I see nothing wrong about it.

**Comment by GrahamCampbell** [comment]
It's unaligning double arrow, and that shouldn't be happening. That case should be excluded, or the double arrow unalign fixer should be removed, and this one replaced with configuration to select operators to unalign.

**Comment by keradus** [comment]
> or the double arrow unalign fixer should be removed

:+1:, I was already thinking about this, but only for 2.x branch

--- 

configuration -> :+1:

**Comment by GrahamCampbell** [comment]
👍
