### ISSUE TITLE
[RFC] Inline docblock fixer

### ISSUE THREAD

**Issue by phansys** [FriendsOfPHP/PHP-CS-Fixer#2159]
This RFC is for inline docblocks, since there are different ways to write them:

```
/** @var $someVar \SomeClass */
```

```
/* @var \SomeClass $someVar */
```

**Comment by keradus** [comment]
:+1: for idea

**Comment by phansys** [comment]
Somebody knows another notation for inline docblocks? Moreover, anyone knows how to name or identify each of them?

**Comment by GrahamCampbell** [comment]
The bottom option is **not** actual doc. It's just a comment.

**Comment by keradus** [comment]
wait wait wait, I misread it.

@phansys , you want to fix this:
```diff
-/** @var $someVar \SomeClass */
+/** @var \SomeClass $someVar */
```

or this as well:
```diff
-/* @var $someVar \SomeClass */
+/** @var \SomeClass $someVar */
```

?

**Comment by phansys** [comment]
It depends in the result of the "C" part of this RFC @keradus. I know some IDEs (like NetBeans) that treat the 2nd example as a docblock, regardless it isn't really a docblock as @GrahamCampbell pointed. I'm completely open to your concerns about this.

**Comment by GrahamCampbell** [comment]
It's incorrect to fix a comment to a docblock. A comment must never be interpreted as phpdoc, and nobody does that?

**Comment by phansys** [comment]
This is an example of what I mean, but the use case exposed is just for type hinting AFAIK: https://blogs.oracle.com/netbeansphp/entry/defining_a_variable_type_in. Should we ignore these cases then?

**Comment by GrahamCampbell** [comment]
Looks like those people there have made a mistake, or don't know how php works. :trollface:

I suspect they just missed out a star by mistake.

**Comment by rob006** [comment]
> I know some IDEs (like NetBeans) that treat the 2nd example as a docblock

AFAIK **all** IDEs treats the 2nd example as docblock and it is only safe way for define typehints for local variables - NetBeans (and Eclipse?) ignores `/** @var $someVar \SomeClass */`

**Comment by GrahamCampbell** [comment]
Gah. I'm going to declare my position on this as "meh". I give zero f***s about optimizing anything for an IDE. PHPDoc is for humans IMO.

**Comment by phansys** [comment]
You mean Coding Style is not for humans?

**Comment by GrahamCampbell** [comment]
Transforming doc for IDEs is outside the realm of cs. Moving about spacing in phpdoc is cs, but changing the fundamental format is not.

**Comment by rob006** [comment]
> PHPDoc is for humans IMO.

Phpdoc is for tools. You don't need special syntax for humans, you can just write

```php
// $test is instance of \SomeClass
$test = Magic::get();
```

**Comment by GrahamCampbell** [comment]
Nope. Humans can parse things just like machines. That's how we read our own code.

**Comment by teohhanhui** [comment]
Please see https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#722-var

(Specifically the [example](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#examples-21))

**Comment by SpacePossum** [comment]
To me it makes sense to support fixing towards popular IDE's, or to put it differently; no matter how good the PSR5 standard will be its usefulness will be determined by acceptance and implementation by tool builders.
That aside, fixing PHPDoc's OOTB :+1:, for fixing comments I would like a config flag.

**Comment by phansys** [comment]
In a strictly docblock scope, this fixer could be also used (via config argument) to transform inline docblocks to multiline ones:
**ACTUAL**:
```php
/** @var \SomeType */
private $someProp;
```
**EXPECTED**:
```php
/*
 * @var \SomeType
 */
private $someProp;
```

**Comment by phansys** [comment]
As a side note, I always use the inline variant for variables that can be inferred by my IDE, like DI services by instance, so, it can be (in my very own use case) considered more a type declaration/hint than a real docblock. Personally, I didn't found other useful use for inline docblocks.
Is there some documentation tool that parses them out of the scope of classy elements (inside a method by instance)? I think the "safe" concern introduced by @rob006 maybe points to that possibility ([comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2159#issuecomment-243153390)).

**Comment by rugk** [comment]
Actually currently (speaking of v1.12.1 d33ee60) all `/**` inline PHPDOC comments are even converted to `/*`, which I don't like. Similar things were already done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2175, however in my case the PHPDOC comment is valid.

Here an example:
```diff
-/** @var Something */
+/* @var Something */
$newObject = new Something;
```

**Comment by SpacePossum** [comment]
@rugk 
In your sample, the fixer follows PSR5 strictly and changes PHPDoc's that doesn't match the format.
For now, if you don't agree with the fixer you can disable/blacklist it when fixing.

For ref: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#722-var

>The @var tag MUST contain the name of the element it documents.

i.e. you must use the following occ. to PSR5 and the fixer
```php
/** @var Something $newObject*/
$newObject = new Something;
```

**Comment by rugk** [comment]
Ah, thanks FYI.
