### ISSUE TITLE
[RFC] [Symfony] Class / Interface / Trait naming conventions fixer

### ISSUE THREAD

**Issue by phansys** [FriendsOfPHP/PHP-CS-Fixer#2161]
* Prefix abstract classes with Abstract
* Suffix exception classes with Exception
* Suffix interfaces with Interface
* Suffix traits with Trait

I think this (or these) fixers should be conidered as risky.
Ref: https://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

**Comment by GrahamCampbell** [comment]
👎 for this since we have no way to actually update references from other classes.

**Comment by SpacePossum** [comment]
very risky and it isn't really code _style_ but rather naming conversion. (I'm not against the fixer doing more than style fixing only btw., but this case seems to me out of scope)

**Comment by keradus** [comment]
yep, no way to do it without breaking people projects heavily...

**Comment by phansys** [comment]
I've sometimes faced this kind of updates based on `preg_replace()`, but I agree the tool currently misses the ability to perform updates in other files.
Closing by now.
