### ISSUE TITLE
[RFC] Import types with `use` statements only for non native types

### ISSUE THREAD

**Issue by phansys** [FriendsOfPHP/PHP-CS-Fixer#2166]
This proposed fixer should perform the following transformation:
**ACTUAL:**

``` php
namespace Example;

use SomeCustomType;
use Some\Qcn;
use RuntimeException;

class SomeClass
{
    public function myMethod()
    {
        throw new RuntimeException();
    }
}
```

**EXPECTED:**

``` php
namespace Example;

use SomeCustomType;
use Some\Qcn;

class SomeClass
{
    public function myMethod()
    {
        throw new \RuntimeException();
    }
}
```

**Comment by keradus** [comment]
i remember there were request to do the other way around

**Comment by keradus** [comment]
:-1: for it from me, hard to implement when you want to remove import only for PHP-defined global classes and not user-defined global classes and have it working for all different PHPs, also, it makes execution slower... if one want to have it he could keep it without fixer I would say, if one want to automatically do the importing (Eg only before creating release) the fixer would be nice.

but yeah, let us wait for more comments.

**Comment by GrahamCampbell** [comment]
Looks doable with little pain, but we might have to be careful when it comes to updating phpdoc.

**Comment by GrahamCampbell** [comment]
The phpdoc side of things maybe doesn;t make this worth the effort.

**Comment by localheinz** [comment]
I was just thinking about it, and wanted to open a ticket, then I ended up here.

I like it!

**Comment by gharlan** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4355 is merged, should we close this?
(the fixer does not differientiate between native/non-native elements, only between global/non-global)

**Comment by SpacePossum** [comment]
Yeah, looks good to me. Feel free to comment if I missed a detail in the discussion. Thanks again @gharlan for writing the fixer!
