### ISSUE TITLE
Chop array/function arguments

### ISSUE THREAD

**Issue by matthewnessworthy** [FriendsOfPHP/PHP-CS-Fixer#2168]
Would it be possible to chop array/function arguments if they exceed a specific line length or if any of the arguments takes up more than 1 line?

e.g.:
From:

```
return $this->setParam('enabled', [
     'type' => 'boolean',
 ]);
```

To:

```
return $this->setParam(
    'enabled', 
    [
        'type' => 'boolean',
    ]
);
```

From:

```
Paginator::presenter(function ($paginator) {
    return new BootstrapFourPresenter($paginator);
});
```

To:

```
Paginator::presenter(
    function ($paginator) {
        return new BootstrapFourPresenter($paginator);
    }
);
```

**Comment by keradus** [comment]
currently - not.
but for sure it's possible to implement that feature.

feel free to contribute !

**Comment by matthewnessworthy** [comment]
Thanks

I think it may be explained better here https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#46-method-and-function-calls

> Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line.

**Comment by SpacePossum** [comment]
Thanks for the suggestion.
I think this might be a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/111

(I would like this feature and tried to write it once, but never finished it)

**Comment by matthewnessworthy** [comment]
Fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440
