### ISSUE TITLE
Internal error with comment between use statements

### ISSUE THREAD

**Issue by bcremer** [FriendsOfPHP/PHP-CS-Fixer#2171]
When a `use` statement is disconnected with a comment that ends with an comma, an Internal error occures.

Please see the following testscript to reproduce:

```bash
$ cat > TestFile.php <<EOL
<?php
use Some\ClassName,
// some comment that ends with comma,
SomeOther\FanceClassName;

class Foo
{

}
EOL

php -l TestFile.php
php-cs-fixer fix -vvv TestFile.php
No syntax errors detected in TestFile.php
E
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.031 s] /tmp/TestFile.php

Fixed all files in 0.032 seconds, 4.000 MB memory used

Files that were not fixed due to internal error:
   1) /tmp/TestFile.php
```

I stumbled upon this error while fixing the following file of a real live project: https://github.com/shopware/shopware/blob/v5.2.6/engine/Shopware/Components/Model/EventSubscriber.php#L27

**Comment by keradus** [comment]
```
php --version
php-cs-fixer --version
cat .php_cs
cat .php_cs.dist
```

?

**Comment by bcremer** [comment]
Sure

```
php --version
php-cs-fixer --version
PHP 7.0.10 (cli) (built: Aug 21 2016 07:35:18) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
PHP CS Fixer version 1.12.0 by Fabien Potencier and Dariusz Ruminski (ddac737)
```

The error happens also on with the latest `master` but with a slightly different message:
"`Files that were not fixed due to errors reported during linting after fixing"

**Comment by keradus** [comment]
Great, do you want to propose a bugfix for it ? :)

**Comment by bcremer** [comment]
Sorry, I have limited time and the error scope is rather limited.
I am sure however, that the error is caused by this line: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.0.0-alpha/src/Fixer/Import/SingleImportPerStatementFixer.php#L46

Hope this helps.

**Comment by SpacePossum** [comment]
On 1.12 I think it is the `MultipleUseFixer`, breaking here https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Fixer/PSR2/MultipleUseFixer.php#L71

**Comment by SpacePossum** [comment]
I'm working on a fix ATM
