### ISSUE TITLE
parentheses bug

### ISSUE THREAD

**Issue by fico7489** [FriendsOfPHP/PHP-CS-Fixer#2172]
This code:

```php
$this->seeder->status = 'cart';
list($order, $promo) = ($this->seeder)->createFullOrder('', [], [], []);
```

 gives me this this error :
1) Http/Controllers/Backend/Admin/HomeController.php (align_equals)
when I run this:
vendor/bin/php-cs-fixer --dry-run -v fix

But when I run:
 vendor/bin/php-cs-fixer fix
error is not fixed.....

I fixed problem when I edit code to be like:
```php
$this->seeder->status = 'cart';
list($order, $promo) = $this->seeder->createFullOrder('', [], [], []);
```
without parentheses ...

**Comment by keradus** [comment]
What does it mean "gives me this error" ? provide full CLI command and whole output.

Also, this would be nice as well:
```
php --version
php-cs-fixer --version
cat .php_cs
cat .php_cs.dist
```
?

**Comment by GrahamCampbell** [comment]
I think what he means is that fixer keeps saying it made a change to the file over and over?

**Comment by SpacePossum** [comment]
```php
<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$this->seeder->status = 'cart';
list($order, $promo) = ($this->seeder)->createFullOrder('', array(), array(), array());
```

```
$ php -v
PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )
```

```
$ php-cs-fixer -V
PHP CS Fixer version 1.12.0 by Fabien Potencier and Dariusz Ruminski (ddac737)
```

and 

```
$ php php-cs-fixer -v
PHP CS Fixer version 1.12.1-DEV by Fabien Potencier and Dariusz Ruminski
```

no issues, so we need more info

**Comment by SpacePossum** [comment]
ping @fico7489 please provide more info @ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2172#issuecomment-245323481
