### ISSUE TITLE
@Ignore annotation converted to comment

### ISSUE THREAD

**Issue by ABM-Dan** [FriendsOfPHP/PHP-CS-Fixer#2175]
I am using the following format in several places:

    /** @Ignore */
    $translatedString = $translator->trans($myString);

And the phpdoc_to_comment fixer keeps converting it into

    /* @Ignore */
    $translatedString = $translator->trans($myString);

Is this intended behavior? Because that transformation destroys the translation bundle's understanding of it.

**Comment by SpacePossum** [comment]
This is because the `@Ignore` is prop. not part of the PSR5 proposal and therefor is considered not a valid PHPDoc.
You can switch of the `phpdoc_to_comment` fixer to stop the fixer from doing this.
(check the readme of the version of the fixer you are using to see how to do that)

**Comment by ABM-Dan** [comment]
Wait, so there's a whitelist of potential metadata? I thought the point of metadata was that we could extend it as we need to.

**Comment by ABM-Dan** [comment]
Is there a way for me to specify --level=symfony but disable that one fixer?

**Comment by SpacePossum** [comment]
@ABM-Dan yes you can, try something like this:
```bash
$ ./php-cs-fixer.phar fix /path/to/dir  --level=symfony --fixers=-phpdoc_to_comment
```

for more info search for 'blacklist' in the [readme](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/README.rst)

**Comment by ABM-Dan** [comment]
That's very useful, thank you!
