### ISSUE TITLE
Unexpected double space between constants passed in method call

### ISSUE THREAD

**Issue by chalasr** [FriendsOfPHP/PHP-CS-Fixer#2177]
Hi there,
here is the patch proposed:

```diff
- json_encode($filesInfo, defined('JSON_PRETTY_PRINT') ? JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES : 0);
+ json_encode($filesInfo, defined('JSON_PRETTY_PRINT') ? JSON_PRETTY_PRINT |  JSON_UNESCAPED_SLASHES : 0);
```

php-cs-fixer tries to add an additional space before JSON constants separated by a pipe, giving to spaces rather than one.

Here is the analysis ran by fabbot http://fabbot.io/report/symfony/symfony/19922/04275945efe1f0d035f1744543138804e3826c3e in https://github.com/symfony/symfony/pull/19922.

Not sure about which fixer causes this as I don't know which are used or not.

**Comment by SpacePossum** [comment]
When running the fixer on 1.11, 1.12 and master using the SF rule set on the sample code the fixer does not add the white space. It is unclear which version of the fixer the bot uses and with what configuration (besides that it also uses some other undisclosed logic). So my guess is that is only a fabbot issue.

**Comment by chalasr** [comment]
@SpacePossum thank you for your answer, I share your guess. 
ping @fabpot

**Comment by fabpot** [comment]
Actually, It is not a problem with PHP-CS-Fixer or fabbot for that matter, but a human problem :) IT was not a "simple" whitespace but a unicode character! See symfony/symfony@81e9713 for the fix.

**Comment by chalasr** [comment]
Haha... Sorry for having blamed the bot so quickly!
Thank you for the fix.

**Comment by SpacePossum** [comment]
Thanks for the feedback, nice find! :)
I'll look into the `operators_spaces`-fixer, it should have replaced the white space unicode character with a space and not just added the space after it.

**Comment by keradus** [comment]
> I'll look into the operators_spaces-fixer, it should have replaced the white space unicode character with a space and not just added the space after it.

nope, i would say dedicated one for converting all of them, not only around operators

**Comment by SpacePossum** [comment]
>nope, i would say dedicated one for converting all of them, not only around operators

agreed, my first guess was off, @ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2185
