### ISSUE TITLE
PHP 7.1: A non-numeric value encountered

### ISSUE THREAD

**Issue by chalasr** [FriendsOfPHP/PHP-CS-Fixer#2178]
Here is the `ErrorException` I get when running `php-cs-fixer` with PHP 7.1.0RC1 on a OSX environment:

>   [ErrorException]
  A non-numeric value encountered

Command: `php-cs-fixer fix -v`

Config:

```php
$header = <<<EOF
...
EOF;

Symfony\CS\Fixer\Contrib\HeaderCommentFixer::setHeader($header);

return Symfony\CS\Config\Config::create()
    ->level('symfony')
    ->fixers([
        '-concat_without_spaces',
        '-phpdoc_short_description',
        '-pre_increment',
        'concat_with_spaces',
        'header_comment',
        'ordered_use',
        'phpdoc_order',
        'short_array_syntax',
        '-psr0'
    ])
    ->setUsingCache(true)
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in('src')
    )
;
```

Stack trace:
> () at /home/cs-fixer-php71/.composer/vendor/friendsofphp/php-cs-fixer/Symfony/CS/ConfigurationResolver.php:122
 {closure}() at /home/cs-fixer-php71/.composer/vendor/friendsofphp/php-cs-fixer/Symfony/CS/ConfigurationResolver.php:122
 Symfony\CS\ConfigurationResolver->resolveByLevel() at /home/cs-fixer-php71/.composer/vendor/friendsofphp/php-cs-fixer/Symfony/CS/ConfigurationResolver.php:84
 Symfony\CS\ConfigurationResolver->resolve() at /home/cs-fixer-php71/.composer/vendor/friendsofphp/php-cs-fixer/Symfony/CS/Console/Command/FixCommand.php:362
 Symfony\CS\Console\Command\FixCommand->execute() at /home/cs-fixer-php71/.composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/cs-fixer-php71/.composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at /home/cs-fixer-php71/.composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/cs-fixer-php71/.composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /home/cs-fixer-php71/.composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:44

I'm using [php-osx by liip](http://php-osx.liip.ch/), tested from two different machines.
Any clue?

**Comment by GrahamCampbell** [comment]
Can you show us the stacktrace please?

**Comment by chalasr** [comment]
Of course, sorry, trace added to the description.

**Comment by GrahamCampbell** [comment]
Looks like a bug in symfony rather than this codebase. :)

**Comment by GrahamCampbell** [comment]
Oh, wait. My bad. If I look a little closer... :)

**Comment by GrahamCampbell** [comment]
What version of php-cs-fixer are you using?

**Comment by chalasr** [comment]
1.11.3

**Comment by GrahamCampbell** [comment]
The bug is in your code. The string 'symfony' is not a valid level.

**Comment by GrahamCampbell** [comment]
This has already been fixed in the latest 1.x version so that it throws a nicer exception to tell you that you messed up. Please upgrade to the latest 1.12.x.

**Comment by chalasr** [comment]
Indeed, using `FixerInterface::SYMFONY_LEVEL` fixed it, don't ask me from where do this string level comes from. 
Thank you for your support on my silly mistake

**Comment by keradus** [comment]
I love the discussion ! :D
so the initial message while going out, wanted to check it when I'll be back, and now between opening it and reading it it's already resolved ;)

**Comment by keradus** [comment]
> , don't ask me from where do this string level comes from

it's valid CLI arg value
