### ISSUE TITLE
Cache not used if installed via homebrew (macOS)

### ISSUE THREAD

**Issue by pascal-hofmann** [FriendsOfPHP/PHP-CS-Fixer#2182]
Caching is not used (if explicitly enabled) when php-cs-fixer is installed via homebrew on macOS. I guess the detection if installed via composer or phar fails.

**Comment by keradus** [comment]
Feel free to debug it and contribute.
We do not support homebrew directly.

**Comment by SpacePossum** [comment]
ping @pascal-hofmann do you have any more input for us to work with?

**Comment by pascal-hofmann** [comment]
This is the homebrew formular for php-cs-fixer: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php-cs-fixer.rb

As far as I understand it downloads the .tar.gz and extracts it in $HOMEBREW_CELLAR/php-cs-fixer/$VERSION/. Afterwards a symlink /usr/local/bin/php-cs-fixer is created, which points to $HOMEBREW_CELLAR/php-cs-fixer/$VERSION/php-cs-fixer

So php-cs-fixer is not installed via composer, and also not as a phar. But IMHO still caching should be enabled in this case. But it's disabled. (I guess the detection is there, to prevent caching in a php-cs-fixer development environment.)

**Comment by keradus** [comment]
Do you want to propose a solution?
We don't have anyone working with brew i think

**Comment by SpacePossum** [comment]
Since homebrew-php indeed installs the tool from source in a tar caching is not available. 
Wonder why they install like this, as it also make the `selfupdate` command not available.
@keradus what is the reason caching is only on for phar builds?

**Comment by keradus** [comment]
Closing as obsolete, not enough details and fact that we do not support homebrew.
