### ISSUE TITLE
PHP code not formatting

### ISSUE THREAD

**Issue by xucaen** [FriendsOfPHP/PHP-CS-Fixer#2183]
I installed the PHP Formatter and I installed the php-cs-fixer.phar. I set both the phpformatter.pharPath and the phpformatter.phpPath (xampp). I even set a keyboard shortcut for alt-shift-f. When I am in my PHP file and I press alt-shift-f  nothing happens. I don't even get an error or warning. All I want is for my PHP code to get auto indented so it looks nice, I'm not sure why this particular plugin has to be so complicated. Javascript and HTML are formatted nicely. Can't we just format PHP using the same rules and Javascript formatting?

**Comment by keradus** [comment]
we have no idea what is `PHP Formatter` ...

**Comment by xucaen** [comment]
That's OK because I decided the editor was not worth using. Too many bugs to be used in an Enterprise environment.

**Comment by keradus** [comment]
Sorry, but we have no idea what is the `PHP Formatter` nor editor you are using. If you have problem with IDE contact their support, if some plugin of it contact author of that plugin.

We could help you to use `PHP CS Fixer`, which is standalone tool. But for other apps you need to contact them.
