### ISSUE TITLE
HHVM 3.9 - 1.12.1 phar release broken

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2184]
```bash
$ php php-cs-fixer.phar --dry-run -v --config-file=.php_cs.dist fix .

Fatal error: Class undefined: Symfony\CS\Fixer\Contrib in phar://php-cs-fixer.phar/Symfony/CS/Fixer.php on line 78

The command "php php-cs-fixer.phar --dry-run -v --config-file=.php_cs.dist fix ." exited with 255.
```

As discussed low prio, but here is a place holder issue.

**Comment by keradus** [comment]
does 1.11.x / 1.12.0 / 2.x works ?
does 1.12.1 on hhvm 3.9 installed via composer works?

**Comment by GrahamCampbell** [comment]
What about HHVM 1.12 or 1.15?

**Comment by SpacePossum** [comment]
lets see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2186

>What about HHVM 1.12 or 1.15?

do we support those versions? I would drop support for everything below 3.x

**Comment by SpacePossum** [comment]
1.11.0 seems OK

**Comment by GrahamCampbell** [comment]
Meant 3.12 and 3.15 rather. :)

**Comment by SpacePossum** [comment]
closing because I fail to care any more ;)
