### ISSUE TITLE
Tokenizer - white space assumed part of literal

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2185]
https://3v4l.org/2bDe7

``` php
<?php \$a = PHP_VERSION;
```

```
  [4]=>
  array(3) {
    [0]=>
    int(319)
    [1]=>
    string(13) " PHP_VERSION"
    [2]=>
    int(1)
  }
```

Because the white space char. before the constant is not a space but a 'special' white space char it is added to the constant. Spotted in the wild @ https://github.com/symfony/symfony/commit/81e9713

Not sure how to proceed here, should we:
-  'dumb' replace the characters with a true space
- fix the tokenizer
- do nothing

Any opinions?

**Comment by ogizanagi** [comment]
So the issue simply was that the used space was an non-breaking space instead of a normal space ?

I think replacing the non-breaking space by a normal space is a good option. I don't think fixing the tokenizer is, because using a non-breaking space here is not expected IMHO.

**Comment by keradus** [comment]
You cannot easily replace it as tokenizer eats that character into another token @ogizanagi 
Chaning the way how tokenizer works to protect against this case would be very, very, very slow and would bring us not that much value

**Comment by SpacePossum** [comment]
maybe we could do something like the `LinefeedFixer` does? i.e. blindly search-replace some characters on file level?

**Comment by keradus** [comment]
nope, so slow...

**Comment by keradus** [comment]
LinefeedFixer deserves to be rewritten. now it's risky

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
