### ISSUE TITLE
Enforce single-style logical operators

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfPHP/PHP-CS-Fixer#2201]
We should be able to specify preference for `&&`, `||` instead of `and`, `or`, maybe not even allow named variants [because they act differently](http://stackoverflow.com/a/34848592/672885).

    if ($a or $b) {
        // ...
    }

becomes

    if ($a || $b) {
        // ...
    }

**Comment by gharlan** [comment]
-> #1212

**Comment by dkarlovi** [comment]
Yeah, I've even searched for this issue before submitting it. :(

Duplicate of #1212, closing.
