### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by hackereg35** [FriendsOfPHP/PHP-CS-Fixer#2210]
i have downloaded php-cs-fixer.phar and i have appserv installed and php5 is in my PATH v but when i execute 
`php php-cs-fixer.phar`
i get 
`Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in C:\AppServ\ph
p5\php-cs-fixer.phar on line 23`

**Comment by SpacePossum** [comment]
Hi @hackereg35,

Thank you for the report. I order to bug track this, could you provide:
- the PHP version you use (or HHVM if this is the case)
- which version of the fixer are you running/have you downloaded
- which version of Windows are you running the fixer on

Thanks in advance :)

**Comment by SpacePossum** [comment]
ping @hackereg35

**Comment by keradus** [comment]
Closing as not verified for 2 months.
could be reopened after become verified.
