### ISSUE TITLE
Don't work for Windows (require_once problem ?)

### ISSUE THREAD

**Issue by AntoDury** [FriendsOfPHP/PHP-CS-Fixer#2211]
Hello !

First of all, sorry for my english but I'm french..

I have a problem with Beautify for Windows, there is an error while executing in command line.
Here is the logs : https://gist.github.com/anonymous/8ff73f92e825ec1e46968972785375e1

```
Warning: Uncaught ErrorException: require_once(C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer:38
Stack trace:
#0 C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer(38): {closure}(2, 'require_once(C:...', 'C:\\Users\\Antoin...', 38, Array)
#1 C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer(38): require_once()
#2 {main}
  thrown in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer on line 38

Fatal error: main(): Failed opening required 'C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer on line 38

2016-10-05T13:39:26.249Z - verbose: [beautifiers\beautifier.coffee] spawn result 255 
Warning: Uncaught ErrorException: require_once(C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer:38
Stack trace:
#0 C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer(38): {closure}(2, 'require_once(C:...', 'C:\\Users\\Antoin...', 38, Array)
#1 C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer(38): require_once()
#2 {main}
  thrown in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer on line 38

Fatal error: main(): Failed opening required 'C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Users\Antoine\Documents\PHP-CS-Fixer-1.12\php-cs-fixer on line 38
```

Thanks for your help guys !

**Comment by SpacePossum** [comment]
Hi and thank you for report.

Could you provide some additional details? The PHP version you are using;
```
$ php -v
```

and the version of Windows you use maybe?

Since the fixer cannot find the `autoload.php` I think one the two problems is going on:
- you are using the `.phar` distribution of the fixer, but the fixer thinks wrongfully it is installed by composer. Or;
- you are running the fixer from code, but didn't install its dependencies using composer

I'm not familiar with Atom Beautify, do you know if they ship the fixer as `phar`?

**Comment by AntoDury** [comment]
Hi thanks for your answer !

Here is my version of PHP : 

`PHP 7.0.4 (cli) (built: Mar  2 2016 14:42:25) ( ZTS )`

This is Windows 10 and I installed php-cs-fixer without composer, maybe this is the problem ?

And sorry but I don't understand your last sentence :/

**Comment by AntoDury** [comment]
I installed composer for Windows and it works, I think that Composer was only for Linux, thanks !

**Comment by SpacePossum** [comment]
Ah good news! : )
Composer is cross platform, so enjoy two new great PHP tools ^_^

**Comment by keradus** [comment]
> I installed composer for Windows and it works, I think that Composer was only for Linux, thanks !

How did you install it ?

**Comment by SpacePossum** [comment]
ping @AntoDury do you recall how you solved this?

**Comment by keradus** [comment]
Closing as incomplete report :(

**Comment by goyote** [comment]
What was the fix for this? Experiencing same
