### ISSUE TITLE
"function_declaration" fixer removes spaces in use parameter list

### ISSUE THREAD

**Issue by Riimu** [FriendsOfPHP/PHP-CS-Fixer#2216]
This is kind of minor issue, but adding fixers one by one to one project I was working on, I noticed that the fixer `function_decleration`  has weird handling of spaces in `use` parameter list. To illustrate, if I have the following file:

```php
<?php

$foo = function ($foo) use($bar, $baz) {
    die;
};
```

And run the following command:

```
php-cs-fixer fix --level=none --fixers="function_declaration" --dry-run fail.php --diff
```

It will change the closure declaration line to: `$foo = function ($foo) use ($bar,$baz) {`. In other words, in addition to adding the space after the `use` keyword, it also removes the space before the `$baz` parameter.

However, If the space character after `use` is not missing, the space character in the parameter list will not be removed. Additionally, including the fixer `method_argument_space` will also produce the expected and correct result.

I'm not sure what the intended behaviour is, but at the moment, the functionality of the `function_declaration` fixer alone is inconsistent and probably should not be affecting the whitespace in the parameter list.

**Comment by keradus** [comment]
php --version
php-cs-fixer --version
?

**Comment by Riimu** [comment]
```
php --version
PHP 7.0.11 (cli) (built: Oct  2 2016 00:32:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
````

```
php-cs-fixer --version
PHP CS Fixer version 1.12.2 by Fabien Potencier and Dariusz Ruminski
```
