### ISSUE TITLE
ClassAttributesSeparationFixer - PHPDoc options

### ISSUE THREAD

**Issue by localheinz** [FriendsOfPHP/PHP-CS-Fixer#2219]
Wondering, is there something similar to the `MethodSeparationFixer` (or has it been proposed), that separates fields _if_ they have a docblock?
### Before

``` php
<?php

namespace Foo;

class Example
{
    /**
     * @var string
     */
    private $foo;
    /**
     * @var int
     */
    private $bar;
}
```
### After

``` php
<?php

namespace Foo;

class Example
{
    /**
     * @var string
     */
    private $foo;

    /**
     * @var int
     */
    private $bar;
}
```

**Comment by SpacePossum** [comment]
>Wondering, is there something similar to the MethodSeparationFixer (or has it been proposed)

AFAIK, no and no, but I would happily like to propose such a fixer together with you :)  
(kindly note: that doesn't mean I have the time to dev the fixer ATM :| )

**Comment by localheinz** [comment]
@SpacePossum 

I'm not sure if I'll be able to build one, but I'm happy to try to do so!

**Comment by keradus** [comment]
hm... i thought we have one. please check master branch

**Comment by SpacePossum** [comment]
>at least for methods

there is, for attributes/properties/fields/const there isn't I think

**Comment by TomasVotruba** [comment]
This is already resolved by #3098, isn't it?

**Comment by SpacePossum** [comment]
it is indeed, at least in part :)

> that separates fields _if_ they have a docblock?

this option is missing. Having that option was requested in 3098 as well (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3098#discussion_r145252212) but I left it out (because of keeping the PR small and not having a lot of time adding the option(s)).

**Comment by TomasVotruba** [comment]
@SpacePossum I miss that in examples.

@localheinz Do you still need this feature? IMO it's very rare to see code like this.

**Comment by localheinz** [comment]
I don't know why or what happened, but the test cases I added passed, so I'm closing this issue.

Thank you!
