### ISSUE TITLE
Conflict between fixers

### ISSUE THREAD

**Issue by xocasdashdash** [FriendsOfPHP/PHP-CS-Fixer#2222]
Hi all!

I'm having some issues running the following command on a linux server and my mac dev machine
bin/php-cs-fixer --level=symfony --verbose fix src/ 

The problem is that on my mac machine it works and returns 0, but when I launch this from the server (linux) I get the following error
 blablabla.php (no_empty_lines_after_phpdocs)

So if right after I run the script with this parameters to avoid using the problematic fixer I get the following:

 bin/php-cs-fixer --level=symfony --verbose fix src/ --fixers=-no_empty_lines_after_phpdocs
blablabla.php (single_blank_line_before_namespace) 

It seems that there's some kind of inconsistency between the linux and mac execution order of the fixers.  Has anybody run into this problem? I need to discuss with my team before being able to share more info about the files.

**Comment by keradus** [comment]
We run both of the rules on single `Symfony` level without conflicts.
Maybe you run into some kind of edge case, minimal file example would be useful.

also:
```
$ php --version
$ php-cs-fixer --version
```

**Comment by xocasdashdash** [comment]
Output of commands:
`php-cs-fixer --version`
PHP CS Fixer version 1.12.1 by Fabien Potencier and Dariusz Ruminski
`php --version`
PHP 5.6.26-2+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

I'm going to try to make the file available on Monday

**Comment by keradus** [comment]
it doesn't need to be whole file. you could make short sample file that will show the behaviour probably from first few lines, no need to expose proprietary code
