### ISSUE TITLE
LineEndingInContentFixer

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2224]
HI!
as original fixer stop changing the content (very good!) after merge of #2209, we need a second, risky fixer that will fix the line ending in content

**Comment by keradus** [comment]
@gharlan , it does not look like a big one to make, and you already claimed that you would use it.
Could you send a proposal please ?

**Comment by SpacePossum** [comment]
This would be a copy-paste of the `linefeed` fixer as on 1.11 with a new name?
Or do you want a configuration option on the current (patched) version of the fixer?

**Comment by keradus** [comment]
It should work on tokens level and touch non-whitespaces only (to not duplicate fixer).
I wouldn't made it one fixer, as this fixer will be risky, while existing one is not.

**Comment by keradus** [comment]
Closing due to #3454 PR ;)
