### ISSUE TITLE
Clarify exit status

### ISSUE THREAD

**Issue by daniel-gomes-sociomantic** [FriendsOfPHP/PHP-CS-Fixer#2231]
Using the curent PHP CS Fixer [1.12](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/e5baef81f5f04d69368afb900d02ae581fc71eb7) version, a command like:

```
php-cs-fixer --level=psr2 fix somefile.php
```

Exits with status code 1 if `somefile.php` did need fixing and status code 0 if it did not (eg. if you run the command twice in a row). I understand from https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1651#issuecomment-177618742 that this cannot be fixed in 1.x because of BC, and I checked that it seems fixed in `v2.0.0-alpha`, but the problem is that the 1.12 version's [README](https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes) reads:

```
Exit codes

0 OK
1 No changes made
```

Which I assume was the _intended_ situation, not what _currently_ happens. 

My question is, can I rely on 1 being **always** the "OK" exit (ie. what should have been 0) and therefore 0 being the "No changes made" exit (ie. what should have been 1), or are there other situations were exit code 1 might **not** mean an "OK" exit?

**Comment by keradus** [comment]
Indeed, doc is not correct here.

0 - OK
1 - Sth was fixed (or need a fix if you use `--dry-run`).

I think that during your own running of the tool - both are "tool works properly" statuses.
The 1 exit status is nice for CIs, when you run the tool on CI and wanna indicate that the job failed.

I agree it's not the best and we changed it for 2.x line as you mentioned.

Could you make a PR to fix the docs please ?

**Comment by daniel-gomes-sociomantic** [comment]
So if I got it correctly, the docs should read:

```
Exit codes

0 OK or no changes made
1 OK or --dry-run was used and files need changes
16 Configuration error of the application
32 Configuration error of a Fixer
```

That it?

**Comment by SpacePossum** [comment]
>1 OK or --dry-run was used and files need changes

1
* when changes have been made 
* when `--dry-run` was used and the changes would have been made if  `--dry-run` was not used

I'm not sure what the exit code is on 1.x when the application crashes (i.e. internal error by for example unhandled exception)

**Comment by tomasfejfar** [comment]
This is not what's happening. 
```
tomasfejfar@X220 MINGW64 /w/www/projects/(temp2)
$ vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --using-cache=no --path-mode=intersection $(git diff --name-only --cached --diff-filter=ACMRTUXB | grep .php); echo $?
Loaded config from ".php_cs.dist".
.F.....
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) src\Data\Aggregator\Strategy\DailyAverage.php (braces)

Fixed all files in 2.803 seconds, 6.000 MB memory used
0

tomasfejfar@X220 MINGW64 /w/www/projects/(temp2)
$ vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --using-cache=no --path-mode=intersection $(git diff --name-only --cached --diff-filter=ACMRTUXB | grep .php); echo $?
Loaded config from ".php_cs.dist".
.......
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Fixed all files in 2.973 seconds, 6.000 MB memory used
0
```
Both scenarios return zero - fixed file as well as noop. That's not the case with dry-run though. 

```
tomasfejfar@X220 MINGW64 /w/www/projects/(temp2)
$ vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --using-cache=no --path-mode=intersection --dry-run $(git diff --name-only --cached --diff-filter=ACMRTUXB | grep .php); echo $?
Loaded config from ".php_cs.dist".
.F.....
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) src\Data\Aggregator\Strategy\DailyAverage.php (braces)

Checked all files in 2.841 seconds, 6.000 MB memory used
8
```

```
vendor/bin/php-cs-fixer -V
PHP CS Fixer version 2.0-DEV by Fabien Potencier and Dariusz Ruminski

$ composer info friendsofphp/php-cs-fixer
name     : friendsofphp/php-cs-fixer
descrip. : A tool to automatically fix PHP code style
keywords :
versions : * dev-master, 2.0.x-dev
type     : application
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/FriendsOfPHP/PHP-CS-Fixer.git 13a21d85789f4e6534610722842019b864980bec
dist     : [zip] https://api.github.com/repos/FriendsOfPHP/PHP-CS-Fixer/zipball/13a21d85789f4e6534610722842019b864980bec 13a21d85789f4e6534610722842019b864980bec
names    : friendsofphp/php-cs-fixer
```
```
<?php
// .php_cs.dist
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => true,
    ))
    ->finder($finder)
;
```

**Comment by keradus** [comment]
read again initial comment... author said that he know that behaviour was modified on 2.x line and he is talking about 1.12...

**Comment by benyanke** [comment]
This still seems to be occurring. Is there any resolution to this? I'm running the latest: 2.13.0

**Comment by keradus** [comment]
I have no clue what you are asking about. Please raise new ticket and describe your case.
