### ISSUE TITLE
Intentation error (Atom beautifyer)

### ISSUE THREAD

**Issue by Hambern** [FriendsOfPHP/PHP-CS-Fixer#2233]
Hi I don't know if this is a bug/issue or not.

But I constantly get this indentation error for PHP. I've installed php-fixer-cs though composer and run it with Atom Beautifyer plugin on my Mac OSX-machine. What could be the error? Is it me or something technical?

I start with

``` php
<?php

namespace hambern\puzzle;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
public function registerComponents()
{
return [
'Hambern\Puzzle\Components\Map' => 'Map',
'Hambern\Puzzle\Components\Timeline' => 'Timeline',
];
}

public function registerSettings()
{
}
}
```

I expect

``` php
<?php

namespace hambern\puzzle;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
  public function registerComponents()
  {
    return [
      'Hambern\Puzzle\Components\Map' => 'Map',
      'Hambern\Puzzle\Components\Timeline' => 'Timeline',
    ];
  }

  public function registerSettings()
  {
  }
}
```

But are getting

``` php
<?php

namespace hambern\puzzle;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
        return [
'Hambern\Puzzle\Components\Map' => 'Map',
'Hambern\Puzzle\Components\Timeline' => 'Timeline',
];
    }

    public function registerSettings()
    {
    }
}
```

I've also set the indent_size to 2, but keep getting 4. Please help me. I get the same when i run the php-cs-fixer directly

**Comment by SpacePossum** [comment]
`indent_size` is not an option ATM for PHP-CS-Fixer, this is WIP and scheduled for release with the new 2.x versions.
The array items not getting indented correctly is prop. a missing feature of the fixer, but I've to check.

**Comment by keradus** [comment]
what is more, `indent_size` is not an option of PHP CS Fixer, it looks like option of that atom sth.

indeed, we don't have feature to re-indent array, maybe you want to contribute @Hambern ?

**Comment by Hambern** [comment]
Ahh... Seems like it's me then ;) I might contribute... Will look into this. Thanks for great answers

**Comment by keradus** [comment]
great to hear :)

**Comment by keradus** [comment]
Closing as ATOM bug is not related to us, and feature request is somehow duplicating #1217.
Still, you are more than welcome to contribute @Hambern
