### ISSUE TITLE
Symfony\CS\FinderInterface declares only setDir() with no documentation.

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#2242]
from, https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2214#issuecomment-252382717
[Symfony\CS\FinderInterface](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v1.12.2/Symfony/CS/FinderInterface.php#L18) declares only `setDir()` with no documentation. 

why is that so?

actual object implementing only that method seems quite useless.

i wish to type-hint the `$finder` object in my code, what should i put there?

**Comment by SpacePossum** [comment]
I think the FinderInterface was introduced before the project became OSS so its hard to state why this was done. Beside that it doesn't change the fact that it is done and cannot be changed on the 1.x line for BC reasons. The lack of documentation is not a choice I think, just that no one did write and PR'ed it.

For the 2.0 release the whole configuration of the fixer has been revised and this interface was removed in favor of using a Finder object (or instance extending it). So typing hinting can be done properly on that line.

**Comment by keradus** [comment]
actually on 2.x line you could set up any iterable, which is already documented.
closing
