### ISSUE TITLE
Camelcase for method name

### ISSUE THREAD

**Issue by harikt** [FriendsOfPHP/PHP-CS-Fixer#2259]
Hi,

Accorindg to PSR-2 Method names MUST be declared in camelCase() : http://www.php-fig.org/psr/psr-1/#4-3-methods

I was running to fix the code against a snake_case method. But seems it is unable to fix to camelCase. Or was that purposefully left ?

Thank you.

**Comment by keradus** [comment]
Changing the method name from `a_b` to `aB` will break the code.

**Comment by harikt** [comment]
Breaking code is not the problem :-) when you are trying to fix it .

**Comment by keradus** [comment]
it's a big problem

**Comment by tony2013** [comment]
It would be great if we had as output the numbers of lines with bad code

**Comment by GrahamCampbell** [comment]
Due to the dynamic nature of PHP (and the way it represents things as strings), it's impossible to actually automatically fix such things.
