### ISSUE TITLE
SelfUpdateCommand - Do not auto update to next major

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2260]
RFC

I think it would be nice to not auto update 1.x to 2.x (when 2.x is released) when running the `SelfUpdateCommand`.
Showing a message that a new major is released with a link to the `UPGRADE.md` would be nice. Additional we could add a `-f` - flag to allow forcing to updating to next major release.

The reason why I think it would be good is that when people have a (custom) config file it needs updating or the Fixer won't run. I would like to prevent getting a lot of people reporting:

```
$ php php-cs-fixer fix -vvv
PHP Fatal error:  Uncaught Error: Class 'Symfony\CS\Fixer\Contrib\HeaderCommentFixer' not found in /home/possum/work/PHP-CS-Fixer/.php_cs:13
```

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Maybe we should still show a notice if a new stable version is available, but the major version of the new version is greater?

**Comment by SpacePossum** [comment]
Sure, check it out https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2264/files#diff-b48dda0c2ec7e050caee3b14d174b17dR85 :)

**Comment by GrahamCampbell** [comment]
👍

**Comment by glensc** [comment]
This issue comes up when searching `Symfony\CS\Fixer\Contrib\HeaderCommentFixer`. would be nice to add here link for `> 1` syntax for same code.

**Comment by SpacePossum** [comment]
Little general help for all who come here because of the error message:

For upgrading from 1.x to 2.x please checkout the upgrade guide;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.2/UPGRADE.md

Feel free to ask more on this topic or ask for help at the community;
https://gitter.im/FriendsOfPHP/PHP-CS-Fixer
