### ISSUE TITLE
Namespace changed to lowercase

### ISSUE THREAD

**Issue by teddywest32** [FriendsOfPHP/PHP-CS-Fixer#2269]
I am trying to use the php-cs-fixer for my `laravel project` and found it saves alot of times for `PSR-2 standard`  to maintain which was a lot of pain if done manually or something other. I have found an issue with my `namespace turning to lowercase `. 

`.php_cs` file
<code>
    <?php

    $finder = Symfony\CS\Finder::create()
        ->exclude('public')
        ->exclude('vendor')
        ->exclude('storage')
        ->exclude('bootstrap')
        ->exclude('tests')
        ->in(__DIR__);

    return Symfony\CS\Config\Config::create()
        ->setUsingCache(true)
        ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
        ->finder($finder);
</code>

My `Controller` file

<code>
    <?php

    namespace App\Http\Controllers;

    use Illuminate\Foundation\Bus\DispatchesJobs;
    use Illuminate\Routing\Controller as BaseController;
    use Illuminate\Foundation\Validation\ValidatesRequests;
    use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

    class Controller extends BaseController
    {
        use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    }
</code>

which on performing a fix changed to

<code>
    <?php

    namespace app\Http\Controllers;

    use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
    use Illuminate\Foundation\Bus\DispatchesJobs;
    use Illuminate\Foundation\Validation\ValidatesRequests;
    use Illuminate\Routing\Controller as BaseController;

    class Controller extends BaseController
    {
        use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    }

</code>

I am unsure is there some `fixers` to fix this namespace changes??
Thanks for the support

**Comment by GrahamCampbell** [comment]
Not a bug. Turn off ps0 fixer.

**Comment by teddywest32** [comment]
Thanks @GrahamCampbell 

It worked. 👍
