### ISSUE TITLE
testestset

### ISSUE THREAD

**Issue by masellfoodpanda** [FriendsOfPHP/PHP-CS-Fixer#2272]
testsetsetst

**Comment by keradus** [comment]
wow, when I added the label, github show it was @masellfoodpanda ... replicable :|

**Comment by keradus** [comment]
@masellfoodpanda , fixed now ;)

**Comment by SpacePossum** [comment]
what is fixed?

**Comment by keradus** [comment]
gh bug that when I have added `invalid` label to this issue it was displayed with MAsell as author of that action

**Comment by SpacePossum** [comment]
ha thats weird :)

**Comment by masellfoodpanda** [comment]
@keradus So, you hacked github again? :+1:
