### ISSUE TITLE
[2.x] ClassDefinitionFixer - issues with anonymous classes

### ISSUE THREAD

**Issue by gharlan** [FriendsOfPHP/PHP-CS-Fixer#2302]
Input:
```php
new class($this->prop) {
};
```

Expected: no change

Result:
```php
new class($this -> prop)
{
};
```

* spaces around `->` are wrong
* opening brace is wrong -> this is fixed by `BracesFixer`, but IMO the `ClassDefinitionFixer` should no put the opening brace to a newline for anonymous classes

**Comment by keradus** [comment]
`php-cs-fixer --version` ?

**Comment by gharlan** [comment]
`PHP CS Fixer version 2.0.0-DEV by Fabien Potencier and Dariusz Ruminski`

current master

**Comment by keradus** [comment]
thanks !
could you work on a fix please ? :)

**Comment by SpacePossum** [comment]
is this also wrong on 1.x line?

**Comment by SpacePossum** [comment]
arrow fixing is wrong on 1.13 as well, braces seem ok

**Comment by keradus** [comment]
#2303 has been merged.
is there sth left to be done here ?

**Comment by gharlan** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2303/files#r88790767
