### ISSUE TITLE
FunctionDeclarationFixer - Doesn't fix static anonymous function

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2316]
```php
<?php

$a = static    function () {
    return 1;
};
```

`FunctionDeclarationFixer` doesn't fix above, test 1.13 and master

**Comment by keradus** [comment]
yep, we do not support static lambas at all

**Comment by SpacePossum** [comment]
I'm closing this as I use a diff. system for keeping tracking on stuff I want to do one day when I've time. Please don't reopen, I like to have a small list of issues on GH to manage. Thanks!
