### ISSUE TITLE
could not find 'Php-cs-fixer'

### ISSUE THREAD

**Issue by shareil23** [FriendsOfPHP/PHP-CS-Fixer#2326]
how to fix this problem, i already installed php-cs-fixer from composer but atom beauty still erorr when use in php
![screenshot_7](https://cloud.githubusercontent.com/assets/16985447/20617328/c071638a-b32b-11e6-9f16-b1ac7e1075d3.png)

**Comment by keradus** [comment]
This is an error for some Atom plugin, not us. You shall ask that plugin community.
