### ISSUE TITLE
PhpUnitFqcnAnnotation - should be marked risky

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2340]
for ref.: https://github.com/GeckoPackages/GeckoPHPUnit/pull/29/commits/1af9075ae004e7d6ea2f1d5491f50cc95d18cbd8#diff-37a77e29482f3ba762623614e7daf6bfR64

**Comment by keradus** [comment]
what's wrong with that change ?

**Comment by SpacePossum** [comment]
it breaks the tests that used to pass

**Comment by SpacePossum** [comment]
```php
<?php

class ExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException PHPUnit_Framework_Exception
     */
    public function testInvalidArgument1()
    {
        throw new \PHPUnit_Framework_Exception();
    }

    /**
     * @expectedException \PHPUnit_Framework_Exception
     */
    public function testInvalidArgument2()
    {
        throw new \PHPUnit_Framework_Exception();
    }
}
```

First passes, seconds fails

```bash
$ phpunit --version
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

$ php -v
PHP 7.0.13-1+deb.sury.org~xenial+1 (cli) ( NTS )
```

**Comment by keradus** [comment]
veeeery edge case...
https://github.com/sebastianbergmann/phpunit/pull/2384

**Comment by SpacePossum** [comment]
haha really? just my luck when working with PHPUnit's own exceptions

nice PR, thanks! :)

**Comment by SpacePossum** [comment]
Closing as this is indeed a very edge case. Thanks @keradus for figuring out why this fails and PR'ing on the PHPUnit repo!
