### ISSUE TITLE
ClassKeywordRemoveFixer incorrectly leaves leading Backslash

### ISSUE THREAD

**Issue by rvock** [FriendsOfPHP/PHP-CS-Fixer#2341]
The ClassKeywordRemoveFixer leaves the backslash prefix infront of classes, if it was in the source:
[ClassKeywordRemoveFixerTest.php#L85](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/ac04a510bed5407e91664f8a37b9d58072d96768/Symfony/CS/Tests/Fixer/Contrib/ClassKeywordRemoveFixerTest.php#L85)

This is incorrect. `::class` always returns the fully qualified name without a leading backslash:
```bash
$ php -r 'echo \DateTime::class;'
DateTime
```

This means the testcase is incorrect and the generated strings will be incorrect.

**Comment by GrahamCampbell** [comment]
> This is incorrect. ::class always returns the fully qualified name without a leading backslash:

No it's not. The fixer is correct.

**Comment by GrahamCampbell** [comment]
Compare `php -r 'namespace Foo; echo DateTime::class;` with `php -r 'namespace Foo; echo \DateTime::class;`

**Comment by SpacePossum** [comment]
>Compare php -r 'namespace Foo; echo DateTime::class; with php -r 'namespace Foo; echo \DateTime::class;

done https://3v4l.org/gXD63

i.e. `echo \DateTime::class;` is not `echo '\DateTime';`

**Comment by GrahamCampbell** [comment]
Oh, I see what you mean now. Sorry! I was thinking the fixer was going the other direction, so we'd have to have the slash for safety.

**Comment by keradus** [comment]
Thanks for a report @rvock !
Do you want to work on a fix for that ?

**Comment by rvock** [comment]
I think, it's enough to change one line:
[ClassKeywordRemoveFixer.php#L151](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/4cdef406cccdc0e3db79932a883f1c0531610861/Symfony/CS/Fixer/Contrib/ClassKeywordRemoveFixer.php#L151), but I am not sure, if this works with other imports:
```php
$classString = ltrim($tokens->generatePartialCode($classBeginIndex, $classEndIndex), '\\');
```

I might find some time during the weekend to test.
