### ISSUE TITLE
Fixer for newline after each import "type"

### ISSUE THREAD

**Issue by kbond** [FriendsOfPHP/PHP-CS-Fixer#2348]
Any interest in having newlines between each import "type"?

Before:

```php
use Vendor\Package\ClassA;
use Vendor\Package\ClassB;
use function Vendor\Package\functionA;
use function Vendor\Package\functionB;
use const Vendor\Package\ConstantA;
use const Vendor\Package\ConstantB;
```

After:

```php
use Vendor\Package\ClassA;
use Vendor\Package\ClassB;

use function Vendor\Package\functionA;
use function Vendor\Package\functionB;

use const Vendor\Package\ConstantA;
use const Vendor\Package\ConstantB;
```

**Comment by SpacePossum** [comment]
Hi!
I'm not against it, as it is a clear rule :) However I would not use it.
Do you know any community that likes this kind of CS? Before introducing new features it is nice to know if there is a broader interest as this typically also means a broader support for developing and maintaining the feature.

**Comment by SpacePossum** [comment]
I'm closing this because the feedback question has been open since Dec 7, 2016. If there is enough interest in this after all; than please comment here and we can discuss the FR further and re-open if applicable.
