### ISSUE TITLE
simplified_null_return works wrong with nullable return type

### ISSUE THREAD

**Issue by prolic** [FriendsOfPHP/PHP-CS-Fixer#2349]
It removes "return null;" in favour of "return;" which is wrong for nullable return types

**Comment by keradus** [comment]
Hi !

That's exactly why it was marked as risky fixer after php7 release.

It was already disabled by default. On 2.0 you also need to willingly
enable risky fixers, that will change your code behaviour.

Did the fixer run without your willingness ?

-- 

Dariusz Rumiński

**Comment by prolic** [comment]
No it was enabled. But I think it should be relatively easy to fix that
behaviour.

Am 01.12.2016 23:01 schrieb "Dariusz Rumiński" <notifications@github.com>:
