### ISSUE TITLE
Not possible to only align equals and not change other binary operators

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2355]
This is due to the merge into BinaryOperatorSpacesFixer, but no config to turn the other parts of the fixer off.

**Comment by SpacePossum** [comment]
I did that, and my reason was if someone cares about the CS of/around `BinaryOperatorSpaces` we allow for variation/configuration where there are open spots in the PSR's, but thats it. Cutting back repeating and conflicting logic is important for the tool.
If someone really wants messy spaces around binary operators but still want to align equals or arrows the user is out of luck atm. Feel free to open an PR to make more parts configurable, especially welcome before I start merging the `not_operator_with_space` and the `not_operator_with_successor_space` into `BinaryOperatorSpacesFixer` using config.

**Comment by GrahamCampbell** [comment]
I will likely prep a PR then. I think it's important for people to be able to just run the alignment part on it's own and nothing else if they want.

**Comment by keradus** [comment]
Closes due to merge of #2573
