### ISSUE TITLE
[Feature request] Reformatting variable names

### ISSUE THREAD

**Issue by skyzyx** [FriendsOfPHP/PHP-CS-Fixer#2362]
I would like to see a feature which can identify (and/or fix) variable names written in one format (e.g., snake_case) to another format (camelCase).

This would be **risky**. This is a regex that I was able to use locally to _identify_ snake_case variables in my project.

```
\$(this->)?([0-9a-z]+(_[0-9a-z]*)+)
```

**Comment by keradus** [comment]
it will not be risky. it will be insanely risky

looking forward for more opinions

**Comment by skyzyx** [comment]
Fixing, yes. Identifying, no.

**Comment by keradus** [comment]
This project is PHP CS **Fixer**.
We do not identify issues. We **fix** them!

**Comment by skyzyx** [comment]
> We do not identify issues. We fix them!

What I think I'm hearing is that you believe that this tool should not bother _identifying_ CS issues if it is unable to completely _resolve_ them. I believe that this is a false assertion.

The `--dry-run` parameter performs _identification_ of issues. Regardless of this parameter setting, the tool should output the same messaging that occurs whenever it encounters any issues that cannot be fixed.

**Comment by keradus** [comment]
the output is the same regardless one use dry-run or not.
dry-run is to not store output on disk. not to change used rules.

if fixer cannot fix sth then the rule is problematic to follow in all cases, thus cannot be blindly enforced, so it would bring conflicts between different developer should that case be fixed or not. here you may inherit from parent class that is outside your repo, and for that you stick to camel case name. for that, you cannot fully automate the process.

**Comment by SpacePossum** [comment]
>What I think I'm hearing is that you believe that this tool should not bother identifying CS issues if it is unable to completely resolve them. I believe that this is a false assertion.

That is the scope of the tool, it is also what makes it awesome. It does not only detect but also fixes! happy days :)
The tool _could_ be used to detect a lot of cases it cannot fix, besides the naming of variable also of classes, interfaces, functions and methods, detecting usage of globals, assignment of variables inside conditions etc. etc.. I've a bunch of such `fixers` I use to profile my projects, however these are not real `fixers`. These do not fix, just detect. Therefor these do not belong here in the core of project.

What I _think_ will happen is that such detecting tool will be made by someone one day based on the tokenizer of this project. However the first step would be to put that into separate repo so both this fixer tool and the new detector tool can use it. This first step will take a bit (or better a lot ;)) of time to be done by however is concerned.

**Comment by skyzyx** [comment]
Closing this issue. Cross-linking with a similar issue posted to PHP_CodeSniffer: https://github.com/squizlabs/PHP_CodeSniffer/issues/1228

**Comment by TomasVotruba** [comment]
In case anyone still needs it, I've made a Rector rule that handles it:
https://github.com/rectorphp/rector/pull/3415
