### ISSUE TITLE
Broken "Add support for user-defined whitespaces"

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2365]
Causes `ErrorException·Undefined offset: 1` on some inputs. I can't confirm exactly how to reproduce this just yet, but I will do soon.

The issue is happening in `PhpCsFixer\DocBlock\Line::addBlank`:

![image](https://cloud.githubusercontent.com/assets/2829600/20967504/b84c3784-bc77-11e6-8a22-80670d6baa96.png)

Called inside `PhpCsFixer\Fixer\Phpdoc\PhpdocSeparationFixer::ensureAreSeparate`:

![image](https://cloud.githubusercontent.com/assets/2829600/20967516/cdd7abf6-bc77-11e6-8a65-66961be8da11.png)

**Comment by ktomk** [comment]
@GrahamCampbell: Sounds like there was no regex match as that is unchecked.

    $matches += [1 => '', 2 => ''];

to provide defaults. If it's not expected to not match, perhaps turning this into a more saying exception would help next time to easier reproduce it.

**Comment by GrahamCampbell** [comment]
But, this code didn't crash before the change, and now it does.
