### ISSUE TITLE
CSFixer leaves tmp-files after non-successful exit

### ISSUE THREAD

**Issue by masellfoodpanda** [FriendsOfPHP/PHP-CS-Fixer#2369]
On unsuccessful exit, the cs-fixer leaves tmp-files like `cs_fixer_tmp_by0aMl`. Please consider using `tmpfile();` for automatic delete of temporary files. Perhaps related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2144

For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/FriendsOfPHP/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v
```
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```
PHP CS Fixer version you are using:

$ php-cs-fixer -V
```
PHP CS Fixer 2.0.0-beta by Fabien Potencier and Dariusz Ruminski
```
The command you use to run the fixer (and the configuration file you are using if any).

`./bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection *`

**Comment by keradus** [comment]
File is created only on 5.x env to lint a file like `php -l tmpfile.php`
`tmpfile` will provide only a resource handler, but it's not possible to consume it by php linter.

Please:
- update version of tool you are using and see if it help
- describe what is unsuccessful exit? fixer crashed? has any error on console? what happen?

**Comment by masellfoodpanda** [comment]
Updated version, seems to be fixed.
