### ISSUE TITLE
NoSpacesInsideParenthesisFixer - deprecate fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2372]
NoExtraConsecutiveBlankLinesFixer does the same when configured with `parenthesis_brace_block`

**Comment by GrahamCampbell** [comment]
The descriptions don't match up:

> remove blank lines after a parenthesis opening block brace ('(') and/or end block brace (')')

Says nothing about spaces inside singleline blocks?

**Comment by GrahamCampbell** [comment]
Specifically, the method it calls is called `fixStructureOpenCloseIfMultiLine`.

**Comment by SpacePossum** [comment]
hmm indeed, closing for now, thanks!
