### ISSUE TITLE
PhpCsFixer\Config::setFinder does not work

### ISSUE THREAD

**Issue by FunTimeCoding** [FriendsOfPHP/PHP-CS-Fixer#2375]
PHP 5.6.24 (cli) (built: Jul 26 2016 18:38:38)
PHP CS Fixer 2.0.0 by Fabien Potencier and Dariusz Ruminski

Contents of `.php_cs.php`.

```php
<?php
$finder = PhpCsFixer\Finder::create()
    ->exclude('build')
    ->in(__DIR__);

foreach ($finder as $file) {
    echo $file.PHP_EOL;
}

return PhpCsFixer\Config::create()
    ->setRules(
        array(
            '@PSR2' => true,
            'array_syntax' => array('syntax' => 'short'),
        )
    )
    # The vendor directory is excluded by default.
    ->setFinder($finder);
```

Command to reproduce.

```sh
vendor/bin/php-cs-fixer fix . --using-cache no --dry-run --config .php_cs.php
```

This is the output I'm getting. As you can see, `build` is not showing up when I'm iterating over the finder, but php-cs-fixer detects a problem inside it. If I modify PhpCsFixer\Config and add `build` after the exclude of `vendor`, it will work. That made me think the config just gets ignored, so I went to ConfigurationResolver::resolveFinder() and var_dumped the last line, which does get called and does return a newly created (wrong?) finder _without_ `build` in it.

```
/home/areitzel/Code/Personal/php-skeleton/src/PhpSkeleton.php
/home/areitzel/Code/Personal/php-skeleton/src/LanguageExample/Calculator.php
/home/areitzel/Code/Personal/php-skeleton/test/Unit/PhpSkeletonTest.php
/home/areitzel/Code/Personal/php-skeleton/test/Unit/LanguageExample/CalculatorTest.php
/home/areitzel/Code/Personal/php-skeleton/test/Integration/MetricsTest.php
/home/areitzel/Code/Personal/php-skeleton/web/index.php
Loaded config default from ".php_cs.php".
   1) build/test.php

Checked all files in 0.079 seconds, 7.500 MB memory used
```

Contents of `build/test.php`.

```php
<?php
$foo = array();
```

**Comment by keradus** [comment]
so, basically
- you have specified the path (by Finder) in config file
- you have override path from config file by CLI argument `.`

if you don't want to override it simply don't provide CLI argument.
if you want to not override it but combine it - read about intersecting option.

**Comment by FunTimeCoding** [comment]
That did it. Silly me. Thanks.
