### ISSUE TITLE
Question: Allow to specify targeted PHP version

### ISSUE THREAD

**Issue by localheinz** [FriendsOfPHP/PHP-CS-Fixer#2378]
Would it make sense to be able to specify a PHP version that should be taken into account for fixing?

For example, working on a legacy code base that is using PHP 5.6, it would be nice to be able to run `php-cs-fixer` on PHP 7.1, but only have fixers applied for PHP version 5.6.

You know what I mean?

It's just much, much faster to run `php-cs-fixer` on PHP 7, but then the enabled fixers (some of them for PHP7) will kick in.

That is, I should be able to specify a version that is smaller than the one I am on, but not the other way around, for example

```
$  php -v

PHP 7.1.0 (cli) (built: Dec  4 2016 21:54:46) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

$ php-cs-fixer fix --php-version=50627
```

All we would need is 

* resolve the PHP version (either from configuration file, command line, or current system)
* have a way of passing that through to the individual fixers, and have them use that instead of refer to `PHP_VERSION_ID`

What do you think?

**Comment by keradus** [comment]
not easy.

we could make poor man check like:
- this fixer requires 7.0, your env is 7.1 so I could run it, but you requested target php 5.6, so I wont run it

but the hard part us tokenizer/linter. we use one that rely on version.
if you run tool on 7.0, you will get tokenizer from 7.0. if you run tool on 5.6, you will get tokenizer for 5.6. as base of tokenizer we are using is php-embedded `token_get_all`.
then, after all changes, we check that file is still valid via linter, which again will lint against your env php, not target php, for same reasons. so in edge case we will accept file valid for 7.0, but invalid on 5.6 (which we cannot check on 7.0 env)

**Comment by localheinz** [comment]
Closing!
