### ISSUE TITLE
Wrong curly braces positioning?

### ISSUE THREAD

**Issue by ricpelo** [FriendsOfPHP/PHP-CS-Fixer#2379]
With the following content:

```php
<?php

namespace Hello;
?>

<html>
    <body>
    <?php if (1 == 0) { ?>
        <?= "hello" ?>
    <?php } ?>
    </body>
</html>
```

after fixing with `php-cs-fixer fix .` I get the following:

```php
<?php

namespace Hello;

?>

<html>
    <body>
    <?php if (1 == 0) {
    ?>
        <?= "hello" ?>
    <?php 
} ?>
    </body>
</html>
```

IMHO, the original content doesn't needs fixing. The opening curly brace `{` and the closing tag `?>` should be on the same line, and the closing `}` is clearly in a wrong place after "fix".

```
$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```

```
$ php-cs-fixer -V
PHP CS Fixer 2.0.0 by Fabien Potencier and Dariusz Ruminski
```

**Comment by keradus** [comment]
we put new line after `<?php`.
i would disable fixing for your templates.

**Comment by ricpelo** [comment]
Thank you very much.
What can I do in order to disable fixing? Or what do you think is the best approach in this situation?

**Comment by keradus** [comment]
I would advice to configure a finder in `.php_cs.dist` file to ignore templates files

**Comment by coatesap** [comment]
+1 This is also causing problems in our codebase, and it's a shame to exclude all templates (and sometimes fiddly if component templates exist alongside their classes).

**Comment by keradus** [comment]
I would advice to either write template as php following all good practices, or dont - and don't try to fix them at all in first place.

**Comment by keradus** [comment]
Closing due to discussion

**Comment by coatesap** [comment]
@keradus - out of interest - in @ricpelo's example above, what would you have him change? Are you saying that just adding a blank line after the PHP tag would result in correct indentation?

**Comment by SpacePossum** [comment]
The indentation of templates like these will mostly likely never be fixed correctly by the tool, because it does look at the html elements in which the code lies.

**Comment by keradus** [comment]
@coatesap , out of interest, i would completely drop off mixing html with php and would use proper templating system instead, eg mustache
