### ISSUE TITLE
RFE: "fixer" to modify code constants, variables

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#2389]
The Go linker (go tool link) has an option to set the value of an uninitialised string variable (http://stackoverflow.com/a/11355611)

```
$ go run -ldflags "-X main.xyz=abc" main.go
```

it would be nice to do something similar in php projects as well. modify them to substitute some constant or class property to new value. i.e specify some build information to php file.

```php
namespace MyPackage;
class Version {
  const VERSION = '1.x-git';
};
```

using the fixer could embed version info there:

```php
namespace MyPackage;
class Version {
  const VERSION = 'v1.0.0-3-g8e2f75f';
};
```

yes, this can be done with `sed`, or some other pattern based replacement, but it's fragile, can cause resulting php file with syntax errors, and so on. 

therefore i think php-cs-fixer is right place to handle this, considering it knows the language syntax.

it could be implemented similarly to copyright fixer that takes extra configuration needed to know what exactly to replace.

some ideas how to implement include:
- add some `@annotation` that could help finding place to replace
- go style config with classname (absolute namespace),  and variable name that could be automatically identified to be:
  - constant (no prefix): `'MyPackage\Version\VERSION' => 'v1.0.0-3-g8e2f75f'`
  - property (`->`-prefix): `'MyPackage\Version->VERSION' => 'v1.0.0-3-g8e2f75f'`
  - static variable (`::$`-prefix): `'MyPackage\Version::$VERSION' => 'v1.0.0-3-g8e2f75f'`

**Comment by stof** [comment]
Putting a version of ``v1.0.0-3-g8e2f75f`` does not make sense. It would always be off by one commit (at least), as you cannot put the hash of the current commit in its own diff (the hash depends on the diff, so you get a chicken-and-egg issue even if you do crazy magic)

**Comment by glensc** [comment]
well. let met try again.

my usecase would not be normal "fixing" but injecting build information to files, i.e distribution files (tar.gz, zip produced by ci). i'm thiking php-cs-fixer is good tool about it because it knows php syntax and likely produces valid file compared to just running `sed` commands.

so in other words: result of this "fixer" is not intended to be committed to VCS.

**Comment by keradus** [comment]
what is your use case ? if something like preparing `.phar` release then just use box project for that

**Comment by glensc** [comment]
i've explained usecase(s) (with reasoning! why this project!) in issue description. and no, it's not about building phar with box.phar project, different distribution logic (which .zip or .tar.gz can be equivalent)

**Comment by keradus** [comment]
so, definitely, not a CS concern.

**Comment by SpacePossum** [comment]
I like the idea of such tool, however it is not a CS related FR.
Maybe when the Tokenizer (and transformers) are split out to its own repo it will be more easy for others to builds tools like this on top of that.
