### ISSUE TITLE
The output diff really needs an overhaul

### ISSUE THREAD

**Issue by twifty** [FriendsOfPHP/PHP-CS-Fixer#2391]
Currently the SebastianBergman diff utility is being used. While that library is great for quickly displaying differences in the terminal, its output is a headache to work with when actually being used as a diff.

Take the following example:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<report>
  <files>
    <file id="1" name="/Test.php">
      <applied_fixers>
        <applied_fixer name="method_separation"/>
      </applied_fixers>
      <diff><![CDATA[--- Original
+++ New
@@ @@
     }
-
 }
 
]]></diff>
    </file>
  </files>
  <time unit="s">
    <total value="0.03"/>
  </time>
  <memory value="6" unit="MB"/>
</report>
````
While I can live without the file headers, "---" and "+++", being correct, there is nothing to indicate at which line block begins. The only way to apply the diff is to iterate the file line by line and compare. While in this example, the block is tiny, if it were located at the beginning of the file rather than the end, the diff would contain almost the whole file, 99% of it being unchanged. For a diff parser though, it would have to iterate each line just in case there is another edit.

Would it be possible to switch out the diff library for one which outputs multiple blocks with real file indices?

**Comment by SpacePossum** [comment]
request for line numbers added to diff: 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/299 ([duplicate ](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1620))
request for short diff: 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1990
PR with short diff:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2007

while a popular request there is no solid solution PR'ed yet, so please help out! :)

**Comment by keradus** [comment]
Closing as duplicate.
Feel free to collaborate ! :)
