### ISSUE TITLE
Allow multiline arguments in function calls

### ISSUE THREAD

**Issue by rafis** [FriendsOfPHP/PHP-CS-Fixer#2417]
The PHP version you are using:
$ php -v
5.6

PHP CS Fixer version you are using:
$ php-cs-fixer -V
2.0.0

The command you use to run the fixer (and the configuration file you are using if any).
php-cs-fixer fix --rules=@PSR2,array_syntax,normalize_index_brace

How to allow multiline arguments in function calls?

    $this
        ->functionName(
            $arg1,
            $arg2,
            $arg3
        );

How to limit line length to certain number of characters, for example, 120 characters?

How to automatically indent code?

How to automatically import classes from other namespaces and replace, for example, "\Exception" to "Exception" in code?

**Comment by SpacePossum** [comment]
Hi!
Thanks for coming by and asking including all needed info :+1: 
ATM we've no fixer that deals with multi line functions, this has been request [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/111) as well. Currently there is no PR for it, so if you've time please let us know!

**Comment by keradus** [comment]
Closing as duplicate.
Indeed, would be nice to have, it would be great if you could prepare a PR ! :)
