### ISSUE TITLE
Add @concrete5 ruleset

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#2418]
Hi everybody,

What about creating a '@concrete5' ruleset in the [RuleSet.php](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/75b8b440231e7f4d3da94500bbd8002ccfb08cf8/src/RuleSet.php#L24) file?

Would you consider a pull request with it?

**Comment by keradus** [comment]
I don't want to be sound rash or anything, but I have never heard of it.
Globally-defined rulesets are rulesets for well established standards across PHP community, not for one-specific project.
What is the case here ?

**Comment by SpacePossum** [comment]
concrete5 is pretty big, but the CS is as unique as that of WP IIRC (been a while since I last worked with it)

**Comment by mlocati** [comment]
Talking about CMSs, concrete5 is one of the most common CMS out there.

Sure, WordPress is the most known one and eats the greater part of the marketshare, but it goes on its way alone and don't follow modern standards (take a look at https://github.com/WordPress/WordPress if you want a subject for your nightmares - I don't think it uses autoloaders for instance).
For sure @aembler or @KorvinSzanto (which is a [member of the PHP-FIG](http://www.php-fig.org/members/) may argue better about this subject.

**Comment by mlocati** [comment]
> concrete5 is pretty big, but the CS is as unique as that of WP IIRC (been a while since I last worked with it)

[Here](https://github.com/concrete5/concrete5/blob/fb59650e5cf5b7b56ba0bea904ed2e3789d88ec0/.php_cs.dist) you can find our rules: as you can see, they are *almost* the same as the Symfony ones, with a few exceptions (and we're going to have a final version of them here: https://github.com/concrete5/concrete5/pull/4873)

**Comment by keradus** [comment]
@mlocati , it's not about which project creates the rulest - example for WordPress has different meaning.
WP has weird standards, but they are used only in WP scope, for that they could have their "private" ruleset, not globalone.

eg `@PSR2` is the ruleset commonly used by many developers across a lot different projects.
same with existing `@Symfony` or (not-existing) other frameworks - they comes from framework community, but they are used across most projects made on top of that frameworks.

But, If I would make a great project XYZ, that is installed by million of users, thousand of contributors, with unique cs style, but then - they style is used only in that one project - no reason to push it to global ruleset, as nobody will use it for different project, and also it would require XYZ owner to send a PR to PHP-CS-Fixer to adjust the ruleset every single time (eg when PHP CS Fixer would offer new rules), making the ruleset harder and slower to maintain

**Comment by GrahamCampbell** [comment]
👎 For adding concrete5 as a preset in here.

**Comment by SpacePossum** [comment]
@mlocati looking at https://github.com/mlocati/concrete5/blob/04193bdbb4c9ab324e9d2a589216bfbf360f4929/.php_cs.dist you got a nice CS config :)
The thing I wonder about is the added value of adding those rules here as a predefined set. As of now the Concrete5 community can update the config/set whenever they want, putting it here will make it less flexiable as @keradus stated (for example https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2413 where one maintainer of SF want the set to be updated which means he has to go through here).
I'm not against added predef. sets as I see those as predef. config and pretty harmless, however the maintenance is best done by the community of that set and that typically makes it more practical for that community to do it in a repo of their own with all the flexibility that comes with it.

**Comment by mlocati** [comment]
@GrahamCampbell I don't think that saying "No" without any argumentation can be a benefit for a discussion (*any* discussion, not just this one) (please, don't take me wrong, it's just a suggestion...)

@keradus @SpacePossum concrete5 is highly customizable thanks to flexibility and portability of packages. BTW you're both right: even if a developer creates and maintains a package, she/he will still (usually) need the concrete5 core, so I agree that having a `.php_cs.dist` file in the release archive could be enough. So yes, you are both right... This issue can be closed IMHO (if no one else has something to add).

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell I don't think that saying "No" without any argumentation can be a benefit for a discussion (any discussion, not just this one) (please, don't take me wrong, it's just a suggestion...)

I was basically agreeing with @keradus. Sorry if that wasn't clear. Presets to be included should be because they target the majority of php-cs-fixer consumers, and concrete5 does not.

**Comment by mlocati** [comment]
> I was basically agreeing with @keradus. Sorry if that wasn't clear.

Now it is :wink:

> Presets to be included should be because they target the majority of php-cs-fixer consumers, and concrete5 does not.

I don't think that the number of users is the point (and btw concrete5 isn't a small project after all).
IMO the point is the availability of a standard project ruleset for all the developers involved.
Since concrete5 developers always need the concrete5 core, it's enough to add the ruleset to the concrete5 core instead of adding it to php-cs-fixer.

**Comment by keradus** [comment]
OK, so, after all the discussion, closing this ticket.
Thanks all for discussion so far and feel free to continue it. I'm closing just to keep the tickets clean and as we know that we don't merge it into global rulesets. Feel free to continue discussion if one wants.

**Comment by keradus** [comment]
@mlocati , I don't know the case here.
There is `concrete5` package that has the configuration.
Is there any other packages that should follow same ruleset ?
If so, then you may be interesting in making extra package like `concrete5-php-cs-fixer-config` which only purpose would be to reveal the `Config` class with `concrete5` settings. Then, it would be easy to reuse that class in other `concrete5` packages

**Comment by mlocati** [comment]
I don't think it's the case for concrete5.
Think of concrete5 packages as Firefox extensions: in theory you could develop a Firefox extension without having Firefox installed, but for sure you want Firefox installed to test it before the distribution...
concrete5 packages needs to be executed inside the concrete5 core.
