### ISSUE TITLE
Consider fixer to qualify global functions

### ISSUE THREAD

**Issue by bendavies** [FriendsOfPHP/PHP-CS-Fixer#2420]
See http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/ for background and benefit.

Probably quite difficult considering a user could have overwritten global functions in the current namespace.

**Comment by SpacePossum** [comment]
Finding candidates can be done using something like the [NativeFunctionCasingFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Casing/NativeFunctionCasingFixer.php) does.
But yes, it will be hard (if not impossible) to see if a candidate is a call to function with the same name in a different namespace by looking at the tokens alone.

**Comment by keradus** [comment]
I wonder what would be better - add `\` or `import` statement.

Still, if one will override the function in same namespace but different file, we would break the code

**Comment by localheinz** [comment]
@bendavies 

Take a look at https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2462!

@keradus 

>I wonder what would be better - add `\` or import statement.

Probably depends on whether people like a ton of imports!

> Still, if one will override the function in same namespace but different file, we would break the code

Declared the fixer in the PR as risky, hehe!

**Comment by bendavies** [comment]
Implemented!
