### ISSUE TITLE
[Question] How to execute rules with params via command line

### ISSUE THREAD

**Issue by shakaran** [FriendsOfPHP/PHP-CS-Fixer#2423]
I am trying to apply only a rule, without create a .php_cs config file, for example:

    $ php vendor/friendsofphp/php-cs-fixer/php-cs-fixer --rules=array_syntax mysrc

But that will take the default value for array_syntax value (which is syntax => long).

I would like use params via command line, something like:

    $ php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --rules=array_syntax[syntax=>short] mysrc

That should convert all the arrays with syntax short (that is array() to [] ) which is more syntax sugar and clean for improve readability. But this obviously doesn't work and it doesn't take the "syntax" param as supported.

Alternative ways (using quoted parameters) could be this one:

 $ php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --rules=array_syntax['syntax' => 'short'] mysrc

In fact this produces a weird exception (probably a bug) assuming that is a path:

    [PhpCsFixer\ConfigurationException\InvalidConfigurationException]  
  The path "=" is not readable.

But this is mostly a regresion, because in previous versions the documentation says that you can use short_array_syntax that was "deprecated" as you can read in [UPGRADE](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE.md) file, but it is only possible to use the values via config file and don't via parameters in command line?

**Comment by keradus** [comment]
expected behaviour is not possible.
using config file is advised

**Comment by shakaran** [comment]
@keradus and it would be possible to implement in future as feature request? It should be only a matter of how to parse params via command line

**Comment by SpacePossum** [comment]
Could be done, however some config is pretty complex. Passing such config by the commandline might not be easy as well, so I wonder how you would like to approach that :)

**Comment by keradus** [comment]
The only way I could approve would be to pass a JSON string as a value.

**Comment by SpacePossum** [comment]
like;
```bash
--rules=@PSR2,class_keyword_remove,concat_space{"spacing": "none"},dir_constant
```
?

**Comment by gharlan** [comment]
`--rules='{"@PSR2": true, "class_keyword_remove": true, "concat_space": {"spacing": "none"}, "dir_constant": true}'`

**Comment by shakaran** [comment]
@keradus @SpacePossum JSON format values seems a perfect valid option to me, it would be perfect!

**Comment by keradus** [comment]
no, like
```
--rules='{"@PSR2": true, "class_keyword_remove": true, "concat_space": {"spacing": "none"}, "dir_constant":true}'
```

we already have 2 formats, i don't want to have 3rd one

**Comment by ptcong** [comment]
Hi, is this feature implemented ?

**Comment by shakaran** [comment]
@ptcong no as far I know, it would be a great change to me if it gets implemented

**Comment by keradus** [comment]
feel free to collaborate ;)

**Comment by keradus** [comment]
feel free to collaborate ;)

**Comment by Bilge** [comment]
JSON seems like complete overkill and is only practical for tools. The command-line should remain usable by humans. My counter-proposal would be to adopt a form similar to Rake, i.e. `--rules=array_syntax[syntax=short]`.

There is no reason to bloat the syntax with JSON-specific grammar: the only thing JSON provides that a simple syntax does not is a distinction between types. That distinction is not important because a fixer should cast its parameters to the expected type, assuming the user will always specify them as a string, since that's what the command line is.

**Comment by shakaran** [comment]
Thanks @keradus works perfectly as:

    php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --rules='{"array_syntax": {"syntax": "short"}}' mypath

**Comment by Bilge** [comment]
Too bad it's impractical to actually type JSON into the command line.

**Comment by ptcong** [comment]
@Bilge  if you don't like, make a PR for style as 
`--rules='blah,blah[key=value]'`
@keradus i just have an idea that make easier to use rule param in cli. For example:
`--rules='array_syntax.syntax=long,another.key1=value1,another.key2=value2'`
It seems better than JSON, is it good ?

**Comment by keradus** [comment]
More possible syntaxes, more possible issues and misunderstanding how to provide CLI argument and more code doing the same to maintain.
Nice thing about reusing the format from file is... that we exactly reuse the code for parsing it. So we are sure that it will always work the same way.

If one don't wanna use predefined set but his own custom group of rules with some custom configuration I stronly advise to use config file.

**Comment by Bilge** [comment]
The configuration file approach is the real maintenance burden and not without its own [issues](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2537).

**Comment by keradus** [comment]
I think you don't understand the config file
