### ISSUE TITLE
Fixer for isset($var) && !empty($var)

### ISSUE THREAD

**Issue by stefandoorn** [FriendsOfPHP/PHP-CS-Fixer#2424]
As far as my understanding for the empty() function goes, it also check for the existence of the var and it will also check for NULL, which are both things isset() is also performing. It's redundant in that sense, but I have the impression it's being used often in code. I remember doing it myself until I really figured out that empty() already covered it. Would it be interesting to have a fixer for this or am I overlooking cases in which this statement makes sense to use?

**Comment by SpacePossum** [comment]
`isset` and `empty` do different things, for example
```php
<?php

$a = [1 => false];
var_dump(isset($a[1]));
var_dump(!empty($a[1]));

//bool(true)
//bool(false)
```
https://3v4l.org/aFcD8

Figuring out if one can be replaced by the other will require (a lot of) SCA for most cases which can not be done on looking at the tokens of one file alone. Even if we had more context it is probably not possible to determine if this can be done in a lot of cases.
I'm not sure if it is worth it to look for the easier cases to 'fix', what kind of cases do you've in mind to change?

**Comment by stefandoorn** [comment]
I mainly mean when being used together:

````
if (isset($row['test]) && !empty($row['test'])) {
````

In this case the isset() call would be redundant as !empty() does the work already. I agree with you that in the shown case above it does not make sense.

**Comment by ostrolucky** [comment]
i'm going to copy & paste here my comment from https://github.com/Symplify/Symplify/issues/409, it might be useful:


> I think I had to educate regarding this every PHP developer I've come in contact with. Read the docs:
> > empty() is essentially the concise equivalent to !isset($var) || $var == false.  
> 
> Only reasonable use for empty is replacement of such logic. In rest of the cases it's misleading, harder to debug, useless and more verbose. I'm going to elaborate:
> 
> Because isset is ok to use to check if variable is defined like such
> ```php
> function a() {
>     if ($someCondition) {
>        $a = true;
>     }
> 
>     if (isset($a)) {
>     }
> }
> ```
> 
> , empty is too, meaning
> ```php
> function a() {
>     $typo = $this->stuff();
> 
>     return !empty($tpyo);
> }
> ```
> 
> Is perfectly valid and won't trigger any errors, including IDEs.
> 
> I believe devs use it because they like name `empty`, but that is misleading, because this code says collection is not empty
> ```php
> function a(Collection $collection) {
>     return !empty($collection);
> }
> ```
> But objects never evaluate to false, so the above function will not work as intended.
> 
> Here is how are these constructs commonly used wrong and replacements:
> 
> <table>
> <tr>
> 	<th>Bad</th>
> 	<th>Good</th>
> </tr>
> <tr>
> 	<td valign="top"><pre>function a(array $stuff) {
>     if (!empty($stuff) {
>         ...
>     }
> }</pre></td>
> 	<td><pre>function a(array $stuff) {
>     if ($stuff) {
>         ...
>     }
> }</pre></td>
> </tr>
> 	<td valign="top"><pre>function a(array $stuff): bool {
>     return !empty($stuff);
> }</pre></td>
> 	<td><pre>function a(array $stuff): bool {
>     return (bool) $stuff;
> }</pre></td>
> </tr>
> 	<td valign="top"><pre>function a(array $stuff) {
>     if (isset($stuff['flag'] && $stuff['flag']) {
>         ...
>     }
> }</pre></td>
> 	<td><pre>function a(array $stuff) {
>     if (!empty($stuff['flag'])) {
>         ...
>     }
> }</pre></td>
> </tr>
> </table>

And I'm going to subscribe to this issue, I have large interest in this one

**Comment by kubawerlos** [comment]
> But objects never evaluate to false

Except when they do: https://3v4l.org/KmLXF

**Comment by ostrolucky** [comment]
No they don't https://3v4l.org/oJ1VM Go try to change your class in any way you want so it produces different result for `empty` construct

**Comment by kubawerlos** [comment]
Yet, sometimes they do: https://3v4l.org/S7XP3

**Comment by ostrolucky** [comment]
Hmm nice edge case. Learning something new every day.

**Comment by keradus** [comment]
1. Initial idea for the fixer is covering very edge case, I don't think it's needed to cover such an edge case (even if idea is valid!), and there were no community support for the request
2. I strongly disagree on first 2 presented by @ostrolucky , as I like to be strict and have true/false instead of truthy/falsy (+optionally casted later)
3. as @kubawerlos , it is different

closing.

**Comment by keradus** [comment]
I use `!empty($stuff)` over `$stuff`

**Comment by ostrolucky** [comment]
empty DOES casting internally

**Comment by keradus** [comment]
no, internal php functions does more than just casting

**Comment by ostrolucky** [comment]
PHP documentation:
> empty() is essentially the concise equivalent to !isset($var) || $var == false.

If you want strict behaviour, instead of empty you have to use: `$var === []` or `$var === false` etc

The things it does additionally are especially wrong as I have shown:
```php
function a() {
    $typo = $this->stuff();

    return !empty($tpyo);
}
```

This is perfectly valid for PHP with empty, but is logically wrong

**Comment by keradus** [comment]
again, `if !empty($stuff)` is different than `if $stuff`
one is true/false, other is truthy/falsy
one is strict, one doesnt. and calling internal fuctions to check sth on value is different than casting the values.
I'm not saying to use `empty` everywhere, I'm saying to not rely on `if $sth` if `$sth` is not boolean.
not sure what more we could educate you.

**Comment by ostrolucky** [comment]
Thing is you say you want strict behaviour, but `empty` is not giving you that, it relies on casting truthy/falsy value to boolean. That's all. If you wanted strict behaviour, you would use === / !=== instead of `empty`. On the other hand if you don't need strict behaviour (as indicated by usage of `empty`), you don't need `empty`.

Either replace `if (!empty($stuff)` with `if ([] !== $stuff)`, or don't say you write strict code. If you don't need to be strict, replacing all `if (!empty($stuff))` with `if ((bool) $stuff)` is same thing, except it no longer ignores undefined variables and doesn't use function with misleading name (see collection example).

**Comment by keradus** [comment]
you stuck with example of `empty`. please understand it's not about one method you stucked into, but it's about not doing truthy/falsy conditions
