### ISSUE TITLE
Travis-CI and PHP nightly issue

### ISSUE THREAD

**Issue by odan** [FriendsOfPHP/PHP-CS-Fixer#2427]
**PHP version:** PHP 7.2.0-dev (cli) (built: Dec 25 2016 22:47:01) ( ZTS )
**PHP CS Fixer version:** ^2.0

**Error message:**
Travis-CI error message: Build failed.
```
$ composer self-update
You are already using composer version 1.3.0 (stable channel).

$ composer install --no-interaction --prefer-source
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for friendsofphp/php-cs-fixer ^2.0 -> satisfiable by friendsofphp/php-cs-fixer[v2.0.0].
    - friendsofphp/php-cs-fixer v2.0.0 requires php ^5.3.6 || >=7.0 <7.2 -> your PHP version (7.2.0-dev) does not satisfy that requirement.
```

I've found a limitation for the upper PHP version in composer.json:
```
"php": "^5.3.6 || >=7.0 <7.2",
```
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json

I think this limit caused the issue in combination with the PHP nightly build.

**Comment by GrahamCampbell** [comment]
This is a bug with travis, we ask for 7.1, not master.

**Comment by GrahamCampbell** [comment]
Oh, right, your test suite is running nightly. Yeh, php-cs-fixer doesn't support php 7.2. It's not a bug, it's intentional.
