### ISSUE TITLE
using [indentation] in 2.0

### ISSUE THREAD

**Issue by NewFuture** [FriendsOfPHP/PHP-CS-Fixer#2439]
The PHP version you are using:
7.0
PHP CS Fixer version you are using:
2.0

The command you use to run the fixer (and the configuration file you are using if any).

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blame/v2.0.0/UPGRADE.md#L97

as document said:
`indentation` =>`no_tab_indentation`

but `no_tab_indentation` not found

is anything wrong here?

**Comment by GrahamCampbell** [comment]
Yes, the docs are exactly the wrong way around. `no_tab_indentation` is the old name.

**Comment by SpacePossum** [comment]
This is currently missing as feature, @ see
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/770
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1438

I've opened an PR to fix the docs, let me know what you think.

**Comment by keradus** [comment]
Closing, as:
- docs were updated
- for array it's a duplicated issue
