### ISSUE TITLE
no_alias_functions renamed user defined join() method to implode()

### ISSUE THREAD

**Issue by ilijastuden** [FriendsOfPHP/PHP-CS-Fixer#2442]
When `no_alias_functions` is included in the list of rules, it will rename user defined `join()` method. For example, there's intereface:

```php
<?php

interface JoinInterface
{
    public function &join();
}
```

and class that implements that interface.

PHP CS Fixer will rename both methods (signature from interface, and implementation from the concrete class) to `implode()`.

PHP 7.1, Code Style Fixer 2.0.

**Comment by keradus** [comment]
@ilijastuden could you send a PR with testcases proving bug and, if possible, a fix for it ?
