### ISSUE TITLE
Config for php-cs-fixer don't use configured finder.

### ISSUE THREAD

**Issue by voskobovich** [FriendsOfPHP/PHP-CS-Fixer#2465]
The PHP version you are using:
$ php -v
PHP 5.5.30 (cli) (built: Oct  3 2015 23:48:03) 

PHP CS Fixer version you are using:
$ vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.0.0 by Fabien Potencier and Dariusz Ruminski

Use command:
$ vendor/bin/php-cs-fixer fix .

This is my `.php_cs` file
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->notPath('/_data')

    ->notPath('/tests')
    ->notPath('/views')
    ->notPath('/assets')
    ->notPath('/runtime')

    ->exclude('/common/mail')

    ->filter(function (SplFileInfo $fileInfo) {
        return $fileInfo->getFilename() != 'requirements.php';
    })
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRules([
        '@PSR1' => true,
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'phpdoc_no_alias_tag' => [],
    ])
    ->setFinder($finder)
;
```

**I expect** that the excluded folders will not be processed.
```
    ->notPath('/_data')

    ->notPath('/tests')
    ->notPath('/views')
    ->notPath('/assets')
    ->notPath('/runtime')

    ->exclude('/common/mail')
```

But in the end they were processed.

See example video: https://www.youtube.com/watch?v=LnSH4iYyBFU

**Comment by GrahamCampbell** [comment]
This is because you're calling php-cs-fixer with a dot, thus overriding the config defined here.

**Comment by GrahamCampbell** [comment]
Change `fix .` to just `fix`.

**Comment by keradus** [comment]
Closing as answered
