### ISSUE TITLE
single_import_per_statement messing with my grouped imports

### ISSUE THREAD

**Issue by naknode** [FriendsOfPHP/PHP-CS-Fixer#2468]
When reporting an issue (bug) please provide the following information:

The PHP version you are using: 7.1.0

PHP CS Fixer version you are using: 2.0.0

I am talking specifically about this rule: _single_import_per_statement_ It messes with my PHP 7 grouped imported statements.

A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
use App\Core\Database\Connect;
use App\Core\Database\Query;
```

The fixed version of that code after you run the fixer and the version you expected.

```php
use App\Core\Database\{Connect, Query};
```

Is the grouped import statements the correct way now or is the single import per statement better?

**Comment by keradus** [comment]
how it mess up with your grouped import statements ?
The example code that was not fixed properly is not using group import. Don't get you here, please elaborate.

**Comment by keradus** [comment]
> The fixed version of that code after you run the fixer and the version you expected.

and then, you have provided one code only. is it expected or received code? how the other looks like ?

**Comment by kubk** [comment]
@naknode "single_import_per_statement" do not combines multiple imports into grouped import.
It splits single 'use' statement with multiple class declarations, examples: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/tests/Fixer/Import/SingleImportPerStatementFixerTest.php

**Comment by naknode** [comment]
Sorry about not responding. I have fixed my issue.
