### ISSUE TITLE
[Question] New 'Text' report

### ISSUE THREAD

**Issue by jaylinski** [FriendsOfPHP/PHP-CS-Fixer#2471]
The PHP version you are using:
> PHP 7.0.11

PHP CS Fixer version you are using:
> PHP CS Fixer 2.0.0

Hi!

First of all, thanks for your work on this package! ❤️ 

I'd like to ask if you are willing to except another report format.
I'm looking for a compact text report that looks similar to the one PHP_CodeSniffer is generating:

![screen](https://cloud.githubusercontent.com/assets/1668766/22150098/95c2d106-df17-11e6-8c61-92cb35434161.png)

If you are open for a reporter like this, I'll be happy to submit a PR. :octocat:

**Comment by keradus** [comment]
it will be ugly and slow to detect line number

**Comment by jaylinski** [comment]
:disappointed:
