### ISSUE TITLE
Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;

### ISSUE THREAD

**Issue by seb2411** [FriendsOfPHP/PHP-CS-Fixer#2479]
Hi,

Just to have a clarification.
In the Symfony coding standard we have this rule:

> Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;

http://symfony.com/doc/current/contributing/code/standards.html

This is not implemented in php-cs-fixer with @symfony.
Any specific reason ? 

Thx.

**Comment by SpacePossum** [comment]
please follow any of these discussions, I'm sure there an answer there somewhere ;)
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1184
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1980
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1187

**Comment by seb2411** [comment]
Thx.
