### ISSUE TITLE
Improve linter failure reporting

### ISSUE THREAD

**Issue by curry684** [FriendsOfPHP/PHP-CS-Fixer#2484]
As mentioned in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2090#issuecomment-275627493 - when linting fails before running a fix operation the output only states the file that causes an error:
```
Files that were not fixed due to errors reported during linting before fixing:
   1) MyBundle/Entity/SomeEntity.php
```
The `LintingException` caught [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3a394e5b8dd8c11065d4c04223714a443beb4a55/src/Runner/Runner.php#L143) does however include the full details of the problem, specifically line number and exact error. It should be logged and shown in the error report.

**Comment by SpacePossum** [comment]
for ref.: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1176
