### ISSUE TITLE
Add support to fix legacy PHP apps to PSR-4 Composer Autoload

### ISSUE THREAD

**Issue by chris001** [FriendsOfPHP/PHP-CS-Fixer#2491]
Would it be possible to add support to automatically fix a legacy PHP application which uses `require` and `include`, to upgrade the PHP code to use the PSR-4 Composer Autoloader.

* user specifies a folder containing the php application files, such as: `/home/domains/abc/public_html`
* user can specify which folders contain 3rd party libraries , and can specify which folders contain the application code
* user specifies an output folder where to save the generated output of the fixer.
* The fixer should do a `composer init` on the output folder.
* For every php file in the path.  Auto-replace all PHP `require` , `require_once`, `include`, `include_once`, with `use` and fix the syntax and paths as needed.
* Analyze the PHP application files and automatically add the correct `namespace` to each PHP file.  Obviously, skip the 3rd party libraries folder specified by the user, these can remain identical as from the repository.
* 3rd party libraries should be outputted to the `vendor` path, and applications code calling  them should be changed to `use` them, referring the corrected fixed path.
* Smart detect when a file is `require`d or `include`d, then all the classes inside it are local scope, these need to be refactored out of that PHP file into their own PHP file and saved to the corresponding place in the folder hierarchy, correct capitalization and naming convention, where the composer autoloader expects to find them.
* User can request a dry run summary report, or to output the new PHP files to a completely new folder tree.
* Etc.

**Comment by keradus** [comment]
1. this is not CS issue
2. this is not file-based changes but project-based changes.

PHP CS Fixer used as a library could probably be used as a base for a tool that will do at least part of your requirements, but as a CS Fixer app - no.

**Comment by chris001** [comment]
Since PHP CS Fixer fixes code to meet PSR-1 and PSR-2 coding standards, it would be a small step to add some rules which should apply most, if not all, of the coding standard for PSR-4 Autoloading with Composer.

I'm surprised a PSR-4 Fixer add-on for PHP CS Fixer, doesn't already exist.

**Comment by keradus** [comment]
there is `psr4` fixer.
but requested changes like rewrite `include` into `use` or create namespaces are not Coding Style issues.
