### ISSUE TITLE
Allow no_closing_tag to strip closing tag with whitespace between it and EOF

### ISSUE THREAD

**Issue by cronfy** [FriendsOfPHP/PHP-CS-Fixer#2497]
Currently `no_closing_tag` works only for monolithic PHP files (without `T_INLINE_HTML`).

I have some PHP files that are detected to be not monolitic, because of whitespace after closing php tag `?>`, for example:

```
<?php

echo "...";

?>
\n
\n
\n
```

I would like this closing tag to also be removed, so after running `php-cs-fixer` it should be:

```
<?php

echo "...";
```

**Comment by keradus** [comment]
removing whitelines after `?>` is changing HTML output that would be printed.
I totally agree that empty lines after `?>` are bad, but also removing them is changing raw HTML of file, which is more than CS issue - it's content change.

**Comment by cronfy** [comment]
Should it be configurable then?

3 февр. 2017 г. 11:12 PM пользователь "Dariusz Rumiński" <
notifications@github.com> написал:

**Comment by cronfy** [comment]
For example, `phpcbf` fixes the case described in my first post (monolitic PHP file, but with whitespace after closing tag).

Should the PR be updated to fix whitespace after closing tag only if there are only single empty (after `trim()`) `T_INLINE_HTML`  token at the end of PHP file?

**Comment by SpacePossum** [comment]
I there is one line break after close like:
```php
<?php
?>
```

than the line break is not printed by PHP, it is part of the close tag token so no T_INLINE is there. These close tags could be removed even for non-monolitic files (could be a new config option, +1 on that ;) ).

If there is a T_INLINE_HTML token than removing it will change code behavior, which is risky and possibly out of scope of the tool (so I'm +0 on this).

**Comment by cronfy** [comment]
> If there is a T_INLINE_HTML token than removing it will change code behavior, which is risky and possibly out of scope of the tool (so I'm +0 on this).

@SpacePossum even when `T_INLINE_HTML` containing only whitespace?

Ok, I see another solution: add a new rule marked as risky that will remove whitespace between closing tag and EOF. But I do not know if a fixer can be forced to run **before** another fixer (`no_closing_tag` in this case)?

**Comment by SpacePossum** [comment]
>even when T_INLINE_HTML containing only whitespace?

I see your point and as config item it could be done of course. I'm not a fan for a new fixer as it would be a lot duplicate code and slower processing (but than again, its just me ;) )

**Comment by keradus** [comment]
issue is riskiness. removing `?>` when there is no HTML is safe, removing `?>` when there is HTML (even blank lines) is changing the content, so it's risky.

I would avoid having one fixer risky or not depends on configuration

**Comment by cronfy** [comment]
Ok.

I have solved my issue by switching to `phpcbf`.

If anyone is interested in this feature in `php-cs-fixer`, I can create PR with a new fixer under `PhpCsFixer\Fixer\Contrib`, just let me know.

**Comment by cronfy** [comment]
I think this new fixer, if it will be created, should be simpler and only remove whitespace at the beginning/end of file before/after php open/close tags. And it should get the priority to be run before `no_closing_tag` fixer.

**Comment by keradus** [comment]
@cronfy 
I'm :+1: for this change, but indeed as separeted rule due to riskiness

**Comment by julienfalque** [comment]
Closing as the discussion staled.
