### ISSUE TITLE
Applying array_syntax short via the command line

### ISSUE THREAD

**Issue by olimorris** [FriendsOfPHP/PHP-CS-Fixer#2502]
In the docs it states that you can pass the `array_syntax` config via:

```
'array_syntax' => array('syntax' => 'short')
```

However, how do you do this via the command line, along with other rules?

**Comment by GrahamCampbell** [comment]
Not possible.

**Comment by GrahamCampbell** [comment]
Related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2494.

**Comment by keradus** [comment]
until solution is ready, you should put this into config file.

**Comment by SpacePossum** [comment]
With 2494 merged the config of the fixer by cli van be done.
It will be available in the next release and is currently available by source.
