### ISSUE TITLE
FullOpeningTag – Ensure opening tag is lowercase

### ISSUE THREAD

**Issue by jtojnar** [FriendsOfPHP/PHP-CS-Fixer#2503]
Using PHP CS Fixer 2.1.0-DEV (dev-master adc33eda0b9cce2b8702f0381c09f44071f210f3)

```
php-cs-fixer fix test.php --rules=full_opening_tag
```

Input (test.php)
-----
```php
<?PHP
echo "hello";
```
Actual Output
-----
```php
<?PHP
echo "hello";
```
Expected Output
---------
```php
<?php
echo "hello";
```

Relevant Documents
---------------------
[PSR-1](http://www.php-fig.org/psr/psr-1/#php-tags) is not exactly clear on this:

> PHP code MUST use the long `<?php ?>` tags or the short-echo `<?= ?>` tags; it MUST NOT use the other tag variations.

While `<?PHP` are technically also long tags, the specification does not talk about whether it considers them as such.

Even if any case were respected by the specification, enforcing the case is needed to keep the application consistent. If needed, configuration option could be added but I did not see much projects using anything else than lowercase.

**Comment by SpacePossum** [comment]
maybe this should be done by `lowercase_keywords`? (although `<?php` is not listed as keyword but it kind of is, isn't it?)

**Comment by keradus** [comment]
:+1: Seb

**Comment by jtojnar** [comment]
`T_OPEN_TAG` is [not considered](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f3baf72eb2f58bf275b372540f5b47d25aed910f/src/Tokenizer/Token.php#L260) a keyword, though.

**Comment by SpacePossum** [comment]
@jtojnar Indeed, I would however update the `lowercase_keywords` to fix the `<?php` open tag as well

**Comment by keradus** [comment]
or, let it be done by `full_opening_tag` perhaps ?

**Comment by jtojnar** [comment]
Sorry, forgot you already wrote that. Would not that be confusing, though? Even the [PSR](http://www.php-fig.org/psr/psr-2/#keywords-and-truefalsenull) links [keyword list](https://secure.php.net/manual/en/reserved.keywords.php). Personally, I do not consider opening tag part of the PHP script, I regard it as a relic of PHP’s templating past.

**Comment by SpacePossum** [comment]
>or, let it be done by full_opening_tag perhaps ?

hmmm would be against single responsibility principle, but I've no strong opinion

**Comment by keradus** [comment]
> full_opening_tag
> PHP code must use the long <?php tags or short-echo <?= tags and not
other tag variations.

So, if we would follow that description, `<?PHP` is not valid and fixer should fix it

**Comment by SpacePossum** [comment]
fair enough, `full_opening_tag` it is :)

**Comment by keradus** [comment]
@jtojnar, do you want to propose a PR?
I would say that it's very small, no need for introduce new fixers or options for existing fixers, just modify existing fixer to always do this change

**Comment by jtojnar** [comment]
@keradus I can do that.
