### ISSUE TITLE
How do you specify configurable rules on the command line?

### ISSUE THREAD

**Issue by nomad-software** [FriendsOfPHP/PHP-CS-Fixer#2510]
How do you specify configurable rules on the command line?

I can't find any documentation anywhere, regarding this.

**Comment by SpacePossum** [comment]
please follow any of these to related PR's which might make this possible

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2423
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2502

**Comment by nomad-software** [comment]
So it's currently not possible. Thanks for the reply.

**Comment by SaifurRahmanMohsin** [comment]
Is there a way to specify a ruleset.xml or phpcs.xml file via the command line or in Config::create()?

**Comment by SpacePossum** [comment]
@nomad-software 
With https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2494 merged the config of the fixer by cli can be done.

@SaifurRahmanMohsin 
not sure I understand correctly, but you can use `$ php-cs-fixer fix --config=.php_cs.dist` for example to specify the config file (`.php_cs.dist` in this example)
