### ISSUE TITLE
RFC stop on first style violation in dry-run mode

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2514]
CI case
When we have a project that uses PHP CS Fixer on CI, it will fail on style violation (so, `--dry-run` mode).
For that, most probably we could stop on first violation instead of checking whole project - for sure as a separated CLI argument switch.

What do you think ?

**Comment by SpacePossum** [comment]
like PHPUnit's `--stop-on-error` CLI option ? :+1:

**Comment by keradus** [comment]
yeah, but rather `--stop-on-violation` ;)

**Comment by GrahamCampbell** [comment]
> yeah, but rather --stop-on-violation ;)

How would that work? Stop once a file fails, or stop once a fixer wants to change something in a file.

**Comment by keradus** [comment]
stop on detection of cs violation

**Comment by GrahamCampbell** [comment]
Your implementation stops once all the fixers have completed running on a file, rather than as soon as one fixer has found something wrong.

**Comment by keradus** [comment]
fine for me. then it won't be like guy stucks 10 times fixing same files, but different rules.

**Comment by SpacePossum** [comment]
would be really be interested in a single rule violation in file over all violations in one file?

**Comment by keradus** [comment]
cannot get it. too many `be` ;)

**Comment by SpacePossum** [comment]
I'll rephrase: I think a user wants the tool to stop if a violation is found. If this happens the user wants the tool to lists _all_ violations in that file and not just of one rule.

hope its better ;)

**Comment by keradus** [comment]
so, same like me

**Comment by SpacePossum** [comment]
like you proposed, so not like your https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2514#issuecomment-279404413  ^_^

**Comment by keradus** [comment]
Ah, I meant my original proposal is fine for me, as Graham's one would couse 10 times fixing for same file

**Comment by keradus** [comment]
Then, please review #2532

**Comment by SpacePossum** [comment]
closing as https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2532 has been merged,
thanks for the work @keradus !
