### ISSUE TITLE
NoSpacesInsideParenthesis - allow multi line with comments

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2517]
PHP 7.1.1 / Fixer 2.x

```php
<?php

$a = $b->test(  // do not remove space between '(' and this comment
    $c,
    $d
);
```

currently the space is removed, RFC so the fixer will allow space between `(` and a comment.

**Comment by keradus** [comment]
makes sense, yet behaviour changing. it needs config option

**Comment by julienfalque** [comment]
👍 although I would consider this a bug, not a new feature.
