### ISSUE TITLE
The Fixer / Rule Symfony & PSR-2 does not exist

### ISSUE THREAD

**Issue by j3rrey** [FriendsOfPHP/PHP-CS-Fixer#2518]
Hey hey,

> "friendsofphp/php-cs-fixer": "^2.0"
> "phpro/grumphp": "^0.10.2",

I'm using grumphp to check my code before commiting and it's telling me:

> F  [UnexpectedValueException]
>   Rule "symfony" does not exist.
> 
> Exception trace:
>  () at /Users/foo/projects/bar/app/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php:181
>  PhpCsFixer\FixerFactory->useRuleSet() at /Users/foo/projects/bar/app/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php:264
>  PhpCsFixer\Console\ConfigurationResolver->getFixers() at /Users/foo/projects/bar/app/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:164
>  PhpCsFixer\Console\Command\FixCommand->execute() at /Users/foo/projects/bar/app/vendor/symfony/console/Command/Command.php:261
>  Symfony\Component\Console\Command\Command->run() at /Users/foo/projects/bar/app/vendor/symfony/console/Application.php:817
>  Symfony\Component\Console\Application->doRunCommand() at /Users/foo/projects/bar/app/vendor/symfony/console/Application.php:185
>  Symfony\Component\Console\Application->doRun() at /Users/foo/projects/bar/app/vendor/symfony/console/Application.php:116
>  Symfony\Component\Console\Application->run() at /Users/foo/projects/bar/app/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:45

Tried executing it manually and it tells me the same.

So I started digging into the code

I can see there is a ruleSet and the fixer factory is calling $ruleset->getRules() but that is returning only the rule Name for symfony, instead of the 91 array keys:

```
array:1 [
  0 => "symfony"
]
```
The rule set is 

```
'@Symfony' => array(
            '@PSR2' => true,
            'binary_operator_spaces' => array(
                'align_double_arrow' => false,
                'align_equals' => false,
            ),
            'blank_line_after_opening_tag' => true,
            'blank_line_before_return' => true,
            'cast_spaces' => true,
            'class_definition' => array('singleLine' => true),
            'concat_space' => array('spacing' => 'none'),
            'declare_equal_normalize' => true,
            'function_typehint_space' => true,
            'hash_to_slash_comment' => true,
            'heredoc_to_nowdoc' => true,
            'include' => true,
            'lowercase_cast' => true,
            'method_separation' => true,
            'native_function_casing' => true,
            'new_with_braces' => true,
            'no_alias_functions' => true,
            'no_blank_lines_after_class_opening' => true,
            'no_blank_lines_after_phpdoc' => true,
            'no_empty_comment' => true,
            'no_empty_phpdoc' => true,
            'no_empty_statement' => true,
            'no_extra_consecutive_blank_lines' => array(
                'curly_brace_block',
                'extra',
                'parenthesis_brace_block',
                'square_brace_block',
                'throw',
                'use',
            ),
            'no_leading_import_slash' => true,
            'no_leading_namespace_whitespace' => true,
            'no_mixed_echo_print' => array('use' => 'echo'),
            'no_multiline_whitespace_around_double_arrow' => true,
            'no_short_bool_cast' => true,
            'no_singleline_whitespace_before_semicolons' => true,
            'no_spaces_around_offset' => true,
            'no_trailing_comma_in_list_call' => true,
            'no_trailing_comma_in_singleline_array' => true,
            'no_unneeded_control_parentheses' => true,
            'no_unreachable_default_argument_value' => true,
            'no_unused_imports' => true,
            'no_whitespace_before_comma_in_array' => true,
            'no_whitespace_in_blank_line' => true,
            'normalize_index_brace' => true,
            'object_operator_without_whitespace' => true,
            'php_unit_fqcn_annotation' => true,
            'phpdoc_align' => true,
            'phpdoc_annotation_without_dot' => true,
            'phpdoc_indent' => true,
            'phpdoc_inline_tag' => true,
            'phpdoc_no_access' => true,
            'phpdoc_no_alias_tag' => true,
            'phpdoc_no_empty_return' => true,
            'phpdoc_no_package' => true,
            'phpdoc_scalar' => true,
            'phpdoc_separation' => true,
            'phpdoc_single_line_var_spacing' => true,
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => true,
            'phpdoc_trim' => true,
            'phpdoc_types' => true,
            'phpdoc_var_without_name' => true,
            'pre_increment' => true,
            'return_type_declaration' => true,
            'self_accessor' => true,
            'short_scalar_cast' => true,
            'single_blank_line_before_namespace' => true,
            'single_class_element_per_statement' => true,
            'single_quote' => true,
            'space_after_semicolon' => true,
            'standardize_not_equals' => true,
            'ternary_operator_spaces' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'unary_operator_spaces' => true,
            'whitespace_after_comma_in_array' => true,
        ),
```

Crashing here in the end:

  ```
  public function useRuleSet(RuleSetInterface $ruleSet)
    {
        $fixers = array();
        $fixersByName = array();
        $fixerConflicts = array();

        $fixerNames = array_keys($ruleSet->getRules());
        foreach ($fixerNames as $name) {
       ----->     if (!array_key_exists($name, $this->fixersByName)) {
          throw new \UnexpectedValueException(sprintf('Rule "%s" does not exist.', $name));
            }
```

ResolveSet() works as expected
somewhere in between resolveSet() and the fixerFactory the array keys get lost
I'll investigate further, any hints ?

**Comment by keradus** [comment]
> F [UnexpectedValueException]
> Rule "symfony" does not exist.

Use
```diff
-symfony
+Symfony
```

and it will work. I don't know would the lowercased value come from your config file or the `grumphp` project

**Comment by j3rrey** [comment]
Grumphp seems to make it lowercase, but the rules case sensitive... and if so maybe all of them should be lowercase ?

Hmm I just executed it with uppercase manually and it still throws the same error 

My grumphp.yml:
`parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    hooks_dir: ~
    hooks_preset: local
    stop_on_failure: false
    ignore_unstaged_changes: false
    process_async_limit: 10
    process_async_wait: 1000
    process_timeout: 60
    ascii:
        failed: grumphp-grumpy.txt
        succeeded: grumphp-happy.txt
    tasks:
        git_blacklist:
            keywords:
                - "die("
                - "var_dump("
                - "print_f("
                - "dump("
                - "dd("
                - "exit;"
            triggered_by: ["php"]
        git_commit_message:
            matchers:
                - /SER-([0-9]*)/
            case_insensitive: true
            multiline: true
            additional_modifiers: ''
        git_conflict: ~
        phpcsfixer2:
            allow_risky: false
            cache_file: ~
            config: ~
            rules: ["@Symfony"]
            using_cache: true
            path_mode: ~
            verbose: true
        phpmd:
            exclude: []
            ruleset: ['cleancode', 'codesize', 'naming']
            triggered_by: ["php"]
        phpparser:
            ignore_patterns: []
            kind: php7
            triggered_by: ["php"]
            visitors: {}
        phpunit: ~
        phpversion:
            project: "7.0"
        shell: ~

    testsuites: []
    extensions: []`


Something is weird here... :

```

  public function useRuleSet(RuleSetInterface $ruleSet)
    {
        $fixers = array();
        $fixersByName = array();
        $fixerConflicts = array();

        $fixerNames = array_keys($ruleSet->getRules());

//        dump($fixerNames, $this->fixersByName);
        foreach ($fixerNames as $name) {
            if (!array_key_exists('Symfony', $this->fixersByName)) {
                dump('==============FIXER FOUND!=============');
                dump($this->fixersByName['Symfony']);

            }
                if (!array_key_exists($name, $this->fixersByName)) {
                throw new \UnexpectedValueException(sprintf('Rule "%s" does not exist.', $name));
            }

            $fixer = $this->fixersByName[$name];

            $config = $ruleSet->getRuleConfiguration($name);
            if (null !== $config) {
                if ($fixer instanceof ConfigurableFixerInterface) {
                    if (!is_array($config) || !count($config)) {
                        throw new InvalidFixerConfigurationException($fixer->getName(), 'Configuration must be an array and may not be empty.');
                    }

                    $fixer->configure($config);
                } else {
                    throw new InvalidFixerConfigurationException($fixer->getName(), 'Is not configurable.');
                }
            }

            $fixers[] = $fixer;
            $fixersByName[$name] = $fixer;

            $conflicts = array_intersect($this->getFixersConflicts($fixer), $fixerNames);
            if (count($conflicts) > 0) {
                $fixerConflicts[$name] = $conflicts;
            }
        }

        if (count($fixerConflicts) > 0) {
            throw new \UnexpectedValueException($this->generateConflictMessage($fixerConflicts));
        }

        $this->fixers = $fixers;
        $this->fixersByName = $fixersByName;

        return $this;
    }

```
Output:

```

'/Users/USER/projects/FOO/APP/vendor/bin/php-cs-fixer' '--allow-risky=no' '--rules=Symfony' '--using-cache=yes' '--verbose' 'fix' 'app/Http/Controllers/v1/ApiController.php'
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config default.
"==============FIXER FOUND!============="


  [ErrorException]
  Undefined index: Symfony


```

**Comment by keradus** [comment]
> Grumphp seems to make it lowercase, but the rules case sensitive... maybe all of them should be lowercase ?

no


> Jep it's Grumphp, sorry for the confusion, you can close this issue now :)

indeed ;)
