### ISSUE TITLE
phpdoc descriptions start with lowercase letter with --rules @Symfony

### ISSUE THREAD

**Issue by bassch** [FriendsOfPHP/PHP-CS-Fixer#2523]
* **PHP version:** `7.0.13`
* **PHP CS Fixer version:** `2.0.0`
* **Command line:** `php-cs-fixer fix --rules @Symfony $FilePath`
* **Before:**
  ```php
  /**
   * Stores the value with the given key.
   *
   * @param mixed $key Key for identifying the data.
   * @param mixed $value Data to store with the given key.
   *
   * @return $this
   */
  public function set($key, $value)
  {
      $this->values[$key] = $value;
  
      return $this;
  }
  ```
* **After:**
  ```php
  /**
   * Stores the value with the given key.
   *
   * @param mixed $key   key for identifying the data
   * @param mixed $value data to store with the given key
   *
   * @return $this
   */
  public function set($key, $value)
  {
      $this->values[$key] = $value;
  
      return $this;
  }
  ```

I'm either doing something horribly wrong or running `php-cs-fixer fix` with  `-rules @Symfony` started converting the first letter of descriptions of phpdoc annotations to lowercase.

It didn't do that prior to upgrading to `2.0.0` so I guess this may either be me not getting the hang of running version `2.0.0` properly or it's an issue which was introduced with this version.

The Symfony documentation starts descriptions with an upper-case letter so I assume it's part of the coding standard.

**Comment by keradus** [comment]
`phpdoc_annotation_without_dot` claims that annotation description is not a sentence (so not only removing trailing dot, but also lowercasing first char)
Symfony codebase is following that rule.
If you don't want to follow it - exclude it in your config

**Comment by bassch** [comment]
I see.

I guess it's time to update the [Symfony Coding Standards documentation](http://symfony.com/doc/current/contributing/code/standards.html) then, because all the code examples are wrong then.

**Comment by keradus** [comment]
discussed. closing

**Comment by taisph** [comment]
According to the comment below:

_The policy is to have an uppercase first letter but no final dot._
https://github.com/symfony/symfony/issues/24164#issuecomment-388196094

Should I create a new issue on this?

**Comment by SpacePossum** [comment]
given this issue was raised 4 years ago and closed 3,5 years ago.. a new issue would be better, following the current issue template and including new samples and new links to SF standard etc. :)
