### ISSUE TITLE
phpdoc_add_missing_param_annotation bug?

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#2524]
Current Travis build for #2500 is failing because of a missing `@param` tag for a new parameter I added to a method, see [Travis log](https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/199890681#L2212). However, the [method](https://github.com/julienfalque/PHP-CS-Fixer/blob/900a170cca3bc2d3300d04d1328e36891d7da3f5/tests/Fixer/LanguageConstruct/DeclareEqualNormalizeFixerTest.php#L77) already had one parameter and no `@param` tag at all. Travis log shows that the fixer only adds one `@param` tag instead of two, is it expected?

**Comment by SpacePossum** [comment]
If you use the output you generate in 2500 you find the answer ;)

```
possum@jurassicpark:~/work/PHP-CS-Fixer$ php php-cs-fixer describe phpdoc_add_missing_param_annotation
Description of phpdoc_add_missing_param_annotation rule.
Phpdoc should contain @param for all params.

Fixer is configurable.
The following can be configured: `only_untyped => boolean`
Default configuration: ['only_untyped' => true].
```

(thanks for all the work on 2500 btw.! : D )

**Comment by julienfalque** [comment]
... Right 😑 sorry for the noise.
