### ISSUE TITLE
Line and column where error occurred should be shown in output

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2529]
* PHP 5.6.18
* PHP CS Fixer 2.0.1 by Fabien Potencier and Dariusz Ruminski

`vendor/bin/php-cs-fixer --allow-risky=no --rules=array_syntax --using-cache=yes -vvv --dry-run fix foo.php`

---

As a minimum, this tool should provide information about the line, and preferably the column, where an error occurred. Output like this is not useful for those wishing to manually fix errors:

>   1) foo.php (array_syntax)

I have no idea where to start looking in the file to fix the issue.

**Comment by SpacePossum** [comment]
`--diff` will show/list all changes that would be made if you would drop the `--dry-run` flag.

For adding alternative or additional output by the tool please see also the other RFC's like https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/299 for example.

**Comment by SpacePossum** [comment]
closed by the merge of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3162
