### ISSUE TITLE
Fixer configuration parameters should be documented

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2531]
It seems the documentation for fixers lives in the root readme file, which is convenient, but neglects to specify which parameters can be passed and their valid values. The readme only makes a distinction between fixers that have parameters and those that do not. For example, for a configurable fixer, the documentation states:

>Rule is: configurable.

This is inadequate and should instead provide a detailed list of each parameter and its accepted values. If this would make the documentation too verbose to live in the root readme then it should be linked in a separate documentation file.

**Comment by keradus** [comment]
1. use `describe` command to get description on CLI of rule and it's parameters.
2. readme update is on the way: #2500 

Valid point, solution is on the way.
Closing. For detailed discussion how to present data in readme file, go to mentioned PR.
