### ISSUE TITLE
Configuration file ignores specified paths in lieu of its own

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2537]
The documentation for the configuration file feature appears quite lacking, but it seems that when a configuration file is specified it is expected to provide its own `Finder` instance, and rules that specify which paths to search.

This doesn't make sense because the command line also accepts arguments that specify which paths/files to scan. Why should the configuration file be allowed, much less *required*, to override the paths specified by at the command line?

Furthermore, in the case that the configuration author wishes to just pass through the paths specified on the command line, it does not seem easy to do this. PHP-CS-Fixer makes no effort to provide the passed paths to the configuration so the best alternative is to re-parse the command line using the `$_SERVER` super global, which is very awkward.

This ticket should be considered satisfied when one or more of the following solutions are implemented.

1. Allow configurations to opt-out of specifying a `Finder` instance and search the paths passed on the command line instead.
2. Provide a mechanism for configurations to easily access the passed paths to seed such a `Finder` instance, assuming one is still required.

**Comment by keradus** [comment]
> configuration file is specified it is expected to provide its own Finder instance

possible, not required


> Why should the configuration file be allowed, much less required, to override the paths specified by at the command line?

not true, CLI arg may override value from config file. config file provides default values, CLI just a one-run values.


> Furthermore, in the case that the configuration author wishes to just pass through the paths specified on the command line, it does not seem easy to do this.

use path from config or CLI arg, no need to pass CLI arg to config instance.


> Allow configurations to opt-out of specifying a Finder instance and search the paths passed on the command line instead

Either use path from CLI or from config. dont mix them. You could use intersection of config/CLI using intersection mode.


> Provide a mechanism for configurations to easily access the passed paths to seed such a Finder instance, assuming one is still required.

config file should not be aware about CLI args.

**Comment by SpacePossum** [comment]
>Allow configurations to opt-out of specifying a Finder instance and search the paths passed on the command line instead.

This would be a BC break that does not add a lot of value. As `--path-mode` can be set to `override` (is by default) the files returned by the configuration are not used; the location passed by the command line is used.

>Provide a mechanism for configurations to easily access the passed paths to seed such a Finder instance, assuming one is still required.

I'm not in fav. of this design change. A configuration should be independent of values passed by the command line, because the code can be used in a diff. context. Resolving the configuration based on diff. sources; configuration file, cli options etc. is the responsibility of the ConfigurationResolver, not of the configuration classes.
