### ISSUE TITLE
Wrong indentation for class functions with comments

### ISSUE THREAD

**Issue by joseluisq** [FriendsOfPHP/PHP-CS-Fixer#2539]
When reporting an issue (bug) please provide the following information:

__The PHP version you are using:__
v7.0.15

__PHP CS Fixer version you are using:__
 v2.1.0

__The command you use to run the fixer (and the configuration file you are using if any).__
```sh
php-cs-fixer fix CategoryController.php --rules=@PSR2 
```

__A minimal sample of valid PHP code that is not fixed correctly (if applicable).__

__Before:__
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    const MODEL = 'App\Category';

    use RESTActions;

    /**
     * Show the default view.
     *
     * @return \Illuminate\Http\Response
     */
public function index(){return view('category');}
}
```

__After:__
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    const MODEL = 'App\Category';

    use RESTActions;

    /**
     * Show the default view.
     *
     * @return \Illuminate\Http\Response
     */
public function index()
{
    return view('category');
}
}
```

__The fixed version of that code after you run the fixer and the version you expected.__

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    const MODEL = 'App\Category';

    use RESTActions;

    /**
     * Show the default view.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category');
    }
}
```

When I remove the comment then indentation issue is fixed.

**Comment by keradus** [comment]
Hi. Thanks for your report.
I classify this as lack of feature (we didn't break the code, we didn't make it uglier either).
Actually, this is a duplicate, I would really want to see it solved.

Would you like to send a PR to make it happen ?

**Comment by joseluisq** [comment]
In fact I did search some related issue before but I did find it..
Sure, I could send a PR for this in near future. I'll need to explore a bit the codebase before. :sweat_smile:

**Comment by keradus** [comment]
probably `braces` fixer is missing proper comment handling

**Comment by joseluisq** [comment]
Ok, I'll fork the codebase..

**Comment by MarekLew** [comment]
This problem is duplicated and closed,closed and duplicated. Indentation after comment not work.

**Comment by keradus** [comment]
Fixed, will be released soon. thanks to @julienfalque !
