### ISSUE TITLE
Rule set subtraction doesn't work

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2543]
PHP 5.6.18
PHP CS Fixer 2.1.0 by Fabien Potencier and Dariusz Ruminski

The documentation seems to suggest it is possible to write `--rules=@Symfony,-@PSR1`. Although it is not clearly specified what this means, I expect it would use the Symfony rule set, less the PSR-1 set. However, this configuration does not work: overlapping PSR-1 rules remain enabled.

**Comment by keradus** [comment]
Could you please send a PR with test proving the bug and hopefully a bugfix ?

**Comment by Bilge** [comment]
I don't know how to do that.

**Comment by keradus** [comment]
Closing due to merge of #2545
