### ISSUE TITLE
phpdoc_order should be configurable

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2544]
The `phpdoc_order` fixer specifies:

>param annotations come first, then throws annotations, then return annotations.

However, this is very opinionated and other projects may wish to configure a different order.

**Comment by localheinz** [comment]
How about opening a PR?

**Comment by Bilge** [comment]
That's an interesting idea. Do you have any other interesting ideas?

**Comment by keradus** [comment]
We are community driven project. If you want to have a feature it would be great to help project introducing it. That's it.

**Comment by Bilge** [comment]
Are you suggesting I should not request a feature I am not prepared to code myself?

**Comment by localheinz** [comment]
@Bilge 

What _I_ am suggesting is this: If you are using an open source library and want a feature, but do not want to contribute it yourself, maybe try being a nice person. It helps in a lot of situations. 👍

**Comment by Bilge** [comment]
When was I not being a nice person?

**Comment by SpacePossum** [comment]
I would like `@throws` after `@returns`, it reminds me of when I was dev.ing in Java.
So please, anyone go for it :+1:

That being said, _I_ think if someone ask for a feature from a community, one should not be surprised if someone from that community asks about opening a PR. You can always so "no" for whatever reason (which you don't have to provide).

**Comment by keradus** [comment]
Everyone, calm down a bit ;)

All suggestions, requests and bug reports are more than welcome.
At the same point, we cannot make everything in house. Best option (but not the only one) to make the request happen is to help with it, if it is not possible by any reason then the requests end up in big backlog, from which requests are chosen by priority, amount of how many people are requesting same thing and finally willing of community to work on it. Your request is valid, question for help from your side as well. Just keep in mind that without it it's not on top of that backlog yet ;)

**Comment by Bilge** [comment]
I've seen enough.

**Comment by keradus** [comment]
Closing as duplicate of #1602
