### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL in 

### ISSUE THREAD

**Issue by fico7489** [FriendsOfPHP/PHP-CS-Fixer#2546]
I have code:

    function joinIfNot(\Illuminate\Database\Eloquent\Builder $builder, string $table, string $one, string $operator = null, string $two = null, string $type = 'inner', bool $where = false)
    {
        foreach ($builder->getQuery()->joins as $joinClause) {
            if ($joinClause->table === $table) {
                return $builder;
            }
        }

        return $builder->join($table, $one, $operator, $two, $type, $where);
    }

I am getting error:

"vendor/bin/php-cs-fixer" fix

Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\www\laravel\am2\green-rush\app\helpers.php on line 59

**Comment by julienfalque** [comment]
Using scalar type hints like `string` is supported since PHP 7. I suppose you run this code with a lower version which expects a `string` _class_ and thus does not allow a string (scalar) default value.

**Comment by SpacePossum** [comment]
https://3v4l.org/FP2vH

My guess is you are running PHP-CS-Fixer on a version lower than PHP 7.

**Comment by keradus** [comment]
@SpacePossum gitter ;P

**Comment by SpacePossum** [comment]
Closing for now as this issue staled, 
@fico7489 please feel free to comment here more if you think the issue was not properly analyzed.

**Comment by camohub** [comment]
I am on PHP7 and I am getting the same error from this peace of code:

    	function create(Product $entity = NULL, boolean $allowedLockPrice = FALSE){}

**Comment by keradus** [comment]
please make a full report using following template:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE

**Comment by JairVel** [comment]
Actualizar la versión de php lo resuelve, era problema de las bibliotecas de php en mi caso.

**Comment by keradus** [comment]
sorry @JairVel , we provide support here only in english.

**Comment by Oxicode** [comment]
> Actualizar la versión de php lo resuelve, era problema de las bibliotecas de php en mi caso.

Gracias, era eso tambien. 👍🏻 



> sorry @JairVel , we provide support here only in english.

Are you serious?

**Comment by SpacePossum** [comment]
hi @Oxicode and @JairVel , we would like to support any language... but if people don't know the langange and therefore don't understand someone how can we help?

**Comment by askmetech** [comment]
Fatal error: Default value for parameters with a class type hint can only be NULL in C:\wamp64\www\garden\system\core\Common.php on line 144
