### ISSUE TITLE
NoUnreachableDefaultArgumentValueFixer - extend docs/mark as risky

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2561]
we should mention in docs the problematic case discussed in #2485 
I'm even fine with marking the fixer as risky for that reason

**Comment by SpacePossum** [comment]
Should be easy enough I think. Marking the fixer `risky` is a BC break or a bug fix? I'd vote for the latter.

**Comment by keradus** [comment]
yeah, later
