### ISSUE TITLE
Blank line before break/continue?

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#2565]
Currently, we have `blank_line_before_return` fixer that adds... well, a blank line before `return` statements 😀. I often apply this by hand to `break` and `continue` statements as well:

```diff
 if ($foo) {
     $foo = 'baz';
+
     continue;
 }
```

```diff
 switch ($foo) {
     case 'foo':
         $foo = 'bar';
+
         break;
-
    default:
        $foo = 'baz';
 }
```

 I'd like to have a fixer to do it automatically. Would that be useful? If so, I'm willing to work on it.

**Comment by localheinz** [comment]
See #2384!
