### ISSUE TITLE
Fixer for opening and closing parenthesis in function call, one argument per function, if multiline.

### ISSUE THREAD

**Issue by ddctd143** [FriendsOfPHP/PHP-CS-Fixer#2576]
At the moment there is no fixer that could fix PSR2 rule, when there is multiline function call, opening and closing parentheses should be on separate lines. Also there should be one argument per line if function call is multiline. I found similar open issue, I don't know, if that issue is same as my request but I will attach that issue to this post.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/111

**Examples in code:**

<img width="592" alt="screen shot 2017-03-06 at 14 46 47" src="https://cloud.githubusercontent.com/assets/5021070/23610665/0a145eb2-027c-11e7-81e4-c59dd73c2823.png">

<img width="683" alt="screen shot 2017-03-06 at 14 45 02" src="https://cloud.githubusercontent.com/assets/5021070/23610669/0c7b50ca-027c-11e7-8c57-71a92050b7ce.png">

<img width="781" alt="screen shot 2017-03-06 at 14 49 15" src="https://cloud.githubusercontent.com/assets/5021070/23610675/194b13ee-027c-11e7-8a50-99c7c1b5afef.png">

```php
<?php

// Example 1: There should be one argument per line for multiline function call
function randomFunction()
{
    return [
        'url' => $this->getImageUrl(
            S3StorageService::MEDIA_TYPE_OFFERS, $image->imageable_id,
            $image->name,
            $image->created_at
        ),
    ];
}

// Example 2: Opening parenthesis of a multiline function call must be the last content on the line
function randomFunction()
{
    return [
        'url' => $this->getImageUrl(S3StorageService::MEDIA_TYPE_OFFERS,
            $image->imageable_id,
            $image->name,
            $image->created_at
        ),
    ];
}

// Example 3: Closing parenthesis of a multi-line function call must be on a line by itself
function randomFunction()
{
    return [
        'url' => $this->getImageUrl(
            S3StorageService::MEDIA_TYPE_OFFERS,
            $image->imageable_id,
            $image->name,
            $image->created_at),
    ];
}
```

Should be like this
```php
function randomFunction()
{
    return [
        'url' => $this->getImageUrl(
            S3StorageService::MEDIA_TYPE_OFFERS,
            $image->imageable_id,
            $image->name,
            $image->created_at
        ),
    ];
}
```

**Comment by SpacePossum** [comment]
Hi @ddctd143 

Thanks for your detailed report! Sorry for not responding sooner.
Your case is valid and reported and even better, addressed here; 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440

**Comment by julienfalque** [comment]
Closing as #2440 was merged.
