### ISSUE TITLE
Installation guide for Windows

### ISSUE THREAD

**Issue by guizoxxv** [FriendsOfPHP/PHP-CS-Fixer#2581]
I'm trying to use [atom-beutify](https://github.com/Glavin001/atom-beautify) with PHP and it request to install PHP-CS-Fixer but I find it confusing to install. I'm using Windows 10, PHP 7.0.13 and Composer 1.3.2.

**First:**
When I run
`composer.phar global require friendsofphp/php-cs-fixer`
on the command prompt I get Windows asking me how would I like to open the .phar file.
![cmd-open-phar](https://cloud.githubusercontent.com/assets/20052395/23671266/61ebdd72-0349-11e7-9e10-bf3b6a7af3b7.png)
Am I missing something? What should I do from here?

**Second:**
When I run
`export PATH="$PATH:$HOME/.composer/vendor/bin"`
it returns "'export' is not recognized as an internal or external command,
operable program or batch file."
![cmd-export](https://cloud.githubusercontent.com/assets/20052395/23671422/eda2d050-0349-11e7-820b-c0e6970a7226.png)
How should I use "export"?

**Third**
The atom-beautify package need a path to php-cs-fixer.
![php-cs-fixer_path](https://cloud.githubusercontent.com/assets/20052395/23668881/3588e6a6-0341-11e7-8da9-e8bab034ed4c.png)
What should I put in this option?

Thank you.

**Comment by keradus** [comment]
Non of your issues are related to PHP CS Fixer.

Either install composer globally (Composer for Windows) or run `.phar` executable like any php file - pointing interpreter (`php composer.phar require...`).

Also, `export` is *nix command, use `SET` instead if you really need it.

**Comment by guizoxxv** [comment]
@keradus 
I believe my Composer is installed globally. I just followed the installation instruction from [https://getcomposer.org/doc/00-intro.md](https://getcomposer.org/doc/00-intro.md).

To my knowledge, I can check if a program is installed globally if I can call it from any directory via command line. I can do so. Typing `composer -V` on any directory via command prompt gives me `Composer version 1.3.2 2017-01-27 18:23:41`. 

If this does not mean that Composer is installed globally I don't know how to do it and haven't seen documentation about doing so on the official site.

About "run `.phar` executable like any php file":
I ran `php composer.phar require php-cs-fixer-v2.phar` on this file directory and got `Could not open input file: composer.phar`

Thank you.

**Comment by SpacePossum** [comment]
>php composer.phar require php-cs-fixer-v2.phar

can you try;

>composer require php-cs-fixer-v2.phar

**Comment by guizoxxv** [comment]
@SpacePossum 
I get
`[InvalidArgumentException] Could not find package php-cs-fixer-v2.phar at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

**Comment by keradus** [comment]
So. You said you have globally installed composer, then even said that `composer -V` works.
Then why you run `composer.phar global require friendsofphp/php-cs-fixer` ?

Use
`composer global require friendsofphp/php-cs-fixer`

**Comment by keradus** [comment]
Closing as it is general issue `how to use Composer` or `how to use Atom` that is not directly related to PHP CS Fixer.
Feel free to continue discussion.

**Comment by guizoxxv** [comment]
@keradus 
You're right. The issue here is probably that I don't know how to use Composer (I just started using). I thought that `composer.phar` was the code for handling .phar files with Composer and `require friendsofphp/php-cs-fixer` was requiring a .phar file.

But since I followed [https://getcomposer.org/](https://getcomposer.org/) default installation for Windows I would expect that if I followed the installation instruction from PHP-CS-Fixer step-by-step would be OK. So I used `composer.phar global require friendsofphp/php-cs-fixer` because its what is available in the PHP-CS-Fixer README on Installation - Globally (Composer).

As `composer.phar global require friendsofphp/php-cs-fixer` didn't worked perhaps the README should also indicate the command you said `composer global require friendsofphp/php-cs-fixer:^2.0` which worked.

Thank you.

**Comment by keradus** [comment]
installing via composer show command and it's parameter for composer. it doesn't focus on how to install composer itself. you could install it via exe/msi installer or download phar file. same way, if you do later you could still name file differently like `composer-v1.phar), so the example command would not work as well
