### ISSUE TITLE
phpdoc_no_empty_return rule leaves empty line in docblocks with groupped annotations

### ISSUE THREAD

**Issue by tzurbaev** [FriendsOfPHP/PHP-CS-Fixer#2583]
## PHP Version
```
PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
```

## PHP CS Fixer Version
```
PHP CS Fixer version 2.1.1 by Fabien Potencier and Dariusz Ruminski (e0e33ce)
```

From some update (can't really track down which one caused this issue) `phpdoc_no_empty_return` rule leaves empty line in dockblocks with annotations groupped by type (see first example). Without groupping rule works fine (second example).

Also, `no_empty_phpdoc` rule does not help fixing this issue - empty line still persists.

### Groupped annotations

Original:

```php
<?php

class Foo
{
    /**
     * Set bar.
     *
     * @param string $bar
     *
     * @return null
     */
    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

Fixed:

```php
<?php

class Foo
{
    /**
     * Set bar.
     *
     * @param string $bar
     *
     */
    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

### Annotations without groupping

Original:

```php
<?php

class Foo
{
    /**
     * Set bar.
     *
     * @param string $bar
     * @return null
     */
    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

Fixed:

```php
<?php

class Foo
{
    /**
     * Set bar.
     *
     * @param string $bar
     */
    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

**.php_cs** config:

```php
<?php

$finder = PhpCsFixer\Finder::create()->in([__DIR__.'/src']);

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRules([
        'phpdoc_no_empty_return' => true,
    ])
    ->setFinder($finder);
```

Command:
`php-cs-fixer fix`

**Comment by SpacePossum** [comment]
Hi, 

Thank you for the detailed report!
`phpdoc_no_empty_return` I've confirmed this fixer indeed leases an empty line when the return annotation is not part of a group, I'll check if this is by design.
`no_empty_phpdoc` will remove the PHPDoc completely if it is made empty by `phpdoc_no_empty_return`.
In your case I would advice to add the rule `phpdoc_trim`, I think that one will remove the first and last empty lines if your PHPDoc's, it might help for a few cases for now.

**Comment by tzurbaev** [comment]
@SpacePossum `phpdoc_trim` did the trick, no more empty lines, thank you!
