### ISSUE TITLE
Fixer for spaces in control structures

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#2588]
As discussed [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2580#pullrequestreview-25993501), in control structures, spaces are not allowed after the opening parenthesis or before the closing one. 

This rule is defined by [_Overview_ section of PSR-2](http://www.php-fig.org/psr/psr-2/#overview) (last point):

> * Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.

and by [_Control Structures_ section of PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#5-control-structures):

> * There MUST NOT be a space after the opening parenthesis
> * There MUST NOT be a space before the closing parenthesis

There is no fixer to cover this. Such fixer should remove the spaces like this:

```diff
-if ( $foo ) { }
+if ($foo) { }
```

It should also remove newlines:

```diff
-if (
-    $foo,
+if ($foo,
     && $bar
-    && $baz
-) { }
+    && baz) { }
```

As one may argue _spaces_ do not include newlines here, maybe the second case should be optional (but enabled by default IMO).

**Comment by SpacePossum** [comment]
function argument list, function calls with multiple arguments, class/interface/traits definitions, all allow to be over multiple lines if each statement is on its own line, should `if` really be different?

i.e. should this be fixed (to one line)?
```php
if (
    $a    // xxxxx 
    || $b // xxxxx
    || $c // xxxxx
) {

}
```

**Comment by keradus** [comment]
Again, I don't see rule in PSR-2. Referring to whole section is not pointing the rule. Quote the sentence please.
In PSR-12 proposal, there is no multiline (as you pointed)

Your 1st case is valid, but 2nd not necessary. Especially if you follow the spirit of other rules, when you have multiple values (in function prototype/call or array), you put one per separate line.

**Comment by julienfalque** [comment]
I updated the description of the issue.

@SpacePossum I fully agree the rule is not consistent with others like function arguments, class definition, etc. The strange thing is that is does not forbid newlines betweens the conditions of an `if`, it just forbids them near the opening and closing parentheses. So in your example, the `if` would still have one condition per line, but the first and third conditions would be on the lines of the opening and closing parentheses.

@keradus I added the quotes. I agree the second case is more debatable and I think I would personnally not use it. I actually would like the second case to be valid as per PSR-12, but the rule has not been amended. I wonder if this diserves a discussion/issue/PR there. Anyway, this is why I suggest the second case to be optional.

**Comment by SpacePossum** [comment]
If we know nobody that is going to use the second case, I would say lets not build it :)

**Comment by julienfalque** [comment]
@SpacePossum If I remember correctly, the second case is reported as invalid by PHP_CodeSniffer using PSR-2 or Symfony standard so I doubt it won't be used at all. It should at least be part of the PSR-2 ruleset of PHP-CS-Fixer IMO.

**Comment by keradus** [comment]
> Opening parentheses for control structures MUST NOT have a space after them

So, let me investigate this

```php
<?php if ( 1 ) {}
````
character after `(` is ` ` (space character), it's violating the rule, it should be removed.

```php
<?php if (
    1
) {}
````
character after `(` is `\n` (newline character), it's not a space character, so it's not a violation

**Comment by julienfalque** [comment]
Yes that's the debatable part :)

You interpret _space_ as _literal single space character_ while I interpret it as _any spacing character, including newlines_. I'm pretty sure that's how PHP_CodeSniffer interpret it as well, but I'll doublecheck.

**Comment by SpacePossum** [comment]
simple grep on SF code base gives at least 45 violations, i.e. using notation:
```php
if (

```

My point about use is not about SF, PHP_CodeSniffer, PSR1/2/12, but about (this) community. You state you probably won't use it, neither would I and if I understand correctly @keradus and no else reported it, so why add it?

**Comment by julienfalque** [comment]
I would not use it on personal projects. For other projects, I would. But you're right, if nobody needs it, I'll better implement it externally.

**Comment by keradus** [comment]
From 2 presented cases:
1 - by default, inside `@PSR2` ruleset.
2 - optional config

at least for initial implementation and getting feedback. WDYT guys ?

**Comment by julienfalque** [comment]
@keradus Not sure what you mean, is it:
* Let's first implement a **non-configurable** fixer for case 1 **only**;
* Let's add it to `@PSR2` ruleset;
* We'll see later if fixing case 2 is worth it?

**Comment by keradus** [comment]
I was thinking about doing the optional config at the same time, but indeed, config could be postponed

**Comment by julienfalque** [comment]
Just saw that case 1 is already covered by `no_spaces_inside_parenthesis` fixer. Also, I asked about case 2 on the PHP-FIG mailing list and it looks like newline are not covered by the quoted rule and thus allowed in control structures, so we can close this issue without further work. Sorry for the noise.

**Comment by SpacePossum** [comment]
No worries about noise, was a nice discussion :)
IIRC it was not the first time it was brought up, with multi line conditions there is a lot more we could fix one way or the other (like comparison operators at the start or end of a line etc.).
I'm sure this will come back a FR.
