### ISSUE TITLE
[QUESTION] Run php-cs-fixer in non pure .php files (.phtml or .tpl files for example)

### ISSUE THREAD

**Issue by shakaran** [FriendsOfPHP/PHP-CS-Fixer#2589]
I am trying to fix the coding in several templates files like .phtml and .tpl files.

A lot of them has blocks of php files inside <?php and ?> which is the part that I would like to format and fix.

It is possible run in some way the php-cs-fixer in that extension files?

**Comment by GrahamCampbell** [comment]
Yes, you can configure the "finder".

![image](https://cloud.githubusercontent.com/assets/2829600/23760264/10e3a730-04e7-11e7-877a-ac4e18de9a24.png)

https://symfony.com/doc/current/components/finder.html

**Comment by SpacePossum** [comment]
little note, the default finder has `.php`, `.phpt` and `.twig` as file extensions set (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.1/src/Finder.php#L29), you can add the extension as you like in similar way.

(TBH I don't know why we have `.twig` as default on)

**Comment by keradus** [comment]
closing as answered
