### ISSUE TITLE
Incorrect diff header 

### ISSUE THREAD

**Issue by SimonvSiegert** [FriendsOfPHP/PHP-CS-Fixer#2604]
In the diff header the corresponing line numbers are missing. It would be great to have the correct line format according to https://en.wikipedia.org/wiki/Diff_utility#Unified_format.
Best wishes

Sample output:
      ---------- begin diff ----------
--- Original
+++ New
@@ @@

$ php -v
PHP 5.6.30
$ php-cs-fixer -V
PHP 5.6.30
command options:
--dry-run --diff

**Comment by SpacePossum** [comment]
Hi, thanks for your feature request.

Since this is already requested I'm closing this issue as duplicate, please see;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/299
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1620
