### ISSUE TITLE
PHP CS Fixer used as file watcher in PHPStorm with path-mode

### ISSUE THREAD

**Issue by MetalArend** [FriendsOfPHP/PHP-CS-Fixer#2624]
I'm using PHP CS Fixer in PHPStorm with the following settings:

```
File Type: PHP
Scope: Project Files
Program: [...]/vendor/friendsofphp/php-cs-fixer/php-cs-fixer
Arguments: fix --path-mode=intersection --config=$ContentRoot$/.php_cs $FilePath$
Output paths to refresh: $FilePath$
Other Options/Working directory: $Projectpath$
```

In my .php_cs file I have a section 
```
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude(['./app', './tests/Fixtures', './var', './vendor', './web'])
            ->in(__DIR__)
    )
```

This works amazingly well. But I have been looking for one specific option: is it possible to make sure the provided configuration excludes are forced, so the file watcher will never ever be able to fix a file that is in one of the excluded directories? Could this be made available as a value for the `--path-mode` option, for example `config`?

**Comment by julienfalque** [comment]
IMO it does not make sense to run the tool for a specific file that is then excluded via the config. Maybe you can create a custom scope in PHPStorm instead?

**Comment by MetalArend** [comment]
Solved: remove the './' from the path.

**Comment by MetalArend** [comment]
@julienfalque I find the use case very interesting: I declare the excluded paths inside the .php_cs file (which is a nice feature to be able to do that), and I leave it up to PHP CS to check if it is okay to fix the file. If you create a custom scope in PHPStorm, you have to make sure it is up to date with php cs at all times. But as I figured out just now, it seems to work correctly if I remove the "./" from the path.
