### ISSUE TITLE
Exit status should be 0, only if there are no errors

### ISSUE THREAD

**Issue by JoyceBabu** [FriendsOfPHP/PHP-CS-Fixer#2629]
This is a follow up to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1041

Currently PHP-CS-Fixer returns 0 if `--dry-run` is not specified, even when some files were skipped due to syntax errors. Shouldn't it return a non-zero value when a file is skipped?

The fixer was expected to fix the file, but it could not be fixed. Isn't that an error condition?

**Comment by keradus** [comment]
No.
User is asking to fix folder `foo`.
Inside there are two files - `foo\valid.php` and `foo\invalid.php`.
If PHP CS Fixer would fix all proper files properly - it did it;s job good, since exit status is zero.

**Comment by JoyceBabu** [comment]
User is asking to fix all files in the folder `foo`. So the expected output is that all the files are fixed, at least for some users. 

I am using PHP-CS-Fixer in `pre-commit` hook of git to fix the coding style on commit. For each file, I am calling `php-cs-fixer fix <filename>`. I expect `php-cs-fixer` to fix the coding style on the specified file, but `php-cs-fixer` skips the file when there is a syntax error. That is an error in my use case.

Currently, the only way to verify whether the file was fixed or not is to check the `STDERR`. Instead, if PHP-CS-Fixer returns different return codes when all files were fixed and when some files were skipped, it would be much better.

Currently it is very difficult to check for skipped files, because I want the STDOUT to be streamed to console and STDERR to go to a variable for checking for skipped files.

        { CS_FIXER_ERROR=$(${PHP_INTERPRETER} ${PHP_CS_FIXER} fix --config="$PROJECT_DIRECTORY/.php_cs" --verbose ${file} 2>&1 1>&3); } 3>&1
        echo "$CS_FIXER_ERROR" | grep -q "Files that were not fixed due to errors reported during linting before fixing:"
        
        if [ $? -eq 0 ]; then
            STATUS=1
        else
            git add "$file";
        fi

I understand that I can avoid all of this by performing syntax check before running `php-cs-fixer fix`, but that is an unnecessary step when `php-cs-fixer` is anyway doing it.

IMHO the ideal solution would be to 
 - Return `0` when all files are fixed
 - Return a non-zero value when some files were skipped
 - Add a new flag, say `--skip-broken`, to return `0` even when files were skipped

That would allow all use cases. I kindly request you to re-consider your decision.

Can you at least add a flag to instruct `PHP-CS-Fixer` to consider skipped files as error, if backward compatibility is an issue?

**Comment by keradus** [comment]
When user want to fix sth automatically, 0 means that everything that could be fixed was fixed, no internal errors. error of user is error of user (like invalid file).
When user want to check that all files are valid, he run dry-run mode, in which any of violating-CS or violating-syntax file will cause non-zero exit status.

**Comment by JoyceBabu** [comment]
The purpose of the `pre-commit` hook is to automatically fix the coding style. So using dry-run mode will not work.

**Comment by stof** [comment]
@JoyceBabu linting files for syntax errors is not the job of a CS fixer. If you want to lint files too, use `php -l` in your pre-commit hook.

the only reason there is some linting in PHP-CS-Fixer is because fixing CS in files which have an invalid syntax would require to make the code totally crazy in the tool (as it relies on parsing the code)

**Comment by hkdobrev** [comment]
If there are no permissions to read the file or the file is missing, would you still exit with a 0, because the fixer fixed everything it could? I think whenever the files being given to the fixer cannot be parsed for whatever reason this should be a non-zero exit code.

**Comment by SpacePossum** [comment]
>If there are no permissions to read the file or the file is missing, would you still exit with a 0,
```
$ chmod 000 a.php

$ php-cs-fixer fix a.php
  [ErrorException]                                                                                       
  file_get_contents(/home/possum/work/PHP-CS-Fixer/doc/a.php): failed to open stream: Permission denied  

$ echo $?
  1

$ php-cs-fixer fix a.txt                                                                 
  [PhpCsFixer\ConfigurationException\InvalidConfigurationException]  
  The path "a.txt" is not readable.                                  

$ echo $?
  16
```                                                                     

If you're using a configuration with a `Finder` than the finder can throw exceptions if it can read or find a file.

**Comment by JoyceBabu** [comment]
> linting files for syntax errors is not the job of a CS fixer. If you want to lint files too, use php -l in your pre-commit hook.

I understand your point of view. But please understand that there is an alternate view too. For me (and I believe for many others), all failures are failures. It doesn't matter whether it was due to permission error or syntax error.

When I run `php-cs-fixer fix a.php`, I expect the output to be a file that conforms to my specified coding syntax. If `php-cs-fixer` has failed to do that due to internal or external reasons, for me, that is an error. While using `php-cs-fixer fix` on a directory, it makes more sense to skip invalid files. But in this case, I am specifically asking to fix a file, and it was not fixed. 

I really hope you would consider the alternate view and add this feature, even if it is the non default behaviour enabled by a flag.

**Comment by keradus** [comment]
as I wrote a month ago, it was strongly discussed and design decision was made. you cannot fulfill everyone wishes, having 10 flags is also bad way.
The closes thing what you want to have is already there:
> run dry-run mode, in which any of violating-CS or violating-syntax file will cause non-zero exit status.

**Comment by SpacePossum** [comment]
To me it would make sense;
- throw/exit with configuration exception when try to fix one file that fails linting. This exit status would be correct as the fixer cannot fix the file, but it does not know if the CS is valid either (i.e. code that does not lint might be CS formatted correct and does need fixing). This would be inline with the other exceptions (`file not found` and `file not readable`). PHPUnit does something similar when trying to run one file that does not contain a utest
- when fixing a directory that contains files that cannot be fixed because of linting I would _not_ fail.

_if_ we make changes I'm -1 on doing it on the current release branches as it would be a BC break. Adding another flag (that would be overcomplete on the next major release) would make things more complex and confusing users than it is worth IMHO.

**Comment by keradus** [comment]
Closing due to discussion.

Don't get me wrong @JoyceBabu , I do see your point, but there is too less interest in that approach
