### ISSUE TITLE
phpdoc_to_comment inconsistent treatment of PHPDoc tags

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2634]
`phpdoc_to_comment` fixer does not consistently detect phpDocumenter comments. Consider the following two examples.

```php
<?php

class A
{
    public function b()
    {
        /** @var int $c */
        print($c = 0);
    }
}
```

This example will be changed as follows:

```diff
--- Original
+++ New
@@ @@
     {
-        /** @var int $c */
+        /* @var int $c */
         print($c = 0);
     }
 }
```

However, exactly the same code formatted in a slightly different way will not be changed by the fixer, as shown below.

```php
<?php

class A
{
    public function b()
    {
        
        print(
            /** @var int $c */
            $c = 0
        );
    }
}
```

I think this fixer should either:

1. Be changed to treat any occurrence of `@foo` (i.e. `\b@\w+\b`) as valid docblock content, or
2. Include a *simple validation* mode that behaves the way described in 1.

Currently this fixer seems to be trying to be "too clever" to determine if a comment comprises valid docblock content which is causing more harm than good in many usage scenarios.

**Comment by SpacePossum** [comment]
If we would change the fixers behavior to your point 1 or 2 what cases are there left for the fixer to fix?

**Comment by keradus** [comment]
ping @ceeram , WDYT ?

**Comment by ceeram** [comment]
The original code is correct. This case should not be converted to normal
comment. I guess I forgot about this scenario

Op 23 mrt. 2017 21:19 schreef "Dariusz Rumiński" <notifications@github.com>:

**Comment by Bilge** [comment]
@SpacePossum It would still convert comments that contain no docblock annotations, which is the case it's supposed to support.

**Comment by ceeram** [comment]
I have looked a bit more into psr5, but it does not cover language constructs as Structural Elements. Control flows are also not covered but are mentioned. print() is neither in the list of valid control structures and structural elements. It is like `list()` a language construct, which we do skip to fix. I will have a pull request up for expand this to allow more language constructs.

**Comment by Bilge** [comment]
`print()` is not significant or relevant. The following code is also converted incorrectly.

```php
<?php

class A
{
    public function b($d)
    {
        /** @var int $c */
        $this->b($c = 0);
    }
}
```

**Comment by GrahamCampbell** [comment]
> It's also like to remind you that PSR-5 is not a published standard. You are adhering to a draft that may never be anything more than a draft. It does not seem prudent to aim for such a moving target.

There is no published standard, so. :P

**Comment by ceeram** [comment]
PSR5 is not accepted yet indeed, this fixer is one that tries to comply with the proposed standard, if you don't want your code to follow PSR5, then exclude this fixer.

**Comment by ceeram** [comment]
the next element after phpdoc is `$this` which is not the documented variable. According to PSR-5 this is incorrect, hence its being fixed to be a comment. This is intentional.
