### ISSUE TITLE
SemicolonAfterInstructionFixer - should not put a semicolon after a colon (alternative syntax)

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#2638]
**semicolon_after_instruction** changes the following code

```php
<?php if ($foo): ?>
```

to

```php
<?php if ($foo):; ?>
```

I don't think it should do it.

**Comment by SpacePossum** [comment]
indeed, good catch, I forgot about the [alternative syntax](http://php.net/manual/en/control-structures.alternative-syntax.php) cases.
