### ISSUE TITLE
Multiline comments to one-line

### ISSUE THREAD

**Issue by zored** [FriendsOfPHP/PHP-CS-Fixer#2646]
Is that possible to convert multiline comments and PHPDocs with into one-line?
Only for comments with one line of useful information.

## Example
Before:
```php
/**
 * @Example
 */
```

After:
```php
/** @Example */
```

**Comment by SpacePossum** [comment]
Hi @zored 

At the moment we do not have a rule/fixer to do that.
Could you elaborate or provide a use case for when you would want this to happen?

**Comment by zored** [comment]
@SpacePossum, hi.

This rule would save 2 extra lines of code per each one-line comment block. Code will be more compact and easier to read.

For example, I have model objects with many properties that only have '@var' type definitions. And each property has getter with only '@return' annotation. They occupy 'N x 2 x 2' lines of code (where 'N' is number of properties).

Or '@inhertDoc' that occupies two extra lines of code.

Thanks for reply :)

**Comment by julienfalque** [comment]
I won't use such fixer personally, but the use case seems valid to me.

**Comment by zored** [comment]
Currently using [my own simple script](https://gist.github.com/zored/8ffde76c8ec1617756de6156b2c63218) for conversion.

**Comment by keradus** [comment]
I wouldn't use that fixer as well. but it's not blocking the fixer to become accepted.
Actually, I would use reverse fixer for methods/classes/properties, but one-line docblock for regular vars.
Would be great to see it that generic and configurable.

**Comment by zored** [comment]
This code:
```php
<?php
class Hi
{
    /** @return string */
    public function hello($string)
    {
        return $string;
    }
}
```

Fixes comment into:
```php
    * @param mixed $string
/** @return string */
```

So existing code should be aware about this type of comments.

@keradus, yes, options for this rule will be great. I think that some users will prefer to use multiline one-liners because they are easier to modify.

**Comment by keradus** [comment]
> Fixes comment into:

what is fixes comment into that invalid piece of code? PHP CS Fixer or your custom script? if first, we have very sad bug here.

**Comment by zored** [comment]
@keradus PHP CS Fixer 2.1.2.
The good news is that this one-line format rarely used in method PHPDocs  😃

**Comment by keradus** [comment]
ok, let us move discussion about invalid phpdoc modification here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2654
here, let us focus only on `multiline vs oneline docblock` ;)

**Comment by BackEndTea** [comment]
If anyone wants to pick this up, this is 'somewhat' included in the phpunit test annotation fixer, although it can be improved upon quite a bit.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/99aeaa2fa1063879ea5782b034eac48f2f6766d3/src/Fixer/PhpUnit/PhpUnitTestAnnotationFixer.php#L441-L477

**Comment by iluuu1994** [comment]
I'd like to implement this since we format all of our properties with only the `@var` attribute this way.

```diff
-/**
- * @var string
- */
+/** @var string */
private $foo;
```

One thing that would be nice is knowing what the comment is commenting. We do method comments in multiple lines, even if there's only one meaningful line:

```php
/**
 * @return string
 */
public function foo() { ... }
```

One could configure the comments of which declarations the fixer is allowed to fix:

* classes (including traits and interfaces)
* functions (including methods)
* properties
* variables

So we would need to look just far enough to recognize the next statement.

It's a pity that php-cs-fixer doesn't have a parse tree. That would make a lot of rules much simpler.

**Comment by iluuu1994** [comment]
Wow, I completely missed that this already has a PR. Sorry.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3810
