### ISSUE TITLE
indentation_type fixer kills switch spacing

### ISSUE THREAD

**Issue by rbayliss** [FriendsOfPHP/PHP-CS-Fixer#2650]
Running the indentation_type fixer with an indentation of '  ' (two spaces) yields the following results:

**Input**
```php
<?php 

switch($myvar) {
  case 1:
    echo 'Got case 1';
    break;
  default:
    echo 'Got default case';
}
```

**Output**
```php
switch($myvar) {
  case 1:
  echo 'Got case 1';
  break;
  default:
  echo 'Got default case';
}
```
Is this expected?  If so, is there another fixer that can correct this spacing?  I'd like it to look just like the input.

**Comment by SpacePossum** [comment]
Hi!
Thanks for the report. Could you please provide the PHP version you are using together with version of the Fixer and the configuration of the Fixer?
This information will help us to answer your question, thanks!

**Comment by rbayliss** [comment]
Yep, sorry for omitting that.  PHP 7.0.12, and the bleeding edge of php-cs-fixer: 9e3302c8fa9c0c622f839fa5f9233f428521011c

**.php_cs:**
```php
<?php

$finder = PhpCsFixer\Finder::create()
  ->in(__DIR__.'/scrap')
  ->files('*');

$config = \PhpCsFixer\Config::create()
  ->setFinder($finder)
  ->setIndent('  ')
  ->setUsingCache(FALSE)
  ->setRules([
    'indentation_type' => TRUE,
  ]);

return $config;
```

**Comment by ntzm** [comment]
I believe this is because the indentation fixer only expects the indentation to be either 4 spaces, tabs, or a mixture of spaces and tabs ([reference](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Whitespace/IndentationTypeFixer.php#L78)).

**Comment by rbayliss** [comment]
Yeah, that's what I'm seeing too... this feels like a bug, right?  I'm willing to submit a PR, but I'm not really sure where to start with this one.

**Comment by medgoprot** [comment]
Someone should close this as the fix was already merged.

**Comment by keradus** [comment]
sure thing, thanks for pointing this out!
