### ISSUE TITLE
2.1.3 deploy didn't work I think?

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2662]
![image](https://cloud.githubusercontent.com/assets/2829600/24559591/2d7de994-1637-11e7-9de1-26251468a5ca.png)

**Comment by keradus** [comment]
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/builds/217162093

**Comment by GrahamCampbell** [comment]
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/builds/217140977
