### ISSUE TITLE
Fixer for ensuring a space between short open tag and code

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#2671]
Want to be able to turn this:

`<?echo 1;`

into

`<? echo 1;`

**Comment by keradus** [comment]
Hi 

did you tried `full_opening_tag` ?

**Comment by ntzm** [comment]
I want to keep the short tag, just force it to put a space in between the short tag and the rest of the code

**Comment by keradus** [comment]
then :-1:
it's a bad practice to use short open tag, thus I'm against a rule that would support it

**Comment by ntzm** [comment]
IMO it's not bad practice, `<? if ($x): ?>` looks a lot better than `<?php if ($x): ?>`

**Comment by julienfalque** [comment]
Using short tag *is* a bad practice because it is not enabled by default, so it reduces code portability.

**Comment by GrahamCampbell** [comment]
I'd say it's a bad practice to do templating in PHP. Use something better such as twig. :P

**Comment by ntzm** [comment]
Agreed, we want to move to a templating language in the future, but we're stuck with PHP for the time being

**Comment by SpacePossum** [comment]
Based on discussion there is not much support for this fixer. This means that we don't want to add it to the repo as it would cost us time to review, maintain, document and such while there is not a user base to help with that.
Thank you for the suggestion @ntzm :+1: ,
kindly note; you can still make a custom fixer and add it to your configuration for the project you want it for.

**Comment by ntzm** [comment]
No worries, thanks for taking the time :)
