### ISSUE TITLE
Fixer for removing useless parent method calls

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#2673]
Should turn this:

```php
<?php

class Foo extends Bar
{
    /**
     * Do the thing
     */
    public function baz($a, $b, $c)
    {
        // Call the parent
        return parent::baz($a, $b, $c);
    }
}
```

into this:

```php
<?php

class Foo extends Bar
{
}
```

but leave this untouched:

```php
<?php

class Foo extends Bar
{
    /**
     * Do the thing
     */
    public function baz($a, $b, $c)
    {
        return parent::baz($a, $b, 123);
    }
}
```

**Comment by keradus** [comment]
very edge case, as it's not happening often

still, if you want, please provide proposal PR.
otherwise I am afraid that your feature won't be prepared for anyone soon

**Comment by SpacePossum** [comment]
I would say it is to rare to be a fixer in this repo. The only case is see sometimes IRL are that some dev. think it is needed to add empty constructors or constructors only calling their parent.

**Comment by julienfalque** [comment]
Invisible characters are very rare too, but we have a fixer for that now :)

**Comment by ntzm** [comment]
If nobody thinks it's needed, that's fine. Just wanted to see if anybody is in need of this

**Comment by SpacePossum** [comment]
Sorry man (@ntzm), it seems your idea is not popular enough to make it to add as a fixer at this repo.
We select fixers to be added here based on popularity as it will give as rough idea about how much people will use it, help out maintain it, etc., which, unfortunately, means some don't make it.

Your case is still valid and could be done, so if you need it go for it, you can always run custom fixers! :)

**Comment by ntzm** [comment]
No worries, thanks for considering and for this awesome project
