### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by vanbogaertjonas** [FriendsOfPHP/PHP-CS-Fixer#2683]
Hi guys,

Simple question;
Is it possible to scan php code based files with other extensions (install, module, inc)?

**Comment by keradus** [comment]
by extension you mean file extension? then yes, it is. make a config file and set up `finder` (eg Symfony Finder) that matches your requirements.

**Comment by vanbogaertjonas** [comment]
Thanks!

**Comment by keradus** [comment]
Glad to help ;)
Closing due to discussion
