### ISSUE TITLE
strict_param should be part of Symfony:risky, not Symfony

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2689]
Using PHP-CS-Fixer 2.2.1, enabling the `@Symfony` ruleset triggers an error saying that `strict_param` is a risky fixer and risky fixers are not allowed.
It should be moved to the `@Symfony:risky` ruleset instead.

**Comment by stof** [comment]
Closing this, it was my own config, not the Symfony ruleset. I looked too fast

**Comment by stof** [comment]
The example given in the doc for the `.php_cs` config file is broken though, as it enables `strict_param` without enabling risky fixers

**Comment by keradus** [comment]
yeah, example is not activating risky flag as with copy-paste of example one may just ignore it. it's possible to set allowance not only in config file, but also as CLI param
