### ISSUE TITLE
Update README regarding risky tests

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#2690]
Ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2689#issuecomment-293840492

Also, the documentation does not mention the `setRiskyAllowed` method at all, it would be a nice addition.

**Comment by SpacePossum** [comment]
The doc clearly states an instance of `PhpCsFixer\ConfigInterface` must be returned, which is a pointer to all its methods including `setRiskyAllowed`. I see no update needed on this topic.

However `Please be aware that this feature is experimental.` is something we can drop, as this is done and stable?

**Comment by keradus** [comment]
it's stable
