### ISSUE TITLE
Doctrine annotation space fixer is breaking things

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2692]
The fixer is clearing tokens of type `T_NONE`. But it does not check first that these tokens are actually containing spaces only.
This is the main reason why Behat annotations are required to be ignored by this fixer (see #2691): the fixer is clearing tokens containing `^` or `+` when encountering a Step regex with a brace in it, thus breaking the regex.

**Comment by julienfalque** [comment]
Which Doctrine Annotation fixer is doing that? Could you provide an example of what it breaks?

**Comment by stof** [comment]
Here is the diff generated by the `doctrine_annotation_space` fixer on the Behat annotation:

```diff
     /**
-     * @Transform /^(\d+)$/
+     * @Transform /(\d)$/
      */
     public function castStringToNumber($string)
```

As you can see here, it is clearing `T_NONE` annotation tokens which are *not* whitespaces when detecting there should be no whitespaces around the parenthesis

**Comment by julienfalque** [comment]
Ok, this annotation should definitely not be affected by the fixer, I'll have a look at it.
