### ISSUE TITLE
The doctrine annotation space fixer should not add spaces before colons for assignments

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2693]
while adding spaces on both sides of `=` may make sense (but why space around equals in arrays and no spaces around assignments ? this is a weird rule), I think that `:` in arrays should have a space only after it, not before, to match common JSON conventions (the syntax using `:` is inspired by JSON after all)

**Comment by julienfalque** [comment]
> why space around equals in arrays and no spaces around assignments ?

I couldn't find official conventions about this so I looked at [Doctrine Annotation documentation](http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html) and [Symfony documention](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html). Most of the time, they have no space for argument assignments but spaces before and after array assignment. I applied the same rule for array assignments using a colon

> I think that : in arrays should have a space only after it, not before, to match common JSON conventions

This behavior could be tweaked by introducing new configuration options to the fixer.

**Comment by stof** [comment]
Then OK for spaces around `=` in arrays. But none of these documentation pages are using `:` (because it was added only after they were written). And the PR adding support for it was precisely about making it more similar to JSON.

**Comment by julienfalque** [comment]
I wasn't aware of that, makes perfect sense.

**Comment by julienfalque** [comment]
Closing as #2770 was merged.
