### ISSUE TITLE
useless else fixer should also convert elseif to if when possible

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2695]
When the `else` part of a `elseif` is useless, the fixer should turn it into a `if`

**Comment by stof** [comment]
rule to determine it is useless:

- all previous `if` of the chain broke the execution path (`return`, `continue`, `throw`, `break`, ...)
- it is the last path in the chain (no `else` or `elseif` after it).

Note that the second part of the condition needs to be checked again for previous conditions of the if/elseif chain once a useless else is fixed (as the previous `elseif` becomes the last one)

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2885 IIUC , please reopen if not so (ping @stof cc @julienfalque )
