### ISSUE TITLE
OrderedImportsFixer - Not configuring the import type sorting still sort by type when using alpha sorting

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2696]
The comments in the code are telling me that using `null` for the `importsOrder` rather than an array is expected to sort all imports together without grouping them by type.

while this seems true for length sorting AFAICT (I haven't tried it to check it), it is **not** true for alpha sorting, as `sortAlphabetically` starts by comparing the import type.
So for alpha sorting, `null` in `importsOrder` actually enforces `array('class', 'const', 'function')`, and there is no way to enforce it.

Is it really the expected behavior ? Or just a bug ?

**Comment by SpacePossum** [comment]
Confirmed; 
with fixer `sorting alpha` and `null` as `order`;

Input
```php
<?php
use const some\b\{ConstB};
use const some\b\{ConstA};
use Z\Y;
use Z\X;
use function some\b\{fn_a, fn_b};
use function some\a\{fn_a, fn_b};
```
Output
```php
<?php
use Z\X;
use Z\Y;
use const some\b\{ConstA};
use const some\b\{ConstB};
use function some\a\{fn_a, fn_b};
use function some\b\{fn_a, fn_b};
```
and not;
```php
<?php
use const some\b\{ConstA};
use const some\b\{ConstB};
use Z\X;
use Z\Y;
use function some\a\{fn_a, fn_b};
use function some\b\{fn_a, fn_b};
```

The question is; if no order is defined, how to fix the following;
```php
<?php
use const some\b\{ConstB};
use const some\b\{ConstA};
use ZZ\Y;
use ZZ\X;
use function some\b\{fn_a, fn_b};
use function some\a\{fn_a, fn_b};
use AZ\Y;
use AZ\X;
```

move the classes from `ZZ` NS to the end, or move the `AZ` NS ones above `ZZ` NS ones?
Or, using another example; if no grouping is used at all, is something like this wanted;
```php
<?php
use const A\b\{ConstB};
use B\A;
use const C\b\{ConstB};
use D\A;
use function E\a\{fn_a, fn_b};
```

**Comment by stof** [comment]
Well, if you don't enable grouping, I would say that the last snippet is acceptable (btw, it is what PhpStorm creates when adding imports automatically).

and if you use length sorting rather than alpha sorting, you indeed end up with a list mixing different types of imports, as grouping is not apply at the sorting level for it.

**Comment by SpacePossum** [comment]
Alright, all clear what option is missing ATM, thanks :)

**Comment by stof** [comment]
currently, `alpha` + `null` and `alpha` + `array('class', 'const', 'function')` are doing exactly the same (through different code paths).
In the second case, grouping is totally expected (as it was requested). But I think the first case should not apply grouping (making it consistent with the behavior of `length` + `null`)

**Comment by SpacePossum** [comment]
Agreed, however since this configuration option is already released it would be a BC break to change it. I propose to use different option value to get the result.

**Comment by keradus** [comment]
no, `alpha + null` shall not do the grouping. if it does, it was wrongly introduced BC breaker and we need to fix it.

**Comment by SpacePossum** [comment]
This wasn't introduced as BC breaker, `alpha + null` has always done this grouping AFAIK (as before that the fixer would break on the PHP 7 code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1989))

**Comment by stof** [comment]
@SpacePossum but then, `null` does not have the same behavior for length and alpha sorting.
Looks like the PR 1989 decided to always apply grouping.

A solution to keep BC could be to change the *default* grouping to keep the existing one (forcing people to disable grouping by setting null)
