### ISSUE TITLE
no_extra_consecutive_blank_lines removes line between cases when it throws

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2697]
When the last line of a `case` is using `throw` rather than `return`, `break` or `continue`, the `no_extra_consecutive_blank_lines` removes the empty line between this case and the next one. But it does not do it for other constructs. This looks like a bug to me. there is no reason to forbid empty lines between cases only when throwing.

**Comment by SpacePossum** [comment]
Hmm sounds odd indeed, do you have sample?

**Comment by stof** [comment]
Existing code (part of a bigger file defining a class):

```php
    /**
     * @return Node
     */
    private function parsePrimaryExpression()
    {
        $token = $this->stream->getCurrent();

        switch ($token->getType()) {
            case Token::NAME_TYPE:
                $this->stream->next();

                if ('(' === $this->stream->getCurrent()->getValue()) {
                    if (!isset($this->functions[strtolower($token->getValue())])) {
                        $errorKey = count($this->functions) ? 'formula.unrecognized_function' : 'formula.no_registered_functions';

                        throw new SyntaxError($errorKey, array(
                            '%name%' => strtoupper($token->getValue()),
                            '%functions_list%' => implode(', ', array_map('strtoupper', array_keys($this->functions))),
                        ));
                    }

                    $arguments = $this->parseArguments();
                    $node = new FunctionNode($token->getValue(), $arguments);

                    //Throws a Syntax Error if the node is not validated
                    $this->functions[$node->getAttribute('name')]->validateNode($arguments, $this->context);

                    return $node;
                }

                throw new SyntaxError('formula.missing_arguments_opening_parenthesis');

            case Token::NUMBER_TYPE:
            case Token::STRING_TYPE:
                $this->stream->next();

                return new ConstantNode($token->getValue());

            default:
                throw new SyntaxError('formula.unrecognized_characters');
        }
    }
```

and here is the generated diff:

```diff
                 }
 
                 throw new SyntaxError('formula.missing_arguments_opening_parenthesis');
-
             case Token::NUMBER_TYPE:
             case Token::STRING_TYPE:
                 $this->stream->next();
```

It removes the line after `throw`, but not after `return` for the next case

**Comment by SpacePossum** [comment]
The removal of the line after the `throw` and `return` is done by configuration and I consider it therefor not a bug.
I would like to a new configuration option for the `NoExtraConsecutiveBlankLinesFixer` to remove blank lines above `case` and `default` Tokens. That would make it possible to fix all cases in a `switch` consistent.

**Comment by stof** [comment]
but line is **not** removed after `return` in this case.

**Comment by SpacePossum** [comment]
thanks, that is a bug than :+1:

**Comment by SpacePossum** [comment]
for ref.: so not a bug, but the result of confusion/misunderstanding and configuration, more details in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2701

**Comment by SpacePossum** [comment]
I don't see anything left to do here, the new options can be used to fix the white lines consistently.
If I missed a case, please provide a new sample and I'll have a look.
