### ISSUE TITLE
ordered_imports ignores indentation

### ISSUE THREAD

**Issue by pilgerone** [FriendsOfPHP/PHP-CS-Fixer#2712]
With `ordered_imports = true` but `single_import_per_statement = false`, the fixer messes up the indentation on PHP 7.1. For example:
Original:
```
<?php

namespace Foo\Bar;

use Foo\Bar\Baz\{
    C,
    B,
    D,
    A
};
```
Expected:
```
<?php

namespace Foo\Bar;

use Foo\Bar\Baz\{
    A,
    B,
    C,
    D
};
```
Actual:
```
<?php

namespace Foo\Bar;

use Foo\Bar\Baz\{A, B, C, D};
```
Might seem harmless but becomes a real problem with big namespaces and class names.

I'm willing to take a swing at this one. Should I do a PR with some tests and attempt a change to the fixer?

**Comment by SpacePossum** [comment]
>Should I do a PR with some tests and attempt a change to the fixer?

Would be awesome. The Fixer is a bit tricky (or at least an odd duck) when it comes to fixing the code. Feel free to give it a shot!
