### ISSUE TITLE
How to use short array syntax with and IDE like PHPStrom

### ISSUE THREAD

**Issue by valeryan** [FriendsOfPHP/PHP-CS-Fixer#2716]
The article linked at the bottom of your readme that explains how to use the PHP-CS-Fixer with PHPStorm is very out of date. I am able to setup the IDE using the new `--rules` argument but I can't figure out how to use the array_syntax in short mode through the external tools in PHPStorm or on the cmd line in windows. 

This is my setup that works.
![phpcsfixerset](https://cloud.githubusercontent.com/assets/1508761/25297971/d46d5ea8-26b6-11e7-99ee-cf7e7ab04eba.png)

Now that everything is configured through `--rules` is there no equivalent to `short_array_syntax` anymore?

 I have tried using Json but that causes the tool to throw errors. I can't use json on the cmd line either because I am on windows and it really does not seem to like json in the arguments. 

In Power Shell
```
php-cs-fixer fix 'SomeFile.php' --verbose --rules='{"@PSR2": true, "ordered_impor_unused_imports": true, "array_syntax": {"syntax": "short"}}'

Loaded config default.
Using cache file ".php_cs.cache".

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  Invalid JSON rules input: Syntax error.
```

In Cmd Or with PHP Storm External Tool
```
php-cs-fixer fix SomeFile.php --verbose --rules='{"@PSR2": true, "ordered_imports": true, "ordered_class_elements": true, "no_unused_imports": true, "array_syntax": {"syntax": "short"}}'

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  The path "true," is not readable.

```

**Comment by SpacePossum** [comment]
Hi!

I did a few tests and for example this is working for me:

```bash
$ php-cs-fixer fix --verbose --rules='{"@PSR2": true, "ordered_imports": true, "no_unused_imports": true, "array_syntax": {"syntax": "short"}}' 'test.php'
```
(on default terminal of Ubuntu desktop)

You might want to try out moving the path(s) to fix to the end and using diff. quotes based on the CLI used.

The links we provide for IDE's support are indeed dated and most are still based on the 1.x line.
Would be nice to update (if there are up to date sources) or remove those.

**Comment by SpacePossum** [comment]
(As alternative you could create a config file for the fixer in `$ProjectFileDir$` with all the rules, then you don't need to configure all those on the command.)

**Comment by valeryan** [comment]
Thanks for the info. I don't have any issues with using php-cs-fixer on linux. If I copy what you have above and try to run it in cmd.exe I get this:

```
php-cs-fixer fix --verbose --rules='{"@PSR2": true, "ordered_imports": true, "no_unused_imports": true, "array_syntax": {"syntax": "short"}}' 'test.php'


  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  The path "true," is not readable.


Exception trace:
 () at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:349
 PhpCsFixer\Console\ConfigurationResolver->PhpCsFixer\Console\{closure}() at n/a:n/a
 array_map() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:357
 PhpCsFixer\Console\ConfigurationResolver->getPath() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:512
 PhpCsFixer\Console\ConfigurationResolver->computeConfigFiles() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:210
 PhpCsFixer\Console\ConfigurationResolver->getConfig() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:560
 PhpCsFixer\Console\ConfigurationResolver->getFormat() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:405
 PhpCsFixer\Console\ConfigurationResolver->getReporter() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php:144
 PhpCsFixer\Console\Command\FixCommand->execute() at C:\Users\shils\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:262
 Symfony\Component\Console\Command\Command->run() at C:\Users\shils\AppData\Roaming\Composer\vendor\symfony\console\Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\shils\AppData\Roaming\Composer\vendor\symfony\console\Application.php:190
 Symfony\Component\Console\Application->doRun() at C:\Users\shils\AppData\Roaming\Composer\vendor\symfony\console\Application.php:121
 Symfony\Component\Console\Application->run() at C:\Users\shils\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\php-cs-fixer:55

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

So I am interested in setting up the config file and trying that out. I have not been able to find much documentation on the config file though. Would I remove the `--rules` argument all together and add a `--config` that point to the config file?  I use this tool on multiple projects so having a central config file would be useful but I am not sure what to put in the config. 

Also, once I get it all working on PHPStorm I can post an article detailing my setup and how it works on medium so you guys can have a refreshed link for PHPstorm. 

Thanks

**Comment by GrahamCampbell** [comment]
Looks like you are running an old version of php-cs-fixer.

**Comment by SpacePossum** [comment]
I think @GrahamCampbell is right, you need at least 2.1.0 to pass configuration using json format from the command line after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2494 .
@valeryan please let us know what version you are using on Windows.

On using a configuration file, you can pass the location of the using `--config` something like;
>php-cs-fixer fix --config=.php_cs.dist

the fixer will look for this file by default in the current working directory.
For an example of how such a file looks like please have a look at the one we use in the repo ourselves;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.3.0/.php_cs.dist

**Comment by valeryan** [comment]
C:\Users\shils>php-cs-fixer --version
PHP CS Fixer 2.2.1 by Fabien Potencier and Dariusz Ruminski

The issue with the json on windows is that it appears that cmd.exe strips out the double quotes. Which causes the json to not parse correctly.

**Comment by valeryan** [comment]
Sorry accidentally hit close.

**Comment by SpacePossum** [comment]
Thanks for reporting back @valeryan (no worries about close/reopen)
As I do not have a Windows setup at hand ATM I'm going to ping @keradus as I think he might have and as such will be able to test and help more than I can (this might be after the weekend though, but we'll get there).

**Comment by valeryan** [comment]
No problem, I appreciate all the help. I am going to try the config setup. I have not been on windows for a long time but my team recently switched to windows for our new project so my tooling is out of sorts but fixer is a must for me to get working. Can't live without it.

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/2829600/25307261/ba53e3f4-2795-11e7-84e5-8d2107b0d284.png)

**Comment by valeryan** [comment]
@GrahamCampbell thanks, I updated a few minutes ago to v2.3... apparently I could not fix a fundamental flaw in windows cmd.exe by updating php-cs-fixer. Its is still stripping the double quotes from the Json. However, I am having success with switching to the config file, so I guess that is the only doable path on windows currently.

**Comment by keradus** [comment]
New feature release is not connected anyhow to this for sure.

On the Windows machine I stronly advise to not use `cmd.exe` nor `command.exe`. use 3rd party consoles like `cmder` (on that the syntax I use on Ubuntu machine works normally) or PowerShell. Finally, you could use Ubuntu on Windows (feature from Microsoft directly): https://gallery.dpcdn.pl/imgc/News/72164/g_-_-x-_-_-_72164x20160409203541_1.png

Anyway, after all that possibilities, I would stronly advise to just use config file, as you ended up with ;)

So, coul we close this one ?

**Comment by valeryan** [comment]
Yep, we can close it. PHPstorm's external tool system that allows it to use PHP-CS-Fixer uses cmd.exe unfortunately. To get this to work on Windows with PHPStorm it looks like a config file is the best and maybe only option. I am writing up a blog post that details how to get this all setup in PHPStorm and I will link it here when I am done. You guys can use it if you want or not. Thanks for all the help.

**Comment by keradus** [comment]
great to hear ;) eager to see a blog article ;)

**Comment by valeryan** [comment]
@keradus here is the link to the article. Maybe it will be helpful to some. https://medium.com/@valeryan/how-to-configure-phpstorm-to-use-php-cs-fixer-1844991e521f

**Comment by keradus** [comment]
@valeryan , few suggestions

please fix in your article:
```diff
-php_cs.dis
+php_cs.dist
```



Also, as you configured tool to fix given `$FileName$`, it may happen that given file is excluded by config file. but then one passed file directly as CLI arg, so it would override finder in config file. but one configured to not fix it. I would respect that adding `--path-mode=intersection`.

-----

Would you consider opening a PR and replacing old article with your new shiny one ? :)

**Comment by FeBe95** [comment]
Solution for Powershell: Add escaped backticks (`) in front of double quotes and pass parameter with double quotes instead of single quotes:
```PowerShell
php-cs-fixer fix 'SomeFile.php' --verbose --sequential --rules="{\`"@PSR2\`": true, \`"ordered_imports\`": true, \`"no_unused_imports\`": true, \`"array_syntax\`": {\`"syntax\`": \`"short\`"}}"
```

Beware: Does not work with parallel runner as of today:
```
[PhpCsFixer\Runner\Parallel\WorkerException]                                                                              
[PhpCsFixer\Runner\Parallel\ParallelisationException] Unable to create runner: Invalid JSON rules input: "Syntax error". 
```

**Comment by Wirone** [comment]
@FeBe95 why not:

```
php-cs-fixer fix 'SomeFile.php' --verbose --sequential --rules='{"@PSR2": true, "ordered_imports": true, "no_unused_imports": true, "array_syntax": {"syntax": "short"}}'
```

Single outer quotes, which means all inner quotes can be double = valid JSON. Doesn't it work on Windows (can't check)?
