### ISSUE TITLE
[Fixer suggestion] Magic Number Detector

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#2719]
Today I've noticed Magic Number Detector package in trending packages: https://github.com/povils/phpmnd

It could be easy to port it to sniff, since it uses PHP-Parser:
https://github.com/povils/phpmnd/blob/master/src/Visitor/DetectorVisitor.php

**Comment by SpacePossum** [comment]
Hi,
That is a nice snif and I use it (through other tooling but still ;) ). 
I do wonder though, what detected cases do you think we could fix automatically within in reasonable "risky" limits?

**Comment by TomasVotruba** [comment]
Hey, what other tool has it?

Well, that's a tough question :) fixing values to constants except those mentioned in readme - 2, 1, -1 - might be useful.

**Comment by keradus** [comment]
Then, let us make it official.

@povils, you came up with nice tool. Would you like to incorporate it into PHP CS Fixer?
The main change IMO would be changing the parser (from nikic into build-in)

**Comment by povils** [comment]
Hey, firstly I'm glad that you liked it :)

Secondly, are you sure that PHPMND is a good fit for PHP-CS-FIXER? I mean  PHP-CS-FIXER is more Coding Standard sniffer/fixer tool and my tool is more about clean code and good practices :)
What do you think guys?

**Comment by keradus** [comment]
we do some good practices as well, like `==` -> `===` or upgrading used php syntax (like ** operator)

**Comment by TomasVotruba** [comment]
I thinks it fits great.

Coding Standard nowadays is very wide term even for refactoring and code upgrading in some cases. Not just tabs and spaces as it used to be :)

**Comment by keradus** [comment]
> Not just tabs and spaces as it used to be :)

I think we just have that great tools in PHP world, wouldn't say it about all languages... :(

**Comment by TomasVotruba** [comment]
Sure, of course in scope of PHP, as this is PHP tool.

**Comment by TomasVotruba** [comment]
Not relevant any more. Feel free to reopen with PR
