### ISSUE TITLE
Requested for help with  first fixer 

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#2756]
Hey, I'm writing my first fixer and I'm lost.

[Cookbook is only for removing](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/COOKBOOK-FIXERS.md), but I want to add or rather replace some content.

**Fixer is fixing content the way I need, tests are passing on content, but failing due to some token inqeuality**. Not sure how is that possible.
I've used similar approach to `VisibilityRequiredFixer`, but with no success. I work on it for 4 hours and I'm frustrated, because don't understand errors I get.

**Could I please ask somebody of you to look on that?**

- Error in Travis: https://travis-ci.org/Symplify/Symplify/builds/229501601#L394-L411

- Fixer:
 https://github.com/Symplify/Symplify/pull/165/commits/2b57db63d569cf1e92b02e0943814790e88032c4#diff-77b0aab940d6b4e15bf451af42434261

- I change content in this line:  https://github.com/Symplify/Symplify/pull/165/commits/2b57db63d569cf1e92b02e0943814790e88032c4#diff-77b0aab940d6b4e15bf451af42434261R75

Please, **comment there on particular lines**. Thank you!

**Comment by keradus** [comment]
https://github.com/Symplify/Symplify/pull/165/commits/2b57db63d569cf1e92b02e0943814790e88032c4#r115126738

**Comment by keradus** [comment]
as you have referred to `visibility_required` rule, here's example of inserting tokens:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.2.0/src/Fixer/ClassNotation/VisibilityRequiredFixer.php#L177-L178

**Comment by TomasVotruba** [comment]
I think I've tried that too, but had another issue. I will try to change it

**Comment by keradus** [comment]
closing here as this is not an issue with package. let us keep discussion in one place - either place of your code or gitter chat
