### ISSUE TITLE
RFE: add option to exit with non-zero if changes were made

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#2762]
Hi,

I would like to have (commandline) option to make program exit non-zero if changes were made by fixer.

The thing is that i want to integrate the tool to run automatically in Git `pre-commit` hook
and the commit must be aborted so user can review changes and stage again.

PS: `fixer fix $file && git add  $file` is not solution here, user may be using line based staging and `git add` would stage whole file.

PS2: `--stop-on-violation (Stop execution on first violation)` also is not the solution, as i want the fixes actually being applied.

**Comment by keradus** [comment]
Use dry-run + diff. Then, you will have non-zero exit code on violations, and will be able to review the violations.
Then, user could apply them automatically via fix or manually change the code.
If you want other, edge behaviour to fit your hook, it's responsibility of hook to provide it.
New flag is not an option.

**Comment by glensc** [comment]
duplicate run is counter productive, php-cs-fixer is very slow to consider duplicate runs.

**Comment by SpacePossum** [comment]
`--stop-on-violation` should prevent doing more that one complete run, together with caching it should perform pretty well unless a single commit has a lot changes.
I'm still +0 for adding this, however the topic has been raised a few times recently and each time the result was the same (i.e. not adding it), therefor I don't see this happen any time soon.
