### ISSUE TITLE
IndentationTypeFixer - fixes white space that is not part of indention

### ISSUE THREAD

**Issue by Arctic76** [FriendsOfPHP/PHP-CS-Fixer#2767]
Hello guys!

It seems I can't get the "binary_operator_spaces" rule working in my config.
When I activate this rule, it is working well the first time I save ("Fix on save" option on VSCode), but then if I try to fix the file again or to save it, the rule detects that the previous work is not enough and add indentation again... so it breaks everything :/..
In my mind i think because I have tabs enabled instead of spaces, so may be it makes conflicts?

My PHP version is:
```
PHP 5.6.30 (cli) (built: May 10 2017 14:28:57) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
My OS is `MAC OS Sierra 10.12.4 (16E195)`.
My editor is VSCode, using the PHP CS Fixer extension [link](https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer).
My PHP CS fixer version is: `PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski`.

My config for the rules:
```
return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => ['header' => $header],
        "@PSR1"                                 => true,
        '@PSR2'                                 => true,
        'binary_operator_spaces'                => ['align_double_arrow' => true, 'align_equals' => true],
        'blank_line_after_opening_tag'          => true,
        'braces'                                => ['position_after_functions_and_oop_constructs' => 'same'],
        'concat_space'                          => ['spacing' => 'one'],
        'hash_to_slash_comment'                 => true,
        'linebreak_after_opening_tag'           => true,
        'method_separation'                     => true,
        'no_blank_lines_after_class_opening'    => true,
        'no_empty_comment'                      => true,
        'no_empty_phpdoc'                       => true,
        'semicolon_after_instruction'           => true,
        'indentation_type'                      => true,
    ])
    ->setIndent("\t")
    ->setLineEnding("\n")
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('tests/Fixtures')
            ->in(__DIR__)
    )
;
```
VSCode config:
```
{
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.config": ".vscode/.php_cs",
    "php-cs-fixer.autoFixBySemicolon": true,
}
```

Code sample after written
```
public function myFunction() {
	$foo = 1;
	$looooongVar = 2;
	$middleVar = 1;
}
```
Code sample after 1st fix
```
public function myFunction() {
	$foo         = 1;
	$looooongVar = 2;
	$middleVar   = 1;
}
```
Code sample after 2nd fix...
```
public function myFunction() {
	$foo		       = 1;
	$looooongVar = 2;
	$middleVar   = 1;
}
```

Thanks in advance, tell me if you need more information!

**Comment by ntzm** [comment]
Does this affect `=>` as well or just `=`?

**Comment by SpacePossum** [comment]
my guess, all operators

**Comment by Arctic76** [comment]
@ntzm I didn't notice this behavior on => but maybe it's also the same result.

**Comment by SpacePossum** [comment]
the bug is in the `indentation_type` fixer, that blindly replaces all the `     ` to `\t`

**Comment by SpacePossum** [comment]
related;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2650
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2679/
