### ISSUE TITLE
[Announcement] Online fixers viewer and configurator

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#2784]
@keradus contacted me after [a post of mine](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2508#issuecomment-300815421), so I thought to post here to involve other people that may be interested too.

Thanks to #2500, we now have the possibility to get detailed info about the fixers via PHP code, so I thought it would be nice to have an online tool to help us all to better use/understand PHP-CS-Fixer.

That's why I created [PHP-CS-Fixer Configurator](https://mlocati.github.io/php-cs-fixer-configurator/) (source code [here](https://github.com/mlocati/php-cs-fixer-configurator)).

It allows you to:
- view all the fixers in a clean (and pretty?) way
- search fixers by name/description/preset
- view details about every fixer (including options and examples)
- generate configurations in PHP code (ready to be saved as a `.php_cs`/`.php_cs.dist` file) and in JSON format
- load configurations defined in JSON format (useful in collaborative environments)

**Comment by SpacePossum** [comment]
nice work :D  :heart:  :+1:

**Comment by sakonachhoeurng** [comment]
Thanks @mlocati for sharing, look nice!

**Comment by shakaran** [comment]
I think that could be a nice thing add a reference to this in the README file of this repo, so everyone that read the initial docs could know about this

**Comment by julienfalque** [comment]
Thanks @mlocati for sharing this, looks awesome!

I'm closing this issue as it's neither a feature request nor a bug report. Feel free to continue the discussion if you want to share more informations or news about it :)

**Comment by mlocati** [comment]
:+1:

**Comment by mlocati** [comment]
I just updated https://mlocati.github.io/php-cs-fixer-configurator
- it's now possible to now choose the PHP-CS-Fixer version you prefer (from 2.3.0 to 2.5.0)
- a help dialog is now available, showing what the configurator can do both in *View Mode* and in *Configuration Mode*

**Comment by keradus** [comment]
2.2 is LTS, it could be nice to support it as well

**Comment by SpacePossum** [comment]
looking better every time, nice update @mlocati :+1:

**Comment by mlocati** [comment]
> 2.2 is LTS, it could be nice to support it as well

@keradus :+1: Done

**Comment by keradus** [comment]
@mlocati IMO you could drop all the patch versions except latest ones.
the only difference between patch-releases of same minor would be a typo fixes and so

**Comment by mlocati** [comment]
@keradus thanks for the hint! Done

**Comment by mlocati** [comment]
Just a site note: I added a new feature to https://mlocati.github.io/php-cs-fixer-configurator
In the versions dropdown menu you can now find a new "Compare versions" item, which displays the changes between PHP-CS-Fixer versions.

**Comment by keradus** [comment]
doesn't look to be fully proper.
eg
> The `commentType` option has been removed

it was not. it was only deprecated

**Comment by mlocati** [comment]
> doesn't look to be fully proper.
> > The `commentType` option has been removed
> 
> it was not. it was only deprecated

The configurator didn't handle option aliases. This is now fixed.
Thanks for the tip!

**Comment by mlocati** [comment]
@keradus what about adding a link to https://mlocati.github.io/php-cs-fixer-configurator/ to the PHP-CS-Fixer `README.rst` file?

**Comment by mlocati** [comment]
Just an update about https://mlocati.github.io/php-cs-fixer-configurator: it now displays the history of a fixer.
See for example the history of [`final_internal_class`](https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:final_internal_class):

![immagine](https://user-images.githubusercontent.com/928116/99684034-47484b00-2a81-11eb-9b0e-4d9e2deae0d7.png)
