### ISSUE TITLE
.php_cs wont override default settings for 'blank_line_after_opening_tag'

### ISSUE THREAD

**Issue by jluisgarcia** [FriendsOfPHP/PHP-CS-Fixer#2791]
Hi,
I have tried many times to override the default behavior of 'blank_line_after_opening_tag', using this short .php_cs config file:

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@Symfony' => true,
        'blank_line_after_opening_tag' => false
    ))
    ->setFinder($finder)
;
```

I have placed it in the project root and when I set: '@Symfony' => false, it does disable it altogether. Meaning that I have access to the config file.
But when I put everything back to the way it is above, in the .php_cs file, it makes a blank line again.

PHP version:  7.1.1

PHP CS Fixer version: php-cs-fixer-v2.phar (latest)

Thanks.

**Comment by keradus** [comment]
Please provide full issue report:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE

**Comment by jluisgarcia** [comment]
PHP version: 7.1.1

PHP CS Fixer version: php-cs-fixer-v2.phar (latest)

Here is the blank line I dont want. (see red arrow)
It is a bit of a special case. Split PHP code

![initial_state](https://cloud.githubusercontent.com/assets/24752182/26330431/255534c8-3f4c-11e7-83ec-d07272d2a695.png)

**Comment by shakaran** [comment]
@jluisgarcia I try to reproduce your bug, but it seems that works fine to me:

.php_cs file:

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@Symfony' => true,
        'blank_line_after_opening_tag' => false
    ))
    ->setFinder($finder)
;
```

Original file:

```
	<?php
	if (have_post()) {
	    while (have_post()) {
	        the_post(); =>
	        
	        // html code here
	        
	        <?php
	        
	    } // end while
	}} // end if
	?>
```

Result file:

```
	<?php
    if (have_post()) {
        while (have_post()) {
            the_post(); ?>
	        
	        // html code here
	        
	        <?php
        } // end while
    } // end if
    ?>
```

```
diff --git a/index.php b/index.php
index 57f91f4..e3d2676 100644
--- a/index.php
+++ b/index.php
@@ -1,12 +1,11 @@
        <?php
-       if (have_post()) {
-           while (have_post()) {
-               the_post(); =>
+    if (have_post()) {
+        while (have_post()) {
+            the_post(); ?>
                
                // html code here
                
                <?php
-               
-           } // end while
-       }} // end if
-       ?>
+        } // end while
+    } // end if
+    ?>
```

**Comment by SpacePossum** [comment]
@shakaran thanks for testing, however I think the report is for the other way around;

input:
```php
<?php
while ($a) {
    ?>

    <?php // a line below here should _not_ be added
}
```

config:
```php
return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
        ->setRules(array(
        '@Symfony' => true,
        'blank_line_after_opening_tag' => false
    ))
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('tests/Fixtures')
            ->in(__DIR__)
    )
;
```

causes _no_ diff, so I _guess_ the configuration file is not used. To confirm this I would like to ask @jluisgarcia to give it a try and (as @keradus hinted) to provide the way you run the fixing command, thanks!
