### ISSUE TITLE
NoUselessElseFixer - bug: fixer brace logic

### ISSUE THREAD

**Issue by shmax** [FriendsOfPHP/PHP-CS-Fixer#2802]
Hi there, great project!

I recently ran the fixer on a large code base, and wound up with some subtle bugs. I tracked it down to this original code from my project (I've simplified it to the point where it's nonsensical, but still demonstrates the bug):
```php
function create_joins($value)
{
	$ret = '';

	if (stripos($value,'JOIN ') === false)
	{
		if (count($value))
		{
			$ret = "foo";
		}
		else
			throw new Exception("Value should not be empty");
	}
	else
		$ret .= $value;

	return $ret;
}
```
After running the fixer, I get:
```php
<?php

function create_joins($value)
{
    $ret = '';

    if (stripos($value, 'JOIN ') === false) {
        if (count($value)) {
            $ret = 'foo';
        } else {
            throw new Exception('Value should not be empty');
        }
    }

    $ret .= $value;

    return $ret;
}

```

You can see that the logic has changed; `$ret .= $value` now executes on every call of the create_joins function, whereas before it only executed when the `if` condition failed.

This is with:
```
PHP: 7.0.19
PHP-CS-Fixer: 2.3.1
```

And with the following `.php_cs.dist`:
```php
$finder = new PhpCsFixer\Finder();
$config = new PhpCsFixer\Config('json-schema', 'json-schema style guide');
$finder->in(__DIR__);
/* Based on ^2.1 of php-cs-fixer */
$config
    ->setRules(array(
        // default
        '@PSR2' => true,
        '@Symfony' => true,
        // additionally
        'array_syntax' => array('syntax' => 'short'),
        'binary_operator_spaces' => false,
        'concat_space' => array('spacing' => 'one'),
        'no_unused_imports' => false,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => true,
        'phpdoc_no_package' => false,
        'phpdoc_order' => true,
        'phpdoc_summary' => false,
        'pre_increment' => false,
        'trailing_comma_in_multiline_array' => false,
        'simplified_null_return' => false,
    ))
    ->setFinder($finder)
;
return $config;
```
Please advise.

**Comment by SpacePossum** [comment]
Hi, thanks for reporting!
By looking at the samples and digging in my mind I'm pretty sure this is done by the `NoUselessElseFixer and it is a bug.
Till the bug is fixed I advice to switch off the `no_useless_else` rule in your configuration.

**Comment by shmax** [comment]
Thanks, will do. By the way, I noticed that if I replace the `Throw` line with anything else it seems to work, so perhaps that's a clue.

**Comment by keradus** [comment]
very nice case to be fixed

**Comment by shakaran** [comment]
@keradus I think that the bug probably is [for this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/ControlStructure/NoUselessElseFixer.php#L133) since the else is cleared always when the do/while is finished, and in this case the last else don't should be cleared since there are a meaningful token available like the line  _$ret .= $value;_
