### ISSUE TITLE
How to remove empty lines?

### ISSUE THREAD

**Issue by UksusoFF** [FriendsOfPHP/PHP-CS-Fixer#2804]
Hi,
is there way to remove continuous empty lines more than one?

**Comment by keradus** [comment]
`no_extra_consecutive_blank_lines `

**Comment by peterpaul02** [comment]
I have the same issue 4 empty lines in the header.php. Please explain what I have to do with your suggested code? thanks for your help

**Comment by SpacePossum** [comment]
Hi @peterpaul02 ,

To help you maybe it is best to provide an example of what you want changed. You can ask us here;
https://gitter.im/PHP-CS-Fixer/Lobby
