### ISSUE TITLE
Simplify property declarations

### ISSUE THREAD

**Issue by petr-buchin** [FriendsOfPHP/PHP-CS-Fixer#2806]
Can I use php-cs-fixer to simplify such property declarations:

```php
private $myProperty = null;
private $yetOneProperty = null;
```

as follows ?

```php
private $myProperty;
private $yetOneProperty;
```

Thanks in advance!

**Comment by SpacePossum** [comment]
Hi!
Currently we've got a Fixer for this, however it shouldn't be a hard one to build.
Please let me know if you can help out, happy to help out :)

**Comment by petr-buchin** [comment]
@SpacePossum , it would be very nice to have this feature.

Unfortunately, for now I cannot help with this, but I will happy to help after first stable release of [MongoDB ODM](https://github.com/tequila/mongodb-odm), which is planned to the June, 2017. 
For now ODM is using [zend-code](https://github.com/zendframework/zend-code) lib, which generates pretty ugly code, for example always generates property like `private $property = null;`, i.e. with `null` default value, so I'm wondering whether there is a quick solution for this for the ODM users, before I release normal library for code generation :)

**Comment by SpacePossum** [comment]
Alright, no rush!
Lets see who can start on this first, you or I, and than we can get this fixer in.
Good luck with MongoDB ODM, looks promising :)

**Comment by petr-buchin** [comment]
@ntzm , @SpacePossum , @keradus, @julienfalque  - thank you guys!

**Comment by SpacePossum** [comment]
you're welcome @petr-buchin , enjoy the next release :)
