### ISSUE TITLE
NoLeadingImportSlashFixer is not working when namespace is missing

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#2813]
Due to [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Import/NoLeadingImportSlashFixer.php#L60) condition when namespace is missing NoLeadingImportSlashFixer won't work on file. According to [manual](http://php.net/manual/en/language.namespaces.importing.php):

> the leading backslash is unnecessary and not recommended, as import names must be fully qualified, and are not processed relative to the current namespace.

Can we update the fixer to always remove leading slash?

**Comment by SpacePossum** [comment]
Hi!

Do you mean changing something like
```
<?php

use \DateTime;
```

to 
```
<?php

use DateTime;
```

? I would not recommend removing the base namespace slash here

**Comment by julienfalque** [comment]
Why not? This looks like a bug to me, although there is an [explicit test case for this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixer/Import/NoLeadingImportSlashFixerTest.php#L52).

**Comment by SpacePossum** [comment]
>Why not? This looks like a bug to me, although there is an explicit test case for this.

because if you have `DateTime` in the same namespace as the code with the `use` import than changing from `use \DateTime` to `use DateTime` means you import a diff. class altogether.

**Comment by julienfalque** [comment]
This is not true because, as quoted from [manual](http://php.net/manual/en/language.namespaces.importing.php) by @kubawerlos:
> import names must be fully qualified, and are not processed relative to the current namespace.

so `use DateTime` is equivalent to `use \DateTime`, whatever the namespace this is declared in.

**Comment by kubawerlos** [comment]
@SpacePossum - it's exactly as @julienfalque said - there is no difference at all.

This is being problematic with OrderedImportsFixer and sorting alphabetically as all imports with leading slashes are moved before the ones without it. I'll make PR, but as enhancement or bugfix?

**Comment by SpacePossum** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/706#issuecomment-62686893
it seems this was done for a reason (so not a bug), didn't test it yet on all PHP versions we support

**Comment by julienfalque** [comment]
The warning in linked comment seems to occur both [with](https://3v4l.org/b5QC6) and [without](https://3v4l.org/LeOiF) the leading slash.

**Comment by kubawerlos** [comment]
@julienfalque seems that way. So removing the leading slash without namespace won't break anything ain't broken, right? Will only help with "namespaced" import.

Maybe extending NoUnusedImportsFixer to remove imports causing the warning is a way to go?

**Comment by kubawerlos** [comment]
So, summarizing:

if we are in [global space](http://php.net/manual/pl/language.namespaces.global.php) - which means we haven't defined any namespace - trying to import any other class from global space will result with `Warning: The use statement with non-compound name ...`, no matter if we added leading slash or not (as @julienfalque [demonstrated](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2813#issuecomment-304971103)).

@fabpot @keradus would you accept PR to change NoLeadingImportSlashFixer so it removes all leading import slashes? Or extending NoUnusedImportsFixer to remove imports causing the warning is a way to go?

In practice this would be helpful when combined with sorting imports.

**Comment by SpacePossum** [comment]
:+1: when added as configurable feature, default `false` as to not change behavior by default.

**Comment by keradus** [comment]
If the behaviour is really the same, `NoLeadingImportSlashFixer` shall remove leading slashes for non-namespaced code.
@SpacePossum , I would say we wrongly thought error is only for non-slashed version, as @julienfalque proved, it's for both. thus, it's a bug and shall be fixed.
