### ISSUE TITLE
About PHP code in HTML attribution format error.

### ISSUE THREAD

**Issue by kmvan** [FriendsOfPHP/PHP-CS-Fixer#2821]
PHP version: 7.1.5
PHP-cs-fixer version: 2.3
Editor: VS code 1.12.2

PHP code:
```php
<?php
$href = 'href="#"';
?>
<a <?= $href;?> ></a>
```
When I save the code, it will format to blew:
```php
<?php
$href = 'href="#"';
?>
	<a <?=$ href;?> ></a>
```
See the href ```<?=$ href;?> >```, it is a parse error.

If need the config file please tell me to upload.

**Comment by SpacePossum** [comment]
Hi @kmvan 
Thanks for reporting. I tried to recreate the scenario, but it would be a great help to know what configuration you use for the fixer.

**Comment by kmvan** [comment]
Thank you your reply @SpacePossum .

This is my config file. (please remove the file txt extension)

[php-cs-fixer.php_cs.txt](https://github.com/FriendsOfPHP/PHP-CS-Fixer/files/1049480/php-cs-fixer.php_cs.txt)

**Comment by SpacePossum** [comment]
thanks :)

With the configuration applied for the fixer @ versions 2.3.0/1/2,
I get the following diff using your sample code:
```diff
--- Original
+++ New
@@ @@
 <?php
 $href = 'href="#"';
 ?>
-<a <?= $href;?> ></a>
+<a <?= $href; ?> ></a>
```

As it seems the editor (VS code) makes additional changes on the save (for example the indenting), I suspect it makes the other (unwanted) change as well.

**Comment by kmvan** [comment]
I found the problem!
If I set the vsc settings ```  "php-cs-fixer.formatHtml": false``` to true, the code will crash. So just set it by default (false) and all OK.

PHP is really the best language in the world.
Thank you very mush man. @SpacePossum
