### ISSUE TITLE
SelfAcessorFixer - breaking code on class properties

### ISSUE THREAD

**Issue by mnabialek** [FriendsOfPHP/PHP-CS-Fixer#2831]
PHP version: 7.1.1 
PHP Cs Fixer version: 2.3.2

When code is like this:

```php
<?php

class Invoice
{
    protected $invoice;

    function dummyFunction()
    {
        $this->invoice::find(5);
    }
}
```

the code is being changed into:

```php
<?php

class Invoice
{
    protected $invoice;

    public function dummyFunction()
    {
        $this->self::find(5);
    }
}
```

what is obviously wrong because `$invoice` doesn't has to be instance of Invoice class. After removing 

```
'self_accessor' => true,
```
rule code is not changed what is expected behaviour

**Comment by julienfalque** [comment]
Thanks for this report, I confirm the bug exists on 2.2:
```diff
--- Expected
+++ Actual
@@ @@
     {
-        $this->invoice::find(5);
+        $this->self::find(5);
     }
 }
```

**Comment by keradus** [comment]
@mnabialek nice ! would you like to help us fixing it? it would be really great ! as the amount or rules are pretty big now, it's hard task to fix everything only by regular maintainers.
Proszę ;)

**Comment by mnabialek** [comment]
@keradus It's done I hope but it seems tests won't pass in PHP 5,6. Can it be solved somehow in test code?
