### ISSUE TITLE
InvalidArgumentException: Cannot set empty content for id-based Token.

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2836]
Master 5d509fbed1c716ee24ea904c20eb18c08bc9f77d.

Error at `src/Tokenizer/Token.php:64`. Called by:

* `PhpCsFixer\Tokenizer\Token->__construct(Array)`,
* `PhpCsFixer\Tokenizer\Tokens->ensureWhitespaceAtIndex(36, 1, '')`,
* `PhpCsFixer\Fixer\Basic\BracesFixer->fixIndents(Object(PhpCsFixer\Tokenizer\Tokens))`

More information to follow very soon.

**Comment by GrahamCampbell** [comment]
This is the offending code:

![image](https://user-images.githubusercontent.com/2829600/26952287-c15aed1a-4c9c-11e7-8cef-2095b04ba83d.png)

**Comment by GrahamCampbell** [comment]
The PR that broke this is https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2817.

**Comment by GrahamCampbell** [comment]
Working on getting a test case for us.

**Comment by SpacePossum** [comment]
Nice edge case,
I wonder why someone would want to ensure the whitespace `''` as it has no space at all..
I think that is what I assumed when puzzling the method together TBH.

**Comment by GrahamCampbell** [comment]
Here's an example test case that breaks php-cs-fixer with only the braces fixer enabled, with all the other config as default:

```php
<?php for ($i = 0; $i < 20; $i++) {
?>
<?php 
} ?>
```

**Comment by SpacePossum** [comment]
can you add that sample as test case in your PR?

**Comment by GrahamCampbell** [comment]
Working on establishing exactly which branch this is broken on.

**Comment by GrahamCampbell** [comment]
Here's a failing test for you, with details about how it fails differently on master: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2838.

**Comment by GrahamCampbell** [comment]
Added this test to my fix PR. Please review. :)
