### ISSUE TITLE
ProcessLinterTest fails on Mac

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2846]
```
There were 2 failures:

1) PhpCsFixer\Tests\Linter\ProcessLinterTest::testPrepareCommandOnPhpOnWindows with data set #0 ('php', 'foo.php', 'php -l foo.php')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-php -l foo.php
+'php' '-l' 'foo.php'

/Users/graham/GitHub/PHP-CS-Fixer/tests/Linter/ProcessLinterTest.php:63

2) PhpCsFixer\Tests\Linter\ProcessLinterTest::testPrepareCommandOnPhpOnWindows with data set #1 ('C:\Program Files\php\php.exe', 'foo bar\baz.php', '"C:\Program Files\php\php.exe...z.php"')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-"C:\Program Files\php\php.exe" -l "foo bar\baz.php"
+'C:\Program Files\php\php.exe' '-l' 'foo bar\baz.php'

/Users/graham/GitHub/PHP-CS-Fixer/tests/Linter/ProcessLinterTest.php:63
```

**Comment by GrahamCampbell** [comment]
```
vendor/bin/phpunit --version
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.
```

**Comment by GrahamCampbell** [comment]
Well, obviously, the windows tests weren't meant to run, but they did. :/

**Comment by GrahamCampbell** [comment]
Related: https://github.com/sebastianbergmann/phpunit/issues/2697, https://github.com/sebastianbergmann/phpunit/issues/2704.

**Comment by keradus** [comment]
poor mac. we don't support it

**Comment by GrahamCampbell** [comment]
> poor mac. we don't support it

What, you can't be serious. Loads of PHP developers use PHP-CS-Fixer on Mac. More than use Windows these days, I'm pretty sure!

**Comment by SpacePossum** [comment]
we support Mac, we don't support running the internal tests on Mac with a bugged PHPUnit version ;)
anyway, must be fixed @ PHPUnit if I understand correctly.

**Comment by keradus** [comment]
we don't run any tests on mac, for that there is no official support. it execution works, it's good. but as we don't test it, there's no official support

**Comment by ConnorVG** [comment]
That's an extremely silly PoV. I'm willing to bet that your OS X use base is within a margin of error's difference from your Windows use base. Thousands of companies rely on this software and you are more than happy with just:
>meh, cba
>windows is fine
>executes on Mac, why do we need to test it? 🙃  – the owner of PHPUnit

Read that last sentence, it makes no sense.

**Comment by keradus** [comment]
it's not about user range. if project is not tested on osx nobody can assure it work now and will in the future. it's not silly, it's stable approach to not claim what is not checked.
I didn't say it's bad to test on mac or sth - I have described current situation (actually, situation since beginning of project).
If you want to ensure project works on osx, it's great - send a PR to configure Travis running on osx as well, and then, if sth would appear to not work on mac, fix it.
