### ISSUE TITLE
indentation incorrect 

### ISSUE THREAD

**Issue by torleif** [FriendsOfPHP/PHP-CS-Fixer#2852]
```PHP 7.0.15 (cli) (built: Jan 23 2017 15:06:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

```
PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski
```
using indentation,linefeed,trailing_spaces,eof_ending,extra_empty_lines,controls_spaces,unused_use,phpdoc_params,visibility,return,braces,include,short_ptag,php_closing_tag,psr12,elseif. 

Here's what this version produces. Note the odd use of two tabs indentation of the static variables: 
```php
<?php 

use SilverStripe\ORM\DataObject;

class Project extends DataObject implements ScaffoldingProvider
{
    private static $db = array(
    'Title' => 'Text'
  );

    public function canCreate($member = null, $context = array())
    {
        return true;
    }
}
```

Here's what atoms auto indentation produces: 
```php
<?php 

use SilverStripe\ORM\DataObject;

class Project extends DataObject implements ScaffoldingProvider
{
  private static $db = array(
    'Title' => 'Text'
  );
  
  public function canCreate($member = null, $context = array())
  {
    return true;
  }
}
```

**Comment by keradus** [comment]
show the code before and after fixing instead of after fixing and after reformatting by 3rd tool

**Comment by torleif** [comment]
Before using 3rd party tool:

```php
<?php 

use SilverStripe\ORM\DataObject;

class Project extends DataObject implements ScaffoldingProvider
{
    private static $db = array(
    'Title' => 'Text'
  );

    public function canCreate($member = null, $context = array())
    {
        return true;
    }
}
```
after:
```php
<?php 

use SilverStripe\ORM\DataObject;

class Project extends DataObject implements ScaffoldingProvider
{
  private static $db = array(
    'Title' => 'Text'
  );
  
  public function canCreate($member = null, $context = array())
  {
    return true;
  }
}
```

note that the code returns tabs, github seems to convert the characters into spaces. 

I'm using MacOS, installed via composer. I ran php-cs-fixer via command line to rule out incase Atom was doing something odd.

**Comment by julienfalque** [comment]
The examples in your second message are exactly the same as in your first message. Which code example is the one **before running any fixing tool**?

> using
> indentation,linefeed,trailing_spaces,eof_ending,extra_empty_lines,controls_spaces,unused_use,phpdoc_params,visibility,return,braces,include,short_ptag,php_closing_tag,psr12,elseif.

This results in an error: _The rules contain unknown fixers_. Could you please also show the exact ruleset you are using?

**Comment by torleif** [comment]
From the command line, I'm using the default ruleset:

```
php-cs-fixer fix Project.php
```

**Comment by SpacePossum** [comment]
```
[02:32 PM]-[possum@zoo4]-[~/work/PHP-CS-Fixer]-[git 2.2] 
$ cat test.php 
<?php

use SilverStripe\ORM\DataObject;

class Project extends DataObject implements ScaffoldingProvider
{
    private static $db = array(
    'Title' => 'Text'
  );

    public function canCreate($member = null, $context = array())
    {
        return true;
    }
}

[02:32 PM]-[possum@zoo4]-[~/work/PHP-CS-Fixer]-[git 2.2] 
$ php-cs-fixer fix test.php --dry-run -vvv --diff
Loaded config default.
.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Checked all files in 0.013 seconds, 4.000 MB memory used

```

```
$ php-cs-fixer -V
PHP CS Fixer 2.3.2 by Fabien Potencier and Dariusz Ruminski (597745f)
```

(not sure why this is not displayed in the phar release when running `fix -vvv`)

I can only conclude this is a third party problem as we cannot reproduce the issue reported.
