### ISSUE TITLE
Extending CastSpacesFixer to remove space after casting

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#2853]
Hi,

what do you thing about extending CastSpacesFixer so it can be configured similarly to ConcatSpaceFixer:

> ``spacing`` (``'none'``, ``'one'``): spacing to apply around concatenation operator;
    defaults to ``'none'``

Both fixers are part of Symfony's codings standars, yet only the later one we can modify.

**Comment by SpacePossum** [comment]
Adding the configuration option sounds good to me.
