### ISSUE TITLE
[phpdoc_align] Is not configurable

### ISSUE THREAD

**Issue by goyote** [FriendsOfPHP/PHP-CS-Fixer#2871]
phpdoc_align should be configurable, yet I get this error: "**[phpdoc_align] Is not configurable**"

**The PHP version you are using:**
~~~
PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.16.0~linux-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.
~~~
**PHP CS Fixer version you are using:**
~~~
PHP CS Fixer 2.3.2 by Fabien Potencier and Dariusz Ruminsk
~~~
**The command you use to run the fixer (and the configuration file you are using if any).**
~~~
php-cs-fixer fix
~~~
~~~
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([
        __DIR__.'/app',
        __DIR__.'/config',
        __DIR__.'/database',
        __DIR__.'/resources/lang',
        __DIR__.'/routes',
        __DIR__.'/tests',
    ]);

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2'                  => true,
        '@Symfony'               => true,
        '@PHP71Migration'        => true,
        'phpdoc_separation'      => false,
        // 'no_useless_return'      => true,
        'array_syntax'           => [
            'syntax' => 'short',
        ],
        'phpdoc_align' => [
            'tags' => ['param'],
        ],
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals'       => true,
        ],
    ]);
~~~

**Comment by SpacePossum** [comment]
Hi and thanks for the report.

The fixer is you try to configure is not configurable, causing the error.
This is because of the following part of your configuration;

```php
        'phpdoc_align' => [
            'tags' => ['param'],
        ],
```

The fixer itself cannot be configured, so can only be enabled or disabled. To enable it please update your configuration to;

```php
        'phpdoc_align' => true, // use `false` if you don't want to use the fixer
```

The fixer is made configurable on `master`, however this feature is not backported to the 2.3 line you are using.
I'm not sure why this was not backported ATM.

**Comment by goyote** [comment]
Thanks!

**Comment by SpacePossum** [comment]
@keradus can we backport this without BC break? Since 3.0 is not in sight it feels kind of a silly not to add features to 2.3

**Comment by keradus** [comment]
huh? minor release of 2.3 was done, bringing *features*. any new feature will came to new minor release.
only bugfixes, docs and CS could be applied at existing minor release, making new patch release.

**Comment by SpacePossum** [comment]
so this will be part of 2.4, so no wait for 3.0?

**Comment by keradus** [comment]
see no reason why a feature should be released under MAJOR release ;)
