### ISSUE TITLE
declare_strict_types can lead to inconsistent looking files

### ISSUE THREAD

**Issue by aidantwoods** [FriendsOfPHP/PHP-CS-Fixer#2890]
Using `declare_strict_types`, the fixer will place `declare(strict_types=1);` on the same line as the opening `<?php` tag.

i.e.

```php
<?php declare(strict_types=1);
```

is produced.

However, if one uses the following format elsewhere:
```php
<?php
declare(strict_types=1);
```

then these files will **not** be adjusted by the fixer so as to lead to inconsistent formatting.

P.S. perhaps the fixer should prefer to place the declare statement on a newline (unless there is a PHP closing tag already on the same line), i.e. as in [this example](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#example) in proposed PSR12, or be configurable.

---

Additionally the fixer, when run will remove a newline present after a `<php` tag – perhaps this falls outside of the formatting responsibilities for this fixer? And may not be desired (I know I don't want it to do that).
e.g.
<img width="822" alt="screen shot 2017-06-29 at 16 19 32" src="https://user-images.githubusercontent.com/3288888/27695428-c193c676-5ce6-11e7-97d7-b3ec2c3cb274.png">

**Comment by keradus** [comment]
Hi ! Thank you for your report.
I think it's a duplicate of #2062 (yet, 2062 is bigger). Could you confirm ?

**Comment by aidantwoods** [comment]
Hmm... my [search](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues?utf8=%E2%9C%93&q=is%3Aissue%20strict) didn't find that one.

Looks like a duplicate though, (with another issue: #2058, touching on that newline problem). Perhaps this can at least serve to reignite the discussion 😉 

I'll close this as all problems mentioned are covered elsewhere.

**Comment by keradus** [comment]
if you are brave enough, please help ;)

**Comment by aidantwoods** [comment]
> if you are brave enough

'tis be determined 😉 I may have some time though

**Comment by aidantwoods** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2891 starts on this
