### ISSUE TITLE
CI - Add running CI tests on Mac

### ISSUE THREAD

**Issue by aidantwoods** [FriendsOfPHP/PHP-CS-Fixer#2892]
* Travis supports testing on Mac: https://docs.travis-ci.com/user/osx-ci-environment/

* Only two tests don't pass: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2846

* These will probably be fixed upstream: https://github.com/sebastianbergmann/phpunit/issues/2697

* No Mac support is 😢

**Comment by GrahamCampbell** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2846. :)

**Comment by aidantwoods** [comment]
@GrahamCampbell This is a feature request, #2846 is closed because this feature doesn't exist 😉

**Comment by SpacePossum** [comment]
:+1: for adding this to Travis

**Comment by keradus** [comment]
PR is welcome @aidantwoods

**Comment by aidantwoods** [comment]
> PR is welcome @aidantwoods

Brb

**Comment by keradus** [comment]
closed due to merge of #2932

**Comment by SpacePossum** [comment]
thanks @aidantwoods for raising the issue and the work done,  awesome to see we have test for Mac now :) 
and thanks @keradus for more work, awesome results :D
