### ISSUE TITLE
Tests on php 5.6 are very slow on master

### ISSUE THREAD

**Issue by aidantwoods** [FriendsOfPHP/PHP-CS-Fixer#2905]
I think some of us have [noticed](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2684#issuecomment-312962885).

~~Possible cause may be performance lost by garbage collection being forced to repeatedly kick in nearing memory allocation limit? I can't even complete the php56 tests locally (without adjusting my ini memory allocation to over `128M`). Maybe a memory leak?~~

~~Tests seem to really start slowing down around the 30% mark (at which point memory allocated to the process is at \~80MB and counting up), which is quite far away from the allocation limit – so possibly that doesn't support this theory.~~

~~In contrast, php71 peaks at around 65MB as it completes the final tests (about half the amount of memory php56 tests need) – possibly (and maybe even likely) that's to do with various improvements in php7 over 5 though.~~

~~Maybe there is another cause to the slowness than memory usage,~~ just thought I'd provide some observations in addition to starting a discussion on the general issue of the completion times.

**Comment by SpacePossum** [comment]
Maybe we could do a test on Travis to up the memory limit for 5.6 to see if it has effect?
When you locally up'ped the limit did it speed up or was it "only" possible to finish the test?

**Comment by aidantwoods** [comment]
> When you locally up'ped the limit did it speed up or was it "only" possible to finish the test?

Hmm... it probably would have been a good idea to test that 😉 

I set it to 1G and tests are still slow, so this doesn't look to be memory related.

**Comment by SpacePossum** [comment]
Thanks for the details and looking forward to the results/observations :)
Will we used to profile and optimize for 5.x line but since our focus has shifted to 7.x, this does not mean that any perfs for 5.x are not welcome, more like a FYI.

**Comment by aidantwoods** [comment]
My main motivation to have a look into it is to keep the travis tests under 20mins ;) (affects those of us that don't use 5.x daily too!)

That said, there are probably other ways of shortening that time if the focus on 5.x is dying down.

**Comment by SpacePossum** [comment]
The focus for 5.x support shouldn't have go down, just stating what happened ;)
Would really like to see the time to test go down!

**Comment by keradus** [comment]
@aidantwoods how long tests took for your php 5.6 if you set up `SKIP_LINT_TEST_CASES=1` ? if it's fairly fast, issue is not memory but php5-based linting, which is hell slower than under php7.

**Comment by aidantwoods** [comment]
With `SKIP_LINT_TEST_CASES=1` it's about 5x faster locally

**Comment by SpacePossum** [comment]
damn that is high factor :) 
not sure we can do without linting...

**Comment by aidantwoods** [comment]
> not sure we can do without linting...

Additional CI for lint tests? This could tie in nicely with #2893 😉

Since OSX tests will likely pass on linux and vice versa – can be fairly confident of result from linux if we're seeing pass/failure, and then just wait for OSX builds to finish to be sure.

**Comment by keradus** [comment]
@aidantwoods then you proved it's slow not because of memory leaks or anything. it's just that slow. that's why we introduced php-7 specific linter.
no, we cant skip linting on 5.x line.

@aidantwoods , if you want, you could play with https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.2/src/Linter/ProcessLinter.php#L145 to store tmp file not in cwd, but in `/tmp` (only if it's available !).
If not, fine for me as well.

Closing due to discussion.
