### ISSUE TITLE
phpdoc_annotation_without_dot incorrectly lowercases the first letter of an acronym 

### ISSUE THREAD

**Issue by oschwald** [FriendsOfPHP/PHP-CS-Fixer#2906]
For instance:

```
    * @param string $ipAddress IPv4 or IPv6 address as a string
```
is turned into:

```
    * @param string $ipAddress iPv4 or IPv6 address as a string
```

Note the "iPv4".

**Comment by SpacePossum** [comment]
Thanks for the report!

I think it would be a nice addition if the fixer would no longer apply the lowercasing if the first two characters of the first word are uppercase or if the those characters are numbers or any are any of the characters `-_:\/`.
So for example the following will not be changed; `IPv4`, `ISO 9001`, `E-abc`, `1Up`, etc.

Help on this would be appreciated, especially as we are trying to wrap up for the upcoming releases, let us know if you can help out and we will help you to get the changes done :)

**Comment by keradus** [comment]
probably target is 2.2, not master branch
