### ISSUE TITLE
Wrong CI integration on config change

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#2908]
Currently, suggested integration looks like:

```
$ IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")); unset IFS
$ vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}"
```

but with that, if one change `.php_cs.dist` file, we shall execute fixing on all files (as there could be new rule configured)
probably we need to change `COMMIT_SCA_FILES` to dot if `.php_cs.dist` was modified.

**Comment by julienfalque** [comment]
I would not change `$COMMIT_SCA_FILES` as it is used by other commands. Maybe you could do something like
```
if $COMMIT_SCA_FILES contains .php_cs.dist
    php-cs-fixer fix [...]
else
    php-cs-fixer fix [...] -- "${COMMIT_SCA_FILES[@]}"
```

**Comment by julienfalque** [comment]
Actually, shouldn't we always fix all files? If a PR fixes a bug in a rule, maybe this rule will then apply changes in a file that isn't modified by the PR.

**Comment by SpacePossum** [comment]
For us that is true, for end users it doesn't matter. Although they should fix all there files after updating the fixer. So as integration suggestion I wouldn't always fix everything.

**Comment by julienfalque** [comment]
Ah I get it now, since the beginning I thought we were discussing our Travis builds...
