### ISSUE TITLE
VoidReturnFixer - Adds void to a closure in a function

### ISSUE THREAD

**Issue by prisis** [FriendsOfPHP/PHP-CS-Fixer#2922]
When reporting an issue (bug) please provide the following information:

The PHP version you are using:
PHP 7.1

PHP CS Fixer version you are using:
PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski

The command you use to run the fixer (and the configuration file you are using if any).
sh vendor/bin/php-cs-fixer fix
https://github.com/narrowspark/php-cs-fixer-config/blob/master/src/Config.php

A minimal sample of valid PHP code that is not fixed correctly (if applicable).
```php
public function test()
{
    $closure = function ($job) {
        $_SERVER['__sync.test'] = true;

        $job->delete();
    };
}
```
The fixed version of that code after you run the fixer and the version you expected.
```php
public function test(): void
{
   $closure = function ($job): void {
        $_SERVER['__sync.test'] = true;

        $job->delete();
   };
}
```

**Error message:**
Fatal error: Cannot use '\TestClass\void' as class name as it is reserved in closure://function ($job): \TestClass\void {

**Comment by keradus** [comment]
code you have in "fixed version" is valid:
https://3v4l.org/Uo3fU

maybe you need to provide more context of the file (like maybe you removed too much to get your example smaller) ?

where the error msg comes from? the PHP CS Fixer execution or somewhere else?

**Comment by prisis** [comment]
I removed some code.. i will update the issue

Phpunit throws the msg after the fix

**Comment by SpacePossum** [comment]
@prisis which version of PHPUnit are you using?

**Comment by prisis** [comment]
Using PHPUnit 6.3.0, but had any time to test this again, sorry

**Comment by SpacePossum** [comment]
This looks like a PHP version conflict somewhere in the tool chain.
Without additional information we cannot proceed with this issue so I'm going to close it.
If new information is available please provide it here and based it we can re-open the issue if needed.
