### ISSUE TITLE
NoBreakCommentFixer should ignore case of first character

### ISSUE THREAD

**Issue by kelunik** [FriendsOfPHP/PHP-CS-Fixer#2948]
Currently, if there's a `// No break` comment, PHP-CS-Fixer adds another `// no break` comment. It should either fix the case of the comment that's already there or instead just ignore the case and do nothing.

**Comment by keradus** [comment]
after fixing, the comment shall have same casing everywhere.
if there is one with different casing, I agree that it would be nice to change casing instead of adding new commnet.

could you send a PR @kelunik ?

**Comment by kelunik** [comment]
Can't PR in the coming days, maybe afterwards.

**Comment by keradus** [comment]
sure, just be aware that we have too many requests to handle all of them on our side.
if community won't help, not all requests will be fulfilled
