### ISSUE TITLE
`combine_consecutive_unsets` gives really long line

### ISSUE THREAD

**Issue by josephzidell** [FriendsOfPHP/PHP-CS-Fixer#2950]
When you have many consecutive `unset()`s and they're combined, it will leave a really long line, possibly breaking any line-length standards one may have in place.

Before:
```php
<?php
function f()
{
	unset($really_long_variable_name[0]);
	unset($really_long_variable_name[1]);
	unset($really_long_variable_name[2]);
	unset($really_long_variable_name[3]);
	unset($really_long_variable_name[4]);
	unset($really_long_variable_name[5]);
	unset($really_long_variable_name[6]);
	unset($really_long_variable_name[7]);
}
```

After:
```php
<?php
function f()
{
	// 254 chars
	unset($really_long_variable_name[0], $really_long_variable_name[1], $really_long_variable_name[2], $really_long_variable_name[3], $really_long_variable_name[4], $really_long_variable_name[5], $really_long_variable_name[6], $really_long_variable_name[7]);

}
```

Would be great if we can specify either:
`'combine_consecutive_unsets' => true,` or `'combine_consecutive_unsets' => 120,` as a line length

**Comment by josephzidell** [comment]
The `120` above as line length was an example

**Comment by keradus** [comment]
btw, there is no hard line limit in PSR.

instead of making this functionality only for `unset`, I would rather create new rule that handles any function calls and change it from single line to multi lines, and run after `combine_consecutive_unsets`, so if it would create extra long line, new rule would normalize that askpect.

after generalization, your new feature request is accepted. please send a PR

**Comment by julienfalque** [comment]
Indeed, creating a generic fixer that ensures lines don't exceed a given limit should be the way to go. We already have an open issue for this feature request (#2790) so I'm closing this one as duplicate.

**Comment by keradus** [comment]
@josephzidell as you faced this concern and want it solved, could you send a PR for it?

**Comment by josephzidell** [comment]
@juliendufresne IMO a general fix would likely need to be marked as risky, and people may not want to use it.

@keradus I haven't made a fix. Actually turned it off until it is fixed.

**Comment by keradus** [comment]
> IMO a general fix would likely need to be marked as risky, and people may not want to use it.

adding whitespaces between args is not changing code execution, thus fixer would not be risky at all

> I haven't made a fix. Actually turned it off until it is fixed.

your call here, just please be aware that not all raised issues/features could be handled in-house.

**Comment by josephzidell** [comment]
I might be able to PR a limited solution for unsets, probably not a global solution. Would you like an unset()-focused PR?

**Comment by keradus** [comment]
what is the difference of fixing
```php
unset($________________________arg1, $________________________arg2, $________________________arg3, $________________________arg4, $________________________arg5, $________________________arg6);
```
than fixing any
```php
foo($________________________arg1, $________________________arg2, $________________________arg3, $________________________arg4, $________________________arg5, $________________________arg6);
```
?

**Comment by josephzidell** [comment]
`unset()`s start out as separate. My thought was never split an-already combined LOC. My plan was rather to use the line length consideration when combining unsets.

**Comment by keradus** [comment]
too narrow. 
why would you split too long unset call? because you have rule in mind "line shall not be too long".
for that, it's better to have general fixer for general rule, instead of only some cases

**Comment by josephzidell** [comment]
Enough beating a dead horse. Combining with constraints is easier/safer than splitting lines.

**Comment by josephzidell** [comment]
> because you have rule in mind "line shall not be too long".

No. What I have in mind is not a new rule, and has nothing to do with splitting lines. It has to do with smart combining. Combine separate `unset()`s up to line length _x_

**Comment by keradus** [comment]
> Combining with constraints is easier/safer than splitting lines.

but... again, what is not safe in splitting lines not related to `unset` ?

> No. What I have in mind is not a new rule, and has nothing to do with splitting lines. It has to do with smart combining.

Then on what indicate you gonna decide to split combined `unset` to multiple lines or not? Not on the rule `line shall not be too long`? :-1: for having non-general rules applied only for some specific cases.
