### ISSUE TITLE
Can php-cs-fixer reindent code?

### ISSUE THREAD

**Issue by wowcut** [FriendsOfPHP/PHP-CS-Fixer#2957]
Can php-cs-fixer reindent code?

**Comment by keradus** [comment]
Hi. not in all cases, but yes.
Closing as not an issue.

For support/first steps help, please visit:
- http://cs.sensiolabs.org/ (or README file inside repo: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/README.rst , awailable also as main package github page)
- https://gitter.im/FriendsOfPHP/PHP-CS-Fixer

**Comment by wowcut** [comment]
Thank you for the gitter hint - this communication channel is not published anywhere - I was looking for any way to ask a question but did not find a better way. You should publish the gitter channel right on the Readme.md and on the website, so people know where to discuss things. 

BTW the docs are not very clear about indendation. However, thanks for your attention and your precious time, have a nice day!

**Comment by keradus** [comment]
> You should publish the gitter channel 

:+1:

> BTW the docs are not very clear about indendation. 

feel free to improve it ;)
