### ISSUE TITLE
ensure_fully_multiline format more than needed

### ISSUE THREAD

**Issue by eclipxe13** [FriendsOfPHP/PHP-CS-Fixer#2958]
I've found that method_argument_space with ensure_fully_multiline as true (as is set in PSR-2) is messing with other code not related.

- PHP versions: 7.0 & 7.1 (other not checked)
- PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski

php-cs-fixer fix --using-cache=no --rules='{"method_argument_space": {"ensure_fully_multiline": true}}' example.php

```php
<?php
exit(call_user_func(function () {
    echo "a", "b",
        "c", "\n";
    return 0;
}));
```

Result (**why is this considering that the function must be in a new line?**):
```php
<?php
exit(call_user_func(
    function () {
    echo "a",
    "b",
        "c",
    "\n";
    return 0;
}
));
```

Expected (**repair only the echo line, don't touch anything else**):
```php
<?php
exit(call_user_func(function () {
    echo "a",
    "b",
        "c",
    "\n";
    return 0;
}));
```

**Comment by eclipxe13** [comment]
Another exampĺe. In this case it is expected that method_argument_space don't change anything.

In the first case, the inner `echo` line with 3 arguments are in 3 different lines, the method_argument_space does not change anything on this line but it does in `call_user_func` moving `function` to a new line.

In the second case, the inner `echo` with 3 arguments all in 1 line, the method_argument_space does not change anything, not even in `call_user_func` as in the previous case.

```php
<?php
call_user_func(function ($arguments) {
    echo "a",
        (X) ? 'T' : 'F',
        "\n";
}, $argv);


call_user_func(function ($arguments) {
    echo "a", (X) ? 'T' : 'F', "\n";
}, $argv);

```

```diff
--- Original
+++ New
@@ @@
 <?php

-call_user_func(function ($arguments) {
+call_user_func(
+    function ($arguments) {
     echo "a",
         (X) ? 'T' : 'F',
         "\n";
-}, $argv);
+},
+    $argv
+);
```

**Comment by keradus** [comment]
nice catch
could you send a fix @eclipxe13 ?

**Comment by greg0ire** [comment]
So to sum up the bug: if an argument to a function is a function with a multiline "function" call in it, the outer function is detected as needing to become multiline?

**Comment by eclipxe13** [comment]
sorry @keradus, I have no idea how to fix it, I will take a look tomorrow but I can't promise anything

**Comment by greg0ire** [comment]
I'm looking into it right now.

**Comment by greg0ire** [comment]
The bug occurs only when the inner function requires a multiline fix.

**Comment by greg0ire** [comment]
Oh wait no it's not exactly that, it works fine when it is a broken function call

**Comment by greg0ire** [comment]
Oh wait no it's not exactly that, it works fine when it is a broken function call. It really is about echo...

**Comment by greg0ire** [comment]
@eclipxe13 I don't think echo should be fixed at all BTW. The spec is about methods and function, which echo is not.

**Comment by eclipxe13** [comment]
@greg0ire, your deduction is fine according to the last example. I would add that if the outer function need to become multiline then forces inner echo multi parameter calls to become multiline. See the following example:

```php
<?php
call_user_func(function ($arguments) {
    echo "a", "foo", "\n";
},
$argv);
```

Result (mess with `echo`):
```php
<?php
call_user_func(function ($arguments) {
    echo "a",
    "foo",
    "\n";
},
$argv
);
```

Expected (don't touch the `echo`):
```php
<?php
call_user_func(
    function ($arguments) {
    echo "a", "foo", "\n";
},
$argv
);
```
Diff:
```diff
--- Original
+++ New
@@ @@
 <?php
-call_user_func(function ($arguments) {
-    echo "a", "foo", "\n";
+call_user_func(
+    function ($arguments) {
+    echo "a",
+    "foo",
+    "\n";
 },
-$argv);
+$argv
+);
```

BTW, if you change the `echo` to a parenthesis call like `myecho("a", "foo", "\n");` or a single argument `echo "a" . "foo" . "\n"` then it does what is expected.

May the problem be in how `echo` with more than 1 parameter is interpreted?

```diff
--- Original
+++ New
@@ @@
 <?php
-call_user_func(function ($arguments) {
+call_user_func(
+    function ($arguments) {
     echo "a" . "foo" . "\n";
 },
-$argv);
+$argv
+);
```

**Comment by greg0ire** [comment]
Here is a fix for the first bug: https://github.com/greg0ire/PHP-CS-Fixer/commit/6392ef2e6b493605b0e585f55b525aff264596be

**Comment by eclipxe13** [comment]
I had test previous examples changing the `echo A, B, C` to `myecho(A, B, C)` and it behaves as expected. So is valid to point out that the problem is echo multi parameter related.

| I don't think echo should be fixed at all BTW. The spec is about methods and functions, which echo is not.
php docs about echo: *echo is not actually a function (it is a language construct), so you are not required to use parentheses with it* ... *. Additionally, if you want to pass more than one parameter to echo, the parameters must not be enclosed within parentheses.*
PSR-2 spec is about: "4.4 Method Arguments" and "4.5 Method and Function Calls"

I don't know how this project deals with multi parameter echo. It is very common to treat it like a function call.

**Comment by greg0ire** [comment]
> I don't know how this project deals with multi parameter echo. It is very common to treat it like a function call.

Yeah maybe but I did not sign up for this :P I'll just fix the bug for now.

**Comment by greg0ire** [comment]
In addition to the laziness argument (or excuse), some people might disagree with you on whether this needs to be fixed or not. Let's not fix that if they don't want use to. If you want to introduce this one day, make sure to make it optional.

**Comment by eclipxe13** [comment]
I think is valid to discard `echo` calls. I have seen code like:
```php
echo _("Title"), "\n",
    "foo: ", _("Foo explanation"), "\n",
    "bar: ", _("Bar explanation"), "\n",
    _("Other line of information"), "\n";
```

And your fixer change it to:
```php
echo _("Title"),
    "\n",
    "foo: ",
    _("Foo explanation"), 
    "\n",
    "bar: ",
    _("Bar explanation"), 
    "\n",
    _("Other line of information"), 
    "\n";
```

In the end, there are no explicitly rule to change this since "echo is not a function".

**Comment by hkdobrev** [comment]
Thanks for this! It helped me with a `[$a, $b, $c] = explode();` call being put on multiple lines when in the body of a closure used as an argument.

Could you please release a patch version with this? Thank you!
