### ISSUE TITLE
phpdoc_add_missing_param_annotation adds params in wrong order

### ISSUE THREAD

**Issue by gingerCodeNinja** [FriendsOfPHP/PHP-CS-Fixer#2960]
It seems that `phpdoc_add_missing_param_annotation`adds params in wrong order? the order does not match the function signature parameter order

PHP 5.6.30
PHP CS Fixer 2.4.0

Command -

`php-cs-fixer fix test.php --rules='{"phpdoc_add_missing_param_annotation": {"only_untyped": false}}'`

Test sample (test.php) -

```
<?

class Test
{
        /**
         * @param Bob1 $test1
         * @param Bob3 $test3
         */
        function test(Bob1 $test1, Bob2 $test2, Bob3 $test3)
        {

        }
}
```

Expected -

```
<?php

class Test
{
        /**
         * @param Bob1 $test1
         * @param Bob2 $test2
         * @param Bob3 $test3
         */
        function test(Bob1 $test1, Bob2 $test2, Bob3 $test3)
        {

        }
}
```

Actual -

```
<?php

class Test
{
        /**
         * @param Bob1 $test1
         * @param Bob3 $test3
         * @param Bob2 $test2
         */
        function test(Bob1 $test1, Bob2 $test2, Bob3 $test3)
        {

        }
}
```

should phpdoc_add_missing_param_annotation handle this, or should it be a different fixer?

**Comment by julienfalque** [comment]
`phpdoc_add_missing_param_annotation` fixer doesn't care about arguments order: it only adds missing `@param` tags after the ones that already exist. There is an open PR (#1602) about adding support for this so I'm closing here.
