### ISSUE TITLE
NoBreakCommentFixer removes comments 

### ISSUE THREAD

**Issue by pascal-hofmann** [FriendsOfPHP/PHP-CS-Fixer#2961]
NoBreakCommentFixer removes comments when they are in the same line as the case statement.

Original code:
```
<?php
switch ($foo) {
    case 1: // no break
    case 2:
        bar();
}
```

Expected result:
```
<?php
switch ($foo) {
    case 1: // No break
    case 2:
        bar();
}
```

Actual result:
```
<?php
switch ($foo) {
    case 1:
    case 2:
        bar();
}
```

PHP 7.0.20 (cli) (built: Jun 23 2017 07:46:30) ( NTS )
PHP CS Fixer version 2.4.1-DEV Silver Gingerbread by Fabien Potencier and Dariusz Ruminski

**Comment by keradus** [comment]
there shall not be a comment in this place
http://www.php-fig.org/psr/psr-2/#52-switch-case

**Comment by pascal-hofmann** [comment]
Yes, but only according to PSR-2. I still would expect the fixer to insert the missing newline instead of removing the comment at all.

**Comment by keradus** [comment]
> Yes, but only according to PSR-2.

and fixer is following PSR2. that's it's spec

**Comment by pascal-hofmann** [comment]
Still it should improve the situation, not make it worse.

Correct behavior according to PSR-2 would be:
```
<?php
switch ($foo) {
    case 1:
        // No break
    case 2:
        bar();
}
```

**Comment by keradus** [comment]
no. again, if there is no code between `case` statements, PSR-2 asked you to not have commend. that's the spec of psr-2 and our fixer.

**Comment by keradus** [comment]
if you want fixer to work differently than PSR-2 asked, then provide source for styling you asking for - any other well established styleguide.
we simply cannot add more and more rules for any request that would be in use by one guy

**Comment by pascal-hofmann** [comment]
Ah, now I get it. "There MUST be a comment such as // no break when fall-through is intentional in a non-empty case body."


Ok, will simply disable it then.
