### ISSUE TITLE
Composer dependencies incompatible with PHPUnit 6.3

### ISSUE THREAD

**Issue by Riimu** [FriendsOfPHP/PHP-CS-Fixer#2966]
With latest PHPUnit and php-cs-fixer, there exists an incompatibility between dependencies:

* php-cs-fixer 2.4.0 requires `"sebastian/diff": "^1.4"`
* phpunit 6.3.0 requires `"sebastian/diff": "^2.0"`

Given that these two version requirements are incompatible, it's currently impossible to have both versions a dev dependencies in a project.

It's not a major issue yet, as there is nothing in PHPUnit 6.3 that I would require. Going forward, however, this prevents updating both, if I want to keep them as dev dependencies instead of separate installations. (and I just migrated all my projects to use dev dependencies rather than relying on external installations...)

**Comment by julienfalque** [comment]
Integration of `sebastian/diff` 2.0 is on its way so this issue should be solved soon. In the meantine, I would suggest you install PHP CS Fixer using a separate `composer.json` file (like [we do on this repository](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master/dev-tools)), this would prevent such dependency issues.

**Comment by keradus** [comment]
thanks for report
it's on the go and have already opened issue. closing thanks to that
