### ISSUE TITLE
 'align_multiline_comment' => true  is not friendly for chinese

### ISSUE THREAD

**Issue by chunhei2008** [FriendsOfPHP/PHP-CS-Fixer#2970]
This example:

<?php
/*
 * member-card.php
 *
 * 会员卡接口路由配置：
 *
 * 1.会员卡接口
 *
 * Author: wangyi <chunhei2008@qq.com>
 *
 * Date:   2017/8/9 11:24
 * Copyright: (C) 2014, Guangzhou YIDEJIA Network Technology Co., Ltd.
 */

fix file will be error in comment

**Comment by keradus** [comment]
there is no chinese in your example.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE is obligatory to help anyone investigating the issue

**Comment by SpacePossum** [comment]
@chunhei2008 please test now https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2984 is merged if this solved the issue.
If not please provide an example of input those is fixed wrongly (follow the issue template please).
