### ISSUE TITLE
Is there a rule that ensures there is only one space before and only one after the equal sign in variable decalarations?

### ISSUE THREAD

**Issue by Aerendir** [FriendsOfPHP/PHP-CS-Fixer#2971]
I have this code:

```php
...
// Get references of objects
$email               = $event->getEmail();
$company             = $event->getCompany();
...
```

As you can see there a re a lot of spaces before the `=` (equal) sign.

Is there a rule that can remove them and then realign respecting the `'binary_operator_spaces' => ['align_double_arrow' => true, 'align_equals' => true,]` rule?

This is my configuration:

```php
return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setUsingCache(true)
    ->setRules([
        'header_comment' => ['header' => $header],
        '@Symfony' => true,

        // Symfony overwritings
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals' => true,
        ],
        'concat_space' => ['spacing' => 'one'],
        'phpdoc_to_comment' => false,
        'declare_equal_normalize' => ['space' => 'single'],

        // Other rules
        'align_multiline_comment' => true,
        'array_syntax' => ['syntax' => 'short'],
        'blank_line_before_return' => true,
        'combine_consecutive_unsets' => true,
        'linebreak_after_opening_tag' => true,
        'list_syntax' => ['syntax' => 'short'],
        'no_multiline_whitespace_before_semicolons' => true,
        'no_null_property_initialization' => true,
        'no_short_echo_tag' => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'not_operator_with_space' => true,
        'not_operator_with_successor_space' => true,
        'ordered_class_elements' => [
            'use_trait',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'construct',
            'phpunit',
            'method_public',
            'method_protected',
            'method_private',
            'destruct',
            'magic'
        ],
        'ordered_imports' => true,
        'phpdoc_add_missing_param_annotation' => true,
        'phpdoc_order' => true,
        'phpdoc_types_order' => ['null_adjustment' => 'always_last'],
        'single_line_comment_style' => ['comment_types' => ['hash']],
        'strict_comparison' => true
    ]);
```

**Comment by skyzyx** [comment]
Not that I have found. This is something I've had to manually catch in code reviews.

**Comment by keradus** [comment]
@Aerendir you asked 2 conflicting questions

> Is there a rule that ensures there is only one space before and only one after the equal sign in variable decalarations?

yes, `binary_operator_spaces` could ensure that there is only one space before and after `=`

> Is there a rule that can remove them and then realign respecting the 'binary_operator_spaces' => ['align_double_arrow' => true, 'align_equals' => true,] rule?

you could align them with `binary_operator_spaces` again.

-----------------

what you want is not to ensure there is only one space around `=`, but decrease indentation when possible - which is a feature request for `binary_operator_spaces`.

Take a look at #2573 and comment there is it working for you.
If you want make #2573 happen faster, please help with review and testing edge cases.

Closing as duplicate.

**Comment by Aerendir** [comment]
@keradus , than you for the direction... I'm going to check the issue #2573...
