### ISSUE TITLE
Changing the phar file cause php-cs-fixer to max out its memory use and die

### ISSUE THREAD

**Issue by pjkaufman** [FriendsOfPHP/PHP-CS-Fixer#2973]
I can run the .phar file the first time, but if I change anything in the file (including adding a space) and then save, this error message is displayed in the php error logs.
Error Message:
manifest cannot be larger than 100 MB in phar "/Users/pkaufman/Downloads/php-cs-fixer-v2.phar" in /Users/pkaufman/Downloads/php-cs-fixer-v2.phar:38
Stack trace:
#0 /Users/pkaufman/Downloads/php-cs-fixer-v2.phar(38): Phar::mapPhar('php-cs-fixer.ph...')
#1 {main}
  thrown in /Users/pkaufman/Downloads/php-cs-fixer-v2.phar on line 38

Is there any quick fix?
Thank you for the help!

**Comment by keradus** [comment]
> I can run the .phar file the first time, but if I change anything in the file (including adding a space) and then save

by that you mean that you are modifying `php-cs-fixer.phar` file itself? how you are doing it, via directly opening phar file in IDE ?

**Comment by pjkaufman** [comment]
Yes. I am using atom to change values  from true to false and add values.

**Comment by keradus** [comment]
phar file is PHP Archive. treat is as binary file. Manually changing this fail could lead to internal inconsistency, wrong checksum and indeterminable effects. I strongly advice to not do this.
Even if you decide to, we do not support that kind of actions.

**Comment by pjkaufman** [comment]
Hey, this web page(http://tricksty.com/coding/editing-code-in-a-phar-file) has helped me edit the phar file. The file must be unpacked before being edited.
