### ISSUE TITLE
SingleBlankLineAtEofFixer accepts file with 0 lines, only fixes 2+ lines

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#2976]
The PHP version you are using: PHP 7.1.6

PHP CS Fixer version you are using: 2.4

`SingleBlankLineAtEofFixer` accepts this class as valid:

```php
<?php declare(strict_types=1);

class SomeClass
{
}
```

This would be expected output:

```php
<?php declare(strict_types=1);

class SomeClass
{
}


```

It might be caused by [`ensureWhitespaceAtIndex()` method](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f9abae03a6da058b6786142ae172c0747d3d3493/src/Fixer/Whitespace/SingleBlankLineAtEofFixer.php#L67), that might accept any whitespace (Not sure how exactly it works).

**Comment by GrahamCampbell** [comment]
The tests show that files with zero newlines are correctly fixed to be one newline: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.4/tests/Fixer/Whitespace/SingleBlankLineAtEofFixerTest.php. Are you able to add a failing test case to there please to demonstrate what you are seeing?

**Comment by TomasVotruba** [comment]
@GrahamCampbell Thanks for link to the tests. It made me recheck my code. 
I missed *added new lines in the end of file* in my reporting and I fixed that, thanks.

Fixer works
