### ISSUE TITLE
[Feature Request] Align all equals and double-arrow symbols using as few superfluous spaces as possible, with a minimum of 1 space

### ISSUE THREAD

**Issue by skyzyx** [FriendsOfPHP/PHP-CS-Fixer#2977]
Similarly to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2971, I would love to see a fixer for “Align all equals and double-arrow symbols using as few superfluous spaces as possible, with a minimum of 1 space.”

For example, this:

```php
$var = [
    'abc'         => 123,
    'def'         => 456,
    'ghi'=>789,
    'jkl' => 012,
];
```

…becomes this:

```php
$var = [
    'abc' => 123,
    'def' => 456,
    'ghi' => 789,
    'jkl' => 012,
];
```

----

And this:

```php
$var = [
    'abc'                       => 123,
    'def'                       => 456,
    'ghi'                       => 789,
    'abcdefghijklmnopqrstuvwxyz'=> 012,
];
```

…becomes this:

```php
$var = [
    'abc'                        => 123,
    'def'                        => 456,
    'ghi'                        => 789,
    'abcdefghijklmnopqrstuvwxyz' => 012,
];
```

**Comment by keradus** [comment]
this is basically same ticket as refered one, it's same rule with same aligning feature.
closing same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2971#issuecomment-322283975
