### ISSUE TITLE
Normalizing simple echo tags (short and long forms)

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#2990]
We currently have the `no_short_echo_tag` to expand code from `<?=` to `<?php echo`.

#2520 was an attempt to do the reverse, but I think it has been closed mainly because of lack of interest.

I can take care of this, by implementing to a configurable fixer that can merge the two fixers (`no_short_echo_tag` and `opening_tag_plus_echo_to_short_echo_tag`), into a new `short_echo_tag` fixer.

This fixer could have
- a `format` option (required), with a value of:
  - `'short'` to convert `<?php echo` and `<?php print` to `<?=`
  - `'long'` to convert `<?=` to `<?php echo` or `<?php print`
- a `printOrEcho` option (optional, defaulting to `'echo'`), with a value of:
  - `'echo'` to convert `<?=` to `<?php echo`
  - `'print'` to convert `<?=` to `<?php print`

We could also add more functionalities to this fixer, but those would maybe be better implemented in another fixer. I'm thinking about normalizing spaces and trailing semi-colons (eg formatting `<?php echo 2;?>` as `<?= 2 ?>` or `<?=2?>` or whatever).

Thoughts?

**Comment by orlangur** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2520#issuecomment-285107842
What do you think about `no_mixed_echo_print` absorption?

**Comment by mlocati** [comment]
I think they are two separate fixers

**Comment by mlocati** [comment]
See #4493

**Comment by julienfalque** [comment]
Closing as #4493 is merged.
