### ISSUE TITLE
Command to list unspecified fixers

### ISSUE THREAD

**Issue by Slamdunk** [FriendsOfPHP/PHP-CS-Fixer#2996]
It is difficult to keep tracking of which fixers you already wrote in the `.php_cs` and which one you didn't, expecially if you use rulesets or a new version of the tool is released.

I propose a new command that gets `.php_cs` config, makes a diff with all the fixers available and shows which ones are not specified.

With a flag we can also print a `var_export` with all these unspecified fixers set to `false` that can be copy-pasted in the `.php_cs`, so the user can progressively set them to true, or leave them to false to be able to re-run the command in the future.

Suggestions on the name of this command and flags are welcome.

**Comment by Slamdunk** [comment]
Of course, I am going to write this command. This topic is an Issue and not a PR because I would like a feedback before deeping in a day af work on this 😄

**Comment by julienfalque** [comment]
I'm not a big fan of this idea. Adding all unwanted rules set to `false` just to prevent them from being shown as new will probably make the config file much more verbose. And what about new options for existing rules?

This can already be done by just reading the changelogs so creating this command is not worth it IMO. Maybe @mlocati's [PHP-CS-Fixer Configurator](https://mlocati.github.io/php-cs-fixer-configurator/) can help too.

**Comment by Slamdunk** [comment]
> And what about new options for existing rules?

No clue 

> This can already be done by just reading the changelogs

This is exactly the reason I'm proponing this feature: reading the changelog is unthinkable.
I dare you to read [Changelog for v2.4.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.4.0/CHANGELOG.md#changelog-for-v240) and list in less than 5 minutes:

1. The new fixers
1. The name of those fixers
1. The options for the new fixers
1. The name of those options
1. The new options for existing fixers
1. The name of those options

It's 3 years now I use this (amazing) tool, and I spent something like 15 minutes for every release to figure out all these point listed, until I made a [test for my Config](https://github.com/Slamdunk/php-cs-fixer-extensions/blob/master/tests/ConfigTest.php#L27) that tells me what I'm proposing here.

I am too not much convinced of the solution I'm proposing to this issue, but the problem is real, at least for me.

**Comment by SpacePossum** [comment]
Listing a diff between configured and available rules sounds useful to me, writing to config not so much.
Listing new options will be hard, but that doesn't make listing the rules less useful.
Maybe a simple list of all rules with an indicator if configured (directly or by configured set) would be enough?

**Comment by Slamdunk** [comment]
> writing to config not so much

Note that I don't want to write the config; I proposed an option that prints the diff list in a format copy-pastable in the config; this option would be straitforward to implement, once implemented the diff or the list with indicators you suggest

**Comment by Aerendir** [comment]
As I didn't see this issue I just opened a new one (#3045).

In the meantime I've also wrote a draft of the command `compare` that simply lists all the builtin fixers and highlights if they are configured to be actually used or not.

See the PR #3047 for more details and a screenshot of the result.

I think this is a good starting point from which we can improve the reporting and generate what we like.

I hope you'll enjoy it! Cheers...

**Comment by Aerendir** [comment]
@Slamdunk , reading again your comments here and going then to your initial issue, I think I've understand what you'd like to have.

Given that using the command `vendor/bin/php-cs-fixer compare --show-risky --hide-in-use` I have this as result:

![schermata 2017-09-12 alle 15 19 05](https://user-images.githubusercontent.com/1968622/30327835-bfc13ae6-97cd-11e7-8b3c-c7212ad6aacc.png)

If I understand well your thoughts, you would be able to dump the first column "Fixer" (where the fixer name is) in a way that is copy-and-pastable directly in the `.php_cs` file.

Something like this:

```php
'class_keyword_remove' => false,
'combine_consecutive_issets' => false,
'declare_strict_types' => false,
'doctrine_annotation_array_assignment' => false,
'doctrine_annotation_braces' => false,
'doctrine_annotation_indentation' => false,
'doctrine_annotation_spaces' => false,
'general_phpdoc_annotation_remove' => false,
'heredoc_to_nowdoc' => false,
'mb_str_functions' => false,
'native_function_invocation' => false,
'no_blank_lines_before_namespace' => false,
'no_homoglyph_names' => false,
'no_php4_constructor' => false,
'no_superfluous_elseif' => false,
'php_unit_strict' => false,
'php_unit_test_class_requires_covers' => false,
'phpdoc_to_comment' => false,
'pow_to_exponentiation' => false,
'psr0' => false,
'random_api_migration' => false,
'simplified_null_return' => false,
'strict_comparison' => false,
'strict_param' => false,
'ternary_to_null_coalescing' => false,
'void_return' => false
```

Am I right?

**Comment by Aerendir** [comment]
@Slamdunk , if I were right, use the flag `--dump` and see what happens! 💃 

If I'm not... anyway there is a useful feature...

**Comment by Slamdunk** [comment]
@Aerendir you are right.

I'm closing this issue as your PR is converging to the point, we can discuss it there 👍
