### ISSUE TITLE
SelfUpdateCommand - Update to newest version, not latest published

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2997]
Currently the `SelfUpdateCommand` updates based on the last version released, which may not be newest version within the given major version. We should fix this logic.

Think of it, this might be nice candidate for a new package in a new repo as a lot of this code can be reused by other packages, WDYT?

(cc @julienfalque)

**Comment by julienfalque** [comment]
Thanks for creating this issue :)

I'm not against extracting this logic into a dedicated package but I think it would require more work and would be out of the scope of this issue. Also, what about existing tools like https://github.com/phar-io/phive?

**Comment by keradus** [comment]
I'm :+1: for using external package for self-update command, but let it not be 10mb big project :)
