### ISSUE TITLE
Expected error with <?= $a,$b,$c; ?>

### ISSUE THREAD

**Issue by kmvan** [FriendsOfPHP/PHP-CS-Fixer#3000]
Cs fixer version: 2.5.0
Code in VS-Code editor.

![tim 20170824231213](https://user-images.githubusercontent.com/3839554/29673551-22d8b06a-8922-11e7-83d1-e187688c426f.png)

Maybe I missed some options to enable?

**Comment by keradus** [comment]
Hi.
Sadly, no clue what you are asking :(

Please follow the template as you were asked:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.5/.github/ISSUE_TEMPLATE

**Comment by SpacePossum** [comment]
Closing as there is no response from the reporter, which is needed to proceed.
