### ISSUE TITLE
[Feature Request] Add allowing empty anonymous class option to `braces`

### ISSUE THREAD

**Issue by issei-m** [FriendsOfPHP/PHP-CS-Fixer#3005]
I wanna write an empty anonymous class (just implementing marker interface) in single line like:

```php
throw new class('Something went wrong') extends \Exception implements \My\Own\ExceptionInterface {};
```

Or is there the way already?

Thanks.

**Comment by SpacePossum** [comment]
Hi and thanks for asking :)
I think your request is the same as made here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2782 ?

**Comment by issei-m** [comment]
@SpacePossum Yep, that's exactly what I want. Thank you for pointing out!
