### ISSUE TITLE
SingleLineCommentStyle is converting PHPDoc comment.

### ISSUE THREAD

**Issue by bycosta** [FriendsOfPHP/PHP-CS-Fixer#3011]
PHP version:
```bash
$ php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 15:01:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.17.3~mac-x64-non_zts71, https://blackfire.io, by SensioLabs
```

PHP CS Fixer version:
```bash
$ php-cs-fixer -V
PHP CS Fixer 2.5.0 Ancient Lizard by Fabien Potencier and Dariusz Ruminski
```

The command used to run the fixer:
```bash
$ php-cs-fixer fix -v
```

The configuration file:

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/app')
    ->in(__DIR__ . '/features/bootstrap')
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/tests');

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'blank_line_after_opening_tag' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => true,
        'is_null' => ['use_yoda_style' => false],
        'list_syntax' => ['syntax' => 'short'],
        'method_argument_space' => ['ensure_fully_multiline' => true],
        'modernize_types_casting' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => true,
        'php_unit_construct' => true,
        'php_unit_dedicate_assert' => true,
        'phpdoc_align' => false,
        'phpdoc_order' => true,
        'pre_increment' => false,
        'single_line_comment_style' => true,
        'ternary_to_null_coalescing' => true,
        'void_return' => true,
    ])
    ->setFinder($finder)
    ->setUsingCache(true)
    ->setRiskyAllowed(true);
```

Code before running the fixer:
```php
<?php

/** @var \Foo\Bar $bar */
$bar->doSomething();
```

Code after the fixer:
```php
<?php

// @var \Foo\Bar $bar
$bar->doSomething();
```

The expected code is the same as before running the fixer.

**Comment by bycosta** [comment]
This was first reported in #3003.

**Comment by keradus** [comment]
Hi, thanks for your report.

it's converted, as your "docblock" is not a docblock. it is understand by fixer to contain random content, not an annotation, as annotation is invalid.
specification is `@var [“Type”] [$element_name] [<description>]` - in your example the order is reverted.

For me, behaviour of fixer is proper. It detected wrong annotation that is not an annotation, so this is not a phpdoc, so it shall be written with comment syntax. When you fix the order, you won't face this issue.

That's short answer.
If you want a longer one (not longer in terms of writing a message, but to accomplish) - you may propose a fixer that will be executed before `docblock to comment` that will fix wrong order of annotation

**Comment by bycosta** [comment]
Even if you put in the order you described:

```php
<?php

// @var $bar \Foo\Bar
$bar->doSomething();
```

The same thing happens:

```php
<?php

// @var $bar \Foo\Bar
$bar->doSomething();
```

**Comment by keradus** [comment]
hm. interesting

**Comment by SpacePossum** [comment]
Verified on master, for both PHPDocs.

Btw. there is also a priority issue at hand.
Using config provided above:
Input
```php
<?php

/** Test */
$bar->doSomething();
```

after run 1:
```
<?php

declare(strict_types=1);
/** Test */
$bar->doSomething();
```

run again:
```
<?php

declare(strict_types=1);
// Test
$bar->doSomething();
```

**Comment by mnabialek** [comment]
Is it not connected to:

        '@Symfony' => true,


set of rules?

I had similar issue and when having config file:

```
<?php

$rules = [
    'phpdoc_to_comment' => true,
];

$finder = PhpCsFixer\Finder::create()
    ->in([
        __DIR__ . '/app',
        __DIR__ . '/tests',
        __DIR__ . '/config',
        __DIR__ . '/database',
    ]);

return PhpCsFixer\Config::create()
    ->setRules($rules)
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setUsingCache(true);
```

when my file is:

```
<?php
use App\Models\Db\User;

/** @var User $bar */
$bar->doSomething();
```

after running fixer it will get converted into:

```
<?php
use App\Models\Db\User;

/* @var User $bar */
$bar->doSomething();
```

So when my rules would become like this:

```
$rules = [
    'phpdoc_to_comment' => true,
    'single_line_comment_style' => true,
];
```

then final result would be:

```
<?php
use App\Models\Db\User;

// @var User $bar
$bar->doSomething();
```

So the be honest this `phpdoc_to_comment` fixer  is really strange and quite misleading when you start using it because it might cause problems like this and I think I was somehow misleaded by this rule and created this https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3003 because I thought this was `single_line_comment_style` fixer fault

**Comment by SpacePossum** [comment]
I looked into this a bit more.

1 - The priority issue is with the declare strict fixer; the PHPDoc to comment fixer skips the first PHPDoc as it assumes it might be an header. However if there is a declare strict statement it does not assume the next PHPDoc might be an header

2 - PHPDoc with `@var` before something like `$bar->doSomething();` is "fixed" before `$bar` is not declared, 'only' used

3 - PHPDoc with something like
```
<?php

/* @var User $bar */
($bar = tmp())->doSomething();
```

is also 'fixed' to comment, which is a bug

4
```
<?php

/* @var User $bar */
list($bar) = a();
```

is also 'fixed' to comment, which is a bug (same with short destruction syntax), which is a bug

**Comment by SpacePossum** [comment]
5

```
 /**
  * @var ClassLoader $loader
  */
 $loader = require __DIR__.'/../vendor/autoload.php';
```

is also 'fixed' to comment, which is a bug as `$loader` is introduced and assigned here

**Comment by coatesap** [comment]
+1 - The `phpdoc_to_comment` rule is a good one, but currently breaks other useful docblock-style comments like `/** @noinspection PhpUnhandledExceptionInspection */`.

**Comment by bkrnetic** [comment]
Still no fix for this?

**Comment by kubawerlos** [comment]
Everything mentioned here is fixed:
 - `single_line_comment_style` is not "quity"
 - the priority issue is no longer - `phpdoc_to_comment` recognises `declare` when searching for header comment
 - for @coatesap - `phpdoc_to_comment` is relying on structural element defined here: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions
 -  issue with parenthesis is also solved: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.4/tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php#L541

Currently `phpdoc_to_comment` has opened PR to add ignore tags: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5572
