### ISSUE TITLE
php-cs-fix not fixing the issues - Files that were not fixed due to errors reported during linting before fixing

### ISSUE THREAD

**Issue by vishytk** [FriendsOfPHP/PHP-CS-Fixer#3014]
`<?php`

class Foo {
    public $name;
    public $age

    public function myMethod($name) {
    
        $this->$name
    }
}

$ php-cs-fixer fix class.php
Loaded config default.
Fixed all files in 0.002 seconds, 6.000 MB memory used

Files that were not fixed due to errors reported during linting before fixing:
   1) /home/vishy/php/class.php

PHP=> 7.1.8, PHP-CS-FIXER=> 2.5.0

$ cat .php_cs.cache
{"php":"7.1.8","version":"2.5.0:v2.5.0#63aad575ec2a29d50eb6c3b5cbc17430b28895b2","rules":{"blank_line_after_namespace":true,"braces":true,"class_definition":true,"elseif":true,"function_declaration":true,"indentation_type":true,"line_ending":true,"lowercase_constants":true,"lowercase_keywords":true,"method_argument_space":{"ensure_fully_multiline":true},"no_break_comment":true,"no_closing_tag":true,"no_spaces_after_function_name":true,"no_spaces_inside_parenthesis":true,"no_trailing_whitespace":true,"no_trailing_whitespace_in_comment":true,"single_blank_line_at_eof":true,"single_class_element_per_statement":{"elements":["property"]},"single_import_per_statement":true,"single_line_after_imports":true,"switch_case_semicolon_to_colon":true,"switch_case_space":true,"visibility_required":true,"encoding":true,"full_opening_tag":true},"hashes":[]}%

**Comment by julienfalque** [comment]
This is expected: your input file has a syntax error (missing semisolon after `$age` property) so the tool will skip it.
