### ISSUE TITLE
Not removing unused import if has same name function

### ISSUE THREAD

**Issue by abhimanyu003** [FriendsOfPHP/PHP-CS-Fixer#3020]
PHP CS Fixer not removing unused import that has the same name as that of the function used somewhere in class.

*Sample Code*

```php
<?php

namespace App\Controllers;

use App\Api\Controller;
use Zend\Diactoros\Exception;

class ValidationController extends Controller
{
    public function ipSubnet()
    {
        return exception('Something', 404);
    }
}
```

*Expected Code*

```php
<?php

namespace App\Controllers;

use App\Api\Controller;
// Remove unused import here

class ValidationController extends Controller
{
    public function ipSubnet()
    {
        return exception('Something', 404);
    }
}
```

The PHP version you are using:
$ php -v
```
PHP 7.1.9 (cli) (built: Aug 30 2017 18:58:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

PHP CS Fixer version you are using:
$ php-cs-fixer -V
```
PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski (63661f3)
```

**Comment by keradus** [comment]
Hi. Thanks you for your report :+1:
It looks like sth we could improve for sure, happily it's not causing issues for changed code.
Sadly, maintainers here cannot handle all filed issues themselves.
Could you help with it and propose a solution (probably for 2.2 branch) ?

**Comment by julienfalque** [comment]
Related: #2814.

**Comment by SpacePossum** [comment]
it is and it isn't related I think, `function` imports and class imports are done explicitly so could be checked against, with or without checking comments and/or PHPDocs.
