### ISSUE TITLE
new fixer: echo sprintf -> printf

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#3025]
i hereby suggest creating such fixer:

```php
echo sprintf("Usage: %s ARGUMENTS\n", $argv[0]);
```
--> 
```php
printf("Usage: %s ARGUMENTS\n", $argv[0]);
```

**Comment by keradus** [comment]
While I do agree this change is fine, I'm not sure is there a need for such a fixer.
Would anyone else willing to have it ?

**Comment by keradus** [comment]
I see there would not be one
