### ISSUE TITLE
lowercase_constants: Enable different casing for true/false and null constants.

### ISSUE THREAD

**Issue by RomanHodulak** [FriendsOfPHP/PHP-CS-Fixer#3026]
In the company where I work, we use lowercase true/false constants and uppercase NULL constant. Since lowercase_constants cannot differentiate between those, it is impossible for us to set proper rules.

Could you add the option to set different casing for null and true/false?

**Comment by keradus** [comment]
big :-1:
it's violating PSR-2 in general and consistency of casing those trivials

**Comment by SpacePossum** [comment]
lets see if there is a bigger community which follows this conversion, till than I'm +0

**Comment by SpacePossum** [comment]
I'm closing this as there does not seem a bigger use of this standard. This doesn't mean I'm judging the standard wrong or whatever.

However the scope of this project is to provide a way to fix PHP code to a wide used standard. Besides advocating usage of wide used standards it is also we'll have more support for maintaining code related to such standards as there is a bigger community interest in it.

You can always create a custom fixer to suit your project needs, copy-pasting the fixer, renaming it and adjust it to fix `null` to uppercase shouldn't be hard. If you decide to give it a try please let me know if you want me to help out with if you get stuck with it.

**Comment by RomanHodulak** [comment]
Thank you for your comments. We've discussed this and ended up changing the standard, so our code uses all these constants in lowercase 🙂

**Comment by SpacePossum** [comment]
great to hear :)  thanks for reporting back!
