### ISSUE TITLE
Load JSON rules from file

### ISSUE THREAD

**Issue by RomanHodulak** [FriendsOfPHP/PHP-CS-Fixer#3027]
Unless I missed something, there is no way to set `--rules` to point to a JSON file. Therefore if I want to have my set of rules stored in a file, I have to do something like `--rules="$(cat cs-rules.json)"`.

Could you add a support for loading JSON rulesets from file(s)?

**Comment by keradus** [comment]
If you want to have your rules in a file, use `.php_cs.dist` config file
