### ISSUE TITLE
Incompatible with PHPUnit 6.3.0

### ISSUE THREAD

**Issue by inoas** [FriendsOfPHP/PHP-CS-Fixer#3028]
When requiring `PHPUnit 6.3.0` it will require `sebastian/diff ^2.0` whereas even the latest `PHP-CS-Fixer` still requires ` "sebastian/diff": "^1.4",`

**Comment by SpacePossum** [comment]
duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2993
