### ISSUE TITLE
Last tabs are changed to 4 spaces in nested arrays in multi-line comments

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3030]
The PHP version you are using: `7.1.8`

PHP CS Fixer version you are using: `2.5.0`

The command you use to run the fixer (and the configuration file you are using if any).

`vendor/bin/php-cs-fixer fix`

A minimal sample of valid PHP code that is not fixed correctly (if applicable).

File: (indent tabs)

```
<?php

return [
	[
		/*
		 * Nice
		 */
		'hi',
	],
];
```

Config:

```
<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

return Config::create()
	->setIndent("\t")
	->setRules([
		'@Symfony' => true,
		'array_syntax' => ['syntax' => 'short'],
		'ordered_imports' => true,
	])
	->setFinder(
		Finder::create()
			->in(__DIR__)
	);
```

The fixed version of that code after you run the fixer and the version you expected.

Fixed: (might want to view whitespace)

```
<?php

return [
	[
		/*
	     * Nice
	     */
		'hi',
	],
];
```

Expected not to change.

**Comment by keradus** [comment]
Hi @ntzm 
Thank you for your complete report, it helps a lot to track it down !

Could you please verify fix proposal: #3031 ?
