### ISSUE TITLE
New fixer: ErrorSuppressionFixer

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3035]
What about fixer with this description:

* **no_errors_suppression**

  There should not be ``@`` before functions.

  Configuration options:

  - ``exclude`` (``array``): list of functions to ignore; defaults to ``[]``

**Comment by keradus** [comment]
Hi.
This rule would be conflicting with `silenced_deprecation_error` rule, which enforces `@` for `trigger_error` (for `E_USER_DEPRECATE`).
Please propose a solution to get non-conflicting rules.

**Comment by kubawerlos** [comment]
Then maybe something like this:

* **error_suppression**

  Removes or ensures suppression of error messages.

  Configuration options:

  - ``allow`` (``array``): list of functions allowed to have error suppresion; defaults to ``[]``
  - ``ensure`` (``array``): list of functions required to have error suppresion; defaults to ``['trigger_error']``

That way all functions not in ``allow`` or ``ensure`` lists would have error suppresion removed. This will make fixer ``silenced_deprecation_error`` deprecated.

**Comment by keradus** [comment]
good direction, yet not enough. in that scenario, how to achieve behaviour of newly deprecated rule with new fixer?

using `ensure=>['trigger_error']` as config for new fixer would:
- put `@` for all `trigger_error` usage, not only user deprecations
- remove `@` from other cases

both things are not done by `silenced_deprecation_error` rule

**Comment by kubawerlos** [comment]
To achieve `silenced_deprecation_error ` with the generalised  `allow`/`ensure` approach, fixer would need 2-dimensional array with first parameter of function as 2nd dimension - this even sounds like a horrible idea.

Maybe a fixer with 2 flags:
- `silence_deprecation_error` with `bool, defaults to `true`
- `noise_other_cases` with `bool`, defaults to `false`

Not a brilliant either, but could replace and extend `silenced_deprecation_error`. I think that also would cover most real life scenarios, when the goal is not to use `@`, except deprecation errors.

**Comment by keradus** [comment]
not most generic approach, but probably cleanest one indeed.
option names would benefit a little grooming, also option value shall accept `null` (to leave it as-is, eg when one want to ensure `@` for user deprecations, yet don't touch anything else)

Looks nice. Do you want to make new PR for this new fixer and deprecating existing one ?

**Comment by kubawerlos** [comment]
@keradus I have answered your comments in PR.
