### ISSUE TITLE
phpdoc_summary treats description as summary

### ISSUE THREAD

**Issue by Synchro** [FriendsOfPHP/PHP-CS-Fixer#3041]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/FriendsOfPHP/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
7.1.8

PHP CS Fixer version you are using:
2.2.6

The command you use to run the fixer (and the configuration file you are using if any).

`.php_cs` rules:
```
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => false,
        'concat_space' => ['spacing' => 'one'],
        'heredoc_to_nowdoc' => true,
        'method_argument_space' => true,
        'no_extra_consecutive_blank_lines' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block'],
        'no_php4_constructor' => true,
        'no_short_echo_tag' => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => true,
        'phpdoc_add_missing_param_annotation' => true,
        'phpdoc_order' => true,
        'psr4' => false,
        'semicolon_after_instruction' => true,
        'simplified_null_return' => true,
```
A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
/**
 * I am a summary.
 * Here is an example:
 *
 * ```php
 * echo 'hi';
 * ```
 */
```

The fixed version of that code after you run the fixer and the version you expected.

```php
/**
 * I am a summary.
 * Here is an example:.
 *
 * ```php
 * echo 'hi';
 * ```
 */
```

It adds a trailing `.` after `example:`, i.e. it's treating it as the end of a summary, not part of a description.

I think this is done by the `phpdoc_summary` rule, which enforces a summary ending with a `.`, `?` or `!`. However, in [PHPDoc terminology](https://docs.phpdoc.org/guides/docblocks.html), a summary explicitly refers to only the first line in the docblock; the remaining untagged text is supposedly free-form description, and should not have the same strict definition applied.

**Comment by GrahamCampbell** [comment]
This is the correct behaviour. You are missing an extra blank line of phpdoc after your first fullstop.

**Comment by GrahamCampbell** [comment]
```php
/**
 * I am a summary.
 *
 * Here is an example:
 *
 * ```php
 * echo 'hi';
 * ```
 */
```

**Comment by keradus** [comment]
@GrahamCampbell is right. 
To fulfill the picture: `Here is an example` part is `description` accorting to PPHDoc

thanks for answering here Graham.

**Comment by keradus** [comment]
> However, in PHPDoc terminology, a summary explicitly refers to only the first line in the docblock

actually, no.
We are follogin PSR-5 proposal actually, but both, PSR-5 and PHPDoc define summary as short, initial sentence, **usually** one-liner, but it could be multilined.
Quote from your own link:
> A short piece of text, usually one line, providing the basic function of the associated element.
