### ISSUE TITLE
2.6 Reverses my if statements

### ISSUE THREAD

**Issue by beschoenen** [FriendsOfPHP/PHP-CS-Fixer#3046]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

2.6 is reversing if statements that it shouldn't be, works perfectly in 2.5.*

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v

```
PHP 7.1.8 (cli) (built: Aug 17 2017 10:13:55) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

PHP CS Fixer version you are using:
$ php-cs-fixer -V
```
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski
```

The command you use to run the fixer (and the configuration file you are using if any).
```
php vendor/bin/php-cs-fixer fix --allow-risky yes
```

```php
<?php

$finder = PhpCsFixer\Finder::create()->in([
    __DIR__ . '/app',
    __DIR__ . '/config',
    __DIR__ . '/database',
    __DIR__ . '/docs',
    __DIR__ . '/resources',
    __DIR__ . '/routes',
    __DIR__ . '/tests',
]);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_blank_lines_after_class_opening' => false,
        'no_useless_else' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'no_blank_lines_before_namespace' => false,
        'ordered_imports' => ['sortAlgorithm' => 'alpha'],
        'return_type_declaration' => ['space_before' => 'none'],
        'psr4' => true,
        'elseif' => false,
        'phpdoc_to_comment' => false,
    ])
    ->setUsingCache(true)
    ->setFinder($finder);
```

A minimal sample of valid PHP code that is not fixed correctly (if applicable).
N/A

The fixed version of that code after you run the fixer and the version you expected.
N/A

Sample of code changed, that shouldn't be:
```
--- a/app/Console/Commands/MakeAdmin.php
+++ b/app/Console/Commands/MakeAdmin.php
@@ -30,7 +30,7 @@ class MakeAdmin extends Command
         /** @var User $user */
         $user = User::find($this->argument('user'));
 
-        if ($user == null) {
+        if (null == $user) {
             $this->error('User does not exist!');
 
             return 1;
```

**Comment by SpacePossum** [comment]
Hi and thanks for all the details,

This is because of the Yoda-style fixer which is enabled by default for the `@Symfony`-set.
You can disable it using (in the array passed for `->setRules`):

`'yoda_style' => false,`

Or you can configure this rule to suit your project needs.

**Comment by beschoenen** [comment]
Why didn't it do this before 2.6?

**Comment by julienfalque** [comment]
Because the `yoda_style` fixer has been introduced and added to the `@Symfony` rule set in 2.6.

**Comment by keradus** [comment]
you know, we follow SEMVER, and new MINOR release is always supposed to bring new... feature.
In PHP CS Fixer land, feature=rule.
