### ISSUE TITLE
CombineConsecutiveIssetsFixer - priority breaks PSR2

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3050]
In 2.6 having this code:
```php
if (isset($x->foo) && isset($x->bar)) {
}
```
and running `CombineConsecutiveIssetsFixer` results with:
```php
if (isset($x->foo, $x->bar)  ) {
}
```

It would be fixed by `NoSpacesInsideParenthesisFixer` (part of PSR2), but unfortunately priority of `CombineConsecutiveIssetsFixer` is `1` while for `NoSpacesInsideParenthesisFixer` it's `2`.

Due to other restrictions in priorities doesn't look easy to fix.

BTW @keradus have you considered refactoring priorities e.g. instead of `getPriority` having 2 functions like `runBefore` and `runAfter` with list of fixer depending of it?

**Comment by keradus** [comment]
there was an attempt to do it, no nice solution was found to handle priority dependencies across build-in and custom-user fixers.
