### ISSUE TITLE
NativeFunctionInvocationFixer is incompatible with imported functions

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#3051]
The following code would add a `\` while the function being called is known *not* to be the internal one at compile time, due to the use statement:

```php
namespace Foo;

use function GuzzleHttp\json_encode;

echo json_encode('foo');
```

Triggering this bug requires having a function with the same name than an internal function, but this happens.

**Comment by keradus** [comment]
Hi. Thanks for report. Could you send a bugfix for it ?

**Comment by SpacePossum** [comment]
Would be great improvement. 
Tagged as improvement as the fixer is marked risky for this case.

**Comment by stof** [comment]
Well, being risky is not only related to the fact that `use function` statements are unsupported. The main risk comes from the fallback feature (functions defined in the same namespace, where you would not need to import them).

Use statements would be a case where you would know that the `\` must not be added. But supporting them would not make the fixer out of risky.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4846
