### ISSUE TITLE
IncrementStyleFixer

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3056]
Some say pre incrementation/decrementation should be used if possible, other say this micro optimization comes at the cost of readability. Sumarizing: I'd like to propose a fixer to replace `pre_increment` one with description:

* **increment_style**

  Pre or post increment and decrement operators should be used.

  Configuration options:

  - ``style`` (``'pre'``, ``'post'``): whether to use the ``pre`` or ``post``increment and decrement operators; defaults to ``'pre'``

Obviously it won't be new fixer, more a modification of `pre_increment`, but configuration above looks cleaner than using `pre_increment` with `false` to achieve post increment/decrement operators.

**Comment by keradus** [comment]
+/- 0
+0.5 if implementation won't create too big changes (so won't introduce more code to maintain)
