### ISSUE TITLE
Changing 3-lines PHPDoc @var to single line.

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3061]
I cannot find how I can configure to have this:
```php
    /**
     * @var Foo
     */
    protected $bar;
```
being fixed to this:
```php
    /** @var Foo */
    protected $bar;
```

I know there is `phpdoc_single_line_var_spacing`, but obviously it's not going to do that? Maybe a new fixer or extension to the mentioned one?

**Comment by julienfalque** [comment]
This is not possible at the moment but it was already requested in #2646, we just need someone to take care of it :)

Closing as duplicate.
