### ISSUE TITLE
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.1.*.

### ISSUE THREAD

**Issue by harikt** [FriendsOfPHP/PHP-CS-Fixer#3066]
The PHP version you are using:
$ php -v

```
PHP 7.2.0RC1 (cli) (built: Sep  4 2017 08:42:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC1, Copyright (c) 1999-2017, by Zend Technologies
```

PHP CS Fixer version you are using:
$ php-cs-fixer -V

The above command will not work in 7.2, but I have multiple php version, so was able to run the phar one.

```
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski (5642a36)
```

Problem is once you upgrade you can't even run the 

```
phpcs self-update 
```

commands. Probably the upper version constraint can be removed or making it higer which the php version is not yet released. Eg : 8.

UPDATE : I forgot to ask one question, does it have any known issues with 7.2 that the constraint is put ?

**Comment by keradus** [comment]
Please use search functionality before raising new issue.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2907

This application is not a regular application that **runs** the code.
This application also **understands** the syntax. 
most of PHP non-bugfixes releases are BC breaker for us, as they introduce new syntax that we need to learn and understand.

Here, it doesn't mean we need to write some new rules that would enhance using 7.2 (like we have multiple php migration rules).
It means that we need to ensure all existing fixers won't crash during reading the code written with 7.2 syntax.

If you want to try current version on PHP we don't yet fully support, you may try to set `PHP_CS_FIXER_IGNORE_ENV=1` env variable. Be aware that it is not fixing an issue, it is bypassing the safe check. If you encounter problem during that, it's not weird, yet please raise an issue report, it will help us get 7.2 support sooner.

Closing as duplicate.

**Comment by harikt** [comment]
Sorry, I tried the search, but only one issue was shown. Which wasn't relevant . I may need to improve the search criteria next time.

**Comment by SpacePossum** [comment]
Thanks @harikt :+1: ,
Please have a look/review @ https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3038 , it is the PR I try to wrap up PHP7.2 compat things (not bringing new features, just making sure we deal with 7.2 nicely).

**Comment by olamedia** [comment]
Same issue
```# sudo php-cs-fixer self-update
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
# php -v
PHP 7.2.15 (cli) (built: Mar  2 2019 02:10:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by keradus** [comment]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4331#issuecomment-470704922
