### ISSUE TITLE
Disappearing function argument

### ISSUE THREAD

**Issue by nullref** [FriendsOfPHP/PHP-CS-Fixer#3067]
PHP-CS-Fixer 5642a36 with default settings running on PHP 7.1.9 exhibits a bug where a function argument is dropped if there is no space after the previous argument's comma and the next argument is on the next line together with the closing parenthesis.

```diff
% vendor/bin/php-cs-fixer fix --dry-run --diff test.php 
Loaded config default.
Using cache file ".php_cs.cache".
   1) test.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

-f(1,2,
-3);
+f(
+    1,
+    ,
+3
+);
      ----------- end diff -----------
```

The argument "2" was removed.

**Comment by keradus** [comment]
Very interesting case indeed and I totally confirm it's sth extra important to fix.
Yet, we can't fix it ! Why ? You refused to provide all info we asked you for :(

Please, to make it possible to fix the issue, fill the template:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE

**Comment by SpacePossum** [comment]
O. o which fixer does this?

**Comment by keradus** [comment]
`method_argument_space`

**Comment by keradus** [comment]
broken since 2.4.x, to be fixed with current stable 2.6

**Comment by nullref** [comment]
I've taken a look at the code and isolated the behavior to the ensureFunctionFullyMultiline method in the MethodArgumentSpaceFixer class, more specifically the code run by fixNewline when $override is set to true.

As for an actual fix, I'm not sure.  Perhaps the actual problem is in fixSpace2 which states it adds spaces after commas, which appears not to have been done in this case.

**Comment by keradus** [comment]
utest added: #3069
thanks for hint @nullref 
I will try to play with it tomorrow, so if you want to take even deeper look before me - go ahead ;)

at 2.4.0 we added new option (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440), and that option is causing the issue.
