### ISSUE TITLE
The is_null fixer breaks on certain files

### ISSUE THREAD

**Issue by SteveJobzniak** [FriendsOfPHP/PHP-CS-Fixer#3071]
The is_null fixer worked on every file of our project except for one. It's strange, since similar lines of code (following this `addParam('bleh', (is_null())` format) were successfully converted in other files.

I'm reporting it, since it's apparently a bug in the tokenizer and/or the IsNullFixer.

PHP-CS-Fixer version: 2.6.

Test file which breaks:

- https://raw.githubusercontent.com/mgp25/Instagram-API/b145c9c077d41c599a071629a1b91e13b5aa3242/src/Request/Timeline.php

PHP_CS Configuration:

```php
<?php

return PhpCsFixer\Config::create()
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->in(__DIR__)
    )
    ->setIndent('    ')
    ->setLineEnding("\n")
    ->setRules([
        '@Symfony'                            => true,
        // Override @Symfony rules
        'pre_increment'                       => false,
        'blank_line_before_statement'         => ['statements' => ['return', 'try', 'throw']],
        'phpdoc_align'                        => ['tags' => ['param', 'throws']],
        'method_argument_space'               => ['ensure_fully_multiline' => false],
        'binary_operator_spaces'              => [
            'align_double_arrow' => true,
            'align_equals'       => false,
        ],
        'phpdoc_annotation_without_dot'       => false,
        'yoda_style'                          => [
            // Symfony writes their conditions backwards; we use normal order.
            'equal'            => false,
            'identical'        => false,
            'less_and_greater' => false,
        ],
        'is_null'                             => [
            // Replaces all is_null() with === null.
            'use_yoda_style' => false,
        ],
        // Custom rules
        'align_multiline_comment'             => true,
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
        'ordered_imports'                     => true,
        'phpdoc_order'                        => true,
        'array_syntax'                        => ['syntax' => 'short'],
    ]);
```

Command used:

`./vendor/bin/php-cs-fixer fix --config=.php_cs.dist --allow-risky yes -vvv`

Error output:

```
Loaded config default from ".php_cs.dist".
Using cache file ".php_cs.cache".
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Fixed all files in 0.449 seconds, 10.000 MB memory used

Files that were not fixed due to errors reported during fixing:
   1) /home/foo/project/vendor/mgp25/instagram-php/src/Request/Timeline.php

                             
        [ErrorException]     
        Undefined offset: 1  
                             

      {closure}()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Token.php at line 61
      PhpCsFixer\Tokenizer\Token->__construct()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/Fixer/LanguageConstruct/IsNullFixer.php at line 167
      PhpCsFixer\Fixer\LanguageConstruct\IsNullFixer->applyFix()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 73
      PhpCsFixer\AbstractFixer->fix()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 188
      PhpCsFixer\Runner\Runner->fixFile()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 131
      PhpCsFixer\Runner\Runner->fix()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php at line 205
      PhpCsFixer\Console\Command\FixCommand->execute()
        in /home/foo/project/vendor/mgp25/instagram-php/vendor/symfony/console/Command/Command.php at line 264
      [ ... ]
```

**Comment by keradus** [comment]
We consider assignment inside condition check as bad practice...
That's probably the reason why we didn't covered such case

**Comment by SteveJobzniak** [comment]
Ah, so it breaks on `while (!is_null($nextMaxId = $myTimeline->getNextMaxId()));`!

That's definitely bad practice, and I didn't write that line. :-) But even though I'll gladly fix that line of code, such a problem can exist in many other projects (I've often seen that code style by people who try to be clever).

An "assignment inside condition check" can be safely rewritten as `!is_null($nextMaxId = $myTimeline->getNextMaxId())` === `null !== ($nextMaxId = $myTimeline->getNextMaxId())`. If you'll consider updating the token parser to handle it.

**Comment by keradus** [comment]
I'm not saying it shall not be fixed, I'm saying why we forgot to handle it ;)
(btw, I didn't wrote that rule as well as you didn't wrote that code ;P)

failing case extracted to PR: #3072

**Comment by SteveJobzniak** [comment]
@keradus Hehe okay, I understand. 👍

**Comment by julienfalque** [comment]
Out of curiosity, why do you consider assignment inside conditions check a bad practice?

**Comment by keradus** [comment]
single responsibility, you want to check sth or assign sth ?
assigning sth inside check is considered to be a side effect

**Comment by SteveJobzniak** [comment]
Also because it makes the code difficult to read, and bug-prone. Small mistakes can easily screw up a line that says `null !== ($nextMaxId = $myTimeline->getNextMaxId())`.

**Comment by cyrrill** [comment]
@keradus I don't see the "no assignment in conditional" within the list of applicable rules.

https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#avoid-conditional-assigment

Is it an implicit check inside another rule, and I'm just missing it, or hasn't been implemented yet?

Thanks

**Comment by SpacePossum** [comment]
Hi @cyrrill 

Currently we have no rule/fixer for `assignment in conditional`. We rely on reviews in the project here to catch it I think.
(reminds me to enable `IfStatementAssignment` in PHPMD configuration)

**Comment by cyrrill** [comment]
Hi @SpacePossum 

Thanks for the reply, but it's a bit unclear to me what you mean by 

> We rely on reviews in the project here to catch it I think.

If it goes against the established PSR-2 guidelines, wouldn't it make sense to make it an automatic checking rule?

**Comment by SpacePossum** [comment]
It would be nice to have such a rule, but it will be very hard to make I think. 
For now I'm just stating the fact we do not have it and therefore we currently rely on reviews in this project.

**Comment by cyrrill** [comment]
Thanks @SpacePossum, yep, I totally understand what you mean.

However, I disagree that it would be very hard to make. You basically just have to match a single `=` inside an `if`.

The regex (which I haven't really tested) provided by the Stackoverflow above mentions it could be as simple as:

```
if\([^=]\|==\+\)*[^=]=[^=]\([^=]\|==\+\)*$
```

If I put in a PR for this, is it likely to get merged?
