### ISSUE TITLE
single_blank_line_before_namespace doesn't add a blank line if on first line

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#3081]
> The PHP version you are using:

`PHP 7.1.6 (cli) (built: Jun  8 2017 02:06:32) ( ZTS MSVC14 (Visual C++ 2015) x86 )`

> PHP CS Fixer version you are using:

`PHP CS Fixer 2.7.0-DEV by Fabien Potencier and Dariusz Ruminski`

> The command you use to run the fixer:

`php-cs-fixer fix --dry-run --diff --rules=single_blank_line_before_namespace test.php`

> A minimal sample of valid PHP code that is not fixed correctly:

```php
<?php
namespace X;
```

> The fixed version of that code after you run the fixer and the version you expected.

Current output:
```php
<?php
namespace X;
```
Expected output:
```php
<?php

namespace X;
```

I think that the root cause is that `token_get_all` returns a single token for the opening tag (eg the first token is `[T_OPEN_TAG, "<?php\n", 1]`) - see https://3v4l.org/38K9F.

**Comment by SpacePossum** [comment]
Thanks for reporting.
Looks like a valid analyze on this issue.

**Comment by mlocati** [comment]
I'm almost ready to submit a pull request to fix this issue.

**Comment by mlocati** [comment]
See #3083
