### ISSUE TITLE
[docs] How to add own context values to error message?

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#3086]
I use this feature from PHP_CodeSniffer and wonder if there is way to use it here as well.

I know that error message is first argument of `FixerDefinition` class.

With [this setup](https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Php/ClassStringToClassConstantFixer.php#L51):

```php
public function getDefinition(): FixerDefinitionInterfaceproperty
{
    return new FixerDefinition(
        '`::class` references should be used over string for classes and interfaces.',
        [   new CodeSample('<?php $className = "DateTime";'),
        ]
    );
}
```

I get this error:

```
`::class` references should be used over string for classes and             
         interfaces.      
```

**Is there a way to have own arguments like wrong token content?**

```
`DateTime::class` references should be used over "DateTime" string for classes and             
         interfaces.      
```

Thils would help me to locate issue more quickly, since Fixer already does it for me.

**Comment by keradus** [comment]
Hi. Actually, those are not error messages, those are Rule/Fixer summaries.
They are suppose to describe the rule fixer is fixing, not report each violation. For that, they are not customizable.

Keep in mind that if there are 2 violations in one file, PHP CS Fixer doesn't report them twice, it just report that given file is violating that rule, and by default fix the violations

**Comment by TomasVotruba** [comment]
Thanks for fast reply.

Do you think there is any elegant way to add this functionality?

**Comment by TomasVotruba** [comment]
Thanks for fast reply.

Do you think there is any elegant way to add this functionality?

**Comment by keradus** [comment]
if I got your feature request right, there is not a nice way. As this tool is focusing on fixing, not on reporting.

**Comment by TomasVotruba** [comment]
I see.

> As this tool is focusing on fixing, not on reporting.

That makes sense.

**Comment by keradus** [comment]
actually, during runner, when we process file fixer by fixer, you could hook in (like in hacky way, no such feature currently), and you could observe the tokens collection to know which part was modified. but probably easier with analysing diff anyway

**Comment by TomasVotruba** [comment]
I see. That could go. But it would require some external dependency to allow fixer to work. 
I was rather looking for some build-in feature, that I could use without any extra modifications. 

Now it seem too complicated idea for the value it would bring. Thanks for consulting though
