### ISSUE TITLE
New fixer: Bareword strings fix

### ISSUE THREAD

**Issue by kykint** [FriendsOfPHP/PHP-CS-Fixer#3090]
In upcoming PHP 7.2 there is incompatible change (and in php 8 will be error):

> Unqualified references to undefined constants now generate a Warning instead
>     of a notice. They will generate an Error in a future version of PHP.
> (https://wiki.php.net/rfc/deprecate-bareword-strings)

There are a lot of people and a lot of projects where bareword strings could be used:
`$foo[bar] = 5;`
`$foo = [bar => 5];`

They must be changed to:
`$foo['bar'] = 5;`
`$foo = ['bar' => 5];`

Note:
Next code is ok and must not be changed:
`$foo = "Lorem $bar[baz] ipsum";`
But next code must:
`$foo = "Lorem {$bar[baz]} ipsum";`
to
`$foo = "Lorem {$bar['baz']} ipsum";`

**Comment by keradus** [comment]
it could be interesting even for PHP <7.2 m;)\


> There are a lot of people and a lot of projects where bareword strings could be used:

is it? why? which?

**Comment by kykint** [comment]
I just saw that many times, and faced with such project:) I think such fixer can be useful

**Comment by keradus** [comment]
each fixer
- demands CPU power during PHP CS Fixer execution
- requires maintenance 

for that, we try to have rules that are widely used

where did you saw it? I didn't saw it in any open source repo I played with for last 3 years, at least.

**Comment by julienfalque** [comment]
I think this only happens in old legacy projects, not sure it's worth it. I don't even think the fixer for that would have a reliable way to detect whether a constant is defined.

**Comment by keradus** [comment]
Closing due to concern raised by Julien and lack of further discussion.
