### ISSUE TITLE
New fixer: proper casting to number

### ISSUE THREAD

**Issue by frmrgr** [FriendsOfPHP/PHP-CS-Fixer#3091]
In php 7.1, in accordance with an [invalid strings in arithmetic RFC](https://wiki.php.net/rfc/invalid_strings_in_arithmetic) a warning is emitted in case of an arithmetic operation acting on a non-numeric string. This creates a problem for a variety of projects which use  `$var * 1` pattern for casting an arbitrary value to a number. In particular, a standard way of mapping empty value to zero `$empty_string * 1` now generates a warning `A non-numeric value encountered on line X`.

Therefore it is suggested to create a new fixer, which would replace all expressions of form `value * 1`, `value *= 1`, `value + 0` and `value += 0` with `(float) (value)`, `value = (float) (value)`, `(float) (value)` and `value = (float) (value)` correspondingly, where `value` is either variable or an element of an array.

Examples:

    $countValue = $_GET['count'] * 1; // was
    $countValue = $_GET['count'] + 0; // was
    $countValue = (float) $_GET['count']; // both should become

    $value_from_file *= 1; // was
    $value_from_file += 0; // was
    $value_from_file = (float) $value_from_file; // both should become

**Comment by SpacePossum** [comment]
All the implicit cast trickery like `$a + 0` (https://3v4l.org/jSqkK) has been around for sometime (I remember something like it from Java for strings concat).
However, I wonder if this case isn't to rare to fix. Is there any community that is really effected by this anti-pattern?

**Comment by SpacePossum** [comment]
```
$countValue = $_GET['count'] + 0; // was
$countValue = (float) $_GET['count']; // both should become
```

this depends on the input value (` $_GET['count']`), for example;
```
<?php

$a = '1';
$a = $a + 0;
var_dump($a);

$a = '1.1';
$a = $a + 0;
var_dump($a);

die;
```

```
int(1)
float(1.1)
```

https://3v4l.org/HHoNY

The problem is that there will be a lot of cases where we cannot, within acceptable risky-range, know (or guess) what the cast should be. 
As such, I really like the idea but this is out of the scope of the project, thanks for bringing the idea!
