### ISSUE TITLE
Incompatibility when installing with PHPUnit 6.3.* release series

### ISSUE THREAD

**Issue by devdrops** [FriendsOfPHP/PHP-CS-Fixer#3095]
Noticed today a conflict when installing (using Composer) the latest releases for both PHP CS Fixer and PHPUnit. Details below:

- PHP Version

```
PHP 7.1.4 (cli) (built: Apr 25 2017 03:19:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

- PHP CS Fixer version

```
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski
```

The issue happens when installing globally on the same environment along with the latest PHPUnit version series (6.3.0 or 6.3.1, at the present moment).

- Steps to reproduce:

On a new-fresh environment (Docker here, `php:7.1-cli`), run:

```
RUN composer global require     phpunit/phpunit     squizlabs/php_codesniffer     friendsofphp/php-cs-fixer     phpmd/phpmd     behat/behat
```

Output:

```
Using version ^6.3 for phpunit/phpunit
Using version ^3.1 for squizlabs/php_codesniffer
Using version ^2.6 for friendsofphp/php-cs-fixer
Using version ^2.6 for phpmd/phpmd
Using version ^3.4 for behat/behat
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for friendsofphp/php-cs-fixer ^2.6 -> satisfiable by friendsofphp/php-cs-fixer[v2.6.0].
    - phpunit/phpunit 6.3.0 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.3.1 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - Conclusion: don't install sebastian/diff 2.0.1
    - Installation request for phpunit/phpunit ^6.3 -> satisfiable by phpunit/phpunit[6.3.0, 6.3.1].


Installation failed, deleting ./composer.json.
```
As `friendsofphp/php-cs-fixer` requires `sebastian/diff ^1.4`, it generates a conflict with PHPUnit requirements.

I'm not sure if this is the right place to report this issue and I'm not saying that this project should fix it ASAP (or even that it is its own responsibility to do so), but I believe that it would be nice to notify about this problem. Any suggestions/tips are really appreciated.

**Comment by orlangur** [comment]
Please search for issues before reporting a new one, duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3028.

**Comment by devdrops** [comment]
Thanks @orlangur!
