### ISSUE TITLE
no_php4_constructor replaces call to existing method by call to constructor

### ISSUE THREAD

**Issue by PowerKiKi** [FriendsOfPHP/PHP-CS-Fixer#3096]
# Input

```php
<?php
    class Parent1
    {
        function __construct($foo)
        {
        }

        function parent1()
        {
            echo "not a constructor";
        }
    }

    class Child extends Parent1
    {
        function foo($foo)
        {
            $this->parent1();
        }
    }
```
# Expected 
I expect no changes at all, because the method actually exist in the parent and is not a constructor.

# Actual
But the actual result is that the call to the method is replaced by the call to the constructor and thus breaking our code logic:

```php
<?php
    class Parent1
    {
        function __construct($foo)
        {
        }

        function parent1()
        {
            echo "not a constructor";
        }
    }

    class Child extends Parent1
    {
        function foo($foo)
        {
            parent::__construct();
        }
    }
```

# Versions

The PHP version:

```
$ php -v
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

PHP CS Fixer version:
```
$ ./vendor/bin/php-cs-fixer -v
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski
```
Also confirmed on master, c15a8d89b55d489bb0e009a0694185c5bb091068.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

I assume you sample is test dummy as `parent` cannot be used as class name (https://3v4l.org/6otWi).
However I small updated version https://3v4l.org/j8qXf

The fix should be that the fixer check if there isn't a `constructor` already defined in the class.
Do you maybe have time to help out?

**Comment by PowerKiKi** [comment]
You are correct, I edited it, sorry for that.

I have limited time, and knowledge of that project. But still I had a look and it actually looked impossible to me because we'd have to know if the parent has a constructor. And as far as I understood we don't this kind of information at all (from another class than the current one) in the fixer. Isn't it right ?

**Comment by SpacePossum** [comment]
No worries, we all have to balance our time :)

IIUC it is the method in the parent that is renamed, not the one in the child?

**Comment by PowerKiKi** [comment]
No, it's the call in the child to the parent method that is renamed. The parent class is left intact.

The child should somehow see that the parent has indeed a real method whose name happens to also be the class name.

**Comment by keradus** [comment]
> The child should somehow see that the parent has indeed a real method whose name happens to also be the class name.

Sadly, as fixers are context unaware, while fixing kid, we don't know anything about parent. not possibility to fix that behaviour.
That's one of the reasons why fixer is marked as risky.

**Comment by PowerKiKi** [comment]
Fair enough, I was going to suggest to mark it as risky. But since it's already the case, there is nothing more to be done.
