### ISSUE TITLE
`declare_equal_normalize` option not works

### ISSUE THREAD

**Issue by lexxur** [FriendsOfPHP/PHP-CS-Fixer#3101]
Config param `declare_equal_normalize` not works with configuration

```php
'declare_equal_normalize' => [
    'space' => 'single',
]
```

It not fix code like this:

```php
$b=5;
```

The PHP version:
```bash
$ php -v
PHP 7.1.8-1 (cli) (built: Aug  3 2017 18:35:23) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-1, Copyright (c) 1999-2017, by Zend Technologies
```

PHP CS Fixer version:
```bash
$ php php-cs-fixer.phar -V
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski (5642a36)
```

**Comment by keradus** [comment]
Hi
It was just reworked in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2573 for `2.7@dev`, could you please try it ?

**Comment by SpacePossum** [comment]
`declare_equal_normalize` fixes spacing around `=` within declare statements only;
like `declare(ticks   =   TICK_VALUE);`.
You sample, `$b=5;`, is not a declare statement. 

To fix the sample you need the updated version of the `binary_operator_spaces` fixer like @keradus stated.

**Comment by lexxur** [comment]
Yeah. Thnx @SpacePossum

**Comment by keradus** [comment]
@lexxur , I'm closing this ticket as your concern was addressed ;)
thanks for helping @SpacePossum ;)
