### ISSUE TITLE
Unable to apply all rules supplied in JSON string

### ISSUE THREAD

**Issue by MaryCoding** [FriendsOfPHP/PHP-CS-Fixer#3105]
I am not sure what exactly I am doing wrong but I am unable to apply certain rules through the json string. I tried multiple ways and get the same error(listed below). Any ideas how to have all those rules in effect? thanks. 

PHP version using:
`PHP 7.1.7 (cli) (built: Jul 18 2017 13:02:17) ( ZTS DEBUG )`

PHP CS Fixer version using:
```
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski (5642a36)
```

```
--rules='{"@PSR2": true, "ordered_imports": true, "no_unused_imports": true, "array_syntax": {"syntax": "short"}, "binary_operator_space": {"align_double_arrow": true, "align_equals": true}}' /x/
```

Error:
```
 [PhpCsFixer\ConfigurationException\InvalidConfigurationException]
  The rules contain unknown fixers (binary_operator_space).
```

**Comment by SpacePossum** [comment]
Hi and thanks for reaching out :)

The error reported `The rules contain unknown fixers (binary_operator_space).` seems correct as there is a little typo in your configuration. The fixer is called `binary_operator_spaces`.
With the `s` added to your configuration it works on my setup. Let me know if this resolves this issue for you.

I'll have a look if we can improve the error message to make it a bit more clear in the future.
