### ISSUE TITLE
PhpUnit 6.3 compatibility

### ISSUE THREAD

**Issue by mnabialek** [FriendsOfPHP/PHP-CS-Fixer#3106]
It seems it's not possible to use latest stable PHPUnit when installed PHP-CS-Fixer.

I believe this line in `composer.json` causes problem:
```
"sebastian/diff": "^1.4",
```

whereas in [PHPUnit 6.3 composer.json](https://github.com/sebastianbergmann/phpunit/blob/6.3/composer.json) there is:

```
"sebastian/diff": "^2.0",
```

so at the moment PHPUnit 6.2 will be installed with:

```
"sebastian/diff": "^1.4.3",
```

dependency.

Any chance to update this to 2.0 too? PHPUnit 6.2 is probably no longer updated so in longer run this update will be also necessary.

**Comment by SpacePossum** [comment]
duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2993
this is resolved in `master`, will be part of the next minor release (2.7)
