### ISSUE TITLE
Change rules of PhpdocVarWithoutNameFixer

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#3112]
`phpdoc_var_without_name` fixer has some internal rules to decide whether the `$varname` part of a `@var` PHPDoc tag should be removed:
- ignore DocComments when they are on a single line, e.g. `/** @var Foo $foo */`;
- ignore `@var` tags that are not the first tag in the DocComment.

IMO these rules are wrong, I would replace them with a new rule: the fixer should simply ignore DocComments that don't apply to a class property.

**Comment by pudovmaxim** [comment]
I think, my issue is similar. For example, this code will be formatted incorrectly
```
         /**
          * @var string $k
          * @var array  $v
          */
         foreach ($arr as $k => $v) {[...]}
```
To
```
         /**
          * @var string
          * @var array  $v
          */
         foreach ($arr as $k => $v) {[...]}
```

**Comment by dmvdbrugge** [comment]
Commenting for backreference: this equals Case 1 of #3844

**Comment by nico-incubiq** [comment]
Issues reported by #4457 and #3982 are still not fixed. Is there already a PR attempting to address these?

**Comment by dmvdbrugge** [comment]
> Issues reported by #4457 and #3982 are still not fixed. Is there already a PR attempting to address these?

#3911 is the fix, however the maintainers disagree that this is a "bug"

**Comment by enumag** [comment]
@dmvdbrugge Doesn't seem like that to me, they are just concerned about backwards compatibility. And there are still some unaddressed code reviews.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911
