### ISSUE TITLE
Echo tags and semicolon_after_instruction

### ISSUE THREAD

**Issue by jtojnar** [FriendsOfPHP/PHP-CS-Fixer#3120]
With PHP-CS-Fixer 2.7.1, when using the `@Symfony` ruleset, the following code will receive a semicolon.

```php
<?= $foo ?>
```

There should be an option not to force semicolons inside template tags, since adding them makes templates unnecessarily verbose.

**Comment by SpacePossum** [comment]
Hi,

This is, most likely, the result of the update of the Symfony set after https://github.com/symfony/symfony/pull/24123 .
The fixer `semicolon_after_instruction` can be disabled if you want.

You call it `unnecessarily verbose`, I call it explicit and consistent (all statements end with `;`). However, as always, CS is a matter of taste sometimes, so feel free to remove the fixer by your configuration :)

**Comment by jtojnar** [comment]
I agree that the semicolon should be enforced in standard PHP scripts and it is good idea for the fixer to be enabled. On the other hand, I would also like the semicolon to be consistently forbidden inside the template tags. Essentially the fixer should accept an additional `templates` option controlling this special case.

**Comment by SpacePossum** [comment]
Not sure how a detection for `templates` would look like, as such I wonder if it is worth the exception in the fixer. 
It is a balance and I feel that making an exception for `templates` in this case is not worth the extra logic (in both development, review and later maintenance). However I'm open for the discussion and willing to reopen this issue as `FR`/

**Comment by jtojnar** [comment]
I am not sure how is the code represented but if the token list is unbounded for expressions like this `<?= $foo . $bar . $baz . … ?>`, traversing the code to the opening tag would not be very efficient. Parser would have to remember the context.

This might indeed be too much work for such a minor feature like native templates. I will just disable the fixer globally, missing semicolons are quite rare itself and should be easy to spot by eye anyway.
