### ISSUE TITLE
Cache - Permission issues

### ISSUE THREAD

**Issue by dominikzogg** [FriendsOfPHP/PHP-CS-Fixer#3122]
When reporting an issue (bug) please provide the following information:

The PHP version you are using:
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

PHP CS Fixer version you are using:
PHP CS Fixer 2.7.0 Sandy Pool by Fabien Potencier and Dariusz Ruminski (e4e93a1

The command you use to run the fixer (and the configuration file you are using if any).
```
$ php-cs-fixer fix --rules=@Symfony src
You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
Loaded config default.
Using cache file ".php_cs.cache".

Fixed all files in 2.525 seconds, 10.000 MB memory used

                                                                
  [Symfony\Component\Filesystem\Exception\IOException]          
  Failed to write file ".php_cs.cache", "no reason available".  
                                                                

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

The PHP CS Fixer is, most likely, not allowed to write a cache file which triggers this exception.
I wonder if we can improve the exception message, or is there something else you would like to see changed?

**Comment by dominikzogg** [comment]
@SpacePossum i understand the message, but not the reason. the file get touched by the command, but not filled with data.

```
default /vagrant/chubbyphp-deserialization vagrant $ ls -la
total 108
drwxrwxr-x  7 vagrant vagrant  4096 Sep 26 14:08 .
drwxrwxr-x 30 vagrant vagrant  4096 Sep 18 18:30 ..
-rw-rw-r--  1 vagrant vagrant   743 Sep 26 14:02 composer.json
-rw-rw-r--  1 vagrant vagrant 52917 Mai 14 18:09 composer.lock
drwxrwxr-x  8 vagrant vagrant  4096 Okt  4 07:56 .git
-rw-rw-r--  1 vagrant vagrant    53 Sep 26 14:02 .gitignore
-rw-rw-r--  1 vagrant vagrant  1056 Mai 14 18:08 LICENSE
-rw-rw-r--  1 vagrant vagrant     0 Sep 26 14:08 .php_cs.cache
drwxrwxr-x  3 vagrant vagrant  4096 Mai 14 18:10 phpunit
-rw-rw-r--  1 vagrant vagrant   771 Mai 14 18:08 phpunit.xml.dist
-rw-rw-r--  1 vagrant vagrant  1421 Sep 26 14:02 README.md
-rw-rw-r--  1 vagrant vagrant   348 Mai 14 18:08 .scrutinizer.yml
drwxrwxr-x  6 vagrant vagrant  4096 Okt  4 07:51 src
drwxrwxr-x  6 vagrant vagrant  4096 Okt  4 07:52 tests
-rw-rw-r--  1 vagrant vagrant   551 Mai 14 18:08 .travis.yml
drwxrwxr-x 15 vagrant vagrant  4096 Mai 14 18:09 vendor
```

**Comment by SpacePossum** [comment]
I think the fixer tries to write in the directory you listed, so it needs permissions on that.
How do the permissions on the directory look like?

**Comment by dominikzogg** [comment]
drwxrwxr-x  7 vagrant vagrant    4096 Sep 26 14:08 chubbyphp-deserialization

**Comment by SpacePossum** [comment]
oh just spotted something in the first overview. There is already a cache file, but is without 'w'. If you didn't modify the permissions of the file maybe the fixer created it without writing permissions...hmmm..

**Comment by dominikzogg** [comment]
I didn't modify the file my self

**Comment by SpacePossum** [comment]
Lets see if [this PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3123) will help.
One more question, did you maybe run the fixer with different users? (like maybe used `sudo` one time and not the next time?)

**Comment by SpacePossum** [comment]
I can confirm this bug.
Reproduce steps:
- run the fixer with cache option set as `sudo` with a profile that doesn't create `r` permission on the file cache for users
- run the fixer again with a user account that is not in the sudo group

Sadly my PR to fix this didn't make it because I don't have the time to;
- investigate how PHP reports errors when trying to write to a file that is a directory on each and every PHP version and OS we support, just so we could safe the `is_dir` check overhead
- build a whole new CI suit so the scenario of running the fixer as sudo first and confirm the cache file is not writeable, run the fixer again and see the error and _than_ re-PR the fix to show the tests now passes

I salute anyone up for the task, but I'm not going to put in a whole bunch of hours to prove something trivial as the PR provides.

**Comment by SpacePossum** [comment]
closed through https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3123 I hope,
@dominikzogg let us know if this issue still pops-up when using the latest releases

**Comment by dominikzogg** [comment]
@SpacePossum there is still an error, no idea what i made wrong (using a vagrant with Ubuntu 16.04 and NFS on a Ubuntu 16.04 host)

```
default /vagrant/chubbyphp-negotiation vagrant $ php-cs-fixer --version
PHP CS Fixer 2.8.0 Round Numbers by Fabien Potencier and Dariusz Ruminski (89e7b08)
```

```
default /vagrant/chubbyphp-negotiation vagrant $ php-cs-fixer fix --rules=@Symfony
You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
Loaded config default.
Using cache file ".php_cs.cache".

                                                                
  [Symfony\Component\Filesystem\Exception\IOException]          
  Failed to write file ".php_cs.cache", "no reason available".  
                                                                

                                                                                 
  [LogicException]                                                               
  You must call one of in() or append() methods before iterating over a Finder.  
                                                                                 

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

```
default /vagrant/chubbyphp-negotiation vagrant $ rm .php_cs.cache 
```

```
default /vagrant/chubbyphp-negotiation vagrant $ php-cs-fixer fix --rules=@Symfony
You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
Loaded config default.

                                                                
  [Symfony\Component\Filesystem\Exception\IOException]          
  Failed to write file ".php_cs.cache", "no reason available".  
                                                                

                                                                                 
  [LogicException]                                                               
  You must call one of in() or append() methods before iterating over a Finder.  
                                                                                 

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting back,

Sadly the bug hunt continues :|
Did you try removing the cache file first and run than? Could you show the file permissions of the cache file after a clean start?

**Comment by SpacePossum** [comment]
btw.
```
  [LogicException]                                                               
  You must call one of in() or append() methods before iterating over a Finder.  
```

is from the configuration, it seems the finder is not setup correctly, maybe try to resolve that first.

**Comment by dominikzogg** [comment]
@SpacePossum 

`-rw-rw-rw-  1 vagrant vagrant    0 Nov  7 09:31 .php_cs.cache`

i do not use any configuration, only --rules=@Symfony

**Comment by SpacePossum** [comment]
does running with the `-vvv` give a stack trace to the exceptions? I'm puzzled about the Finder exception here...

**Comment by dominikzogg** [comment]
@SpacePossum finder exception was cause missing directory to check (see command line), i use no config which means i have to define the folder on call

**Comment by A1rPun** [comment]
I had this problem too today:
```
In FileHandler.php line 91:                           
  Failed to write file "/location/var/cache/.php_cs.cache", "no reason available".
```
Solved it with adding the missing folder:
```
$ mkdir -p var/cache
```

I hope this will help someone (possible future-me).

**Comment by mihhac** [comment]
My problem was with using **~** in the file path. When I switched to absolute path it started working.

**Comment by JRixGer** [comment]
> $ mkdir -p var/cache

What folder is this? if you don't mind pls include the path?
