### ISSUE TITLE
PHPDoc Tag - update valid tags

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3139]
List of "[valid](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/DocBlock/Tag.php#L27)" tags are not up to date.

I'd like to create a PR, but first I need to know if deprecated tags are considered valid and where to target it - 2.2 or master?

**Comment by keradus** [comment]
deprecated tags are valid IMO, but cc @GrahamCampbell 
2.2 as LTS shall be the target

**Comment by kubawerlos** [comment]
ping @GrahamCampbell

**Comment by kubawerlos** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3140.

**Comment by kubawerlos** [comment]
Actually only `PhpdocSeparationFixer` and `PhpdocSeparationFixer` are relying on the list of "valid" tags, so it does not have much impact on the codebase.
