### ISSUE TITLE
PHPDoc Tag - name of tag

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3140]
Let me start with a question: what is the name of a tag in line `' * @method("GET")'`?

If your answer is `method` then you are [wrong](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/DocBlock/TagTest.php#L62). In PHP-CS-Fixer world it's `other`.

Let's move back a little: [PSR-5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#53-tags)'s draft describes:

> Each tag starts on a new line, followed by an at-sign (@) and a tag-name followed by white-space

yet, few lines lower example:

> `@see:unit-test \Mapping\EntityTest::testGetId`

claims against it - name above is `see`. Additionally PSR5 itself has no coordinator or sponsor and hasn't been update for over one and a half year.

Thus, I'd like to not follow it strictly and propose that name of tag could match following RegEx:

```
/@[a-zA-Z0-9_\\\\-]+(?=\s|\(|$)/
```

Motivation come from need to remove PHPMD suppressions, e.g. `@SuppressWarnings(PHPMD)` - currently this is not possible as removing by `other` would affect also all Doctrine's annotations.

Surprisingly (or not) changes in code would affect only Tag class (and obviously it's test class).

**Comment by kubawerlos** [comment]
@GrahamCampbell as an author of `Tag` class would you have anything against this proposition?

**Comment by kubawerlos** [comment]
ping @GrahamCampbell

**Comment by kubawerlos** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
The point of that valid array was not to define what are syntactically valid tags, but to define those that we should be messing with.

**Comment by GrahamCampbell** [comment]
> In PHP-CS-Fixer world it's other.

Yes, that was very much intentional. When I designed that code, it was tested on over 100 codebases, and took 2 months.

**Comment by GrahamCampbell** [comment]
If we do want to change the behaviour, we should be very careful to test it thoroughly, and that stuff we didn't think about starts getting manipulated. Good repos to test on are Symfony, Zend, Doctrine, Guzzle, AWS SDK, to get variety of phpdoc usages.
