### ISSUE TITLE
Have any option that using group imports instead of single line imports?

### ISSUE THREAD

**Issue by kmvan** [FriendsOfPHP/PHP-CS-Fixer#3143]
In PHP70
I had look around all options but not found. Not `single_import_per_statement`, like `group_import_statement`.
E.g:
```
use SomeNamespace\A;
use SomeNamespace\B;
use SomeNamespace\C;
```
fix to
```
use SomeNamespace\{
    A,
    B,
    C
}
```
Have any idea?

**Comment by SpacePossum** [comment]
Hi @kmvan ,
Currently we've no rule to do such change. Feel free to open a PR and we'll be happy to look at it.

**Comment by kubawerlos** [comment]
Do we really want to have a rule to break `PSR2`?

**Comment by keradus** [comment]
please elaborate why it's breaking it and compare to PSR-12

**Comment by kubawerlos** [comment]
From http://www.php-fig.org/psr/psr-2/:
> There MUST be one `use` keyword per declaration.

Which is exactly the  description of `single_import_per_statement` fixer - which belongs to `@PSR` rule set.

Moreover, the result from @kmvan example is similar to what would be fixed [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixer/Import/SingleImportPerStatementFixerTest.php#L329).

**Comment by keradus** [comment]
adding option to rule used by ruleset doesn't mean that ruleset will be modified - it doesn't need to use new option.
what does psr-12 says about group import? I see it's fine: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements

**Comment by basheerOct** [comment]
Any updates on this?

**Comment by danielspk** [comment]
Hello, any news about it?

**Comment by julienfalque** [comment]
Added in #4005.

**Comment by kmvan** [comment]
Awesome project
