### ISSUE TITLE
Fix namespace declaration

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#3148]
Hello.

Symfony [encourage us](https://github.com/symfony/symfony-standard/blob/8065d0e2526bf973e316d82336a5543103274e43/composer.json#L13) to put our tests in the `tests` Folder. And the `tests` maps to a `Tests` namespace.
But actually you can do anything in this folder because theses classes are runned by PHPUnit.
So you can omit the namespace, or you can use a not-related namespace.

I would be cool to add a new fixed that would fix the namespace in a file (a bit like the fixer that change the class name according to the file name)

And basically, here I'm talking about tests, but it could be the same for all folder / namespace.

**Comment by gotardo** [comment]
Hi, 

I don't know if this could be a good solution. May be it can lead to some undesired behaviors. If we fix the namespace, we will be most likely breaking the use of namespaces inside the test.

Usually, I put sources in ```./src``` folder and tests in ```./tests```, both at the same level and both accomplishing the PSR-4 recommendation. Which means that MyClass and MyClassTests are in different folders but still within the same namespace -may be it is not the recommendation?

**Comment by lyrixx** [comment]
Usually, We prefixed tests with the `Tests\` namespace.

**Comment by lyrixx** [comment]
It looks like it fixed now.
