### ISSUE TITLE
AlignDoubleArrowFixer leaves extra whitespaces before the => operator

### ISSUE THREAD

**Issue by Korikulum** [FriendsOfPHP/PHP-CS-Fixer#3154]
PHP version: 7.1.9
PHP CS Fixer version: 2.6.0

The `AlignDoubleArrowFixer` leaves extra whitespaces before the `=>` operator.

Example:
```php
$a = [
    'asdvg'        => 1,
    'bfd' => 2,
    'cff'=> 3,
];
```

Actual result:
```php
$a = [
    'asdvg'        => 1,
    'bfd'          => 2,
    'cff'          => 3,
];
```

Expected result:
```php
$a = [
    'asdvg' => 1,
    'bfd'   => 2,
    'cff'   => 3,
];
```

**Comment by SpacePossum** [comment]
Hi,

This is resolved on 2.7. Please update to this version, than replace `AlignDoubleArrowFixer`
with `binary_operator_spaces` with options `operators: { '=>': 'align_single_space_minimal' }` or any other you want :)

**Comment by Korikulum** [comment]
@SpacePossum Great, works perfectly, tnx.

**Comment by AxiosCros** [comment]
My setting.json content as follow
``` json
        "binary_operator_spaces": {
            "align_double_arrow": true,
            "align_equals": true,
            "operators": {
                "=>": "align_single_space_minimal"
            }
        },
```
Something Error with "PHP CS Fixer: Configuration error of a Fixer."

**Comment by SpacePossum** [comment]
Hi @AxiosCros 

What tooling are you using?
