### ISSUE TITLE
Provide gpg signature for phar in releases

### ISSUE THREAD

**Issue by theseer** [FriendsOfPHP/PHP-CS-Fixer#3158]
While the git tags marking a release are already signed and releases are made available as phar archive - which both is already awesome -, the phar file provided within the release is not signed.

Please consider adding a detached signature to the releases, so the validity of the release phar can also be verified. This would also allow installing PHP-CS-Fixer via [phive](https://github.com/phar-io/phive).

**Comment by keradus** [comment]
phive is requiring phars to be signed? why is that?
phar releases are autogenerated on Travis and upload via Github Releases.
I don't feel confident storing private key in Travis. (it is possible to get secured/encrypted/private var from Travis job, eg via debugging the job)

**Comment by theseer** [comment]
> phive is requiring phars to be signed? why is that?

For the same reason your release tags are signed and every serious linux distribution verifies signatures on their packages before installing them. The [Debian wiki](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) also has a note on signatures and releases on github.

> phar releases are autogenerated on Travis and upload via Github Releases.
> I don't feel confident storing private key in Travis. (it is possible to get secured/encrypted/private var from > Travis job, eg via debugging the job)

Understandable. I agree that storing a private key on travis sounds like a bad idea.

It would actually be interesting to see how Redhat does it with their .rpm packages. Because they of course also do not manually build packages and need some sort of automation. They do have a dedicated package sign key - that much I know.

How are releases actually made for PHP-CS-Fixer? Adding a tag does not actually make a release on github. Is that implict to uploading a file to it via the travis hook?


Just an idea: Github can send a trigger whenever a release is made. That way you could have a more trusted server download the phar, create a signature using gpg and attach it to the release.
Not sure whether that is feasible or would actually work.

**Comment by keradus** [comment]
> How are releases actually made for PHP-CS-Fixer? Adding a tag does not actually make a release on github. Is that implict to uploading a file to it via the travis hook?

Let me repeat myself:
> > phar releases are autogenerated on Travis and upload via Github Releases.

ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/.travis.yml#L98
on git tag, Travis start job, verify all is fine, prepare release and upload it to Github.

-------------------

> Just an idea: Github can send a trigger whenever a release is made. That way you could have a more trusted server download the phar, create a signature using gpg and attach it to the release.
Not sure whether that is feasible or would actually work.

All solutions could be made, but imo creating a server service with one responsibility - build and sign phar, is overkill.

**Comment by theseer** [comment]
>>        phar releases are autogenerated on Travis and upload via Github Releases.

> ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/.travis.yml#L98
> on git tag, Travis start job, verify all is fine, prepare release and upload it to Github.

I never used the travis deploy mechanism. But a github release has a name that is not based on the tag and mardown list of things that changed. So I'm confused as to where travis gets that information from when everything is, as you say, automated. Somebody needs to come up with the name and create that changes list and other markdown text. I asumed that that would still be a sort of manual process?
     
> All solutions could be made, but imo creating a server service with one responsibility - build and sign 
> phar, is overkill.

I disagree: You distribute a binary without any cryptographic means of verification. 

PHPUnit, phpDocumentor, Composer, to just name a few, all publish signatures to verify the integrity of their binary phar releases. And I think PHP-CS-Fixer should do the same.

**Comment by keradus** [comment]
```diff
-PHP-CS-Fixer
+PHP CS Fixer
```

if you care only about checking integrity of phar file, then php phar is doing it out of the box currently

**Comment by theseer** [comment]
No it's not. How would it?

There is no way for it to cryptographically verify a phar if you do not include a signature into it that can be verified against a known key.

The phar contains a sha1 signature that you could check if the phar content has been modified after it has been created. But that's something completely different.

**Comment by keradus** [comment]
> No it's not. How would it?

you said "checking integrity of phar"

now, you are saying verify signature to be sure it was created by given entity. it's totally different.

one is verifying if file is properly built, downloaded, it's not damaged.
other is checking if someone is not trying to trick you providing you malware under name of well-known tool

**Comment by theseer** [comment]
Sorry for the confusion caused by my choice of words. I now better understand your previous reaction.
But when writing "integrity", I indeed always meant the 2nd. Which, to me, is the whole point of having crytographic signatures.

**Comment by Jean85** [comment]
If you want to apply a signature to your PHARs, you can take a look at my setup (it uses Travis deploy into GitHub releases too): https://github.com/facile-it/paraunit/blob/eb43cbcfeddc9a6c85f0b3a6c1772913a3292185/.travis.yml#L50

I took this approach from this blog post: https://andreas.heigl.org/2017/01/19/encrypt-a-build-result-automaticaly/

**Comment by SpacePossum** [comment]
Thanks @Jean85 for the read :)
Pinging @remicollet , hope you don't mind, I've the feeling you might have some ideas as well on this topic :)

**Comment by keradus** [comment]
that;s the thing @Jean85 , `DECRYPT_KEY` could be extracted from your configuration, eg via build debugging

**Comment by Jean85** [comment]
No they couldn't (without your approval, at least...), see the [Travis docs](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings):
> By default, the value of these new environment variables is hidden from the export line in the logs. This corresponds to the behavior of encrypted variables in your .travis.yml. The variables are stored encrypted in our systems, and get decrypted when the build script is generated.
>
> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

**Comment by keradus** [comment]
yes they could. I do it often when I need to recover secrets. You pointed docs about **logs** (btw, hiding mechanism for logs was not working for few days once, it was quite a big fuckup) and **PR**. I said **build debugging**

**Comment by Jean85** [comment]
If they fail in the hiding mechanism, it's indeed a big fuckup. 

But PR shouldn't be allowed in reading that stuff. Also I'm missing what do you mean by build debugging.

**Comment by keradus** [comment]
![debu](https://user-images.githubusercontent.com/2716794/31990851-8b215f76-b976-11e7-9dc6-96c04cd98911.png)

**Comment by Jean85** [comment]
I think that is accessible only to who has admin permission on Travis... right?

**Comment by keradus** [comment]
no, not admin. some rights, perhaps.
so yes, if travis had fuckup with not-working "log-securing" mechanism and provides official mechanism which could be used to retrieve secrets, I'm simply not trusting it to share private key with it

**Comment by eclipxe13** [comment]
Looks like the debug mode is enabled on travis for private repos and some public repos that had this access granted, not for every project. And as you are inside the travis build environment you can have access to everything. It seems to be a feature, not a leak: https://docs.travis-ci.com/user/running-build-in-debug-mode/

I can see that in deployment stage you are using deploy / api_key / secure.
You can use also that strategy to decrypt your key, can't you?
I mean, the new secret is as well stored as the deploy key.

Anyhow, if you don't want to sign the phar file inside travis for this security reasons then there is no option that put a service server to sign and publish. Or don't do it at all.

I think it would be great to have php-cs-fixer.phar listed on phive.

**Comment by keradus** [comment]
@theseer, does phive supports phar files signed outside? so, the checksum and signature are outside of phar file, letting one to sign file post-creation, not during creation ?

**Comment by theseer** [comment]
Sure, with GPG signatures that's as far as I know the only way. Even RPM only allows to "attach" the signature" to the file after the fact.

To be specific: Phive - by default - looks for a detached signature in ascii armored format (usually saved as `file.phar.asc`) at the same location it found the phar itself.

**Comment by keradus** [comment]
Thanks for quick answer.
That could be the answer actually, to have Travis build the artifact in sandbox, upload it, and then I would sign it after it's already uploaded to github releases.
But that means that phar would be available for a while without a signature (Between auto-publish by Travis and my manual sign action). Do you know how phive autodiscover new versions? or maybe there is a hook that could be triggered ?

**Comment by theseer** [comment]
Currently, for github based releases, phive uses the github API to request the list of public releases and silently ignores every entry that does not include a phar *and* a signature file attachment. That behavior will slightly change though: Upcoming releases will report what it found and why a release entry was skipped (see issue https://github.com/phar-io/phive/issues/117) .

If you'd want to avoid that, maybe travis should not actually make a release? You can keep a release as draft, making it invisible for everyone but members of the project. This way, at least theoretically, travis should be able to upload a phar file without it being public. Phive might need to get adjusted to ignore mere tags - that would have to be determined.

What kind of hook would you be looking for? Travis of course could trigger any kind of thing - in worst case by having your build script do a manual curl/wget call - but what should it trigger?

**Comment by keradus** [comment]
hook like with packagist - I could manually trigger "please, rediscover the releases now".

That's the thing, I don't want to make build manually, I want to have as much as possible automated.
Other thing is that I found multiple repos (even our own) providing wrong phar file (like works only on higher PHP than it is supposed to support), that's why building a phar file on CI sandbox is must have for me.

**Comment by theseer** [comment]
Phive does not rely on a central repository.The only somewhat centralized thing is an alias list that is maintained at phar.io to allow shorthand alias names like "phpunit" to be mapped to its actual repository for downloading and to support custom, selfhosted repositories like phar.phpunit.de.

Phive caches the repository data - like for github releases the json data it got from the API - based on the ETAG. That means there shouldn't be a need to externally triggering an update.

Regarding the build: I wasn't suggesting to make a manual release. All I was considering was, since you suggested manually adding the gpg signature after the fact, you could not have travis mark it as release but have it stay in darft mode until you added the signature and *then* publish it. That wouldn't affect anything in the process except the "draft" flag and thus the public availability.

**Comment by keradus** [comment]
> Phive does not rely on a central repository.

sure, but how it knows it shall observe some repos or not ?

>  you could not have travis mark it as release but have it stay in darft mode until you added the signature and then publish it

could Travis create a draft-release on it;s own?

**Comment by theseer** [comment]
>> Phive does not rely on a central repository.

> sure, but how it knows it shall observe some repos or not ?

It doesn't need to observe anything. It's all on-demand resolving when you run "phive install" or "phive update". 

>> you could not have travis mark it as release but have it stay in darft mode until you added the 
>> signature and then publish it

> could Travis create a draft-release on it;s own?

I'd assume travis merely adds a file to a tag, not caring wether that is an actual "release" on github. How do you make a release right now? Apart from the tag it's based on, a github release contains a descriptive text as well as a title. These seem to be not based on any automated process so far?

**Comment by keradus** [comment]
> It doesn't need to observe anything. It's all on-demand resolving when you run "phive install" or "phive update".

awesome, it solves my wondering :D with that approach, until I would attach signature, release is invisible for phive - that's what I understand from your explanation


> I'd assume travis merely adds a file to a tag, not caring wether that is an actual "release" on github. How do you make a release right now? Apart from the tag it's based on, a github release contains a descriptive text as well as a title. These seem to be not based on any automated process so far?

Actually, Travis creates a real release.
https://docs.travis-ci.com/user/deployment/releases/
On gh level, there are git tags, on top of which there is possibility to create releases. Releases can contain attachments, tags not. Travis takes a tag, and if there is no release yet, it creates a release.
From that point, release is valid (eg Packagist will see it). Adding changelog to release is done post factum and is not obligatory.

**Comment by theseer** [comment]
>>    It doesn't need to observe anything. It's all on-demand resolving when you run "phive install" or "phive update".

> awesome, it solves my wondering :D with that approach, until I would attach signature, release is invisible for phive - that's what I understand from your explanation

For now that is correct. In a later release, phive will report about an "incomplete" release but still use whatever other "complete" release is available - if any.

> Actually, Travis creates a real release.
> https://docs.travis-ci.com/user/deployment/releases/
> On gh level, there are git tags, on top of which there is possibility to create releases. Releases can contain attachments, tags not. Travis takes a tag, and if there is no release yet, it creates a release.
From that point, release is valid (eg Packagist will see it). Adding changelog to release is done post factum and is not obligatory.

I guess that makes sense ;) The [travis documentation](https://docs.travis-ci.com/user/deployment/releases/#Advanced-options) claims, that you can add additional fields to be passed on to the github API. One flag - according to the linked documentation - is draft: boolean.  So you could have travis create a draft release. I'm not sure though I understand the travis documentation on how to actually add these aditional options syntactically to the .travis.yml file.

**Comment by theseer** [comment]
Find this: https://github.com/travis-ci/travis-ci/issues/6132 - maybe that helps.

**Comment by keradus** [comment]
nice hint :+1: thanks!

**Comment by theseer** [comment]
Not necessarily: While I don't know for certain when exactly github will trigger the "release" event - the page for adding webservices only says "Release published in a repository" in the description - you can have github generate a webservice request when a release is made.

Granted, the payload probably looks different from what you have now, but that should make updating actually easier?

**Comment by keradus** [comment]
there is no service behind website, Travis, on tag, creates a phar file, upload it to gh releases, triggers page regeneration. the last step must be done after release is fully out (in terms it is not pre-release)

**Comment by sebastianbergmann** [comment]
Some releases, such as [2.13.2](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.13.2) have signatures and can be installed using Phive. But [2.14.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.14.0), for instance, does not have a signature. This means that in projects where Phive is used to manage PHAR dependencies people are stuck.

**Comment by keradus** [comment]
@sebastianbergmann , i just saw your comment.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.14.0 has the signature,
it got signature in same moment last 2.13.3 got it.

**Comment by keradus** [comment]
anyway, the issue to add signatures look obsolete, as we are providing them for quite a while already, closing
