### ISSUE TITLE
generate a editorconfig file

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#3159]
wouldn't it make sense to generate a editorconfig [1] file based on the CS rules available via php_cs.
most information can already be present by the definitions/settings.

having php-cs-fixer generate the editor config would have 2 possitive effects
- editor config would reflect settings of php-cs, so doesnt need to be maintained independently
- when editorconfig is present a few classes of style errors will already be prevented by a editor which respects this settings

[1] http://editorconfig.org/

**Comment by keradus** [comment]
Please send a PR against `master` branch :+1:

**Comment by SpacePossum** [comment]
Hi and thanks for the suggestion,

I consider this out of the scope of the project and therefore I'm going to close it.
As a note I also think it will be pretty hard to generate the files in sub directories when needed and also to merge new rules into existing files.

To me it might make more sense to develop a separate tool that can read `.php_cs` config files and knows how to deal with editorconfig files.
