### ISSUE TITLE
Exclude paths from .gitignore

### ISSUE THREAD

**Issue by grachevko** [FriendsOfPHP/PHP-CS-Fixer#3163]
I think will be cool to have option which import `.gitignore` in `Finder` to exclude all ignored paths instead of manually adding every path in `.php_cs` config.

**Comment by julienfalque** [comment]
I think it would be a nice feature but it should be implemented into the Symfony Finder Component directly, or as a generic third-party extension of it, not in PHP CS Fixer itself.

**Comment by keradus** [comment]
Thanks for idea, yet all maintainers agree with @julienfalque . Closing

**Comment by soullivaneuh** [comment]
To help people leading to this issue, here is the related MR to use this option: https://github.com/symfony/symfony/pull/30448
