### ISSUE TITLE
Is there a rule for removing extra spaces in a nullable type hinting?

### ISSUE THREAD

**Issue by jfcherng** [FriendsOfPHP/PHP-CS-Fixer#3167]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/FriendsOfPHP/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
7.2.0RC4

PHP CS Fixer version you are using:
2.7.1

# Question

Is there a rule for removing extra spaces in a nullable type hinting?

Before:
```php
function foo(? string $bar): ? string
{
    return $bar;
}
```

After:
```php
function foo(?string $bar): ?string
{
    return $bar;
}
```

**Comment by SpacePossum** [comment]
Hi @jfcherng ,

Currently there is no rule for this, it will be much welcome so please let us know if you've time to help out!

**Comment by jfcherng** [comment]
@SpacePossum https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3170 My first PR here. Advice wanted.

**Comment by jfcherng** [comment]
Close this since it's in `2.8.0` milestone.
