### ISSUE TITLE
Missing docs for creating custom fixers

### ISSUE THREAD

**Issue by vitek-rostislav** [FriendsOfPHP/PHP-CS-Fixer#3175]
In documentation, there are no information about creating custom fixers whatsoever. We had a really tough time figuring out what is wrong with our custom fixers after upgrading from 1.* to 2.*. I have created new [pull request](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3174) for adding information about configuration changes in UPGRADE.md but I believe that basic tutorial for creating custom fixers in documentation could be very useful.

**Comment by sustmi** [comment]
There is already [doc/COOKBOOK-FIXERS.md](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/doc/COOKBOOK-FIXERS.md) file that explains how to develop a new fixer but it focuses on creating *internal* fixers.

The documentation currently lacks two points:
- How to register and enable a *custom* fixer
- The convention for return value of `getName()` method of custom fixers - see [FixerNameValidator](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/src/FixerNameValidator.php#L34) which says that custom fixer name must be in format: `FirstPart/second_part` but comment in [FixerInterface](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/src/Fixer/FixerInterface.php#L58) says just that the name should be all lowercase.

**Comment by keradus** [comment]
Hi ;)

Looks like some valid points,
could you please send a PR ?

**Comment by vitek-rostislav** [comment]
Hi, I believe so, but it will probably take a while :)

**Comment by julienfalque** [comment]
Documentation was updated in #3475 (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/custom_rules.rst).
