### ISSUE TITLE
Binary operator spaces fixer config resolution

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3181]
Binary operator spaces fixer config resolution broken between 2.6.0 and 2.7-dev.

```
        'binary_operator_spaces' => [
            'align_equals' => null, 'align_double_arrow' => null,
        ],
```

In 2.6, this doesn't touch those, but in 2.7, it unaligns them.

**Comment by GrahamCampbell** [comment]
This breaking change in 2.x is caused by default being set to single space.

**Comment by keradus** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/.github/ISSUE_TEMPLATE

**Comment by GrahamCampbell** [comment]
Meh.

**Comment by keradus** [comment]
lol

**Comment by SpacePossum** [comment]
what : D
