### ISSUE TITLE
no braces to single command controls option

### ISSUE THREAD

**Issue by SailorMax** [FriendsOfPHP/PHP-CS-Fixer#3192]
Can you add option do not add braces to controls with single command?
Use it as double line structure plus add new line at end.
Expected sample:
``` php
if (true)
    DoSomething();

foreach ($arr as &$item)
    array_filter($item['sublist']);

```

For multiple commands we use `position_after_control_structures = 'next'` in result we have:
``` php
// acceptable syntax
if (true)
{
    DoBegin();
    DoSomething();
    DoEnd();
}

// and not acceptable (too many space uses)
if (true)
{
    DoSomething()
}

```

thank you.

**Comment by keradus** [comment]
big :-1: for dropping `{`, it violates PSR and is consider a bad practice

**Comment by SailorMax** [comment]
PSR offer to use `position_after_control_structures = 'same'` where we have:
``` php
// acceptable syntax
if (true) {
    DoBegin();
    DoSomething();
    DoEnd();
}

// also acceptable (not too many space uses)
if (true) {
    DoSomething()
}
```

But you allow to use `position_after_control_structures = 'next'`. In this case I just ask to save using space like in first case:
``` php
if (true) /*{*/                 // remove braces
    DoSomething()
/*}*/                           // but keep empty line - delimiter
```

**Comment by SpacePossum** [comment]
PSR doesn't allow the structure without the braces.
The CS you use is not one that we know is in use by a larger community. 
As such, i.e. not a standard and not in use by a large (F)OSS community I'm :-1: .

We use these requirements for new features as we care about promoting the use of standards.
For custom rules we need help with the dev/maintenance/review of the related code which is more likely to happen if there is a larger user base within the (F)OSS domain.

**Comment by SpacePossum** [comment]
Closing as there doesn't seem to be much support for this feature to add to the repo.
It is doesn't have to be the end though, you can always create custom fixers and use and share those! :)
