### ISSUE TITLE
Swapping the expression values around with count changed the expression

### ISSUE THREAD

**Issue by Vandersteen** [FriendsOfPHP/PHP-CS-Fixer#3203]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v

PHP 7.0.22 (cli) (built: Aug 24 2017 11:18:32) ( NTS )

PHP CS Fixer version you are using:
$ php-cs-fixer -V

PHP CS Fixer 2.7.1

The command you use to run the fixer (and the configuration file you are using if any).

php-cs-fixer fix .

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__."/src")
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        '@PSR2' => true,
        '@PHP70Migration' => true,
        'trailing_comma_in_multiline_array' => false,
        'array_syntax' => ['syntax' => 'short'],
        'braces' => [
            'allow_single_line_closure' => false,
            'position_after_functions_and_oop_constructs' => 'next',
            'position_after_anonymous_constructs' => 'next',
            'position_after_control_structures' => 'next'
        ]
    ])
    ->setFinder($finder)
    ;
```

A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```
if(count($array['x']) === 4)
{
    //
}

```
The fixed version of that code after you run the fixer and the version you expected.

```
if(count(4 === $array['x']))
{
    //
}
```

**Comment by SpacePossum** [comment]
Hi,

Fixing to;

```php
if(count(4 === $array['x']))
{
    //
}
```

will likely never happen; fixing to:

```php
if(4 === count($array['x']))
{
    //
}
```

has left out of the `yoda_style` fixer by design.
If you want the fixer to have a option to enable such fixing than this `issue` is a feature request. Please let us know if have to time to help out adding such option.

**Comment by Vandersteen** [comment]
I guess I was not entirely clear:

This is the code we had:

```
if(count($array['x']) === 4) //if there are 4 items in the array do something
{
     //
}
```

has been fixed to the following, which has changed the logic

```
if(count(4 === $array['x'])) //if 'x' is equal to 4 -> count(bool) -> return 0 or 1
{
      //Not the incorrect placements of brackets
}
```

it should have fixed it to:

```
if(4 === count($array['x']))
{
    //
}
```

**Comment by SpacePossum** [comment]
Using your sample code and configuration:

```
[10:45 AM]-[possum@zoo1]-[/home/possum/work/PHP-CS-Fixer]-[git 2.7] 
$ php php-cs-fixer fix test.php --dry-run -vvv --diff
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) test.php (no_empty_comment, yoda_style, no_whitespace_in_blank_line, no_extra_consecutive_blank_lines, braces)
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

-if(count($array['x']) === 4)
+if (4 === count($array['x']))
 {
-    //
 }
      ----------- end diff -----------
```

The `4` is not moved inside the `count`, which would indeed be a bug.

Could you the fixer or the code using the `-vvv` and list the fixers that made changed to the code? It would help tracking down the issue further.

**Comment by Vandersteen** [comment]
After a more detailed investigation it appears that the code change was introduced by a developer and not by this tool.

My apologies

**Comment by SpacePossum** [comment]
great to hear this mystery is solved :)
thanks for reporting back!
