### ISSUE TITLE
Namespaces On Same Line As PHP Opening Tag Are Prefixed With A New Line

### ISSUE THREAD

**Issue by moebrowne** [FriendsOfPHP/PHP-CS-Fixer#3204]
Since #3083 (v2.7.2) was merged namespaces that are defined on the same line as the opening PHP tag are prefixed with a newline when using the `no_blank_lines_before_namespace` rule.

For example the following:

```
<?php namespace Some\Name\Space;
```

Is transformed into:

```
<?php
namespace Some\Name\Space;
```

**Comment by moebrowne** [comment]
Thanks @SpacePossum !

**Comment by SpacePossum** [comment]
you're welcome :)  thanks!
