### ISSUE TITLE
Proposal for the constants casing fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3213]
Just wanna run this by you guys. How do you feel about the lowercase constants fixer becoming just a constants casing fixer, with config to select between upper and lower? For BC, we can make the existing fixer proxy to the new one, with lowercase config.

**Comment by ntzm** [comment]
Uppercase goes against PSR2 iirc

**Comment by GrahamCampbell** [comment]
Yes, I know, but not everybody follows PSR-2 (unfortunately). Drupal for example (https://www.drupal.org/docs/develop/standards/coding-standards#naming). PHP-CS-Fixer isn't PSR-2 only, since it has config for things that aren't PSR-2 already.

**Comment by KacerCZ** [comment]
+1 for this proposal
PHP_CodeSniffer also offers sniffs for both variants of constants.

@ntzm If someone prefers uppercase constants, then there is no way to configure php-cs-fixer to enforce consistency.

**Comment by SpacePossum** [comment]
Is Drupal the only FOSS community we known uses this standard? Do they plan on updating their CS to PSR in the future?

**Comment by kubawerlos** [comment]
Drupal does not follow PSR2, yet when it comes to constants:

> Constants should always be all-uppercase

so Drupal's example is not valid here.


> PHP-CS-Fixer isn't PSR-2 only

is there a fixer to break PSR2?

**Comment by SpacePossum** [comment]
We've a few fixers not following PSR (sometimes only through configuration).
If Drupal is moving to PSR standard, than I'm :-1: to add a fixer that is not PSR compat, _unless_ there is another big community following this PSR exception.

**Comment by SpacePossum** [comment]
Closing as there are no known (big) communities that have the `lower-casing constant` rule.
Making and maintaining a custom fixer for this is (relative) easy, so as long as there is no active user support for it here I think it does not belong to the core of the fixer.
