### ISSUE TITLE
odd behaviour of `new_with_braces` fixer

### ISSUE THREAD

**Issue by alcohol** [FriendsOfPHP/PHP-CS-Fixer#3218]
The PHP version you are using:
$ php -v
`PHP 7.0.25`

PHP CS Fixer version you are using:
$ php-cs-fixer -V
`PHP CS Fixer 2.7.2`

``` diff
@@ -22,7 +22,7 @@ final class DateAndTimeOfTimeslot

     public static function fromDateTime(\DateTimeInterface $dateTime): self
     {
-        return new static(
+        return new static()(
             new DateTimeImmutable($dateTime->format(\DateTime::ISO8601))
         );
     }
```

This is applied by the `new_with_braces` fixer. Is this to be expected?

**Comment by SpacePossum** [comment]
Thanks for reporting!

Currently @julienfalque is working on a patch related to this;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3208

**Comment by julienfalque** [comment]
Thanks for the report, this definitely looks like a bug. I suspect it has the same cause than #3202, could you check whether #3208 fixes the issue?

**Comment by alcohol** [comment]
#3208 does not fix it.

**Comment by julienfalque** [comment]
Ok, thanks for checking, I'll have a look then.

**Comment by julienfalque** [comment]
@alcohol #3208 has been merged with additional work from @SpacePossum regarding this issue so it should be fixed.
