### ISSUE TITLE
multi line annotation problem

### ISSUE THREAD

**Issue by OskarStark** [FriendsOfPHP/PHP-CS-Fixer#3220]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v
`PHP 7.0.25 (cli) (built: Nov  4 2017 10:58:36) ( NTS )`

PHP CS Fixer version you are using:
$ php-cs-fixer -V
`PHP CS Fixer 2.8.0 Round Numbers by Fabien Potencier and Dariusz Ruminski`

The command you use to run the fixer (and the configuration file you are using if any).

`vendor/bin/php-cs-fixer fix`

with the following config:

*.php_cs*
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in('src')
    ->in('tests')
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'no_unused_imports' => true,
        'psr4' => true,
    ])
    ->setFinder($finder)
;
```
A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
<?php

namespace SupplierPortalBackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SupplierPortalBackendBundle\Annotation\Filter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="sp_purchase_order_item_history", indexes={
      @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
      @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
      @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
      @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
      @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
   })
 */
class PurchaseOrderItemHistory
{
```

The fixed version of that code after you run the fixer and the version you expected.

```diff
  * @ORM\Entity
  * @ORM\HasLifecycleCallbacks()
  * @ORM\Table(name="sp_purchase_order_item_history", indexes={
-      @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
-      @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
-      @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
-      @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
-      @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
-   })
  */
 class PurchaseOrderItemHistory
 {
```

**HINT:** this was the result by only applying the `@Symfony` ruleset

//cc @silasjoisten

**Comment by julienfalque** [comment]
I confirm the bug (on 2.6). The changes are made by the `phpdoc_trim` fixer.

**Comment by OskarStark** [comment]
Thanks for the feedback @julienfalque

**Comment by julienfalque** [comment]
@OskarStark could you please try #3225 to see whether it fixes the issue?

**Comment by OskarStark** [comment]
What is the best way to test the new code?

**Comment by SpacePossum** [comment]
If you've the project already cloned/forked/check out using git, you could:
- checkout 2.2, cherry pick the commits from @julienfalque PR and test; or
- add @julienfalque his fork as upstream and checkout the branch used to create the PR and test;
- or checkout 2.2 and do a copy-paste of the changed files from the PR and test (most fragile/ugly way ;) )
