### ISSUE TITLE
NoExtraConsecutiveBlankLinesFixer crashes on bad whitespace characters

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3240]
$ php -v

`7.1.11`

$ php-cs-fixer -V

`2.8.0`

The command you use to run the fixer (and the configuration file you are using if any).

`NoExtraConsecutiveBlankLinesFixer`

A minimal sample of valid PHP code that is not fixed correctly (if applicable).

https://github.com/ByTIC/Common/blob/8e7382a9e9f24e9e3d77abea3e8d03a0c6229e47/src/Payments/Gateways/Providers/Euplatesc/Gateway.php

Was hard to edit the file because editors and git settings kept fixing the characters. The original file demonstrates the issue just fine though.

```
 InvalidArgumentException · Cannot set empty content for id-based Token.
```

Happens as a result of calling `$this->tokens[$index] = new Token([T_WHITESPACE, $content]);`.

**Comment by SpacePossum** [comment]
thanks for reporting,
this fails on 2.7 as well
