### ISSUE TITLE
NoEmptyPhpdocFixer keeps spaces after removal

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#3245]
When I run `NoEmptyPhpdocFixer` on empty phpdoc, it keeps spaces there:

```diff
-    /**
-     */
+    
     protected f
```

I've tried to run it with `BracesFixer` to remove spaces, but with no success.

What should I use?

- PHP CS Fixer 2.8.1
- PHP 7.1

**Comment by SpacePossum** [comment]
try `no_extra_consecutive_blank_lines` , together with `method_separation` and various other, really depends on your use case :)

**Comment by keradus** [comment]
Hi Tomas!

Purpose of `...Phpdoc...` is to touch Phpdoc, not sth outside of it. Single responsibility prevents the fixed to do sth outside.
Whitespaces were there and they are simply not touched (most of us don't like them, yet not all). If you don't like them as well, simply add `no_trailing_whitespace` rule to your configuration.

**Comment by TomasVotruba** [comment]
That's the one I was lookin for, thanks

**Comment by TomasVotruba** [comment]
Actually it doesn't work on this case.

I'll try to prepar failing test.

**Comment by TomasVotruba** [comment]
@SpacePossum I just now noticed your answer. Thanks.

This is related to other people's code. I can't force people to change spaces between methods by `method_separation`. Some people use 2, some 3 etc. I only can remove this trailing space.

I'll try `no_extra_consecutive_blank_lines`.

What "othes" do you have in mind?

**Comment by TomasVotruba** [comment]
This should be already part of PSR-2 set:

- http://www.php-fig.org/psr/psr-2/#23-lines

> There MUST NOT be trailing whitespace at the end of non-blank lines.

**Comment by TomasVotruba** [comment]
So I found a checkers, that does remove trailing spaces: `PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff`

![image](https://user-images.githubusercontent.com/924196/32694663-284325b4-c746-11e7-90e7-299d63f5d704.png)

But as you see, in finall version it replaces docblock with one empty line. Which is wrong.

That's how I get to my original issue, that `NoEmptyPhpdocFixer` replaces docs with spaces.
**It should remove the docs, instead of replacing it with new line.**

Could we fix that?

**Comment by TomasVotruba** [comment]
With something like this: https://github.com/Symplify/Symplify/pull/434/commits/7c077b714bc6f2578790314f7d27d2109f46fdd8#diff-25eac1497dd973032fff85fbbf8981b0R57

**Comment by keradus** [comment]
> Actually `no_trailing_whitespace` doesn't work on this case

`no_whitespace_in_blank_line`
readme to the rescue...

**Comment by keradus** [comment]
let me replace spaces with underscores.
```diff
-____/**
-_____*_FOO....
-_____*/
+____
````
as you can see, phpdoc... removed content starting with `/**` and ending with `*/`. whitespaces before were not touched (instead, how you wrote, added)

**Comment by TomasVotruba** [comment]
This look like result of AI. Being correct on tasks, but adding extra work.

What's the advantage of such approach?

**Comment by keradus** [comment]
not having same rules applies by multiple fixers.
again, not all ppl follow rule "no trailing whitespaces"

**Comment by keradus** [comment]
instead of applying one rule and expecting some other rules will be applied automatically (which for different ppl would be different rules...), specify the ruleset you want to follow and apply whole of it, not just part of it

**Comment by TomasVotruba** [comment]
This rule is actually incorrect, so others rules only build on this error.

See - here are 2 properties separated by 3 spaces (= random custom number).

```php
    public $property;



    /**
     */
    public $anotherProperty;
```

After this rule

```php
    public $property;



    
    public $anotherProperty;
```

After trailing spaces removal

```php
    public $property;




    public $anotherProperty;
```

From 3 spaces to 4 with no option to fix this.

**Comment by TomasVotruba** [comment]
Also this consider this case.

```php
    public $property;



    /**
     *
     *
     *
     *
     *
     */
    public $anotherProperty;
```

After

```php
    public $property;



    
    
    
    
    
    

     public $anotherProperty;
```

I would have fix all this manually :/

**Comment by GrahamCampbell** [comment]
> why is it designed this way?

Separation of responsibilities keeps things sane.

**Comment by keradus** [comment]
> When we put apart assumption, that other rule takes care of this - which they don't, see bellow

Again, use the ruleset you want to follow, and apply whole of it, not only one or two picked up rules.
If you want to not have consecutive blank lines, add `no_extra_consecutive_blank_lines` to your ruleset.

To have output like
```php
    public $property;

    public $anotherProperty;
```

it's far away for responsibility of dropping empty phpdoc block.

---------------------------------

if you want empty docblock removal fixer to drop that one line the docblock was starting at, simply create a PR for doing it, if community will give approval, I would be more than happy to merge it.
yet, don't touch other empty lines in that fixer.

**Comment by TomasVotruba** [comment]
> Separation of responsibilities keeps things sane.

Any real life example to support this?

**Comment by TomasVotruba** [comment]
@keradus That's forces people to use rules they don't want to use, not a way to go.

What is sense of making rules as standalone clases then if they have such hidden and forcing dependencies?

**As I stated, some code I change prefer 2 spaces.**

**Comment by keradus** [comment]
> That's forces people to use rules they don't want to use, not a way to go.

so I got lost ,you don't want trailing spaces, yet you don't want enabling the rule. You dont want consecutive lines, but you don't want the rule.

> What is sense of making rules as standalone clases then if they have such hidden and forcing dependencies?

single class = single rule, if doblock is removed, removing empty lines before is assumption, one wants it, one doesn't, separated rule to give full control. what's more, with separated rule you apply rule to whole project as one should if he follow the rule, not only in places where he dropped docblock

> As I stated, some code I change prefer 2 spaces.

sorry, i cannot see connection to 2 spaces anyhow

**Comment by TomasVotruba** [comment]
> if you want empty docblock removal fixer to drop that one line the docblock was starting at, simply create a PR for doing it, if community will give approval, I would be more than happy to merge it.
yet, don't touch other empty lines in that fixer.

I miss some support here. At the moment it would be waste of time for me to repeat some discussion, if I'm the only one who needs that.

It was easier for me to create own fixer: https://github.com/Symplify/CodingStandard#there-should-not-be-empty-phpdoc-blocks

If anyone feels like this would be useful to him or her, feel free to ping me. I might reconsider PR.

**Comment by TomasVotruba** [comment]
> so I got lost ,you don't want trailing spaces, yet you don't want enabling the rule. You dont want consecutive lines, but you don't want the rule.

Nono, I don't want anything of this. That was added in responses. I only need what I asked in my first issue.

> removing empty lines before is assumption

Not lines, just spaces that are part of the code - in browser and for people, not in token way.

> sorry, i cannot see connection to 2 spaces anyhow

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3245#issuecomment-343740094, some people prefer 2+ empty lines between properties.

Other rules are making assumption (separation of concerns?) that they want only 1.

**Comment by keradus** [comment]
> I miss some support here. At the moment it would be waste of time for me to repeat some discussion, if I'm the only one who needs that.

you don't need to repeat discussion, you could point it here.
I gave you the reasoning for current state of art, I even said I won't block if and let the community decide ;) So ultimately, it's up to you and other users ;) especially when you say it's more than you who needs it.


> It was easier for me to create own fixer

It's sad approach for me to not contribute back, and then copy-paste without respecting the copyrights/license when you want to make your patch.

> Nono, I don't want anything of this. That was added in responses. I only need what I asked in my first issue.
> Not lines, just spaces that are part of the code - in browser and for people, not in token way.

I already said to go with PR ;)

**Comment by TomasVotruba** [comment]
> copy-paste without respecting the copyrights/license when you want to make your patch.

That was not my intention. What can I do about that?

**Comment by keradus** [comment]
Original question was "what should I use?" as `braces` rule was not helpful, we answered with candidate rules, and, as you see, even if original question was answered, we don't block this thread and we could happily continue the discussion (which, on the other side, could be done outside issue tracker but on gitter chat ;P).

At least put back the copyrights/license (as we ask you in our license file), or even opening a PR to not need to maintain the forked version, but it's up to you ;)
