### ISSUE TITLE
Show rules sets list on readme

### ISSUE THREAD

**Issue by soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#3252]
The rules sets count is being high.

Just a little thing, but it would be great to have a short list of all rules sets, before the fixers list.

**Comment by keradus** [comment]
why not. but let us also have it autogenerated (instead of hardcoded in readme content), so we could also display it in `describe` command.
do you want to propose a PR?

**Comment by Soullivaneuh** [comment]
@keradus It should not be so hard to do it. I'll take a look this week.
