### ISSUE TITLE
Yoda fixer doesn't work with a block statement followed by a ternary statement

### ISSUE THREAD

**Issue by weareoutman** [FriendsOfPHP/PHP-CS-Fixer#3264]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
PHP 5.6.32 (cli) (built: Nov  1 2017 11:09:11) 

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.8.1 Round Numbers by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix --config=.php_cs.dist -v --using-cache=no

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->in(__DIR__ . '/src');

return PhpCsFixer\Config::create()
    ->setRules([
        'yoda_style' => true,
    ])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
function hello() {}
$a === 1 ? b() : c();
```

 * with unexpected changes applied when running PHP CS Fixer:
Actually it reported an error `Files that were not fixed due to errors reported during linting after fixing`.
```php
<?php
1 === function hello() {}
$a ? b() : c();
```

 * with the changes you expected instead:
```php
<?php
function hello() {}
1 === $a ? b() : c();
```

I know using ternary statements is not a good practice, but it's a valid syntax.

**Comment by keradus** [comment]
very nice report, great to see your PR as well !
