### ISSUE TITLE
Fixer to disable stuff (functions, language constructs, statements, classes)

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3267]
If I have a penny for every time I saw `var_dump` in pull request...

We have [`disable_functions`](http://php.net/manual/pl/ini.core.php#ini.disable-functions) (and [classes](http://php.net/manual/pl/ini.core.php#ini.disable-classes)) directives - what about a fixer to disable/prevent some stuff in code. Who wouldn't want to have this:

* **disable_stuff**

  Disable functions, language constructs, statements and classes.

  Configuration options:

  - ``functions`` (``array``): list of functions to remove; defaults to
    ``['eval', 'var_dump']``
  - ``constructs`` (``array``): list of language constructs to remove; defaults to
    ``['echo']``
  - ``statements `` (``array``): list of functions to remove; defaults to
    ``['include', 'include_once']``
  - ``classes`` (``array``): list of classesto remove; defaults to
    ``['ReflectionClass']``

**Comment by Slamdunk** [comment]
The overuse of raw functions that should be wrapped is real and your intentions are good, but (`eval` apart) I have tons of good and strong OOP codebases that have valid usage for each of the abused low-lever PHP functions.

I don't see a value in a fixer like this.

**Comment by kubawerlos** [comment]
As I still would like to have a tool to find any usage of `var_dump` (especially in comments) I agree that it's beyond scope of fixing - there is no proper way of fixing usage of it.

**Comment by keradus** [comment]
one of GrumPHP internal tasks allows it (it has to be used via GrumPHP, not standalone):
https://github.com/phpro/grumphp/issues/439
