### ISSUE TITLE
How to choose php version

### ISSUE THREAD

**Issue by indapublic** [FriendsOfPHP/PHP-CS-Fixer#3269]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.1.11

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.8.1 Round Numbers

#### The command you use to run PHP CS Fixer:
=> Using with grumphp

> phpcsfixer2:
>             allow_risky: true
>             diff: true
>             verbose: true
>             using_cache: true
>             rules:
>                 '@Symfony': true
>                 declare_strict_types: true
>                 binary_operator_spaces: false
>                 trailing_comma_in_multiline_array: false
>                 yoda_style: false
>                 array_syntax:
>                     syntax: short
>                 concat_space:
>                     spacing:
>                         one

I'm not sure about this repo is correct place where I should to ask.
But I'm asked [here](https://github.com/phpro/grumphp/issues/425) and still not receiving solution.

I'm using grumphp with php-cs-fixer at one as rules for my simple Symfony project. And I receive error on each commit:

> Warning: Unsupported declare 'strict_types' in /Volumes/Data/www/com.indapublic/starter/api/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
> 
> Parse error: parse error, expecting `';'' or `'{'' in /Volumes/Data/www/com.indapublic/starter/api/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 87

Seems like checks use wrong php version. How I can to fix it? Thanks

**Comment by keradus** [comment]
Sorry, but I actually have no clue what we can answer here.

Looking at a title only... phpenv? phpbrew? choco? apt?

Looking at description...
PHP CS Fixer can be executed on PHP 5.3-7.2.
You claim to use 7.1, which supports strict_types declaration.
You show some error in vendor code, which we don't use even.
What you don't show is where the error come from, at least some backtrace would be usefull.

> But I'm asked here and still not receiving solution.

Your request got attention already from repo owner yesterday, you answered today and "still not received solution". Oh c'mon! Give ppl some time! It's weekend and ppl are resting.

Finally, google to the rescue: 
https://github.com/Ocramius/ProxyManager/issues/328#issuecomment-304170899 (and previous messages to know how to track the issue)

**Comment by indapublic** [comment]
> Oh c'mon! Give ppl some time! It's weekend and ppl are resting.

Calm down, please.

**Comment by GrahamCampbell** [comment]
I think the question is actually asking: "How do I prevent PHP fixer from making changes that cause files to need a later version of PHP?".

For that, you can run php-cs-fixer using an older version of php. That will force the linting phase to keep the code compatible with your version (ie, it will fail loudly if you had a fixer that was making bad changes).

**Comment by indapublic** [comment]
@GrahamCampbell Thanks for your reply.

Nope. I'm using PHP7.1 already (cli and fpm). And I want to run checks with PHP7.1. But it seems like it is used 5.6 (which originally exists in OSX).

**Comment by keradus** [comment]
no @GrahamCampbell , it has nothing to do with PHP CS Fixer. guy is posting in (at least) 3 different repos looking for help. the only one that's valid in this case is grumphp, yet it's not grumphp issue but his local setup

**Comment by GrahamCampbell** [comment]
Ah well. No harm done. :)

**Comment by sovetski** [comment]
Hi,

Any idea on how PHP CS Fixer gets which php version to use?

Imagine I have a project with PHP 7.3, and I don't want that PHP CS Fixer format my code for PHP 8.0, how to do it?

**Comment by Wirone** [comment]
@sovetski you've already [asked about it](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7118) and got the answer there 😉. Probably it should be documented under [supported PHP versions section](https://cs.symfony.com/#supported-php-versions), though.
