### ISSUE TITLE
PhpdocTrimFixer - breaks some cyrillic in phpdoc

### ISSUE THREAD

**Issue by zobzn** [FriendsOfPHP/PHP-CS-Fixer#3271]
#### The PHP version you are using (`$ php -v`):
PHP 7.0.25 (cli) (built: Oct 24 2017 13:54:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25, Copyright (c) 1999-2017, by Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.8.2 Round Numbers by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
vendor/bin/php-cs-fixer fix -vv

#### The configuration file you are using, if any:
```php
<?php

return call_user_func(function () {
    $finder = PhpCsFixer\Finder::create()
        ->files()
        ->ignoreDotFiles(true)
        ->ignoreVCS(true)
        ->name('*.php')
        ->exclude('vendor')
        ->in(__DIR__ . '/.');

    $config = PhpCsFixer\Config::create();
    $config->setUsingCache(false);
    $config->setLineEnding("\n");
    $config->setFinder($finder);
    $config->setRules([
        '@PSR1'    => true,
        '@PSR2'    => true,
        '@Symfony' => true,
    ]);

    return $config;
});
```

#### sample of PHP code before running PHP CS Fixer (in UTF-8 encoding):
```php
<?php

/**
 * @return int количество деактивированных
 */
function deactivateCompleted()
{
    return 0;
}
```

#### sample of PHP code after running PHP CS Fixer (with unexpected changes):
```php
<?php

/**
 * @return int количество деактивированны�
 */
function deactivateCompleted()
{
    return 0;
}
```

#### output of `php-cs-fixer fix -vv`:
```
Loaded config default from "c:\work\1\.php_cs.dist".
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) 1\.\test.php (phpdoc_trim)

Fixed all files in 0.018 seconds, 8.000 MB memory used
```

There is no error in version 2.8.1.
Perhaps this is side effect of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3225

**Comment by SpacePossum** [comment]
Hi @zobzn ,

Thanks for reported, I've confirmed your bug reported and opened https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3272 in the hope to resolve this issue.

**Comment by zobzn** [comment]
@SpacePossum thanx. This seems to solve the problem.
