### ISSUE TITLE
upgrade from older php71 version to php72

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#3277]
on my mac when i upgraded to php72 i couldn't run anymore self-update to jump from 2.3.2 -> 2.8.2

perhaps remove on the old branch the requirement for 7.1*

also i added these lines to my php_cs

'is_null' => null,
        'yoda_style' => null,
        'self_accessor' => false,

maybe not BC

**Comment by GrahamCampbell** [comment]
You can set an environment variable to ignore platform deps, then run the command. :)

**Comment by cordoval** [comment]
thanks i will remember for php 7.4 👍

**Comment by GrahamCampbell** [comment]
The one you want is:

```
PHP_CS_FIXER_IGNORE_ENV
```

**Comment by cordoval** [comment]
good to know for the future, too late for now 🗡 

thanks 👍
