### ISSUE TITLE
protected_to_private in Symfony ruleset

### ISSUE THREAD

**Issue by johnnypeck** [FriendsOfPHP/PHP-CS-Fixer#3282]
Why is protected_to_private set to true in the Symfony ruleset when it is set to false in the Symfony repository? That doesn't make sense to me. Is there some particular reason for the difference?

[Official Symfony repo ruleset](https://github.com/symfony/symfony/blob/master/.php_cs.dist#L12)
vs
[CS Fixer Symfony ruleset](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/RuleSet.php#L130)

Thanks!

**Comment by keradus** [comment]
https://github.com/symfony/symfony/pull/24136 for details

Sf follows it everywhere except one file.

**Comment by johnnypeck** [comment]
Thank you @keradus
