### ISSUE TITLE
Missing operators `=+` and `=-` in binary_operator_spaces rule

### ISSUE THREAD

**Issue by meridius** [FriendsOfPHP/PHP-CS-Fixer#3284]
#### The PHP version you are using (`$ php -v`):
=> 7.0.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.8.3

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
class Response extends SymfonyResponse
{
    const HTTP_INVALID_BRAIN_RESPONSE = 550;

    public static $statusTexts =+ [
        self::HTTP_INVALID_BRAIN_RESPONSE => 'Invalid response from Brain client',
    ];
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
class Response extends SymfonyResponse
{
    const HTTP_INVALID_BRAIN_RESPONSE = 550;

    public static $statusTexts = +[
        self::HTTP_INVALID_BRAIN_RESPONSE => 'Invalid response from Brain client',
    ];
}
```

 * with the changes you expected instead:
```php
class Response extends SymfonyResponse
{
    const HTTP_INVALID_BRAIN_RESPONSE = 550;

    public static $statusTexts =+ [
        self::HTTP_INVALID_BRAIN_RESPONSE => 'Invalid response from Brain client',
    ];
}
```

#### Conclusion
There should be no diff. Instead `$a =+ [];` is transformed to `$a = +[];`. This seems to be due to missing `=+` operator in `binary_operator_spaces` rule. The `=-` might me also affected.

**Comment by julienfalque** [comment]
AFAIK the `=+` operator does not exist. I'd say that PHP reads it as `=` operator followed by `+` operator so the fixer behavior is actually correct.

Note that since PHP 7.0.18, this code snippet would trigger an error: https://3v4l.org/uftMc. In such case, the fixing process should catch it and ignore the file.

**Comment by meridius** [comment]
You are right. Thank you 😄
