### ISSUE TITLE
Convert the string from utf8 to windows 1252.

### ISSUE THREAD

**Issue by icanc** [FriendsOfPHP/PHP-CS-Fixer#3291]
#### The PHP version 

```
PHP 7.2.0 (cli) (built: Dec  3 2017 21:46:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```
#### PHP CS Fixer version

```
PHP CS Fixer 2.8.3 Round Numbers by Fabien Potencier and Dariusz Ruminski
```
 
#### The command 

```
php-cs-fixer fix ./Test.php --diff
```

#### Test.php (utf-8)

```
<?php

class Test
{
//酰
}

```

#### The result
 
```
Loaded config default.
Using cache file ".php_cs.cache".
   1) Test.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

 class Test
 {
-//酰
+    //?    ?
 }
      ----------- end diff -----------
```

**Comment by Slamdunk** [comment]
Hi, could you re-run the command with `--verbose` flag so it outpus also the fixer name that caused the unexpected change?

**Comment by kubawerlos** [comment]
It's this [line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.2/src/Fixer/Basic/BracesFixer.php#L864), because of `\R` does not work as `\n|\r|\r\n`: https://3v4l.org/fVYlQ

We can either replace `\R` with the `\n|\r|\r\n` or expect `mbstring` extension and use `mb_ereg_replace`. I'll try to to it today.

**Comment by keradus** [comment]
cc @julienfalque 
could you please take a look ?

**Comment by keradus** [comment]
https://3v4l.org/3n9gB
cc @kubawerlos

**Comment by keradus** [comment]
Closing due to release of #3446 , please update version you are using
