### ISSUE TITLE
Tabs on newline with chain methods

### ISSUE THREAD

**Issue by pythonizo** [FriendsOfPHP/PHP-CS-Fixer#3294]
* before running PHP CS Fixer (no changes):
```php
    $this->_postFactory
->create()
->setData($data)->save();
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    $this->_postFactory
->create()
->setData($data)->save();
```

 * with the changes you expected instead:
```php
    $this->_postFactory
        ->create()
        ->setData($data)
        ->save();
```

**Comment by keradus** [comment]
Hi. You are requesting a feature or raising a bug ?

**Comment by pythonizo** [comment]
I dont know. Maybe is a feature. Is not specified in PSR2.

**Comment by keradus** [comment]
ok, I must admit I am confused now.
You are reporting the issue for currently existing rule / ruleset that you are using, or you wanted to create new feature ?

**Comment by pythonizo** [comment]
I mean. PSR2 not specified what to do with this. But, i think, that fixer should, at least, add tabs in this way:

```php
$this->_postFactory
->create()
->setData($data)
->save();
```
So the code will be aligned with previous line. Sorry if I have not explained myself well

**Comment by julienfalque** [comment]
There already is an open PR for that: #3063.

**Comment by pythonizo** [comment]
I swear I look for it. Sorry
