### ISSUE TITLE
Rules @Symfony really including all specified in docs ?

### ISSUE THREAD

**Issue by gregoirepaqueron** [FriendsOfPHP/PHP-CS-Fixer#3295]
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+
PHP CS Fixer 2.8.3 Round Numbers

With this command :` php-cs-fixer fix -v --rules=@Symfony src/` i cleaned my `src` folder with all rules of Symfony tag.

But then, i executed this one : ` php-cs-fixer fix -v --rules=blank_line_before_statement src/` and it fixed me new files.
In documentation, we can see that the rule `blank_line_before_statement` is included in `@Symfony` rule : 

```txt
blank_line_before_statement [@Symfony]

An empty line feed must precede any configured statement.

Configuration options:

statements (array): list of statements which must be preceded by an empty line; defaults to ['break', 'continue', 'declare', 'return', 'throw', 'try']
```

Do i miss something ?

**Comment by julienfalque** [comment]
The `@Symfony` ruleset does include the `blank_line_before_statement` but with a specific configuration: `['statements' => ['return']]`. When you run it with default configuration, the rule will add blank lines before statement that are ignored when running it via the `@Symfony` ruleset.

This is currently not mentioned by the documentation, maybe we should add a note about it.

**Comment by gregoirepaqueron** [comment]
Yes maybe for clearer information. But maybe the doc will be too verbose too ...
Anyway, thanks for your answer, it makes sense :)
