### ISSUE TITLE
Snake or camel casing for phpunit tests

### ISSUE THREAD

**Issue by BackEndTea** [FriendsOfPHP/PHP-CS-Fixer#3302]
My proposal is a fixer that enforces either

```php
public function test_it_does_a_test() {}
```
or
```php
public function testItDoesATest() {}
```
for **PHPUnit tests**.

Ive seen the discussion in #1044, but i feel that reducing the scope of a fixer like this to only PHPUnit tests makes it safe to use. 
Any helper functions or dataproviders and the like would not be affected by the fixer, only the tests (either prefixed with test or having a doc block containing ```@test```.

The fixer would only have to adjust the function names it finds, and function names in any ```@depends``` tags in doc blocks.

If there is any desire for a fixer like this i'm willing to shoot a PR this way.

**Comment by keradus** [comment]
is there any big community using underscore convension for tests ?

**Comment by Slamdunk** [comment]
> is there any big community using underscore convension for tests ?

I don't know, but I used camelCase since ever (maybe 10 years) and snake_case since this week, and can be much more readable if the method names are longer than 100 chars, which is a good practice if you have a complex domain with thousand edge cases for every single feature/spec.

**Comment by keradus** [comment]
you are using it globally, or just for test method names?
if later, use proper reporter that do this for you, eg `testdox`

**Comment by Slamdunk** [comment]
Just test method names.
Testdox is  only useful when running tests: I need it to be useful also when reading them.

**Comment by keradus** [comment]
why do you consider long name inside `src` as readable, but in `tests` not?

**Comment by Slamdunk** [comment]
There is a fundamental difference between the two environments: in `src` methods name are composed solely of a verb and a noun because a method shall have a single responsability and a simple way of acting; in `tests` for most of the edge cases we wrote entire phrases explaining what the test code can't explain well or quickly.
