### ISSUE TITLE
Command $php-cs-fixer return - symbols

### ISSUE THREAD

**Issue by MaximStrutinskiy** [FriendsOfPHP/PHP-CS-Fixer#3303]
Command `$php-cs-fixer` returning - symbols, why this happens? 
```
user@userpc:~$ php-cs-fixer
끱Ɇ𘥨𘥚𛙏 񬽰񬽚?user@userpc:~$ 
```

**Comment by SpacePossum** [comment]
Hi,

Can you tell us which OS and bash/shell/console you are using and which version of the fixer (`php-cs-fixer -v`)?

**Comment by MaximStrutinskiy** [comment]
Hi,

OS - Ubuntu 16.04
default ubuntu console
`php-cs-fixer -v` return `끱Ɇ𘥨𘥚𛙏 񬽰񬽚?`

**Comment by keradus** [comment]
![pic](https://user-images.githubusercontent.com/2716794/33711184-60287d42-db43-11e7-89d3-4b607f824f2f.png)
under default ubuntu console.

we need more information for sure.
are you sure you don't have any custom terminal settings ?

**Comment by MaximStrutinskiy** [comment]
@keradus 
No, i use default settings

**Comment by keradus** [comment]
> we need more information for sure.

without steps to reproduce, not able to figure out.
does phpunit or any Sf cli app behaves properly?

**Comment by MaximStrutinskiy** [comment]
Yes, all app works fine, (maybe you mean some specific app? )

**Comment by keradus** [comment]
no, i just shooting random hints at you, as we still have no way to reproduce.
try to run it under different console and under docker, maybe it will give you some hints.

**Comment by MaximStrutinskiy** [comment]
omg, i'm just add `php` before `php-cs-fixer.phar` and all is worked.
`example php php-cs-fixer.phar fix src/`

**Comment by keradus** [comment]
in your initial comment you didn't said you called phar file.
you renamed phar file to extension-less one ?

**Comment by MaximStrutinskiy** [comment]
`php-cs-fixer.phar` = `php-cs-fixer`
In last message with: `example php php-cs-fixer.phar fix src/`.  I download new `php-cs-fixer-v2.phar`, and forgeted renamed to `php-cs-fixer`.

**Comment by keradus** [comment]
```
ker@dus:/tmp$ chmod u+x php-cs-fixer.phar 
ker@dus:/tmp$ ./php-cs-fixer.phar 
PHP CS Fixer 2.8.3 Round Numbers by Fabien Potencier and Dariusz Ruminski (d9ec9b8)
```

**Comment by SpacePossum** [comment]
Would there be a way to detect this case and warn the user?

**Comment by keradus** [comment]
Maxim had to do sth else than he is showing.


```
ker@dus:/tmp$ wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.8.3/php-cs-fixer.phar -O local-php-cs-fixer
ker@dus:/tmp$ local-php-cs-fixer 
local-php-cs-fixer: command not found
```


way diffferent error than he got

**Comment by kubawerlos** [comment]
```bash
kuba@kubapc:~$ cd /usr/local/bin
kuba@kubapc:/usr/local/bin$ wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.8.3/php-cs-fixer.phar -O local-php-cs-fixer
kuba@kubapc:/usr/local/bin$ chmod +x local-php-cs-fixer
kuba@kubapc:/usr/local/bin$ local-php-cs-fixer                                                                                                                                                                                                     
PHP CS Fixer 2.8.3 Round Numbers by Fabien Potencier and Dariusz Ruminski (d9ec9b8)
```

Still fine.

**Comment by SpacePossum** [comment]
Closing as I see no actions needed here? Let me know if there is exactly something left.
