### ISSUE TITLE
[Feature Request] Add @inheritdoc

### ISSUE THREAD

**Issue by grachevko** [FriendsOfPHP/PHP-CS-Fixer#3308]
Adding docblock {@inheritdoc} to impemented or overridden methods.
It may useful on code review on github, as github don't show hints like IDE.

**Comment by SpacePossum** [comment]
Hi @grachevko ,

could you elaborate on your request, what would you like the tool to do? Maybe a small (pseudo) sample to illustrate would help :)

**Comment by grachevko** [comment]
@SpacePossum detect if method is implementation of parent class or one of his/his parent interface and don't have any docblock then add inheritdoc to it.

**Comment by julienfalque** [comment]
This is not possible because the tool would need to know about parent class but it only knows about the file it is currently fixing.

Also, `/** @inheritDoc */` and similar syntaxes have the exact same meaning than no PHPDoc at all because inheritance is the default behavior. Adding the tag without anything more only makes inheritance explicit. For that reason I tend to go the other way: remove PHPDocs that don't provide any useful information.

**Comment by grachevko** [comment]
@julienfalque oddly. It seemed to me that it reads the return type from phpdoc of the parent class.

**Comment by SpacePossum** [comment]
>Also, /** @inheritDoc */ and similar syntaxes have the exact same meaning than no PHPDoc at all because inheritance is the default behavior.

which is odd, so if you don't want any doc you've to add an empty PHPDoc to stop the inheritance  of the doc? 

But yeah, @julienfalque is right, since we only have the file scope we cannot always determine the parent and its methods. There have been discussions about getting that info in some way (reading composer files or autoload file etc.), but this is not implemented yet.

**Comment by julienfalque** [comment]
> which is odd, so if you don't want any doc you've to add an empty PHPDoc to stop the inheritance of the doc?

I think you can only _override_ inherited elements, not disable them completely. What would be the use cases for that?

**Comment by SpacePossum** [comment]
sample from the SF repo:
```
    /**
     * Executes the current command.
     *
     * This method is not abstract because you can use this class
     * as a concrete class. In this case, instead of defining the
     * execute() method, you set the code to execute by passing
     * a Closure to the setCode() method.
     *
    [ ... ]
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        //...
```

This description doesn't add anything useful for the method that overrides it, however it is handy on the parent level. I just don't like to put an empty PHPDoc above my implementation ;)

**Comment by keradus** [comment]
I'm :+1: for `Adding docblock {@inheritdoc} to impemented or overridden methods.` feature,
yet as said, it cannot be done without context-aware functionality

**Comment by EvgenyOrekhov** [comment]
> **Important** Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.

Source and more info: https://docs.phpdoc.org/guides/inheritance.html

So the following form is not valid:

```php
/**
 * {@inheritdoc}
 */
public function bar()
{
}
```

**Comment by SpacePossum** [comment]
>So the following form is not valid:

when following `phpdoc`, it is valid for PSR-5 I think?

**Comment by EvgenyOrekhov** [comment]
@SpacePossum https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#62-using-the-inheritdoc-inline-tag-to-augment-a-description also says that the `{@inheritDoc}` inline tag can augment a Description, not a Summary. So no, not valid for PSR-5.

**Comment by Aerendir** [comment]
The correct spelling of `inheritDoc` is in camelCase, not in lowercase.
Source: https://docs.phpdoc.org/latest/guides/inheritance.html#the-inheritdoc-tag

Using it in lowercase may cause issues, with PHPStan, for example.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5141

**Comment by julienfalque** [comment]
@kubawerlos @SpacePossum @keradus @localheinz Shall we close here? Even if we agreed to implement this (I don't), I think we can't do it without a massive rewrite anyway.

**Comment by kubawerlos** [comment]
I'd say close it, adding context-aware functionality is not something what will happen anytime soon (if at all).
