### ISSUE TITLE
[Question] Variable spacing

### ISSUE THREAD

**Issue by tafelglotzer** [FriendsOfPHP/PHP-CS-Fixer#3313]
For example i have this in my code: 
```
$veryLongVar = 'foo';
$shortVar    = 'bar';
```

When i fix the file it removes the spaces between the name and the `=`. Then it looks like this:
```
$veryLongVar = 'foo';
$shortVar = 'bar';
```
Is there a setting to keep the spaces?

**Comment by GrahamCampbell** [comment]
Yes, there is. Check the readme for `binary_operator_spaces`.

**Comment by tafelglotzer** [comment]
Thanks for the quick answer, works great!
