### ISSUE TITLE
Closing tag inside comment causes cs fixer to throw error

### ISSUE THREAD

**Issue by jxmallett** [FriendsOfPHP/PHP-CS-Fixer#3315]
I seem to have found a bug with handling of comments. The following file will cause an "errors reported during linting after fixing" error:

```php
<?php
function foo() {
    /*?>*/
    return 'bar';
}
```
The issue seems to be with comments starting with `/*` (ie a single asterisk after the slash). Changing the start to `/**` fixes the problem.

The error persists if the comment is changed to either of the following:
```php
/*
?>
*/

/*
 * ?>
 */
```

The `single_line_comment_style` option seems to cause the error because (I'm guessing) it changes the comment to `// ?>` which PHP interprets as a comment followed by a real closing tag.

I'm sorry I'm not familiar enough with cs fixer to fully track down the problem and suggest a fix.

#### The command you use to run PHP CS Fixer:
`/C/php/php.exe /C/php/php-cs-fixer.phar fix -n --verbose --config=php_cs.conf test.php`

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        'single_line_comment_style' => ['comment_types' => ['asterisk']],
    ])
;
```

#### Actual result
Files that were not fixed due to errors reported during linting after fixing:
 ... test.php

#### Expected result
```php
<?php

function foo() 
{
    /*?>*/
    return 'bar';
}
```

**Comment by jxmallett** [comment]
I'm actually undecided on the 'expected result'. It probably should error like it does because it's a very specific case with no obvious expected result.

It would be nice to have an option to save problematic styled files to disk so they can be reviewed. Eg:
```
php-cs-fixer fix --save-failed-fixes test.php
Files that were not fixed due to errors reported during linting after fixing:
1) test.php - Failed file saved as test.php.cs_failed
```

**Comment by SpacePossum** [comment]
thanks for reporting @jxmallett :+1:
