### ISSUE TITLE
unable to install in windows

### ISSUE THREAD

**Issue by cmk128** [FriendsOfPHP/PHP-CS-Fixer#3331]
Hi all, unable to install in windows

C:\Users\Peter\Desktop>php c:\download\composer.phar global require php-cs-fixer-v2.phar
Changed current directory to C:/Users/Peter/AppData/Roaming/Composer

  [InvalidArgumentException]
  Could not find a matching version of package php-cs-fixer-v2.phar. Check the package spelling, your version constraint and that the package is av
  ailable in a stability which matches your minimum-stability (stable).

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-depende
ncies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu
-autoloader] [--] [<packages>]...

C:\Users\Peter\Desktop>php c:\download\composer.phar global require php-cs-fixer
Changed current directory to C:/Users/Peter/AppData/Roaming/Composer

  [InvalidArgumentException]
  Could not find a matching version of package php-cs-fixer. Check the package spelling, your version constraint and that the package is available
  in a stability which matches your minimum-stability (stable).

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-depende
ncies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu
-autoloader] [--] [<packages>]...

**Comment by cmk128** [comment]
forget me, it working now, thanks

**Comment by SpacePossum** [comment]
good to hear this was resolved @cmk128 :+1: 
please let us know if you run into something else :)

**Comment by keradus** [comment]
for those who will find this thread looking for solution for similar issue, solution was to not use
`php c:\download\composer.phar global require php-cs-fixer-v2.phar`
but
`php c:\download\composer.phar global require friendsofphp/php-cs-fixer`
