### ISSUE TITLE
explicit_string_variable fixes object property access incorrectly

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3332]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.0

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.9.0-DEV

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('vendor');

return PhpCsFixer\Config::create()
    ->setRules(['explicit_string_variable' => true])
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
echo "$a->b";
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
echo "${a}->b";
```

 * with the changes you expected instead:
```php
<?php
echo "{$a->b}";
```

**Comment by Slamdunk** [comment]
Whops, my fault, keep traking https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3334 for the fix.
