### ISSUE TITLE
method_chaining_indentation unexpected changes when using HTML

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3338]
#### The PHP version you are using (`$ php -v`):
=> 7.2.0

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.9.0-DEV

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('vendor');

return PhpCsFixer\Config::create()
    ->setRules(['method_chaining_indentation' => true])
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<div>
    <?= $object
        ->method()
        ->method();
    ?>
</div>

<?= $object
    ->method()
    ->method();
?>
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<div>
    <?= $object
    ->method()
    ->method();
    ?>
</div>

<?= $object
        ->method()
        ->method();
?>
```

 * with the changes you expected instead:
Expected no changes.

**Comment by keradus** [comment]
ping @julienfalque
