### ISSUE TITLE
Why the composer.lock is not commited

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#3348]
Hello.

This code is a project. And like all other projects, the `composer.lock` should be committed.

Why it's not the case?

**Comment by keradus** [comment]
Hello. This code is not a "project".

Let us make a little dictionary first to make discussion easier.
- project - full scale application having business logic, maybe API, website, queue consumer, executed on concrete environment dedicated for it
- tool - little CLI application, executed on any environment
- library - code to be used by other projects

Then, IMO:
- project **must** have locked dependencies
- tool **may** have locked dependencies
- library **must not** have locked dependencies

Tools... look at other tools - eg PHPUnit - there is no lock files. It's not a project, where you do control environment. For tools, you have no idea which php would be used and what are the best deps versions for it. Like here - we allowed PHP 5.3+ | 7+.

Library is tricky, as one ofter, wrongly, commit the lockfile, which is later ignored when library is installed by given project, but it is respected when library is tested on CI, which leads to scenario when library is tested against only one set of deps versions, while it shall be tested across full range of allowed deps versions.

So. What is PHP CS Fixer? It is, at the same time, tool and library. For both of them, we don't need lock file. For later, we cannot have one. And finally, we do heavily test repo across different version of deps (We were even one of the earliest project that started performing tests against lowest deps allowed in composer.json).

If it is not convincing you - for your PHP CS Fixer as a tool usage, install it via phar file, which has deps included, and which is tested against them.

**Comment by lyrixx** [comment]
Thanks for the clarification ;)

I said that because I installed php-cs-fixer via git, and when I updated the version, I had to do `composer up` because it was broken.

More over [composer](https://github.com/composer/composer/blob/master/composer.lock) itself has `composer.lock` committed 

And finally in php-cs-fixer's `composer.lock` it says it's an `application` https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.9/composer.json#L3

But anyway, this is not a big deal ;)

**Comment by keradus** [comment]
> More over composer itself has composer.lock committed

> > tool may have locked dependencies


> And finally in php-cs-fixer's composer.lock it says it's an application

no way to specify multipurpose
