### ISSUE TITLE
PHP-CS-Fixer internals invalid phpdoc syntax

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3353]
I question if the syntax used for arrays in this project are valid syntax. Php documentor's type resolver crashes when resolving them because of the space after the comma. 

Good: `array<string,float>`, Bad `array<string, float>`.

---

Refs https://github.com/phpDocumentor/TypeResolver/issues/49.

**Comment by keradus** [comment]
when we started using that syntax, we were using, in general, psr-5 proposal, we did not follow phpDocumentor any time.
i guess no big deal if phpDocumentor want to fix it on their parser. our parser understands it.

**Comment by GrahamCampbell** [comment]
> when we started using that syntax, we were using, in general, psr-5 proposal

I searched the psr-5 spec for `array<`, and didn't find any matches. Did I miss it?

> we did not follow phpDocumentor

With this in mind, I looked to phpDocumentor, to see what was implemented there.

> i guess no big deal if phpDocumentor want to fix it on their parser. our parser understands it.

Well, I was establishing, if their parser actually broken, or is does the php-cs-fixer code have invalid syntax, and a parser that accepts invalid strings.

---

It looks like the syntax with the space is fine, and phpDocumentor should be fixed.

**Comment by GrahamCampbell** [comment]
Before we close this, can we establish what spec was used for that style of doc?

**Comment by keradus** [comment]
I searched the psr-5 spec for `array<`, and didn't find any matches. Did I miss it?

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#collections
eg `@return \ArrayObject<int, string>` (**with space**)

**Comment by GrahamCampbell** [comment]
Ah, well, that spec only corresponds to Object types, it doesn't actually say that you can do it with `array`. I think the PSR-5 spec needs clarifying, that is, if it's still being developed now! :)

**Comment by keradus** [comment]
Read it carefully.
It is already stating this:
> With Generics-style notation it is REQUIRED to specify a class name, or **the array keyword**, followed by the type of the values enclosed with angular brackets.

**Comment by GrahamCampbell** [comment]
Ah, right. They forgot about the `iterable` type then. :trollface:

**Comment by GrahamCampbell** [comment]
Actually, so did PHP-CS-Fixer. We should probably add it to our list of things. Sec, will comment on the other PR.
