### ISSUE TITLE
Can we deprecate phpdoc_no_package?

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3391]
...and add `package` and `subpackage` as defaults for `general_phpdoc_annotation_remove` and add it to `@Symfony`?

**Comment by keradus** [comment]
No, we can not.

`general_*` fixers are not supposed to be part of any ruleset, as they are highly configurable and it is not possible to predict out of the box conflicts, priority, riskyness and so, and it is not possible to have them configured differently in different rulesets and then use them at the same time.
In the end, `general_*` is a fixer that change code out of the blue, without following any concrete rule. But precise usage of it does represent very concrete rule.
If we figured out given behaviour for concrete configuration and on top of it we build up a rule, we store it as dedicated rule.
`general_*` rules shall be use directly only by experience users who knows what they are doing.
