### ISSUE TITLE
[RFC] PHP-CS-Fixer 3.0 to be PHP 7.0+

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3396]
See title. :)

**Comment by keradus** [comment]
no, 7.1

**Comment by GrahamCampbell** [comment]
Really? I'm fine with that also. Is there an issue tracking the changes in 3.0. The current 3.0 branch is still on 5.6?

**Comment by keradus** [comment]
current 3.0 branch was created yesterday. give it a time.

**Comment by GrahamCampbell** [comment]
![parrot](http://emojis.slackmojis.com/emojis/images/1495224267/2309/popcorn_parrot.gif?1495224267)
