### ISSUE TITLE
Removing "use_yoda_style" option in "is_null" fixer

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3399]
As we have `yoda_style` to handle Yoda conditions we can easily drop handling it in `is_null` fixer.

That would be split into 2 pull request:
- deprecating option to master branch
- removing option to 3.0 branch

Pinging Jedi Master @SpacePossum

**Comment by SpacePossum** [comment]
sounds like a good idea to me :)
maybe the force be with your PR's!

**Comment by keradus** [comment]
Kuba, could you please propose PRs ? Thanks !

**Comment by keradus** [comment]
closing as done
