### ISSUE TITLE
drop `--diff-format` option

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#3400]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3384#discussion_r160030201

**Comment by keradus** [comment]
cc @FriendsOfPHP/php-cs-fixer

**Comment by fabpot** [comment]
👍

**Comment by keradus** [comment]
haha, sorry to ping you as well, I thought you are only in `PHP-CS-Fixer-admin` team ;)
If you would like to get less notifications @fabpot, leave used group and stay in admin only ;)

**Comment by fabpot** [comment]
Actually, I like to get some notifications from time to time. I still like this project very much :)

**Comment by SpacePossum** [comment]
close because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3384 has been merged,
thanks @keradus :)

**Comment by keradus** [comment]
reopening, #3384 was removing extra values of this option, yet option still exists

**Comment by keradus** [comment]
I have doubts about dropping the `diff-format`. it can be good extension point for future, even if now we have only single differ.

what do you think, @SpacePossum @julienfalque @kubawerlos @sebastianbergmann ?

**Comment by SpacePossum** [comment]
Having different report formats is a great thing we have, json/xml/checkstyle.
However for formatting diffs I think most developers are used to udiff (as used by git etc.) and I see no real candidate to we wanted to add soon.
As such I think removing it is fine (less code to maintain), if we want to support a different format in the future we can still add support for it.
If the concern is BC breaks than maybe we can still allow just only except that one value (like we have now), but I think the actually usage of the option is pretty low.
