### ISSUE TITLE
FOpenFlagOrderFixer - vs 'b'/'t'

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#3417]
ref #3405

```diff
-fopen($foo, 'b+r')
+fopen($foo, 'r+b')
```
```diff
-fopen($foo, 't+w', $a, $b)
+fopen($foo, 'w+t', $a, $b)
```
```diff
fopen($foo, $bar, $a, $b)
```

**Comment by keradus** [comment]
cc @ntzm

**Comment by ntzm** [comment]
I'm not sure if `b` or `t` being last actually makes a difference in terms of behaviour, but PHP's manual clearly states that they should be last.

It's the same with Linux C: https://linux.die.net/man/3/fopen

> The mode string can also include the letter 'b' either as a last character or as a character between the characters in any of the two-character strings described above.

However it notes that the flag is ignored on all POSIX systems

**Comment by SpacePossum** [comment]
almost done with this one, however `FOpenFlagOrderFixer` is not a valid fixer name ;)  any suggestions?

**Comment by julienfalque** [comment]
`FopenFlagOrderFixer`?
