### ISSUE TITLE
Add 'sortAlgorithm' to 'ordered_class_elements'

### ISSUE THREAD

**Issue by meridius** [FriendsOfPHP/PHP-CS-Fixer#3433]
PHP-CS-Fixer has `ordered_class_elements` sniff which does ordering only by element type `['use_trait', 'constant_public', 'constant_protected', 'constant_private', 'property_public', 'property_protected', 'property_private', 'construct', 'destruct', 'magic', 'phpunit', 'method_public', 'method_protected', 'method_private']`

There should be a possibility to order also by the name of the element, not only by its type.

There is already `ordered_imports` sniff which supports option `sortAlgorithm` with possible values `('alpha', 'length')`.

The resulting configuration could then look like:

```php
...
'ordered_class_elements' => [
    'order' => [
        'use_trait',
        'constant_public',
        'constant_protected',
        'constant_private',
        'property_public',
        'property_protected',
        'property_private',
        'construct',
        'destruct',
        'magic',
        'phpunit',
        'method_public',
        'method_protected',
        'method_private',
    ],
    'sortAlgorithm' => 'alpha',
],
...
```

Which would order the class elements by their type and for multiple `method_public` or similar there would then be used the defined sorting algorithm.

**Comment by keradus** [comment]
Hi @meridius , could you please create a PR proposal ?

**Comment by meridius** [comment]
Hi @keradus, I'll try to look into it during this weekend.

**Comment by meridius** [comment]
Hi @keradus, all the builds are passing except AppVeyor because of exceeded build time for plan. 

Could you please look at the PR #3448 and let me know what you think?

Thank you
