### ISSUE TITLE
PhpUnitTestAnnotationFixer false positive since 2.10

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#3437]
It now duplicates `test()` name to `testTest()`. It didn't happen before 2.10.

What was changed?

![image](https://user-images.githubusercontent.com/924196/34849205-e6bb7950-f721-11e7-81c7-03cd8943ee39.png)

See also Travis: https://travis-ci.org/Symplify/Symplify/jobs/327849604#L644

**Comment by localheinz** [comment]
Follows #3312. 

I‘ll take a look later.

**Comment by localheinz** [comment]
@TomasVotruba 

Can you please share your configuration?

**Comment by localheinz** [comment]
@TomasVotruba 

Never mind, a fix is under way with #3438!

**Comment by SpacePossum** [comment]
#### The PHP version you are using (`$ php -v`):
PHP 7.2.0-2+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Dec  7 2017 20:14:31) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.10.0 Bowling Bear by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
$ php php-cs-fixer fix tmp/MyTest.php --dry-run -vvv --diff --rules=php_unit_test_annotation

#### The configuration file you are using, if any:
n/a

#### If applicable, please provide minimum samples of PHP code (as plain text,
##  not screenshots
):
 * before running PHP CS Fixer (no changes):
```php
<?php

class MyTest
{
    /**
     */
    public function test()
    {
    }
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

class MyTest
{
    /**
     */
    public function testTest()
    {
    }
}

```

 * with the changes you expected instead:
not sure

**Comment by TomasVotruba** [comment]
@SpacePossum Too long description for simple problem described in first sentence and name.
Screenshot is not so relevant, just explanatory. In more complicated problem I'd add those of course.

@localheinz thank you! What PR broke this actually?

**Comment by localheinz** [comment]
@TomasVotruba 

Hehe, I just didn't think of the case where someone would use `test` as a test method name, hehe! Thank you for reporting, I'm glad we could resolve this quickly!

**Comment by TomasVotruba** [comment]
@localheinz No problem :) I use them for classes with one important method with data provider.

Mee too, great job :+1:

**Comment by localheinz** [comment]
Thank you, @TomasVotruba!
