### ISSUE TITLE
Change order of NoEmptyPhpdocFixer or ClassAttributesSeparationFixer

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#3441]
This issue is related to unresolved #3245

- v2.10
- PHP 7.1.11

## Use Case

When I run this setup on:

- `ClassAttributesSeparationFixer`, priority 55
- `NoEmptyPhpdocFixer`, priority 5

on this code

```php
<?php

class SomeClass
{
    public function one()
    {
    }

    /**
     */
    public function two()
    {
    }
}
```

Only 2nd is applied, doc block removed:

```diff
<?php

class SomeClass
{
    public function one()
    {
    }

-    /**
-     */
+
    public function two()
    {
    }
}
```

Then 2nd run is required, to remove the space with `ClassAttributesSeparationFixer`

```diff
<?php

class SomeClass
{
    public function one()
    {
    }

-
    public function two()
    {
    }
}
```

### Expected Behavior

Only **1 run**, not 2

Options:

- fix #3245, as it should be
- do workaround and change order of these fixers - that could be difficult due to priority dependencies - and make `NoEmptyPhpdocFixer` run first

`NoEmptyPhpdocFixer`

```php
    /**
     * {@inheritdoc}
     */
    public function getPriority()
    {
        // should be run before NoExtraBlankLinesFixer, NoTrailingWhitespaceFixer, NoWhitespaceInBlankLineFixer and
        // after PhpdocNoAccessFixer, PhpdocNoEmptyReturnFixer, PhpdocNoPackageFixer, PHPUnitTestAnnotationFixer.
        return 5;
    }
```

`ClassAttributesSeparationFixer`

```php
    /**
     * {@inheritdoc}
     */
    public function getPriority()
    {
        // Must run before BracesFixer and IndentationTypeFixer fixers because this fixer
        // might add line breaks to the code without indenting.
        return 55;
    }
```

**Comment by SpacePossum** [comment]
issue extends more fixers,
for example:

```php
trait SerializersResolverTrait
{
    /**
     * @var RepositoriesService
     */
    private $repositoriesService;

    /**
     * @var FileSyncer
     */
    protected $fileSyncer;

    protected function getSerializer(string $class): EntitySerializerForSyncInterface
    {
```

```php
trait SerializersResolverTrait
{
    /**
     * @var FileSyncer
     */
    protected $fileSyncer;
    /**
     * @var RepositoriesService
     */
    private $repositoriesService;
```

Therefore the concept of "fix #3245, as it should be", which I think mean that all the fixers should be able to deal with empty lines, is beyond me as it would cause a lot of repeating I think.
Wish I had time to figure out the priorities soon, but I don't think I have :|

**Comment by TomasVotruba** [comment]
I'm not sure I understand. How would you solve this?

**Comment by SpacePossum** [comment]
`do workaround and change order of these fixers` , that would be my first try

**Comment by TomasVotruba** [comment]
Outdated
