### ISSUE TITLE
To mbstring, or not to mbstring?

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3447]
Is there official/final decision about this extension? Ping @keradus 

I'm confused - it is not required in `composer.json` and I've got a comment in PR not use it, yet listed in [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/.composer-require-checker.json) not to scream about its usage.

Can we go one way? Require it or remove from `.composer-require-checker.json`?

----

As extra task maybe fully synchronise `composer.json` with `.composer-require-checker.json` in the terms of PHP extensions? With AutoReview to check they synched?

**Comment by SpacePossum** [comment]
Using `mb_string` will give the best results, however using the `polyfill` (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/composer.json#L47) will work as well.
Having neither, must be OK as well (please report if not).

As for `composer-require-checker`; it cannot detect that the extension is not required at all.
For example from the code base;

```php
        if (!function_exists('mb_detect_encoding')) {
            return $data;
        }

        array_walk_recursive($data, static function (&$item) {
            if (is_string($item) && !mb_detect_encoding($item, 'utf-8', true)) {
                $item = utf8_encode($item);
            }
        });
```

this will trip the detection, will the extension is not required, therefore we put it in the white list

**Comment by SpacePossum** [comment]
I don't think there is an action open here and as such I close this one, @kubawerlos if I missed anything please let me know and we'll see from there :)
