### ISSUE TITLE
it there way for run some custom php code for processing content of file after PHP-CS-Fixer ?

### ISSUE THREAD

**Issue by rivetweb** [FriendsOfPHP/PHP-CS-Fixer#3461]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> ....................................

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> ....................................

#### The command you use to run PHP CS Fixer:
=> ....................................

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> ....................................
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> ....................................
```

 * with the changes you expected instead:
```php
=> ....................................
```

**Comment by rivetweb** [comment]
i need to process content of each file after formating that file by PHP-CS-Fixer

**Comment by SpacePossum** [comment]
Hi,

When using PHP CS Fixer as lib. you could utilize on the `EventDispatcher` or a listener on that, as the dispatcher is passed to `Runner` which in turn dispatches events like `FixerFileProcessedEvent::STATUS_FIXED` etc. through it.
(this might be a good starting point to see it at work: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Runner/Runner.php#L265)

If you use the project as tool (i.e. `phar`) from the command line you can parse the output and act upon it, see the docs for output formats details (`json`, `xml`, `checkstyle` and `junit` are available as "parsable" formats)

**Comment by rivetweb** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Runner/Runner.php#L265

there is no information about fixed filename  - only status

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/93b6694bada0fed87cf2668447f6e3b52197c074/src/FixerFileProcessedEvent.php

how to get file name?

**Comment by julienfalque** [comment]
Note that `FixerFileProcessedEvent` is `@internal` so you shouldn't rely on it at all as the class might or get removed at any time. I think the tool has no official support for third party event listeners, does it?

**Comment by keradus** [comment]
no.
TBH, I do not understand the request - what you actually want to do @rivetweb ?
"process content" is very generic

**Comment by rivetweb** [comment]
nvm 

i made own fork https://github.com/rivetweb/PHP-CS-Fixer/tree/bitrix

 there you can check what is process content means

**Comment by SpacePossum** [comment]
>there you can check what is "process content" means

So something about white space after a `{`?  you could do that with a custom fixer as well.
Well; let us know if you want to know more, if so please give a small description in English, it is easier than reading code, thanks!

**Comment by rivetweb** [comment]
can you provide a compete example for fix brackets?

**Comment by rivetweb** [comment]
``

**Comment by SpacePossum** [comment]
A good starting point for any fixer is the cookbook (in the docs) and by studying a current known-good-fixer that does something similar/close to what you want.
In this case that would be the `braces` fixer that has multiple methods that show how you can move braces around.
Since the custom fixer you want is not suitable for this repo this issue is more of a question for support. As such I close the issue, but feel free to ask more detailed questions if you get stuck with the development of the custom fixer.
