### ISSUE TITLE
include fixer doesn't fix correctly when using include_once/require_once and include/require

### ISSUE THREAD

**Issue by haroldb** [FriendsOfPHP/PHP-CS-Fixer#3463]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.10.0

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix --rules=include test.php

#### The configuration file you are using, if any:
N/A

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
require_once('test1.php');
include_once('test2.php');
require('test3.php');
include('test4.php');
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
require_once 'test1.php';
include_once 'test2.php'; require('test3.php');
 include('test4.php');
```

 * with the changes you expected instead:
```php
<?php
require_once 'test1.php';
include_once 'test2.php';
require 'test3.php';
include 'test4.php';

```

**Comment by SpacePossum** [comment]
thanks @haroldb for reporting!
