### ISSUE TITLE
what is the use off digital marketing?

### ISSUE THREAD

**Issue by careenjoseph** [FriendsOfPHP/PHP-CS-Fixer#3470]
For it is the process of attracting targeted audiences online that will spell the difference between a successfully thriving business – and a failed one. Even if you receive tons of daily traffic to your website, they would not amount to anything unless they convert to leads or sales. In the digital arena where business and commerce are heading to, Digital Marketing tools and techniques provide business owners the best chances for competition, survival and even business growth.
https://www.besanttechnologies.com/training-courses/other-training-courses/digital-marketing-training-institute-in-chennai

**Comment by SpacePossum** [comment]
please explain what this has to do with this repo and or its community, thanks
