### ISSUE TITLE
The native_function_invocation should not add a trailling \ on file without namespace

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#3471]
On a PHP file like this:

```php
<?php

declare(strict_types=1);

ini_set('memory_limit', '4096M');
```

`ini_set` does not necessary need a trailing `\` if the file does not have any namespace on some CS rule, like this one: https://github.com/slevomat/coding-standard/blob/823ba04bdcfe642ec2b912e4650d6e33d48c2ef7/SlevomatCodingStandard/Sniffs/Namespaces/ReferenceUsedNamesOnlySniff.php#L22

```
 5 | ERROR | [x] Function \ini_set() should not be referenced via a fully qualified name, but via an unqualified name without the leading \, because the file does not have a namespace and the type cannot be put in a use statement.
   |       |     (SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFullyQualifiedNameWithoutNamespace)
```

Many possibilities:

1. The fixer should not add a trailling `\` on file without a namespace.
2. The fixer should **remove** trailling `\` on file without a namespace.
3. The behavior of both `1` and `2` might be configurable with an option like `namespaced_file_only` and may be `true` as default.

What do you think?

**Comment by SpacePossum** [comment]
Hi and thanks,

This has been discussed and there is a PR open that will bring you that:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3223

please help out by commenting/reviewing/co-PR'ing there (or any other PR/issue about this topic)
