### ISSUE TITLE
[3.0] Remove readme-command

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3473]
I propose to remove the readme generate command and refactor to a dedicated script.
The command has little value to end users and does not need to be shipped with the release.
We do need it (of course) at dev time, however for that it is not needed (to list) as command.

**Comment by kubawerlos** [comment]
@SpacePossum what do you think about moving it (or its replacement form #3475) to `dev-tools`? I did this in [custom fixers](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v2.1.0/dev-tools/src) and it works well for some time.

**Comment by SpacePossum** [comment]
indeed better to do with the doc refactor

**Comment by julienfalque** [comment]
I added a TODO to #3475.
