### ISSUE TITLE
ordered_class_elements fixer should be under Symfony ruleset

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#3482]
I can't find similar issues, so I open the issue.

According to the [official coding standard documentation](https://symfony.com/doc/current/contributing/code/standards.html):

> Declare public methods first, then protected ones and finally private ones. The exceptions to this rule are the class constructor and the setUp() and tearDown() methods of PHPUnit tests, which must always be the first methods to increase readability;

This is exactly what `ordered_class_elements` does AFAIK. What not adding it on the Symfony ruleset?

**Comment by SpacePossum** [comment]
Hi,
Did you try running it on the SF code base (lowest maintained version)? Wonder how many issues there are.

**Comment by SpacePossum** [comment]
Closing after discussion;
we can reopen this when a PR at SF repo has been accepted which contains the changes this fixer makes, or when the SF deciders want to have this rule at the SF set.
