### ISSUE TITLE
Fixer for changing array_push($a, $b) to $a[] = $b 

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3483]
> Note: If you use array_push() to add one element to the array it's better to use $array[] = because in that way there is no overhead of calling a function.

Source: https://secure.php.net/manual/en/function.array-push.php

I think this fixer may be risky because there is a change in behaviour:

> Note: array_push() will raise a warning if the first argument is not an array. This differs from the $var[] behaviour where a new array is created.

**Comment by SpacePossum** [comment]
added in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4790
