### ISSUE TITLE
Ternary to elvis fixer

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3485]
When the first and the second operands are the same:

```diff
-$a = $b ? $b : $c;
+$a = $b ?: $c;
```

**Comment by keradus** [comment]
@EvgenyOrekhov, hi, thanks for bringing up great idea !
this project is quite big and mature already, it's super hard to bring all requested features just by core team, could you please create a PR for this feature ?

**Comment by EvgenyOrekhov** [comment]
@keradus Sorry, I don't have the time for it.

**Comment by carusogabriel** [comment]
@keradus I'll try this one as my study of Tokens :nerd_face:

**Comment by SpacePossum** [comment]
done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3485

**Comment by guilliamxavier** [comment]
*done in #4741
