### ISSUE TITLE
[RFC] Use PHPUnit dedicated method

### ISSUE THREAD

**Issue by carusogabriel** [FriendsOfPHP/PHP-CS-Fixer#3493]
Recently, [I made several PRs in Symfony refactoring some tests](https://github.com/symfony/symfony/pulls?q=is%3Apr+author%3Acarusogabriel+is%3Aclosed), and I believe we can automatize this with this library. 

I'd like to discuss with the core team what is possible to do with PHP Tokens (also what should I study to create this Fixer).

Related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3342#issuecomment-354742676.

**Comment by SpacePossum** [comment]
Sounds great :)
Maybe it would be nice to start listing the changes so these can be discussed

**Comment by carusogabriel** [comment]
@SpacePossum I did [this table](https://docs.google.com/spreadsheets/d/145hef6esG-B09AfooY-4e0oFKa1eVDoeUeo-eXVZRoA/edit?usp=sharing) a while ago, and might be something to start with :smile:

**Comment by Slamdunk** [comment]
Some of those are already in plase:

* [PhpUnitConstructFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/PhpUnit/PhpUnitConstructFixer.php)
* [PhpUnitDedicateAssertFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php)

**Comment by carusogabriel** [comment]
@Slamdunk Yes, a lot of them actually. I thought in a `PhpUnitDedicateComparisonAssertFixer` from the `comparison operators` table

**Comment by keradus** [comment]
what is column `C` ?

**Comment by carusogabriel** [comment]
@keradus Sorry, was a column to track the created ones. I removed.

Do you think we should have here, and is possible with Tokens? Also, is something to fix, or is more a refactoring?

**Comment by keradus** [comment]
remember that Fixer change not only style.
We already do a lot of phpunit changes, one type is better assertions, other is migrate to newer phpunit version, definietly sth possible with Tokens.

**Comment by carusogabriel** [comment]
So I'll study and open a PR with some ideas :smile:
