### ISSUE TITLE
[Installation] Cannot install fresh fork of PHP-CS-Fixer

### ISSUE THREAD

**Issue by carusogabriel** [FriendsOfPHP/PHP-CS-Fixer#3497]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.1.13

I forked the repo and try to install locally. Received this error from Composer:
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package php-cs-fixer/diff ^1.2 exists as php-cs-fixer/diff[dev-differ3, dev-master, v1.0.0, v1.1.0] but these are rejected by your constraint.
```

I checked my global installs, and nothing, as well other dependencies that might conflict.

Edit: this is a global conflict, all build is failing due that https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3492

**Comment by reardestani** [comment]
Same here

**Comment by carusogabriel** [comment]
Related to https://github.com/PHP-CS-Fixer/diff/issues/8

**Comment by SpacePossum** [comment]
please try again, we got a v1.2.1 release now to try to fix this issue while we try to figure out what happened to v1.2.0

thanks for the heads up all!

**Comment by carusogabriel** [comment]
@SpacePossum Now is working, thanks for the quick fix.

Should I let this open to track this problem?

**Comment by SpacePossum** [comment]
Thanks @carusogabriel for reporting back.
I'm closing this issue as it is kind of resolved and the real issue is with the diff package and packagist.org , so we don't have to track it here anymore I think.

**Comment by keradus** [comment]
just a feedback.
1.2.0 was restored, it was an issue on packagist side fixed at 5th by Jordi
