### ISSUE TITLE
[Regression] Empty line above declare() being removed.

### ISSUE THREAD

**Issue by skyzyx** [FriendsOfPHP/PHP-CS-Fixer#3508]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.2.2 (cli) (built: Jan  5 2018 17:34:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.10.2 Bowling Bear by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
https://github.com/simplepie/simplepie-ng/blob/master/Makefile#L65

#### The configuration file you are using, if any:
https://github.com/simplepie/simplepie-ng/blob/master/.php_cs.dist

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
Can be seen several times in [this commit](https://github.com/simplepie/simplepie-ng/commit/061ea878b01763119513c51421fa57a1d9240743). It appears that between v2.10.0–v2.10.2, the empty line between the the file header and the `declare` line is now being removed.

 * before running PHP CS Fixer (no changes):
```php
<?php
/**
 * Copyright (c) 2017–2018 Ryan Parman <http://ryanparman.com>.
 * Copyright (c) 2017–2018 Contributors.
 *
 * http://opensource.org/licenses/Apache2.0
 */

declare(strict_types=1);

namespace SimplePie\Exception;

use Exception;

/**
 * `SimplePieException` is the base `Exception` class for all SimplePie-related exceptions.
 */
class SimplePieException extends Exception
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
/**
 * Copyright (c) 2017–2018 Ryan Parman <http://ryanparman.com>.
 * Copyright (c) 2017–2018 Contributors.
 *
 * http://opensource.org/licenses/Apache2.0
 */
declare(strict_types=1);

namespace SimplePie\Exception;

use Exception;

/**
 * `SimplePieException` is the base `Exception` class for all SimplePie-related exceptions.
 */
class SimplePieException extends Exception
{
}
```

 * with the changes you expected instead:
```php
<?php
/**
 * Copyright (c) 2017–2018 Ryan Parman <http://ryanparman.com>.
 * Copyright (c) 2017–2018 Contributors.
 *
 * http://opensource.org/licenses/Apache2.0
 */

declare(strict_types=1);

namespace SimplePie\Exception;

use Exception;

/**
 * `SimplePieException` is the base `Exception` class for all SimplePie-related exceptions.
 */
class SimplePieException extends Exception
{
}
```

**Comment by SpacePossum** [comment]
Thanks for reporting!

Does this happen only with `declare` cases? I wonder if this might have the same cause as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3503 , for which than the same fix could be tried on the samples here.

**Comment by julienfalque** [comment]
I confirm: I was able to reproduce this on v2.10.2 but not on v2.10.3, on which #3504 was merged.
