### ISSUE TITLE
PHPDoc with latin1 characters in file with ISO-8859-1 encoding causes error 

### ISSUE THREAD

**Issue by sakarikl** [FriendsOfPHP/PHP-CS-Fixer#3509]
If I change the file encoding to UTF-8 everything works fine.

Code causing the error is in https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/Phpdoc/PhpdocTrimFixer.php#L115

fixEnd methods preg_replace returns null

#### The PHP version you are using (`$ php -v`):
php -v
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 
php-cs-fixer -V
PHP CS Fixer 2.10.2 Bowling Bear by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> 
php-cs-fixer fix test-cs-fixer.php --using-cache=no -vvv --rules=@Symfony

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

/**
 * ä
 */
$variable = NULL;

```

#### Output of command

Loaded config default.
E
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Fixed all files in 0.013 seconds, 12.000 MB memory used

Files that were not fixed due to errors reported during fixing:
   1) test-cs-fixer.php
                                               
        [InvalidArgumentException]             
        Content must be a string, got "NULL".  
                                               
      PhpCsFixer\Tokenizer\Token->__construct()
        in vendor/friendsofphp/php-cs-fixer/src/Fixer/Phpdoc/PhpdocTrimFixer.php at line 81
      PhpCsFixer\Fixer\Phpdoc\PhpdocTrimFixer->applyFix()
        in vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 73
      PhpCsFixer\AbstractFixer->fix()
        in vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 190
      PhpCsFixer\Runner\Runner->fixFile()
        in vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 132
      PhpCsFixer\Runner\Runner->fix()
        in vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php at line 219
      PhpCsFixer\Console\Command\FixCommand->execute()
        in vendor/symfony/console/Command/Command.php at line 262
      [ ... ]

**Comment by sakarikl** [comment]
Same thing happens with php 7.1.14

without u modifier in regexp works fine.

modifier was added in https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/fbfc252f37c966612539483b811ea4376f8f1e66

**Comment by julienfalque** [comment]
Thanks for the report. This is a known issue, see #3309 and #3446.

Closing as duplicate.
