### ISSUE TITLE
Historical Issue Research Question

### ISSUE THREAD

**Issue by ktomk** [FriendsOfPHP/PHP-CS-Fixer#3530]
In https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1593#issue-121885869 @uuf6429  mentioned an existing issue but it was not specified which one was meant.

In https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1593#issuecomment-364938802 I was asking about that historical reference as I didn't want to do any assumptions.

Then in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1593#issuecomment-364940738 @SpacePossum made me require to open a new issue to ask about the historical reference.

The required new issue are you reading currently, its reference number is: #3530

**Comment by keradus** [comment]
@ktomk , could you please state your question ?

**Comment by ktomk** [comment]
@keradus: Sorry if that was hidden behind the bureaucracy, the reference to the question is  https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1593#issuecomment-364938802:

> @uuf6429: Perhaps you can resurrect it, to which that time existing issue did you refer to?

The reference to the context to that question is https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1593#issue-121885869:

> As a result of the issue #158, php-cs-fixer exits with a value of 1 when changes are found, regardless if --dry-run was specified or not.
>
> Ideally, when --dry-run is disabled and the status is non-zero it should either mean an error occurred, or some issues cannot be fixed automatically.
>
> Closed; I just realized there's already an issue for this.

(markdown not preserved)

Did that answer your question?

**Comment by keradus** [comment]
if your only question is about
> > Closed; I just realized there's already an issue for this.
> Perhaps you can resurrect it, to which that time existing issue did you refer to?

then I have no idea what was the other issue, as I don't know what's the original question is about, as everything else is a statement.

**Comment by uuf6429** [comment]
Hi all.

I don't remember the details (it's been two years!), but from what I remember, I needed a way to know if php-cs-fixer fixed something vs something failed.

Since then, many new exit codes have been implemented: https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes

**Comment by ktomk** [comment]
@uuf6429: Thanks for the quick and insightful reply. I'm looking for a non-zero exit code for the `fix` command not having the `--dry-run` switch and when files are changed.

**Comment by keradus** [comment]
as @uuf6429 mentioned, https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes 

it would be
If you want to fix files, and tools does it job properly (no random crash like RuntimeException or sth), it reports success - and success is always 0 exit status (regardless there were files that required fix or not).
If you want to lint files (`fix --dry-run`), if linting failed, you will get non-zero exit code (`8` to be specific).

**Comment by ktomk** [comment]
I'm currently using`fix --dry-run` (and did so in the past), was just looking how to combine the build on the CI server and the local system build.

local system build is allowed to change files.

ci server is not.

I was searching if possible to run the same command on both systems, but so far just work around by using two different commands.

**Comment by keradus** [comment]
no, different usage, different purpose, way different behaviour, different command ;)

**Comment by ktomk** [comment]
@keradus  Well that depends as so often, e.g. in my scenario it would be fine for the local build to fail on changes so that the user can review, then rinse and repeat (pre commit).

The remote build just would notice a failure and stop then (post commit).

So even with a different command the same process. Just not any utility option of a non-zero exit status on successful fixes. But that was no critique, just to explain what looking for, not saying what expected to find ready-made ;)
