### ISSUE TITLE
PhpdocScalarFixer - Callback classname is seen as an issue in php docblock

### ISSUE THREAD

**Issue by B-Galati** [FriendsOfPHP/PHP-CS-Fixer#3536]
Hello !

Following #3492, my `Callback` class is detected as cs issue in docblock while `Callback` is a valid classname in my context.

```
     /**
-     * @var Collection|Callback[]
+     * @var Collection|callable[]
      *
      * @ORM\OneToMany(targetEntity="AppBundle\Entity\WebHook\Callback", mappedBy="webHook", cascade={"all"}, orphanRemoval=true)
      *
```

#### The PHP version you are using (`$ php -v`):
=> 
```
PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.2~linux-x64-non_zts71, https://blackfire.io, by SensioLabs
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `PHP CS Fixer 2.10.2 Bowling Bear by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/src')
    ->in(__DIR__.'/tests')
    ->in(__DIR__.'/app')
    ->in(__DIR__.'/features/bootstrap')
    ->exclude(__DIR__.'app/data')
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'phpdoc_to_comment' => false,
        'no_unneeded_final_method' => false,
        'concat_space' => ['spacing' => 'none'],
        'multiline_whitespace_before_semicolons' => ['strategy' => 'new_line_for_chained_calls'],
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/var/.php_cs.cache')
;
```

 * with the changes you expected instead: nothing

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

THB I'm not sure why `Callback` is touched by a `scalar`-fixer, nor why this is not documented in the README / describe samples, secondly it was added unconditionally (i.e. not configurable).

**Comment by julienfalque** [comment]
Indeed, `callback` replacement should have been added via a configuration option, and not enabled by default. Also I think it's the only way to fix this issue: in the example above, the `Callback` class is in the same namespace so we cannot be sure whether `Callback` is an actual class and `callable` was *not* intended.

IMO we should make the list of replacements configurable, and target branch 2.10.

We could add a check on `use` statements to avoid replacing a type that is imported, but that would not cover all cases so I think it's not worth it.

**Comment by B-Galati** [comment]
Thanks ! \o/
