### ISSUE TITLE
PHP Parse error:  syntax error, unexpected on line 980

### ISSUE THREAD

**Issue by vittore** [FriendsOfPHP/PHP-CS-Fixer#3537]
#### The PHP version you are using (`$ php -v`):
PHP 7.0.27 (cli)

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
get error:
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/options-resolver/OptionsResolver.php on line 980

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/options-resolver/OptionsResolver.php on line 980

Installed in OSX with homebrew.

**Comment by keradus** [comment]
homebrew installed package using php 7.1+, but you run it with php 7.0.
use same php version, raise issue to homebrew, install via composer or phar.
