### ISSUE TITLE
mb_string_functions and strncmp

### ISSUE THREAD

**Issue by soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#3554]
Let's start with this code sample:

```
$str = 'éàçééééé,ef';
dump(strncmp($str, 'ée', strlen('ée'))); // displays int(94)
dump(strncmp($str, 'ée', mb_strlen('ée'))); // displays int(0)
```

As you can see, the first test without `mb_` is correct, no the second.

It's because `strncmp` does a binary safe comparison.

IMO, the `mb_string_functions` should not change `strlen` to `mb_strlen` when we are inside a `strncmp` call.

If you think it's not possible or out of the PHP-CS-Fixer scope, in this case we should add this detail to the risky warning.

**Comment by ntzm** [comment]
I think the risky description needs updating to explain it will also change behaviour on multibyte strings, not just if the functions are overridden.

**Comment by keradus** [comment]
if one could provide a fix, I would gladly merge it.
Yet, I'm afraid that it's not the only problematic case.
Always :+1: for extending description of rule.
