### ISSUE TITLE
All config options should follow the same casing rules

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3567]
Most options seems to follow `snake_case`, but some like `header_comment` have `commentType`. Would be good to normalise these

**Comment by keradus** [comment]
Good point.

Things to do:
- create an AutoReview test that check if all options are snake_case,
- for those which not, make new option that suppresses old option (`comment_type` over `commentType`), deprecate old option and make it an exception to new AutoReview check
- make dedicated PR for 3.0 line to remove deprecated options

**Comment by keradus** [comment]
@ntzm , would you like to dive into it?

**Comment by ntzm** [comment]
I would love to!

**Comment by ntzm** [comment]
So in terms of branches:

- The AutoReview targets 2.2
- The new options that suppress the old options targets 2.2
- The deprecation of non snake_case options targets master
- The removal of deprecated options targets 3.0

Is this correct?

**Comment by mvorisek** [comment]
@SpacePossum is there a roadmap when the 3.0 version will be releases?

**Comment by SpacePossum** [comment]
Hi,
I missed the last checking with the maintainers, but AFAIK there is no target date besides "this year" (I hope we make that one : ) ).

**Comment by keradus** [comment]
all identified cases were marked as aliased and provided with both casing on 2.x line, and then cleaned up on 3.0-dev
