### ISSUE TITLE
"class_definition" fixer does not allow to keep multi-line class definitions (even if 'singleLine' => false)

### ISSUE THREAD

**Issue by vyshkant** [FriendsOfPHP/PHP-CS-Fixer#3569]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.10.2 Bowling Bear by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
```
php-cs-fixer -vvv fix src/Path/To/My/FooClass.php
```

#### The configuration file you are using, if any:
```php
<?php

declare(strict_types=1);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PHP56Migration' => true,
        '@PHP56Migration:risky' => true,
        '@PHP70Migration' => true,
        '@PHP70Migration:risky' => true,
        '@PHP71Migration' => true,
        '@PHP71Migration:risky' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'no_php4_constructor' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'non_printable_character' => ['use_escape_sequences_in_strings' => true],
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'class_definition' => [
            'singleLine' => false,
        ],
    ])
    ->setRiskyAllowed(true)
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(['app', 'bin', 'src', 'tests'])
            ->append(['.php_cs.dist', '.phan.dist', 'web/app.php', 'web/app_dev.php'])
    )
    ->setUsingCache(false)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
final class FooClass
extends AbstractFooClass
implements FooInterface
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
final class FooClass extends AbstractFooClass implements FooInterface
{
}
```

 * with the changes you expected instead:
```php
final class FooClass
extends AbstractFooClass
implements FooInterface
{
}
```

## Subject
I've overridden `singleLine` property of `class_definition` fixer to `false`, so I expect my multiline class definition will not be "fixed" to single line. But it is.

I think this behavior is unexpected, and suggest either to fix it (if it is a bug), or to add an extra option to customize `class_definition` fixer properly.

**Comment by keradus** [comment]
The rule is build on top of PSR-2, which enforce:
> 4.1 The extends and implements keywords MUST be declared on the same line as the class name.

what it doesn't enforce is where to put classes that our class extends (if there are no interfaces) or interfaces that our class implements, they could be on next line, multiple next lines, same line... and for that, we do have configuration options.
But main rule of PSR-2 to have classname and keywords (`class MyClass *extends* (...) *implements* (...)`) in same line is not breakable with configuration.

**Comment by vyshkant** [comment]
Thank you for the answer!
