### ISSUE TITLE
GeneralPhpdocAnnotationRemoveFixer - does not remove given annotation

### ISSUE THREAD

**Issue by MarcusFulbright** [FriendsOfPHP/PHP-CS-Fixer#3570]
When trying to use the rule `general_phpdoc_annotation_remove` to remove some `@noinspection` annotations, I get get the following error: `[InvalidArgumentException]  Cannot set empty content for id-based Token.`

The particulars of my set up are below: 

#### The PHP version you are using (`$ php -v`):
7.1.11

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.10.3

#### The command you use to run PHP CS Fixer:
vendor/bin/php-cs-fixer fix --config=.php_cs.dist.php -vvv

#### The configuration file you are using, if any:
Only Rule: ` 'general_phpdoc_annotation_remove' => ['annotations' => ["noinspection"]] `

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
/** @noinspection PhpAssignmentInConditionInspection */
while ($something = myFunction($foo) {
  //code 
}

I'd expect the annotation to get removed.

while ($something = myFunction($foo)) {
  //code 
}

**Comment by SpacePossum** [comment]
Hi @MarcusFulbright and thanks for reporting.

From the sample and config you provided I created a unit test to prove the bug and proposed a fix here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3574
