### ISSUE TITLE
Laravel Code Style

### ISSUE THREAD

**Issue by lloricode** [FriendsOfPHP/PHP-CS-Fixer#3571]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=>PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=>PHP CS Fixer 2.10.3 Bowling Bear by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> i used `composer format`
then `composer.json` contains 
```
"format": [
            "./vendor/bin/php-cs-fixer fix app/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix config/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix database/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix resources/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix routes/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix tests/  --show-progress=estimating"
         ]
```

Hi, is there any way to format code like `laravel` or [spatie/guidelines.spatie.be ](https://github.com/spatie/guidelines.spatie.be/blob/master/content/code-style/laravel-php.md)?

with only one parameter? like `--preset=laravel`

Thanks best regards, :)

**Comment by keradus** [comment]
1. no, there is no laravel ruleset and there won't be one - laraver doesn't want it. See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2985
2. no, there is no and there won't be any ruleset for companies in main repo, company shall create their ruleset in their repo that they control.
