### ISSUE TITLE
[RFC] Dedupe imports in a file

### ISSUE THREAD

**Issue by fmata** [FriendsOfPHP/PHP-CS-Fixer#3580]
I use the fixer "ordered_imports" and after resolving a conflict, I was expecting that duplicated imports be dedupe but it is not.

Will you accept a new fixer "dedupe_imports" which only removes duplicated imports ?

**Comment by keradus** [comment]
Actually, we would not be able to pick up the file that easily.
depends which Tokenizer we would use... if the real `php -l $file`, then tokenizer will say file is invalid (duplicated import), and we don't touch invalid files

**Comment by SpacePossum** [comment]
was duplicated here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5790 ,
closing here although this is the older issue as the other one has the main discussion going, thanks for proposing this idea :+1:
