### ISSUE TITLE
DoctrineAnnotationIndentationFixer - Line indented while it shouldn't

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#3581]
Ref: https://github.com/api-platform/core/pull/1753#discussion_r172880047.

Basically, the change bellow should not happen:

```diff
 /**
  * @Foo(foo={
  *     "bar": 1,
- * }, baz={
+ *     }, baz={
  *     "qux": 2,
  * })
 */
```

**Comment by ntzm** [comment]
Just doing some investigation into this, only seems to be broken when followed by a class or a method definition, i.e.

```php
/**
 * @Foo(foo={
 *     "bar": 1,
 * }, baz={
 *     "qux": 2,
 * })
 */           
class Foo {}
```
