### ISSUE TITLE
[OrderedImportsFixer] Ability to add blank line between groups

### ISSUE THREAD

**Issue by teohhanhui** [FriendsOfPHP/PHP-CS-Fixer#3582]
`OrderedImportsFixer` should have a `blankLineBetweenGroups` config option, which when used together with
```php
'importsOrder' => ['class', 'function', 'const']
```
would allow adherence to the [draft PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md).

[Example taken from the draft PSR](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements):
```php
use Vendor\Package\{ClassA as A, ClassB, ClassC as C};
use Vendor\Package\SomeNamespace\ClassD as D;
use Vendor\Package\AnotherNamespace\ClassE as E;

use function Vendor\Package\{functionA, functionB, functionC};
use function Another\Vendor\functionD;

use const Vendor\Package\{CONSTANT_A, CONSTANT_B, CONSTANT_C};
use const Another\Vendor\CONSTANT_D;
```

**Comment by GrahamCampbell** [comment]
What's the status here?

**Comment by VincentLanglet** [comment]
@keradus This issue can be closed, it was solved by https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/whitespace/blank_line_between_import_groups.rst
