### ISSUE TITLE
Add different sort algorithm for "uses" - also order by length THEN alpha

### ISSUE THREAD

**Issue by garygreen** [FriendsOfPHP/PHP-CS-Fixer#3591]
When using the `ordered_imports` option, you can only specify one `sortAlgorithm`, e.g. length:

```php
'ordered_imports' => [
    'sortAlgorithm' => 'length',
],
```

This results in the following:

![image](https://user-images.githubusercontent.com/1702638/37219748-42ebe7fc-23bc-11e8-98be-add7ce28ff96.png)

Which is correct ~~however it also sorts the use statements inside the class.~~

However it would be nice if you could specify a different sort order for the "use" statements inside the class - I would like them to be alpha sorted. Ideally there should also be two sort options so it sorts by length THEN alpha.

Maybe something like:

```php
'ordered_imports' => [
    'sortAlgorithm' => ['length', 'alpha'],
],
'ordered_use' => [
    'sortAlgorithm' => 'alpha',
]
```

**Comment by SpacePossum** [comment]
Hi and thanks for opening this issue :)

When you state;

>Which is correct however it also sorts the use statements inside the class.

do you mean the `ordered_imports` is also sorting your Trait uses/imports? It shouldn't touch those..

**Comment by garygreen** [comment]
Oh yes my bad, it's not touching those I was under the impression it was. Maybe that's an idea for another option though? To sort the use ones...

**Comment by SpacePossum** [comment]
Thanks for clearing it up, all good :+1: 
I'm not sure but I think sorting the traits use/imports in different order might cause the code to be act different with respect to conflict handling of methods having the same name. I've to check though ;)

**Comment by ibrunotome** [comment]
Using enums in php 8.1, it tries to sort traits with outside imports too.

<img width="564" alt="Screen Shot 2021-12-16 at 11 49 16" src="https://user-images.githubusercontent.com/4256471/146393691-b9fdd0d1-c75e-46fa-957d-cbed46411733.png">

**Comment by zaherg** [comment]
you can use `ordered_class_elements` for this, sadly the only thins supported is `alpha` and `none` more info https://cs.symfony.com/doc/rules/class_notation/ordered_class_elements.html

**Comment by SpacePossum** [comment]
You can use https://cs.symfony.com/doc/rules/class_notation/ordered_traits to order the import as `alpha`.

So there are a few fixers to check:
- https://cs.symfony.com/doc/rules/class_notation/ordered_traits  to order trait imports (inside a class/trait)
- https://cs.symfony.com/doc/rules/class_notation/ordered_class_elements.html to define where these trait imports should be in your class/trait
- order_imports - this is about namespaced imports , so not about trait imports in a class/trait

I'm going to close this ticket now as it is unclear what is left to do/asked, feel free to make a new issue with a request if something is still lacking.
