### ISSUE TITLE
Can't Follow Contribution Guide as Tests Fail On Checkout

### ISSUE THREAD

**Issue by ktomk** [FriendsOfPHP/PHP-CS-Fixer#3608]
When following https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/CONTRIBUTING.md and checking out the branch which is eligible to make changes to (that is 2.2 I think), invoking Phpunit:
~~~
$ composer install
# ...
$ vendor/bin/phpunit
~~~

fails with tests.

I'm running PHP 7.2. something. Which PHP version do I need to configure for Composer so that the test-suite runs?

**Comment by ktomk** [comment]
Trying to pin-point the culprit, but no luck so far. Thought it was xdebug, but w/o xdebug get a different error then (first was a test failure not taking the you're using xdebug warning message into account):

~~~
php -n -dextension=ctype -dextension=json -dextension=tokenizer -dextension=dom -dextension=mbstring  vendor/bin/phpunit --stop-on-failure 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1
Configuration: /home/tom/PhpstormProjects/PHP-CS-Fixer/phpunit.xml.dist

Testing 
.............................................................   61 / 9683 (  0%)
# ...
....................................................S........ 5246 / 9683 ( 54%)
...............................................F

Time: 5.88 seconds, Memory: 118.00MB

There was 1 failure:

1) PhpCsFixer\Tests\Fixer\Comment\HeaderCommentFixerTest::testDoNotTouch with data set #5 ('<?= 1?><?php')
Failed asserting that 'PHP Parse error: syntax error, unexpected end of file on line 1.

Source:
<?= 1?><?php' is null.

/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Test/AbstractFixerTestCase.php:164
/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Fixer/Comment/HeaderCommentFixerTest.php:508

--

There were 31 incomplete tests:
#...
~~~

**Comment by SpacePossum** [comment]
Hi and thanks for reporting :)

Can you try applying this diff to see if this is the cause/fix ?

```diff
diff --git a/tests/Fixer/Comment/HeaderCommentFixerTest.php b/tests/Fixer/Comment/HeaderCommentFixerTest.php
index 1c63733..d2c62a2 100644
--- a/tests/Fixer/Comment/HeaderCommentFixerTest.php
+++ b/tests/Fixer/Comment/HeaderCommentFixerTest.php
@@ -512,8 +512,8 @@ public function provideDoNotTouchCases()
             ["<?php\nphpinfo();\n?><hr/>"],
             ["  <?php\n"],
             ['<?= 1?>'],
-            ['<?= 1?><?php'],
-            ["<?= 1?>\n<?php"],
+            ["<?= 1?><?php\n"],
+            ["<?= 1?>\n<?php\n"],
         ];
     }

```

**Comment by ktomk** [comment]
@SpacePossum: I did, and I'm one further ;) :

~~~
There was 1 failure:

1) PhpCsFixer\Tests\Fixer\Semicolon\NoEmptyStatementFixerTest::testWithShortOpenTag with data set #1 ('<?= ', '<?= ;')
Failed asserting that 'PHP Parse error: syntax error, unexpected ';' on line 1.

Source:
<?= ;' is null.

/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Test/AbstractFixerTestCase.php:130
/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Fixer/Semicolon/NoEmptyStatementFixerTest.php:533
~~~

**Comment by SpacePossum** [comment]
That cases seems to be invalid for near all PHP versions and for the versions that support it it does not mean what is being tested here (also we don't support this old PHP version)
(https://3v4l.org/1Krdq)
please remove that invalid test case :)

**Comment by ktomk** [comment]
@SpacePossum: Zapped, and then we go again:

~~~
There was 1 failure:

1) PhpCsFixer\Tests\Fixer\Whitespace\NoWhitespaceInBlankLineFixerTest::testFix with data set #0 ('<?php')
Failed asserting that 'PHP Parse error: syntax error, unexpected end of file on line 1.

Source:
<?php' is null.

/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Test/AbstractFixerTestCase.php:164
/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Fixer/Whitespace/NoWhitespaceInBlankLineFixerTest.php:35
~~~

If I remove that errorneous case, I come to this one which looks somewhat more special:

~~~
There was 1 failure:

1) PhpCsFixer\Tests\Smoke\CiIntegrationTest::testIntegration with data set #0 ('random-changes', array('touch dir\ a/file.php', 'rm -r dir\ c', 'echo "" >> dir\ b/file\ b.php', 'echo "echo 1;" >> dir\ b/file\ b.php', 'git add .', 'git commit -m "Random changes" -q'), array('
dir a/file.php', 'dir b/file b.php'), array('4', '--path-mode=intersection -- d... b.php', '--path-mode=intersection', '--', 'dir a/file.php', 'dir b/file b.php', ''), 'S.')
Failed asserting that 'You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
Loaded config default from ".php_cs.dist".
.S
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
' matches PCRE pattern "/^(PHP needs to be a minimum version of PHP 5\.3\.6 and maximum version of PHP 7\.2\.\*\.
Ignoring environment requirements because `PHP_CS_FIXER_IGNORE_ENV` is set\. Execution may be unstable\.
)?(You are running PHP CS Fixer with xdebug enabled\. This has a major impact on runtime performance\.
If you need help while solving warnings, ask at https\:\/\/gitter\.im\/PHP\-CS\-Fixer, we will help you\!
)?Loaded config default from "\.php_cs\.dist"\.
S\.
Legend\: \?\-unknown, I\-invalid file syntax, file ignored, S\-Skipped, \.\-no changes, F\-fixed, E\-error$/".

/home/tom/PhpstormProjects/PHP-CS-Fixer/tests/Smoke/CiIntegrationTest.php:150
~~~

Is that perhaps not the intended suite for developing but more for the CI server? Should I perhaps use a specific test-suite?

And for the previous failed test, should I remove the first data-point of that data-provider? If I remove it, the rest works.

**Comment by SpacePossum** [comment]
Thanks for all the testing! I think `"<?php"` is best to be updated to `"<?php\n"` if that passes.

The `CiIntegrationTest` should run on any setup (as all test should or be skipped automatically at run time), however I'm not very familiar with its content/working of this test. Maybe @keradus spots a hint in the failing message?

**Comment by ktomk** [comment]
@SpacePossum: The `"<?php\n"` is already in there, so I'll just remove the one that makes it fail. I'll double check the other test again if I can see something.

**Comment by ktomk** [comment]
Difference is in the `expectedResult3Files` parameter. Expected is `S.` and my output is `.S`. The test is checking for changes in two files. Maybe allow both `S.` and `.S`?

**Comment by kubawerlos** [comment]
@ktomk I have the same `CiIntegrationTest` failing for the same reason, described [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3171) - still valid for PHP 7.2 and still only on one PC.

**Comment by keradus** [comment]
@SpacePossum , is there anything left here after merge of #3617 ?

**Comment by SpacePossum** [comment]
I think what is left is described here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3171 in more detail.
Thanks @ktomk for raising these issues here and fixing a bunch of them in the related PR!
Please let me know if we missed anything.

**Comment by ktomk** [comment]
Looks fine (the merge commit message is incorrect though). The week was pretty busy so is the WE, however I could file an updated PR for the fourth patch, my local build gets full green after #3667.
