### ISSUE TITLE
PhpdocToCommentFixer and third party annotations

### ISSUE THREAD

**Issue by ostrolucky** [FriendsOfPHP/PHP-CS-Fixer#3611]
Some tools like PHPMD and Psalm allow to suppress warnings via annotations.

```php
// phpmd
/** @SuppressWarnings(PHPMD) */

// psalm
/** @psalm-suppress PossiblyFalseArgument */
```

`phpdoc_to_comment` changes those to normal comments and afterwards `single_line_comments_style` changes those as well, making 3rd party tools no longer recognizing these annotations. 

What are the options to solve this?

**Comment by SpacePossum** [comment]
I would recommend switching off the `phpdoc_to_comment` fixer/rule, there are multiple issues with it and not enough people/time to resolve those all.

**Comment by ostrolucky** [comment]
Will do. But if it were fixed, is there a suggestion how? Maybe configurable regex for content inside `/** */`? Something else?

And what are the other issues? I don't see them in this issue tracker

**Comment by kubawerlos** [comment]
@ostrolucky can you give some example when PHPMD comments are removed in your case? Examples from https://phpmd.org/documentation/suppress-warnings.html are not touched by `phpdoc_to_comment` fixer.

**Comment by SpacePossum** [comment]
```php
<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$connections = require_once __DIR__.'/conf.php';

/** @SuppressWarnings(PHPMD) */
foreach ($connections as $connection) {
    foo($connection);
}
```

**Comment by kubawerlos** [comment]
Well, in such case I wouldn't say it's an issue with `phpdoc_to_comment`, because it does exactly what it suppose to and has in the description: "Docblocks should only be used on structural elements."

It's rather the issue with using it - as personally I call all kind of suppressing warnings/errors/code coverage in the code a "cheating" and encourage to remove it/update rules - if it's really necessary to have it there I guess the fixer has to be disabled.

**Comment by ostrolucky** [comment]
Seems you are right. Those annotations don't specify structural elements. 

For others who occur this problem, in some cases there is an easy fix though:

Instead of doing
```php
/** @psalm-suppress PossiblyFalseArgument */
$foo = str_replace('bar', 'baz', getenv('FOO'));
```

one can do
```php
/** @psalm-suppress PossiblyFalseArgument str_replace */
$foo = str_replace('bar', 'baz', getenv('FOO'));
```

Second one conforms to phpDocumentor spec, because function is structural element and phpdoc_to_comment fixer leaves such block alone as well.
