### ISSUE TITLE
Add ShellCheck to CI

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3613]
[ShellCheck](https://www.shellcheck.net/) is a great static analyzer for shell scripts.

I propose to add it to CI.

**Comment by EvgenyOrekhov** [comment]
I am willing to submit a PR after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3548 is merged.

**Comment by julienfalque** [comment]
I don't think this *must* wait for #3548 though, it's even better to do this first IMO :)
