### ISSUE TITLE
no_unused_imports won't pick up unused imports

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfPHP/PHP-CS-Fixer#3620]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.15-0ubuntu0.17.10.1 (cli) (built: Mar 14 2018 22:30:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.15-0ubuntu0.17.10.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.10.4 Bowling Bear by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
```
vendor/bin/php-cs-fixer fix src --dry-run --verbose --diff
```

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'ordered_imports' => true,
        'no_unused_imports' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude(['app', 'bin', 'var', 'vendor', 'web'])
            ->in(__DIR__)
    );

```

I deliberately add an unused import to a class but fixer won't complain about it. `'no_unused_imports' => true,` doesn't seem to be working. `'ordered_imports' => true,` is fine.

**Comment by julienfalque** [comment]
Does the name of the unused imported element also appear somewhere in the file (even as something unrelated, e.g. a word in a comment)?

**Comment by BentCoder** [comment]
No. It is only in import section. This is something new, I never had this issue in my previous projects.

**Comment by julienfalque** [comment]
Could you provide a minimal example that reproduces the issue please?

**Comment by BentCoder** [comment]
```
<?php
declare(strict_types=1);

namespace AppBundle\Controller;

use AppBundle\Entity\Hello;
use GuzzleHttp\Client;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

class MyController
{
    public function createAction(Request $request)
    {
        return new Response($request->getContent());
    }
}
```

As you can see above, I am importing `Hello` and `Client` classes but not using them at all. Fixer won't complain aboutit.

**Comment by julienfalque** [comment]
This is the diff I get when trying to fix this file with your setup:
```diff
 <?php
+
 declare(strict_types=1);
 
 namespace AppBundle\Controller;
 
-use AppBundle\Entity\Hello;
-use GuzzleHttp\Client;
+use Symfony\Component\HttpFoundation\Request;
 use Symfony\Component\HttpFoundation\Response;
-use Symfony\Component\HttpFoundation\Request;
@@ @@
 }
+
```
Is the file actually processed? Could you try running the tool with the path of the file in the arguments?

**Comment by SpacePossum** [comment]
@julienfalque unrelated maybe, but that `Request` import is needed for the argument hint of the method isn't it?

**Comment by BentCoder** [comment]
```vendor/bin/php-cs-fixer fix src/AppBundle/Controller/MyController.php --using-cache=no --dry-run --verbose --diff

Loaded config default.
.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Checked all files in 0.316 seconds, 10.000 MB memory used
```

**Comment by BentCoder** [comment]
@juliendufresne Any solution to this problem?

**Comment by SpacePossum** [comment]
@BentCoder the output

```
Loaded config default.
.
```

means:

```
.-no changes
```

it seems the file is not processed by the tool at all. Best to check how the finder in your config has been done to see why it excludes the file you try to fix

**Comment by SwiTool** [comment]
@bentcoder or @SpacePossum you should reopen, as I could replicate the issue.

```php
<?php
use Illuminate\Support\Facades\Artisan;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [];
}
```

`Artisan` is a word used in the comment, and `no_unused_imports` option does not clear the `use` statement.

If you replace `use Illuminate\Support\Facades\Artisan;` by `use Exception;` the option will work as expected.

```
> php-cs-fixer --version
PHP CS Fixer 3.11.0 (7dcdea3) Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.10
```

**Comment by julienfalque** [comment]
Unused imports not being removed because they appear in comments is a known issue, see #2814.
