### ISSUE TITLE
Incorrect priorities for array_indentation and method_chaining_indentation

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3625]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.1.14

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.11.0

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
	->setIndent("\t")
	->setUsingCache(false)
	->setRules([
		'method_chaining_indentation' => true,
		'array_indentation' => true,
	])
	->setFinder(
		PhpCsFixer\Finder::create()->in(__DIR__)
	)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

Foo::bar([
		'baz',
	])
	->call();
```

 * with unexpected changes applied when running PHP CS Fixer:

First run:
```diff
 Foo::bar([
-		'baz',
-	])
+	'baz',
+])
 	->call();
```

Second run:
```diff
 <?php

 Foo::bar([
 	'baz',
 ])
-	->call();
+->call();
```

**Comment by keradus** [comment]
thanks for report. closing due to merge of fix #3626
