### ISSUE TITLE
CommentToPhpdocFixer - Allow to ignore some tags

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#3628]
I think it would be nice if `comment_to_phpdoc` could be configured to ignore a set of tags. My use case is the following:
```php
// @todo do something later
$foo = 'foo';
```
It is common to use regular comments for `@todo` tags and I would like those to be left untouched.

**Comment by kubawerlos** [comment]
Right now it's under heavy refactoring as it was released too early: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3614

**Comment by SpacePossum** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3614 has been merged so I think this can be picked up by someone or do you plan on more related-changes for this fixer @kubawerlos ?

**Comment by kubawerlos** [comment]
After the merge the example is not valid anymore - only comments on structural elements will be candidates for PHPDoc. @julienfalque @SpacePossum do you still think allowing to ignore some tags would be useful?

**Comment by SpacePossum** [comment]
if `//@todo xyx` and`// @FIXME abc` are no longer changed to PHPDoc's I think this can be closed indeed, I leave the call to @julienfalque (as reporter of this issue)

**Comment by julienfalque** [comment]
Indeed the example isn't valid anymore but `// @TODO` would still be changed to a DocComment if placed before e.g. a class property. I would leave this feature request open.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4385 thanks @kubawerlos
