### ISSUE TITLE
ArrayIndentationFixer unexpected changes with HTML attributes

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3631]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.11.0

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('vendor');

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRules([
        'array_indentation' => true,
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<div>
    <a
        class="link"
        href="<?= Url::to([
            '/site/page',
            'id' => 123,
        ]); ?>"
    >
        Link text
    </a>
</div>
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<div>
    <a
        class="link"
        href="<?= Url::to([
    '/site/page',
    'id' => 123,
]); ?>"
    >
        Link text
    </a>
</div>
```

 * with the changes you expected instead:
Expected no changes

**Comment by SpacePossum** [comment]
TBH the changes look good to me, the indent is one level. You could reason one indent level more than the call (here the line `Url::to([`), however that is also not what you expect. What, in your opinion, should be a good rule/logic for the fixer?

**Comment by EvgenyOrekhov** [comment]
@SpacePossum ArrayIndentationFixer already understands and respects indentation of HTML tags.

For example, it will not fix the following code:

```php
<div>
    <?= Url::to([
        '/site/page',
        'id' => 123,
    ]); ?>"
</div>
```

Which is good.

But I want it to also understand a different kind of indentation level - indentation of attributes in multiline opening tags:

```html
| Level 0
<div>
    | Level 1
    <a
        | Level 2
        class="some very long list of classes"
    >
        | Level 2
        <img
            | Level 3
            src="/some/very/long/path/to/image.jpg"
        >
    </a>
</div>
```
