### ISSUE TITLE
Document possible values for subset options

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#3642]
When using `ordered_class_elements` I would like to specify the order of static methods separate from non-static methods. For instance, I would like to be able to have public static methods before the constructor.

**Comment by keradus** [comment]
sounds like a good idea @sebastianbergmann , are you willing to give it a try and raise a PR ? :)

**Comment by EvgenyOrekhov** [comment]
It is already supported. Here is the list of all possible types of elements you can use in your config:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/90efa83e60f00d848e56c6484f6a4eb8b03c4684/src/Fixer/ClassNotation/OrderedClassElementsFixer.php#L40-L63

As you can see, there are elements with the `static` suffix.

Example config:

```php
'ordered_class_elements' => [
    'order' => [
        'use_trait',
        'constant_public',
        'constant_protected',
        'constant_private',
        'property_public_static',
        'property_protected_static',
        'property_private_static',
        'property_public',
        'property_protected',
        'property_private',
        'construct',
        'destruct',
        'magic',
        'phpunit',
        'method_public_static',
        'method_protected_static',
        'method_private_static',
        'method_public',
        'method_protected',
        'method_private',
    ],
],
```

**Comment by sebastianbergmann** [comment]
Ah, great. Thanks!

This seems to be missing from the documentation of `ordered_class_elements` in https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/README.rst.

**Comment by keradus** [comment]
I double checked it. Issue is that readme presents default value, but not all possible values... :(

**Comment by julienfalque** [comment]
See #3669.
