### ISSUE TITLE
tests/Smoke/CiIntegrationTest.php doesn't work without Bash

### ISSUE THREAD

**Issue by EvgenyOrekhov** [FriendsOfPHP/PHP-CS-Fixer#3650]
After fixing #3544 it is still not possible to run PHP-CS-Fixer's unit tests in an environment that doesn't have Bash, because tests/Smoke/CiIntegrationTest.php fails with

> env: can't execute 'bash': No such file or directory

`BashScriptExecutor` here should be replaced with `ShellScriptExecutor` that uses `sh` instead of `bash`:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/90efa83e60f00d848e56c6484f6a4eb8b03c4684/tests/Smoke/CiIntegrationTest.php#L15

**Comment by keradus** [comment]
ref #3652
