### ISSUE TITLE
Remove return `null` type hint from PHPDoc if not possible

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3651]
When a method signature defines a return type, than that type must be the only one in the PHPDoc return annotation (if any of course)

For example:
```php
/**
 * @return Foo|null
 */
function A(): Foo
{
}
```

`null` must be removed by the fixer

**Comment by julienfalque** [comment]
IMO this should be covered by a more general fixer that removes useless PHPDocs. In your example, beside being wrong, the annotation does not add any information so it can be removed altogether.

**Comment by keradus** [comment]
yep, I would expect to drop whole annotation as well

**Comment by julienfalque** [comment]
Is this still relevant? Static tools analysis already detect such mistake.

**Comment by SpacePossum** [comment]
this can go both ways indeed: either doc is wrong or code is wrong, so needs to be reviewed by person so no auto fixing, closing :+1:
