### ISSUE TITLE
not fixed due to linting error

### ISSUE THREAD

**Issue by DarrenReyes** [FriendsOfPHP/PHP-CS-Fixer#3685]
Hi,

I'm new to this so apologies in advance if I post something that is incorrect. When I try to do a fix, I get this file was not fixed due to errors reported during linting after it try to fix the file. I isolated the problem to this:

```php
public static function my_function($var, $type = 'title')
{
	if (empty($var)) return false;
	if (empty($type)) $type == 'title';
	// more codes here
	return $var;
}
```
It's part of a class. After removing that piece of code above, I no longer see the error and the file has been modified successfully. The function does not produce a PHP error.

PHP Version: 7.1.15
PHP CS Fixer Version: 2.11.1

Normal php-cs-fixer fix from the command line.

**Comment by DarrenReyes** [comment]
sorry. found it.

**Comment by keradus** [comment]
Hi @DarrenReyes 
what was the issue?
also, did you had config file ?
