### ISSUE TITLE
Unexpected ordered_class_elements behaviour

### ISSUE THREAD

**Issue by erickskrauch** [FriendsOfPHP/PHP-CS-Fixer#3689]
#### The PHP version you are using (`$ php -v`):
=> `PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `PHP CS Fixer 2.11.2-DEV` ([My fork, that implements](https://github.com/erickskrauch/PHP-CS-Fixer/tree/c55f014955c6a5257aa0beb4a7d2384abdeb672a) https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3688)

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer --diff --dry-run -v fix`

#### The configuration file you are using, if any:
```php
<?php
$finder = Symfony\Component\Finder\Finder::create()
    ->in(__DIR__)
    ->exclude('data')
    ->exclude('docker')
    ->exclude('frontend')
    ->exclude('vendor')
    ->notPath('common/emails/views')
    ->notPath('/.*\/runtime/')
    ->notPath('autocompletion.php')
    ->notPath('tests/codeception/_output')
    ->notPath('/tests\/codeception\/.*\/_output/')
    ->notPath('/tests\/codeception\/.*\/_support\/_generated/')
    ->name('*.php')
    ->name('yii')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'braces' => [
            'allow_single_line_closure' => false,
            'position_after_functions_and_oop_constructs' => 'same',
        ],
        'cast_spaces' => [
            'space' => 'none',
        ],
        'linebreak_after_opening_tag' => true,
        'no_whitespace_in_blank_line' => true,
        'non_printable_character' => [
            'use_escape_sequences_in_strings' => true,
        ],
        'ordered_imports' => true,
        'single_quote' => true,
        'whitespace_after_comma_in_array' => true,
        'trailing_comma_in_multiline_array' => true,
        'class_attributes_separation' => [
            'elements' => ['method', 'property'],
        ],
        'function_declaration' => [
            'closure_function_spacing' => 'none',
        ],
        'function_to_constant' => true,
        'return_type_declaration' => [
            'space_before' => 'none',
        ],
        'ordered_class_elements' => true,
        'concat_space' => [
            'spacing' => 'one',
        ],
        'blank_line_around_class_body' => true,
    ])
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
namespace tests\codeception\common\unit;

use Mockery;

class TestCase extends \Codeception\Test\Unit {

    /**
     * @var \tests\codeception\common\UnitTester
     */
    protected $tester;

    /**
     * @url http://codeception.com/docs/modules/Yii2#fixtures
     *
     * @return array
     */
    public function _fixtures() {
        return [];
    }

    protected function tearDown() {
        parent::tearDown();
        Mockery::close();
    }

}
```

 * with unexpected changes applied when running PHP CS Fixer:
```diff
   1) tests/codeception/common/unit/TestCase.php (ordered_class_elements, class_attributes_separation, class_definition, braces, blank_line_around_class_body)
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 
+    protected function tearDown() {
+        parent::tearDown();
+        Mockery::close();
+    }
+
@@ @@
         return [];
-    }
-
-    protected function tearDown() {
-        parent::tearDown();
-        Mockery::close();
     }
 
 }
 

      ----------- end diff -----------
```

 * with the changes you expected instead:
```
No changes expected
```

---------------------

By some unknown reasons `ordered_class_elements` fixer wants to move `tearDown` method before `public` method. But in any other files it's works as expected `public` => `protected` => `private`.

I did an investigation and found this code lines:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/a9bed70399bb0dda32d2a666f5295b2c3041861e/src/Fixer/ClassNotation/OrderedClassElementsFixer.php#L384-L393

I tried to find any documentation about such behavior: moving up phpunit methods, but didn't found anything. Is this is expected behavior? And if this is expected, maybe it should be configurable?

**Comment by ntzm** [comment]
This is expected and configurable! The default configuration of `ordered_class_elements` places PHPUnit methods above all other methods, you can configure it by moving the `'phpunit'` value around in the config.

**Comment by erickskrauch** [comment]
@ntzm oh, yes, indeed. Sorry for disturb and thank you!

**Comment by ntzm** [comment]
No worries! :)
