### ISSUE TITLE
method_argument_space with multiline arguments

### ISSUE THREAD

**Issue by nobuf** [FriendsOfPHP/PHP-CS-Fixer#3712]
#### The PHP version you are using (`$ php -v`):
=> 7.2.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.11.1

#### The command you use to run PHP CS Fixer:

```php
<?php
function a($a, $b,
           $c, $d) {
}
```
```shell
php-cs-fixer fix sandbox.php --rules=@PSR2 --dry-run --diff
```
```diff
--- Original
+++ New
@@ @@
 <?php

-function a($a, $b,
-           $c, $d) {
+function a(
+    $a,
+    $b,
+           $c,
+    $d
+) {
 }
```

Extra spaces before `$c` could be removed. Perhaps this isn't `MethodArgumentSpaceFixer`'s responsibility, or it could have a new option `ensure_aligned` if `ensure_fully_multiline` is `true`.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

Here's a test case with expected output:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/master...nobuf:MethodArgumentSpaceFixer-with-multiline-args

**Comment by julienfalque** [comment]
Indeed, this is not the responsibility of `method_argument_space` to fix indentation in such case. We don't have any fixer to do that currently but it would be nice to have one :)

**Comment by erickskrauch** [comment]
[Here is](https://github.com/PedroTroller/PhpCSFixer-Custom-Fixers/blob/master/src/PedroTroller/CS/Fixer/CodingStyle/LineBreakBetweenMethodArgumentsFixer.php) someone tried to implement [something similar](https://github.com/PedroTroller/PhpCSFixer-Custom-Fixers#pedrotrollerline_break_between_method_arguments). Maybe it'll be useful.

**Comment by nobuf** [comment]
Thanks, erickskrauch!

I think the new fixer would be similar to `array_indentation`:

- `multiline_method_argument_indentation`: When a method has a multiline argument list, each subsequent line must be indented once.

The description of `method_argument_space` actually says "each subsequent line is indented once" as PSR-2 does, so I still think it could be their responsibility. What do you think?

**Comment by Billz95** [comment]
By making the following deletion to the `MethodArgumentSpaceFixer.php` file, the problem mentioned in this issue is resolved. 
However, I'm not sure whether this approach would cause any side effect. Can anyone shed some light on this?
```
--- a/src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
+++ b/src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php
@@ -377,7 +377,7 @@ private function ensureFunctionFullyMultiline(Tokens $tokens, $startFunctionInde
      */
     private function fixNewline(Tokens $tokens, $index, $indentation, $override = true)
     {
-        if ($this->isNewline($tokens[$index + 1]) || $tokens[$index + 1]->isComment()) {
+        if ($tokens[$index + 1]->isComment()) {
             return;
         }
```
