### ISSUE TITLE
Invalid group use decalration with new line before brace

### ISSUE THREAD

**Issue by A-VD** [FriendsOfPHP/PHP-CS-Fixer#3714]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### My PHP version 
=> 7.1

#### PHP CS Fixer version
=> PHP CS Fixer 2.11.1 Grey Devil by Fabien Potencier and Dariusz Ruminski

#### The configuration php-cs-fixer
 only rules @PSR2 @Symfony

#### Case
 * before running PHP CS Fixer (no changes):
```php
use Symfony\Component\DependencyInjection\
{
    ContainerAwareInterface, ContainerInterface, ContainerAwareTrait
};
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
use Symfony\Component\DependencyInjection\ ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ ContainerInterface;
use Symfony\Component\DependencyInjection\ ContainerAwareTrait;
```

 * with the changes you expected instead:
```php
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;
```

**Comment by julienfalque** [comment]
Hi, thanks for the report! This should be fixed with #3715.
