### ISSUE TITLE
Fixer for reordering @param annotations into the one used by method signature

### ISSUE THREAD

**Issue by ostrolucky** [FriendsOfPHP/PHP-CS-Fixer#3716]
I noticed there is no issue for this created, little discussion I found about this is scattered through comments in separate issues, like https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1602#issuecomment-280717077 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2385#issuecomment-266505538

It deserves issue topic on its own

This fixer should do
```diff
 /**
+ * @param mixed $a
  * @param mixed $b
- * @param mixed $a
  */ 
function ($a, $b) {}
```

Just for reference, this is already implemented in [Phan](https://github.com/phan/phan), in rule `PhanCommentParamOutOfOrder`

**Comment by ntzm** [comment]
Duplicate of #3161?

**Comment by ostrolucky** [comment]
indeed
