### ISSUE TITLE
Multiple spaces after namespace keyword

### ISSUE THREAD

**Issue by iluuu1994** [FriendsOfPHP/PHP-CS-Fixer#3728]
I noticed that PHP-CS-Fixer does not fix multiple spaces after the `namespace` keyword.

#### The PHP version you are using (`$ php -v`):

> PHP 7.0.30 (cli) (built: Apr 26 2018 11:49:41) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

> PHP CS Fixer 2.11.1 Grey Devil by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:

> vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix

#### The configuration file you are using, if any:

Using ruleset `@PSR1`, `@PSR2` and `@Symfony`, otherwise pretty standard.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

 * before running PHP CS Fixer (no changes):
```php
namespace  My\Name\Space;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
namespace  My\Name\Space;
```

 * with the changes you expected instead:
```php
namespace My\Name\Space;
```

**Comment by SpacePossum** [comment]
Thanks for reporting @iluuu1994 !
Currently we've no rule for this, maybe we could add this to an existing rule, do you've an idea for a good fit to add this?

**Comment by iluuu1994** [comment]
@SpacePossum Sure thing, I'll see if I can write or extend a fixer. 👍 I noticed the same thing for return statements.

**Comment by SpacePossum** [comment]
It is tempting, I recall doing something like that. However there are a few cases left to consider ;)

For example the `binary_operator_spaces` can be configured to do this:

```php
$a  = 1;
$ab = 1;  
```

than there are cases like;
```php
$abc = 1; // aligned...
$b = 2;   // ... comment
```

But after all, having a `GenericSingleSpaceAfterX` - fixer with config options like `return`, `namespace` still sounds _very_ tempting to me... yet I'm not sure there will be enough support for such a fixer here..

**Comment by SpacePossum** [comment]
I would build the fixer the other way around, like;
`SingleSpaceAfterFixer`
than add configuration options like;
`cast` (then we deprecate `cast_spaces`), `namespace`, `visibility`, etc., but not other were we have dedicated rules for like `binary operator` .
Using the white list makes it easier to prevent conflicts and would allow for more refined configuration.
Downside is of course that it takes more time to write the fixer.
As a general rule I would not touch multi line spacing and not spacing before a comment, than we should be on the safe side and still be able to fix a lot :)
WDYT?

**Comment by iluuu1994** [comment]
I tried the `no_multiple_spaces` fixer after all and ran it over the Symfony code base:
https://github.com/iluuu1994/symfony/commit/a574c085ea3869947a3ab1e46fdb7ca8d5ca45c4

This works perfectly for our use case. I know this is not exactly what you had in mind but the suggested fixer would leave many things unfixed in our code base. But obviously this breaks intentionally aligned code such as parameters.

Are you interested in this fixer? It could still be useful to people who strictly want to disallow aligning code like we do.
