### ISSUE TITLE
Feature request: Non abstract phpunit test classes should be final

### ISSUE THREAD

**Issue by BackEndTea** [FriendsOfPHP/PHP-CS-Fixer#3741]
```diff
- class MyTest extends \PHPUnit\Framework\TestCase {}
+ final class MyTest extends \PHPUnit\Framework\TestCase {}
```

It could replace the `testThatTestClassesAreTraitOrAbstractOrFinal` auto-review test.

**Comment by SpacePossum** [comment]
Sounds like a good idea to me.
Just FYI: if you would tag the class as `@internal` you can use the `final_internal_class` rule to do this.
