### ISSUE TITLE
OrderedClassElementsFixer - incorrect location after sorting

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3742]
On 2.2 / PHP 7.2.5-1 

>$ php php-cs-fixer fix tmp/test2.php  --rules=ordered_class_elements 

input 

```php
<?php

class Foo
{
    /**
     * @var int
     */
    private $a;

    /**
     * @var string
     */
    protected $b;
}
```

output

```php
<?php

class Foo
{

    /**
     * @var string
     */
    protected $b;
    /**
     * @var int
     */
    private $a;
}
```

expected

```php
<?php

class Foo
{
    /**
     * @var string
     */
    protected $b;

    /**
     * @var int
     */
    private $a;
}
```

ping @gharlan , not sure if this is an easy fix though

**Comment by gharlan** [comment]
The blank line after class opening should be removed by NoBlankLinesAfterClassOpeningFixer.

And for the missing blank line between properties we maybe should introduce a PropertySeparationFixer (like existing MethodSeparationFixer)?

**Comment by SpacePossum** [comment]
In the end, both the line issues will be fixed by the `class_attributes_separation`-fixer (using the non-default   `property` configuration). However it kind of leaves a dependency, so I'm wondering if the `OrderedClassElementsFixer` could do the "swap" by itself? if it is hard we can close this as a non-issue and advice users to reconfigure with the `class_attributes_separation` of course.

**Comment by gharlan** [comment]
> if it is hard we can close this as a non-issue and advice users to reconfigure with the class_attributes_separation of course.

Yeah, i think it would be hard to solve hier. Imo it is not the responsibility of this fixer.

**Comment by SpacePossum** [comment]
Thanks for getting back on this :)
After reading and thinking it over again I agree on the responsibility argument.
Closing as a won't fix.
