### ISSUE TITLE
Feature request: magic_static option for ordered_class_elements order

### ISSUE THREAD

**Issue by jnvsor** [FriendsOfPHP/PHP-CS-Fixer#3744]
ordered_class_elements is missing a magic_static option

**Comment by gharlan** [comment]
The keys already exist, but they are named `property_public_static` etc.
But the default config doesn't differentiate between static and non-static elements, so it does not use these keys.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/src/Fixer/ClassNotation/OrderedClassElementsFixer.php#L39-L74

Only the `magic_static` is missing.

**Comment by jnvsor** [comment]
Ah, mind if I update the readme to show the static options?

**Comment by SpacePossum** [comment]
```
static_property_public
static_property_protected
static_property_private
static_magic
static_method_public
static_method_protected
static_method_private
```

we have;

```
property_public_static
property_protected_static
property_private_static
...
method_public_static
method_protected_static
method_private_static
```

with the exception of `static_magic` I think you already got the requested options?

**Comment by ntzm** [comment]
Hi @jnvsor, PR #3669 will introduce the documentation of allowed subsets, which will document these options for you

**Comment by SpacePossum** [comment]
closing as 3669 has been merged and I see no action required here, feel free to comment here if I missed anything.
