### ISSUE TITLE
Accept any number of space superior at 2 for indentation

### ISSUE THREAD

**Issue by Paviluf** [FriendsOfPHP/PHP-CS-Fixer#3759]
Hello,

I work on project that have 2 or 4 spaces for indentation and I wonder if it's possible to set up php-cs-fixer to accept any number of space superior at 2 for indentation ?
If yes how ? If no is it possible to add it please ?

Thanks !

**Comment by SpacePossum** [comment]
Hi @Paviluf ,

You can configure the indentation through the configuration you use for the fixer. Therefore you need a configuration file. Details about this file can be found in the [README](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.2.0), for the indentation search for `->setIndent`  to find the relevant details.
Mixing two types of indentation is not something the fixer support, currently you can use 4-spaces or tabs, I'm not sure if 2-spaces is (still) supported.

**Comment by Paviluf** [comment]
Thank you but it's not really practical. It will be great if we can have a setting to detect the indentation and format the code accordingly.

**Comment by SpacePossum** [comment]
Some rules will detect the indentation and try to preserve it or apply it to the code these modify.
The ones that don't detect the indent use the configured indentation.
While this is indeed a limitation that might not be very practical in your use case it is done for a reason.
The tool is designed to change code into _one_ style that can be defined through configuration, it is not meant to fix to multiple/dynamic styles.
I would advice:
- reconsider using one style in the project
- if not possible; make two configuration files; one for each style for each set of files
- if not practical either I would remove the indentation fixer for the configuration

**Comment by Paviluf** [comment]
To remove the indentation fixer I just need to remove setIndent() from the config ?

**Comment by SpacePossum** [comment]
the rule is called `indentation_type`, either remove it from you config or if it is imported through a set you can disable it later on using `indentation_type => false` in the `->setRules([` part of your configuration file

**Comment by Paviluf** [comment]
OK thank you !

**Comment by keradus** [comment]
Closing as question had been resolved
