### ISSUE TITLE
Allow single line PHP opening/closing tags in BracesFixer

### ISSUE THREAD

**Issue by lukascernydis** [FriendsOfPHP/PHP-CS-Fixer#3787]
Hi,

I would like to propose new feature in BracesFixer.

When working in Yii2 framework, developer may want to mix PHP code with HTML in view files.

Example:
```php
<div>
    <?php if (true === $user->is_active) { ?>
        <i class="fa fa-check text-success"></i>&nbsp;Active
    <?php } else { ?>
        <i class="fa fa-times text-danger">&nbsp;Inactive
    <?php } ?>
</div>
```
Currently the BracesFixer is formatting the code above as:
```php
<div>
    <?php 
    if (true === $user->is_active) { 
        ?>
        <i class="fa fa-check text-success"></i>&nbsp;Active
        <?php 
    } else { 
        ?>
        <i class="fa fa-times text-danger">&nbsp;Inactive
        <?php 
    } 
    ?>
</div>
```
...which is less readable than the original code.

This could be solved by adding another configuration option that would allow opening and closing php tags on same/next line.

**Comment by lukascernydis** [comment]
Hi, me again.

It seems that this issue is already being implemeted by #3781

Sorry for duplicate.

**Comment by SpacePossum** [comment]
Hi @lukascernydis ,
no worries about the duplicate, it is good to hear that more people have the same idea for a change :)
