### ISSUE TITLE
LowercaseStaticReferenceFixer - makes private constant named PARENT lowercase

### ISSUE THREAD

**Issue by holtkamp** [FriendsOfPHP/PHP-CS-Fixer#3807]
#### The PHP version you are using (`$ php -v`):
`7.1.18`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`2.12.0`

#### The command you use to run PHP CS Fixer:
`./vendor/bin/php-cs-fixer fix --verbose`

#### The configuration file you are using, if any:
n/a

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
private const PARENT = 'faa-parent';
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
private const parent = 'faa-parent';
```
This seems to be done by the `lowercase_static_reference` fixer https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3735

 * with the changes you expected instead:
I think no change should be applied

**Comment by SpacePossum** [comment]
Thanks for reporting @holtkamp 
@kubawerlos already put a fix together so expect that one in the release. TBH I'm surprised PHP allows for a `private const` to be called `parent`

**Comment by holtkamp** [comment]
> TBH I'm surprised PHP allows for a private const to be called parent

haha, actually me too! Good the fixer "found this out" for me 😏

**Comment by keradus** [comment]
@holtkamp , PHP 7.0 added possibility to use reserved keywords in some context
