### ISSUE TITLE
NoSuperfluousPhpdocTags - Add option to remove entries only if all superfluous

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#3809]
```diff
 /**
  * @param mixed $arg1
  * @param int   $arg2
  */
 function foo($arg1, $arg2) { }

-/**
- * @param mixed $arg1
- * @param mixed $arg2
- */
 function bar($arg1, $arg2) { }
```

~The PR that will introduce this option should also enable it on the repository as discussed in #3793.~

**Comment by SpacePossum** [comment]
maybe it should only remove the params and not the block itself? leaving that to the 'no empty doc block' rule?

**Comment by julienfalque** [comment]
Sorry the sample is misleading: yep, the fixer would only remove all annotations and leave an empty DocComment (then removed by `no_empty_phpdoc`).

This brings some questions though: what if all `@param`/`@return` annotations are superfluous but the DocComment also contains a summary, a description or e.g. `@throws` annotations? What if it contains annotations that are not PHPDoc like e.g. `@dataProvider` for PHPUnit?

**Comment by k00ni** [comment]
I got weird behavior when using PHP-CS with `@Symfony` enabled: it removed non-superfluous PHPDoc entries too. It started with the recent release of [v2.16.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.16.0).

Can you please provide another example which demonstrates the benefit of the rule? I would like to understand the meaning behind the rule and to see, if i made something wrong.

**Comment by julienfalque** [comment]
The benefit of the rule is to prevent duplicated information regarding function signatures, e.g.:
```php
/** @param int $foo */
function foo(int $foo) {}
```
It should not remove non-superfluous PHPDoc tags though. Are you sure they were removed by the `no_superfluous_phpdoc_tags` rule? If so, could you please open a new issue with more details?

**Comment by k00ni** [comment]
Thank you, for the quick response. 

So by your example:

```php
/** @param int $foo */
function foo(int $foo) {}
```
superfluous means that `int $foo` is already defined with type and name in the function head itself and therefore the information in the comment above is obsolete? OK, got it.

If that is right, the observed behavior with my code is intended and PHP CS Fixer is not faulty.
