### ISSUE TITLE
PhpUnit test method name casing fixer

### ISSUE THREAD

**Issue by Slamdunk** [FriendsOfPHP/PHP-CS-Fixer#3816]
I would like a fixer to go back and forth `camelCase` and `snake_case` for test method names in PhpUnit classes. It should be trivial to implement.

(I hope to work on this soon)

**Comment by julienfalque** [comment]
What about supporting [non breakable spaces](http://mnapoli.fr/using-non-breakable-spaces-in-test-method-names/) as well?

**Comment by Slamdunk** [comment]
I thought about it: I'm against because I find it misleading/confusing, and this project aims to make the code clearer to understand.

**Comment by SpacePossum** [comment]
is this request the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3302 ?

**Comment by Slamdunk** [comment]
Whoops :\
