### ISSUE TITLE
PSR2 (default) ruleset adds trailing whitespace

### ISSUE THREAD

**Issue by sampablokuper** [FriendsOfPHP/PHP-CS-Fixer#3819]
#### The PHP version you are using (`$ php -v`):
`7.0.27-0+deb9u1`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.0 Long Journey by Fabien Potencier and Dariusz Ruminski (a53f39a)`

#### The command you use to run PHP CS Fixer:
`php-cs-fixer fix myfile.php`

#### The configuration file you are using, if any:
N/A

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
class MyClass extends SomeClass {
/*	public function myFunction() {

		$MyItems = [];

		return $MyItems;
	}
*/
}
```
For clarity about how the whitespace starts out, here is the above snippet after passing through `cat -A`:
```<?php$
class MyClass extends SomeClass {$
/*^Ipublic function myFunction() {$
$
^I^I$MyItems = [];$
$
^I^Ireturn $MyItems;$
^I}$
*/$
}$
?>$

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
class MyClass extends SomeClass
{
    /*	public function myFunction() {
    
            $MyItems = [];
    
            return $MyItems;
        }
    */
}
```

In case you can't see the added whitespace in the code sample above, here is what it now looks like after passing through `cat -A`:
```
<?php$
class MyClass extends SomeClass$
{$
    /*^Ipublic function myFunction() {$
    $
            $MyItems = [];$
    $
            return $MyItems;$
        }$
    */$
}$
```

 * with the changes you expected instead:
```php
<?php
class MyClass extends SomeClass
{
    /*	public function myFunction() {

            $MyItems = [];

            return $MyItems;
        }
    */
}
```

I.e. after passing through `cat -A`, the output from PHP-CS-Fixer should instead look like this:
```
<?php$
class MyClass extends SomeClass$
{$
    /*^Ipublic function myFunction() {$
$
            $MyItems = [];$
$
            return $MyItems;$
        }$
    */$
}$
```

**Comment by SpacePossum** [comment]
Hi @sampablokuper and thanks for reporting.

After looking into this issue it seems it the `braces` rule re-indents the comment, which is OK, but also adds indentation to empty lines within that comment which is a bug.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3820
