### ISSUE TITLE
PhpdocAddMissingParamAnnotationFixer - do not handle `&` and `...` as "type hint"

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3821]
#### The PHP version you are using (`$ php -v`):
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:59:13) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.12.0 Long Journey  (might be an issue on lower versions as well)

#### The command you use to run PHP CS Fixer:
>$ php-cs-fixer fix src/foo.php -vvv --rules=phpdoc_add_missing_param_annotation

#### The configuration file you are using, if any:
none

```diff
$ g diff src/foo.php
diff --git a/src/foo.php b/src/foo.php
index 0000000..0000000 100644
--- a/src/foo.php
+++ b/src/foo.php
@@ -14,6 +14,7 @@
 {
     /**
      * @param $cat
+     * @param mixed $domain
      */
     private function foo(&$cat, $domain)
     {
```

I think the fixer should've fixed `$cat` here as well, or none, but not just one. The reference `&` is not a type hint :)

**Comment by keradus** [comment]
can you provide code before fixing, after fixing, and expected one ?

**Comment by SpacePossum** [comment]
before (from the diff)

```
 {
     /**
      * @param $cat
      * @param $domain
      */
     private function foo(&$cat, $domain)
     {
```

after  (from the diff)

```
 {
     /**
      * @param $cat
      * @param mixed $domain
      */
     private function foo(&$cat, $domain)
     {
```

expected  (from the description)

```
 {
     /**
      * @param mixed $cat
      * @param mixed $domain
      */
     private function foo(&$cat, $domain)
     {
```

**Comment by SpacePossum** [comment]
note sure about this one either:
input:
```
<?php
                /**
                 *
                 */
                function foo(...$bar)
                {
                }
```

output

```
<?php
                /**
                 *
                 * @param ... $bar
                 */
                function foo(...$bar)
                {
                }
```

the draft of PSR5 defines `Type` in [appendix A](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types) for `@param`, but doesn't provide much guidance on variable-length arguments or arguments passed by reference modifiers.

**Comment by julienfalque** [comment]
When using the `...` syntax, the `$bar` argument will always be an `array` so I think we should add `@param array $bar`.
