### ISSUE TITLE
Add option to remove all whitespace surrounding binary operators

### ISSUE THREAD

**Issue by ocrampete16** [FriendsOfPHP/PHP-CS-Fixer#3827]
First of all, thank you for all the work you've put into making this a great piece of software!

Right now there is no way to have the CS fixer remove spaces surrounding binary operators. (`1 + 2` -> `1+2`).

Actually, I'm only looking to get rid of them for multiple exception catches. It's part of the style guide of the project I'm currently working on that there should be no spaces between exception type declarations, i.e.

```php
<?php

try {
} catch (FooException|BarException $e) {
}
```

Is this something you'd accept? I'd have time to work on it on Friday, so if you give me the go signal I'll get it done by then.

**Comment by SpacePossum** [comment]
Hi @ocrampete16 ,

Thanks for the kind words, means a lot to hear someone enjoys the result of this great community!  :)

Currently it is indeed impossible to configure the fixer to remove any space around binary operators. Before the `multiple catch` was introduced I didn't see a need for it, but now you brought it forward I kind of do. I would even like the fixer to remove spacing around a `|` for flag type of expressions (`json_encode` comes to mind with something like `JSON_NUMERIC_CHECK|JSON_PRETTY_PRINT`).

For ease of implementation I would suggest to allow a new strategy for the `operators` option on the `binary_operator_spaces`, called something like `no_space`.

Before I or someone else starts working on a PR I would like to hear some more opinions on this topic :)

**Comment by kubawerlos** [comment]
As it would be against [PHP 12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) (yes, it's in review, but we are going this way):

> All binary and ternary (but not unary) operators MUST be preceded and followed by at least one space.

I'm 👎 for this one.

**Comment by SpacePossum** [comment]
closing as https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3833 has been merged
