### ISSUE TITLE
friendsofsymfony/php-cs-fixer-shim?

### ISSUE THREAD

**Issue by mente** [FriendsOfPHP/PHP-CS-Fixer#3836]
It would be very nice to have php-cs-fixer-shim (inspired by https://github.com/phpstan/phpstan-shim ). It combines both benefits of phar usage and semantic versioning and seamless update of libraries with `composer update`. 

If it's just a matter of time and maintenance, I can contribute by creating this repository.

**Comment by keradus** [comment]
:-1:

We distribute phars via regular wget and PhiVE (https://phar.io), later offers nice versioning

**Comment by SpacePossum** [comment]
Hi @mente ,

Thanks for your suggestion!
We feel the distribution of the tool (`composer`, `PhiVE` and download through `https://cs.sensiolabs.org/`) is sufficient for now, maintaining more channels will be more work we cannot take on right now, as such I'm closing this as a `won't fix`.

**Comment by keradus** [comment]
we shall still document it: #3838

**Comment by Pierstoval** [comment]
Someone created a repo to provide `php-cs-fixer` shims there: https://gitlab.irstea.fr/pole-is/tools/php-cs-fixer-shim

I mean, creating such repository should not be too hard. A webhook on the main repo that listens to releases, and the receiver retrieves the tag, builds the phar, commits it in the shims repo, tag the commit, push, done.

It would definitely allow having it with `composer req friendsofphp/php-cs-fixer-shims` without risking conflicts in the main project's dependencies. Kinda the same thing than phpstan does.

**Comment by julienfalque** [comment]
@Pierstoval that would still require a few extra work (setup then maintenance) from us and we lack time for the things we already want to do here. I'm personally not against this but I won't make it our priority at the moment.

Also note that even with such repository I would still strongly discourage installing the tool in the main `composer.json`: the tool won't bring its own dependencies anymore but the extension you might need will (e.g. extra rules from another repository). We already see this here with PHPStan.

Installing PHP CS Fixer via the main `composer.json` is even sementically wrong IMO: it's a tool, not an actual dependency your application/library needs to run (unless you're developping some PHP CS Fixer extension).
