### ISSUE TITLE
phpdoc_var_without_name also removing name from inline annotations

### ISSUE THREAD

**Issue by dmvdbrugge** [FriendsOfPHP/PHP-CS-Fixer#3852]
#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix -v --using-cache=no`

#### The configuration file you are using, if any:
Basically the same as [dmvdbrugge/dynamic-components](https://github.com/dmvdbrugge/dynamic-components/blob/5dfba1d7ea9573b2f2d75468556c988019be541c/.php_cs.dist), except `explicit_string_variable`, `header_comment`, `no_alternative_syntax`, and `no_unset_on_property`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
/**
 * @var \Model_Payment $payment
 */
foreach ([
    $payment1,
    $payment2,
] as $payment) {
```

* after first run:
```php
/**
 * @var \Model_Payment
 */
foreach ([
    $payment1,
    $payment2,
] as $payment) {
```

* after second run:
```php
/*
 * @var \Model_Payment
 */
foreach ([
    $payment1,
    $payment2,
] as $payment) {
```

* expected:
No changes, as this is an "inline" docblock (just spread out over multiple lines).
When I change the code to 
```php
/** @var \Model_Payment $payment */
foreach ([
    $payment1,
    $payment2,
] as $payment) {
```
Nothing changes as expected.

Meta: this is case 1 of #3844 (looks like not a priority issue at all, just like #3849 and maybe #3850)

**Comment by julienfalque** [comment]
Thanks for the report! This duplicates #3112.
