### ISSUE TITLE
binary_operator_spaces conflicts with itself

### ISSUE THREAD

**Issue by dmvdbrugge** [FriendsOfPHP/PHP-CS-Fixer#3853]
#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix -v --using-cache=no`

#### The configuration file you are using, if any:
Basically the same as [dmvdbrugge/dynamic-components](https://github.com/dmvdbrugge/dynamic-components/blob/5dfba1d7ea9573b2f2d75468556c988019be541c/.php_cs.dist), except `explicit_string_variable`, `header_comment`, `no_alternative_syntax`, and `no_unset_on_property`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
$variable = $some_var == Something::ELSE;
$longer_variable = $some_var == Something::ELSE;
```

* after first run:
```php
$variable        = $some_var        == Something::ELSE;
$longer_variable = $some_var == Something::ELSE;
```
Here it tried to first align the `==` with each other, before aligning the `=`.

* after second run:
```php
$variable        = $some_var == Something::ELSE;
$longer_variable = $some_var == Something::ELSE;
```

* expected:
Immediately arrive at the last step

Meta: this is (one of) case 2 of #3844

**Comment by SpacePossum** [comment]
thanks,
this one duplicates: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3729
I thought I was close in fixing that bug, but it more complex than I thought :(
