### ISSUE TITLE
NativeConstantInvocationFixer - should not prepend a backslash when the file is not namespaced

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#3872]
If the file is not namespaced, all native calls are already fully-qualified. So prepending a backslash is not necessary there.

**Comment by stof** [comment]
OK, actually, NativeFunctionInvocationFixer already has a `scope` option for that AFAIU. but NativeConstantInvocationFixer does not have it

**Comment by keradus** [comment]
@stof, can you propose a PR to add `scope` option for native_constant_invocation rule ?

**Comment by stof** [comment]
@keradus already done
