### ISSUE TITLE
Circle CI needs to be migrated to v2

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#3874]
Circle CI builds are displaying a warning about running on v1 which will be shutdown after August 31, 2018.

So migrating the CI to Circle CI v2 is needed before the end of the summer.

**Comment by keradus** [comment]
when v2 was launched, PHP was not offered for it (at least officially).
I hope it's available now...

**Comment by stof** [comment]
I don't think it is offered officially on v1 either. the current config is installing PHP on its own: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/ceec561308e27f2778c869d82e0c08109ff27d17/circle.yml#L15

**Comment by stof** [comment]
I have absolutely no experience with Circle CI. I opened this issue due to seeing a warning when looking at the build for one of my PRs.
