### ISSUE TITLE
Add a rule to force-add or force-remove `?` on nullable types

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#3883]
Sorry if this already exists, I didn't find it with a quick lookup,

Since PHP 7.1, nullable arguments can be written with or without the `?` prefix:
Form 1: `function (string $s = null) {}`
vs
Form 2: `function (?string $s = null) {}`

It would be great to have a rule to normalize to either form 1 or 2.
(On Symfony, we would stick to Form 1 for consistency with branches that still support PHP 5.5)

**Comment by SpacePossum** [comment]
Hi,
Sounds like a good idea, we currently don't have a rule for this nor an open request for it, so all good :+1:

**Comment by gharlan** [comment]
@keradus I think for this case the NoUnreachableDefaultArgumentValueFixer should be updated.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/src/Fixer/FunctionNotation/NoUnreachableDefaultArgumentValueFixer.php#L102

`isTypehintedNullableVariable` should be replaced by
`isNonNullableTypehintedNullableVariable`

**Comment by keradus** [comment]
Closing due to merge of #4401
