### ISSUE TITLE
ConcatSpace - deprecate in favor of BinaryOperatorSpaces

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3899]
`binary_operator_spaces` now supports `no_space` no space, so concat ops can fixed just as the other bin. ops. 

- deprecate `concat_space` rule
- ~add `.` to the `operators` supported operators of `binary_operator_spaces`~ done
- change `concat_space` rule to proxy of `binary_operator_spaces`
- on v3 remove `concat_space` rule, must be done in another PR after the previous items have been handled

**Comment by ahmadkarlam** [comment]
Is this still open ? I like to learn it. I try to learn to contribute on Github too 😄.

**Comment by kubawerlos** [comment]
@ahmadkarlam it looks so, do the honours 😃

**Comment by SpacePossum** [comment]
It is still open, however I noticed that it might not be an easy pick....
The concat operator has an odd exception; this is valid:
```
$b = $a. 1;
```
this is not:
```
$b = $a.1;
```
this is unique of the concat operator.
Secondly, there are some more changes coming up for operator in 7.4;
https://wiki.php.net/rfc/concatenation_precedence

so sure it can be done, however if you want an issue to get into github and the project then there might be better candidates

**Comment by SpacePossum** [comment]
not worth the trouble and risk, closing as such
