### ISSUE TITLE
FunctionToConstant - update `get_class`

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3900]
Currently `get_class($this)` is not fixed.
Update the logic to change `get_class($this)` to:
> `self::class` if the class is final
> `static::class` if not final

as such the rule must run after `final_internal_class`

note by kerad:
`@Symfony` ruleset

**Comment by ntzm** [comment]
However, https://3v4l.org/8Ts0d

**Comment by SpacePossum** [comment]
alrighty,
maybe if `get_class` is used within a closure, fixture or trait, don't fix, alternative would be throw more details in the risky-text

**Comment by ntzm** [comment]
I'd vote for making it risky personally

**Comment by keradus** [comment]
if the file is final, I would like to see this change as well, even if there were no `get_class` originally:
```diff
-static::class
+self::class
```
but other would not.

IMO, 2 different rules, good priority and integration test, voila

**Comment by fabpot** [comment]
I wanted to create an issue for the same. In Symfony, we have a lot of `get_class($this)` that could be converted to `static::class` (100% of them actually). Is it still something you want to consider adding to PHP-CS-Fixer?

**Comment by keradus** [comment]
@fabpot , for sure sth we want to have.

@ntzm , concern raised by you - `self::class vs get_class($this)` is that `get_class` works as `static::class, not `self::class`.

**Comment by SpacePossum** [comment]
added in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4742
