### ISSUE TITLE
FR: Add 'final' keyword to classes

### ISSUE THREAD

**Issue by JarJak** [FriendsOfPHP/PHP-CS-Fixer#3902]
Feature Request

According to https://ocramius.github.io/blog/when-to-declare-classes-final/

Make classes final, if they are not extended somewhere, they implement an interface, and no other public methods are defined.

**Comment by SpacePossum** [comment]
Hi and thanks for the suggestion,

Is this something you feel not covered by the rule `final_internal_class` ?

**Comment by JarJak** [comment]
I mean something like https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Solid/FinalInterfaceFixer.php

**Comment by SpacePossum** [comment]
I think this request is similar to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3923 and the related PR of it, therefore I'm closing this one in favor of discussing it in one place.

There is a lot of work and talk about this issue so please @JarJak hop over to the other issue and PR to give your input if you can :)
