### ISSUE TITLE
New fixer: Make classes final

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3923]
Apart from:

- Doctrine entities
- Abstract classes

Any others?

**Comment by keradus** [comment]
in Sf, classes are marked as `@final` via annotation, when they can not be marked with `final` keyword yet (due to BC promise)
it may be worth to have an option to mark with final either by annotation or keyword,
and not add keyword when annotation is there

**Comment by Slamdunk** [comment]
References:

1. https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3902
1. https://github.com/Slamdunk/php-cs-fixer-extensions/blob/master/lib/FinalInternalClassFixer.php
1. https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Solid/FinalInterfaceFixer.php

**Comment by keradus** [comment]
@Slamdunk , what would you think about sharing your fixer and incorporating it into main package ?
