### ISSUE TITLE
PHP needs to be a minimum version of PHP 5.3.6 and maximum version of PHP 7.1.*

### ISSUE THREAD

**Issue by mikeerickson** [FriendsOfPHP/PHP-CS-Fixer#3925]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> ....................................

PHP 7.2.7 (cli) (built: Jun 23 2018 11:20:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> ....................................

Unable to get version from above command, but I am sure I installed 2.12.2

composer global require friendsofphp/php-cs-fixer:2.12.2

#### The command you use to run PHP CS Fixer:
=> ....................................

Trying to run simple --version grab, produces above

**Comment by mikeerickson** [comment]
@julienfalque I am following what you are saying (makes good sense) but I believe I am still having this issue, even when executing from where you are outlining

![image](https://user-images.githubusercontent.com/183153/42830283-d8c3f906-899f-11e8-8f25-ff1ebc16074b.png)

**Comment by kubawerlos** [comment]
When you write `php-cs-fixer` bash searches for the binary from `$PATH` directories.

Try `./php-cs-fixer --version`.

**Comment by mikeerickson** [comment]
@kubawerlos OK, got it working!  Using the following

```
~/.composer/vendor/bin/php-cs-fixer
```

And when configuring with VSCode, had to set

```
...
  "php-cs-fixer.executablePath": "~/.composer/vendor/bin/php-cs-fixer"
...
```
