### ISSUE TITLE
Unable to write to cache file located on a network drive

### ISSUE THREAD

**Issue by iotch** [FriendsOfPHP/PHP-CS-Fixer#3934]
I'm getting the following error after upgrading from 2.7.x version:

```
In FileHandler.php line 74:
                                                                                        
  [Symfony\Component\Filesystem\Exception\IOException]                                  
  Cannot write to file "Y:\collection\.php_cs.cache" as it is not writable.  
                                                                                        

Exception trace:
 PhpCsFixer\Cache\FileHandler->write() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Cache\FileCacheManager.php:118
 PhpCsFixer\Cache\FileCacheManager->writeCache() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Cache\FileCacheManager.php:80
 PhpCsFixer\Cache\FileCacheManager->__destruct() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php:267
 PhpCsFixer\Console\Command\FixCommand->execute() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:251
 Symfony\Component\Console\Command\Command->run() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\symfony\console\Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\symfony\console\Application.php:262
 Symfony\Component\Console\Application->doRun() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Application.php:84
 PhpCsFixer\Console\Application->doRun() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\symfony\console\Application.php:145
 Symfony\Component\Console\Application->run() at C:\Users\Kanstantsin\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\php-cs-fixer:76
```
The `.php_cs.cache` is located on a network drive mounted with samba on Linux machine. The file is actually writable, but `is_writable()` returns `false` at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Cache/FileHandler.php#L73

I believe this is related to https://bugs.php.net/bug.php?id=73543

So maybe its a good idea to not to rely on `is_writable()` but try to write to the file without this check, as it was prior to version 2.8.

Relevant smb.conf section:
```
[packages]
path = /var/packages
public = yes
writeable = yes
browseable = yes
guest ok = yes
follow symlinks = no
create mode = 0644
directory mode = 0755
hosts allow = 127. 10.0.0. 192.168.1.
force user = someuser
force group = somegroup
```

----------

#### The PHP version you are using (`$ php -v`):
PHP 7.1.3 (cli) (built: Mar 14 2017 23:33:35) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
php-cs-fixer.bat "--config=C:\\[...]\\.php_cs" --allow-risky=yes --verbose fix Y:\collection\src\GenericCollection.php

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(false)
    ->setRules([
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => true,
        'function_to_constant' => true,
        'hash_to_slash_comment' => true,
        'is_null' => true,
        'mb_str_functions' => true,
        'no_empty_statement' => true,
        'no_leading_import_slash' => true,
        'no_unused_imports' => true,
        'no_useless_return' => true,
        'not_operator_with_successor_space' => false,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'phpdoc_scalar' => true,
        'psr4' => true,
        'single_blank_line_before_namespace' => true,
        // 'ordered_class_elements' => true,
    ]);
```

**Comment by SpacePossum** [comment]
Hi @iotch and thanks for report,

Reading up on the bug report on the PHP tracker this seems indeed a PHP bug that is unresolved.
I would prefer to see it resolved there, so if anyone can get their attention to follow up on this please reach out to them :)
In the mean time I would recommend using a local cache file or disable the caching all together.
We could apply a workaround for the testing if we can write to the file till the bug is fixed, any opinions anyone?

**Comment by SpacePossum** [comment]
I'm going to close here as the bug is a PHP one and I see no nice work around, secondly nobody else either reported the issue or proposed a nice work around, thanks for reporting!
