### ISSUE TITLE
Fixer for reordering traits

### ISSUE THREAD

**Issue by JarJak** [FriendsOfPHP/PHP-CS-Fixer#3945]
I would be nice to have a fixer for trait imports.

```
    use SomeTrait,
        
        AnotherTrait
    
        ;
```

would become

```
    use AnotherTrait,
        SomeTrait;
```

(moved from https://github.com/Symplify/Symplify/issues/1006)

**Comment by keradus** [comment]
Hi there !

feel free to raise a PR with such feature against master branch ;)

**Comment by SpacePossum** [comment]
based on the title this is about ordering of traits (so not the empty line CS fix),
than it is a good idea but also a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1334
