### ISSUE TITLE
Doesn't automatically use windows new line endings

### ISSUE THREAD

**Issue by joelharkes** [FriendsOfPHP/PHP-CS-Fixer#3955]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):

PHP 7.2.7 (cli) (built: Jun 19 2018 23:13:48) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:

php-cs-fixer fix -vvv

#### The configuration file you are using, if any:

```php
<?php
use PhpCsFixer\Config;
use PhpCsFixer\Finder;

require 'vendor/autoload.php';

$finder = Finder::create()->in([
    __DIR__ . '/app',
    __DIR__ . '/config',
    __DIR__ . '/database',
    __DIR__ . '/tests',
]);

return Config::create()
    ->setRules([
        '@Symfony' => true,
        'binary_operator_spaces' => ['align_double_arrow' => false, 'align_equals' => false],
        'combine_consecutive_unsets' => true,
        'concat_space' => ['spacing'=> 'one'],
        'dir_constant' => true,
        'no_mixed_echo_print' => ['use'=> 'echo'],
        'ereg_to_preg' => true,
        'general_phpdoc_annotation_remove' => false,
        'phpdoc_no_alias_tag' => ['type' => 'var'],
        'header_comment' => false,
        'linebreak_after_opening_tag' => true,
        'modernize_types_casting' => true,
        'no_blank_lines_before_namespace' => false,
        'no_php4_constructor' => true,
        'no_short_echo_tag' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'not_operator_with_space' => false,
        'not_operator_with_successor_space' => false,
        'ordered_class_elements' => false,
        'ordered_imports' => true,
        'php_unit_construct' => true,
        'php_unit_dedicate_assert' => true,
        'php_unit_strict' => false,
        'phpdoc_order' => true,
        'psr0' => false,
        'psr4' => true,
        'random_api_migration' => true,
        'array_syntax' => ['syntax' => 'short'],
        'simplified_null_return' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'phpdoc_align' => ['align' => 'left'],
    ])
    ->setLineEnding("\r\n")
    ->setRiskyAllowed(true)
    ->setUsingCache(true)
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

problem is i have to manually add `  ->setLineEnding("\r\n")` otherwise it doesn't work.
But since i also want to work on linux sometimes this is not acceptable. why does it not automatically detect windows line endings and use them as such, and is there a way to fix that?

**Comment by kubawerlos** [comment]
> problem is i have to manually add `->setLineEnding("\r\n")` otherwise it doesn't work.

@joelharkes it does work, you have selected `@Symfony` ruleset, which contains `@PSR2` ruleset, and PSR2 has this:

> All PHP files MUST use the Unix LF (linefeed) line ending.

**Comment by joelharkes** [comment]
Ah ofc it's just php. Thanks you're amazing!
