### ISSUE TITLE
Withespace after opening tag no trimed

### ISSUE THREAD

**Issue by waghanza** [FriendsOfPHP/PHP-CS-Fixer#3956]
Hi,

I have a file starting with a withespace after the opening tag.
```php
<?php 
```

Using
~~~
composer exec php-cs-fixer -- fix --rules=@PSR1,@PSR2 src/
~~~

does not trim this withespace, but
~~~
composer exec php-cs-fixer -- fix --rules=@PSR1,@PSR2,@Symfony src/
~~~
does

+ **PHP** : `7.1.17`
+ **PHP CS Fixer** : `2.12.2`

Regards,

**Comment by SpacePossum** [comment]
`no_trailing_whitespace` rule should be updated to check for this special case

**Comment by SpacePossum** [comment]
`<?php ` cannot be fixed to `<?php` because that is not valid PHP

**Comment by SpacePossum** [comment]
```
<?php

```
with space after `<?php`  can be trimmed (but the newline must be there than)
