### ISSUE TITLE
Grammar correction

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfPHP/PHP-CS-Fixer#3965]
`v2.11.0`

> You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
Loaded config default from "/applications/listings/.php_cs".
Paths from configuration file have been overridden by paths provided as command arguments.

The last sentence should read: ..... Paths from configuration file `has` been .....

**Comment by BentCoder** [comment]
Just realised it is `PathS` :)

**Comment by keradus** [comment]
no worry, thanks for raising the ticket anyway ! that's good attitude !
