### ISSUE TITLE
Atom beautify not woking with PHP.CS.Fixer  

### ISSUE THREAD

**Issue by YutaNakai** [FriendsOfPHP/PHP-CS-Fixer#3966]
It,s my first time here. I dont't really know what to do.

I'm from 
https://github.com/Glavin001/atom-beautify/issues/2195

I've been trying to beautify but no result and turns out it's beacuse of PHP.CS.Fixer.
Please help.

It,s my debug
https://gist.github.com/YutaNakai/3811fd962dff276cd3e19c702469c416

**Comment by YutaNakai** [comment]
![33](https://user-images.githubusercontent.com/42037264/43910430-c80047b4-9c37-11e8-89c9-beb39a34e8c1.png)

I also installed php.cs.fixer on the internet.
This is where it is.


![34](https://user-images.githubusercontent.com/42037264/43910642-52b4dcda-9c38-11e8-861a-7fc49102456f.png)

This is path in setting of PHP.CS.Fixer in Atom.

**Comment by keradus** [comment]
1. in future, please follow the issue template you were asked for during opening a ticket

2. in debug file you provided, there is:
> Files that were not fixed due to errors reported during linting before fixing:
>    1) C:\Users\kjlwn\AppData\Local\Temp\temp118710-16156-3zj1d6.n2zlw.php

it means that file that PHP CS Fixer was asked to fix/lint is not valid PHP file. try out with `php -l C:\Users\kjlwn\AppData\Local\Temp\temp118710-16156-3zj1d6.n2zlw.php` to see why

**Comment by YutaNakai** [comment]
Thank you.

Where should I put

"php -l
C:\Users\kjlwn\AppData\Local\Temp\temp118710-16156-3zj1d6.n2zlw.php"？

**Comment by SpacePossum** [comment]
@YutaNakai it is a PHP command for the commandline, so you can run it in a console or command window (not sure how it is called in Windows).

Basically, what the tool tries to tell you is that the contents of that file is not valid PHP.
It might be worth checking out what is that file in the first place, it might provide clues how to proceed.

You might want to check the configuration to see why this file is being fixed, maybe you don't want file in the temp folder to be fixed,

**Comment by YutaNakai** [comment]
l really appreciate you responding.

but what do I run?

**Comment by keradus** [comment]
https://www.google.pl/search?q=windows+how+to+run+cli+command
