### ISSUE TITLE
PHP.CS.Fixer not working

### ISSUE THREAD

**Issue by YutaNakai** [FriendsOfPHP/PHP-CS-Fixer#3970]
I've been trying to beautify codes with PHP.CS.Fixer tha are in Atom.
I did run PHP.CS.Fixer in cmd but none of code that I want to fix  has changed.
When I run PHP.CS.Fixer in cmd the file 'php-cs-fixer-v2.phar' creates.

I insatlled PHP.CS.Fixer at https://github.com/FriendsOfPHP/PHP-CS-Fixer.

PHP: 7.1.2
PHP-CS-Fixer: 4.1.1
PHP-CS-Fixer Conf: I don't know how to do it.
ATOM: 1.29.0
Beautify: 0.32.5
Beautify Conf: I don't know how to do it.

 * before running PHP CS Fixer (no changes):
```php
=><?php

$num = 10;

   $dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
$user = 'tennisuser';

   $page = 0;


    if (isset($_GET['page']) && $_GET['page'] > 0) {
        $page = intval($_GET['page'])-1;
    } try {
        $db = new PDO($dsn, $user, $password);
        $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

        $stmt = $db ->prepare("
    SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
    ");

        $page = $page * $num;
        $stmt->bindParam(':page', $page, PDO::PARAM_INT);
        $stmt->bindParam(':num', $num, PDO::PARAM_INT);

        $stmt ->execute();
    } catch (PDOException $e) {
        die('エラー：'.$e->getMessage());
    }
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>掲示板</title>
  </head>  <body>
       <p><a href="index.php">トップページに戻る</a></p>
    <form class="" action="write.html" method="post">
          <p>名前:<input type="text" name="name"></p>
      <p>タイトル:<input type="text" name="title"></p>
      <textarea name="body"></textarea>
      <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
      <p><input type="submit" value="書き込む"></p>

    </form></body>
</html>

This below is what I want.
<?php

$num = 10;
$dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
$user = 'tennisuser';
$page = 0;


    if (isset($_GET['page']) && $_GET['page'] > 0) {
        $page = intval($_GET['page'])-1;
    } try {
        $db = new PDO($dsn, $user, $password);
        $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

        $stmt = $db ->prepare("
    SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
    ");

        $page = $page * $num;
        $stmt->bindParam(':page', $page, PDO::PARAM_INT);
        $stmt->bindParam(':num', $num, PDO::PARAM_INT);

        $stmt ->execute();
    } catch (PDOException $e) {
        die('エラー：'.$e->getMessage());
    }
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>掲示板</title>
  </head>  

  <body>
       <p><a href="index.php">トップページに戻る</a></p>
    <form class="" action="write.html" method="post">

      <p>名前:<input type="text" name="name"></p>
      <p>タイトル:<input type="text" name="title"></p>
      <textarea name="body"></textarea>
      <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
      <p><input type="submit" value="書き込む"></p>

    </form>
  </body>
</html>

**Comment by YutaNakai** [comment]
C:\xampp\php\php-cs-fixer-v2.phar fix C:\xampp\htdocs\stuff\exa.php

It is what I run in cmd. After that like this

![40](https://user-images.githubusercontent.com/42037264/44036118-0567ed98-9f4c-11e8-8094-9f25a7b6e54a.png)

**Comment by ntzm** [comment]
You posted a screenshot of the contents of php-cs-fixer, not the code in `exa.php`

**Comment by YutaNakai** [comment]
Tnank you for replying.
This is it.

`<?php

$num = 10;

   $dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
$user = 'tennisuser';

   $page = 0;


    if (isset($_GET['page']) && $_GET['page'] > 0) {
        $page = intval($_GET['page'])-1;
    } try {
        $db = new PDO($dsn, $user, $password);
        $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

        $stmt = $db ->prepare("
    SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
    ");

        $page = $page * $num;
        $stmt->bindParam(':page', $page, PDO::PARAM_INT);
        $stmt->bindParam(':num', $num, PDO::PARAM_INT);

        $stmt ->execute();
    } catch (PDOException $e) {
        die('エラー：'.$e->getMessage());
    }
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>掲示板</title>
  </head>  <body>
       <p><a href="index.php">トップページに戻る</a></p>
    <form class="" action="write.html" method="post">
          <p>名前:<input type="text" name="name"></p>
      <p>タイトル:<input type="text" name="title"></p>
      <textarea name="body"></textarea>
      <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
      <p><input type="submit" value="書き込む"></p>

    </form></body>
</html>
`

I messed up HTML code on purpose.

**Comment by YutaNakai** [comment]
`
<?php

   $num = 10;
$dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
  $user = 'tennisuser';
$page = 0;


    if (isset($_GET['page']) && $_GET['page'] > 0) {
        $page = intval($_GET['page'])-1;
    } try {
        $db = new PDO($dsn, $user, $password);
        $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

        $stmt = $db ->prepare("
    SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
    ");

        $page = $page * $num;
        $stmt->bindParam(':page', $page, PDO::PARAM_INT);
        $stmt->bindParam(':num', $num, PDO::PARAM_INT);

        $stmt ->execute();
    } catch (PDOException $e) {
        die('エラー：'.$e->getMessage());
    }
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>掲示板</title>
  </head>

  <body>
       <p><a href="index.php">トップページに戻る</a></p>
    <form class="" action="write.html" method="post">

       <p>名前:<input type="text" name="name"></p>
      <p>タイトル:<input type="text" name="title"></p>
           <textarea name="body"></textarea>
      <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
      <p><input type="submit" value="書き込む"></p>

    </form>  </body>
</html>
`

**Comment by YutaNakai** [comment]
Tnank you for replying.

The code on my question is exa.php

**Comment by ntzm** [comment]
What's wrong with that?

**Comment by YutaNakai** [comment]
HTML doesn't get changed

**Comment by ntzm** [comment]
This is PHP CS Fixer not HTML CS Fixer, the HTML isn't meant to change

**Comment by ntzm** [comment]
You need to enable the indent rules using a config file, which you can read about here: https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file

**Comment by YutaNakai** [comment]
I checked but I don't know what to do.
What sould I run in cmd?

Do I need something called Composer?

**Comment by ntzm** [comment]
You need to *create a file* called `.php_cs` with the config file in, then *run the command that you ran before*

**Comment by YutaNakai** [comment]
Did I do it correct?

![42](https://user-images.githubusercontent.com/42037264/44088984-1f74e33a-a000-11e8-86f8-2988dad3486b.png)

I also don't know what to run.

I know I'm not really good at it. But I need you to help.

**Comment by ntzm** [comment]
No, you need to create a file called `.php_cs` not `exa.php_cs`, then run the same command again

**Comment by ntzm** [comment]
You need to put the config in the `.php_cs` file https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file

**Comment by YutaNakai** [comment]
Like this?

![44](https://user-images.githubusercontent.com/42037264/44095269-55dfc3f0-a013-11e8-9700-0f40a5f6c878.png)

**Comment by ntzm** [comment]
In the `.php_cs` file!

**Comment by ntzm** [comment]
And then run `php C:\xampp\php\php-cs-fixer-v2.phar fix`

**Comment by YutaNakai** [comment]
Thank you. I did both. Nothing changed but got the mesaage in cmd.

![46](https://user-images.githubusercontent.com/42037264/44095911-eb5bb334-a014-11e8-9d16-f5021707192b.png)
![45](https://user-images.githubusercontent.com/42037264/44095932-f8191cec-a014-11e8-9aba-43271dc1b897.png)

**Comment by ntzm** [comment]
Ok, we're getting closer. You need to put what you've got in `exa.conf` inside `.php_cs`. So *delete* `exa.conf` and copy the content into `.php_cs`. OK?

Then you need to move the `.php_cs` *file* out of the `.php_cs` *directory* into `htdocs`, then, in your terminal, change directory into `htdocs` and run that command again.

**Comment by YutaNakai** [comment]
Thank you. But I din't get anything in exa.conf.
Because I just created exa.conf and put example Config file from here  
https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file


I'm so sorry I'm having hard time.

**Comment by ntzm** [comment]
Seeing as this isn't an issue with PHP-CS-Fixer, can you close this issue and email me personally at nathanielzimmermann@gmail.com? I'll try and sort your issue out

**Comment by YutaNakai** [comment]
Okay. Thank you. I really appreciate. I'll close it.

**Comment by YutaNakai** [comment]
Can't I get anything?

**Comment by ntzm** [comment]
Sorry mate I have a job I have to do as well, I'll reply to your email in depth tonight
