### ISSUE TITLE
PhpdocVarWithoutNameFixer removes variable name when it should not.

### ISSUE THREAD

**Issue by enumag** [FriendsOfPHP/PHP-CS-Fixer#3982]
php-cs-fixer version: 2.13.0

```php
/**
 * @var string $key
 * @var string $value
 */
foreach ($result as $key => $value) {
   // ...
}
```

This code is "fixed" to this:

```php
/**
 * @var string
 * @var string $value
 */
foreach ($result as $key => $value) {
   // ...
}
```

----

I tried to use multiple annotations like this but the problem with that is that PHPStan then ignores the first annotation:

```php
/** @var string $key */
/** @var string $value */
foreach ($result as $key => $value) {
```

**Comment by dmvdbrugge** [comment]
Duplicates #3112 (which has a PR: #3911)

**Comment by enumag** [comment]
@dmvdbrugge I disagree. I saw that PR and this case is not in the tests of that PR so it either does not solve or a test is missing.

**Comment by dmvdbrugge** [comment]
It solves your case, because your case will be untouched: that PR makes it so that only properties will have their docblocks examined by the fixer. As your docblocks are not docblocks for a property but for "random" other variables, they will be skipped, and thus this issue can and should be closed.

**Comment by enumag** [comment]
Without a test case I still have to disagree. ;-)

**Comment by dmvdbrugge** [comment]
It has testcases for "no property". As your case is no property, those cases prove your case isn't touched.

**Comment by enumag** [comment]
Well if you say so... Thanks for your work on the PR!
