### ISSUE TITLE
Single line "throw"

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#3988]
On symfony/symfony, we keep asking people to not split lines that start with "throw" (that's our CS, it helps grepping the code for errors.)
It'd be awesome if php-cs-fixer could do it for us.

Related to #3168 (method's signature also should be on a single line.)

**Comment by keradus** [comment]
Can you raise a PR, @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
Nope sorry I need help also.
