### ISSUE TITLE
Don't force multiline anonymous classes

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#3989]
I should be able to create an anonymous class on a single line (only when no body is defined):
```
$foo = new class() extends bar {};
```

Right now, php-cs-fixer enforces a line between the braces:
```
$foo = new class() extends bar {
};
```

**Comment by keradus** [comment]
Can you raise a PR, @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
Nope sorry I need help also.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4012 by @kubawerlos :+1:
