### ISSUE TITLE
Suggestion: Show line number

### ISSUE THREAD

**Issue by dennisdahlc** [FriendsOfPHP/PHP-CS-Fixer#3990]
Would it be possible for each token to have associated a line number from the file ?

I know that the line number is more or less impossible to keep up-to-date during the fixing, but being able to be shown the original line number of tokens fixed in the most verbose cases would be very useful.

Perhaps something like:
- Lines changed: 40,41,129

**Comment by SpacePossum** [comment]
you can use `--diff` to generate a diff, use `--diff-format=udiff` for the line numbers

**Comment by keradus** [comment]
Closing as "easy" answer was provided. Hard one would be #3601 .
Don't hesitate to continue discussion, even if thread is closed now ;)
