### ISSUE TITLE
Convert array access with curly braces to array access with square brackets

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#3991]
Today I learned that
```php
<?php
$array = ['key' => 'value'];

var_dump($array{'key'});
```
is [valid syntax](https://3v4l.org/1dTOj).

And while the PHP manual actually [documents](http://php.net/manual/en/language.types.array.php) this

> Both square brackets and curly braces can be used interchangeably for accessing array elements

I think that using curly braces for accessing array elements is wrong.

It would be great if php-cs-fixer had a fixer to replace `$array{'key'}` with `$array['key']`.

**Comment by kubawerlos** [comment]
It is great: `php-cs-fixer fix --rules=normalize_index_brace` and you are already [using](https://github.com/sebastianbergmann/phpunit/blob/7.3.5/.php_cs.dist#L117) it.

**Comment by sebastianbergmann** [comment]
Sorry for the noise.

**Comment by SpacePossum** [comment]
no worries @sebastianbergmann , thanks for raising the issue and nice to see it resolved as well :)
