### ISSUE TITLE
Where can I find default configuration?

### ISSUE THREAD

**Issue by neluzhin** [FriendsOfPHP/PHP-CS-Fixer#3993]
Hello. I want to find default rule set used by PHP-CS-Fixer in `.php_cs` format. Didn't find it in docs. It's easier to maintain project codestyle when you can look at config and understand what will be happened when you'll run the fixer.

Is it just `['@PSR2' => true]`?

**Comment by kubawerlos** [comment]
`README.rst` serves for docs in this case - each rule has an information to which ruleset it belongs.

Rulesets are defined [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.13.0/src/RuleSet.php#L28).

And if you only want to see what will be fixed you can use flags `--dry-run --diff`.

**Comment by keradus** [comment]
Indeed, default ruleset is `@PSR2`, it's defined by our code: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/src/Config.php#L34

if you may, please raise a PR to expose it in readme as well, thanks !

in the meantime, I'm closing this question, as your question has been answered
