### ISSUE TITLE
Braces setting adds a space after ifs

### ISSUE THREAD

**Issue by royreuversgit** [FriendsOfPHP/PHP-CS-Fixer#4003]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.0.30

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.0

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer.phar fix /path/to/file

#### The configuration file you are using, if any:
```php
<?php
return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => false,
        'array_indentation' => true,
        'array_syntax' => array('syntax' => 'short'),
        'combine_consecutive_unsets' => false,
        'class_attributes_separation' => [],
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote' => false,
        'binary_operator_spaces' => array(
            'align_double_arrow' => false,
            'align_equals' => false,
        ),
		'blank_line_after_opening_tag' => false,
		'no_blank_lines_before_namespace' => true,

        'braces' => array(
			'allow_single_line_closure' => true,
			'position_after_functions_and_oop_constructs' => 'same',
			'position_after_control_structures' => 'same',
			'position_after_anonymous_constructs' => 'same',
		),
		'no_trailing_comma_in_list_call' => false,
		'no_trailing_comma_in_singleline_array' => false,
		'trailing_comma_in_multiline_array' => true,
		'full_opening_tag' => false,
		'no_unused_imports' => true,
		'ordered_imports' => true,
		'ordered_class_elements' => true,
		'class_definition' => [
			'single_line' => true,
		],
        'class_definition' => array('singleLine' => true),
        'concat_space' => array('spacing' => 'one'),
        'declare_equal_normalize' => true,
        'function_typehint_space' => true,
        'hash_to_slash_comment' => true,
        'include' => true,
		'lowercase_cast' => true,
		'lowercase_constants' => false,
        'no_extra_consecutive_blank_lines' => array(
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ),
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_spaces_around_offset' => true,
        'no_unneeded_control_parentheses' => true,
        'no_whitespace_before_comma_in_array' => true,
		'no_whitespace_in_blank_line' => true,
		'no_spaces_inside_parenthesis' => true,
		'no_trailing_whitespace' => true,
		'not_operator_with_space' => false,
		'object_operator_without_whitespace' => true,
		'class_attributes_separation' => false,
        'ternary_operator_spaces' => true,
        'trim_array_spaces' => true,
        'unary_operator_spaces' => true,
		'whitespace_after_comma_in_array' => true,
		'switch_case_space' => false,
    ))
    ->setIndent("\t")
    ->setLineEnding("\n")
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
		if($request->expectsJson()) {
			return new JsonResponse($transformed);
		}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
		if ($request->expectsJson()) {
			return new JsonResponse($transformed);
		}
```

 * with the changes you expected instead:
```php
		if($request->expectsJson()) {
			return new JsonResponse($transformed);
		}
```

I expected no changes but a space will be added behind the if. 
This stops occurring when I remove the 'braces' array from the settings file.
Unfortunately I want to use this setting for purposes such as keeping the { on the same line as the class(name).
Is seems odd that the 'braces' settings is adding a space before the if or is this on purpose?

**Comment by ntzm** [comment]
That's on purpose to adhere to PSR-2

**Comment by royreuversgit** [comment]
Even tho it is intended, is there a way to change this behaviour? I already set '@PSR2' to false in the settings.

**Comment by ntzm** [comment]
Unfortunately not, `braces` is one of the fixers that does a lot of fixing

**Comment by royreuversgit** [comment]
Ah oke, thanks for the information

**Comment by davi5e** [comment]
Even though it's PSR2, shouldn't it be moved to it's own rule? The parenthesis spaces are being checked under `Braces` and applies to `if`, `else`, `for`, etc...

Moreover, what if people use a different notation? In my humble opinion, this should be configurable in spite what PSR2 defines...

**Comment by dktapps** [comment]
^ seconded, I just ran into this problem myself, we don't use PSR-2 but we can't opt-out of the spacing if `braces` rules are used.

**Comment by julienfalque** [comment]
I reopened #823 to track this.

**Comment by salarmehr** [comment]
Any update for this? We also don't need spaces after the control statement.
