### ISSUE TITLE
Call to protected method PhpCsFixer\Tokenizer\Tokens::generatePartialCode() from context 'PhpCsFixer\Tokenizer\Analyzer\NamespacesAnalyzer'

### ISSUE THREAD

**Issue by jbnv** [FriendsOfPHP/PHP-CS-Fixer#4004]
All of a sudden I'm getting this error in some of my repositories, but not others. All of them are using custom fixers that I wrote. 

      PhpCsFixer\Tokenizer\Analyzer\NamespacesAnalyzer->getDeclarations()
        in phar:///usr/local/bin/php-cs-fixer/src/Fixer/Import/FullyQualifiedStrictTypesFixer.php at line 79
      PhpCsFixer\Fixer\Import\FullyQualifiedStrictTypesFixer->isCandidate()
        in phar:///usr/local/bin/php-cs-fixer/src/AbstractFixer.php at line 74
      PhpCsFixer\AbstractFixer->fix()
        in /my_project/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 190
      PhpCsFixer\Runner\Runner->fixFile()
        in /my_project/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 132
      PhpCsFixer\Runner\Runner->fix()
        in phar:///usr/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php at line 220
      PhpCsFixer\Console\Command\FixCommand->execute()
        in phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php at line 251

#### The PHP version you are using (`$ php -v`):

PHP 7.0.17 (cli) (built: Mar 18 2017 20:13:50) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski (dcc87d5)

**Comment by keradus** [comment]
@jbnv , what was the reason of issue ?
(I see you had closed it, so probably you had figured it out on your own already ;) )
