### ISSUE TITLE
Rule native_constant_invocation doesn't work in some cases

### ISSUE THREAD

**Issue by bkrukowski** [FriendsOfPHP/PHP-CS-Fixer#4008]
#### The PHP version you are using (`$ php -v`):
=> 7.1.22

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.0 Yogi's BBQ

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix . --rules=native_constant_invocation --allow-risky=yes`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function doSth($bitmask) {
}

doSth(E_DEPRECATED | E_USER_DEPRECATED);

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

function doSth($bitmask) {
}

doSth(E_DEPRECATED | \E_USER_DEPRECATED);

```

 * with the changes you expected instead:
```php
<?php

function doSth($bitmask) {
}

doSth(\E_DEPRECATED | \E_USER_DEPRECATED);

```

**Comment by ntzm** [comment]
There's no use of prefixing `\` if you're not in a namespace. The fixer is working as intended

**Comment by bkrukowski** [comment]
@ntzm no. Why first constant has changed and second hasn't? Anyway issue occurs not only in root namespace.

**Comment by ntzm** [comment]
Ah sorry read the report wrong, looks like this is a genuine bug.

**Comment by ntzm** [comment]
The bug is in TypeAlterationTransformer, I'm working on a fix now

**Comment by SpacePossum** [comment]
Thanks @bkrukowski for reporting and @ntzm for picking this up :+1:

**Comment by SpacePossum** [comment]
fixed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4009
