### ISSUE TITLE
Simple methods in one line

### ISSUE THREAD

**Issue by souljacker** [FriendsOfPHP/PHP-CS-Fixer#4010]
Is it possible to set the fixer to allow this as the option in PHP Storm?

It would allow this kind of function:

`	function foo() { return 0; }
`

**Comment by SpacePossum** [comment]
Hi,

The change you likely want to prevent from happening is done by the `braces` rule.
You can check the configuration option:

```
allow_single_line_closure: true
```

In order to help you further please following the issue-template so we've at least the base info to work with, thanks!

**Comment by SpacePossum** [comment]
closing as we didn't hear back from the reporter for a over a year
