### ISSUE TITLE
Allow removing the "b" mode from fopen calls

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#4011]
Since #3812, php-cs-fixer keeps adding the 'b' mode to fopen() calls.
But since PHP ~4~5.something, this is already the default.
It should be disabled by default IMHO.

**Comment by SpacePossum** [comment]
Hi @nicolas-grekas 
Can you point to the code where PHP makes sure this is the default? 
AFAIK the default is left to the SAPI and version of PHP in use, leaving room for different behavior of the same code on different environments when the flag is omitted.

Secondly, do you want a rule to remove the flag or would removing the current rule that adds it from the Symfony set be sufficient?

**Comment by nicolas-grekas** [comment]
This commit I think: https://github.com/php/php-src/commit/fa342d2404a9c809d0a182d80798da2abd3a98f7

**Comment by SpacePossum** [comment]
:+1:  that settles it than :)
do you still want a fixer to remove the `t` flag as well, or just the `b` flag?

**Comment by nicolas-grekas** [comment]
The "t" flag should never be used for sure (it's not portable).
About the "b", I think it's fine to not care. At least we could remove it from the Symfony ruleset I think.

**Comment by ntzm** [comment]
Welp, that's my bad, part of the documentation is out of date :(

**Comment by keradus** [comment]
let's simply update the fixer and ruleset, nice finding @nicolas-grekas

**Comment by SpacePossum** [comment]
reopen to discuss changing the default config (and on what release (branch))

**Comment by dbu** [comment]
the documentation of php itself "strongly recommends" to not rely on the default "b" and set it explicitly: https://www.php.net/manual/en/function.fopen.php

**Comment by SpacePossum** [comment]
I think this issue has been resolved here;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/69b973a4ee21bc2c8d1a10b37b37c31c1379ee69#diff-1e418beac3b4a9cf60ecd4ca4e2975a8R171

so by default the SF will remove the `b` flag.

@dbu I think the documentation of PHP is outdated on this topic, however I config my projects to keep adding the `b` for the same `strong recommends` :)
