### ISSUE TITLE
ClassAttributesSeparationFixer - Option to add blank lines only before items with PHPDocs

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#4014]
I'd like to have a new option for `class_attributes_separation` rule that makes it add blank lines before items with PHPDocs only, e.g.:

```diff
 class Foo
 {
     private $foo;
     private $bar;
 }
 
 class Bar
 {
     /**
      * @var int
      */
     private $foo;
+
     /**
      * @var int
      */
     private $bar;
 }
```
instead of:
```diff
 class Foo
 {
     private $foo;
+
     private $bar;
 }
 
 class Bar
 {
     /**
      * @var int
      */
     private $foo;
+
     /**
      * @var int
      */
     private $bar;
 }
```

Maybe the format of this option should mimic the format of option `elements` as one might not want to enable the new behavior for all kinds of element. I would make it default to constants and properties.

WDYT?

**Comment by SpacePossum** [comment]
Not sure about the default, but it is an option requested multiple times so :+1:  for adding it.
Which new configuration format do you propose for this?

**Comment by julienfalque** [comment]
> it is an option requested multiple times

I was pretty sure we already discussed something similar a while ago but I couldn't find it before opening this issue. I tried harder and just found https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3098#discussion_r145252212.

I would still propose this solution actually, maybe with one more possible value: `ignore`. So:

```php
[
    'const' => 'ignore | no_blank_line | single_blank_line | single_blank_line_if_phpdoc',
    'property' => 'ignore | no_blank_line | single_blank_line | single_blank_line_if_phpdoc',
    'method' => 'ignore | no_blank_line | single_blank_line | single_blank_line_if_phpdoc',
]
```

Though #4001 requests an option to set the number of blank lines added, so maybe not the best solution.

**Comment by SpacePossum** [comment]
ah that is fine with me as well :)
