### ISSUE TITLE
Reverse fixer for is_null

### ISSUE THREAD

**Issue by Riimu** [FriendsOfPHP/PHP-CS-Fixer#4015]
I wonder if it would be possible to have a fixer that works in reverse compared to the current `is_null` fixer. My reasoning for wanting like something this is as follows:

* Since PHP 7.0 (I believe), there has existed an opcode TYPE_CHECK, so in conjunction with `native_function_invocation` fixer, there isn't as notable performance difference between `$var === null` and `\is_null($var)`, since there is no function call overhead and both are exactly one opcode.
* The opcode optimizer actually treats the TYPE_CHECK and IS_IDENTICAL opcodes a bit differently. It seems that in some cases, for example, the dead code elimination can omit the `\is_null($var)` check, if the type of the variable can be inferred, even though the exact value cannot.
* With PHP 7.3, the TYPE_CHECK opcode has been changed further and actually uses a type mask, instead of specific type. As such, it may down in the line be changed to optimize, for example, the code `\is_null($var) || \is_string($var)` into a single opcode.

Now, I'm not exactly privy to why PHP internally treats TYPE_CHECK and IS_IDENTICAL differently internally for null values, but it seems that in some cases the `\is_null($var)` may actually be preferable.

So, I'm asking if it would be possible to have a fixer/option that transforms `$var === null` and `null === $var` into `\is_null($var)`, since this would allow having consistent style if you want to prefer the function call instead of the comparison.

**Comment by SpacePossum** [comment]
Hi @Riimu and thanks for your report.

The details in it are very interesting! However, as you concluded, they are not complete. Therefore I'm not in favor of changing the code to `is_null` until we know there is real benefit.

**Comment by rybakit** [comment]
I stumbled across this [commit](https://github.com/php/php-src/commit/36afe4e39ec724eab19c54c1492db030721d0ec1) recently and decided to benchmark both options. I got results that correlate with what @Riimu described above:

 * PHP 5.6: `is_null($x)` is 2.5x slower than `null === $x` with opcache disabled, and 2.2x slower with opcache enabled
 * PHP 7.0-7.2: the performance of both is the same,  with and without opcache
 * PHP 7.3-7.4: `is_null($x)` is 1.2x *faster* than `null === $x` with opcache disabled, with opcache enabled there's no noticeable difference (but still, `is_null()` is 0.2% *faster*).

Opcodes:
 * `is_null($x)` is compiled into `TYPE_CHECK`: https://3v4l.org/0PM75/vld#output
 * `null === $x` is compiled into `IS_NOT_IDENTICAL`: https://3v4l.org/duj9i/vld#output

**Comment by SpacePossum** [comment]
Thanks for the details! 
I think the gain is very minimal so creating a fixer to the reverse is not something I'll be working on any time soon. I'm ok for adding this fixer though, not sure what others think

**Comment by julienfalque** [comment]
Agreed, the gain is very minimal and I prefer `X === null` over `is_null(X)` so not a priority at all for me.

**Comment by peter-gribanov** [comment]
It is also worth considering that adding a namespace negatively affects performance, as it takes time to resolve a function.

Benchmark:
* https://3v4l.org/WQk7Q (without namespace)
* https://3v4l.org/Qru9q (with namespace)

Result [opcodes](https://3v4l.org/HjtlN/vld#output) with namespace:

* ` INIT_NS_FCALL_BY_NAME`
* `SEND_VAR_EX`
* `DO_FCALL`

Since we almost always use namespaces, to improve performance, you should always write like that  `\is_null($x)` if you want to use functions.

**Comment by rybakit** [comment]
The existence of this fixer does not mean that it should be automatically enabled by default, nothing will change for users in this regard. But for ones who want to get the maximum performance or don't want to follow outdated PRS recommendation, this fixer can be useful.

> Since we almost always use namespaces, to improve performance, you should always write like that \is_null($x) if you want to use functions.

`is_null` has been on [the list](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3e5dd53a0ab1fbe87057b06a027d8d072457ca3e/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L382) of "opcached" functions for a long time already. Again, this fixer is for users who know what they're doing, if you don't need it don't enable it (which is btw true for other fixers as well).

**Comment by peter-gribanov** [comment]
> `is_null` has been on the list of "opcached" functions for a long time already.

Hm... As i can understand, you mean `native_function_invocation` rule that belongs to the category of risky and do not apply by default. This means that without applying this rule, `$x === null` will be replaced to `in_null($x)` without explicit namespace and we will lose in performance.

**Comment by SpacePossum** [comment]
Thanks for putting this idea forward and thanks all for providing details and reasoning in this PR :+1: 
Given the responses form the members I see that there is no majority in favor of adding this as new rule to the project. As such I'm closing the FR.
