### ISSUE TITLE
Performance investigation

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#4026]
while crunching together initial numbers in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4024#issuecomment-428994403 I did some blackfire profiles

my findings:

linting a single file:
`blackfire run php ./PHP-CS-Fixer/php-cs-fixer fix ./sabre-dav/lib/CalDAV/Calendar.php`

https://blackfire.io/profiles/739e8c50-2345-4f4b-a157-e94b9b220029/graph
![grafik](https://user-images.githubusercontent.com/120441/46814772-b7038c00-cd79-11e8-99f9-4bdb3f2dbad2.png)

=> PhpCsFixer\Tokenizer\Token::equals() and PhpCsFixer\Tokenizer\Token::isGivenKind() seem to be slow

linting a folder of files (pretty similar picture):
`blackfire run php ./PHP-CS-Fixer/php-cs-fixer fix ./sabre-dav/lib/CalDAV/`

https://blackfire.io/profiles/7db4aa88-ece8-4fd4-9850-a1a7467bf1a4/graph
![grafik](https://user-images.githubusercontent.com/120441/46815438-36de2600-cd7b-11e8-9caf-f7768e8165c4.png)

=> PhpCsFixer\Tokenizer\Token::equals(), PhpCsFixer\Tokenizer\Tokens::extractTokenKind(), PhpCsFixer\Tokenizer\Tokens::offsetSet() seem to be slow

**Comment by staabm** [comment]
> can you elaborate on that ?
> what I can see is that they are called plenty of times, and well, they will, due to their responsibility

those methods are called so frequently that very minor changes can lead to walltime speed win. alternatively one could check the calling locations whether some of those calls can be saved, e.g. by using temp-variables or similar

**Comment by keradus** [comment]
Great work @staabm !
Closing due to merge of #4046, #4047, #4048 .

-----------------

After saying that, if anyone has idea how to improve performance even further, PRs are welcome !

**Comment by staabm** [comment]
Thx for merging. I am very proud to contribute to this great tool.

**Comment by keradus** [comment]
Thanks for your patience as well ;)

**Comment by ntzm** [comment]
Awesome work on this @staabm
