### ISSUE TITLE
PhpUnitNoExpectationAnnotationFixer - wrong handling of multiline annotation

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#4032]
`PhpUnitNoExpectationAnnotationFixer` will convert `testOld` into `testNew`:
```php
<?php
class FooTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @expectedException \RuntimeException
     * @expectedExceptionMessage Message
     *                           on
     *                           multilines AAA
     *                           €
     */
    public function testOld()
    {
        throw new \RuntimeException('Message');
    }

    /**
     */
    public function testNew()
    {
        $this->setExpectedException(\RuntimeException::class, 'Message on multilines AAA €');

        throw new \RuntimeException('Message');
    }
}
```

as of [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.13.0/tests/Fixer/PhpUnit/PhpUnitNoExpectationAnnotationFixerTest.php#L466) test case. But running it with PHPUnit 4.8 (no need for newer, the point is about the message conversion) will result with failure of `testNew`. Or am I missing something?

Ping @keradus as an author.

**Comment by kubawerlos** [comment]
Still would fail - `@expectedExceptionMessage` in `testOld` expects only "Message", nothing more.

**Comment by ntzm** [comment]
Oh I see, just misread

**Comment by kubawerlos** [comment]
Annotation `@expectedExceptionMessage` is removed from PHPUnit, fixing this case is not worth the effort anymore.
