### ISSUE TITLE
PhpdocToParamTypeFixer

### ISSUE THREAD

**Issue by jg-development** [FriendsOfPHP/PHP-CS-Fixer#4054]
Hi,
I hava adapted the PhpdocToReturnTypeFixer fixer and created a PhpdocToParamTypeFixer.
The goal is to convert all phpdoc params to the corresponding param type hint.
Could anybody please review this class and tests for feedback?

Greetings Jan

**Comment by julienfalque** [comment]
Hi, this feature was already requested in #3258 so I'm closing this one as duplicate, thanks.
