### ISSUE TITLE
VisibilityRequiredFixer removes comments between access modifier and variable name

### ISSUE THREAD

**Issue by pcf0** [FriendsOfPHP/PHP-CS-Fixer#4057]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.11

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.13.0

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix --rules visibility_required -- Test.php

#### The configuration file you are using, if any:
no config

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
declare(strict_types=1);

class Test
{
  private /* comment */ $private = 'private';
};
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
declare(strict_types=1);

class Test
{
  private $private = 'private';
};
```

 * with the changes you expected instead:
no change, comment not removed

**Comment by keradus** [comment]
btw, what is the purpose of such comment ?
