### ISSUE TITLE
Question integration with github

### ISSUE THREAD

**Issue by Webonaute** [FriendsOfPHP/PHP-CS-Fixer#4059]
How I can integrate PHP-CS-Fixer to automatically create PR review on github PullRequest ?
I run my build on travis, I would like to report result to the related PR on github when build is finish.

**Comment by SpacePossum** [comment]
Hi :)

Your question is interesting yet a bit out of scope of what we would like to provide, still I'm curious if someone has good pointers!
Pinging @GrahamCampbell as he made a service that uses the fixers and hooks int o the GH ecoculture.

**Comment by SpacePossum** [comment]
Hi :)

Your question is interesting yet a bit out of scope of what we would like to provide, still I'm curious if someone has good pointers!
Pinging @GrahamCampbell as he made a service that uses the fixers and hooks int o the GH ecoculture.

**Comment by dmvdbrugge** [comment]
Add a Travis build step in which you run the fixer with the `--dry-run` flag. If that would have changed anything, the fixer exits with non-zero, which makes Travis fail.

**Comment by dmvdbrugge** [comment]
Add a Travis build step in which you only run php-cs-fixer, with the `--dry-run` flag. If that would've changed anything, it exits with a non-zero status which makes the Travis build fail.

Or you can link https://prettyci.com/ (free for open source)

**Comment by dmvdbrugge** [comment]
Add a Travis build step in which you only run php-cs-fixer, with the `--dry-run` flag. If that would've changed anything, it exits with a non-zero status which makes the Travis build fail.

Or you can link https://prettyci.com/ (free for open source)

**Comment by Webonaute** [comment]
I don’t want to fail Travis build, just add review for each line error in github for current running PR in Travis

**Comment by dmvdbrugge** [comment]
As explained in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3601#issuecomment-408926036 php-cs-fixer diffs aren't explicitly mappable to PR diffs. It's also not the purpose of the tool.

Based on this, I don't think there is a service that uses php-cs-fixer to do what you want. It's also not necessary: why would you want to comment about code style, when you can just let them automatically fix it?

I think that's why PrettyCI is nice too: it doesn't fail your Travis build, but it also integrates into GH checks, so it will notify your PR that the code style is wrong.

**Comment by keradus** [comment]
Closing, as not the issue of PHP CS Fixer itself.
Feel free to continue discussion

**Comment by keradus** [comment]
> As explained in #3601 (comment) php-cs-fixer diffs aren't explicitly mappable to PR diffs.

not true anymore, use `--diff --diff-format=udiff` and you will get diff in unified diff format, which is accepted by git.

**Comment by dmvdbrugge** [comment]
Sorry bad wording, it's not explicitly mappable to the changes, as explained in that comment. And that hasn't changed.

**Comment by dmvdbrugge** [comment]
@SpacePossum why the downvote, without actually correcting what I'm saying? Look at the comment I linked and tell me how I'm wrong please.

**Comment by SpacePossum** [comment]
Because the linked issue/comment is both invalid and is also not blocking nor a requirement for the request here, it was pointed out but but you insist it is relevant and think not, that is why.

**Comment by GrahamCampbell** [comment]
> I think that's why PrettyCI is nice too: it doesn't fail your Travis build, but it also integrates into GH checks, so it will notify your PR that the code style is wrong.

You could also use StyleCI. It's sign significantly faster than PrettyCI (both on first run, and massively faster on subsequent runs) and supports more than just PHP too. Can fix JS/CSS/Vue within apps too.

https://styleci.io/
