### ISSUE TITLE
merge SingleBlankLineBeforeNamespaceFixer into BlankLineBeforeStatementFixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#4065]

**Comment by localheinz** [comment]
@SpacePossum 

I've been meaning to attend to it, but haven't found the time yet - I was thinking of a fixer that ensures single blank lines around (that is, before and after) blocks, for example:

* `if`
* `while`
* `do`
* `for`
* `foreach`
* `switch`
* `try-catch-finally`
