### ISSUE TITLE
increment_style rule should be marked as risky

### ISSUE THREAD

**Issue by maidmaid** [FriendsOfPHP/PHP-CS-Fixer#4066]
`$a = $i++;` and `$a = ++$i;` behave differently, so why isn't `increment_style` a risky rule?

**Comment by kubawerlos** [comment]
No, it should not be marked as risky.

Your examples won't be touched by the fixer, we have that covered by [tests](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.13.1/tests/Fixer/Operator/IncrementStyleFixerTest.php#L126) - those cases are "not possible" to handle as mentioned in the description:
> Pre- or post-increment and decrement operators should be used if possible.

**Comment by keradus** [comment]
Closing as answered, feel free to continue the discussion
