### ISSUE TITLE
blank_line_after_statement

### ISSUE THREAD

**Issue by Rolige** [FriendsOfPHP/PHP-CS-Fixer#4081]
Hi,

How about the creation of a rule like `blank_line_after_statement` ?
Or maybe the creation of a new one unifying the currently `blank_line_before_statement` with my suggestion of `blank_line_after_statement`.

Or there is a way, that I’m missing, to force a blank line after the parenthesis closure in a statement?

Regards,
Rolige

**Comment by dennisdahlc** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4053

**Comment by SpacePossum** [comment]
thanks for the suggestion, please follow the issue as pointed out bu @dennisdahlc ! :)
