### ISSUE TITLE
Processing other files than those stup in configuration

### ISSUE THREAD

**Issue by davidmpaz** [FriendsOfPHP/PHP-CS-Fixer#4124]
Hi all,

thanks before hand for your time. I am creating this issue because PHP CS Fixer is processing files that should not process. As my configuration state, i pretend to process all inside `src` and `tests`, no other directories. Currently is processing other directories with JavaScript files in it.

Is this intended behaviour?

#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.12-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:12) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.13.1 Yogi's BBQ by Fabien Potencier and Dariusz Ruminski (54814c6)

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer.phar fix --config=.php-cs-fixer

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setUsingCache(true)->setCacheFile(__DIR__ . '.php_cs.cache')
    ->setRiskyAllowed(true)->setRules([
        '@Symfony'                           => true,
        '@Symfony:risky'                     => true,
        '@PHP71Migration'                    => true,
        '@PHP71Migration:risky'              => true,

        'header_comment'                     => ['header' => ''],
        'declare_strict_types'               => true,
        'array_syntax'                       => array('syntax' => 'short'),
        'yoda_style'                         => false,
        'binary_operator_spaces'             => array('operators' => ['=>' => null]),
        'return_assignment'                  => false,

        'strict_comparison'                  => true,
        'strict_param'                       => true,
        'dir_constant'                       => true,
        'php_unit_strict'                    => true,
        'php_unit_no_expectation_annotation' => true,
        'php_unit_expectation'               => true,
        'php_unit_ordered_covers'            => true,
        'is_null'                            => true,
        'function_to_constant'               => true,
        'ordered_imports'                    => true,
        'not_operator_with_successor_space'  => true,
        'combine_consecutive_issets'         => true,
        'combine_consecutive_unsets'         => true,
        'escape_implicit_backslashes'        => true,
        'no_superfluous_elseif'              => true,
        'no_useless_else'                    => true,
        'static_lambda'                      => true,
        'compact_nullable_typehint'          => true,
        'method_chaining_indentation'        => true,
        'no_null_property_initialization'    => true,
        'no_useless_return'                  => true,
    ])

    ->setFinder(PhpCsFixer\Finder::create()
        ->in([
            __DIR__ . '/packages/*/src',
            __DIR__ . '/packages/*/test',
        ])
    );
```

I would expect that no other directories than those specified in configuration are processed. I have also tried to exclude the directories i don't want to process explicitely, something like this:
```php
...
->setFinder(PhpCsFixer\Finder::create()
        ->exclude([
            __DIR__ . '/packages/*/resources',
        ])
        ->in([
            __DIR__ . '/packages/*/src',
            __DIR__ . '/packages/*/test',
        ])
    );
```
But it does not work either. Any hint on this one?

Cheers,
David

**Comment by kubawerlos** [comment]
For [exclude](https://api.symfony.com/4.1/Symfony/Component/Finder/Finder.html#method_exclude):
> Directories passed as argument must be relative to the ones defined with the `in()` method

BTW, I love this line:
>         'array_syntax'                       => array('syntax' => 'short'),

Try adding `->append([__FILE__])` for `Finder` ;)

**Comment by davidmpaz** [comment]
Hehehe, Thanks!

> Try adding ->append([__FILE__]) for Finder ;)

was indeed enlighting :D

Cheers
