### ISSUE TITLE
blank_line_after_namespace enforces zero intentation on line after blank line

### ISSUE THREAD

**Issue by InvisibleSmiley** [FriendsOfPHP/PHP-CS-Fixer#4130]
#### The PHP version you are using (`$ php -v`):
7.1.23

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.13.1

#### The command you use to run PHP CS Fixer:
vendor/bin/php-cs-fixer fix --dry-run /path/to/file.php -v --diff

#### The configuration file you are using, if any:
Custom, too long/irrelevant to post here. You only need to know two things:
1. Our code style requires one level of indentation for **everything** except for the opening tag
2. The test file becomes valid if I disable blank_line_after_namespace.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
    declare(strict_types=1);

    namespace My\NS;

    use Exception;

    /**
     * Example class
     *
     * @author Me
     */
    class X extends Y {

        /**
         * Example method
         *
         * @throws Exception
         * @return void
         */
        public function test(): void {
            throw new Exception();
        }

    }

```

 * with unexpected changes applied when running PHP CS Fixer:
```
-    use Exception;
+use Exception;
```
(When fixing this, please also mind/test the case without any "use" statements!)

 * with the changes you expected instead:
None

**Comment by SpacePossum** [comment]
Hi!

Looking about your configuration you want the fixer to changes your code style to be compliant with PSR2.
As such, following the standard it will remove the indentation. The first sample of standard shows this is valid; https://www.php-fig.org/psr/psr-2/#11-example

**Comment by InvisibleSmiley** [comment]
FYI I certainly do **not** want to apply PSR-2 or make our code compliant with it. We are using a completely custom coding standard, part of which is the requirement for one level of indentation of everything but the opening tag. We have tons (read: hunderds of thousands of lines) of existing code that is already compliant with said custom code style. We even created a custom php_codesniffer ruleset for it. I'm just trying to make PHP-CS-Fixer work with it, not change our standard.

The above is just an excerpt to show the particular issue I have.

**Comment by SpacePossum** [comment]
misread indeed, sorry about that, I think your case might be related to this fix:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4109

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4132
