### ISSUE TITLE
Broken CI checks

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#4140]
Three issues happened recently:
1. Composer 1.8.0 - released on December 3rd - changed how `composer require --no-update` works.
[This](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3639) is PR that introduced `symfony/lts` usage - when you go to Travis log you can [see](https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/359259428) (click on the line with "symfony/lts" to expand logs) that it was failing from the begging. It started to break builds after Composer 1.8.0 was released. Run this series of commands to see:
    ```bash
    mkdir test173 test180
    composer self-update 1.7.3
    composer require --no-update symfony/lts:v4.0 --working-dir=test173
    composer self-update 1.8.0
    composer require --no-update symfony/lts:v4.0 --working-dir=test180
    cat test173/composer.json
    cat test180/composer.json
    
    ```
    [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4138) with fix.

2. MacOS brew formulas has changed so `brew install php72` stopped working: [log](https://circleci.com/gh/FriendsOfPHP/PHP-CS-Fixer/5315) and [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4139) with fix.

3. Symfony 4.2 introduced deprecation for constructing `Process` with command as a string - [PR](https://github.com/keradus/cli-executor/pull/2) with fix in `keradus/cli-executor` and [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4129) with fix here.

**Comment by keradus** [comment]
Closing due to all the recent merges. Thanks @kubawerlos for amazing work here!
