### ISSUE TITLE
[PHPUnit] Add migration for 7.5 assertInternalType

### ISSUE THREAD

**Issue by Slamdunk** [FriendsOfPHP/PHP-CS-Fixer#4144]
References: https://github.com/sebastianbergmann/phpunit/blob/7.5.0/ChangeLog-7.5.md

> Implemented https://github.com/sebastianbergmann/phpunit/issues/3368: Added assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), assertIsIterable(), assertIsNotArray(), assertIsNotBool(), assertIsNotFloat(), assertIsNotInt(), assertIsNotNumeric(), assertIsNotObject(), assertIsNotResource(), assertIsNotString(), assertIsNotScalar(), assertIsNotCallable(), assertIsNotIterable() as alternatives to assertInternalType() and assertNotInternalType()
> 
> The methods assertInternalType() and assertNotInternalType() are now deprecated. There is no behavioral change in this version of PHPUnit. Using these methods will trigger a deprecation warning in PHPUnit 8 and in PHPUnit 9 these methods will be removed.

**Comment by TomasVotruba** [comment]
AST integration in Rector for inspiration: https://github.com/rectorphp/rector/pull/825/commits/a59e35678ce16d9c3ea9c1f9116eb60553832d94#diff-d98925ff1d61912b3a56a882ffafeae3

One drawbacks is that `boolean`/`integer` are internaly converted to `bool`/`int`.

```diff
-$this->assertNotInternalType('bool', $value, 'message');
+$this->assertIsNotBool($value, 'message');

-$this->assertNotInternalType('boolean', $value, 'message');
+$this->assertIsNotBool($value, 'message');
```

**Comment by TomasVotruba** [comment]
@SpacePossum Could you elaborate on :confused: ?

**Comment by SpacePossum** [comment]
The linking to other tooling/project that use AST confuses (:confused:) me because this tool does not use AST, it works with tokens.

**Comment by TomasVotruba** [comment]
It's not about AST, it's about test case that you can copy while writing the fixer - https://github.com/rectorphp/rector/commit/a59e35678ce16d9c3ea9c1f9116eb60553832d94#diff-fb3d7cfa2c5b2dca79374f0551cbaeec

**Comment by SpacePossum** [comment]
I see now, thanks for the help!

**Comment by TomasVotruba** [comment]
Great! I'm glad it's clear :+1: . Free free to comment next time, if something I write seems confusing. I'm happy for feedback to improve my writing.
