### ISSUE TITLE
How can I run a custom rule set and standard?

### ISSUE THREAD

**Issue by burzum** [FriendsOfPHP/PHP-CS-Fixer#4151]
We have a `phpcs.xml` in our root that defines our rule set called "PSA". This is including `/vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml`. But whatever I do, php-cs-fixer doesn't apply these rules but seems to always running PSR2. How can I include and run our rule set?

#### The PHP version you are using (`$ php -v`):
λ php -v
PHP 7.1.15 (cli) (built: Mar  1 2018 02:04:08) ( NTS MSVC14 (Visual C++ 2015) x86 )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
λ .\bin\php-cs-fixer
PHP CS Fixer 2.13.1 Yogi's BBQ by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
.\bin\php-cs-fixer

#### The configuration file you are using, if any:
```php
<?php
$finder = PhpCsFixer\Finder::create()
	->in(__DIR__ . '/plugins')
	->in(__DIR__ . '/tests')
	->in(__DIR__ . '/src');

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRules(array(
        '@PSA' => true,
    ))
    ->setRiskyAllowed(true);
```

phpcs.xml

```xml
<?xml version="1.0"?>
<ruleset name="PSA">
	<rule ref="./vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml"/>
	<file>./src</file>
	<file>./tests</file>
	<file>./plugins/Psa/Cms/src</file>
	<file>./plugins/Psa/Cms/tests</file>
	<file>./plugins/Psa/MailingLists/src</file>
	<file>./plugins/Psa/MailingLists/tests</file>
	<exclude-pattern>*/tests/bootstrap.php</exclude-pattern>
	<exclude-pattern>*/config/Migrations/*</exclude-pattern>
</ruleset>
```

**Comment by ntzm** [comment]
You are getting confused between PHP-CS-Fixer and PHP_CodeSniffer :)

**Comment by kubawerlos** [comment]
> I thought it uses the same rules?

What made you think that? Is PHP_CodeSniffer or PHP CS Fixer projects mention anywhere that they can use the rules from each other?

When writing custom rule/fixer PHP_CodeSniffer requires implementing [`Sniff`](https://github.com/squizlabs/PHP_CodeSniffer/blob/3.3.2/src/Sniffs/Sniff.php) interface and for PHP CS Fixer you have to implement [`FixerInterface`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.13.1/src/Fixer/FixerInterface.php). I guess it would be possible to write some kind of bridge if you need such.

> I can't really find a documentation for all available rules either?

Where did you search? The list is in `README` file ;)

**Comment by burzum** [comment]
@kubawerlos the @<ruleset> confused me, I thought this is a better fixer than phpcbf but I've got this lib to work but it doesn't do a better job than phpcbf. But I like the code of this lib more. 😃 

I've read the readme.md indeed, just not all the way down. A suggestion to fix this is to move the looong list of options to one or more docs in the docs folder and keep the readme.md short. I personally like to point users to the docs folder and provide an index.md there that lists the topics. This might be an option here a well? But yes, my fault. 🤕

**Comment by keradus** [comment]
closing, as not an issue but request for explanation.
feel free to continue discussion even if ticket is closed, or use our gitter.im instead
