### ISSUE TITLE
can I run with --ignore-platform-reqs by default?

### ISSUE THREAD

**Issue by Nothing-Works** [FriendsOfPHP/PHP-CS-Fixer#4154]
Hi,
I know that php 7.3 is not supported. and I know I can run with `--ignore-platform-reqs`. however, I have [php cs fixer](https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer) installed in VsCode. 

And this is the configuration for it
`"php-cs-fixer.executablePathWindows": "C:\\Users\\{user}\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat",`

And now I can not use the plugin to auto format code as `--ignore-platform-reqs` is not added when vscode extention runs `PHP-CS-Fixer`. 

Anyone knows what's the workaround?

**Comment by keradus** [comment]
`--ignore-platform-reqs` is flag of Composer, not PHP CS Fixer. It's not needed to run PHP CS Fixer after installation.

PS closing the `Issue` as it's not an issue, but question for support. Feel free to continue discussion here, but it's suggested to move it to gitter channel.

**Comment by Nothing-Works** [comment]
@keradus I see, sorry about that. I will do my own research.

**Comment by Nothing-Works** [comment]
@keradus can I add `PHP_CS_FIXER_IGNORE_ENV=1` as default every time I run `PHP-CS-Fixer`?

**Comment by keradus** [comment]
You can add it to your profile envs
