### ISSUE TITLE
What is equivalent for this following rules?

### ISSUE THREAD

**Issue by zackijack** [FriendsOfPHP/PHP-CS-Fixer#4155]
based on StyleCI's preset, I get the following rules that I can't find in the PHP-CS-Fixer:

```
no_blank_lines_after_throw => Removes empty lines following a throw statement.
no_blank_lines_between_imports => Removes empty lines inbetween import use statements.
no_blank_lines_between_traits => Removes empty lines inbetween trait use statements.
phpdoc_type_to_var => @type should always be written as @var.
```

does anyone know how to implement the above rules in PHP-CS-Fixer?

**Comment by keradus** [comment]
styleci has some custom aliasing, eg `no_blank_lines_between_traits` is in fact `no_extra_blank_lines => ["tokens" => ["use_trait"]]`
to get help about custom aliases of external wrappers of PHP CS Fixer, ask support of that wrappers.
