### ISSUE TITLE
Q: Is there are rule to enforce single-line doc block for class properties?

### ISSUE THREAD

**Issue by nikolaposa** [FriendsOfPHP/PHP-CS-Fixer#4156]
For example, rule that should turn this:

```
class Foo 
{
    /**
     * @var string 
     */
    private $bar;
}
```

into this:
```
class Foo 
{
    /** @var string */
    private $bar;
}
```

**Comment by SpacePossum** [comment]
Hi, you might want to check out https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3810 :)

**Comment by nikolaposa** [comment]
@SpacePossum Yup, that's the one, thanks for the reference. I look forward to 2.14 release
