### ISSUE TITLE
ReturnAssignmentFixer - Ignore variable with PHPDoc @var tag

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#4157]
Suppose the following code:
```php
    public function foo(): string
    {
        return preg_replace(/* ... */);
    }
```

With this snippet, PHPStan would report that `foo()` returns `string|null` will it must return `string` because of the `preg_replace()` call. We could assign the result to a variable, throw an exception if the variable is `null` and return it otherwise. But we assume the `preg_replace()` call will never fail so instead we use a `@var` tag as follow:

```php
    public function foo(): string
    {
        /** @var string $foo */
        $foo = preg_replace(/* ... */);

        return $foo;
    }
```

This makes PHPStan happy but PHP CS Fixer unhappy when using the `return_assignment` rule. IMO, the rule should ignore such case. Not sure if this should be considered a bugfix, an enhancement or a new feature.

**Comment by SpacePossum** [comment]
Both tools are right as both do not (and cannot?) know that you are sure that `preg_replace` always returns an string here because of how it is called. I think it would be create to have an annotation for this to hint to PHPStan that you are sure of this fact and it should raise an warning.

**Comment by julienfalque** [comment]
> I think it would be create to have an annotation for this to hint to PHPStan that you are sure of this fact and it should not raise an warning.

That's the point of the added `@var` tag :)

**Comment by SpacePossum** [comment]
would be great to not have the single use `var` for the annotation only, like

```php
    public function foo(): string
    {
        /** @return string */  // this will likely never become a standard
        return preg_replace(/* ... */);
    }
```

or

```php
    public function foo(): string
    {
        /** @ignore phpstan\phpstan\[some name of a sniffer] */
        return preg_replace(/* ... */);
    }
```

:)

**Comment by kubawerlos** [comment]
> Not sure if this should be considered a bugfix, an enhancement or a new feature.

Definitely NOT a bugfix - I'd still prefer the `return_assignment` to fix it over false positive warning from PHPStan and add latter to ignored errors list.

**Comment by julienfalque** [comment]
Closing as adding the error to ignored errors list is probably the best way to go indeed.

**Comment by Wirone** [comment]
I got this problem when I type-hinted variable assignments (for static analysis) in repository implementation, which extends `EntityRepository`. I ended with overriding `find()` and `findOneBy()` signatures via `@method` on class level, so return types are more specific than in base methods.

**Comment by snake-py** [comment]
@Wirone can you point me where I can overwrite this? I have exactly the same issue.

**Comment by Wirone** [comment]
@snake-py hard to tell without seeing your code and exact problem you have. Also it was 3 years ago 🤷.  In general, if you need to add such workaround annotations, it means you most probably have some architectural flaws in the code.

PS. It's not a good place for such discussion 😉.

**Comment by BHSPitMonkey** [comment]
For what it's worth to anyone finding this thread now: Anonymous `@var` above a `return` statement (without creating a temporary variable) seems to work as expected in PHPStan these days, though it is [not explicitly documented](https://github.com/phpstan/phpstan/issues/7218#issuecomment-1172274655) anywhere that I've found.
