### ISSUE TITLE
Documentation don't specify what "binary operators" strings to use.

### ISSUE THREAD

**Issue by 9brada6** [FriendsOfPHP/PHP-CS-Fixer#4158]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.13.1 Yogi's BBQ by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> From VS Code, Format file

#### The configuration file you are using, if any:
```php
=>         // Set all styles to false.
        '@PSR1' => false,
        //'@Symfony'  => false,
        '@PSR2' => false,
        'align_multiline_comment' => [ 'comment_type' => 'phpdocs_like' ],
        'array_indentation' => true,
        'array_syntax'  => [ 'syntax' => 'long' ], 

        'binary_operator_spaces'  => [
            // 'align_double_arrow'    => true,
            // 'align_equals'          => false,
            
            'default'   => 'single_space',
            'operators' => [
                'double_arrow'  =>  'align',
            ]
        ],


        'braces' => array(
            'allow_single_line_closure' => true,
            'position_after_functions_and_oop_constructs' => 'same',
        ),
```

I will try to explain my problem in short:
In the documentation, at the binary_operator_spaces [@Symfony] paragraph it states that:
> operators (array): dictionary of binary operator => fix strategy values that differ from the default strategy; defaults to [],

However, If i try:
(this works)
```
        'binary_operator_spaces'  => [
            'default'   => 'single_space',
            'operators' => []
        ],
```
(don't work)
```
        'binary_operator_spaces'  => [
            'default'   => 'single_space',
            'operators' => [
                'double_arrow'  =>  'align',    //align_double_arrow also not working
            ]
        ],
```

It seems that i can't guess what the binary operators strings are. Can u add it in the documentation? Thanks!

**Comment by SpacePossum** [comment]
Hi @9brada6 ,

Thanks for the suggestion! There are multiple initiatives to create better docs because and I hope this will be included as well :)

For now, here is the current list of supported operators by the rule:

```php
    /**
     * @var string[]
     */
    private static $supportedOperators = [
        '=',
        '*',
        '/',
        '%',
        '<',
        '>',
        '|',
        '^',
        '+',
        '-',
        '&',
        '&=',
        '&&',
        '||',
        '.=',
        '/=',
        '=>',
        '==',
        '>=',
        '===',
        '!=',
        '<>',
        '!==',
        '<=',
        'and',
        'or',
        'xor',
        '-=',
        '%=',
        '*=',
        '|=',
        '+=',
        '<<',
        '<<=',
        '>>',
        '>>=',
        '^=',
        '**',
        '**=',
        '<=>',
        '??',
    ];

```

I think you look for something like:

```
        'binary_operator_spaces'  => [
            'default'   => 'single_space',
            'operators' => [
               '=>' => 'align_single_space_minimal'
           ]
        ],
```

**Comment by 9brada6** [comment]
Ah i see, that's cool, I love that it has a lot of customization. also after playing with this tool I want to say/request/problems i encountered: 
1. I can't make this to use some the Wordpress syntax for calling/declaring a function:
    I found 'no_spaces_inside_parenthesis' setting, but this won't let me to put only one space.
    test(     $arg )   ---will not convert-->  test( $arg )  
    see: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage
    There should be spaces also when calling an array with a variable as a key, $array[ $key ], this is too 
     much anyway.

2. I ( can't / didn't find option to )  disable the auto-indentation for formater. 
    I just want to use this tool for micromanagement, this I can do myself, also i usually use, and dont like being formated:
`echo'<div>;'
      echo 'Something';
echo </div>;
`

   The auto-indent seems to have a problem with if(): endif; syntax, for example if i wrote( default php-cs rules ):

```
<?php

function test1($arg1, $arg2){
	if( true ):
		$arg1 = 'asdfasdfag';
		$arg2 = $arg1 . 'asfdfas';
		$sdfds	= 'fdsfs';
		$sdfds	= 'fdsfs';
	else:
		$sdfds	= 'fdsfs';
		$sdfds	= 'fdsfs';	
	endif;
}

if( ! function_exists( 'test1' ) ):
	function test1( ){
	if( true ):
		$arg1 = 'asdfasdfag';
	elseif( true ):
		$arg2 = $arg1 . 'asfdfas';
	endif;		
	}
endif;

if( true ):
	$arg1 = 'asdfasdfag';
	$sdfds	= 'fdsfs';
elseif( true ):
	$arg2 = $arg1 . 'asfdfas';
	$sdfds	= 'fdsfs';
endif;
```

After formatting, I get:

```
<?php

function test1($arg1, $arg2)
{
    if (true):
        $arg1 = 'asdfasdfag';
    $arg2 = $arg1 . 'asfdfas';
    $sdfds	= 'fdsfs';
    $sdfds	= 'fdsfs'; else:
        $sdfds	= 'fdsfs';
    $sdfds	= 'fdsfs';
    endif;
}

if (! function_exists('test1')):
    function test1()
    {
        if (true):
        $arg1 = 'asdfasdfag'; elseif (true):
        $arg2 = $arg1 . 'asfdfas';
        endif;
    }
endif;

if (true):
    $arg1 = 'asdfasdfag';
    $sdfds	= 'fdsfs';
elseif (true):
    $arg2 = $arg1 . 'asfdfas';
    $sdfds	= 'fdsfs';
endif;
```

The if/endif is messed up, i didn't try the others like enforeach/endfor.
