### ISSUE TITLE
Merge ruleset from --config and --rules

### ISSUE THREAD

**Issue by bernhard-efler** [FriendsOfPHP/PHP-CS-Fixer#4170]
I think it would be a great feature to merge the ruleset provided by the config file with the ruleset set as command line argument.

I personally would need these feature to have a default ruleset in the config with the possibility to overwrite some rules for some some of our projects.
For example a different phpdoc header.

When I write a PR for this, how are the chances that it will get merged?

**Comment by kubawerlos** [comment]
So you would pass a header via command line?

Your use case is to extends some "general" configuration with project specific one, right?

I have similar situation and ended with a project's configuration like this:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules((require __DIR__.'/vendor/vendor-name/shared-cs-config/.php_cs')->getRules() + [
        '@PHP71Migration:risky' => true,
       // and whetever rules could not be set for all projets under a vendor
    ]);
```

**Comment by keradus** [comment]
not sure if you mean exactly this, but... https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2493/files#diff-305e1cb3821b99ed834e9968ee602ac0R155

> I personally would need these feature to have a default ruleset in the config with the possibility to overwrite some rules for some some of our projects.

so, instead of configuring them once, in config file per project, you would need to provide the config of rules each time you execute PHP CS Fixer?


> When I write a PR for this, how are the chances that it will get merged?

First, you would need to provide a specification how it shall work exactly. Topic is too wide to say one-sentence summary is enough

**Comment by bernhard-efler** [comment]
I know there is a warning and in v3 an exception!
That is the reason I'm asking before spending time in implementing something. Maybe there is an reason why both options can't used together.

My use case is that I have a whole bunch of repositories to manage, and to my php_cs config is in an separate repository to keep maintain easier. But I want to set a different header in each repository, and maybe some other changes in the ruleset.

The idea to achieve that is to define the base config over the config file and to be able to overwrite specific rules.

Possible solutions:
*) Allow --config and --rules simultaneously 
all rules define be --rules would extend/overwrite the rules defined in the config. All rules with value === null will be removed.
example: php-cs-fixer.phar fix --config path/to/config --rules='{"concat_space": {"spacing": "none"}}'
*) Allow multiple --config arguments
Merge the config files in the order they are applied. The later one overwrites the one before.
The rules of merging are the same as above

**Comment by keradus** [comment]
> But I want to set a different header in each repository, and maybe some other changes in the ruleset.

that's pretty good and valid example, most of nicely maintained repositories have config like that, see our config for example, or any Symfony based ones:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.13/.php_cs.dist#L18
1. Add standard ruleset, for us it's our one, for Sf it's Sf one.
2. Add ruleset for version of your language
3. Add ruleset for version of your PHPUnit, if you are using it
4. configure header, if wanted
5. add custom rules, if needed

> The idea to achieve that is to define the base config over the config file and to be able to overwrite specific rules.

You can overwrite them directly in config file, as you showed ;)
Point is, if you overwrite it via command line, you need to share the command line with all ppl contributing to repo, and if one forgot to run that special command, he would just use config file, it would mess up the CS of repo...

---------------------

> *) Allow --config and --rules simultaneously
all rules define be --rules would extend/overwrite the rules defined in the config. All rules with value === null will be removed.

how to set does one want to totally overrite all ruleset defined in config with ruleset defined via CLI arg or merge them together? if merging, which definition for rule would be taken into consideration, one from file or arg? what if we have `[example_rule=>[option_a => true]]` vs `[example_rule=>[option_b => true]]` ? combine all options or set only one of them? what's the difference between setting the rule to `null` vs `false` ?

> *) Allow multiple --config arguments
Merge the config files in the order they are applied. The later one overwrites the one before.
The rules of merging are the same as above

what if 2 config files are conflicting?
one say to fix fileA.php, one to omit fileA.php.
one say to use short syntax, one to use long syntax for arrays.
amount of possible conflicts are impossible to manage.


For all that reasoning, I have decided (already, ages ago) to remove little functionallity we have originally and to not bring ones you are mentioning - as even in very simple form we had implemented, it was way confusing for users to decide what would be the outcome ruleset.
As said on very beginning, suggested way of configuring is via config file, that can be easily shared via repo.

Saying that, I'm closing the ticket - yet, feel free if you want to continue discussion. Nothing is written in stone, if you will provide nice solution that would get applause of the ppl, my decision may change ;)
