### ISSUE TITLE
Delay before woking 

### ISSUE THREAD

**Issue by GrCOTE7** [FriendsOfPHP/PHP-CS-Fixer#4174]
Hi, all

Is there possible to set a delay (i.E. 1000 ms) for this script begins to work ?

Or either, the possibility that it works only after n ( 5 or 10 i.e.) changes, but not for each change ?

**Comment by SpacePossum** [comment]
Hi @GrCOTE7 

The tool runs whenever you want it to run so you've full control :) Maybe you are running the tool using some plugin that makes it run an every change you make?

**Comment by keradus** [comment]
To fulfill the picture - PHP CS Fixer has no functionality of "watch" changes in live mode, count changes or sth like that. It's functionality of your IDE or sth.

Closing as this is not question related directly to this repo. Feel free to continue the discusion, even after closing!
