### ISSUE TITLE
Brackets in the same line

### ISSUE THREAD

**Issue by onorax** [FriendsOfPHP/PHP-CS-Fixer#4227]
How can i config PHP CS Fixer to fix with the brackets in te same line, like this:

```
class Email extends model{
      function name_function(){
      }
}
```

now the extension is doing like this
```
class Email extends model
{
      function name_function()
      {
      }
}
```

**Comment by limminho** [comment]
In my opinion, you may add some options under 'braces' in ```.php_cs``` file.
```
'braces' => array(
            'allow_single_line_closure' => true,
            'position_after_control_structures' => 'same',
            'position_after_functions_and_oop_constructs' => 'same',
        ),
```

**Comment by SpacePossum** [comment]
Hi @onorax ,

Currently we do not have this option. I doubt we'll add it as it is not a wide use standard now in the PHP ecosystem, or do you know a community that uses this style?
