### ISSUE TITLE
ModernizeTypesCastingFixer - breaks operator precedence

### ISSUE THREAD

**Issue by guilliamxavier** [FriendsOfPHP/PHP-CS-Fixer#4239]
`[]` and `**` have higher precedence than `(TYPE)` casts (http://php.net/manual/en/language.operators.precedence.php).

#### The PHP version you are using (`$ php -v`):
=> 7.2.10

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.12.6 (same issue with 2.13.3 and 2.14.0)

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix -vvv --using-cache=no --rules=modernize_types_casting --allow-risky=yes sample.php`

#### The configuration file you are using, if any:
(none)

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

$x = 42;
$y = strval($x)[0]; // ***
var_dump($y);

$x = 3.25;
$y = intval($x)**2; // ***
var_dump($y);
```
=> output (`$ php sample.php`):
```
string(1) "4"
int(9)
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

$x = 42;
$y = (string) $x[0]; // ***
var_dump($y);

$x = 3.25;
$y = (int) $x**2; // ***
var_dump($y);
```
=> new output:
```
string(0) ""
int(10)
```

 * with the changes you expected instead:
```php
<?php

$x = 42;
$y = ((string) $x)[0]; // ***
var_dump($y);

$x = 3.25;
$y = ((int) $x)**2; // ***
var_dump($y);
```
=> (output: same as original)

**Comment by SpacePossum** [comment]
thanks for reporting @guilliamxavier
