### ISSUE TITLE
NoUnsetCastFixer - breaks higher-precedence operators and some side effects

### ISSUE THREAD

**Issue by guilliamxavier** [FriendsOfPHP/PHP-CS-Fixer#4241]
#### The PHP version you are using (`$ php -v`):
=> 7.2.10

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14.0

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix -vvv --using-cache=no --rules=no_unset_cast sample.php`

#### The configuration file you are using, if any:
(none)

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

Given (don't mind the compact style):

```php
<?php

function f($x) {
    var_dump($x); // note: side effect
    return $x;
}
class C {
    public static function sf($x) { return f($x); }
    public function mf($x) { return f($x); }
}
class A extends ArrayObject {
    public function offsetGet($x) { return parent::offsetGet(f($x)); }
}

$f = 'f';
$c = new C();
$a = new A([42]);
$n = 3;
$i = 0;
```

then the following are correctly preserved:

| before | after |
| --- | --- |
| `$r = (unset) f(1);` | (no change) |
| `$r = (unset) C::sf(2);` | (no change) |
| `$r = (unset) (new C())->mf(3);` | (no change) |

but the following are not:

| before | after | problem |
| --- | --- | --- |
| `$r = (unset) $f(1);` | `$r =  null(1);` | Fatal error |
| `$r = (unset) $c::sf(2);` | `$r =  null::sf(2);` | Fatal error |
| `$r = (unset) $c->mf(3);` | `$r =  null->mf(3);` | [not applied because of] Parse error |
| `$r = (unset) $a[0];` | `$r =  null[0];` | lost side effect (`$a->offsetGet(0)`) |
| `$r = (unset) $n**f($n);` | `$r =  null**f($n);` | `$r` = `0` instead of `null` |
| `$r = (unset) $i++;` | `$r =  null++;` | [not applied because of] Parse error |

**Comment by SpacePossum** [comment]
@guilliamxavier thanks for reporting, good find!
Do you plan on proposing a fix through a PR? I might give it a shot but I'm also kind of busy so please let me know :)

**Comment by SpacePossum** [comment]
thanks for the details @guilliamxavier :)

I give it a try soon, checking if after the variable is either `;` or `?>` seems the easiest to do. It will still cover the most common cases.

```
(By the way, in all cases, replacing (unset) $x with null might also hide a notice if $x was not defined :/)
```

indeed, however dealing with that edge case is pretty hard in this project (lack of AST), however I'm not sure it worth tagging the fixer as `risky` for it (however if people want it than that is fine by me)
