### ISSUE TITLE
/** @var Classname **/ gets lowercased

### ISSUE THREAD

**Issue by wuestkamp** [FriendsOfPHP/PHP-CS-Fixer#4248]
#### The PHP version you are using (`$ php -v`):
PHP 7.2.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.13.0 Yogi's BBQ

#### The command you use to run PHP CS Fixer:
./bin/php-cs-fixer fix -vv --config=./.php_cs

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->notPath('vendor')
    ->in('src')
    ->name('*.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRiskyAllowed(false)
    ->setRules([
        '@Symfony' => true,
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => ['align_equals' => false, 'align_double_arrow' => false],
        'ordered_imports' => true,
        'phpdoc_order' => true,
    ]
);

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    /**
     * @var Donation
     *
     * NOT PERSISTED - used in a single request only for processing.
     */
    protected $donation;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    /**
     * @var donation
     *
     * NOT PERSISTED - used in a single request only for processing
     */
    protected $donation;
```

 * with the changes you expected instead:
```php
    /**
     * @var Donation
     *
     * NOT PERSISTED - used in a single request only for processing.
     */
    protected $donation;
```

So why does the `Donation` class gets lowercased?
And the dot gets removed, this might be on purpose though?

Thanks,
Kim

**Comment by ntzm** [comment]
[Confirmed](https://php-cs-fixer-playground.herokuapp.com/run/450697c8-4f80-458c-85c0-5a90358e9f0f). It's `phpdoc_annotation_without_dot` that's doing it.

**Comment by wuestkamp** [comment]
@ntzm thanks, but then its weird because this one is not touched and remains unchanged (in the same file):

```
    /**
     * NOT PERSISTED - used in a single request only for processing.
     */
    protected $cardNumber;
```

So the dot is not removed from ANY other comment. Just in this case.

**Comment by kubawerlos** [comment]
For the comment:
```
    /**
     * @var donation
     *
     * NOT PERSISTED - used in a single request only for processing
     */
```
`DocBlock` will treat all 3 meaningful lines as single annotation - as we assume summary and description of doc block suppose to be at he [beginning](http://docs.phpdoc.org/references/phpdoc/basic-syntax.html#sections).

So, the doc block contain 1 annotation with should not be sentence - thus lowercasing first letter and removing trailing dot.

**Comment by wuestkamp** [comment]
@kubawerlos thanks! putting description at the beginning solves this. That's how it should be O:)
For me we can close this.

**Comment by SpacePossum** [comment]
closing as the reporter stated it could :)
