### ISSUE TITLE
Install problems with composer

### ISSUE THREAD

**Issue by cswgr** [FriendsOfPHP/PHP-CS-Fixer#4265]
#### The PHP version you are using (`$ php -v`):
=> 5.6.38

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14

---

I'm trying to install php-cs-fixer via composer using this:

```bash
composer require --dev friendsofphp/php-cs-fixer
```

I don't want to install it globally, but per project.

So when I try I get this error:

```bash
Problem 1
    - symfony/console v4.2.2 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.2.1 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.2.0 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.1.9 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.1.8 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.1.7 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.1.6 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - symfony/console v4.1.10 requires php ^7.1.3 -> your PHP version (5.6.38) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer ^2.14 -> satisfiable by friendsofphp/php-cs-fixer[v2.14.0].
    - Conclusion: remove symfony/console v3.4.8
    - Conclusion: don't install symfony/console v3.4.8
    - friendsofphp/php-cs-fixer v2.14.0 requires symfony/console ^3.4.17 || ^4.1.6 -> satisfiable by symfony/console[v3.4.17, v3.4.18, v3.4.19, v3.4.20, v3.4.21, v4.1.1
0, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2].
    - Can only install one of: symfony/console[v3.4.17, v3.4.8].
    - Can only install one of: symfony/console[v3.4.18, v3.4.8].
    - Can only install one of: symfony/console[v3.4.19, v3.4.8].
    - Can only install one of: symfony/console[v3.4.20, v3.4.8].
    - Can only install one of: symfony/console[v3.4.21, v3.4.8].
    - Installation request for symfony/console (locked at v3.4.8) -> satisfiable by symfony/console[v3.4.8].
```

As you see, there is this condition:

```
friendsofphp/php-cs-fixer v2.14.0 requires symfony/console ^3.4.17 || ^4.1.6 -> satisfiable by symfony/console[v3.4.17, v3.4.18, v3.4.19, v3.4.20, v3.4.21, v4.1.1
```

So the latest version possible for me because of php 5.6 is symfony/console is 3.4.21, which I tried to install with composer.

Problem is, it downgrades a lot of other libs, which is partially fatal for our project.

I know I should upgrade to php 7, but at the moment it's not possible.
On the other hand php-cs-fixer installation works if I install it globaly with composer.

How does it work? Can I somehow force it to be installed locally?

**Comment by kubawerlos** [comment]
You may want to look at this: https://phar.io/

**Comment by cswgr** [comment]
Thanks, but "PHIVE is still under heavy development".
I'd rather continue to use composer.

Maybe a different idea, anyone? 😬

**Comment by dmvdbrugge** [comment]
create a sub-dir "dev-tools", and _inside of it_ do `composer init && composer require --dev friendsofphp/php-cs-fixer`.

That would require you to run it as `dev-tools/vendor/bin/php-cs-fixer`, and also require you to keep 2 composer installs up to date, but you could solve _that_ by using a `Makefile`.

**Comment by keradus** [comment]
even we are using `dev-tools` approach:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.14/dev-tools/composer.json ,
but really, don't be afraid to switch to PhiVE. It's written by great guys, eg creator of PHPUnit. One day, you will experience conflicts of your dev tools, same as you have experienced it now inside main composer file.

**Comment by keradus** [comment]
I am closing this issue as it has been answered and it is more a support request than issue report/feature request.
If you are willing to, feel free to continue discussion here or on our [gitter](https://gitter.im/PHP-CS-Fixer/Lobby) channel.
