### ISSUE TITLE
NoSuperfluousPhpdocTagsFixer removes "@return null" tags

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#4269]
The `no_superfluous_phpdoc_tags` removes `@param`/`@return` tags with only `null` as type. Those tags shouldn't be removed: they can't be superfluous because `null` can't be used as a type declaration.

```diff
 /**
- * @param null $foo
- * @return null
  */
 function foo($foo)
 {
     return null;
 }
```

**Comment by dmvdbrugge** [comment]
However what is the actual use of these params/returns? If an argument accepts only null, why is it an argument to begin with? If it only returns null, why return anything at all? And if they were changed into that for some reason later on there should be a description _why_ and then it's not superfluous anymore.

**Comment by dmvdbrugge** [comment]
That's not what I'm talking about, because what you're describing should not be hinted as `@return null` in the first place, as you're not returning null. You're returning "X or null" which because of implementation happens to always be null.

In that case your doc block should still be `@return X|null` and not `@return null`.

**Comment by julienfalque** [comment]
My use case for `@return null` is a Behat context with some methods annotated with `@Transform` to convert string values from the scenarios into PHP values. One of this method converts the string `null` into PHP's `null`. On the project, the PHPStan strict rule that requires parameter and return type declarations is enabled and complains that the method has no return type declaration. As declaring that a function only returns `null` is not possible, a `@return null` annotation is needed, but PHP-CS-Fixer removes it unless I add a dummy description to it.

I don't have a use case for a `@param null` annotation, I just noticed that the behavior of the fixer was the same.

**Comment by dmvdbrugge** [comment]
I see. However, I wouldn't consider this a bug. I'd say it's a feature request, just like there recently was a PR merged that allows `mixed` to not be considered superfluous.

**Comment by julienfalque** [comment]
I tend to disagree. In the initial implementation, considering `mixed` as always superfluous was intended. `null` is an edge case I didn't think about but I would have handled it as *never* superfluous. Though I'm not against considering this a new feature (with a opt-in configuration option) or an enhancement (no configuration option).
