### ISSUE TITLE
Directive `single_blank_line_at_eof` doesn't work as expected.

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#4297]
Hi,

I was trying to make sure that all the files in my project were ending with a blank line at the end (`single_blank_line_at_eof` directive) and I noticed that this tool doesn't detect and fix the directive properly.

Apparently it does it properly for `.php` files, but not for `.yml` files.

See this repository that highlight the issue: https://github.com/drupol/issue-4297-php-cs-fixer

**Comment by julienfalque** [comment]
PHP CS Fixer was never intended to process any files but PHP ones. The behavior you are describing is expected.

**Comment by drupol** [comment]
So sad, I was looking for a solution to completely replace phpcs with php-cs-fixer.

**Comment by keradus** [comment]
well, we are not YML CS Fixer or Anything CS Fixer.
one tool to do one thing, but good.

**Comment by drupol** [comment]
Make sense anyway. Thanks for the support guys, keep up the good work.
