### ISSUE TITLE
Class Paddings

### ISSUE THREAD

**Issue by zored** [FriendsOfPHP/PHP-CS-Fixer#4304]
Here is a little feature request: add padding rules (blank line, new line, etc.) for fields and functions inside of classes.

Before:
```php
class Foo {

    use Bar;
    private $baz1;
    private $baz2;
    function qux(){}

}

```

After:
```php
class Foo {
    use Bar;

    private $baz1;
    private $baz2;

    function qux(){}
}

```

What do you think about it?
I can try and implement it here.

**Comment by dmvdbrugge** [comment]
Check out `class_attributes_separation`, it's already there 😉

**Comment by SpacePossum** [comment]
@zored please check the answer of @dmvdbrugge and please let us know if that (doesn't) works for you :)
