### ISSUE TITLE
Multiline arrays with leading commas.

### ISSUE THREAD

**Issue by adjenks** [FriendsOfPHP/PHP-CS-Fixer#4308]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=>  7.1.26

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.14.1 Sunrise by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> fix

I cannot seem to find any configuration possible to properly format arrays with leading commas.
I like to write arrays with leading commas. For example:
```
$rules = [
	'@PSR2' => true
	,'@PHP71Migration' => true
	,'@PhpCsFixer' => true
	,'array_syntax' => ['syntax' => 'short']
	,'no_whitespace_before_comma_in_array' => false
	,'multiline_array_trailing_comma' => false
	,'single_quote' => true
];
```
But there is no option to convert multi-line arrays that are trailing commas into leading commas. Not that I can see. Am I missing it? If not. I would like to request this feature. Thank you.

**Comment by julienfalque** [comment]
I really don't like this syntax so I'd be against such feature, but that's my opinion.

**Comment by adjenks** [comment]
A lot of people like leading commas. We're the minority, but a reasonable number of people. Someone did some simple research on leading/lagging commas: https://hackernoon.com/winning-arguments-with-data-leading-with-commas-in-sql-672b3b81eac9

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/53570160-cc4e4b00-3ba0-11e9-955b-1e9f742ff780.png)

With the article you provided, in SQL grammar, adding a comma at the red circle is simply **illegal** so people have no choice to keep consistency with an extra trailing comma. For people who loves consistency they may use leading comma then.

While in PHP, trailing comma in an array is legal and [recommended in PSR-2](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#multi-line-arrays) but well, not forced indeed.

I think the thing I actually love is consistency. Neither a leading comma nor a trailing comma. It's just in this case, a leading comma has no consistency.

**Comment by SpacePossum** [comment]
Thanks @adjenks for the question.

We like to promote standards (like PSR2) for consistency through out communities projects. I think you suggestion is not a wide use standard and therefore I'm closing this request.

Please let me know if I'm wrong, I don't know all the communities out there after all :)
