### ISSUE TITLE
add configuration for strict_comparison => strings

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#4317]
The [strict_comparison](https://mlocati.github.io/php-cs-fixer-configurator/#fixer:strict_comparison) is nice fixer, but by default it is considered risky.

Please add configuration, that applies only if the equation is done with non-empty constant strings. in that case, the result is interchangeable.

non-safe:
```php
		if ("a" == '') {
			return;
		}
```

safe:
```php
		if ("a" == 'aaa') {
			return;
		}
		if ($baz == 'aaa') {
			return;
		}
		if ($barf != 'aaa') {
			return;
		}
		if (some_method() == 'aaa') {
			return;
		}
```

proposed config:

```php
    'strict_comparison' => ['strings'],
```

**Comment by keradus** [comment]
> non-safe: `"a" == ''`

why it's not safe to use `===` here ?

> safe: `$baz == 'aaa'`

it's not safe. https://3v4l.org/LDW2G

**Comment by glensc** [comment]
i made the bugreport how phpstorm suggested to make changes. did not give deep thought on the scenarios.

but the thing is, there exist scenarios which are safe to convert to `===` and php-cs-fixer could apply those.

**Comment by glensc** [comment]
not sure how much php-cs-fixer is able to get from context, is it able to deduce that the `$baz` is object rather scalar?

if not then php-cs-fixer probably can only do safe replacements when both sides are constants, i.e assigned with clear value within scope.

**Comment by keradus** [comment]
no, it can't.

tbh, i'm not seeing the effort worth to make this change happen - if dev is not using `===` at all, applying this change only to `string literal vs string literal` won't help him a lot, and to be honest, nobody writes conditions like `"foo" === "foo"`...

**Comment by glensc** [comment]
yeah, i realized too, if php-cs-fixer is not able to detect type of variable (via native or phpdoc type hints), this can't be implemented...
