### ISSUE TITLE
Integration with Ant build script

### ISSUE THREAD

**Issue by sdaoudi** [FriendsOfPHP/PHP-CS-Fixer#4326]
Would you accept a PR to support the generation of a report based on the chosen format (txt by default)?

**Comment by SpacePossum** [comment]
HI @sdaoudi, 

Thanks for asking :)
Currently we support something like:

```bash
[10:53 AM]-[possum@zoo4]-[~/work/PHP-CS-Fixer]-[git 2_14_concat] 
$ php php-cs-fixer fix test.php --dry-run --format checkstyle
```
(and `txt` (default one), `json`, `xml` and `junit`)

Which produces something like:
```
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
  <file name="test.php">
    <error severity="warning" source="PHP-CS-Fixer.class_definition" message="Found violation(s) of type: class_definition"/>
    <error severity="warning" source="PHP-CS-Fixer.no_extra_blank_lines" message="Found violation(s) of type: no_extra_blank_lines"/>
    <error severity="warning" source="PHP-CS-Fixer.braces" message="Found violation(s) of type: braces"/>
    <error severity="warning" source="PHP-CS-Fixer.header_comment" message="Found violation(s) of type: header_comment"/>
  </file>
</checkstyle>
```

Which can be written to file (as we separate the `xml` output and the rest using stdout and stderr).
Is this sufficient for you use case?

**Comment by sdaoudi** [comment]
Hi @SpacePossum, 

Thank you for this informations. It was already worked for me on the command line, but I have a problem with my Ant build script, when I use the output argument (of Ant), my output file contains the stdout and the stderr messages.

That's why I thought about creating a new input option with the report path.

**Comment by SpacePossum** [comment]
Hi thanks for the background,

I haven't work with ant for a while I'm afraid, so please forgive me if this is not on topic. but maybe splitting the outputs would work?

**Comment by sdaoudi** [comment]
Yes, I will try to find how to split Ant outputs.
Thanks @SpacePossum for your time.

**Comment by sdaoudi** [comment]
Hi @SpacePossum,

Issue resolved using Ant doc:

- output: Name of a file to which to write the output. If the error stream is not also redirected to a file or property, it will appear in this output
- error: The file to which the standard error of the command should be redirected. since Ant 1.6

Before:
`<target name="phpcs">
  <exec executable="php" output="${basedir}/build/logs/checkstyle.xml">
   <arg value="${basedir}/bin/php-cs-fixer" />
   <arg value="fix" />
   <arg value="--dry-run" />
   <arg value="--no-interaction" />
   <arg value="--format=checkstyle" />
  </exec>
 </target>`

After:
``<target name="phpcs">
  <exec executable="php" output="${basedir}/build/logs/checkstyle.xml" **_error="${basedir}/build/logs/checkstyle.log"_**>
   <arg value="${basedir}/bin/php-cs-fixer" />
   <arg value="fix" />
   <arg value="--dry-run" />
   <arg value="--no-interaction" />
   <arg value="--format=checkstyle" />
  </exec>
 </target>``

Thank you @SpacePossum

**Comment by SpacePossum** [comment]
thanks for reporting back @sdaoudi , great to hear you got it working :)
