### ISSUE TITLE
Changing indent doesn't invalidate cache

### ISSUE THREAD

**Issue by simon-tma** [FriendsOfPHP/PHP-CS-Fixer#4330]
#### The PHP version you are using (`$ php -v`):
=> `7.3.2`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `2.14.0 Sunrise`

Changing the indent style by changing (or initially setting) the value passed to `setIndent()` doesn't invalidate the cache, thus requiring either bypassing the cache or changing one of the rules to be able to get the indentation change to apply.

**Comment by SpacePossum** [comment]
Thank for reporting,

This seems like a bug to me, when we calculate the cache signature we should also take these into account:
- `getIndent`
- `getLineEnding`

(i.e.`PhpCsFixer\ WhitespacesFixerConfig`)
