### ISSUE TITLE
Add no_root_imports fixer

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#4347]
With this fixer, an import such as `use PDO;` would be removed and all references to `PDO` in that file would be replaced with `\PDO`. Root imports are those which do not contain a backslash (`\`) character, excluding the first. The following are root imports:

* `PDO`
* `\PDO`

The following are not root imports:

* `Foo\Bar`.

The rationale behind this fixer is to make it clear, when reading the code, whether the built-in implementation is used or a custom implementation. That is, when code follows the *no root imports* style, we can be confident that code occurences of `\PDO` refer to the standard implementation, and `PDO` refers to a custom implementation, because PHP built-in classes are not namespaced.

**Comment by SpacePossum** [comment]
done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4355
