### ISSUE TITLE
Multi blank lines between functions

### ISSUE THREAD

**Issue by Mushr0000m** [FriendsOfPHP/PHP-CS-Fixer#4359]
Hi, I'm not sure if this is the right place to ask this question, but here it is. We have a small team and want to use PHP-CS-Fixer to format all our code but we have custom standards rules, like 2 blank line arround functions for readability (except first one and last one of a class). I read the doc but only saw rules with `true` or `false` so I'm not sure PHP-CS-Fixer is made for our needs.

Can we write this kind of rules ?

**Comment by SpacePossum** [comment]
Hi @Mushr0000m 

Within the project we try to promote standards used by bigger PHP communities and for that we provide rules to help format code following those standards.

You question is about a format that is not very common and therefore we've no rule that will do this for you. However, you can write you own rules and use these custom rules with the tool.
There are a bunch of projects on github that do this already. You can use the rules in this project as example or any of the other projects out there. Maybe have a look at the [cook book](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.14.2/doc/COOKBOOK-FIXERS.md) on this topic as well if it helps.

I'm closing this ticket now as to not raise expectations that we'll add this rule soon. However if there are more people that would like to see this rule added; please let me know!

**Comment by r8928** [comment]
Hi @Mushr0000m, I use same rule in my projects too :). Any luck with the custom rule?

**Comment by Mushr0000m** [comment]
No sorry I didn't find a way so I dropped PHP-CS-Fixer for the moment.... If you find a way to create theses custom rules, please tell me !
