### ISSUE TITLE
MethodChainingIndentationFixer: Taking too long (possible unnecessary loop)

### ISSUE THREAD

**Issue by Billz95** [FriendsOfPHP/PHP-CS-Fixer#4363]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.3.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15.0-DEV

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix --verbose --diff  --rules=method_chaining_indentation --dry-run largeFolder

### Issue
When running the `method_chaining_indentation` rule over large number php files, especially where each php file is large, it tends to take a long time. (e.g. 90 seconds for 7500 files)

I looked into the code and found a suspicious loop in function `MethodChainingIndentationFixer::getIndentContentAt`

```php
    private function getIndentContentAt(Tokens $tokens, $index)
    {
        for ($i = $index; $i >= 0; --$i) {
            if (!$tokens[$index]->isGivenKind([T_WHITESPACE, T_INLINE_HTML])) {
                continue;
            }

            $content = $tokens[$index]->getContent();

            if ($tokens[$index]->isWhitespace() && $tokens[$index - 1]->isGivenKind(T_OPEN_TAG)) {
                $content = $tokens[$index - 1]->getContent().$content;
            }

            if (Preg::match('/\R/', $content)) {
                return $content;
            }
        }

        return '';
    }
```

This loops lines of code that doesn't seem to have any side effects, while the `$i` is not used at all. I'm suspecting whether we really need to loop this code this many times? 

I removed the loop and the unit test seems to be fine. And removing the loop decrease the 90 seconds runtime over 7500 files to **only <30 seconds**

**Comment by julienfalque** [comment]
Indeed, the loop looks unecessary. Do you mind creating a pull request?

**Comment by Billz95** [comment]
> Indeed, the loop looks unecessary. Do you mind creating a pull request?

Sure thing, I'll make one for 2.12 :D
