### ISSUE TITLE
problem with multiline conditions

### ISSUE THREAD

**Issue by aapodolskiy** [FriendsOfPHP/PHP-CS-Fixer#4371]
#### The PHP version I am using (`$ php -v`):
> PHP 7.2.11 

#### PHP CS Fixer version I am using (`$ php-cs-fixer -V`):
> PHP CS Fixer 2.14.2 Sunrise by Fabien Potencier and Dariusz Ruminski

#### The command I use to run PHP CS Fixer:
> php-cs-fixer fix --config=.php_cs.php test.php

#### The configuration file I am using is `.php_cs.php`:
```php
<?php 
 
return PhpCsFixer\Config::create()
  ->setIndent('  ')
  ->setRules([
    'braces' => true,
    'indentation_type' => true,
  ])
  ;
```

#### file test.php:
 * before running PHP CS Fixer (no changes):
```php
<?php

if (true) {
  $a = $b = 1;
  if (true) {
    if (
      $a ||
      $b
    ) {
      echo '1';
    }
  }
}
```

 * after usage of PHP CS Fixer:
```php
<?php

if (true) {
  $a = $b = 1;
  if (true) {
    if (
    $a ||
    $b
  ) {
      echo '1';
    }
  }
}
```

 * after one more usage of PHP CS Fixer:
```php
<?php

if (true) {
  $a = $b = 1;
  if (true) {
    if (
  $a ||
  $b
  ) {
      echo '1';
    }
  }
}
```

As one can see, running PHP CS Fixer destroyed spaces in inner `if` condition and braces.

**Comment by SpacePossum** [comment]
I tried this again on latest with `braces` and the code seems to be fixed properly now, suggest closing this ticket.
