### ISSUE TITLE
Add support for PHP 7.4 property types

### ISSUE THREAD

**Issue by ircmaxell** [FriendsOfPHP/PHP-CS-Fixer#4372]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.4 - master

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15.0-DEV

#### The command you use to run PHP CS Fixer:
```console
$ PHP_CS_FIXER_IGNORE_ENV=true php-7.4 vendor/bin/php-cs-fixer fix --allow-risky=yes
```

#### The configuration file you are using, if any:
not relevant

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class Foo {
    public int $bar;
}

$foo = new Foo;
$foo->bar = 12;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
 
declare(strict_types=1);

class Foo
{
    public int

 public $bar;
}
 
$foo = new Foo();
$foo->bar = 12;
```

 * with the changes you expected instead:
```php
<?php

declare(strict_types=1);

class Foo
{
    public int $bar;
}

$foo = new Foo();
$foo->bar = 12;
```

This doesn't actually change the file (it fails linting), but that also means it is unable to fix any code targetting PHP 7.4.

**Comment by SpacePossum** [comment]
Thanks for reporting!
We didn't start with PHP7.4 support yet, but is high on the agenda of course :)

**Comment by julienfalque** [comment]
I'm closing as this is now tracked by #4382, thanks for reporting.
