### ISSUE TITLE
Check only changed lines

### ISSUE THREAD

**Issue by slashsbin** [FriendsOfPHP/PHP-CS-Fixer#4374]
Hi,
We are running php-cs-fixer in a Gitlab CI job like this:
```bash
php-cs-fixer fix --config=.php_cs.dist --verbose --dry-run --using-cache=no \
    --path-mode=intersection --diff -- $(git diff --name-only \
        --diff-filter=ACMRTUXB HEAD~..HEAD)
```
This is working great, but checks all lines of all changed files between commit range `HEAD~..HEAD`.

Is there a way to limit php-cs-fixer to report only violations of changed lines?

**Comment by localheinz** [comment]
Have you seen https://github.com/FriendsOfPHP/PHP-CS-Fixer#using-php-cs-fixer-on-ci?

**Comment by slashsbin** [comment]
Yes, that checks changed files between commit range `$COMMIT_RANGE` just fine, but we need to limit that further to changed lines.
Any idea how to do that?

**Comment by SpacePossum** [comment]
Hi,

The tool works on a file level scope and it would be incredibly hard to work on line level as some of the rules move lines around, remove lines and/or insert lines, etc.

**Comment by tyd** [comment]
@slashsbin did you ever find a solution for checking only changed lines?

**Comment by dozer111** [comment]
> @slashsbin did you ever find a solution for checking only changed lines?

command: `php ./vendor/bin/php-cs-fixer fix --using-cache=no --config .php-cs-fixer.dist.php  --diff --allow-risky=yes --path-mode=intersection -- $(git diff --name-only  --diff-filter=ACMRTUXB $(git cherry origin/master | head -1 | awk '{print $2}')..HEAD)`

or alias:
```bash
# /etc/bash.bashrc

function ff(){
	php ./vendor/bin/php-cs-fixer fix --using-cache=no --config .php-cs-fixer.dist.php  --diff --allow-risky=yes --path-mode=intersection -- $(git diff --name-only  --diff-filter=ACMRTUXB $(git cherry origin/master | head -1 | awk '{print $2}')..HEAD)
}
export -f ff
```

**Comment by slashsbin** [comment]
@tyd no not really. and my understanding is that this is not possible with the current implementation.
The tool, by design, looks at the PHP files in a single context as a whole thing.
