### ISSUE TITLE
php-cs fixer removes doctrine syntax

### ISSUE THREAD

**Issue by hajar-jobtip** [FriendsOfPHP/PHP-CS-Fixer#4387]
#### The PHP version you are using
7.2.15

I am using  "arubacao/php-cs-fixer-config": "^0.2.0",
When i run
`bin/php-cs-fixer fix ./ --config=vendor/arubacao/php-cs-fixer-config/laravel.php_cs -vv`

It removes doctrine comments from `/** */` to `/*  */`
Is there a solution to use php cs fix and have doctrine working

**Comment by kubawerlos** [comment]
Please share a snippet of code that is causing the problem.

**Comment by hajar-jobtip** [comment]
Here is my file but that don't cause the problem. 
[code snippet](https://gist.github.com/hajar-jobtip/2a3b4ad679f58c885ae9ee3a278db744#file-example-php)
Could have anything to do with `arubacao/php-cs-fixer-config`

**Comment by kubawerlos** [comment]
> Here is my file but that don't cause the problem.

Please share a snippet of code **that is** causing the problem.

The one you pasted is changed to comment as it is not followed by any code.

**Comment by SpacePossum** [comment]
I'm closing here because we didn't get the details from the reporting to continue working on this. Happy to reopen for investigation if new details are provided.
