### ISSUE TITLE
[Question] Class comment personal doc block

### ISSUE THREAD

**Issue by noniagriconomie** [FriendsOfPHP/PHP-CS-Fixer#4388]
Hi,
I would like to know if there is a config to disable the removal of this, I've searched but did not found :/

=> php 7.2.16 (Mac os with brew)
=> PHP CS Fixer 2.14.2 Sunrise
=> php-cs-fixer fix src

```php
<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

return Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'lowercase_constants' => true,
        'native_function_casing' => true,
        'linebreak_after_opening_tag' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'strict_comparison' => true,
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
        'phpdoc_align' => false,
        'phpdoc_order' => true,
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_summary' => false,
        'modernize_types_casting' => true,
        'native_function_invocation' => true,
    ])
    ->setFinder(
        Finder::create()
            ->in([
                __DIR__ . '/src',
                __DIR__ . '/tests',
            ])
    )
;

```

 * before running PHP CS Fixer (no changes):
```php
/**
 * Class FooBar.
 *
 * My specific class doc.
 * 
 * An other doc sub part:
 *      - foo
 *      - bar
 */
class FooBar
{
    // code
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
/**
 * Class FooBar.
 */
class FooBar
{
    // code
}
```

 * with the changes you expected instead:
```php
/**
 * Class FooBar.
 *
 * My specific class doc.
 * 
 * An other doc sub part:
 *      - foo
 *      - bar
 */
class FooBar
{
    // code
}
```

Also, it could be good to reference this page in the doc, it help a lot :) https://mlocati.github.io/php-cs-fixer-configurator/

**Comment by SpacePossum** [comment]
Hi @noniagriconomie ,

Thanks for reporting and all the details. I cannot reproduce the issue with the given config and sample code on 2.14.2. Could you run the fixer again that gave you this change while adding `-vvv`  to the command, this should output details that might be helpful to debug this issue further.

(I would also like to recommend updating to 2.16 as 2.14 is EOL and there shouldn't be BC breaking changes in the update)

**Comment by SpacePossum** [comment]
I'm going to fix this as I cannot reproduce the issue ob 2.15.dev nor on 2.14.1 or 2.14.2. Please let me know if this is still an issue and provide the details needed to reproduce the case. Thanks!
