### ISSUE TITLE
Change "sortAlgorithm" option of "ordered_class_elements" fixer to "sort_algorithm"?

### ISSUE THREAD

**Issue by jaydiablo** [FriendsOfPHP/PHP-CS-Fixer#4389]
The `ordered_class_elements` fixer has a sort algorithm option that uses camel case for the option (`sortAlgorithm`), all other fixers that have the same option use snake case (`sort_algorithm`).  It seems that the `ordered_imports` fixer has deprecated the camel case version already.

Should the camel case syntax be deprecated for the `ordered_class_elements` fixer as well, for consistency?

**Comment by SpacePossum** [comment]
Hi and thanks for reporting :+1: 

Looks like a good change, having a unit test to prevent camel cased options getting added would be great as well

**Comment by kubawerlos** [comment]
@SpacePossum we [have](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4634/files#diff-0ae0077906c99aaf35085e05c46cefd3L135) that test :)
