### ISSUE TITLE
GPG signature missing

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#4402]
The v2.14.3 and v2.12.9 releases do not have a GPG signature.

**Comment by keradus** [comment]
Hi @sebastianbergmann ,
GPG signature is always taking a bit to be uploaded since tag has been released (travis is taking a while to generate phar file), but signatures are already there since yesterday. Probably you spot the moment when versions were not fully created.
Thanks anyway!
