### ISSUE TITLE
PHP Parse error @PHPUnit60Migration

### ISSUE THREAD

**Issue by ktomk** [FriendsOfPHP/PHP-CS-Fixer#4417]
When using the _@PHPUnit60Migration:riky_ ruleset (effectively the **PhpUnitNamespacedFixer**) PHP-CS-Fixer was not able to fix files due to resulting the fixes into a PHP Parse error:

> PHP Parse error: syntax error, unexpected 'Return' (T_RETURN), expecting identifier (T_STRING)

This is when changing the class **PHPUnit_Framework_MockObject_Stub_Return** into the new namespaced  class **PHPUnit\Framework\MockObject\Stub\Return**.

Changing the class-name string `PHPUnit_Framework_MockObject_Stub_Return` to `PHPUnit_Framework_MockObject_Stub_ReturnStub` results in the correct new type `PHPUnit\Framework\MockObject\Stub\ReturnStub`.

---

#### The PHP version you are using (`$ php -v`):
> PHP 7.1.29-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 09:51:29) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
> master / PHP CS Fixer 2.16.0-DEV by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
~~~
php7.1 -n -dextension=tokenizer.so -dextension=json.so -dextension=ctype.so -dextension=iconv.so \
  -f../PHP-CS-Fixer/php-cs-fixer -- fix -vvv \
  --rules=@PHPUnit60Migration:risky,-php_unit_mock \
  tests
~~~

**Comment by ktomk** [comment]
Checked against all [Phpunit 5 and 6 class names](https://gist.github.com/ktomk/79d842340cdc02f6c088aaa5bb4d92ef) to make the change more complete.

**Comment by keradus** [comment]
Hi,
can you provide a file example, on which you got the error during fixing ?
