### ISSUE TITLE
When type php-cs-fixer got error "escape_Implicit_backslashes"

### ISSUE THREAD

**Issue by dogukanayd** [FriendsOfPHP/PHP-CS-Fixer#4434]
Php Version:
=> PHP 7.2.17-0ubuntu0.18.04.1

I installed php-cs-fixer using composer with this command:

composer global require friendsofphp/php-cs-fixer

so far so good.

But when I type
`php-cs-fixer` or `php-cs-fixer`
I got this error

> PHP Fatal error:  Uncaught UnexpectedValueException: Fixer named "escape_Implicit_backslashes" has invalid name. in /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php:144
> Stack trace:
> #0 /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php(109): PhpCsFixer\FixerFactory->registerFixer(Object(PhpCsFixer\Fixer\StringNotation\EscapeImplicitBackslashesFixer), false)
> #1 /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/src/Console/Command/DescribeCommand.php(77): PhpCsFixer\FixerFactory->registerBuiltInFixers()
> #2 /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php(56): PhpCsFixer\Console\Command\DescribeCommand->__construct()
> #3 /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(76): PhpCsFixer\Console\Application->__construct()
> #4 {main}
>   thrown in /home/dogukan/.composer/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php on line 144

**Comment by kubawerlos** [comment]
You have capital "I" in word "Implicit".

**Comment by dogukanayd** [comment]
Here is the solution. My system language setup as a Turkish and problem is happen because of that. I change system language to English and problem fixed.
