### ISSUE TITLE
NativeFunctionTypeDeclarationCasingFixer: expand scope

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#4441]
Currently the `native_function_type_declaration_casing` only supports parameter type declarations. It would be nice to also support return type declarations (and PhpDocs?).

**Comment by SpacePossum** [comment]
yes please :)

**Comment by julienfalque** [comment]
Ok, maybe it was an unsupported edge case but I can't remember. Let's close for now. Thanks for checking :+1:
