### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL in C:\wamp64\www\laravel-blog\app\Helpers\date.php on line 8

### ISSUE THREAD

**Issue by dean2017** [FriendsOfPHP/PHP-CS-Fixer#4442]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> ....................................

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> ....................................

#### The command you use to run PHP CS Fixer:
=> ....................................

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> ....................................
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> ....................................
```

 * with the changes you expected instead:
```php
=> ....................................
```

**Comment by SpacePossum** [comment]
Hi @dean2017 ,

Im sorry but your error report doesn't give us enough details to work on.
Can you fill out the details so we can help you?

**Comment by SpacePossum** [comment]
Closing as we don't have enough information to work, happy to reopen if we have the details needed to continue.
