### ISSUE TITLE
How do I format the code inside <?php opening tag

### ISSUE THREAD

**Issue by wyattbiker** [FriendsOfPHP/PHP-CS-Fixer#4447]
Why does the code below not get formatted to line up properly when I try to format it? I am using VS Code, so I right click and choose Format Document.   It will format correctly if I place the code inside { ... }

Here are the versions of the installation:

- VS Code Version 1.35.1 (1.35.1) on Mac OS X
- PHP 7.3
- PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski (2006451)
- Name: php cs fixer
- Id: junstyle.php-cs-fixer
- Description: PHP CS Fixer extension for VS Code, php formatter, php code beautify tool, format html
- Version: 0.1.119
- Publisher: junstyle
- VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer

```php
<?php

phpinfo();
$x = 20;
$x = $x + 1;
    echo $x;

        if ($x == 1) {
            echo $x;
        }

      if ($x == 1) {
          echo $x;
      } else {
          echo('nope');
      }

      function foo() {
          echo 1;
      }
```

Here is my .php_cs
```php
<?php

$finder = PhpCsFixer\Finder::create()
    //->exclude('somedir')
    //->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php'
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'strict_param' => false,
        'array_syntax' => ['syntax' => 'long'],
        'braces' => [
            'allow_single_line_closure' => true, 
            'position_after_functions_and_oop_constructs' => 'same'],
    ])
    ->setFinder($finder)
;

**Comment by wyattbiker** [comment]
I am adding this as a comment of another user with same issue from Sep 2017.

https://stackoverflow.com/questions/46305564/fix-indentation-of-php-code-files-with-php-cs-fixer/46305930#46305930

**Comment by SpacePossum** [comment]
Hi and thanks for your question.

Currently we don't have a rule that will remove the extra indentation, sadly because it would be great to have!

**Comment by SpacePossum** [comment]
This extra indentation now gets properly fixed by the `braces` rule, I suggest closing this issue.
