### ISSUE TITLE
New rule: remove backslash on non-optmizable function calls

### ISSUE THREAD

**Issue by fabpot** [FriendsOfPHP/PHP-CS-Fixer#4448]
It's great to have a rule that adds backslashes when needed (optimizable function calls). The problem is that people do not really know which function calls can be optimized, so they add backslashes "randomly". It would be great a have a new rule that would remove such unneeded blackslashes. WDYT?

**Comment by kubawerlos** [comment]
We already have such [option](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.1/src/RuleSet.php#L194) for `native_function_invocation` and it's even part of `@Symfony:risky`.

**Comment by fabpot** [comment]
@kubawerlos Great! Thank you for the tip.

**Comment by fabpot** [comment]
@kubawerlos Great! Thank you for the tip.
