### ISSUE TITLE
BracesFixer adds newline to dynamic static method call

### ISSUE THREAD

**Issue by ShiraNai7** [FriendsOfPHP/PHP-CS-Fixer#4451]
#### The PHP version you are using (`$ php -v`):
=> 7.3.6

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15.1

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer.phar fix --rules=@PSR2 src

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function example()
{
    SomeClass::{$method}(new \stdClass());
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

function example()
{
    SomeClass::{$method}
    (new \stdClass());
}

```

 * with the changes you expected instead:
no changes expected

**Comment by SpacePossum** [comment]
Thanks for reporting this bug @ShiraNai7 !
I've proposed a bug fix for it.
