### ISSUE TITLE
Help wanted: support PHPStorm issue with anonymous class opening brace placement

### ISSUE THREAD

**Issue by Doqnach** [FriendsOfPHP/PHP-CS-Fixer#4456]
Currently PHP-CS-Fixer and PHPStorm code style are not agreeing on the position of the opening brace for anonymous classes:

PHP-CS-Fixer:
```php
$class = new class extends SomeClass {
};
```

PHPStorm:
```php
$class = new class extends SomeClass
{
};
```

There is an issue filed at PHPStorm about this, but 3 years old and could use some community support to put it in the spotlight and get it fixed.

https://youtrack.jetbrains.net/issue/WI-32915

**Comment by SpacePossum** [comment]
Hi and thanks for looking into this.
Im not sure how we can be of more assistance, lets hope PHPStorm will allow for more configuration on this subject :)

**Comment by Doqnach** [comment]
Maybe https://youtrack.jetbrains.com/issue/WI-45330 will bring the solution!

**Comment by Doqnach** [comment]
Looks like the introduction of PSR-12 support in PHPStorm has solved this issue!

**Comment by SpacePossum** [comment]
thanks for reporting back :)
