### ISSUE TITLE
the version constant in code should be updated for releases

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#446]
It would be great if the version constant in https://github.com/fabpot/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer.php#L23 could be updated for tagged releases, so that the PHAR archive can tell me I'm running 0.5.6 without requiring me to go looking at the git history to figure out the version corresponding to the commit hash display in the version.

**Comment by keradus** [comment]
I can do the release now. Closing.
