### ISSUE TITLE
new_with_braces generates invalid code

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4464]
PHP v7.3.6, PHP-CS-Fixer CS Fixer v2.15.1. Enable only `new_with_braces`.

Then the following input file is "fixed" into invalid PHP code:

```php
<?php

(new $foo[0]->bar());
```

**Comment by keradus** [comment]
Thanks for report @GrahamCampbell .
Can you raise a fix, please ?

**Comment by GrahamCampbell** [comment]
What would the expected behaviour be here. There are two options I guess:

1. To add extra parentheses around the class name, and then add the `()`.
2. Skip fixing this case, since it'd only make the syntax more messy.

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4483
