### ISSUE TITLE
ErrorException thrown when attempting to run from project specific

### ISSUE THREAD

**Issue by ticktackk** [FriendsOfPHP/PHP-CS-Fixer#4468]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.3.7

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15.1

#### The command you use to run PHP CS Fixer:
=> `php <path to project>/_vendor/bin/php-cs-fixer -h`

When installed as project specific instead of globally this exception will be thrown:
```
PHP Warning:  Uncaught ErrorException: require_once(<path to project>/_vendor/bin/vendor/autoload.php): failed to open stream: No such file or directory in <path to project>/_vendor/bin/php-cs-fixer:61
Stack trace:
#0 <path to project>/_vendor/bin/php-cs-fixer(61): {closure}(2, 'require_once(<p...', '<path to projec...', 61, Array)
#1 <path to project>/_vendor/bin/php-cs-fixer(61): require_once()
#2 {main}
  thrown in <path to project>/_vendor/bin/php-cs-fixer on line 61
PHP Stack trace:
PHP   1. {main}() <path to project>/_vendor/bin/php-cs-fixer:0
PHP Fatal error:  main(): Failed opening required '<path to project>/_vendor/bin/vendor/autoload.php' (include_path='.:/usr/share/php') in <path to project>/_vendor/bin/php-cs-fixer on line 61
PHP Stack trace:
PHP   1. {main}() <path to project>/_vendor/bin/php-cs-fixer:0

**Comment by SpacePossum** [comment]
Hi @ticktackk 

Can you elaborate a bit more how you setup the project that ended in this erroneous state? Did you install it through `composer` and than moved the files?

I'm not sure the proposed fix is the right way to go as it will lead to more guessing where the files are, while we would like test for known places only.

The ErrorException thrown is not very user friendly, so I do see an improvement option there, testing if the files exists and if not let the user know what was tried and was expected.

**Comment by ticktackk** [comment]
> Can you elaborate a bit more how you setup the project that ended in this erroneous state?

My project requires me to follow XenForo's add-on directory structure, which should look something like this:
```
/var/www/<dir for host>/html
...
├── src
    └── addons
        └── <vendor name>
            └── <project internal id>
                ├── _vendor
                ├── LICENSE.md
                ├── README.md
                ├── Setup.php
                ├── addon.json
                ├── composer.json
                └── composer.lock
...
```
The only place where I'm allowed to make any changes is inside `<project internal id>`. The `composer.json` file is also modified to include this:

```
    "config": {
        "vendor-dir": "_vendor"
    },
```
to use `_vendor` directory instead of `vendor`. I've also attempted to just use `vendor` directory but even so I receieve the same exception.

> Did you install it through `composer` and than moved the files?

I installed using composer without the global flag.

```
composer require friendsofphp/php-cs-fixer --dev
```

While using that file structure if you attempt to call php-cs-fixer via this command:
```
php /var/www/<dir for host>/html/src/addons/<vendor name>/project internal id>/_vendor/bin/php-cs-fixer
```
