### ISSUE TITLE
README `Usage` list all opions

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#4473]
The README `Usage` section list almost all options.
The exceptions are:

```
--config=CONFIG
--using-cache=USING-CACHE
--cache-file
```

I think the rationale behind that was that these are listed in more detail later on. However this much down in the doc (after the rules listing in some cases).

I propose to list all options and where applicable with minimal detail and a hint to further down in the document.

**Comment by Alejandro-Villa** [comment]
Is this issue still open? I can work on it

**Comment by SpacePossum** [comment]
closing as it is better to do in the doc refactor work
