### ISSUE TITLE
README - update the curl example

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#4474]
The README `Installation` list an example how to get the tool using `curl`.

However the recent `curl` updates on some distro this results in: 

```
$ curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar php-cs-fixer.phar
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

Suggest to update to a warning free `curl` example.

**Comment by keradus** [comment]
curl or wget ? maybe we want to switch?

**Comment by SpacePossum** [comment]
we have both `curl` and `wget` in the README ATM, I propose fixing the `curl` sample or dropping it

**Comment by keradus** [comment]
@SpacePossum , actually, where did you take this command from?
In our readme, we have:
```
curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer
```

(see the `-o` part)

**Comment by SpacePossum** [comment]
hmm good question, not from the docs it seems  :)  closing as invalid
