### ISSUE TITLE
phpdoc_inline_tag: does not respect PSR-19

### ISSUE THREAD

**Issue by vvanpo** [FriendsOfPHP/PHP-CS-Fixer#4478]
The `phpdoc_inline_tag` rule forces the `@inheritdoc` tag to be inline, but PSR-19 does not require this and explicitly allows for `@inheritdoc` to be used as a block tag:
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#41-making-inheritance-explicit-using-the-inheritdoc-tag

My suggestion would be to add an `inheritdoc_inline` configuration option to this rule defaulting to `true`, to prevent changing existing behaviour.

**Comment by julienfalque** [comment]
See #2619.

**Comment by vvanpo** [comment]
Thanks, I should have done a more thorough search.
