### ISSUE TITLE
Punctuate @params fixer

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#4481]
There's a fixer to force removing punctuation from `@params` annotations (`phpdoc_annotation_without_dot`), but disabling it does not force the reverse. That is, there is not a fixer to enforce punctuation, even though there is such a fixer for the summar (`phpdoc_summary`). This seems like a glaring omission.

**Comment by keradus** [comment]
Please, avoid judging (`glaring omission`).

This action was done by purpose, rule was raised by Symfony maintainers and it's part of their coding standard - Summary is full sentence (starting with uppercase, ending with dot), param description is not (and fixer for it does not only remove the ending dot, but also lowercasing the beginning).

If you would love to have a feature that would make it uppercased+ending dot, please raise a PR to make `phpdoc_annotation_without_dot` configurable. Thanks !
