### ISSUE TITLE
Single line array to multiple line array fixer

### ISSUE THREAD

**Issue by surenderpratap** [FriendsOfPHP/PHP-CS-Fixer#4485]
//From
$array = array("foo" => "bar","bar" => "foo");

//To
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);

**Comment by SpacePossum** [comment]
Hi and thanks for the question,

Currentlky we have no rule in place to do this, would be nice to have though :)

**Comment by taylankasap** [comment]
Duplicate of #1217

**Comment by SpacePossum** [comment]
thanks! closing as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1217
