### ISSUE TITLE
Redundant concatenation fixer

### ISSUE THREAD

**Issue by weshooper** [FriendsOfPHP/PHP-CS-Fixer#4491]
Is there a fixer for removing redundant string concatenation, as in the following example?

```diff
-echo 'foo' . 'bar';
+echo 'foobar';
```

**Comment by kubawerlos** [comment]
Do you mean like [this](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v1.15.0#nounneededconcatenationfixer)? Should I create PR for that fixer here?

**Comment by weshooper** [comment]
@kubawerlos oh wow, yes that's exactly it!

**Comment by SpacePossum** [comment]
:+1:  

nice to figure out the priority with the quote fixer, for example:

```
<?php $a = "\n" . "a";
```

could be fixed by this fixer, but after the single quote fixer it would have to check again if it can change `'a'` to `"a"` and merge to `"\na"`
