### ISSUE TITLE
Remove unneeded alias in import

### ISSUE THREAD

**Issue by JakeFr** [FriendsOfPHP/PHP-CS-Fixer#4492]
Hello,

Fixers related to import do not remove unneeded alias.
If would be nice to have a fixer for this code

 * before running PHP CS Fixer (no changes):
```php
namespace Vendor\Package;

use OtherVendor\OtherPackage\BazClass as BazClass;
```

 * with the changes you expected instead:
```php
namespace Vendor\Package;

use OtherVendor\OtherPackage\BazClass;
```

And fix the other imports (trait, const and function)

WDYT?
Are there any code side effects?

**Comment by SpacePossum** [comment]
this is implemented in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6267 , closing as such
