### ISSUE TITLE
sentence ending in colon or semilcolon should not get another dot

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#4495]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.0.33

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.15.1 Europe Round

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:
default symfony style 

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
/**
 * the function is doing things as following:
 * - a
 * - b 
 *
 */
function func() {
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
/**
 * the function is doing things as following:.
 * - a
 * - b 
 *
 */
function func() {
}
```

 * with the changes you expected instead:
```php
/**
 * the function is doing things as following:
 * - a
 * - b 
 *
 */
function func() {
}
```

**Comment by staabm** [comment]
same problem with a description ending in `;`

```
/**
 * the function is doing things as following;
 * - a
 * - b 
 *
 */
function func() {
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting

This behavior comes from the rules relying on [PSR5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#51-summary), stating:

```
Summaries to span a single line or at most two, but not more than that.
```

As such, if you want to list items over multiple lines and be PSR5 compliant you might want to do something like;

```
/**
 * This function does A.
 *
 * The function does that by doing things as following;
 * - a
 * - b 
 *
 */
function func() {
}

```
we just cant support all formats, but of course you are free to write however you want :)
