### ISSUE TITLE
`'yoda_style' => false` not working

### ISSUE THREAD

**Issue by Zayon** [FriendsOfPHP/PHP-CS-Fixer#4499]
The ` 'yoda_style' => false` rule seems to behave like ` 'yoda_style' => null`.

` 'yoda_style' => true` works corretly.

#### The PHP version you are using (`$ php -v`):

> PHP 7.3.8 (cli) (built: Aug  2 2019 05:16:32) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

> PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:

`php vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php_cs`

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRules([
        'yoda_style' => false,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(['src'])
    )
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

$var = true;

if (true === $var) {
	echo 'true';
} else {
	echo 'false';
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
Nothing
```

 * with the changes you expected instead:
```php
<?php

$var = true;

if ($var === true) {
	echo 'true';
} else {
	echo 'false';
}
```

--- 

This is solved by using this configuration: 
```php
<?php

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRules([
        'yoda_style' => [
            'identical' => false,
        ],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(['src'])
    );
```

But I think ` 'yoda_style' => false` should work

**Comment by kubawerlos** [comment]
> But I think `'yoda_style' => false` should work

And it works, as for any fixer - and setting any fixer to `false` disable it.

To achieve your expected changes you need to do this:
```
        'yoda_style' => [
            'equal' => false,
            'identical' => false,
            'less_and_greater' => false,
        ],
```

**Comment by keradus** [comment]
Closing as it was more misunderstanding how to configure the rule and not bug in it.
