### ISSUE TITLE
native_function_invocation functioning backwards

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#4501]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.19-1+ubuntu18.04.1+deb.sury.org+1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.15.1 Europe Round

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer fix --allow-risky=yes --verbose --dry-run --diff --diff-format=udiff`

#### The configuration file you are using, if any:
```php
<?php
declare(strict_types=1);

return PhpCsFixer\Config::create()
    ->setRules([
        #region Rule sets.

        '@PhpCsFixer' => true,
        '@PhpCsFixer:risky' => true,
        '@PHP71Migration' => true,
        '@PHP71Migration:risky' => true,
        '@PHPUnit75Migration:risky' => true,

        #endregion

        #region Individual fixers.

        'backtick_to_shell_exec' => true,
        'blank_line_after_opening_tag' => false,
        'cast_spaces' => ['space' => 'none'],
        'concat_space' => ['spacing' => 'one'],
        'date_time_immutable' => true,
        'escape_implicit_backslashes' => ['single_quoted' => true],
        'explicit_string_variable' => false,
        'linebreak_after_opening_tag' => true,
        'list_syntax' => ['syntax' => 'short'],
        'mb_str_functions' => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'new_line_for_chained_calls'],
        'no_php4_constructor' => true,
        'no_short_echo_tag' => false,
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
        'ordered_class_elements' => ['sortAlgorithm' => 'alpha'],
        'php_unit_fqcn_annotation' => false,
        'php_unit_internal_class' => ['types' => ['normal', 'final', 'abstract']],
        'php_unit_test_case_static_method_calls' => ['call_type' => 'self'],
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_annotation_without_dot' => false,
        'phpdoc_types_order' => ['null_adjustment' => 'always_last'],
        'static_lambda' => true,
        'yoda_style' => false,

        #endregion
    ])
    ->setFinder(
		PhpCsFixer\Finder::create()
			->exclude('vendor')
			->exclude('var/cache')
			->exclude('tests/Fixtures')
			->in(__DIR__)
            ->name('console')
	)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
declare(strict_types=1);

namespace Foo;

use PHPUnit\Framework\TestCase;

/**
 * @internal
 */
final class FooTest extends TestCase
{
    public function test(): void
    {
        \json_decode('foo', true);
    }
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```diff
--- Original
+++ New
@@ -12,6 +12,6 @@
 {
     public function test(): void
     {
-        \json_decode('foo', true);
+        json_decode('foo', true);
     }
 }

```

 * with the changes you expected instead:
```
=> none
```

**Comment by kubawerlos** [comment]
You are using `@Symfony:risky` ruleset (via `@PhpCsFixer:risky`) and it uses `native_function_invocation` in strict version.

To achieve what you expect add this to your config:
```
    'native_function_invocation' => [
        'include' => [NativeFunctionInvocationFixer::SET_COMPILER_OPTIMIZED],
        'scope' => 'namespaced',
        'strict' => false, // or remove this line, as false is default value
    ],
```

**Comment by Bilge** [comment]
What does *strict* mean here? The doc just says, _whether leading `\` of function call not meant to have it should be removed_, but it's entirely opaque as to how it determines whether a function is _meant to have it_ or not.

**Comment by kubawerlos** [comment]
As the set of functions is [`SET_COMPILER_OPTIMIZED`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.1/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L49) it means "functions known to be optimized by the Zend engine" which is this: https://github.com/php/php-src/blob/PHP-7.3.8/Zend/zend_compile.c#L3904

So other functions - including `json_decode` - are "not meant to have it".

**Comment by Bilge** [comment]
Why would you ever just limit it to the _compiler optimized_ subset? Isn't the optimization benefit applicable to all internal functions within namespaced code?
