### ISSUE TITLE
How to enforce double space in PHPDoc?

### ISSUE THREAD

**Issue by szepeviktor** [FriendsOfPHP/PHP-CS-Fixer#4506]
I'm trying to replicate StyleCI's Laravel fixers

- https://api.styleci.io/presets
- https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/.php_cs

How to tell PHP CS Fixer to enforce double spaces like this?
```
@param␣␣string␣␣$path
```
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php#L18

Thank you.

Cc @iamgergo

**Comment by szepeviktor** [comment]
Is there anyone from StyleCI? @joecohens ?

**Comment by GrahamCampbell** [comment]
StyleCI doesn't enforce the double spacing in PHPDoc for Laravel yet.

**Comment by szepeviktor** [comment]
@GrahamCampbell Thank you. How come that PPH CS Fixer's `phpdoc_align` would like to correct double spaces in PHPDoc but StyleCI is OK with laravel/framework's source containing [double spaces](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php#L18)?

**Comment by GrahamCampbell** [comment]
Yes, because the phpdoc was typed out like that. I don't think this discussion is relevent to PHP-CS-Fixer.

**Comment by szepeviktor** [comment]
I see! StyleCI really does not care about whitepspaces: https://github.com/laravel/framework/pull/29700

**Comment by GrahamCampbell** [comment]
@szepeviktor StyleCI does enforce with phpdoc tag alignment style, enabled by default on the Laravel preset, as of today. See https://blog.styleci.io/new-php-fixers-6/. 🎉

**Comment by szepeviktor** [comment]
@GrahamCampbell Thank you for notifying me.
