### ISSUE TITLE
closing tag forced on same line + odd indentation with mixed content (html + php)

### ISSUE THREAD

**Issue by felixpenrose** [FriendsOfPHP/PHP-CS-Fixer#4507]
In the example below the `echo` is un-indented once, and the closing `?>` tag is moved onto the same line.

This very small example is exacerbated in files where there's lots of mixed html + php. The php code un-indents itself back to the last section of php, whereas the code is much easier to read if it's indented to align to the last opening html tag.

#### The PHP version you are using (`$ php -v`):
7.2.0

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.15.1

#### The command you use to run PHP CS Fixer:
VSCode extension
https://github.com/fterrag/vscode-php-cs-fixer

#### The configuration file you are using, if any:
Any configuration. I'll add mine if needed, but a fresh PSR2 config handles formatting as below

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
if ($foo) {
    ?>
    <p>
        <?php
        foreach ($variable as $key => $value) {
        }

        echo '<span>Complete</span>';
        ?>
    </p>
    <?php
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
if ($foo) {
    ?>
    <p>
        <?php
        foreach ($variable as $key => $value) {
        }

    echo '<span>Complete</span>'; ?>
    </p>
    <?php
}
```

 * with the changes you expected instead:
```php
<?php
if ($foo) {
    ?>
    <p>
        <?php
        foreach ($variable as $key => $value) {
        }

        echo '<span>Complete</span>';
        ?>
    </p>
    <?php
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for the report,

Currently we have very limited support for mixing PHP and HTML (or any other templating). Given the challenges and effort to support that we generally consider it out of scope of the tooling.
I know there a valid cases to mix the two and switching to a templating setup like Twig can be too much, but another workaround could be to not fix these template files using this tool. 

I'm closing this as I don't think supporting this, while being a nice thing, is not going to happen any time soon.
