### ISSUE TITLE
PHP 7.4 Compatibility Heads Up

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4519]
It is no longer allowed (deprecation warning, will break in PHP 8.0) to unbind closures that reference `$this` from PHP 7.4.0beta5 onwards (beta4 forbids unbinding completely). The following code will need changing: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.1/src/FixerConfiguration/FixerOption.php#L153-L175.

// cc @nikic

**Comment by nikic** [comment]
I don't think this needs any changes. If the closure was using `$this` in the first place, then unbinding it would already break it right now. If it wasn't using `$this`, then it's not affected by the deprecation anyway.

**Comment by GrahamCampbell** [comment]
Right. I'll verify there are no errors in beta5 when it hands early in September. ;)

**Comment by GrahamCampbell** [comment]
Thanks for the help @nikic. 🎉

**Comment by SpacePossum** [comment]
Thanks for the heads up @GrahamCampbell and the additional check @nikic , much appreciated!
Im closing this ticket as I see no action here, please correct me if I'm wrong :)
