### ISSUE TITLE
Wrong strings for string fix in php_unit_no_expectation_annotation fixer

### ISSUE THREAD

**Issue by ktomk** [FriendsOfPHP/PHP-CS-Fixer#4520]
While making use of the php_unit_no_expectation_annotation fixer recently, I stumbled over a little flaw when strings are used for class-names: All strings are wrongly generated with a leading backslash character (`\`). Correct is to not have it.

This is also PHP's behaviour, when outputting a class in global or another namespace for the PHP versions that support the ::class constant:

Example:
```php
<?php namespace Foo\Bar;
class Baz {};
var_dump(Baz::class);
```
Output:
```
string(11) "Foo\Bar\Baz"
```
(find [this example on 3v4l](https://3v4l.org/DJiV4))

Which is also a correct FQCN. However it might have been that for annotations (which are getting converted here) it is of use in IDEs which do fully resolve any class-name from annotations to the namespace of the file, so a leading back-slash is sometimes added in front of 
FQCNs in annotations for code editing convenience reasons.

As the fixer changes into a string parameter, this is not necessary at all as class-names expressed as strings always need to point to the class in the global namespace, hence never require a leading backslash.

For the conversions I do I current have a regular expression based fixer after PHP-CS-Fixer to workaround this issue temporarily however as I'm even fiddled with this fixer I'm open to provide a pull request which addresses this issue. It will just change from backslash-ed to the correct string.

Example:

Input:

```php
<?php
    final class MyTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @expectedException FooException
         */
        public function testFnc()
        {
            aaa();
        }
    }
```

Output:

```php
<?php
    final class MyTest extends \PHPUnit_Framework_TestCase
    {
        /**
         */
        public function testFnc()
        {
            $this->setExpectedException('\FooException');

            aaa();
        }
    }
```

This issue basically suggests to remove the leading `\` from the string in:

```php
$this->setExpectedException('\FooException');
                             ^
```
to get into a correct FQCN:

```php
$this->setExpectedException('FooException');
                            ^^
```

Let me know if you see any issues with this as otherwise I might just file a PR.

**Comment by GrahamCampbell** [comment]
Hmm, yes. I'd say that FQCNs as string literals should not have a leading slash.

**Comment by GrahamCampbell** [comment]
I'd expect `\Foo::class` -> `'Foo'`.
