### ISSUE TITLE
Request: Fixer that turns `?><some html><?php` into `echo '<some html>';`

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#4522]
A fixer that turns 
`?>text<?php` 
into 
`echo 'text';` 

This is for legacy code that's probably way beyond what this project is focusing on, but it would be nice to have some transform that pulls all of "end PHP interpreter" / "start PHP interpreter" into PHP space.

Another one could be chaining consecutive `echo`'s together into a concatenation. And one that turns them into a `sprintf()` invocation.

That would ease transfering especially messy interwoven PHP code to a template language. I've inherited legacy code with up to 127 interpreter open/closes per file, with ifs and loops iterating over these (effectively `echo`) blocks.

Currently I'm doing this process half-way manually in PhpStorm, which is messy and prone to errors.

**Comment by keradus** [comment]
PHP CS Fixer is not template refactoring tool.
I stronly advise to stop mixing code with template.

**Comment by HenkPoley** [comment]
> I strongly advise to stop mixing code with template.

That was the purpose of the request.

**Comment by keradus** [comment]
no, you just wanted to move template part from html to php, but it is still php code mixed with template. just switch to template system like `mustache`, handing html-based content in php and do the transformation requires a lot of effort and hundreds of edge cases, while the benefit is not that big

**Comment by HenkPoley** [comment]
I understand your concern, and I know you will not work on this. But.. in PhpStorm there is a fairly simple to use "convert string concatenation to sprintf call" which is then almost in template format (just edit all the %s). Hence I would like to have everything as PHP string.

Just repeating, I know you will not work on this. But just showing my approach has some sanity to it.
