### ISSUE TITLE
Inconsistent default value for multiline_whitespace_before_semicolons between docs and code

### ISSUE THREAD

**Issue by junruisz** [FriendsOfPHP/PHP-CS-Fixer#4527]
Basically [this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/c9d30fddfa3feb8b82663104864224f2ce7a3675/src/RuleSet.php#L222) in the default rule set contradicts with [documentation](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blame/c9d30fddfa3feb8b82663104864224f2ce7a3675/README.rst#L900)

#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.31-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 10:23:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.31-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.15.2 Europe Round by Fabien Potencier and Dariusz Ruminski`
git commit `c9d30fddfa3feb8b82663104864224f2ce7a3675`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix -v --dry-run --diff .php_cs.dist`

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('node_modules')
    ->exclude('var')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRules([
        '@PhpCsFixer' => true,
        'braces' => [
            'position_after_functions_and_oop_constructs' => 'same',
        ],
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
Please see the diff below

 * with unexpected changes applied when running PHP CS Fixer:

This is the result of running the command `vendor/bin/php-cs-fixer fix -v --dry-run --diff .php_cs.dist`
```php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 
 $finder = PhpCsFixer\Finder::create()
     ->exclude('node_modules')
     ->exclude('var')
-    ->in(__DIR__);
+    ->in(__DIR__)
+;
@@ @@
         ],
-    ]);
+    ])
+;
 

      ----------- end diff -----------
```

 * with the changes you expected instead:
`.php_cs.dist` should not be modified

**Comment by kubawerlos** [comment]
I don't see any inconsistency.

Default value for `strategy` in `multiline_whitespace_before_semicolons` is `no_multi_line`. Always.

The fact that rule set `@PhpCsFixer` uses this fixer with different `strategy` does not make that strategy `default` in any way.

In `RuleSet` class you can see many similar situations when some set is using fixer with non-default configuration and it is perfectly fine.

**Comment by julienfalque** [comment]
There is no inconsistency here. The second link you gave shows the *default* configuration of the standalone rule while the first link shows how the rule is configured when used via the `@PhpCsFixer` ruleset.

**Comment by junruisz** [comment]
Thanks for the clarification
