### ISSUE TITLE
Release phar for 2.15.2 unsigned

### ISSUE THREAD

**Issue by theseer** [FriendsOfPHP/PHP-CS-Fixer#4528]
```
theseer@nyda ~/storage/php/css2xpath master $ phive update php-cs-fixer
Phive 0.12.4-4 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/FriendsOfPHP/PHP-CS-Fixer/releases
[WARNING] php-cs-fixer 2.15.2: No GPG Signature
```

**Comment by sebastianbergmann** [comment]
All of these are missing signatures:
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.12.11
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.14.5
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.15.2

**Comment by keradus** [comment]
Yeah, basically Travis is so slow with the release, that I have to wait 1h until it creates a release artifact I can sign, thus often I do it already on next day.
