### ISSUE TITLE
PHP 7.4 features invalidating PHP 7.2 code

### ISSUE THREAD

**Issue by LarsGrevelink** [FriendsOfPHP/PHP-CS-Fixer#4529]
By merging #4380 PHP 7.4 functionality seems to have entered the realm of existing rules which are applied to existing projects. If I understand the code changes correctly there should be a check whether the function exists but for some reason that is not respected. I created a small test case to verify this.

We're running on Docker PHP 7.2 environments so nothing too fancy there.

Are we misconfiguring our tools somewhere or should this be fixed on the CS Fixer side?

Cheers,
L

**PHP version:** 7.2.19
**PHP CS Fixer version:** PHP CS Fixer 2.15.2 Europe Round by Fabien Potencier and Dariusz Ruminski (c9d30fd)

**Command used;**
```
./php-cs-fixer fix --config=.php_cs test.php
```

**Configuration used;**
```php
<?php

return PhpCsFixer\Config::create()->setRules([
    'mb_str_functions' => true,
])->setLineEnding("\n")->setRiskyAllowed(true);
```

**Before running PHP CS Fixer (no changes);**
```php
<?php

var_dump(function_exists('mb_str_split'));
// bool(false)

str_split('splitting the string');
```

**With unexpected changes applied when running PHP CS Fixer;**
```php
<?php

var_dump(function_exists('mb_str_split'));
// bool(false)

mb_str_split('splitting the string');
// Fatal error: Uncaught Error: Call to undefined function mb_str_split() in /src/test.php on line 5
```

**With the changes you expected instead;**
```php
<?php

var_dump(function_exists('mb_str_split'));
// bool(false)

str_split('splitting the string');
```

**Comment by LarsGrevelink** [comment]
Might be good to know that we're retrieving it via;

```
$ curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer
```

**Comment by weshooper** [comment]
Came here to report the same issue. We're running PHP 7.3.6.

**Comment by keradus** [comment]
looks like we need to revert #4380 , thanks for the report

**Comment by LarsGrevelink** [comment]
@keradus It was still scratching my head since the code was very solid which was added. Unfortunately, a dependency used by the project adds a polyfill. This is why for the validator is always seems to exist even though it isn't.

Dependency: `symfony/console` which requires `symfony/polyfill-mbstring`

Code which causes the eventual issue;
https://github.com/symfony/polyfill-mbstring/blob/b42a2f66e8f1b15ccf25652c3424265923eb4f17/bootstrap.php#L60-L62

Since `symfony/console` is used as the base application for PHP CS Fixer I think this has to be discussed internally how you want to proceed with this issue. If you decide on the way to go, I'd love to help out in addressing this problem.

**Comment by keradus** [comment]
exactly what i just wrote here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4380/files#r319718704

for now, i will revert as-is, recreate the original PR and we will continue on discussion how to bring this change. most probably, configuration option for the fixer, i believe.

**Comment by keradus** [comment]
Closing due to merge of #4533 
I will release it today

**Comment by LarsGrevelink** [comment]
Great, thanks! Keep us posted of any developments and where we can help out!

**Comment by weshooper** [comment]
Thanks!

**Comment by keradus** [comment]
If you would be willing to help, best place would be to help with reviews! we have quite a few opened, but not that much capacity to deal with all of them as fast as we would want to!

**Comment by keradus** [comment]
@LarsGrevelink , released

**Comment by LarsGrevelink** [comment]
@keradus Thanks! When do you think the latest version is also fetchable through the Symfony URLs as well? Just now only 2.15.2 was available there.

I will see if I can find some time to start reviewing some code in the upcoming days. 😄

**Comment by keradus** [comment]
our automated page regeneration triggered by deployment ( ref https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/579168739#L580 ) didn't done the trick.
looks to be related to `Travis CI Status : Partial System Outage` (ref https://www.traviscistatus.com/ )

page is autogenerated nightly, so it should go back to normal

also, `php php-cs-fixer self-update should do the trick, as it uses GitHub releases
```
ker@dus:/tmp λ php php-cs-fixer --version
PHP CS Fixer 2.15.2 Europe Round by Fabien Potencier and Dariusz Ruminski (c9d30fd)
ker@dus:/tmp λ php php-cs-fixer self-update
php-cs-fixer updated (v2.15.3)
```

**Comment by keradus** [comment]
@LarsGrevelink 
our automated page regeneration triggered by deployment ( ref https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/579168739#L580 ) didn't done the trick.
looks to be related to `Travis CI Status : Partial System Outage` (ref https://www.traviscistatus.com/ )

page is autogenerated nightly, so it should go back to normal

also, `php php-cs-fixer self-update should do the trick, as it uses GitHub releases
```
ker@dus:/tmp λ php php-cs-fixer --version
PHP CS Fixer 2.15.2 Europe Round by Fabien Potencier and Dariusz Ruminski (c9d30fd)
ker@dus:/tmp λ php php-cs-fixer self-update
php-cs-fixer updated (v2.15.3)
```
