### ISSUE TITLE
Suggestion: phpdoc_align should support `@property-read`

### ISSUE THREAD

**Issue by ghobaty** [FriendsOfPHP/PHP-CS-Fixer#4530]
Currently, `phpdoc_align` doesn't have support for [@property-read](https://docs.phpdoc.org/references/phpdoc/tags/property-read.html)

Trying to configure it, e.g. `'phpdoc_align' => [ 'tags' => [ 'property', 'property-read']]` causes an `InvalidOptionsException` to be thrown.

I suggest adding `property-read` here https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/37cc9c62f71a4cd49d9427aea729954f0ca35fe2/src/Fixer/Phpdoc/PhpdocAlignFixer.php#L62-L70 which should be backward compatible as long as the default config value is not altered.

**Comment by kubawerlos** [comment]
@ghobaty that perfectly makes sense, take a look at https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4531 and make a review if you find time.
