### ISSUE TITLE
GuzzleHttp Error!

### ISSUE THREAD

**Issue by Sarfroz** [FriendsOfPHP/PHP-CS-Fixer#4547]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.1

Hi suddenly i am getting 

**"cURL error 51: SSL: no alternative certificate subject name matches target host name 'www.google.com' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"**  the error appears during login.

**Comment by ktomk** [comment]
@Sarfroz What command do you execute that triggers that error?

**Comment by Sarfroz** [comment]
I am using laravel 5.6 . my site was working fine. Now I found that I am using invisible re-captcha. During auth check, the Recaptcha is verified using GuzzleHttp. If I disable invisible recaptcha my login works fine. But I don't know why suddenly this error comes up. Even I did not update or change anything on my site.

**Comment by ktomk** [comment]
@Sarfroz I see. Maybe you want to address this to the Lavarvel project? It's only an educated guess, but the PHP-CS-Fixer project might not be the right venue here to post such issues

**Comment by Sarfroz** [comment]
ok sir sure.
