### ISSUE TITLE
class_keyword_remove doesn't convert to fully qualified class names

### ISSUE THREAD

**Issue by lukasbestle** [FriendsOfPHP/PHP-CS-Fixer#4555]
#### The PHP version you are using (`$ php -v`):
=> `7.2.11`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `2.15.3 Europe Round`

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix test.php --rules=class_keyword_remove`

#### The configuration file you are using, if any:
=>  None in this reduced test case.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, AnotherTestClass::class)) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, 'AnotherTestClass')) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

 * with the changes you expected instead:
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, 'TestNamespace\AnotherTestClass')) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

**Comment by kubawerlos** [comment]
Also
```
namespace Foo\Bar;
var_dump(Bar\Baz::class);
```
would not work.

Let's do https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4556 and handle this one after.

**Comment by SpacePossum** [comment]
@kubawerlos 4556 got merge, do you have time to have a look at what still needs fixing?

**Comment by yassine-ah** [comment]
**The PHP version you are using ($ php -v):**
=> PHP 7.3.9 (cli) (built: Sep  3 2019 06:49:26) ( NTS )

**PHP CS Fixer version you are using ($ php-cs-fixer -V):**
=> PHP CS Fixer 2.15.4-DEV Europe Round by Fabien Potencier and Dariusz Ruminski

**The command you use to run PHP CS Fixer:**
=> php-cs-fixer fix test.php --rules=class_keyword_remove

**Result**:
=> Exactly the same issue

**Comment by julienfalque** [comment]
Closing as #4601 has been merged.
