### ISSUE TITLE
Bug - Convert typehint to comment

### ISSUE THREAD

**Issue by Selion05** [FriendsOfPHP/PHP-CS-Fixer#4558]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
`$ php -v
PHP 7.3.9 (cli) (built: Aug 29 2019 12:55:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`$ php-cs-fixer -V
PHP CS Fixer 2.15.3 Europe Round by Fabien Potencier and Dariusz Ruminski
`

#### The command you use to run PHP CS Fixer:
` php-cs-fixer fix --rules=@PhpCsFixer test.php`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

use Symfony\Component\Validator\ConstraintViolation;

foreach ($errors as $error) {
    /* @var ConstraintViolation $error */
    //...
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

use Symfony\Component\Validator\ConstraintViolation;

foreach ($errors as $error) {
    // @var ConstraintViolation $error
    //...
}

```

 * with the changes you expected instead:
none

**Comment by kubawerlos** [comment]
There is no bug here, all is working fine in this case.

`@PhpCsFixer` contains a rule `single_line_comment_style` which is making the change as `/* @var ConstraintViolation $error */` is not typehint comment for 2 reasons:

 - it is a regular comment (staring with `/*`) and not PHPDoc comment (staring with `/**`) and the latter is used to document code - such as adding typehints
 - PHPDoc with [`@var`](https://docs.phpdoc.org/references/phpdoc/tags/var.html) must be placed [before](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#4-basic-principles) the variable it typehints and in your example it is after the variable

**Comment by Selion05** [comment]
ahh well actually the original started with `/**`. I didn't notice that.

and placing the typehint before the var works. Thanks for the clarification!
