### ISSUE TITLE
declare_strict_types misplaces declare statement next to <?php

### ISSUE THREAD

**Issue by jdufresne** [FriendsOfPHP/PHP-CS-Fixer#4567]
Per [PSR-12](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements), declare statements should be their own block, separated from the opening `<?php` by a newline.

#### The PHP version you are using (`$ php -v`):

```
$ php -v
PHP 7.3.9 (cli) (built: Aug 27 2019 22:52:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

```
$ ./vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.15.3 Europe Round by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:

```
$ ./vendor/bin/php-cs-fixer fix --rules declare_strict_types --allow-risky=yes ~/Foo.php
```

#### The configuration file you are using, if any:

none

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class A
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php declare(strict_types=1);

class A
{
}
```

 * with the changes you expected instead:
```php
<?php

declare(strict_types=1);

class A
{
}
```

**Comment by kubawerlos** [comment]
PSR-12 does not claim that:

> declare statements should be their own block, separated from the opening `<?php` by a newline.

It claims instead:

> When the opening `<?php` tag is on the first line of the file, it MUST be on its own line with no other statements

and we have fixer that handles this, it is `blank_line_after_opening_tag`.

**Comment by jdufresne** [comment]
Hmnm, I'm reading this:

> The header of a PHP file may consist of a number of different blocks. If present, each of the blocks below MUST be separated by a single blank line

It then goes on to list "Opening `<?php` tag" and "One or more declare statements" as separate blocks.

**Comment by kubawerlos** [comment]
Yes, sorry, my bad, I went through the page too quickly.

Still, using `blank_line_after_opening_tag` and `declare_strict_types` together will cover PSR-12 requirements, right?

Other things are not done: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502

**Comment by jdufresne** [comment]
Perhaps that is the case. I was under the impression that php-cs-fixer conformed to the PSR style standards out of the box with no additional configuration. I suppose I'm reporting that if PSR is intended as the default that is not the case. FWIW, when using just `declare_strict_types` on the command line, I was surprised by the result not conforming to the PSR standard.

**Comment by SpacePossum** [comment]
Thanks fro asking. 

Looking at the fixer; it was created way before PSR12 was approved, which might explain why it is not compliant OOTB. On 3.0.0 we could set a new default configuration for the tool following PSR12. IMHO; even than not each individual rule would have to create PSR12 compliant code, as long the end result is (like we have done with any PSR so far).

Discussion can continue here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502
