### ISSUE TITLE
Should add space around = of arguments with default values

### ISSUE THREAD

**Issue by jdufresne** [FriendsOfPHP/PHP-CS-Fixer#4568]
Per [PSR-12](https://www.php-fig.org/psr/psr-12/#45-method-and-function-arguments), functions and methods arguments with default values should be formatted with a space around the `=`.

#### The PHP version you are using (`$ php -v`):

```
$ php -v
PHP 7.3.9 (cli) (built: Aug 27 2019 22:52:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

```
$ ./vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.15.3 Europe Round by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:

```
./vendor/bin/php-cs-fixer fix ~/Foo.php
```

#### The configuration file you are using, if any:

None. 

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):

```php
<?php

class Foo
{
    public function bar($x=42)
    {
        return $x;
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:

No change.

 * with the changes you expected instead:

```php
<?php

class Foo
{
    public function bar($x = 42)
    {
        return $x;
    }
}
```

**Comment by kubawerlos** [comment]
Where is that explicitly written? You deduced it from the examples. Similarly some can say all namespaces must be named `Vendor\Package` ;)

Anyway, run `./vendor/bin/php-cs-fixer fix ~/Foo.php --rules=binary_operator_spaces` and this will do the trick.

**Comment by jdufresne** [comment]
> Where is that explicitly written? You deduced it from the examples.

You're right that it is not explicitly stated. It is just the way I always see it written, such that it looks like expected practice. I also see is many many PHP packages use this style, further suggesting to me that this is an entrenched practice.

 > Anyway, run ./vendor/bin/php-cs-fixer fix ~/Foo.php --rules=binary_operator_spaces and this will do the trick.

Okay. I was under the impression that not using a configuration should apply the PSR standard rules by default. If that is not the case, no worries.

**Comment by kubawerlos** [comment]
> I was under the impression that not using a configuration should apply the PSR standard rules by default

Yes, but PSR-2, not PSR-12. Maybe PSR-12 would be the default for [v3](https://github.com/FriendsOfPHP/PHP-CS-Fixer/milestone/67).
