### ISSUE TITLE
I notice that in master #d39b456 the sorting order of @throws in phpdoc is not stable

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#4576]
Re-running php-cs-fixer changes the ordering of multiple @throws lines in a single phpdoc.

I know, master is not 'stable'. So YMMV, yaddayadda, etc.

Maybe these settings have something to do with it:

```
    ->setRules([
        '@PSR1' => true,
        '@PSR2' => true,
        '@PHP71Migration' => true,
        '@PhpCsFixer' => true,
        'concat_space' => ['spacing' => 'one'],
        'phpdoc_separation' => false,
        'phpdoc_align' => false,
//        'comment_to_phpdoc' => true,
    ])
```

**Comment by SpacePossum** [comment]
Hi,
can you share some sample code where you've seen this?

**Comment by HenkPoley** [comment]
```
    /**
     * @param Request $request
     * @param int $eventId 
     * @param string $lang
     * @return string|Response
     * @throws Exception
     * @throws QueryException
     * @throws ValidationException
     * @throws MyException
     */
    public function store(Request $request, int $eventId, string $lang) {
        // Some code
    }
```

Executing php-cs-fixer appears to take the top @throws and put it at the bottom.

**Comment by SpacePossum** [comment]
Running on https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/627e39cb0aa717e34cc5d4137df370c885297744 and on 2.15 I get the same results with your configuration and sample code.

Can you provide the input code and output code together with the result of the command when running with `-vvv`, for example `$php-cs-fixer fix -vvv` ?

**Comment by HenkPoley** [comment]
I don't see the behaviour I saw back then (on a different codebase) on my current codebase (with PHP CS Fixer 2.16.3).

I never figured out what caused the leapfrogging behaviour. We don't extend Exception in this codebase (only stuff in vendor/ does that). That's just about the only thing I can come up with. That 'custom' Exception classes are in a different list, that cause it to be picked in a differing order.

**Comment by SpacePossum** [comment]
all good, thanks for reporting back!
