### ISSUE TITLE
phpdoc_types_order changes string default value in @method

### ISSUE THREAD

**Issue by iluuu1994** [FriendsOfPHP/PHP-CS-Fixer#4599]
https://php-cs-fixer-playground.herokuapp.com/run/8767d840-7ffd-406a-b7dd-cbb3d7a781a9

```diff
 <?php
 
 /**
- * @method void bar(string $delimiter = ',<br/>')
+ * @method void bar(string $delimiter = ',<|br/>')
  */
 class Foo
 {
 }
```

Side node: Playgrounds make it much easier to post issues and also for you to understand them. Why not make a tool like this mandatory for submitting issues?

**Comment by laurent35240** [comment]
Hi,

I created this PR #4609 for fixing this issue.
The problem was from the comma in default string value that was wrongly parsed by a regular expression

Laurent
