### ISSUE TITLE
force 'Your php-cs-version is outdated: please upgrade it.'

### ISSUE THREAD

**Issue by kamarton** [FriendsOfPHP/PHP-CS-Fixer#4611]
First I wanted to use from vendor with a composer, but i get the "Your php-cs-version is outdated: please upgrade it." problem.

I installed it globally according to the [readme.md](https://github.com/FriendsOfPHP/PHP-CS-Fixer#globally-manual), but the problem is the same.

```bash
$ php-cs-fixer fix --dry-run
Your php-cs-version is outdated: please upgrade it.
$ php-cs-fixer self-update
php-cs-fixer is already up to date.
$ php-cs-fixer fix --dry-run
Your php-cs-version is outdated: please upgrade it.
```

#### The PHP version you are using (`$ php -v`):
```
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.15.3 Europe Round by Fabien Potencier and Dariusz Ruminski (705490b)
```

#### The command you use to run PHP CS Fixer:
```bash
$ php-cs-fixer fix --dry-run
```

**Comment by SpacePossum** [comment]
Hi!

Can you give us the output of;
`$ composer info -D` 
?

Im trying to find this error message, but no luck so far.

You can also try; `php-cs-fixer self-update --force` if you want to upgrade from 1.x to 2.x line. It might break on you configuration, but upgrading is highly recommended.

**Comment by SpacePossum** [comment]
Closing as the needed information to continue has not been provided. If someone has more information on this topic than please comment belong and I'll be happy to reopen.
