### ISSUE TITLE
Feat: Fixer for Abstract Text Replacement

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#4612]
I was thinking that there could be fixer that is able to replace abstract text.

For example in our intranet we moved service to different domain, so all `@see` or `@link` urls could be replaced to new domain.

Does such use-case deserve a fixer?

**Comment by keradus** [comment]
how would it be different than just running `sed` ?

**Comment by julienfalque** [comment]
I agree. This use case seems to be a one-time change. Using `sed` or any search and replace tool might be fine. No need to have a tool that always applies the rule and likely never applies change except the first time.

**Comment by glensc** [comment]
given the rule is applied to some "company-foo-codestyle", the difference is that cs-fixer is typically applied to all code, regardless of the project, using sed means you actually know you want to do those kind text replacements. but the project may have no matches at all at that time. and the "wrong" url could be added in a later commit.

this is based on a given example, there might be similar use-cases.

**Comment by voku** [comment]
I could imagine an use-case. For example if  there are many branches with different features and you can't use sed just once.

**Comment by julienfalque** [comment]
I still fail to see why this should be done by PHP CS Fixer specifically. Having multiple branches would not change much: you would run PHP CS Fixer on each branch instead of sed or whatever tool that can already do that. This remains true if you don't have files to fix yet, but you may in the future: add that tool to your dev workflow and/or your CI.

**Comment by voku** [comment]
Yes you are right, we can also use "sed" as pre-commit hook + in the CI. Maybe the "law of the hammer" problem :) but otherwise you can't use "sed" in Windows.

**Comment by SpacePossum** [comment]
I think an Abstract Text Replacement is out of the scope of the project. A generic/abstract rule one would either not provide much or would be complex or abstract in nature.
Creating a custom (one off) rule for the use cases described should be well doable when `sed` is really not an option. 
Closing for now, however feel free to keep discussing, we can always reopen if the request is popular :)

**Comment by glensc** [comment]
Seems the abstract text replacement could be done with `rector`:
- https://github.com/rectorphp/rector
