### ISSUE TITLE
It would be nice to have a fixer that adds `$`'s to `@property` PhpDoc. 

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#4616]
It would be nice to have a fixer that adds `$`'s to `@property` PhpDoc. Eg.

```
@property int id
```

to:

```
@property int $id
```

[laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)'s `php artisan ide-helper:models` requires the properties to start with a `$` for automatic updating of the PhpDoc.

**Comment by kubawerlos** [comment]
```
   @property int
   @property x
   @property x optional
   @property int x
   @property int x description
   @property int x description with variable $x in content
```
Which should have `$` added?

**Comment by SpacePossum** [comment]
`@property` is not part of the [PSR5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md) proposal and [phpDocumentor](https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.property.pkg.html) doesn't state a formal format neither.

I think it might be better fit for a custom fixer for the `laravel` project and not in this project until PSR5 is finalized (or some other standard we like to support).

**Comment by SpacePossum** [comment]
Closing for now, however feel free to keep discussing! 
Based on other input we can always reopen :)
