### ISSUE TITLE
Ignore lines / methods

### ISSUE THREAD

**Issue by Jamesking56** [FriendsOfPHP/PHP-CS-Fixer#4629]
## The PHP version you are using (`$ php -v`):
=> PHP 7.2.24-1+ubuntu18.04.1+deb.sury.org+1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.13.0 Yogi's BBQ

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix`

## Issue

It would be helpful if we could ignore lines / methods in our code to bypass the CS fixing. I have a method that extends Symfony and I use the fixer which changes `\DateTime` to `\DateTimeImmutable`. The problem is, Symfony's method signature uses `\DateTime` but my fixer changes my extended method to `\DateTimeImmutable`.

The issue with that is it causes a php error `Declaration of ... must be compatible to ...`

So how can I make this method signature excluded without affecting the rest of my codebase?

**Comment by julienfalque** [comment]
This is currently not possible. See #4512 for a similar discussion. Closing as duplicate.
