### ISSUE TITLE
BlankLineAfterOpeningTagFixer conflicts with PHPStorm "ignore for file" annotation

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#4631]
PHPStorm allows to disable inspections for a whole file. It does so by adding an annotation on the PHP opening tag line `<?php /** @noinspection ... */`. This is broken by `BlankLineAfterOpeningTagFixer`.

#### The PHP version you are using (`$ php -v`):
`PHP 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:23) ( NTS )`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.16.0 Yellow Bird`

#### The command you use to run PHP CS Fixer:
Running through `vendor/bin/ecs check src/`.

#### The configuration file you are using, if any:
```yaml
# easy-coding-standard.yml
services:
    PhpCsFixer\Fixer\Strict\DeclareStrictTypesFixer: ~
    PhpCsFixer\Fixer\PhpTag\BlankLineAfterOpeningTagFixer: ~
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php /** @noinspection StaticClosureCanBeUsedInspection */

namespace ...;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

declare(strict_types=1);

 /** @noinspection StaticClosureCanBeUsedInspection */

namespace ...;
```

 * with the changes you expected instead:
```php
<?php /** @noinspection StaticClosureCanBeUsedInspection */

declare(strict_types=1);

namespace ...;
```

**Comment by kubawerlos** [comment]
You want to have a fixer `BlankLineAfterOpeningTagFixer` and want to have content after opening tag.

It seems like a conflict in your expectations - either disable the rule and have the comment after opening tag or let the fixer does its job.

**Comment by gnutix** [comment]
Maybe you're right... As I didn't enable this rule specifically (instead I included a bunch of pre-made rules sets which included it), I didn't really thought that I could just skip it individually. Guess it makes no sense for this rule to support such a case indeed.
