### ISSUE TITLE
Typed params keep getting removed

### ISSUE THREAD

**Issue by Christophvh** [FriendsOfPHP/PHP-CS-Fixer#4642]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.3 & 7.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16 yellow bird

#### The command you use to run PHP CS Fixer:
=> .fix

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'combine_consecutive_unsets' => true,
        'general_phpdoc_annotation_remove' => ['expectedException', 'expectedExceptionMessage', 'expectedExceptionMessageRegExp'],
        'no_extra_consecutive_blank_lines' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block'],
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => ['sortAlgorithm' => 'length'],
        'php_unit_strict' => true,
        'php_unit_test_class_requires_covers' => true,
        'phpdoc_order' => true,
        'semicolon_after_instruction' => true,
        'single_trait_insert_per_statement' => false,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude([
                'tests',
                'storage',
                'node_modules',
                'vendor',
            ])
            ->in(__DIR__)
    )
;

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    /**
     * Show the retribution data from external API based on OGM.
     *
     * @param string         $ogm
     * @param RetributionAPI $retributionAPI
     *
     * @return json $response
     */
    public function show($ogm, RetributionAPI $retributionAPI)
    {
        return $retributionAPI->toJsonResponse($retributionAPI->findByOgm($ogm));
    }
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    /**
     * Show the retribution data from external API based on OGM.
     *
     * @param string         $ogm
     *
     * @return json $response
     */
    public function show($ogm, RetributionAPI $retributionAPI)
    {
        return $retributionAPI->toJsonResponse($retributionAPI->findByOgm($ogm));
    }
```

 * with the changes you expected instead:
```php
    /**
     * Show the retribution data from external API based on OGM.
     *
     * @param string $ogm
     * @param RetributionAPI $retributionAPI
     *
     * @return json $response
     */
    public function show($ogm, RetributionAPI $retributionAPI)
    {
        return $retributionAPI->toJsonResponse($retributionAPI->findByOgm($ogm));
    }
```

How do I stop type hinted parameters from being removed? If I type hint parameters in the method call the params get removed. It only works if I remove the type-hint from the doc-block or remove it from the method parameters itself.

**Comment by julienfalque** [comment]
The `@param` annotation is most likely removed by the `no_superfluous_phpdoc_tags` rule which is now part of the `@Symfony` ruleset. If so, the behavior you see is expected: the annotation is superfluous because it adds no value regarding the definition of the `$retributionAPI` argument. It only defines its type (`RetributionAPI`) which is already defined by an actual type definition. Hence the annotation is redundant and so it is removed.

If you don't want this behavior, you can either disable the rule or add a description to the `@param` annotation so that it actually adds value (details/reasoning) regarding the definition of the argument.
