### ISSUE TITLE
NullableTypeDeclarationForDefaultNullValueFixer does not handle NULL

### ISSUE THREAD

**Issue by KacerCZ** [FriendsOfPHP/PHP-CS-Fixer#4646]
Fixer 'nullable_type_declaration_for_default_null_value' does not work if default value is written in uppercase 'NULL', it works only for lowercase form 'null'.

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.3.11

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.16.0 Yellow Bird by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> PHP_CS_FIXER_FUTURE_MODE=1 vendor/bin/php-cs-fixer fix --dry-run -v --diff

#### The configuration file you are using, if any:
```php
$finder = \PhpCsFixer\Finder::create()
		->in( __DIR__ )
		->path( '/^src/');

$rules = [ 'nullable_type_declaration_for_default_null_value' => TRUE ];

$config = \PhpCsFixer\Config::create()
		->setRules( $rules )
		->setRiskyAllowed( TRUE )
		->setFinder( $finder );

return $config;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
function defaultNull( string $input = NULL ) {}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
function defaultNull( string $input = NULL ) {}
```

 * with the changes you expected instead:
```php
function defaultNull( ?string $input = NULL ) {}
```

**Comment by kubawerlos** [comment]
[Fix](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4632) is already approved.
