### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by garak** [FriendsOfPHP/PHP-CS-Fixer#4647]
Symfony 5 is [just around the corner](https://symfony.com/blog/symfony-5-0-curated-new-features), but I can't use it in any of my projects since I also require this lib.

**Comment by julienfalque** [comment]
Please see #4608.

**Comment by julienfalque** [comment]
Note: if you only use PHP CS Fixer as a tool, you can install it in a dedicated directory (e.g. `tools/php-cs-fixer/composer.json`) so it doesn't conflict with the actual dependencies of your project.

**Comment by garak** [comment]
@juliendufresne that's a suitable solutions for projects/applications, not for libraries/bundles

**Comment by kubawerlos** [comment]
> not for libraries/bundles

why not?

BTW wrong Julien 😃

**Comment by garak** [comment]
Sorry for the wrong reference @julienfalque 
@kubawerlos because a library has probably a wider audience and wants to ensure every user getting all relevant tools to keep quality. Moreover, it can use this tool in some automated checks, so keeping it the dev requirement can be easier than install an external package

**Comment by kubawerlos** [comment]
> it can use this tool in some automated checks, so keeping it the dev requirement can be easier than install an external package

I still cannot see what's the problem with Julien's solution - "dev requirement" is simply what we got used to for years.

Check [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers) - nothing in `require-dev` and still 2 commands (`composer update` and `composer verify`) are all that you need to set it up and run all checks.

**Comment by julienfalque** [comment]
Closing as #4608 was merged.

**Comment by ssaki** [comment]
@julienfalque would you also create a new tag so it's not necessary to install dev version?

**Comment by Jean85** [comment]
A tag on 2.15 was created (2.15.4) but we're still missing a tag on 2.16, and Composer is preferring it, downgrading Symfony as a result. Can we please have a 2.16.1 too?

**Comment by keradus** [comment]
it was released to 2.15.5 and 2.16.1 on same time. it was never met to go to 2.15.4.
looks like typo in your msg.

**Comment by Jean85** [comment]
Nope, I mistakenly thought that 2.15.4 included #4608, that's why I was confused. Thanks!
