### ISSUE TITLE
Braces Rule Adds Unexpected Spacing

### ISSUE THREAD

**Issue by nehoffman** [FriendsOfPHP/PHP-CS-Fixer#4651]
#### The PHP version I'm using (`$ php -v`):
PHP 7.3.11 (cli) (built: Nov 11 2019 23:27:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

#### PHP CS Fixer version I'm using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.0 Yellow Bird by Fabien Potencier and Dariusz Ruminski

#### The different commands I used to run PHP CS Fixer:
```
php-cs-fixer fix ./path/myfile.php -vvv --rules="{\"braces\": true}"
php-cs-fixer fix ./path/myfile.php -vvv --rules="{\"braces\": {\"allow_single_line_closure\": false}}"
php-cs-fixer fix ./path/myfile.php -vvv --rules="{\"braces\": {\"allow_single_line_closure\": true}}"
```

#### PHP code sample:
 * before running PHP CS Fixer (no changes):
```php
<?php
    $arr = ["1", "2", "3"];
    foreach($arr as $v) {
        echo $v;
    }
?>
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
    $arr = ["1", "2", "3"];
    foreach ($arr as $v) {
        echo $v;
    }
?>
```

 * with the changes you expected instead:
```php
<?php
    $arr = ["1", "2", "3"];
    foreach($arr as $v) {
        echo $v;
    }
?>
```

PHP CS Fixer is adding a space between the foreach statement and the open parenthesis when the braces rule is turned on. Running either of the two commands listed below will result in no changes to the file, which is the expected behavior.

```
php-cs-fixer fix ./path/myfile.php -vvv --rules="{\"braces\": false}"
php-cs-fixer fix ./path/myfile.php -vvv --rules="{\"braces\": {}}"
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

I think the change is good, however we know that it would be better if you would have more configuration options by splitting up the `braces` rule. Please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/823 for the discussion on this topic. Closing as it would be better to continue the discussion on one issue.
