### ISSUE TITLE
Is there any configuration to do not add braces on inline 'if' ?

### ISSUE THREAD

**Issue by MarceloLuis1997** [FriendsOfPHP/PHP-CS-Fixer#4686]
I am new to PHP-CS-Fixer and I was wondering if there is any configuration to do not automatically add curly braces on inline statements, for example

```
//I want to keep this way
if (empty($var))
    throw new Exception('An error message..')
```

but when I format it turns into

```
if (empty($var)) {
    throw new Exception('An error message..')
}
```

I only have this config so far:

```
    ->setRules([
          'braces' => [
			'allow_single_line_closure' => true,
			'position_after_functions_and_oop_constructs' => 'same'
		  ]
    ])
```

Is there any way to do not add curly braces in cases like this?

**Comment by SpacePossum** [comment]
Hi @MarceloLuis1997 ,

Currently this is not possible, we are looking into splitting up the braces fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/823) to bring configuration options.

However I doubt we will be supported your requested code style as it is not part of a standard or used by a bigger community, which is a requirement for most of our rules in this project.

Please feel free to keep discussing the feature request below, we can always reopen when this request is actually very popular :)
