### ISSUE TITLE
declare_strict_types: adds strict_types=1 even though strict_types=0 is set

### ISSUE THREAD

**Issue by JeroenVanOort** [FriendsOfPHP/PHP-CS-Fixer#4687]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.3.11-1+ubuntu18.04.1+deb.sury.org+1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.16.1 Yellow Bird

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix test.php --config=.php_cs_test

#### The configuration file you are using, if any:
```php
<?php

declare(strict_types=1);

return PhpCsFixer\Config::create()
    ->setRules([
        'declare_strict_types' => true,
    ])
    ->setRiskyAllowed(true);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php declare(strict_types=0);
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php declare(strict_types=1);
declare(strict_types=0);
```

 * with the changes you expected instead:
```php
<?php declare(strict_types=0);
```

**Comment by julienfalque** [comment]
I don't think the rule supports ignoring files where strict mode is explicitly disabled. IMO this would be a new feature.

Though the current behavior (enabling strict mode everywhere) is buggy too: it should update the existing statement, i.e.:
```diff
-<?php declare(strict_types=0);
+<?php declare(strict_types=1);
```

**Comment by JeroenVanOort** [comment]
While being very content with your swift reply, I'd like to share my thoughts on what part of this issue I consider a bug and what I consider a requested feature.

In my opinion, this rule's name and summary allow for two interpretations:
1. Require `strict_types` to be declared, regardless of it's value.
2. Require `strict_types=1`.

In my opinion, number 1 is the correct interpretation, as the name and summary do not explicitly specify a value. However, I do see a valid use case in number 2.

Therefore, I think that the bug is that the declaration is made twice while the file should have been left unchanged and that the requested feature is having a configurable option to allow forcing `strict_types=1`.

**Comment by kubawerlos** [comment]
@JeroenVanOort 

> this rule's name and summary allow for two interpretations:

Agree, though the reason why it is risky ("forcing strict types will stop non strict code from working") make it clear that it should be the 2nd interpretations.

**Comment by julienfalque** [comment]
#4689 has been merged so the reported bug should be fixed. I keep this issue open regarding the feature request part (adding an option to prevent updating existing statements).
