### ISSUE TITLE
Changing label "bug" to "surprise feature"

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#4705]
> I, and many others, find the use of the term "bug" to be offensive. You have no idea if the "bug" you are reffering to would like to be called a "bug", which is comparing them to an insect - unwanted, unneeded, and maybe worse, wants to be called a "bug". You should instead use the term "surprise feature" as a less offensive term for describing such things.

Taken from: https://github.com/microsoft/vscode/issues/87424 😃 

See how cool it looks [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pulls?q=is%3Apr+is%3Aclosed).

**Comment by SpacePossum** [comment]
>insect - unwanted, unneeded,

Well that is very offensive to bugs! I like bugs and appreciate them as any other creatures on this planet. I often feel guilty when I buy bugs and feed them to my adopted lizard. They are needed and they are wanted. Without bugs we will all die.

Besides, most bugs reported here in the project are not surprise features or any other feature for that matter. So yeah, maybe the "bugs" here are given to _much_ credit by being called bugs, however calling them "features" is as much incorrect IMHO. 

I would propose calling these "honest mistakes" and call it a day :)

**Comment by SpacePossum** [comment]
closing for now, lets poll on gitter if we want to update the labels and lets go from there :)
