### ISSUE TITLE
SingleTraitInsertPerStatement - wrong formatting

### ISSUE THREAD

**Issue by javaDeveloperKid** [FriendsOfPHP/PHP-CS-Fixer#4709]
#### The PHP version you are using (`$ php -v`):
7.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.15.1

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
class Test
{
    use FirstTrait,
        SecondTrait,
        ThirdTrait;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
class Test
{
    use FirstTrait;
    use
        SecondTrait;
    use
        ThirdTrait;
}
```

 * with the changes you expected instead:
```php
class Test
{
    use FirstTrait;
    use SecondTrait;
    use ThirdTrait;
}
```

**Comment by SpacePossum** [comment]
Thanks for reporting @javaDeveloperKid and thanks @kubawerlos for picking this up :)

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4710
