### ISSUE TITLE
Fix more alias-like language construct, eg, die() -> exit

### ISSUE THREAD

**Issue by bluedasher13** [FriendsOfPHP/PHP-CS-Fixer#4717]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
echo doubleval('123.0') . "\n";

echo imap_create(null, 0) . "\n";

echo mbsplit('/./', 'str') . "\n";

die();

die('message');

exit;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
echo floatval('123.0') . "\n";

echo imap_createmailbox(null, 0) . "\n";

echo mb_split('/./', 'str') . "\n";

die();

die('message');

exit;
```

 * with the changes you expected instead:
```php
echo floatval('123.0') . "\n";

echo imap_createmailbox(null, 0) . "\n";

echo mb_split('/./', 'str') . "\n";

exit;

echo 'message';
exit;

exit;
```

I know there's a option called `no_alias_functions`, it could replace aliases of ``imap_*``, ``mb*``, and internal (``chop``, ``close``, ``doubleval``, ``fputs``, ``get_required_files``, ``ini_alter``, ``is_double``, ``is_integer``, ``is_long``, ``is_real``, ``is_writeable``, ``join``, ``key_exists``, ``magic_quotes_runtime``, ``pos``, ``show_source``, ``sizeof``, ``strchr``, ``user_error``) functions.

But I wish that there's an another option which called ``no_mixed_die_exit``, `no_alias_like_language_construct`, or anything we could understand. And it can fix alias-like language construct, for example, replace ``die();`` and ``die('str');`` with ``exit;`` and ``echo 'str'; exit;`` (working with ``no_mixed_echo_print``).

**Comment by kubawerlos** [comment]
Can you give another example? :)

Because this is the only one missing - already discussed [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1692).

**Comment by SpacePossum** [comment]
Would be a nice fixer :)
I think `no_mixed_die_exit` sounds alright, making it configurable. I don't think there are other language constructs with aliases out there?

**Comment by kubawerlos** [comment]
I'm not sure about the configurable part - isn't `die` alias of `exit`?

**Comment by SpacePossum** [comment]
>isn't `die` alias of `exit`

[it is](https://www.php.net/manual/en/aliases.php) , so no config than?

**Comment by SpacePossum** [comment]
done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4740
