### ISSUE TITLE
The "yoda_style" option can be a risky rule while working with pecl-php-operator extension?

### ISSUE THREAD

**Issue by bluedasher13** [FriendsOfPHP/PHP-CS-Fixer#4719]
I found **[pecl-php-operator](https://github.com/php/pecl-php-operator)** extension that can overload PHP operators.

If it works, then `$a === 100` won't be equivalent to `100 === $a` after overloading `__is_identical($arg)` method and the "yoda_style" option can be a risky rule ?

Sorry to ask such a silly question, but I don't know whether this option is really safe or not.

https://github.com/php/pecl-php-operator

http://pecl.php.net/package/operator

**Comment by kubawerlos** [comment]
Wouldn't it still be the same and in both cases function `__is_identical` would be called?

**Comment by SpacePossum** [comment]
Hi @bluedasher13 ,

Interesting extensions :) 
We don't support these, however we can always try to not break things for these extensions. If I read the docs correctly I have the same question as @kubawerlos , flipping to yoda or back won't change anything here?

**Comment by SpacePossum** [comment]
closing for now, happy to reopen if details show there is an action for us here, please share such details if you've any :)
