### ISSUE TITLE
PHP-CS-FIXER ERROR WITH PHPSTORM

### ISSUE THREAD

**Issue by CoffeyKang** [FriendsOfPHP/PHP-CS-Fixer#4725]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.211..................................

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> ....................2.16.1................

#### The command you use to run PHP CS Fixer:
=> ....................................

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> ....................................
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> ....................................
```

 * with the changes you expected instead:
```php
=> ....................................
```

hello, I installed `php-cs-fixer` for a new laptop in PHPstorm, in `terminal` I run `php-cs-fixer --version` it works, but it always fail in `phpstorm validate`. The error message is simple ` Can not run php cs fixer` .
Do you have any idea about this.

Btw, I use laragon as my developing environment

**Comment by SpacePossum** [comment]
Hi and thanks for your report,

Since your issue is not with the tool itself but with a 3rd party integration I think getting help from that party might be the best. I'll leave this open for a bit to see if others here know about your issue, after that I 'll close it as this issue is outside of the scope of this project.

**Comment by SpacePossum** [comment]
closing for now as we do not work on the PHPStorm integration, maybe someone on their support forums can help?

**Comment by keradus** [comment]
looks like you need to teach PHPStore where is your PHP CS Fixer file ;) best case - install it per project and let PHPStorm discover it ;)
