### ISSUE TITLE
fully_qualified_strict_types messes up when same classname is imported from global and non-global namespace

### ISSUE THREAD

**Issue by oprypkhantc** [FriendsOfPHP/PHP-CS-Fixer#4726]
Hey there. `fully_qualified_strict_types` does strange things when a class with same name is imported from both the global namespace and a non-global one.

#### The PHP version you are using (`$ php -v`):
=> 7.1.30

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1

#### The command you use to run PHP CS Fixer:
=> ./vendor/bin/php-cs-fixer fix -v

#### The configuration file you are using, if any:
```php
=> fully_qualified_strict_types => true
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
namespace App\Models {
    class TestModel {}
}

namespace {
    class TestModel {}
}

namespace App {
    use App\Models\TestModel;
    use TestModel as TestModelAlias;

    class TestTest
    {
        public function test(): TestModel
        {
            TestModelAlias::class;
        }
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
- public function test(): TestModel
+ public function test(): TestModelAlias
```

 * with the changes you expected instead:
=> None

**Comment by SpacePossum** [comment]
Hi @oprypkhantc and thanks for reporting,

Using 2.15 and 2.16 with the sample code and the `fully_qualified_strict_types` I cannot reproduce the issue. Are you sure about the fixer name that does this? If you add `-vvv` when running, which details do you get?

**Comment by oprypkhantc** [comment]
Pretty sure - initially I only tested it with @PSR2 and saw `fully_qualified_strict_types` in verbose output near file name. Just now I tested it with this rule alone and it's still the same, unfortunately.

-vvv output (not any different from -v):
```
Loaded config default from "/Users/user/.../.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) test.php (fully_qualified_strict_types)

Fixed all files in 0.048 seconds, 16.000 MB memory used
```

Config:

```
$config = PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'fully_qualified_strict_types' => true,
    ])
    ->setIndent("\t")
    ->setFinder($finder);

return $config;
```

**Comment by chr-hertel** [comment]
we are running into this with version 3.3.2

my example to reproduce this was:
```php
use App\DateTime;

class Example
{
    public function foo(DateTime $dateTime)
    {
    }

    public function bar(\DateTime $dateTime)
    {
    }
}
```

fixer claims to apply `fully_qualified_strict_types`

**Comment by chr-hertel** [comment]
can confirm that this fixes our issue! Thanks for your effort @SpacePossum!

**Comment by SpacePossum** [comment]
thanks for checking and letting us know : D
