### ISSUE TITLE
`global_namespace_import` do not work properly with imported class in docstrings

### ISSUE THREAD

**Issue by koninka** [FriendsOfPHP/PHP-CS-Fixer#4730]
Hello, I use the rule `global_namespace_import` and found inconsistent behavior of this rule.

#### The PHP version you are using (`$ php -v`):
```
$ php -v
PHP 7.1.33 (cli) (built: Oct 25 2019 10:53:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
$ bin/php-cs-fixer -V
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
`bin/php-cs-fixer fix --verbose`

#### The configuration file you are using, if any:
```php
$config = PhpCsFixer\Config::create()
    ->setRules([
        'global_namespace_import' => true,
    ])
    ->setUsingCache(true)
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace App;
use RuntimeException;
use Throwable;

class SomeClass
{
    /**
     * @throws Throwable
     */
    public function test()
    {
        throw new RuntimeException('Error');
    }

    /**
     * @throws \Throwable
     */
    public function test2()
    {
        throw new \RuntimeException('Error');
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace App;
use RuntimeException;
use Throwable;

class SomeClass
{
    /**
     * @throws Throwable
     */
    public function test()
    {
        throw new RuntimeException('Error');
    }

    /**
     * @throws \Throwable
     */
    public function test2()
    {
        throw new RuntimeException('Error');
    }
}
```

 * with the changes you expected instead:
```php
<?php

namespace App;
use RuntimeException;
use Throwable;

class SomeClass
{
    /**
     * @throws Throwable
     */
    public function test()
    {
        throw new RuntimeException('Error');
    }

    /**
     * @throws Throwable
     */
    public function test2()
    {
        throw new RuntimeException('Error');
    }
}
```

As you can see, the cs-fixer recognized that I was using the global `RuntimeException` and removed the full class name, but he did not do the same for docstring with the `\Throwable` interface. Moreover, if I had not imported `\Throwable`, then he would have successfully added a use statement for it and changed the docstring

**Comment by SpacePossum** [comment]
thanks for reporting @koninka :+1:  and of course thanks for fixing @gharlan :+1:  :)
