### ISSUE TITLE
Files that were not fixed due to errors reported during linting after fixing (string variable expansion?)

### ISSUE THREAD

**Issue by jdufresne** [FriendsOfPHP/PHP-CS-Fixer#4734]
#### The PHP version you are using (`$ php -v`):
```
PHP 7.3.13 (cli) (built: Dec 17 2019 10:29:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
```
vendor/bin/php-cs-fixer fix src/path/file.php
```

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()->setRules(['@PhpCsFixer' => true]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function foo($tag, $style='')
{
    return "<$tag{$style}>";
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$ vendor/bin/php-cs-fixer fix src/path/file.php  
Loaded config default from ".../.php_cs".
Using cache file ".php_cs.cache".

Fixed all files in 0.007 seconds, 12.000 MB memory used

Files that were not fixed due to errors reported during linting after fixing:
   1) .../src/path/fix.php
```

Before running php-cs-fixer, the file passes `php -l`.

**Comment by kubawerlos** [comment]
I don't understand what are you reporting here.

> were not fixed

So after running php-cs-fixer the file would still pass `php -l` as it was not changed.

**Comment by jdufresne** [comment]
I'm reporting that the file was not fixed. From the output:

> Files that were not fixed due to errors reported during linting after fixing:

My expectation is that php-cs-fixer should not introduce syntax errors (that are then avoided) preventing a fix, but instead fix the files according to the supplied rules. In my real project this is just one of many files.

**Comment by kubawerlos** [comment]
Oh, after the fixing, sorry, I read it "before" 🤦‍♂

**Comment by SpacePossum** [comment]
this is fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4379 I believe, so will be shipped in next bug fixes releases
