### ISSUE TITLE
broken fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4737]
Further to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4731, the fixer that is responsible for moving statements to a new line should not delete blank lines.

**Comment by GrahamCampbell** [comment]
The original issue was closed and locked too soon. I opened it to start a discussion. I was not suggesting we should just change the trait fixer.

**Comment by SpacePossum** [comment]
please follow the issue template

**Comment by kubawerlos** [comment]
@GrahamCampbell can you provide an example of the change you are describing in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4731? I've tried on `SingleTraitInsertPerStatementFixer` and `single_trait_insert_per_statement,braces.test` and cannot reproduce it there.

**Comment by GrahamCampbell** [comment]
This bug is actually a priority bug. Disabling the cache and doing a 2nd run actually fixes the code correctly.

**Comment by GrahamCampbell** [comment]
Can we re-open this, so I can be reminded that I need to minimally reproduce this, and then actually fix the priorities, which should be quite easy once the issue is identified.

**Comment by julienfalque** [comment]
@GrahamCampbell maybe reproduce first, then submit a new issue with the failing case.

**Comment by GrahamCampbell** [comment]
I have a failing case. It just has 100 or so fixers.

**Comment by SpacePossum** [comment]
Can you maybe share that case? I'm really struggling what you expect us to do here?

**Comment by GrahamCampbell** [comment]
Looks like I already did: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4731.

**Comment by SpacePossum** [comment]
I see now, I cannot help rewriting the priority system, lets hope someone else can :)

**Comment by GrahamCampbell** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4867 shows the issue. Interestingly, I could not reproduce it with fewer than 5 rules!
