### ISSUE TITLE
GitLab reporter - no documentation

### ISSUE THREAD

**Issue by Jamesking56** [FriendsOfPHP/PHP-CS-Fixer#4738]
There is no documentation for how to properly configure the GitLab reporter. I'm struggling to get GitLab to show anything for CS dry run via GitLab CI.

**Comment by kubawerlos** [comment]
https://github.com/codeclimate/spec/blob/master/SPEC.md#data-types?

**Comment by SpacePossum** [comment]
From the readme;

```
The --format option for the output format. Supported formats are txt (default one), json, xml, checkstyle, junit and gitlab.
```

Using that format will give the output usable by gitlab. Maybe @mjanser or @hco can help you with the setup. Doing the setup itself is out of the scope of theis project, as such I'm closing this issue.

**Comment by milgner** [comment]
@Jamesking56 did you find out how to use it? I saw it by chance and would like to know more but couldn't find any information about the Gitlab reporter.
(sorry for commenting on an old GH issue but I couldn't find any other thread or mention anywhere else)

**Comment by keradus** [comment]
please see the following - #4430
we couldn't get official schema of this format even from gitlab themselves. maybe it's the other case now - don't hesitate to help on that, @milgner

**Comment by hco** [comment]
Has been a long time since I last used gitlab - but you should be able to run it an configure the output as a "code quality" artifact. The following links might help:
https://docs.gitlab.com/ee/ci/yaml/#artifactsreportscodequality-starter
https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

**Comment by milgner** [comment]
Much appreciated! I was missing the link to the code quality artifacts! I'll give it a try and will gladly write down some corresponding documentation.

Not sure whether there is a schema somewhere but it's also something I'll try to look into. Might be a couple of weeks, though, as my free time right now is mostly consumed by preparing to move to a new apartment with a pandemic around 😅
