### ISSUE TITLE
Forbid fluent interface

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#4739]
Im curious if we can consider this a code style topic, rather than a static analysis one.

TLDR; i like to forbid any `return $this;`, in favor of a void return type by default.

```php
// before
public function setter($v): self/static/Some/$this {
  $this->v = $v;
  return $this;
}

// after
public function setter($v): void {
  $this->v = $v;
}
```

most likely it should be possible to whitelist valid methods at the configuration level, ie a rule like;

```php
'no_fluent_interface' => [
  'whitelist' => [Builder::class, Some::class.'::method'],
],
```

Thoughts?

**Comment by SpacePossum** [comment]
I think this is out of scope of the project, this is not CS and the changes are heavily changing the meaning of the code.

**Comment by ro0NL** [comment]
im not sure, it's definitevely not a static analysis concern which only validates type info as is. So it's a rule at least :sweat_smile: 

i guess, applying on a existing codebase is risky. Perhaps mark the rule as such :sweat_smile:

**Comment by oprypkhantc** [comment]
Why would you want to do this though?

**Comment by ro0NL** [comment]
IMHO a fluent interface should be explicit, CS-wise; thus 

```php
/** @return $this */
public function fluent(): self {
   return $this;
}
```

to know `$o->fluent()->fluent();` is the same as `$o->fluent(); $o->fluent();`

Yes, im not a big fan of fluent interface, IMHO they only serve the builder pattern.

This rule would counter PHPStorm's behavior, for generating dumb fluent setters on DTOs etc.

In this case i'd like to enforce property (typed as of 7.4) which arent fluent either.

However, pre 7.4 `setter(Type $v)` would be considerable, but to match property semantics it should not be fluent.
