### ISSUE TITLE
Add `static_method` fixer

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#4743]
Similar to `static_lambda`, we could turn any method not referencing `$this` into a static one.

I tend to believe it wouldnt be a risky change, as regular instance calls keep on working: https://3v4l.org/2RjSJ (vice versa as well: https://3v4l.org/fEkVS)

However you cannot opt-out (i.e. keep a non-static method while not referencing $this), but my perosonal reasoning is it keeps the object API clean (pure if you like). This should improve IDE autocompletion at `$this->...`

Thoughts?

**Comment by julienfalque** [comment]
:-1: for me. I don't see the point of making methods static by default until they use `$this`. Static methods tend to make code less flexible and less testable so I try to avoid them as much as possible.

**Comment by SpacePossum** [comment]
I'll link this PR for reference https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4557 (StaticPrivateMethodFixer)

I agree with @julienfalque here, lets see if others have an opinion on this as well

**Comment by ro0NL** [comment]
> Static methods tend to make code less flexible and less testable

that's a design issue at least (eg. not being able to replace/inject deps)

`assertSame('expected', Some::actual())` :man_shrugging: which would be just as hard, or easy, to test as `$some->actual()` considering it's the same implementation.
