### ISSUE TITLE
Allow *some* risky rules

### ISSUE THREAD

**Issue by Taluu** [FriendsOfPHP/PHP-CS-Fixer#4748]
Currently, you allow either all risky rules or none of them. I think being able to "override" this flag on a specific fixer could be useful to allow risky rules case by case instead of globally.

A `risky` option on the abstract fixer could do the trick, I guess ?

**Comment by julienfalque** [comment]
I do see the point of this but I'm not sure it's worth it. You would list more rules you want to enable despite risky rules being disabled, instead of listing more rules you want to disable, despite risky rules being allowed.

**Comment by SpacePossum** [comment]
I think it is not worth it within the current configuration setup, maybe for 3.0

**Comment by keradus** [comment]
Hey! I'm closing this as no traffic around anymore. The idea could be valid, yet it didn't get any movement around.
If any of you see a value in it and are ready to implement it, please draft mini-RFC what you would like to achieve and how.
