### ISSUE TITLE
Problem with rule no_unneeded_final_method

### ISSUE THREAD

**Issue by peter-gribanov** [FriendsOfPHP/PHP-CS-Fixer#4771]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

The rule `no_unneeded_final_method` causes problems. I could disable it, but this is a useful rule.
In this example, i create a base class and forbid it to use the constructor and override in it.
If the constructor is not marked as `final`, then it will be possible to override it and break the behavior of the class.

* https://3v4l.org/bSHWs
* https://3v4l.org/v7fQf

This is also due to the innovation in the PHPStan.

 * https://phpstan.org/r/21c696b0-8ad1-4b86-a608-5db69683852d
 * https://twitter.com/phpstan/status/1162376299039678464

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.3.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:48:32) ( NTS )
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

```
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
```
./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix -v
```

#### The configuration file you are using, if any:

```php
<?php
declare(strict_types=1);

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'class_definition' => [
            'multi_line_extends_each_single_line' => true,
        ],
        'no_superfluous_phpdoc_tags' => false,
        'single_line_throw' => false,
        'blank_line_after_opening_tag' => false,
        'yoda_style' => false,
        'phpdoc_no_empty_return' => false,
        'ordered_imports' => [
            'sort_algorithm' => 'alpha',
        ],
        'list_syntax' => [
            'syntax' => 'short',
        ],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__.'/src')
            ->in(__DIR__.'/tests')
    )
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
abstract class Foo
{
    final private function __construct()
    {
    }

    /**
     * @return static
     */
    public static function create()
    {
        return new static();
    }
}

class Bar extends Foo
{
}

$bar = Bar::create();
```

 * with unexpected changes applied when running PHP CS Fixer:
```php

abstract class Foo
{
    private function __construct()
    {
    }

    /**
     * @return static
     */
    public static function create()
    {
        return new static();
    }
}

class Bar extends Foo
{
}

$bar = Bar::create();
```

```diff
-    final private function __construct()
+    private function __construct()
```

 * with the changes you expected instead:

don't expect any changes

**Comment by kubawerlos** [comment]
The problem is with the fixer description - this is [expected](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3093) behaviour, I've updated the description [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4772).

**Comment by peter-gribanov** [comment]
@kubawerlos I understand how this rule works. The problem is that the result of this rule is incorrect.

**Comment by kubawerlos** [comment]
@peter-gribanov the incorrect part is the description - the result is correct - unneeded `final` keyword was removed.

**Comment by peter-gribanov** [comment]
@kubawerlos re-read my message again. This behavior is incorrect. You need to change the rule itself, not its description.

**Comment by peter-gribanov** [comment]
We need to rework this rule.

* A `final` class must not have `final` methods :+1:
* A `private` method must not be `final` :-1:

**Comment by SpacePossum** [comment]
what would be a good use case for `final private` methods?

**Comment by peter-gribanov** [comment]
@SpacePossum good case is a `final private __construct()`. I described in the issue.

Example:
* https://phpstan.org/r/21c696b0-8ad1-4b86-a608-5db69683852d

Discussion:
* https://twitter.com/phpstan/status/1162376299039678464

Violation examples:
* https://3v4l.org/bSHWs
* https://3v4l.org/v7fQf

Do you need examples that use a private constructor?

**Comment by kubawerlos** [comment]
@peter-gribanov I wanted to ask the same as @SpacePossum - especially with "good" part.

The example shows IMHO quite weird use case and the discussion from Twitter makes sense if you talk about public constructor, not private.

You want to enforce the people that would be extending some `Foo` class (with final private constructor) not to be able to create an instance of the child class. But what is the motivation of this restriction?

**Comment by peter-gribanov** [comment]
> The example shows IMHO quite weird use case and the discussion from Twitter makes sense if you talk about public constructor, not private.

The discussion also affects the private constructor too.
https://twitter.com/dave1010/status/1162422281894866945
https://twitter.com/Ocramius/status/1162380548947533825

> But what is the motivation of this restriction?

There are cases when we do not want the behavior of a method to be overridden in child classes. For this case, you need the `final` modifier. The `private` access modifier does not give us such guarantees.

You can use the agreement in your private project and prohibit overriding private methods, but discovering the fact of substitution can be difficult on review and this option is not suitable for Open Source projects.

Real cases in which private constructors are needed is a [**Singleton pattern** and **Factory method**](https://stackoverflow.com/questions/12553142/when-we-should-make-the-constructor-private-why-php/12553289).

Examples from real projects:
 * https://github.com/marc-mabe/php-enum/blob/master/src/Enum.php#L61
 * https://github.com/gpslab/enum/blob/master/src/ReflectionEnum.php#L35
 * https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/LockMode.php#L20
 * https://github.com/szepeviktor/cascader/blob/master/src/Options.php#L17 - Maybe it would be better to use a private constructor here
 * https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Exception/InvalidEntityRepository.php#L10 - It does not use a private constructor, but it would be a good fit here.

More examples here:
* https://github.com/search?l=PHP&q=%22final+private+function+__construct%22&type=Code

**Comment by peter-gribanov** [comment]
> But what is the motivation of this restriction?

By the way.  What is the motivation to remove the `final` modifier from the `private` methods?

**Comment by SpacePossum** [comment]
IIRC the reasoning was that `private` methods cannot be overridden/overloaded and therefore declaring these as `final` is never needed. As such, I asked for the motivation for when this would be needed _and_ makes sense.

I still agree updating the description make sense as it is more precise on what the fixer _currently_ does.

The fixer can be updated with an opt-out configuration option for the behavior for fixing `private` `final` methods (it would be the BC way).
However reading the discussion and looking at the cases it won't be on my todo-list.

**Comment by kubawerlos** [comment]
@peter-gribanov the `__cosntrutor` case is a good case to prevent creating of the instance (especially in the example from your first link).

@SpacePossum I was thinking about option in a non-BC way.

**Comment by peter-gribanov** [comment]
> IIRC the reasoning was that `private` methods cannot be overridden/overloaded and therefore declaring these as `final` is never needed.

@SpacePossum This problem is beced what this statement is incorrect. PHP allows you to override `private` cosntrutor.

**Comment by SpacePossum** [comment]
yes, I took that from your examples, however you asked why something was done, I cannot change that

**Comment by peter-gribanov** [comment]
Sorry. I focused on my example and did not notice the obvious.

Access to `private` methods is only within the same class. This means that in child classes we can create a `public` method with the same name. This is correct for custom methods but it causes problems with [magic methods](https://www.php.net/manual/en/language.oop5.magic.php).

The magic methods are `public` by default and we can make them `private` in order to block access to them. By making magic methods `private`, we allow child classes to open access to them.

For example, i can order access to the cloning of object by declaring the `__clone` method as `private`, but this may not work if i allow to extend my class.

https://3v4l.org/uK93e

Similarly for the `__sleep` method.

https://3v4l.org/sjqRN

I see the cases of `__constructor` and `__clone` methods, but it might be worth considering the rest of the magic methods.

**Comment by SpacePossum** [comment]
If the case is;
>I define class A with `final private` method `X` so its scope cannot be widened by extending classes, 

than I think this applies to both magic and non-magic methods, as PHP allows child classes to widen any method, magic or not. Therefore I still think it is best to introduce a new option on the fixer that allows stopping the fixer for fixing `private final` methods.

**Comment by peter-gribanov** [comment]
@SpacePossum good job. Thanks :+1:

**Comment by SpacePossum** [comment]
thans, you're welcome :)  :+1:
