### ISSUE TITLE
Using Fixer not at CLI

### ISSUE THREAD

**Issue by WinterSilence** [FriendsOfPHP/PHP-CS-Fixer#4775]
I did not find examples of using the package not through the CLI and write this crutch - it's dirty, but work. Question: how to rewrite this code shorter/better/purest?
```php
$file = __DIR__ . '/demo.php';
$config = \PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one',],
    ])
    ->setFinder(new ArrayIterator([new SplFileInfo($file)]));

$resolver = new \PhpCsFixer\Console\ConfigurationResolver(
    $config,
    [],
    dirname($file),
    new \PhpCsFixer\ToolInfo()
);
$runner = new \PhpCsFixer\Runner\Runner(
    $config->getFinder(),
    $resolver->getFixers(),
    $resolver->getDiffer(),
    null,
    new \PhpCsFixer\Error\ErrorsManager(),
    $resolver->getLinter(),
    $resolver->isDryRun(),
    $resolver->getCacheManager(),
    $resolver->getDirectory(),
    $resolver->shouldStopOnViolation()
);
$runner->fix();
```

**Comment by SpacePossum** [comment]
Hi @WinterSilence ,

How you can use the various part of the tool is indeed not very much documented. Your setup might just be very well what works for you and not be messy as such. Depending on what you want to do you might not need all the components you use now and work with a smaller set.

**Comment by WinterSilence** [comment]
@SpacePossum i find way to separate Fixer classes (Fixer, Tokenizer) and CLI  application.

**Comment by SpacePossum** [comment]
good to hear :) be careful not to rely on `@internal` classes as these might get changed between minor releases

**Comment by SpacePossum** [comment]
Im closing for now, but feel free to leave more questions here!
