### ISSUE TITLE
Importing some global functions produces warnings

### ISSUE THREAD

**Issue by dktapps** [FriendsOfPHP/PHP-CS-Fixer#4779]
Importing global functions like `define` and `defined` causes warnings to be emitted when running the code, like these:
https://3v4l.org/DMg0K

#### The PHP version you are using (`$ php -v`): 
=> 7.3.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1 Yellow Bird

#### The command you use to run PHP CS Fixer:
=> `~/php-cs-fixer.phar fix test2.php --rules='{"global_namespace_import":{"import_functions":true},"native_function_invocation":true}' --allow-risky=yes`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace test;

function dummy() : void{
        if(!defined('myconst')){
                define('myconst', 1);
        }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace test;
use function defined;
use function define;

function dummy() : void{
        if(!defined('myconst')){
                define('myconst', 1);
        }
}
```

 * with the changes you expected instead:
The output code should be the same as the input.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,
can you check if this is the same issue as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4776 ?

**Comment by dktapps** [comment]
My bad, this is indeed a duplicate of #4776 .
