### ISSUE TITLE
GlobalNamespaceImportFixer - use statement before strict types

### ISSUE THREAD

**Issue by dktapps** [FriendsOfPHP/PHP-CS-Fixer#4780]
#### The PHP version you are using (`$ php -v`):
=> 7.3.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1 Yellow Bird

#### The command you use to run PHP CS Fixer:
=> `~/php-cs-fixer.phar fix test2.php --rules='{"global_namespace_import":{"import_functions":true},"native_function_invocation":true,"declare_strict_types":true}' --allow-risky=yes`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function dummy() : void{
        var_dump(strlen("hi"));
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
use function var_dump;
use function strlen;
declare(strict_types=1);


function dummy() : void{
        var_dump(strlen("hi"));
}
```

 * with the changes you expected instead:
Something approximately the same as this, barring whitespace changes
```php
<?php

declare(strict_types=1);

use function var_dump;
use function strlen;


function dummy() : void{
        var_dump(strlen("hi"));
}
```

**Comment by SpacePossum** [comment]
Hi,

Thanks for reporting this issue including all the details :+1:

**Comment by SpacePossum** [comment]
This is an issue with the GlobalNamespaceImportFixer; `['import_functions' => true]`

```php
<?php declare(strict_types=1);

function dummy() : void{
    \var_dump(strlen("hi"));
}
```

this happens when there is namespace declared, see also: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4776
