### ISSUE TITLE
Would be nice if it would clean up if-isset-unset

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#4792]
`if(isset($X)) { unset($X) }` with the same variable, is the same as just doing `unset($X)`.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    if (isset($foo['bar'])) {
        unset($foo['bar']);
    }
```

Could be turned into:

 * with the changes you expected instead:
```php
    unset($foo['bar']);
```

After this transform, unsets could be combined into one, but meh 🤷‍♂️. (`unset($a); unset($b)` = `unset($a, $b);`). It is possible that it already does that.

Maybe if I have time in a few months I'll look at this ticket myself. Seems easy, if you know how this machine works.

**Comment by SpacePossum** [comment]
Hi!

Thanks for sharing your idea. I think the use case might be a little too rare for adding the rule here, but I like to hear what others thing as well!

>After this transform, unsets could be combined into one, but meh man_shrugging. (unset($a); unset($b) = unset($a, $b);). It is possible that it already does that.

there is already a rule for that; `combine_consecutive_unsets` :)

**Comment by HenkPoley** [comment]
Code I inherited is littered with if-isset-unset 🤷‍♂️

**Comment by kubawerlos** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/COOKBOOK-FIXERS.md

**Comment by SpacePossum** [comment]
I'm closing this feature request as I think it is to small/rare to add to this project. Thanks for proposing and good luck making the 3rd party rule!
If anyone else wants this feature, please let us know in the comments here below and we can always open the request again, thanks!
