### ISSUE TITLE
NoSuperfluousPhpdocTagsFixer - false positive with intersection types

### ISSUE THREAD

**Issue by enumag** [FriendsOfPHP/PHP-CS-Fixer#4796]
#### The PHP version you are using (`$ php -v`):
=> 7.4.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> dev-master

#### The command you use to run PHP CS Fixer:
=> vendor/bin/ecs check src

#### The configuration file you are using, if any:

=> irrelevant

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

This annotation was removed:

 * before running PHP CS Fixer (no changes):
```php
      /**
       * @var Traversable<Foo>&Countable
       */
      private $errors;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
      private $errors;
```

 * with the changes you expected instead:
```php
no changes expected
```

**Comment by julienfalque** [comment]
I think nothing in the tool supports this syntax at the moment.

**Comment by SpacePossum** [comment]
indeed, the support for intersections seem to missing all the way down here; https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/DocBlock/Annotation.php#L35

**Comment by SpacePossum** [comment]
this has been fixed in various PR's related the intersection and will ship next release, please let me know if not and I'll reopen
