### ISSUE TITLE
about the [single_line_after_imports] rule, probably not a bug, just a little strange

### ISSUE THREAD

**Issue by bluedasher13** [FriendsOfPHP/PHP-CS-Fixer#4805]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> `7.3.8`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `3.0.0-DEV`

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php
return PhpCsFixer\Config::create()
    ->setRules([
        'single_line_after_imports' => true
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

use namespace1;
use namespace2;
// use namespace3;
echo 'test';

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

use namespace1;
use namespace2;

// use namespace3;
echo 'test';

```

 * with the changes you expected instead:
```php
<?php

use namespace1;
use namespace2;
// use namespace3;

echo 'test';

```

According to [PSR-2 rules](https://www.php-fig.org/psr/psr-2/#3-namespace-and-use-declarations), *there MUST be one blank line after the `use` block.*

But if the last `use` statement in the `use` block is commented out, the last statement will be put after a new blank line;

I think this isn't a bug, just point out that.

**Comment by julienfalque** [comment]
I don't think we can do anything about this: it would be hard to reliably detect that the comment is temporarily disabled code.

Even if we were able to, I think such code should be removed completely so PHP CS Fixer should never even see it. I'd prefer a rule dedicated to that rather than updating all existing rules to handle this comment as if it was actual code.

**Comment by SpacePossum** [comment]
closing as answered, feel free to discuss some more here though :)
