### ISSUE TITLE
[Bug] Unattended error on linting for simple code.

### ISSUE THREAD

**Issue by Yivan** [FriendsOfPHP/PHP-CS-Fixer#4811]
Hello,

On the last version of PHPCS Fixer at this date (v2.16.1 Yellow Bird), the following code:

```
<div>
    <?php if ($this->brands) foreach ($this->brands as $brand): ?>
        CONTENT: <?= $brand->getName(); ?>
    <?php endforeach; ?>
</div>
```

made an error:

`Files that were not fixed due to errors reported during linting after fixing`

I wanted to try `->setUsingLinter(false)` to see the rendered file before linting but seems no more exists.

I think this is a bug as file lint well (before modification with `php -l`). Files is UNIX LF, UTF8 (without BOM), space char only and no empty lines with spaces.

Hope it helps!

Thanks.

**Comment by SpacePossum** [comment]
Hi @Yivan ,

Thanks for report! 
Your example proves a bug in the `braces` fixer/rule that also exists in the 2.15 line.

**Comment by Yivan** [comment]
I would like just to add on my example problem occurs only with `'no_alternative_syntax' => false`. If set to true, output linitng is ok and no error is sent by the fixer.

**Comment by Yivan** [comment]
I just found another one:

```
<?=$this->areablock(
        'test',
        [
            'allowed' => [
                'test-header',
                'demo-guided-search',
            ],
            'globalParams' => [
                'forceEditInView' => true
            ]
        ]
);?>
```
The lint fail if with @PhpCsFixer + 'no_alternative_syntax' => false.

On same linked subjet i have opened this issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4819 for those having this type of problem, this is a suggestion but any experience return is welcome!

Thanks!

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4813

**Comment by Yivan** [comment]
Thanks a lot!
