### ISSUE TITLE
[Bug] Trim trainling spaces not done in comment parts

### ISSUE THREAD

**Issue by Yivan** [FriendsOfPHP/PHP-CS-Fixer#4814]
Hello,

On the last version at this day, commented php part are not properly processed to trim trailing spaces.

Exemple:

```
        $this->view->query = $query;
        $this->view->listing = $listing;
        $this->view->ajax = $ajax;
        $this->view->paginator = $paginator;
        $this->view->areas_select = $areasSelect;
        $this->view->medias_select = $mediasSelect;
        $this->view->brands_select = $brandsSelect;
        $this->view->targets_select = $targetsSelect;
<= here OK
        /*
                // Search (query)
                $query = $request->get('query');
                <= here KO
                if (!empty($query))
                {
                    $news->addConditionParam('title LIKE ?', "%{$query}%");
                    $news->addConditionParam ('description LIKE ?', "%{$query}%", 'OR');
                    $filters[] = "query={$query}";
                }
                <= here KO
                // Pagination
                $filters[] = "page={$request->get('page')}";
                <= here KO
                // $filters_string = '?' . implode('&', $filters);
        */
```

I think for file coherence it should be done in this part too. Usualy when "trim trainling spaces" features are applied on a file, it is on all the file.
I should be applied in the case of mixed content too (html/php). I don't think it can break HTML code (HTML space are important because it can change behaviour of how diplayed, but as this is empty line, the empty line will act like a space for hmtl displaying). Expert could confirm ?

Thanks.

**Comment by SpacePossum** [comment]
for the space in comments you can enable the `no_trailing_whitespace_in_comment` rule

**Comment by Yivan** [comment]
I use @PhpCSFixer and i have not modified this rule.

Here is the ruleset:
```
    ->setRules([
        '@PhpCsFixer'                         => true,

        // one space when concatenation
        'concat_space' => ['spacing' => 'one'],

        // force class element order alphabetically
        'ordered_class_elements'              => ['sortAlgorithm' => 'alpha'],

        // if views are fixed better to activate those
        'no_alternative_syntax'               => false, // this one do the bug
        'no_short_echo_tag'                   => false,
    ])
```

So rules doesn't seems to work ?

**Comment by SpacePossum** [comment]
I think this is the same issue as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3819 , the `no_trailing_whitespace_in_comment` remove the trailing space but `braces` re-adds it

**Comment by SpacePossum** [comment]
closing as duplicate

**Comment by Yivan** [comment]
I confirm same, thanks. Sorry for polluting with this issue.

**Comment by SpacePossum** [comment]
no problem! :)

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3820

**Comment by Yivan** [comment]
Thanks again for your fast fix : )
