### ISSUE TITLE
MethodArgumentSpace - array issue

### ISSUE THREAD

**Issue by Yivan** [FriendsOfPHP/PHP-CS-Fixer#4816]
Hello,

I looked though the issues history and find this is a recurring problem sometimes that you need to run the fixer several times before having no more errors. It seems linked to priority, and seems hard to achieve in one pass.

We encounter this problem too. We test on one project, and fixer need to bee run 2 times so all files are fixed (pure php files). In case of mixed content (html/php), it needs to be run 5 times : (
It make complicating CI check, as generaly we check there is no errors, developper must run several time the fix command, and disabling the cache (because as cached untotally fixed files won't be fixed on next run).

This could be done with a wrapper script running fix command with no cache until no more files are modified. But it will be slow and integrate badly with IDE.

Purpose of this issue is to make it native, and more performant so it works with cache.

**Proposition:**
The way would be to be able to set an option, like "until no more fix to apply" (with a safegard on 10 try for instance, configurable, if after 10 try if not stabilize, we go on).
This way cache could be used too. And overall performance would be better.
And finally it will make best life for CI and some priority problem would be surely be resolved this way.

I hope it is a good suggestion.

Best regards.

**Comment by julienfalque** [comment]
Having to run the tool several times almost always indicates a priority issue between several rules, i.e. rule A applies some changes, then rule B applies changes that should have been modified by rule A. Now you need to run rule A again but the actual fix is to make sure rule B is always executed first.

Automatically running the tool multiple times until everything is fixed would be hiding the real problem. Could you please share PHP snippets that reproduce it so we can fix priorities?

A long term fix to this IMO should be to rework the way rules are implemented to get rid of priority requirements but that means probably too much work.

**Comment by Yivan** [comment]
It would be a plus to have this ablities of multiple pass but I understand it will make less priority bug reporting so less good base code and sure it is better to fix issue at the base.
But it would be really helpful such a feature : )
You could implement a warning that multipass has been needed, which will generate a report so the user can send to you... just an idea.

Is there any e-mail adresses I can send you the files ? (cannot share it, not to be disclosed publicly)

Thanks.

**Comment by julienfalque** [comment]
I don't think implementing anything is worth the hassle: running the tool again to fix CI failures is a simple workaround. If this is too much annoying, what you are asking for can be done with a simple bash script. I think we should focus on fixing the priority issues here.

If you cannot share any PHP file as-is, maybe you can reduce their contents and remove sensitive info? All we need is a reproducer.

**Comment by Yivan** [comment]
Yes priority feature for sure, I totally agree. This was just a suggestion of improvement based on my experience with the fixer.

I will try to prepare you the stripped content so! Thanks.

**Comment by Yivan** [comment]
I stripped any content, and tried to get a way it need at least 2 passes. I manage to isolate those ones.
Here they are. Those 4 needs 2 passes to get ok.

```
<main class="main approach">

    <section class="section">
        <div class="wrapper">
            <div class="video-player">

			<?=$this->areablock(
				'cms-content',
				[
					'allowed' => [
						'cms-full-width-media'
					],
					'globalParams' => [
						'forceEditInView' => true
					]
				]
			);?>

            </div>
        </div>
    </section>

	<section class="section section">
		<div class="wrapper">

			<ul class="section-list">

				<?php while ($this->block('loop')->loop()):?>

				<?=$this->renderlet(
					'product',
					[
						'bundle' => 'oopBundle',
						'controller' => 'renderlet',
						'action' => 'render',
						'template' => 'oopBundle::documents/Renderlet/render.html.php',
						'title' => 'Content',
						'type' => 'object'
					]
				);?>

				<?php endwhile;?>

			</ul>

			<div class="section-action">
				<a href="<?=$this->page['prettyUrl'];?>" class="btn-2">Dummy</a>
			</div>

		</div>
	</section>

</main>
```

```
<?php

namespace TTYBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/* Pimcore namespaces */

use Pimcore\Model\DataObject\TTYCar as Car;
use Pimcore\Model\DataObject\TTYPlane as Plane;
use Pimcore\Model\DataObject\TTYContact as Contact;
use Pimcore\Model\DataObject\TTYPaper as Paper;
use Pimcore\Model\DataObject\TTYGame;
use \Pimcore\Model\DataObject\Service as PimcoreObjectService;
use Demo\PimcoreBundle\Model\Document\Page as DemoPage;
/* TTYBundle namespaces */

use \TTYBundle\Controller\AbstractController;


class SearchController extends AbstractController
{
    public function listingResultsAction(Request $request)
    {
    }

	//Résultats de la recherche inspirationnel
    public function resultsAction(Request $request)
    {

		$results_document = DemoPage::GetByConfiguration(
			[
				'type' => 'page',
				'bundle' => 'TTYBundle',
				'controller' => '@TTYBundle\Controller\SearchController',
				'action' => 'results',
				'template' => 'TTYBundle:documents/Search:results.html.php',
				'published' => true
			]
		);

    }
}
```

```
<?php

class DemoController extends AbstractController
{
    public function listingAction(Request $request)
    {
                
/*
        // Search (query)
		$query = $request->get('query');

		if (!empty($query))
		{
			$news->addConditionParam('title LIKE ?', "%{$query}%");
			$news->addConditionParam ('description LIKE ?', "%{$query}%", 'OR');
			$filters[] = "query={$query}";
		}
		
		// Pagination
		$filters[] = "page={$request->get('page')}";
	
		// $filters_string = '?' . implode('&', $filters);
*/

	}
	
}
```

```
<?php

namespace Demo;

class Test
{
	public function getOptions($json)
	{
		$options = file_get_contents($json);

		$options = json_decode($options, true);

		$output = $options;

		return $output;
	}
}
```

**Comment by SpacePossum** [comment]
case 1 can be reduced to;

```php

<?php
    a(
        [
        ]
    ); ?>

    <?php b(
        [
        ]
    );
?>
```

and is an issue within the `method_argument_space` rule with configuration `{"on_multiline":"ensure_fully_multiline"}`.

The 3 other cases have bug fix PR's open.
Thanks for reporting!

**Comment by keradus** [comment]
@SpacePossum , after #4824 was merged, is there anything open here? if so, let's have dedicated, separated tickets per each case

**Comment by SpacePossum** [comment]
last case is shown here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4960
