### ISSUE TITLE
no_spaces_after_function_name: echo/print or include/require[_once] parenthesized expression (before binary operator)

### ISSUE THREAD

**Issue by guilliamxavier** [FriendsOfPHP/PHP-CS-Fixer#4817]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.25 (cli) (built: Nov 22 2019 17:19:47) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski (c8afb59)

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix -vvv --using-cache=no --rules=@Symfony,-concat_space sample.php`

#### The configuration file you are using, if any:
(none)

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

echo (0 === rand(0, 1) ? 'foo' : 'bar') . PHP_EOL;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

echo(0 === rand(0, 1) ? 'foo' : 'bar') . PHP_EOL;
```

 * with the changes you expected instead:
(no changes)

**Comment by guilliamxavier** [comment]
Same problem with e.g.

```php
echo (1 + 2), PHP_EOL;
```

**Comment by SpacePossum** [comment]
Hi and thanks for your question.

This changes is done by the `no_spaces_after_function_name` rule, it is done because of the following:

```
PSR2 4.6  Method and Function Calls
When making a method or function call, there MUST NOT be a space between the method or function name and the opening parenthesis, there MUST NOT be a space after the opening parenthesis, and there MUST NOT be a space before the closing parenthesis. In the argument list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.
```
sample
```php
<?php
$foo->bar(
    $longArgument,
    $longerArgument,
    $muchLongerArgument
);
```

https://www.php-fig.org/psr/psr-2/#46-method-and-function-calls

If you don't like this you can disable the rule in your configuration.

Closing as answered but feel free to respond if I missed anything :)

**Comment by guilliamxavier** [comment]
@SpacePossum: Sorry I probably should be more explicit: *`echo` is not a function*.

https://www.php.net/manual/en/function.echo.php (**emphasis** mine):

> `echo` is not actually a function (it is a language construct), so you are not required to use parentheses with it. `echo` (unlike some other language constructs) does not behave like a function, so it cannot always be used in the context of a function. Additionally, if you want to pass more than one parameter to `echo`, **the parameters must not be enclosed within parentheses**.

Therefore, *there should always be a space after `echo`*.

Here's a more complete example:

```php
echo (2 + 3) * 4, "\n";
```

=> that's a call to `echo` with 2 arguments: `(2 + 3) * 4` (which will evaluate to `20`) and `"\n"`. But PHP-CS-Fixer currently will alter it like this:

```php
echo(2 + 3) * 4, "\n";
```

which makes it look like it would multiply by 4 "the result of `echo(2 + 3)`" (which doesn't make sense, see https://3v4l.org/Pde5T) and then a parse error because of the comma (https://3v4l.org/G2CZe).

Actually, *same thing for `print`* (which takes only one argument):

https://www.php.net/manual/en/function.print.php:

> `print` is not actually a real function (it is a language construct) so you are not required to use parentheses with its argument list.
> 
> The major differences to `echo` are that `print` only accepts a single argument and always returns 1.

e.g.

```php
$one = print (2 + 3) * 4;
```

should be left untouched (https://3v4l.org/SfaCn).

So do you agree to reopen?

**Comment by julienfalque** [comment]
I agree `echo` and `print` should have a special treatment. I would consider this a bugfix (or enhancement), not a new feature.

**Comment by SpacePossum** [comment]
see also https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4744#issuecomment-575519472 where the reasoning to fix code style in `isset` like a function is stated, yet here function constructs like `isset` should not be fixed in the same way?

**Comment by guilliamxavier** [comment]
@SpacePossum: You made me realize that actually the issue with `echo`/`print` (and for that matter `include`/`require`[`_once`] too) is not just that they are not functions (which is also the case of `isset`, `unset`, `empty`, `eval`) but that *they don't take parentheses around their argument(s)* (which is *not* the case of `isset` et al.). Two very simple examples:
- `print(1) - 2` looks like it would print `1` and give `-1`, but in reality it will print `-1` and give `1` (like `print (1 - 2)`; did you mean `(print 1) - 2`? https://3v4l.org/Q5PIT)
- `echo(1, 2);` isn't even valid syntax (https://3v4l.org/Kt7h4), you *have to omit* the parentheses (https://3v4l.org/2eeRS).

(By the way, a nice trick to see how PHP interprets an expression is to look at the error message of `assert(false && (EXPRESSION));`, which works for `print` but alas not for `echo`.)

So, again, I don't see how one could argue that the following "fix" is right:

```diff
-    echo (2 + 3) * 4, "\n";
+    echo(2 + 3) * 4, "\n";
```

Do you?

**Comment by kubawerlos** [comment]
I'd say if we call `echo` as function:
```php
echo(1 + 2);
```
then no space, but if the opening parenthesis is not from "function" like in:
```
echo (1 + 2) . ' a';
echo (1 + 2), ' a';
```
then we can keep/add space.

**Comment by julienfalque** [comment]
`echo` is a language construct and is mostly used *without* parentheses (I think). In this example:
```php
echo (1 + 2);
```
I would consider the parentheses to be part of the expression that is passed to `echo`, not argument list delimiters.

**Comment by guilliamxavier** [comment]
*Heads-up:* I had a look at [the code](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixer.php) and it appears that, among the dozen or so "false functions" (search "Functiony"), the six `echo`/`print`/`include`/`include_once`/`require`/`require_once` are already special-cased (search "LanguageConstruction") but only for a very specific pattern (#1237, in which the parentheses are actually unnecessary, by the way)...

To be extra clear (and in the following you could replace `echo` with any of its five "special friends"):
- `echo ($a);` _arguably_ shouldn't become `echo($a);` (but rather `echo $a;`, which is actually the case with the `no_unneeded_control_parentheses` rule, not in the default `@PSR2` ruleset but included in both `@Symfony` and `@PhpCsFixer`).
- `echo ($a ?: $b);` _arguably_ shouldn't become `echo($a ?: $b);` (but rather `echo $a ?: $b;`, ditto).
- `echo ($a ?: $b) . $c;` **certainly** shouldn't become `echo($a ?: $b) . $c;` but should be kept as-is (or become `echo ($a ?: $b).$c;` if the ruleset includes `concat_space`).

On the other hand, I agree that `isset ($a)` should still become `isset($a)` (and same for `array`/`empty`/`eval`/`exit`/`list`/`unset` and e.g. `$callable`).

I don't think there needs to be that much of an argument between @julienfalque and @SpacePossum: the crux here is actually *not* about "real function" vs "language construct", but about "argument [list] is delimited by parentheses" vs "argument [list] is everything on the right (until the end of the statement or expression)", which in fact sub-divides "false functions" language constructs. In other words, it's not that "`echo` isn't really a function" but that "`echo` *doesn't work like* a function".

A last example: the expression `include('foo.php') === 1` is actually `include (('foo.php') === 1)` (and `include 'foo.php' === 1` would evaluate the same), not `(include ('foo.php')) === 1` (which could be written `(include 'foo.php') === 1`, or `1 === include 'foo.php'`) as was probably intended.

Therefore, **I consider the current behavior as an unintended bug** (i.e. #1266 should have been more general). Do someone still disagree?

**Comment by SpacePossum** [comment]
I think `die` / `exit` should be added to the list?
Also, I see no argument, just a different preference like we've a lot here in this project.
Just because `echo 1,2,3;` is valid and say `foo 1,2,3` not , doesn't change my mind that I like `echo(1 + 2)` be formatted like `foo(1 + 2)` or `unset($a,$b)` etc.
Does it matter? well no, it is just my preference, so if someone can make the PR I'm happy to merge.

**Comment by guilliamxavier** [comment]
@SpacePossum: Thanks for your response (and your time). About `die` / `exit`: there is no `T_DIE`, both are tokenized as `T_EXIT` (https://3v4l.org/70N4B) which already is in the "Functiony" list, but not in the "LanguageConstruction" sub-list, which is correct, because valid forms are `exit($a);` and `exit();` (which can be written `exit;`), but in no way `exit $a;`.
Sorry if I saw an argument where there's just a different preference 🙂
For symmetry I add that `echo(1,2,3);` is not valid while `foo(1,2,3)` is.
I'm glad to see you're actually open to a PR! I'll be happy if I can find the time to try to put up one

**Comment by guilliamxavier** [comment]
Thinking of it, why is this labeled as a "feature request"? Currently,

- `echo ($a ?: $b) ?: $c` is left untouched but
  `echo ($a ?: $b) ?? $c` is changed to `echo($a ?: $b) ?? $c`

- `echo (new \Foo)->f()` is left untouched but
  `echo (clone $a)->f()` is changed to `echo(clone $a)->f()`

Doesn't that look like a "bug"?

**Comment by guilliamxavier** [comment]
Another kind of inconsistency (with the `@Symfony` ruleset minus the `concat_space` rule):

`echo($a . ($b ?? ''));` is fixed (`no_unneeded_control_parentheses`) to
`echo $a . ($b ?? '');`
but
`echo(($a ?? '') . $b);` is fixed (`no_unneeded_control_parentheses, no_spaces_after_function_name`) to
`echo($a ?? '') . $b;`

**Comment by guilliamxavier** [comment]
One more to add to the record:

- `$r = print ($a ?? $b) . $c;` is changed to `$r = print($a ?? $b) . $c;` ([*misleading*](https://3v4l.org/YWh7X), cf. operator precedence) but
  `$r = clone ($a ?? $b) . $c;` is *not* changed to `$r = clone($a ?? $b) . $c;` (even though that would be ["not so misleading"](https://3v4l.org/ZKMjb), ironically)

#4893 would fix all the above (actually the much simpler #4837 too), if only you would accept the supposed "BC break"...

**Comment by guilliamxavier** [comment]
I confirm that upgrading to 2.17 solves the problem (automatically with `--rules=@PhpCsFixer` or `--rules=@Symfony`, and explicitly with `--rules=@PSR2,single_space_after_construct`).
