### ISSUE TITLE
Empty line between import groups

### ISSUE THREAD

**Issue by Yivan** [FriendsOfPHP/PHP-CS-Fixer#4821]
Hello,

Redorder of the `use` statements in the header block seems not to take into account the "use function ..." and it order it like other use.

After using `@PhpCsFixer` set, it end up with:
```
use FATBundle\Service;
use function GuzzleHttp\json_encode;
use Pimcore\Controller\FrontendController;
```

Should be:
```
use FATBundle\Service;
use Pimcore\Controller\FrontendController;
use function GuzzleHttp\json_encode;
```

It would be great for lisibility !

---

If we go further, I think it should be spaced, for better visibility:
```
use FATBundle\Service;
use Pimcore\Controller\FrontendController;

use function GuzzleHttp\json_encode;
```

_I know you are working on PSR12 rules, so it would allow PSR12 compliance (i run this tool to check: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR12/Sniffs/Files/FileHeaderSniff.php#L357 , aka rule `Header blocks must be separated by a single blank line`). Please see https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements. But PSR12 is another subject, but as this issue is about talking use statement I mention it._

I think `use function...` (and `use const...`) should be ordered at end and space by default.

Best regards.

**Comment by SpacePossum** [comment]
Hi,

I think this is a configuration issue, please see `$ php php-cs-fixer describe ordered_imports` and the README for rule configuration details. For example here:

```
 * Example #5. Fixing with configuration: ['sort_algorithm' => 'alpha', 'imports_order' => ['const', 'class', 'function']].
   ---------- begin diff ----------
```

```diff
--- Original
+++ New
@@ -1,10 +1,10 @@
<?php
+use const AAAA;
 use const BBB;
-use const AAAA;

+use AAC;
 use Acme;
-use AAC;
 use Bar;

+use function CCC\AA;
 use function DDD;
-use function CCC\AA;
```

**Comment by SpacePossum** [comment]
closing as answered, feel free to leave a comment or question if I missed anything!

**Comment by Yivan** [comment]
Thanks ! I should have better looking at documention, my fault, sorry.

Juste maybe this issue could be reponned, as improvement, because i really think as default is alpha sorting, it mess const/class/function order, which in fact is not at all really usefull for developper.

I sugger those two things:

- As default for @PhpCsFixer set it could be alpha + `'imports_order' => ['const', 'class', 'function']`.
I think it make sense, and it doesn't break nothing or nor risky. Just better than actually i think ?
It will prevent finishing with something like that with actual default, which bring mess for the developper:

```
use A
use B
use const Z
use C
use function B
use function D
use D
```

- As nice addition would be a space between different type (as option or fixed choice):

```
use const A ...
use const B ...

use A ...
use B ...

use function A ...
use function B ...
```

If option, this last one would be better with empty line separation, so it sticks PSR12.

Best regards.

**Comment by SpacePossum** [comment]
Not sure on the new default, Im not for or against for now. I do like the PSR12 request for adding the empty line :+1:

**Comment by masi** [comment]
"ordered_imports" as is it is now is included in PSR12 but violates the spec. In context of PSR12 it is a bug, not a feature request. But this is already mentioned in #4502.

**Comment by ngmy** [comment]
> As nice addition would be a space between different type (as option or fixed choice):

That's very good.
I have no choice but to run phpcbf after php-cs-fixer to insert a empty line.

**Comment by clar-cmp** [comment]
Also running into this issue -- the PSR-12 configs for php-cs-fixer and php-codesniffer will oscillate between adding and removing the new line between differently-typed imports. Would be nice to fix this so that there isn't the discrepancy between these two inspectors.

**Comment by mutec** [comment]
Any news on that issue?
I don't really want to disable `PSR12.Files.FileHeader.SpacingInsideBlock` since this skips checking the blank line between namespace and use-block too.

**Comment by SpacePossum** [comment]
see this the PR that deals with this issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6365
it is as good as ready to merge :+1:   finger crossed it gets merged soon and released!
