### ISSUE TITLE
Error when the cache folder doesn't exist

### ISSUE THREAD

**Issue by yguedidi** [FriendsOfPHP/PHP-CS-Fixer#4827]
#### The PHP version you are using (`$ php -v`):
=> 7.3.14

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer fix --dry-run`

#### The configuration file you are using, if any:
```php
<?php

use PhpCsFixer\Fixer\Import\OrderedImportsFixer;

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/src')
    ...
;

return PhpCsFixer\Config::create()
    ...
    ->setCacheFile(__DIR__.'/var/cache/.php_cs.cache')
;

```

---

When the folder `var/cache/` doesn't exist, there is this error:

```
Loaded config default from "/home/user/.php_cs".

Checked all files in 493.477 seconds, 30.000 MB memory used

In FileHandler.php line 91:
                                                                                          
  Failed to write file "/home/user/var/cache/.php_cs.cache", "no reason available".  
                                                                                          

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

Shouldn't PHP-CS-Fixer be able to create the folder? or at least provide a better reason for the error?

Thank you

**Comment by julienfalque** [comment]
I don't think creating the directory is the responsibility of PHP CS Fixer though I agree the error message is not helpful.

Now, making PHP CS Fixer create the directory probably needs an amount of work that is similar to improving the error message so... I'd say let's create the directory then.

**Comment by GrahamCampbell** [comment]
Creating the directory can be risky too. Perhaps it doesn't exist because someone has typoed it.

**Comment by julienfalque** [comment]
That's also true for directories that do exist though. Creating an unexpected directory would likely be spotted with a VCS such as Git anyway.

**Comment by GrahamCampbell** [comment]
Not if it was made outside of that by mistake. Like someone accidentally putting `""` which would be interpreted as `/`, perhaps? I've had this happen before. Deleting `/` is never good. 😆

**Comment by SpacePossum** [comment]
Indeed, it is risky to make the directory on typos like '' and '/'. 
IMHO, it is the responsibility of the user that the tool can write the cache where they want it. This also prevents including more logic and maintenance on the code base, for example when dealing with files on network space etc. 

We can improve the error message though, currently we display what PHP itself set as error when the write failed.

**Comment by julienfalque** [comment]
Ok let's improve the message :+1:

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5161
