### ISSUE TITLE
Suggestion: Dedicated phpunit assertion for instanceof in assertTrue

### ISSUE THREAD

**Issue by Riimu** [FriendsOfPHP/PHP-CS-Fixer#4845]
PHP-CS-Fixer already has plenty of good fixers to use dedicated assertions in PHPUnit when applicable. However, one glaring omission seems to be the `instanceof` operator.

It would be nice if the `php_unit_dedicate_assert` would also look at the special case of using:

```php
$this->assertTrue($instance instanceof SomeClass);
```

And fix it to use the dedicated assertion instead:

```php
$this->assertInstanceOf(SomeClass::class, $instance);
```

I realize this is not necessarily as straightforward as the others, as it's not about using specific function, but a language construct. Additionally, there is the question of whether using `SomeClass::class` or `"SomeClass"` or `'SomeClass'`, but that could possibly be handled by other fixers. It might also make sense to create a separate fixer for this rather than including it in the `php_unit_dedicate_assert`.

Scouring through one legacy code base I was just surprised to find plenty of these tests, so it would nice to have automated way of correcting them.

**Comment by kubawerlos** [comment]
Also these:
```php
    $this->assertTrue(isset($foo['bar']));
    $this->assertTrue(isset($foo->bar]));
```
can be changed to:
```php
    $this->assertArrayHasKey('bar', $foo);
    $this->assertClassHasAttribute('bar', $foo);
```

and similar for assertions `assertClassHasStaticAttribute` and `assertObjectHasAttribute`.
