### ISSUE TITLE
After updating to version2 large parts of my annotations get removed

### ISSUE THREAD

**Issue by weberdominik** [FriendsOfPHP/PHP-CS-Fixer#4848]
After updating php-cs-fixer to version 2 it removes large parts of my annotations. Here's an example:

`php-cs-fixer fix src/ --rules=@Symfony`

**Before**

/\*\*
 \* Does something
 \*
 \* @param Something $something
 \* @return bool
 \*/
public function doSomething(Something $something): bool
{
...
}

**After**

/\*\*
 \* Does something.
 \*/
public function doSomething(Something $something): bool
{
...
}

Is this a bug or did the config somehow change?

**Comment by SpacePossum** [comment]
Hi!

There are a lot of changes between v1 and v2. If you add `-vvv` to the command you use it will list all the rules it applied. From there you can tweak your configuration by switching off the rules you do not want.
My guess is the changes you see here are done by the `no_superfluous_phpdoc_tags` rule, which is part of the Symfony set.

**Comment by weberdominik** [comment]
Thanks for your quick reply. Your guess is correct (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3809).
