### ISSUE TITLE
braces for `case` look totally ignored and not treated as `anonymous_constructs`

### ISSUE THREAD

**Issue by e-gaulue** [FriendsOfPHP/PHP-CS-Fixer#4855]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
PHP 7.1.19

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.1

#### The command you use to run PHP CS Fixer:
`php-cs-fixer fix .`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    case 'deleteattachment':
    {
        DeleteAttachment($_ARG['id']);
        $result=1;
        break;
    }
    case 'addimage': {
            break;
        }
    case 'getimage': {
            $result = 1;
            break;
        }
```

 * with the changes you expected instead:
```php
    case 'deleteattachment':
    {
        DeleteAttachment($_ARG['id']);
        $result=1;
        break;
    }
    case 'addimage': 
    {
        break;
    }
    case 'getimage': 
    {
        $result = 1;
        break;
    }
```
or 
```php
    case 'deleteattachment': {
        DeleteAttachment($_ARG['id']);
        $result=1;
        break;
    }
    case 'addimage': {
        break;
    }
    case 'getimage': {
        $result = 1;
        break;
    }
```
but not a mix of them.

Regards,

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

The issue you describe is the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/776 as such I'm closing this report as duplicate.
