### ISSUE TITLE
Opposite of new_with_braces

### ISSUE THREAD

**Issue by JKingweb** [FriendsOfPHP/PHP-CS-Fixer#4858]
I realize the `new_with_braces` rule is only designed to add braces (not remove them), but it would be nice if it would do either. Right now I have only the choice of always braces, or no enforcement.

This would be particularly helpful once PSR-12 is supported, as I would want to override this part of its rules. 

#### The PHP version you are using (`$ php -v`):
=> 7.4.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.1

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:
```php
$finder = ...
return \PhpCsFixer\Config::create()->setRiskyAllowed(true)->setRules([
    'new_with_braces => false
])->setFinder($finder);

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
new stdClass();
```

 * with unexpected changes applied when running PHP CS Fixer:
=> No change

 * with the changes you expected instead:
```php
<?php
new stdClass;
```

**Comment by SpacePossum** [comment]
Hi and thanks for your request.

Is this part of a standard or used by a bigger (F)OSS community? For us that is a condition to add a rule to this project, otherwise you can create a custom fixer and use that in your projects. Thanks for understanding.

**Comment by JKingweb** [comment]
I'll consider doing that. Thanks.
