### ISSUE TITLE
no_superfluous_phpdoc_tags doesn't remove @var in PHP 7.4

### ISSUE THREAD

**Issue by garak** [FriendsOfPHP/PHP-CS-Fixer#4864]
I'm migrating a project to PHP 7.4, adding typed properties.
I expect phpdoc (now useless) are removed, but they are not.

#### The PHP version you are using (`$ php -v`):
PHP 7.4.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.16.1

#### The command you use to run PHP CS Fixer:
`php-cs-fixer fix -v`

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__.'/src', __DIR__.'/tests'])
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PHP71Migration:risky' => true,
        '@PHP73Migration' => true,
        '@PHPUnit60Migration:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'ordered_imports' => true,
        'declare_strict_types' => false,
        'native_function_invocation' => true,
        'no_superfluous_phpdoc_tags' => true,
    ])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace Foo;

class Bar
{
    /**
     * @var string
     */
    private string $name;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
no change

 * with the changes you expected instead:
```php
<?php

namespace Foo;

class Bar
{
    private string $name;
}
```

**Comment by julienfalque** [comment]
This has been implemented in #4746 and will be available with future release.
