### ISSUE TITLE
Trait import bug

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4867]
Non-idempotency of fixing imported traits can be observed as follows...

#### The PHP version you are using (`$ php -v`):
=> PHP 7.4.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> Latest 2.16 branch at time of writing (3849a14a804fa12271f08cdd3275e4183d30379b)

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:

These are the **minimal** rules to reproduce the issue:

```php
[
    "braces" => [
        "allow_single_line_closure" => true,
    ],
    "class_attributes_separation" => [
        "elements" => ["method"],
    ],
    "no_extra_blank_lines" => [
        "useTrait",
    ],
    "single_trait_insert_per_statement" => true,
    "space_after_semicolon" => true,
]
```

If I delete any one of these rules, then the issue does not occur!

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class Foo
{
    use Bar, Baz;

    public function baz()
    {
        //
    }
}

```

 * after **first run** of PHP CS Fixer:
```php
<?php

class Foo
{
    use Bar;
    use Baz;
    public function baz()
    {
        //
    }
}

```

 * after **second run** of PHP CS Fixer:
```php
<?php

class Foo
{
    use Bar;
    use Baz;

    public function baz()
    {
        //
    }
}

```

**Comment by SpacePossum** [comment]
Thanks for the report, happens on 2.15 as well.
With simplified config
```
        [
            "braces" => true,
            "class_attributes_separation" => true,
            "no_extra_blank_lines" => [
                "useTrait",
            ],
            "single_trait_insert_per_statement" => true,
            "space_after_semicolon" => true,
        ]
```

**Comment by GrahamCampbell** [comment]
Glad we were finally able to pin this down properly, and sorry it took me so long to provide a proper example to reproduce it!

**Comment by SpacePossum** [comment]
Yeah great to have a concrete case, thanks for providing :)
I tracked it down to being a bug in the `no_extra_blank_lines` fixer, not related to the other fixers or priority, proposed fix is here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4871

**Comment by GrahamCampbell** [comment]
Nice. This stuff is kinda funky, lol.
