### ISSUE TITLE
PSR-12 Style Sorted Imports

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4874]
PSR-12 doesn't say anything about import order, but it does mandate that the class-based imports should be separated from the function imports, from the constant imports:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/2829600/76090858-41bed980-5fb4-11ea-9482-a274c306a1b3.png">

The current import ordering fixer will mix them all together. Should we add a way to get this fixer to consider the import type when ordering?

**Comment by julienfalque** [comment]
I updated #4502 to keep track of all tasks in a single place. Thank you.
