### ISSUE TITLE
Use symfony trigger_deprecation

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4881]
I'm wondering if we should change the silenced calls to trigger_error within this codebase to use `trigger_deprecation` on the master branch? https://github.com/symfony/deprecation-contracts

**Comment by julienfalque** [comment]
That would mean dropping support for PHP 5.6 and 7.0 though.

**Comment by GrahamCampbell** [comment]
Oh, dear. I didn't notice that. Given that will happen in 3.0, then there is no case for this, for now.

**Comment by julienfalque** [comment]
> Given that will happen in 3.0

Actually it can happen on any version, bumping dependencies is not a BC break.

**Comment by GrahamCampbell** [comment]
Yeh, but I kinda assumed 3.0 was gonna land in 2020, so it would be unlikely we'd drip both 5.6 and 7.0 in 2.17 or 2.18. If you think that's likely, then we could re-open this.
