### ISSUE TITLE
Looks like get_class_this break some Traits 

### ISSUE THREAD

**Issue by soyuka** [FriendsOfPHP/PHP-CS-Fixer#4921]
#### The PHP version you are using (`$ php -v`):
php 7.4.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.2 Yellow Bird by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix

#### The configuration file you are using, if any:

https://github.com/api-platform/core/blob/2.5/.php_cs.dist

To test this you can remove the `function_to_constant'` configuration I added to keep `get_class_this` which btw is now default and wasn't added to the docs see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4742/files. You'll see in  src/Bridge/Doctrine/Common/PropertyHelperTrait.php that the following gets changed:

```diff
-            if (__CLASS__ !== \get_class($this)) {
+            if (__CLASS__ !== static::class) {
```
Which isn't right in a tray.

**Comment by kubawerlos** [comment]
@soyuka can you provide an example? All looks fine here: https://3v4l.org/4nSBX

**Comment by soyuka** [comment]
Indeed phpstan got me wrong here sorry for the trouble (https://github.com/phpstan/phpstan/issues/1885).
