### ISSUE TITLE
Add aliases for options of final_internal_class fixer

### ISSUE THREAD

**Issue by a-menshchikov** [FriendsOfPHP/PHP-CS-Fixer#4922]
Now options contain dashes what prevents to use this fixer in EasyCodingStandard (which replaces dashes with underscores).
To resolve this problem options of final_internal_class should be aliased with values, where dashes will be replaced with underscores.

**Comment by SpacePossum** [comment]
:+1: 
we should also update the auto review tests to no longer allow dashes in the names of options (and possible other characters as well)

**Comment by kubawerlos** [comment]
@a-menshchikov this will be solved with the release of 2.17, it's already merged: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4634

**Comment by julienfalque** [comment]
Indeed, totally forgot about this.
