### ISSUE TITLE
Reading .php_cs.dist from a PHP class::method

### ISSUE THREAD

**Issue by NiklasBr** [FriendsOfPHP/PHP-CS-Fixer#4928]
#### The PHP version you are using (`$ php -v`):
=>7.4.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=>2.16.3

#### The command you use to run PHP CS Fixer:
In a class method I run this code:
```php
        $path = "path/to/my_file.php";
        if (class_exists('PhpCsFixer\\Runner\\Runner')) {
            $config = \PhpCsFixer\Config::create()
                ->setRules([
                    '@PSR1' => true,
                    '@PSR2' => true,
                    '@Symfony' => true,
                ])
                ->setFinder(new \ArrayIterator([new \SplFileInfo($path)]));

            $resolver = new \PhpCsFixer\Console\ConfigurationResolver(
                $config,
                [],
                \dirname($path),
                new \PhpCsFixer\ToolInfo()
            );
            $runner = new \PhpCsFixer\Runner\Runner(
                $config->getFinder(),
                $resolver->getFixers(),
                $resolver->getDiffer(),
                null,
                new \PhpCsFixer\Error\ErrorsManager(),
                $resolver->getLinter(),
                $resolver->isDryRun(),
                $resolver->getCacheManager(),
                $resolver->getDirectory(),
                $resolver->shouldStopOnViolation()
            );
            $runner->fix();
        }
```

The reason is that I have PHP files which can ge generated dynamically and would like to trigger the CS fixer when writing them to disk. Might not always have the ability to run the command line utility. The above code works, however, I already have a `.php_cs.dist` file in my project root, I would like to load that when the above code runs but I can't find any docs regarding it. Is it possible? How?

**Comment by kubawerlos** [comment]
File `.php_cs.dist` is returning `Config` class, right?

So `$config = require "path/to/.php_cs.dist";` would do the trick.

**Comment by NiklasBr** [comment]
Yes it did, thanks!

I just had to run the `setFinder()` method again to avoid using the one in the settings file.
