### ISSUE TITLE
Behavior change to comment processing in v2.16.2

### ISSUE THREAD

**Issue by phil-davis** [FriendsOfPHP/PHP-CS-Fixer#4933]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.30

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> v2.16.2 or 2.16.3

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer fix --dry-run --diff

#### The configuration file you are using, if any:
The `.php_cs.dist` in the PHP-CS-Fixer repo with just line 26 commented out:
```php
//'header_comment' => ['header' => $header],
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
/**
 * This is the top comment.
 */

/**
 * This is a comment about some code.
 * It has 2 lines.
 */
echo 'abc';

/**
 * This is a comment about some code that has a variable.
 * It has 2 lines.
 */
$y = 42;

/**
 * This is another comment about some code.
 * It has 2 lines.
 */
echo 'def';
```

Put the above in a file in a local clone of https://github.com/FriendsOfPHP/PHP-CS-Fixer and:
```
$ git checkout v2.16.1
$ php php-cs-fixer fix --dry-run --diff
Loaded config default from "/home/phil/git/FriendsOfPHP/PHP-CS-Fixer/.php_cs.dist".
   1) example.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 
-/**
+/*
  * This is another comment about some code.
  * It has 2 lines.
  */
 echo 'def';
 

      ----------- end diff -----------


Checked all files in 24.976 seconds, 18.000 MB memory used
```

Next:
```
$ git checkout v2.16.2
$ php php-cs-fixer fix --dry-run --diff
Loaded config default from "/home/phil/git/FriendsOfPHP/PHP-CS-Fixer/.php_cs.dist".
   1) example.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 /**
  * This is the top comment.
  */
 
-/**
+/*
@@ @@
 
-/**
+/*
  * This is another comment about some code.
  * It has 2 lines.
  */
 echo 'def';
 

      ----------- end diff -----------


Checked all files in 26.554 seconds, 18.000 MB memory used
```

In `v2.16.2` it wants to fix 2 comments, but in `v2.16.1` it wants to fix only one comment (that is further down in the code)

The behavior has changed. In the real-life example where this came from, CI started failing after the patch update to php-cs-fixer. I think the behavior change happened in PR #4377 

Actually maybe the behavior is now more correct?

Can someone confirm if this a new bug/regression, or an old bug that is fixed.

**Comment by phil-davis** [comment]
@SpacePossum @keradus or whoever - ping.

I think that probably the new behavior is correct. It just needs someone to say that and close this issue. Then I can happily apply the needed/suggested changes in my CI... and move on with life.

**Comment by julienfalque** [comment]
I confirm this behavior change was introduced in #4377. To me it looks like an unintended, yet correct side effect of it. @kubawerlos What do you think?

**Comment by kubawerlos** [comment]
Oh geez, 2nd worst fixer 😨 

Seeing from the PR (no new test for header fixer) it was definitely not intentional.

I hope one day to refactor the fixer, I believe I have even one bug saved somewhere related to surrounding lines.

**Comment by phil-davis** [comment]
Actually the fixing is now more consistent. The higher comment also gets fixed in the same way as the lower comment. So I was thinking that is an improvement.

Now that it is more consistent in fixing, another different question comes up:

- If the comment is followed by code with a variable, then the fixer is happy that the comment starts with `/**`
- But if the comment is followed by code without a variable (e.g. the `echo` above)  then the fixer does not like the comment starting with `/**` - it changes it to `/*`

Is that something in some PSR standard? Or just some accident of the fixers?

**Comment by kubawerlos** [comment]
Is that changed by the `header_comment` fixer? Looks like the change made by `phpdoc_to_comment` fixer.

**Comment by phil-davis** [comment]
It could be a different change between v2.16.1 and v2.16.2 - now I am not sure that I did a full git bisect to identify the exact commit.

In any case, I don't care so much about the forensics - if it is agreed that this change is good, then we can close this issue and all is well.

**Comment by SpacePossum** [comment]
I think the change is good, but the fixer itself is indeed 2nd worst... 

If we all agree that here it is ok'ish what it does than I propose to close this issue and use one of many other `header` issues/PR's to fix it properly

(gotta say to it is kind of weirdly hard to write a good header fixer)
