### ISSUE TITLE
no_unset_on_property is exteremely dangerous

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#4939]
`no_unset_on_property` is exteremely dangerous as it change code hebaviour when the property is a reference.

This behaviour should be documented.

**Comment by julienfalque** [comment]
Just to be sure I understand correctly, could you please share a code snippet that shows what you are describing?

**Comment by mvorisek** [comment]
Here you go:

```
<?php

$x = new \StdClass();
$test = &$x->prop; // make prop property a reference - see https://www.php.net/manual/en/language.references.php

// the issue with null vs unset()
$x->prop = null;
//unset($x->prop); // this is automatically replaced to "$x->prop = null" when rule "no_unset_on_property" is enabled
//unset($x->{'prop'}); // a solution to prevent this CS fixer behaviour - but refactoring does not work then
//'unset'($x->prop); // should be refactorable, but it does not work: Fatal error: Uncaught Error: Call to undefined function unset()

$y = clone $x;
$y->prop = 'x'; // notice, that only prop on $y is set, not on $x!

print_r($x);
print_r($y);
```

**Comment by mvorisek** [comment]
If there is an elegant refactorable solution please advise.

**Comment by julienfalque** [comment]
As I understand:
* the risky description of the rule lacks information about references indeed;
* you *do* want to use `unset()` here so you should not use `no_unset_on_property`. As PHP CS Fixer does not support disabling a rule for a particular place in the code, you should disable the rule completely.

**Comment by SpacePossum** [comment]
@mvorisek can you maybe propose a better description? doesn't have to be in PR form, can be here as comment as well, thanks!

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek can you maybe propose a better description? doesn't have to be in PR form, can be here as comment as well, thanks!

please read the issue description incl. example

the `Risky rule` text should mention something:
```
Changing variables to `null` instead of unsetting them will not unset/break php
reference (if property is reference property) - if you want to keep unset exceptionally unfixed, use `unset($obj->{'prop'})`
```
can be probably better formulated...

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5149
