### ISSUE TITLE
How get line number in my fixer?

### ISSUE THREAD

**Issue by WinterSilence** [FriendsOfPHP/PHP-CS-Fixer#4968]
I want find some tokens after/before current token and not at current line, how do that?
Main question: how get token line?

**Comment by julienfalque** [comment]
Current API does not provide a way to know the line number of a token. If you want to get a token on the line before current token, you can loop backwards until you find a token that contains `\n`.

**Comment by WinterSilence** [comment]
@julienfalque thanks for hint! Exists helper methods for this?

**Comment by SpacePossum** [comment]
@WinterSilence we don't have any helpers for it as we made the design decision to not rely on linenumbers whenever possible as it turns out to be complex and very fragile. I don't know what you are building but if you can avoid using linenumbers inside your fixer I would highly recommend that.

**Comment by WinterSilence** [comment]
@SpacePossum i wrote fixer for normalize sql's ~50-100 strings every query.. sick! dirty solution for dirty code) @julienfalque advice helped
