### ISSUE TITLE
No blank lines between properties

### ISSUE THREAD

**Issue by JesusValera** [FriendsOfPHP/PHP-CS-Fixer#4969]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.3

#### The command you use to run PHP CS Fixer:
=> ./vendor/bin/php-cs-fixer fix

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
class Example
{
    public const FOO = 1;
    public static $bar = [1, 2, 3];
    private bool $baz = false;
    private $qux = [];
    private float $quux = 5.0;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
class Example
{
    public const FOO = 1;

    public static $bar = [1, 2, 3];

    private bool $baz = false;

    private $qux = [];

    private float $quux = 5.0;
}
```

 * with the changes you expected instead:
```php
<?php
class Example
{
    public const FOO = 1;
    public static $bar = [1, 2, 3];
    private bool $baz = false;
    private $qux = [];
    private float $quux = 5.0;
}
```

According to [PSR-12](https://www.php-fig.org/psr/psr-12/#43-properties-and-constants) it shouldn't be spaces between each property. Isn't? :smile: 

Best,

**Comment by julienfalque** [comment]
PHP CS Fixer doesn't have a PSR-12 ruleset yet (see #4502) but on v2.17, `class_attributes_separation` will allow what you want (#4875). Closing as there is nothing left to do here.
