### ISSUE TITLE
Adding blank line after block with braces inside method (if/foreach/for/etc)?

### ISSUE THREAD

**Issue by Soletiq** [FriendsOfPHP/PHP-CS-Fixer#4972]
Hi,

I'd like to add a line break after each `if/foreach/for` (any block with braces) inside a method. Is this possible? This seems like a pretty obvious rule. Who wants 2 if statements right on top of each other?

We recently used php-cs-fixer to convert all single line if statements to the suggested multi-line if statements. So now we have hundreds of cases like this.

#### The PHP version you are using (`$ php -v`):
7.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.16

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * current code:
```php
if (true) {

}
if (true) {

}
```

 * what we want:
```php
if (true) {

}

if (true) {

}
```

**Comment by SpacePossum** [comment]
Hi,

we got the `before` version... but to my surprise not a before variant

```
        'blank_line_before_statement' => [
            'statements' => [
                'break',
                'case',
                'continue',
                'declare',
                'default',
                'do',
                'exit',
                'for',
                'foreach',
                'goto',
                'if',
                'include',
                'include_once',
                'require',
                'require_once',
                'return',
                'switch',
                'throw',
                'try',
                'while',
                'yield',
            ],
        ],
```
