### ISSUE TITLE
Tests now failing

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4983]
I've re-run the travis tests on the 2.16 branch. The following now happens: https://travis-ci.org/github/GrahamCampbell/PHP-CS-Fixer/builds/693144039.

Also, the tests seem to be incorrectly named. `5.0` actually is `5.x`...

<img width="152" alt="image" src="https://user-images.githubusercontent.com/2829600/83354375-30d1fa00-a350-11ea-886d-08559fe4d76f.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/2829600/83354381-392a3500-a350-11ea-9976-ed1758798f3a.png">

**Comment by GrahamCampbell** [comment]
Issues seem to be caused by `symfony/options-resolver` 5.0.9 -> 5.1.0 upgrade and also with the exact messages of silenced deprecation errors.

**Comment by SpacePossum** [comment]
I think this is all resolved now?

**Comment by GrahamCampbell** [comment]
Yes. :)
