### ISSUE TITLE
Braces fixer crashing

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4984]
#### The PHP version you are using (`$ php -v`):
=> 7.4.6

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.3

#### The command you use to run PHP CS Fixer:
=> only the braces fixer enabled

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function foo()
{
    do {
        bar();
    } //comment
    while (baz());
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```
Unexpected '}', expecting while (T_WHILE) on line 8.
```

 * with the changes you expected instead:
```php
<?php

function foo()
{
    do {
        bar();
    } //comment
    while (baz());
}
```

Note that this only happens within a function body. The following code is fine:

```php
do {
    bar();
} //comment
while (baz());
```

**Comment by julienfalque** [comment]
Please give #4884 a try and see if it fixes that issue, thanks!

**Comment by SpacePossum** [comment]
duplicate reporting of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4721
