### ISSUE TITLE
Comments after control structures are moved if "braces" are set to "next"

### ISSUE THREAD

**Issue by pvx-** [FriendsOfPHP/PHP-CS-Fixer#4989]
## Bug report

PHP 7.4.6, PHP-CS-Fixer 2.16.3 (both latest at this time)

Command used:

```sh
php php-cs-fixer-v2.phar fix a.php -v \
  --rules='{ "@Symfony": true, "braces": {"position_after_control_structures": "next"}}'
```

### Code snippet that reproduces the problem

Input:
```php
if(true) // comment
{
    echo "a";
}
```
Expected:
```php
if (true) // comment
{
    echo 'a';
}
```
Actual output:
```php
if (true)
{ // comment
    echo 'a';
}
```

**Comment by pvx-** [comment]
It seems very few people who use braces "next" write comments after control structures ;) (in our code we use it mainly for folding marks).

While (unsuccessfully) trying to fix it myself I found another maybe useful thing - `position_after_functions_and_oop_constructs` behaves differently. This code:

```php
function test($a) // comment
{
  echo 'b';
}
```

is left as-is regardless if it is set to "same" or "next". Without the comment it correctly moves the brace one line up for "same". Code like this:

```php
function test($a) { // comment
  echo 'b';
}
```
is changed to

```php
function test($a)
{ // comment
  echo 'b';
}
```
if set to "next".

So if it is too complicated to fix `position_after_control_structures`, please at least change it to the same behaviour as `position_after_functions_and_oop_constructs` has (leave code as-is, if there is a comment at the end of previous line); I seriously doubt anyone will have a problem with it.

**Comment by SpacePossum** [comment]
I think this issue can be close, the `braces` rule now fixes the input to the expected out from this issue, please give it a try @pvx-

**Comment by pvx-** [comment]
Yes, I tested current version and it works OK; I already lost hope that this will ever be fixed ;), thank you.

**Comment by SpacePossum** [comment]
all credits to the one who made the fix; Julien :)
