### ISSUE TITLE
Incorrect newline added

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4990]
In 1.16.3, the following would rule would not change the code, but now it does (1.16-dev):

```php
[
    'blank_line_before_statement' => ['statements' => ['return']]
]
```

Input:

```php
<?php

function foo()
{
    switch ($foo) {
        case 1:
            return 'bar';
        case 2: // comment
            return 'baz';
        case 3:
            return 'test';
        default:
            return 'foo';
    }
}
```

Diff:

```diff
@@ -6,6 +6,7 @@ function foo()
         case 1:
             return 'bar';
         case 2: // comment
+
             return 'baz';
         case 3:
             return 'test';
```

---

PHP 7.4.6, PHP-CS-Fixer c0f3b0a44f4c465ef15af89378e02b9cd94d885e.

**Comment by GrahamCampbell** [comment]
This seems to have been caused by https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/77234a0ed6ca5414e567b98db312fcc52837d435#diff-7512cf0f0abcd38c0e402b20788674fd.

**Comment by SpacePossum** [comment]
Thanks for reporting!
I'm 98% sure I did this on 2.15 so I send a PR to fix it here

**Comment by GrahamCampbell** [comment]
🚀

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4999
