### ISSUE TITLE
Add "no_general_phpdoc_throws" - feature request 

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5003]
Feature request for "no_general_phpdoc_throws".

Quite important rule to remove `@throws` phpdoc tags as these tags are very often generated by IDEs and very often absolutely unmaitaned.

This rule should support to set excluded/included class (but never both).

**Comment by julienfalque** [comment]
Quite :-1: for me: this looks like a static analysis concern, which is not what PHP CS Fixer is designed for. Something like [pepakriz/phpstan-exception-rules](https://github.com/pepakriz/phpstan-exception-rules) is likely a better solution.

**Comment by mvorisek** [comment]
I do not propose this to be dafault, but it can be helpfull as there is demand (the repo you mentioned is an confirmation to it).

It would be great if this can be (simply, with limitations) set with pur CS fixer only.

**Comment by kubawerlos** [comment]
> Quite important rule to remove `@throws` phpdoc tags

Is it? Where can I find more information about why?

Anyway, it looks like `general_phpdoc_annotation_remove` with `throws` in the list.

**Comment by mvorisek** [comment]
> Anyway, it looks like general_phpdoc_annotation_remove with throws in the list.

Yes, I did not know about `general_phpdoc_annotation_remove`, I seached in the README but did not come to it...

Thank you guys!
