### ISSUE TITLE
ban strlen equals or greater than zero

### ISSUE THREAD

**Issue by gmponos** [FriendsOfPHP/PHP-CS-Fixer#5005]
## Rule request

For performance reasons I would like to ban cases where a developer uses strlen to check if a var is empty or not.

`strlen($str) === 0` ->  `$str === ''`

or

`strlen($str) > 0` ->  `$str !== ''`

### Code snippet that shows how the rule would fix PHP code

Replace this:

```php
<?php strlen($str) > 0;
```

With this

```php
<?php $str !== '';
```
----------------

And replace this:

  ```php
  <?php strlen($str) === 0`;
  ```

with this:

  ```php
  <?php $str === '';
  ```

**Comment by gharlan** [comment]
👍, but the fixer would be risky because of stringable objects.
