### ISSUE TITLE
Wrong work class_attributes_separation

### ISSUE THREAD

**Issue by alksily** [FriendsOfPHP/PHP-CS-Fixer#5015]
## Support question

In my `.php_cs` config file:
```'class_attributes_separation' => ['elements' => ['method', 'property']]```

Code before:
```
abstract class AbstractService extends AbstractComponent
{
    /* ... */

    /**
     * @var array
     */
    protected static array $default_read = [
        'order' => [],
        'limit' => 1000,
        'offset' => 0,
    ];

    /* ... */
}
```

Code after:
```
abstract class AbstractService extends AbstractComponent
{
    /* ... */

    /**
     * @var array
     */
    protected static array

 $default_read = [
     'order' => [],
     'limit' => 1000,
     'offset' => 0,
 ];

    /* ... */
}
```

How to fix it?

**Comment by SpacePossum** [comment]
Hi @alksily and thanks for reporting!

I tried to reproduce the issue on various branches without luck. Can you share the version of the tool and version of PHP you are using? Thanks!

**Comment by alksily** [comment]
Hello @SpacePossum thanks for answer!

PHP: 7.4.6
CS: 2.16.1 Yellow Bird

**Comment by alksily** [comment]
On version `2.16.4 Yellow Bird` the error does not occur

**Comment by SpacePossum** [comment]
Hi!

I think this is fixed here;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/fe3ead21102e76e5035e17bfe82f92ee7804325f#diff-aa9e97d556ec8c39613ee4d6251dea53
so on 2.15.6 and 2.16.4 this should no longer happen.

Let me know if there is still a problem and I'll reopen this report :)

**Comment by alksily** [comment]
Thank you!
