### ISSUE TITLE
braces rule improperly removes new line before php closing tag. 

### ISSUE THREAD

**Issue by dwenaus** [FriendsOfPHP/PHP-CS-Fixer#5019]
## Bug report
   * PHP version: 7.1
   * PHP CS Fixer version: 2.16.3 Yellow Bird
   * run using `php-cs-fixer run`
   * single rule  `'braces' => true,`

### Code snippet that reproduces the problem

  ```php
<?php
my_function();
?>
  ```

results in:
  ```php
<?php
my_function(); ?>
  ```

it also happens in this situation as well:

```php
public function foo() 
{
    $var = 'bar';
    ?> 
    some html 
    <?php
}
```
turns into:
```php
public function foo() 
{
    $var = 'bar'; ?> 
    some html 
    <?php
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,

I think this can be best addressed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4884 (cc @julienfalque)

**Comment by wshaver** [comment]
+1

With any `braces` settings turned on, the open/close php tags get pulled to the same line as this comment.
Super confusing to read, should be on the next line, as it looks like a comment but is ran!
Input:
```
<?php
function sayHello() {
// example comment 
?><div>hello</div><?php
print('hi');
}
```

Output:
```
<?php
function sayHello()
{
    // example comment ?><div>hello</div><?php
print('hi');
}
```

**Comment by SpacePossum** [comment]
yeah that looks truly off :(

**Comment by SpacePossum** [comment]
The last one now get fixed into:
```php
<?php
function sayHello()
{
    // example comment
    ?><div>hello</div><?php
    print('hi');
}
```

The first samples also seems to get properly handled not by the `braces` rule, I suggest closing this issue.
