### ISSUE TITLE
Incorrect alignment of array of arrow functions with binary_operator_spaces

### ISSUE THREAD

**Issue by hackel** [FriendsOfPHP/PHP-CS-Fixer#5020]
## Bug report

The align strategies of the `binary_operator_spaces` fixer give some wonky results when used with an array of arrow functions.  I get the same result with all 3 align options.

### Code snippet that reproduces the problem

```php
<?php
// $initial
$arrowFunctions = [
    'a' => fn ($a1) => fn ($a2) => $a,
    'bIsMuchLonger' => fn ($b1) => fn ($b2) => $b,
    'c' => fn ($c1) => fn ($c2) => $c,
];

// expected
$arrowFunctions = [
    'a'             => fn ($a1) => fn ($a2) => $a,
    'bIsMuchLonger' => fn ($b1) => fn ($b2) => $b,
    'c'             => fn ($c1) => fn ($c2) => $c,
];

// result
$arrowFunctions = [
    'a'             => fn ($a1)             => fn ($a2)             => $a,
    'bIsMuchLonger' => fn ($b1) => fn ($b2) => $b,
    'c'             => fn ($c1)             => fn ($c2)             => $c,
];
```

* PHP version: 7.4.7
* PHP CS Fixer version: 2.16.3
* the command used to run PHP CS Fixer:
`php-cs-fixer fix --rules='{"binary_operator_spaces": {"operators": {"=>": "align_single_space_minimal"}}}'`

**Comment by omgmashina** [comment]
bump

`<?php

$before = [
    'a' => $a,
    'b' => array_map(
        fn ($b) => $b,
        $c
    ),
];

$after = [
    'a'         => $a,
    'b'         => array_map(
        fn ($b) => $b,
        $c
    ),
];
`
