### ISSUE TITLE
VisibilityRequiredFixer not handling whitespaces very well

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#5022]
Currently `VisibilityRequiredFixer` given class:
```php
class Foo
{
    public    int $a;
    public ? int $b;
    public int    $c;
    public    int    $d;
    public    \    Bar    \    Baz    $e;
    public
    int
    $f;
}
```
will  change it to:
```php
class Foo
{
    public int $a;
    public ? int $b;
    public int    $c;
    public int    $d;
    public \    Bar    \    Baz    $e;
    public int
    $f;
}
```
So
 - it does not change whitespaces in and after type
 - it modifies class that already has all visibilities and scope of the fixer suppose to be adding visibility when missing (or in wrong place regarding to other keywords).

I wonder:
1. Should we fix the `VisibilityRequiredFixer` to handle whitespace better?
2. Should we make `VisibilityRequiredFixer` only adding (or moving to the correct place) visibilities and create new fixer (`PropertiesSpaceFixer`?) that will handle whitespace (should `? int` vs `?int` be configurable?)?

**Comment by SpacePossum** [comment]
I would scope down to only add the visibility and than leave the single spacing after visibility and type to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4435 and `?[type]` to `compact_nullable_typehint`

**Comment by GrahamCampbell** [comment]
That syntax will actually be invalid as of PHP 8.0. Spaces in (fully) qualified class names are no longer permitted.

**Comment by kubawerlos** [comment]
But is valid in PHP < 8 as well as all other cases are valid in PHP 8

**Comment by kubawerlos** [comment]
Handled in  https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4435
