### ISSUE TITLE
Support custom phpdoc tag (like phpstan or psalm one) for phpdoc rules like order and separation

### ISSUE THREAD

**Issue by VincentLanglet** [FriendsOfPHP/PHP-CS-Fixer#5026]
## Feature request

Currently, phpdoc rules are only working for *valid* tags.
```
private static $tags = [
    'api', 'author', 'category', 'copyright', 'deprecated', 'example',
    'global', 'internal', 'license', 'link', 'method', 'package', 'param',
    'property', 'property-read', 'property-write', 'return', 'see',
    'since', 'subpackage', 'throws', 'todo', 'uses', 'var', 'version',
];
```

But most of the fixer could work with custom tag too. This could be interesting since more and more developers are using custom phpdoc tag, for example for static analysis.

`phpdoc_order` could for example consider that custom tag should be last and/or support a custom-tag list.

`phpdoc_separation` could at least change 
```
/**
 * @param foo
 * @param bar
 * @phpstan-param foo
 * @phpstan-return baz
 *
 * @return baz
 **/
```
to 
```
/**
 * @param foo
 * @param bar
 *
 * @phpstan-param foo
 * @phpstan-return baz
 *
 * @return baz
 **/
```

**Comment by vladyslavstartsev** [comment]
See https://github.com/sonata-project/SonataAdminBundle/pull/6161#discussion_r443222218 for context
