### ISSUE TITLE
 Explicitly aliased functions are overwritten by the native_function_invocation directive

### ISSUE THREAD

**Issue by danog** [FriendsOfPHP/PHP-CS-Fixer#5027]
## Bug report

From amphp/php-cs-fixer-config#4
Explicitly aliased functions are overwritten by the `native_function_invocation` directive.
The following file:

```php
<?php

namespace Amp;
use function Amp\File\touch;

touch('a');
touch('a');
```

Would be incorrectly "fixed" to:
```php
<?php

namespace Amp;

\touch('a');
\touch('a');
```

**Comment by kubawerlos** [comment]
I believe [this PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4846) is fixing it.

**Comment by SpacePossum** [comment]
I hope so :)  @danog can you provide the details following the bug report template? I'm curious about which version of the tool you are using and which version of PHP. Thanks!

**Comment by danog** [comment]
Welp, seems like this was fixed.
Sorry for the trouble, and thanks for the tool! <3

**Comment by SpacePossum** [comment]
good to hear, thanks for reporting back :+1:  : )
