### ISSUE TITLE
Do not require "exec" function to be enabled

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5030]
This is a feature request to not require "exec" function to be not within `disable_functions`.

Quite important as some users have this php.ini value set even for CLI.

Maybe this is even unintended now because it seems it is called to get console height:
```
vendor\symfony\console\Application.php(110): Symfony\Component\Console\Terminal->getHeight()
```

**Comment by SpacePossum** [comment]
Hi, not sure what we can do here in this repo, shouldn't this be addressed in the SF console code?

**Comment by mvorisek** [comment]
Not every Console needs `exec`, so I think CS fixer calls something that triggers it.

**Comment by SpacePossum** [comment]
That would be an implementation detail of the console package than I guess? we don't call `exec` directly so not sure what we can do in this repo

**Comment by mvorisek** [comment]
Closing, issue addressed in Symfony directly - https://github.com/symfony/symfony/commit/9f6acd549c914dabb9cbcb1a1c5b3f6452de5887

@SpacePossum thank you for your feedback on this

**Comment by SpacePossum** [comment]
thanks for picking this up :+1:

**Comment by SpacePossum** [comment]
ps. when the bug fix is released by the SF team maybe we should up the version in the composer.json in the repo as well? (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.8/composer.json#L24)
