### ISSUE TITLE
Site broken - Download url is broken

### ISSUE THREAD

**Issue by b1rdex** [FriendsOfPHP/PHP-CS-Fixer#5036]
`https://cs.symfony.com/download/php-cs-fixer-v2.phar` returns an HTML page saying GitHub blocked the client.

**Comment by b1rdex** [comment]
Same page is shown on the site: https://cs.symfony.com/

![image](https://user-images.githubusercontent.com/312855/86089206-22136a00-baeb-11ea-91dd-57ac76d2d654.png)

**Comment by SpacePossum** [comment]
Thanks for reporting! I think the site got broken during the release process.
cc @keradus

**Comment by arjanfrans** [comment]
Would be good to see this fixed a.s.a.p.. Some of our CI tests depend on this.

**Comment by LarsGrevelink** [comment]
Everything seems to be up and running again on our side. 👍

**Comment by b1rdex** [comment]
Yes, it's working for now. But I'm in doubt it won't break on the next release again.

**Comment by SpacePossum** [comment]
thanks all for reporting :+1: , good to see this is fixed :)
