### ISSUE TITLE
StandardizeIncrementFixer - static property access handling

### ISSUE THREAD

**Issue by guilliamxavier** [FriendsOfPHP/PHP-CS-Fixer#5042]
## Bug report

The `standardize_increment` rule doesn't correctly handle static property access.

   * PHP version: 7.4.7
   * PHP CS Fixer version: 2.16.4
   * the command used to run PHP CS Fixer: `php-cs-fixer fix snippet.php --rules=@Symfony --using-cache=no -vvv`
   * the configuration file you used: (none)

### Code snippet that reproduces the problem

```php
<?php

A::$b += 1;
```

Expected output: Fixed to:

```php
<?php

++A::$b;
```

Actual output: **Error**:

```
Files that were not fixed due to errors reported during linting after fixing:
   1) /usr/src/z/snippet.php

        [PhpCsFixer\Linter\LintingException]
        PHP Parse error: syntax error, unexpected '++' (T_INC) on line 3.

      Applied fixers: standardize_increment
```

Adding `--diff` to the command shows it wanted to fix to:

```php
<?php

A::++$b;
```

#### Additional info

`$a::$b += 1;` gives the same error.

`$a->$b += 1;` is OK.

**Comment by SpacePossum** [comment]
Thanks for reporting! 
Confirmed as bug on 2.15 and I suspect all versions up

**Comment by SpacePossum** [comment]
ping @ntzm as author of the fixer, maybe you wanna give it try to patch?
