### ISSUE TITLE
Support only monolithic code?

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#5055]
Is it a time to stop support PHP mixed with HTML code?

And support only monolithic code (plus shebang) in all fixers?

Issues like https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4951 are coming from time to time and I doubt all such cases will be fixed as it is not a high priority for anyone.

@keradus, @SpacePossum, @julienfalque WDYT?

**Comment by julienfalque** [comment]
I'm not sure. While it increases the work required to maintain the tool, issues related to inline HTML tend to be simple to fix as far as I know. If the goal is to reduce our maintainance burden, I would give priority to #4810.

**Comment by GrahamCampbell** [comment]
I don't think it's worth the effort of removing tbh. Sure, there may be edge cases that don't work, but nobody says anyone has to spend time fixing those. If someone runs into an issue with it, and wants to fix it, they can.
