### ISSUE TITLE
Make compatible with compose/semver 3

### ISSUE THREAD

**Issue by shyim** [FriendsOfPHP/PHP-CS-Fixer#5058]
## Feature request
    - friendsofphp/php-cs-fixer v2.16.4 requires composer/semver ^1.4 -> satisfiable by composer/semver[1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.x-dev] but these conflict with your requirements or minimum-stability

**Comment by kubawerlos** [comment]
Done in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5048
