### ISSUE TITLE
Usage with generated code in string

### ISSUE THREAD

**Issue by lud** [FriendsOfPHP/PHP-CS-Fixer#5059]
Hi,

We are generating PHP code and we would like to format it with user preferences before writing it to disk. Is the API to do that described somewhere ?

Thank you.

**Comment by SpacePossum** [comment]
Hi,

You can use the tool without files to fix by using the `stdIn`, pass `-` as path value for this and the tool will read from the `stdIn` instead. Let me know if this works for you, been a while since I used it last.

**Comment by lud** [comment]
Hi, thank you for your answer.

I was more thinking about calling the linter directly from php, not from the command line. I have this PHP script that generates PHP code, I would like to run the linter over the string before writing it to the disk.

For now I write them to disk directly and use this big, messy chunk of code to run the linter:

```PHP
use PhpCsFixer\Cache\Directory;
use PhpCsFixer\Cache\NullCacheManager;
use PhpCsFixer\Config;
use PhpCsFixer\Console\ConfigurationResolver;
use PhpCsFixer\Error\ErrorsManager;
use PhpCsFixer\Finder;
use PhpCsFixer\Linter\Linter;
use PhpCsFixer\Runner\Runner;
use PhpCsFixer\ToolInfo;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\EventDispatcher\EventDispatcher;

// . . .

    protected function fixFiles(array $files, OutputInterface $output): void
    {
        /**
         * @var Config
         */
        $phpFixerConfig = require '.php_cs.dist';
        $finder = Finder::create();
        $finder->append($files);

        // @phpstan-ignore-next-line
        $phpFixerConfig->setFinder($finder);

        $resolver = new ConfigurationResolver($phpFixerConfig, [
            'verbosity' => $output->getVerbosity(),
        ], getcwd(), new ToolInfo());

        $eventBus = new EventDispatcher();
        $eventBus->addListener('fixer.file_processed', fn ($event) => $output->write('.'));

        $runner = new Runner(
            $phpFixerConfig->getFinder(),
            $resolver->getFixers(),
            $resolver->getDiffer(),
            $eventBus,
            new ErrorsManager(),
            new Linter($phpFixerConfig->getPhpExecutable()),
            false,
            new NullCacheManager(),
            new Directory(getcwd()),
            false
        );

        $runner->fix();
        $output->writeln('');
    }
```

**Comment by SpacePossum** [comment]
Looking at the code, I think it might be the best there is for now.  As a project we like to provide a CLI tool ready for use and an API but only up to a point. I think this is around that point TBH, as the code doesn't look to bad does it?

**Comment by lud** [comment]
Ok I'll stick to that then. It _does_ look kind of bad to me because it references a lot of internal classes that I really don't know the purpose of, but yep, it works :D

Thank you
