### ISSUE TITLE
no_unused_imports on anonymous function

### ISSUE THREAD

**Issue by vinnygambiny** [FriendsOfPHP/PHP-CS-Fixer#5072]
## Support question

I use the `no_unused_imports` option, that work for the unused import on top of a class. But how to remove unused import in anonymous function like
```
function () use ($variableUnused) {

}
```

Thanks

**Comment by SpacePossum** [comment]
Hi and thanks for your question,

Currently we no rule or option to remove these, it would be great to have though!

**Comment by vinnygambiny** [comment]
Thanks for the reply. I will wait for this rule !

**Comment by kubawerlos** [comment]
@vinnygambiny why wait? Wouldn't be better to implement it?

**Comment by unkind** [comment]
@vinnygambiny try some static PHP analyzer like PhpStan or Psalm. That libraries operate with code on different level (using AST, not just tokenizer) and such issue is probably solved there.

**Comment by SpacePossum** [comment]
I forgot I already made it https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4704  ^_^
