### ISSUE TITLE
Superfluous PHP doc only class name

### ISSUE THREAD

**Issue by seferov** [FriendsOfPHP/PHP-CS-Fixer#5074]
## Feature request

Under NoSuperfluousPhpdocTagsFixer or a new rule, IMHO, it would be nice to remove PHPStorm superfluous class php doc.

Example:

```php
<?php


namespace App;

/**
 * Class Foo
 * @package App
 */
class Foo
{
}
```

`@package` is removed by phpdoc_no_package and this is left after:

```php
<?php


namespace App;

/**
 * Class Foo.
 */
class Foo
{
}
```

I think `Class Foo.` should be removed as superfluous if it is only "Class {className}" since it has no added value.

**Comment by kubawerlos** [comment]
@seferov it was discussed here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4078 without agreement what it should do.

Form what you are asking I can recommend you this [fixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#NoUselessCommentFixer).

**Comment by seferov** [comment]
@kubawerlos that's what I was looking for. The other fixers are useful as well. Thank you!
