### ISSUE TITLE
[RFC] Cache per minor version

### ISSUE THREAD

**Issue by boesing** [FriendsOfPHP/PHP-CS-Fixer#5075]
## Support question

Hey there, I'd like to ask if there are reasons why the cache signature explicitly checks for the exact version.
I wonder if it would be possible to allow minor version differences with e.g. an additional configuration flag?

Would love to get some feedback here.

**Comment by julienfalque** [comment]
This is because even a patch release might change the way some files are fixed. For example, a new release could fix a bug that prevented one of your file from being fixed. If the cache isn't automatically bypassed when installing this new version, you would have to remove the cache  manually to get your file fixed.

**Comment by boesing** [comment]
I see. I am working on a huge project and I'd like to commit the cache file to VCS to avoid waiting for the CS fix/check which takes up to 30+ seconds. That will also slowdown the CI pipeline, which probably is 7.4.3 while some devs are working with 7.4.4 (for example).

I think one has to go with some kind of docker cs-check which ensures proper php version?

**Comment by kubawerlos** [comment]
@boesing you mean minor PHP version, not PHP CS Fixer version as @julienfalque (and I too when reading firs comment) understood.

What exactly are you trying to achieve? Speed up your CI? Can't you simply cache `.php_cs.cache` file between the builds?

If you really, really must commit the cache then you can go with something like this:
```php
->setCacheFile(__DIR__ . '/cache/php-cs-fixer/. PHP_VERSION_ID . '.cache')
```
in the config, so each version has it's own cache, but it would be a nightmare to keep it up to date.

**Comment by boesing** [comment]
Thats an idea. 👍🏻
Gonna try that!

**Comment by SpacePossum** [comment]
Thanks for the suggestion! I think the use case is not very typical for our users and I think you can still achieve what you want following kubawerlos suggestion. As such I'm closing here, but feel free to comment and we can always reopen if needed/wanted.
