### ISSUE TITLE
You must call one of in() or append() methods before iterating over a Finder. 

### ISSUE THREAD

**Issue by hediyebykkolaybi** [FriendsOfPHP/PHP-CS-Fixer#5086]
## Support question
Hi,
When I run php-cs-fixer fix command, I get the following error. can you help me ? thank you.

You must call one of in() or append() methods before iterating over a Finder.

**Comment by SpacePossum** [comment]
Hi,

This most like because of the configuration you've for your file finder. We use the [Symfony finder](https://symfony.com/doc/current/components/finder.html) (click for docs). If the docs don't help please share your configuration file so we can try to help.

**Comment by SpacePossum** [comment]
Let me know if the linked doc is of any help or if you can share more details about your setup so we can help more, till than I'm going to close here and we can reopen when needed.
