### ISSUE TITLE
PhpdocToParamTypeFixer - states option 'scalar_types' but never uses it

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#5089]
Configuration is not used by the fixer, must be removed.

**Comment by GrahamCampbell** [comment]
It looks like it was meant to be used in the same way the return type fixer uses it.

**Comment by GrahamCampbell** [comment]
TBH, I don't think "scalar_types" is a very good option anyway. It'd be better to allow someone to say the minimum PHP version they wanna be compatible with. Other syntax than scalar types to be configured would be void (not for param), nullable, mixed, object, iterable, and union types. Indeed, nullable union types is also special.
