### ISSUE TITLE
Upload latest 2.16 version to cs.symfony.com/download link

### ISSUE THREAD

**Issue by andrew-demb** [FriendsOfPHP/PHP-CS-Fixer#5099]
## Feature request

The suggested link to download package phar from https://cs.symfony.com/download/php-cs-fixer-v2.phar contains the 2.15.8 version, but the newest version is `v2.16.4`.

Maybe because version `2.15.8` published later than `2.16.4` (difference in time - 5 minutes).

Can you upload latest version to cs.symfony.com?

**Comment by andrew-demb** [comment]
Seems that issue resolved.

Downloaded phar now have a version 2.16.4

**Comment by kbond** [comment]
I'm having this problem now. https://cs.symfony.com/download/php-cs-fixer-v2.phar is v2.15.8

**Comment by kubawerlos** [comment]
There is the latest version. Have you tried a link in incognito mode or something like this to avoid hitting browser cache?

To verify there is latest version run this:
```php
<?php
$content = file_get_contents('https://cs.symfony.com/download/php-cs-fixer-v2.phar');
echo substr($content, strpos($content, 'const VERSION') - 44, 70);
```

it can be seen here: https://paiza.io/projects/HfRtyQCxl5RHJZqXDxnyeg

**Comment by guillaumesmo** [comment]
I'm experiencing this issue too, output of https://paiza.io/projects/HfRtyQCxl5RHJZqXDxnyeg few seconds ago:
`
class Application extends BaseApplication
{
const VERSION = '2.15.8';
`

**Comment by kubawerlos** [comment]
WTF? Now both paiza URLs, my local PC and the link https://cs.symfony.com/download/php-cs-fixer-v2.phar resulting with 2.15.8.

Yesterday it was 2.16.4.

**Comment by keradus** [comment]
i guess this is orphan ticket, version in download link is valid
```
ker@dus:~/Downloads λ php php-cs-fixer-v2.phar --version
PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski (18f8c9d)
```

closing for now, in case of issue re-appearing, please create a new ticket or reach out via gitter
