### ISSUE TITLE
How to remove extra spaces before equals?

### ISSUE THREAD

**Issue by Aerendir** [FriendsOfPHP/PHP-CS-Fixer#5102]
After running a series of automated tools, I have this block of code in various classes:

```php
class MyCommand
{
    /** @var string */
    private const NAME            = 'my:command:name';
    /** @var string */
    protected static $defaultName = self::NAME;
...
```

As you can see, the automated tools added DockBlock comments to `NAME` and `$defaultName`.

They was once without DocBlocks, and so they was aligned:

```php
class MyCommand
{
    private const NAME            = 'my:command:name';
    protected static $defaultName = self::NAME;
```

But now, with the DocBlock comment, they should not be aligned anymore and should be only one space before and one after the equal sign:

```php
class MyCommand
{
    private const NAME = 'my:command:name';
    protected static $defaultName = self::NAME;
```

Any idea how to realign the equals?

PS
Don't give attention to the wrong code: it is being refactored.

**Comment by SpacePossum** [comment]
Hi!

To remove the extra spacing you can use the `binary_operator_spaces` rule.
From:

```php
class MyCommand
{
    /** @var string */
    private const NAME             = 'my:command:name';
    /** @var string */
    protected static $defaultName = self::NAME;
}
```

to

```php
class MyCommand
{
    /** @var string */
    private const NAME = 'my:command:name';
    /** @var string */
    protected static $defaultName = self::NAME;
}

```

make sure you don't have the alignment configured for `=` and you should be good I think.

**Comment by Aerendir** [comment]
@SpacePossum , thank you for your comment :)

I already have this rule configured:

```php
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals' => true,
        ],
```

When you write

>make sure you don't have the alignment configured for `=` and you should be good I think.

Is what you mean?

**Comment by SpacePossum** [comment]
hi,

If you want to remove the space before `=` than you should not align these, so do not set it to `true`.
This should work:
```
'binary_operator_spaces' => ['operators' => ['=' => 'single_space']]
```

**Comment by Aerendir** [comment]
@SpacePossum , the point is this: I want to align `=` if they are on consecutive lines (line 1, line 2, line 3, ...); I don't want to align if they are not on consecutive lines.

So, this is correct:

```php
class MyCommand
{
    private const NAME            = 'my:command:name';
    protected static $defaultName = self::NAME;
```

While this is not:

```php
class MyCommand
{
    /** @var string */
    private const NAME            = 'my:command:name';
    /** @var string */
    protected static $defaultName = self::NAME;
```

Using the config you are suggesting me, it seems to me that I always have the one or the other, doesn't it?

**Comment by SpacePossum** [comment]
I see now! Sadly I cannot remember we've the logic to do is.
`binary_operator_spaces` is already far from perfect and very complex so I doubt we'll add support for your use case anytime soon.

**Comment by Aerendir** [comment]
@SpacePossum , ok, thanks! I think I will find a workaround in some ways... Thank you for your support and clarifications!

I'm going to close this...

**Comment by SpacePossum** [comment]
wish I could've been of more help, thanks and good luck :)

**Comment by joshbmarshall** [comment]
For those who arrive here, the answer is now:

```
'binary_operator_spaces' => ['operators' => ['=' => 'align_single_space_minimal']]
```
