### ISSUE TITLE
'class_keyword_remove' rule prepends current namespace even if already fully qualified

### ISSUE THREAD

**Issue by paulbalandan** [FriendsOfPHP/PHP-CS-Fixer#5104]
## Bug report

- PHP 7.4.8
- PHP CS Fixer 2.16.4 Yellow Bird
- included `class_keyword_remove` rule in php_cs.dist
- `vendor/bin/php-cs-fixer fix -v`

---
The rule fails on these instances and will just prepend the current namespace.:
- The class name with `::class` is fully qualified.
- The class name with `::class` is fully qualified and has a corresponding `use` statement.

### Code Snippet
**Before**
```php
<?php

namespace Acme\Foo\Bar;

use Acme\Foo\Exception\RuntimeException;

class Test
{
    public $runtime = Acme\Foo\Exception\RuntimeException::class;
    public $logic   = \Acme\Foo\Exception\LogicException::class;
}
```

**After**
```php
<?php

namespace Acme\Foo\Bar;

class Test
{
    public $runtime = 'Acme\Foo\Bar\Acme\Foo\Exception\RuntimeException';
    public $logic   = 'Acme\Foo\Bar\Acme\Foo\Exception\LogicException';
}
```

**Comment by kubawerlos** [comment]
The first example is actually correct, without leading `\` you are in namespace "context", so calling any class will go deeper in the namespaces, see: https://3v4l.org/iRPac

The second case is fixed in: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5105 - do not hesitate to make review ;)
