### ISSUE TITLE
TernaryOperatorSpacesFixer - goto label handling

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#5107]
## Bug report

https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/02a63e3f2d63f1b484ef764b6c9a365e82beb72d has caused the TernaryOperatorSpacesFixer to add whitespace to labels which are not ternary expressions.

### Code snippet that reproduces the problem

PHP 7.4.9, php-cs-fixer master.

Input:

```php
<?php

beginning:
echo $guard ? 'foo' : 'bar';
```

Expected output: no change

Actual output:

```php
<?php

beginning :
echo $guard ? 'foo' : 'bar';
```

// cc @kubawerlos, @SpacePossum

**Comment by GrahamCampbell** [comment]
That commit also seems to have incorrectly changed the file permissions of some of the files:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/2829600/89730543-763d3280-da37-11ea-9545-0794cd2f13a8.png">

**Comment by SpacePossum** [comment]
I never knew this was valid PHP, what is `beginning:` here? a comment/documentation feature or something?

**Comment by GrahamCampbell** [comment]
Yes, it's a goto label. Goto can be very useful for doing tail recursion. Compiled languages can compile tail recursive code to an iterative process, however PHP cannot. This example with beginning actually comes from the `laravel/framework` codebase! ;)

The full example, if you are interested, is:

```
if (! function_exists('retry')) {
    /**
     * Retry an operation a given number of times.
     *
     * @param  int  $times
     * @param  callable  $callback
     * @param  int  $sleep
     * @param  callable|null  $when
     * @return mixed
     *
     * @throws \Exception
     */
    function retry($times, callable $callback, $sleep = 0, $when = null)
    {
        $attempts = 0;

        beginning:
        $attempts++;
        $times--;

        try {
            return $callback($attempts);
        } catch (Exception $e) {
            if ($times < 1 || ($when && ! $when($e))) {
                throw $e;
            }

            if ($sleep) {
                usleep($sleep * 1000);
            }

            goto beginning;
        }
    }
}
```
