### ISSUE TITLE
ReturnAssignmentFixer should not fix self referencing functions

### ISSUE THREAD

**Issue by bendavies** [FriendsOfPHP/PHP-CS-Fixer#5108]
## Bug report

  Please describe the problem and provide technical details such as:
   * PHP version: 7.4.8
   * PHP CS Fixer version: 2.16.4
   * the command used to run PHP CS Fixer: `vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --show-progress=estimating --verbose --rules return_assignment file.php`

The following snippet shows that ReturnAssignmentFixer is sometimes removing assignment of variables where it should not, because the assigned variable is referenced.

### Code snippet that reproduces the problem

  ```php
<?php

class Bar
{
    public function __construct(callable $callable)
    {
    }
}

function foo(): callable
{
    $bar = new Bar(function () use (&$bar): void {
        echo get_class($bar);
    });

    return $bar;
}
  ```
after:
  ```php
<?php

class Bar
{
    public function __construct(callable $callable)
    {
    }
}

function foo(): callable
{
    return new Bar(function () use (&$bar): void {
        echo get_class($bar);
    });
}
  ```

**Comment by SpacePossum** [comment]
Hi and thanks for your report.

Could you update the example to a working one so I can understand the issue better?
For example with the current `before` code, when the function `foo` is called `$bar` is not defined yet:

```php
<?php

class Bar
{
    public function __construct(callable $callable)
    {
        $callable();
    }
}

function foo()
{
    $bar = new Bar(function () use (&$bar) {
        echo get_class($bar);
    });

    return $bar;
}

foo();
```

> get_class() expects parameter 1 to be object, null given 

when `$bar` is defined before passing it into the static function it is no longer simplified by the rule.

**Comment by SpacePossum** [comment]
Closing as no valid sample has been provided to reproduce the issue. Happy to reopen if someone comments such a sample below :+1:
