### ISSUE TITLE
请问header_comment怎么设置标题不要替换描述

### ISSUE THREAD

**Issue by 233cy** [FriendsOfPHP/PHP-CS-Fixer#5117]
比如我设置了一个header_comment
![image](https://user-images.githubusercontent.com/29916783/90753480-3fa2ca00-e30b-11ea-8544-fe8c2cbe8d01.png)

我要怎么样设置让描述那里，不要每次格式化的时候被格式化

**Comment by 233cy** [comment]
@elliot @sebastianbergmann

**Comment by SpacePossum** [comment]
Hi @233cy,
 could you maybe following the reporting template and translate this into English as I don't think we can be of much help otherwise sadly.
