### ISSUE TITLE
求助，php-cs-fixer中header怎么样设置一个描述文件的行，不要每次格式化的时候被替换

### ISSUE THREAD

**Issue by 233cy** [FriendsOfPHP/PHP-CS-Fixer#5118]
求助，php-cs-fixer中header怎么样设置一个描述文件的行，不要每次格式化的时候被替换

**Comment by 233cy** [comment]
@EvanDotPro @ridcully

**Comment by SpacePossum** [comment]
Hi @233cy,
 could you maybe following the reporting template and translate this into English as I don't think we can be of much help otherwise sadly.
