### ISSUE TITLE
Files that were not fixed due to errors reported during linting before fixing

### ISSUE THREAD

**Issue by hafrit** [FriendsOfPHP/PHP-CS-Fixer#5121]
PHP => 7.4.7
php-cs-fixer => 2.16.4
Symfony => 4.4.11
Command used => php-cs-fixer fix --rules=@Symfony --verbose --show-progress=estimating

This is my class

`<?php

namespace App\Manager;

use DateInterval;
use Psr\Cache\InvalidArgumentException;
use Symfony\Component\Cache\Adapter\AdapterInterface;
use Symfony\Component\Cache\CacheItem;

class RedisCacheManager
{
    /**
     * @var AdapterInterface
     */
    protected AdapterInterface $cache;

    /**
     * @var \DateInterval
     */
    protected DateInterval $cacheInterval;

    /**
     * RedisCacheManager constructor.
     *
     * @param AdapterInterface $cache
     */
    public function __construct(AdapterInterface $cache)
    {
        $this->cache = $cache;
        $this->cacheInterval = new DateInterval('P2D');// the item will be cached for 2 days
    }
    
    /**
     * @param string $key
     * @param        $dataToCache
     *
     * @return CacheItem
     */
    public function manageCacheItem(string $key, $dataToCache): CacheItem
    {
        $item = $this->getItemFromCache($key);
        
        return $this->populateItemToCache($item, $dataToCache);
    }
    
    /**
     * @param string $key
     *
     * @return CacheItem
     */
    private function getItemFromCache(string $key): CacheItem
    {
        $item = new CacheItem();
        $cacheKey = $key;
        
        try {
            $item = $this->cache->getItem($cacheKey);
        } catch (InvalidArgumentException $e) {
            //Do nothing let's continue
        }
        
        return $item;
    }
    
    /**
     * @param CacheItem $item
     * @param $dataToCache
     *
     * @return CacheItem
     */
    private function populateItemToCache(CacheItem $item, $dataToCache): CacheItem
    {
        if (!$item->isHit()) {
            $item->set($dataToCache);
            $item->expiresAfter($this->cacheInterval);
            $this->cache->save($item);
        }
        
        return $item;
    }
}
`

**Comment by hafrit** [comment]
Actually the version of PHP on the machine is 7.3 while the container is 7.4.
Since PHP-CS-FIXER is locally it is executed by php version 7.3 on php code 7.4.

Not issue to close please and thank you @kubawerlos and @mfn

**Comment by SpacePossum** [comment]
thanks for reporting back @hafrit and good to see it resolved :+1:
