### ISSUE TITLE
What does the SCA part of COMMIT_SCA_FILES mean?

### ISSUE THREAD

**Issue by rquadling** [FriendsOfPHP/PHP-CS-Fixer#5128]
Stupid question I'm sure, but I've seen this in the docs and, via the joys of cut'n'paste, in our own pipelines.

I can see it is a used to get a list of files that have changed as compared to the target branch (that's the use case I see), but there was a change from `files` to `COMMIT_SCA_FILES` back in 2017 (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2567#pullrequestreview-24000294).

I'm sure it is really obvious ... but I'm stumped.

**Comment by SpacePossum** [comment]
Hi,

This seems to have been renamed again to `CHANGED_FILES`;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/02ed5435cc392935c5eba97783bc57588b11f1fb
(Aug 20, 2017)

I think the initial naming might have come from being a part of this project own CI scripts and have later been renamed and clean upped for a more generic use case and part of the documentation.

**Comment by keradus** [comment]
Closing the thread, as it's not really a raised issue or feature request, it's an open question that can be addressed on our gitter community or anywhere - including this thread, as it's already created. So don't hesitate to continue this thread even if it's "closed", I'm not "locking" it ;)

SCA - Static Code Analysis

**Comment by mfn** [comment]
> SCA - Static Code Analysis

![mindblowing](https://user-images.githubusercontent.com/87493/91735960-51a72700-ebad-11ea-880d-22857c577b27.gif)

**Comment by rquadling** [comment]
Thank you.
