### ISSUE TITLE
phpdoc_inline_tag wrongly changes @inheritDoc (camelcase) to inheritdoc (lowercase: wrong)

### ISSUE THREAD

**Issue by Aerendir** [FriendsOfPHP/PHP-CS-Fixer#5141]
## Code snippet that reproduces the problem

  ```diff
  <?php
class MyClass {
    /**
-     * {@inheritDoc}
+     * {@inheritdoc}
     */
    public function __set(string $field, $value): void
    {
    }
}
  ```

The correct tag is `inheritDoc`, in camelCase, not `inheritdoc`, in lowercase.
Source: https://docs.phpdoc.org/latest/guides/inheritance.html#the-inheritdoc-tag

This causes PHPStan not be able to recognize the `@inheritDoc` tag, causing the static analysis to fail.

**Comment by SpacePossum** [comment]
this has been fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2619
