### ISSUE TITLE
Tried to create table this happened

### ISSUE THREAD

**Issue by Prajwol213** [FriendsOfPHP/PHP-CS-Fixer#5150]
C:\Users\Dell\BLOG (master)
λ php artisan make:model post -m

Warning: Unsupported declare 'strict_types' in C:\Users\Dell\BLOG\vendor\phpunit\phpunit\src\Framework\Assert\Functions.php on line 1

Fatal error: Default value for parameters with a class type hint can only be NULL in C:\Users\Dell\BLOG\vendor\phpunit\phpunit\src\Framework\Assert\Functions.php on line 86

**Comment by mfn** [comment]
Wrong repository?

**Comment by SpacePossum** [comment]
Hi @Prajwol213 

Your question seems to be about another project and is most likely related to running it on an older version of PHP.
I think your best bet for support is over at the other project, good luck!
