### ISSUE TITLE
Shouldn't phpdoc_types_order => ['null_adjustment' => 'always_first',] sort 'void' first too ?

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#5152]
## Bug report

Shouldn't in `@return string|void` the 'void' be treated like null when asking to order nulls first ?

```
$ php -v
PHP 7.3.22-1+ubuntu18.04.1+deb.sury.org+1
$ vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.16.4 Yellow Bird by Fabien Potencier and Dariusz Ruminski
```

### Code snippet that reproduces the problem

E.g. something like the following `.php_cs`:
  ```php
  <?php
return PhpCsFixer\Config::create()
    ->setRules([
        'phpdoc_types_order' => [
            'null_adjustment' => 'always_first',
            'sort_algorithm' => 'alpha'
        ]
    ])
  ```

Should sort this ([pretty stock from Laravel](https://github.com/laravel/laravel/blob/40f93daa83b17ad47c51ec9beed4c1ba79eb66ed/app/Http/Middleware/Authenticate.php), just vimeo/psalm replacing null with void in the past):

```php
<?php declare(strict_types=1);

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;
use function route;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param Request $request
     * @return string|void
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }
}
```
as `@return void|string`, since return void is null-ish.

**Comment by HenkPoley** [comment]
For now I replaced 'void|' with 'null|' in my code, as that might be more propper.

**Comment by julienfalque** [comment]
Mixing `void` with other possible return types does not make sense: `void` specifically means the function never returns any value, including `null`. I'm closing as I don't think this should be implemented.

**Comment by HenkPoley** [comment]
Fine with me. I fixed the annotation bug at Laravel too.
