### ISSUE TITLE
Null coalescing operator makes yoda_style rule to fail

### ISSUE THREAD

**Issue by fluffycondor** [FriendsOfPHP/PHP-CS-Fixer#5154]
## Bug report

For code like this: `(($_SERVER['HTTP_HEADER'] ?? '') === 'test')` yoda_style rule does nothing.
I think the code above should be changed to `('test' === ($_SERVER['HTTP_HEADER'] ?? ''))`.

```
PHP 7.3.21-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:10) ( NTS )
PHP CS Fixer 2.16.4 Yellow Bird by Fabien Potencier and Dariusz Ruminski (1023c34)
php-cs-fixer fix --verbose --diff --config ".php_cs.dist"

<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . DIRECTORY_SEPARATOR . 'src')
    ->notPath('Kernel.php')
    ->in(__DIR__ . DIRECTORY_SEPARATOR . 'public')
    ->notPath('index.php')
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        '@PhpCsFixer' => true,
        'declare_strict_types' => true,
        'concat_space' => ['spacing' => 'one'],
        'ordered_class_elements' => false,
        'phpdoc_add_missing_param_annotation' => false,
        'binary_operator_spaces' => [
            'default' => 'single_space',
            'operators' => [
                '=>' => null,
                '=' => null,
            ],
        ],
        'phpdoc_to_comment' => false, // breaks @var on return statements
    ])
    ->setFinder($finder)
;

```

### Code snippet that reproduces the problem

  ```php
<?php

if (($_SERVER['HTTP_X_HEADER'] ?? '') !== 'something') {
    return;
}
  ```

**Comment by hamdrew** [comment]
Yoda conditions are intended to avoid accidental assignments when comparing a variable.  The left side of your example condition is comparing the value of the **conditional expression** `($_SERVER['HTTP_X_HEADER'] ?? '')`, which is not considered a variable.  You can verify this by trying to assign `'something'` to the conditional expression:

```php
// The bad thing you're trying to avoid
($_SERVER['HTTP_X_HEADER'] ?? '') = 'something'
```

You will receive the error: `Parse error: syntax error, unexpected '='`

Yoda conditions [increase the cognitive load of reading code](https://en.wikipedia.org/wiki/Yoda_conditions#Criticism), so it's better not to use them if you don't need to protect from accidental variable assignment or unsafe null behavior.  Your use of the null-coalescing operator is a good example of _safe_ null behavior. :)

If you're curious, [this is where](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/src/Fixer/ControlStructure/YodaStyleFixer.php#L374) YodaStyleFixer determines if the left and ride side of a comparison are eligible to be swapped. 

Recommend wontfix tag on this, but this was a good test case to bring up!

**Comment by SpacePossum** [comment]
Thanks for reporting @fluffycondor , and thanks for the detailed response @hamdrew !

I think your report is valid, as we fix the form `($a === 1)` we should/could also fix `(($a) === 1)` IMHO. 

There is a lot to say about Yoda or not Yoda and since we found ourselves so divided we offer it all :D you can fix to Yoda, fix to not-Yoda or configure to allow both (i.e. don't touch).
