### ISSUE TITLE
rule combine_nested_dirname makes code sniffer doesn´t work in Visual Studio Code

### ISSUE THREAD

**Issue by pablolopezmestre** [FriendsOfPHP/PHP-CS-Fixer#5158]
## Bug report

Hi
- PHP version: PHP 7.4.10 (cli) (built: Sep  3 2020 18:21:42)
- PHP CS Fixer version: PHP CS Fixer 2.16.4 Yellow Bird by Fabien Potencier and Dariusz Ruminski (1023c34)
- Visual Studio Code: Version: 1.49.1
- Configuration file:

`<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        //'backtick_to_shell_exec' => xxxx,
        'binary_operator_spaces' => [
            'align_double_arrow' => false,
            'align_equals' => false,
        ],
        'blank_line_after_namespace' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => ['statements' => ['break', 'continue', 'declare', 'die', 'do', 'exit', 'for', 'foreach', 'if', 'return', 'switch', 'throw', 'try', 'while']],
        'braces' => [
            'allow_single_line_closure' => false,
            'position_after_anonymous_constructs' => 'same',
            'position_after_control_structures' => 'same',
            'position_after_functions_and_oop_constructs' => 'next',
        ],
        'cast_spaces' => [
            'space' => 'single',
        ],
        'class_attributes_separation' => ['elements' => ['method']],
        'class_definition' => [
            'multi_line_extends_each_single_line' => false,
            'single_item_single_line' => false,
            'single_line' => true,
        ],
        'class_keyword_remove' => false,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        /*'combine_nested_dirname' => true, // >= 7.0*/
        //'comment_to_phpdoc' => xxxx,
        'compact_nullable_typehint' => true, // >= 7.1
        'concat_space' => ['spacing' => 'one'],
        'constant_case' => ['case' => 'lower'],
        //'date_time_immutable' => xxxx,
        'declare_equal_normalize' => ['space' => 'single'],
        /*'declare_strict_types' => true, // >= 7.0*/
        //'dir_constant' => xxxx,
        //'doctrine_annotation_array_assignment' => xxxx,
        //'doctrine_annotation_braces' => xxxx,
        //'doctrine_annotation_indentation' => xxxx,
        //'doctrine_annotation_spaces' => xxxx,
        'elseif' => true,
        'encoding' => true,
        /*'ereg_to_preg' => true,*/
        //'error_suppression' => xxxx,
        //'escape_implicit_backslashes' => xxxx,
        'explicit_indirect_variable' => true, // >= 7.0
        'explicit_string_variable' => true,
        //'final_class' => xxxx,
        //'final_internal_class' => xxxx,
        //'final_public_method_for_abstract_class' => xxxx,
        'final_static_access' => true,
        //'fopen_flag_order' => true,
        //'fopen_flags' => true,
        'full_opening_tag' => true,
        'fully_qualified_strict_types' => true,
        'function_declaration' => ['closure_function_spacing' => 'none'],
        /*'function_to_constant' => array('functions' => ['get_called_class', 'get_class', 'get_class_this', 'php_sapi_name', 'phpversion', 'pi']),*/
        'function_typehint_space' => true,
        //'general_phpdoc_annotation_remove' => xxxx,
        'global_namespace_import' => [
            'import_constants' => true,
            'import_functions' => true,
            'import_classes' => true,
        ],
        //'header_comment' => xxxx,
        'heredoc_indentation' => true, // >= 7.3
        //'heredoc_to_nowdoc' => xxxx,
        //'implode_call' => xxxx,
        'include' => true,
        'increment_style' => ['style' => 'post'],
        'indentation_type' => true,
        /*'is_null' => array('use_yoda_style' => true),*/
        //'line_ending' => true,
        'linebreak_after_opening_tag' => true,
        //'list_syntax' => xxxx,
        /*'logical_operators' => true,*/
        'lowercase_cast' => true,
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        /*'mb_str_functions' => true,*/
        'method_argument_space' => [
            'keep_multiple_spaces_after_comma' => false,
            'ensure_fully_multiline' => false,
            'on_multiline' => 'ensure_single_line',
            'after_heredoc' => false,
        ],
        'method_chaining_indentation' => true,
        /*'modernize_types_casting' => true,*/
        'multiline_comment_opening_closing' => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        //'native_constant_invocation' => xxxx,
        'native_function_casing' => true,
        //'native_function_invocation' => xxxx,
        'native_function_type_declaration_casing' => true,
        'new_with_braces' => true,
        //no_alias_functions' => ['sets' => ['@internal', '@IMAP', '@mbreg', '@all']],
        'no_alternative_syntax' => true,
        //'no_binary_string' => xxxx,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_blank_lines_before_namespace' => true,
        'no_break_comment' => true,
        'no_closing_tag' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        //'no_extra_blank_lines' => xxxx,
        //'no_homoglyph_names' => xxxx,
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        //'no_mixed_echo_print' => xxxx,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization' => true,
        //'no_php4_constructor' => xxxx,
        'no_short_bool_cast' => true,
        //'no_short_echo_tag' => xxxx,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => true,
        'no_spaces_inside_parenthesis' => true,
        'no_superfluous_elseif' => true,
        //'no_superfluous_phpdoc_tags' => xxxx,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unneeded_curly_braces' => true,
        //'no_unneeded_final_method' => xxxx,
        //'no_unreachable_default_argument_value' => xxxx,
        'no_unset_cast' => true,
        /*'no_unset_on_property' => true,*/
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        //'non_printable_character' => xxxx,
        'normalize_index_brace' => true,
        //'not_operator_with_space' => xxxx,
        'not_operator_with_successor_space' => true,
        'nullable_type_declaration_for_default_null_value' => ['use_nullable_type_declaration' => true],
        'object_operator_without_whitespace' => true,
        //'ordered_class_elements' => xxxx,
        //'ordered_imports' => xxxx,
        //'ordered_interfaces' => true,
        //'php_unit_construct' => xxxx,
        //'php_unit_dedicate_assert' => xxxx,
        //'php_unit_dedicate_assert_internal_type' => xxxx,
        //'php_unit_expectation' => xxxx,
        //'php_unit_fqcn_annotation' => xxxx,
        //'php_unit_internal_class' => xxxx,
        //'php_unit_method_casing' => xxxx,
        //'php_unit_mock' => xxxx,
        //'php_unit_mock_short_will_return' => xxxx,
        //'php_unit_namespaced' => xxxx,
        //'php_unit_no_expectation_annotation' => xxxx,
        //'php_unit_ordered_covers' => xxxx,
        //'php_unit_set_up_tear_down_visibility' => xxxx,
        //'php_unit_size_class' => xxxx,
        //'php_unit_strict' => xxxx,
        //'php_unit_test_annotation' => xxxx,
        //'php_unit_test_case_static_method_calls' => xxxx,
        //'php_unit_test_class_requires_covers' => xxxx,
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
        'phpdoc_align' => true,
        'phpdoc_annotation_without_dot' => false,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag' => true,
        //'phpdoc_line_span' => xxxx,
        //'phpdoc_no_access' => xxxx,
        //'phpdoc_no_alias_tag' => xxxx,
        'phpdoc_no_empty_return' => true,
        //'phpdoc_no_package' => xxxx,
        //'phpdoc_no_useless_inheritdoc' => xxxx,
        'phpdoc_order' => true,
        'phpdoc_return_self_reference' => true,
        'phpdoc_scalar' => ['types' => ['boolean', 'callback', 'double', 'integer', 'real', 'str']],
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_summary' => true,
        'phpdoc_to_comment' => true,
        //'phpdoc_to_param_type' => xxxx,
        //'phpdoc_to_return_type' => xxxx,
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => true,
        'phpdoc_var_annotation_correct_order' => true,
        //'phpdoc_var_without_name' => xxxx,
        /*'pow_to_exponentiation' => true,*/
        //'protected_to_private' => xxxx,
        //'psr0' => xxxx,
        //'psr4' => xxxx,
        //'random_api_migration' => xxxx,
        'return_assignment' => true,
        'return_type_declaration' => ['space_before' => 'none'],
        /*'self_accessor' => true,*/
        'self_static_accessor' => true,
        'semicolon_after_instruction' => true,
        /*'set_type_to_cast' => true,*/
        'short_scalar_cast' => true,
        'simple_to_complex_string_variable' => true,
        'simplified_null_return' => true,
        'single_blank_line_at_eof' => true,
        /*'single_blank_line_before_namespace' => true,*/
        'single_class_element_per_statement' => ['elements' => ['const', 'property']],
        'single_import_per_statement' => true,
        'single_line_after_imports' => true,
        'single_line_comment_style' => ['comment_types' => ['asterisk', 'hash']],
        'single_line_throw' => true,
        'single_quote' => ['strings_containing_single_quote_chars' => false],
        'single_trait_insert_per_statement' => true,
        'space_after_semicolon' => ['remove_in_empty_for_expressions' => false],
        'standardize_increment' => true,
        'standardize_not_equals' => true,
        //'static_lambda' => xxxx,
        /*'strict_comparison' => true,*/
        /*'strict_param' => true,*/
        //'string_line_ending' => xxxx,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_null_coalescing' => true, // >= 7.0
        'trailing_comma_in_multiline_array' => ['after_heredoc' => false],
        'trim_array_spaces' => true,
        'unary_operator_spaces' => true,
        'visibility_required' => ['elements' => ['property', 'method', 'const']], // >= 7.1
        /*'void_return' => true, // >= 7.1*/
        'whitespace_after_comma_in_array' => true,
        'yoda_style' => [
            'equal' => true,
            'identical' => true,
            'less_and_greater' => null,
            'always_move_variable' => false,
        ],
    ])
    //->setIndent("\t")
    ->setLineEnding("\n");`

In this configuration file there are rules with inline comments (//) that are rules that do not apply in my project, just commented. There are other rules with block comments (/* */, which are the ones that doesn't works, and are listed below:

- 'combine_nested_dirname' => true,
- 'declare_strict_types' => true,
- 'ereg_to_preg' => true,
- 'function_to_constant' => array('functions' => ['get_called_class', 'get_class', 'get_class_this', 'php_sapi_name', 'phpversion', 'pi']),
- 'is_null' => array('use_yoda_style' => true),
- 'logical_operators' => true,
- 'mb_str_functions' => true,
- 'modernize_types_casting' => true,
- 'no_unset_on_property' => true,
- 'pow_to_exponentiation' => true,
- 'self_accessor' => true,
- 'set_type_to_cast' => true,
- 'single_blank_line_before_namespace' => true,  (Only in this case, "PHP CS Fixer: php general error." message appears in VS Code)
- 'strict_comparison' => true,
- 'strict_param' => true,
- 'void_return' => true,

This rules in VS Code doesn`t works. No rules apply. If I try to use one of these rules, the CS doesn't works, rest of rules applies perfectly

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

Can you share a minimal example of the code that is not fixed to your expectation? Thanks!

**Comment by pablolopezmestre** [comment]
I'm sorry, I didn't explain myself well

The problem is not that it doesn't apply some rules but that everything stops working. Nothing works, in the moment I activate any of the rules I indicate, everything fails, nothing works

**Comment by SpacePossum** [comment]
I think this is an issue with the integration by Visual Studio Code and I don't see what we could do here to help out with that. If anyone has more details than I'm happy to reopen, but for now I'm closing as there is not enough to go with.
