### ISSUE TITLE
Multiline if (while, ...) condition with closing bracket on a new line

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5159]
## Feature request

`if` and other multiline conditions like:
```
if ($objRefl
    ->getMethod(!$objRefl->hasMethod($name) && $objRefl->hasMethod('__call') ? '__call' : $name)
    ->returnsReference()) {
    return $obj->{$name}(...$args);
}
```
are much more readable with closing bracket on the new line:
```
if ($objRefl
    ->getMethod(!$objRefl->hasMethod($name) && $objRefl->hasMethod('__call') ? '__call' : $name)
    ->returnsReference()
) {
    return $obj->{$name}(...$args);
}
```

This is a feature request. If some fixer for this already exists, please advise.

**Comment by julienfalque** [comment]
[PSR-12 has (kind of) the same rule](https://www.php-fig.org/psr/psr-12/#51-if-elseif-else):

> Expressions in parentheses MAY be split across multiple lines, where each subsequent line is indented at least once. When doing so, the first condition MUST be on the next line. The closing parenthesis and opening brace MUST be placed together on their own line with one space between them. Boolean operators between conditions MUST always be at the beginning or at the end of the line, not a mix of both.

This is already tracked in #4502. Personally I'm :-1: for implementing this rule with an option allowing the beginning of the expression to remain on the line of the opening parenthesis.

**Comment by mvorisek** [comment]
> Personally I'm 👎 for implementing this rule with an option allowing the beginning of the expression to remain on the line of the opening parenthesis.

thanks for reply, closing in favor of #4502, I am ok with it, my primary concern is to enforce the closing bracket to be on a new line
