### ISSUE TITLE
Use GH actions to test on PHP 8.0

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#5179]
Because travis refuses point blank to provide a sensible versioning system, so now their nightly means php 8.1... and there is no 8.0 option.

**Comment by SpacePossum** [comment]
Good idea!
Hope someone knows how to do it. Maybe it is possible to move all Travis testing parts to GH actions so we don't have to maintain two test setups for linux based setups

**Comment by julienfalque** [comment]
I'm willing to give it a try when I find some time :)

**Comment by sanmai** [comment]
There is an option. There's `8.0snapshot` now.
