### ISSUE TITLE
Rename repo name to "php-cs-fixer" to match composer package name

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5182]
This is a feature request to rename this repo

from `PHP-CS-Fixer`
to `php-cs-fixer`

to match composer package name and allow easier clone etc. Be simply consistent.

**Comment by julienfalque** [comment]
:+1: for me but this might have unexpected consequences I'm not aware of.

**Comment by SpacePossum** [comment]
:-1:  I don't see much value in it TBH

**Comment by GrahamCampbell** [comment]
👎 from me. No point, especially since the org name is as it is.

**Comment by SpacePossum** [comment]
closing for now, feel free to keep discussing and voting, we can always reconsider open this request.
