### ISSUE TITLE
Files not fixed if --rules option has an excluded rule

### ISSUE THREAD

**Issue by thsmrtone1** [FriendsOfPHP/PHP-CS-Fixer#5198]
## Bug report

php-cs-fixer will not fix a file if the `--rules` option has an excluded rule (i.e. `-header_comment`).

--------

   * PHP version: PHP 7.4.6 (cli) (built: May 14 2020 10:38:36) ( NTS )
   * PHP CS Fixer version: PHP CS Fixer 2.16.4 Yellow Bird by Fabien Potencier and Dariusz Ruminski (1023c34)
   * the command used to run PHP CS Fixer:
      ```bash
      php php-cs-fixer-v2.phar fix foo.php --rules=-header_comment
      ```
   * the configuration (file) you used: NONE (I've tested with and without a config file -- same results).

### Code snippet that reproduces the problem

**Before execution**

```php
<?php

class Foo {}
```

**After execution**

Actual: *No change*

Expected:

```php
<?php

class Foo
{
}
```

**Comment by kubawerlos** [comment]
The

> Actual: No change

is what is expected.

In README you can see:

> The `--rules` option lets you choose the exact rules to apply

and you have chosen to use no rules and exclude `header_comment`.


You were expecting that the rules from `.php_cs` file would be used and `header_comment` would be excluded from the set, right?

Unfortunately, the rules [parsing](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.4/src/Console/ConfigurationResolver.php#L677) works differently: if the option `--rules` is used then the rules from config file are ignored.

**Comment by thsmrtone1** [comment]
@kubawerlos 

> and you have chosen to use no rules and exclude header_comment.

The examples in the README are unclear about what will happen:

> By default the PSR1 and PSR2 rules are used.

> You can also exclude the rules you don't want by placing a dash in front of the rule name, if this is more convenient, using `-name_of_fixer`:
`$ php php-cs-fixer.phar fix /path/to/dir --rules=-full_opening_tag,-indentation_type`

To me, it doesn't make sense that the example would "exclude something from nothing" unless there was something by default.

> Unfortunately, the rules parsing works differently: if the option --rules is used then the rules from config file are ignored.

This is good to know. I was expecting .php_cs to be used if one was available, and if not, by default use PSR1 and PSR2 and subtract the excluded rules provided.
