### ISSUE TITLE
Crashes in Composer 2.0.2

### ISSUE THREAD

**Issue by Jamesking56** [FriendsOfPHP/PHP-CS-Fixer#5202]
## Bug report

When running:

```
vendor/bin/php-cs-fixer fix --dry-run --ansi --format=checkstyle
```

In Composer 2.0.2, `php-cs-fixer` crashes with an error:

```
In ToolInfo.php line 50:
                         
  Undefined index: name  
                         
```

PHP version: 7.4.11
PHP CS Fixer version: 2.16.1 Yellow Bird - but I think this is the same in later versions

### Code snippet that reproduces the problem

N/A, its not related to any code being fixed.

**Comment by lt** [comment]
It looks like the structure of `installed.json` changed (packages are now nested one level deeper)

**Comment by matks** [comment]
Seems fixed in Composer 2.16.4 https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4905

**Comment by SpacePossum** [comment]
thanks for reporting :+1: 

closing based on the comment of @matks  : )

**Comment by Jamesking56** [comment]
Thanks, I'm not going above `2.16.1` due to needing a fix for header comments which is in a PR waiting review #4936
