### ISSUE TITLE
New 2.16.x release?

### ISSUE THREAD

**Issue by WyriHaximus** [FriendsOfPHP/PHP-CS-Fixer#5205]
Working on a [PR to dependabot to add support for composer v2](https://github.com/dependabot/dependabot-core/pull/2682), and one of the things that is blocking that is a new `v2.16.x` release on this package. Reason for that is the use of `composer/semver` `v3` where the latest `v2.16.x` release on this package only supports `v1.4`. Already found out that the dev branch for `v2.16.x` on this package has support for `composer/semver`. A new release would be greatly appreciated.

**Comment by SpacePossum** [comment]
Please have a look @ https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5130#issuecomment-708976913
Next Monday is another alignment between members and maintainer and if there is any new I'm happy to share :)

**Comment by WyriHaximus** [comment]
Done, and looking forward to that. Also, make sure you and the rest of the team take care of your lives before OSS projects :).

**Comment by SpacePossum** [comment]
releases have been done :)

**Comment by lptn** [comment]
Thanks! There is one more dependency to update:
` - php-cs-fixer/diff (v1.3.1) latest is v2.0.2`
```sh
composer why php-cs-fixer/diff

>friendsofphp/php-cs-fixer  v2.16.7  requires  php-cs-fixer/diff (^1.3)
```

**Comment by keradus** [comment]
@lptn , does it block you with anything?
PHP CS Fixer uses diff 1.3 (v1.3.1 is ready for PHP 8) or 2.0 (v2.0.2 is ready for PHP 8)
update to v2 is bringing different behaviour thus behaviour of PHP CS Fixer itself would be different, causing a BC break, which we applied on v3@dev

**Comment by lptn** [comment]
@keradus 
>does it block you with anything?

No, sorry if I confused you. Thanks for the information 👍
