### ISSUE TITLE
no_unneeded_final_method should no complain about __construct

### ISSUE THREAD

**Issue by vudaltsov** [FriendsOfPHP/PHP-CS-Fixer#5212]
It's allowed to override parent private constructor unless it's final. So it makes sense to have `final private function __construct`

https://3v4l.org/oAaIC

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

I've proposed this https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5220 as fix
