### ISSUE TITLE
bug with cs fixer on CI

### ISSUE THREAD

**Issue by TheoDeberles** [FriendsOfPHP/PHP-CS-Fixer#5238]
Hello, my problem is that when I use "cs-fixer" on my local I have no error but yet in the CI I have an error of this type: 
```
In ToolInfo.php :
 Undefined index: name
```
I don't know where this problem comes from.
Thank you.

**Comment by julienfalque** [comment]
This looks like the Composer 2 compatibility issue that was fixed in #4905. Which version of PHP CS Fixer are you using?

**Comment by TheoDeberles** [comment]
I have the 2.16 version

**Comment by keradus** [comment]
@TheoDeberles , there are 8 versions of 2.16.X.
which one you are using? can yu use the newest, 2.16.7 and try again?

**Comment by TheoDeberles** [comment]
we have using the latest but the problem is same.

**Comment by keradus** [comment]
@TheoDeberles , I would love to dig into the problem, but I need to ask for more details:
- can you name the version of PHP CS Fixer in use? the "latest" is not enough, we have different lines maintained
- can you name version of Composer?
- can you attach `composer/installed.json` file ?

**Comment by svacher** [comment]
Hi all,

I have the same problem using v. 2.15.3. I use it since several months without problem.
Then i update Composer (from v1.10.17 to 2.0.4 and 2.06 too) and the problem appears.

So i rollback composer to version 1.10.17 and no problem. This is my only lead for now... If it can help someone.

A will add composer.lock for composer v1 versus composer.lock for composer v2.

**Comment by svacher** [comment]
The main difference is that composer v1 uses symfony/* v5.1.8 while composer v2 uses symfony/* v4.4.16...

**Comment by vpArth** [comment]
Looks like issue is closed by 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/524b57de7be82121fb51c49abf8a1648cafe258c/src/ToolInfo.php#L49

What php-cs-fixer's versions are contain that fix?

**Comment by keradus** [comment]
2.15.6 - https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4905

thanks for veryfiyng @vpArth , closing the issue then

**Comment by mats852** [comment]
Hello, I'm currently using PHP 7.0 and the hard limit for PHP-CS-Fixer is v2.13.

Would it be possible to implement this patch for that minor version?

https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/3.0...mats852:v2.13.4

Thanks in advance

**Comment by julienfalque** [comment]
Version 2.13 is not maintained anymore. I suggest you upgrade PHP (version 7 is not supported since more than two years ago). If you can't, you might still fork the project and apply this patch.

**Comment by mats852** [comment]
> Version 2.13 is not maintained anymore. I suggest you upgrade PHP (version 7 is not supported since more than two years ago). If you can't, you might still fork the project and apply this patch.

Yes, I'll resort to use my fork for now. Thanks!
