### ISSUE TITLE
Is there option to ignore files in the root? ( _ide_helper.php and _ide_helper_models.php)

### ISSUE THREAD

**Issue by fico7489** [FriendsOfPHP/PHP-CS-Fixer#5243]
_ide_helper.php and _ide_helper_models.php from https://github.com/barryvdh/laravel-ide-helper

**Comment by SpacePossum** [comment]
Hi!
You can configure a SF Finder in your configuration file to fix only the files you want.
For example this projects configuration file show excluding files on directory bases;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.7/.php_cs.dist

More details about the configuration file can be found in the docs;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/config.rst

**Comment by fico7489** [comment]
I know how to exclude a directory, but there is no option to exclude a file...

**Comment by SpacePossum** [comment]
please look into the docs of SF finder itself; https://symfony.com/doc/current/components/finder.html

>$finder->files()->notName('*.rb');
>$finder->files()->notName(['*.rb', '*.py']);

etc.
