### ISSUE TITLE
\␠function_name() is no longer recognised by PHP 8, but is not fixed with @PHP80Migration

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/PHP-CS-Fixer#5259]
## Rule request

php =<7.4 used to parse `\ str_replace()`, with a space between the backslash and the function name. In PHP 8.0/8.1 this triggers `PHP Parse error:  syntax error, unexpected token "\"`.

A fixer that removes this space would be nice.

### Code snippet that shows how the rule would fix PHP code

https://github.com/afterlogic/aurora-framework/pull/6/commits/fda56112037791ae42f7b56ead510f93776bf4a7

```diff
- $sTemplateSource =\ str_replace('{%INCLUDE-START/'.$aItem[0].'/INCLUDE-END%}',
+ $sTemplateSource = \str_replace('{%INCLUDE-START/'.$aItem[0].'/INCLUDE-END%}',
```

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5264
