### ISSUE TITLE
braces - NL is removed before method opening brace

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5260]
## Bug report

There is an issue in `braces` fixer, see test code below - the latest fixer version is removing NL before method opening `{` brace.

```diff
-    ): self
-    {
+    ): self {
```

Version: the latest stable / PHP CS Fixer 2.16.7 (UPDATE: 2.18.4 still present)

### Test Code

```
<?php

declare(strict_types=1);

namespace Xxx;

use Doctrine\DBAL\Types\ConversionException as BaseConversionException;
use Doctrine\DBAL\Types\Type;

class ConversionException extends BaseConversionException
{
    public static function fixedCorrectly($value): string
    {
    }

    public static function fixedIncorrectly(
        $value,
        Type $type,
        string $error,
        bool $fromDatabase,
        int $code = 0,
        \Throwable $previous = null
    ): self {
        return new self();
    }
}
```

### Config
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__])
    ->exclude([
        'vendor',
    ]);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PhpCsFixer' => true,
        '@PhpCsFixer:risky' =>true,
        '@PHP71Migration:risky' => true,
        '@PHP73Migration' => true,

        // required by PSR-12
        'concat_space' => [
            'spacing' => 'one',
        ],

        // disable some too strict rules
        'phpdoc_types_order' => [
            'null_adjustment' => 'always_last',
            'sort_algorithm' => 'none',
        ],
        'single_line_throw' => false,
        'yoda_style' => [
            'equal' => false,
            'identical' => false,
        ],
        'native_function_invocation' => false,
        'non_printable_character' => [
            'use_escape_sequences_in_strings' => true,
        ],
        'void_return' => false,
        'blank_line_before_statement' => [
            'statements' => ['break', 'continue', 'declare', 'return', 'throw', 'exit'],
        ],
        'combine_consecutive_issets' => false,
        'combine_consecutive_unsets' => false,
        'multiline_whitespace_before_semicolons' => false,
        'no_superfluous_elseif' => false,
        'ordered_class_elements' => false,
        'php_unit_internal_class' => false,
        'php_unit_test_case_static_method_calls' => [
            'call_type' => 'this',
        ],
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_add_missing_param_annotation' => false,
        'return_assignment' => false,
        'comment_to_phpdoc' => false,
        'list_syntax' => ['syntax' => 'short'],
        'general_phpdoc_annotation_remove' => [
            'annotations' => ['author', 'copyright', 'throws'],
        ],
        'nullable_type_declaration_for_default_null_value' => [
            'use_nullable_type_declaration' => false,
        ],
    ])
    ->setFinder($finder);
```

**Comment by mvorisek** [comment]
@keradus @kubawerlos can you guy please look at this issue? Also, it seems it is present only after 2nd run /w cache clean.

**Comment by kubawerlos** [comment]
@mvorisek can you dobule check the config? I cannot reproduce it.

Or the "test code" is code what you are expecting, not the version to fix?

**Comment by mvorisek** [comment]
> Or the "test code" is code what you are expecting, not the version to fix?

Of course, checkout https://github.com/mvorisek/WarnockPDF/tree/code_wo_huge_fonts and run cs fixer with this config:
```
    ->setRules([
        '@PSR2' => true,
        'concat_space' => [
            'spacing' => 'one',
        ],
        'binary_operator_spaces' => true,
        'whitespace_after_comma_in_array' => true,
    ])
```
Notice the newly removed NL before the curly brace of `setUserRights` method body.

**Comment by kubawerlos** [comment]
Ok, now I get the `braces` removing NL, but the same happens on `v2.12.9` with config from above - should I add some extra rule to have it not remove NL in old version and broken in latest ones?

**Comment by mvorisek** [comment]
I would consider this as a standard bug fix, ie. land the fix into `2.18` branch.

**Comment by kubawerlos** [comment]
Okay, but I cannot nail what is wrong - `braces` removes that BL since `v2.12.9`, what config makes (should make) that line to stay?

**Comment by mvorisek** [comment]
I belive `position_after_functions_and_oop_constructs` set to `next` (by default) of the `braces` rule.

Why?

```
class Foo
{
    public function bar($baz) {
```

is fixed (correctly) to:
```
class Foo
{
    public function bar($baz)
{
```

but when the method declaration is multiline:
```
class Foo
{
    public function bar(
        $baz
    ) {
```

the NL must be inserted in a simillar fashion:

```
class Foo
{
    public function bar(
        $baz
    )
    {
```

**Comment by keradus** [comment]
> the NL must be inserted in a simillar fashion:

PSR-12 disagree with this claim

https://www.php-fig.org/psr/psr-12/#45-method-and-function-arguments
> When the argument list is split across multiple lines, **the closing parenthesis and opening brace MUST be placed together on their own line** with one space between them.
> (...)
> When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. **The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.**
> ```php
>     public function anotherFunction(
>         string $foo,
>         string $bar,
>         int $baz
>     ): string {
>         return 'foo';
>     }
> ```

**Comment by mvorisek** [comment]
Inconsistent, but PSR is written that way. I belive, no IDE can be even configred to that...
