### ISSUE TITLE
Docs UX

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5270]
This is a feature request.

## single page for all rules/rulesets
I personally find the original single page docs much more usefull, as it was possible to find almost all information at one page using"`ctrl + f`".

I propose to change https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/index.rst to single page or at least provide it in some other single page location.

## add link to src
I propose - feature I miss - add link to src from rule/ruselet page.

## deduplicate config details

Example: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.7/doc/rules/alias/random_api_migration.rst#rule-sets - `@PHP71Migration:risky` should not diplay the same config again.

I propose to list all rulesets with inherited unchanged configuration and then show the configuration once - in image:
![image](https://user-images.githubusercontent.com/2228672/99184287-03340e00-2742-11eb-8790-40659d0658ad.png)

**Comment by keradus** [comment]
Hey,

please consider atomic threads for different suggestions next time, that can help to keep discussion focused ;)

-------------

> single page for all rules/rulesets

what is missing for you on this page?

> add link to src

sounds nice. please raise a PR

> deduplicate config details

in this case, it was indeed same configs. but it does not need to be same config each time, eg https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/whitespace/no_extra_blank_lines.rst#rule-sets .
I find it a bit nitpicking, but if you wish to work on it, please raise a PR
