### ISSUE TITLE
yoda_style "false" not working, while "true" is.

### ISSUE THREAD

**Issue by Luc45** [FriendsOfPHP/PHP-CS-Fixer#5281]
## Bug report

`yoda_style` sniff only works if set to `true`, eg:

```php
$a = 'foo';

// After fix
'foo' = $a;
```

I would expect that, setting `yoda_style` to false, the opposite would happen:

```php
'foo' = $a;

// After fix
$a = 'foo';
```

But it isn't. **It converts** my code to Yoda Style with `true`, but **don't convert back** with `false`.

### Environment

```
www-data@c1163c254900:~/tests$ php -v
PHP 7.3.13 (cli) (built: Dec 28 2019 21:22:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans

www-data@c1163c254900:~/tests$ ./vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.16.7 Yellow Bird by Fabien Potencier and Dariusz Ruminski

php -d memory_limit=3G /var/www/tests/vendor/bin/php-cs-fixer fix -vvv --rules='{"yoda_style": false}'
```

### Config file:

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in('/var/www/single_tests/wp-content/plugins/foo-dev')
    ->exclude('vendor')
;

return PhpCsFixer\Config::create()
    ->setRules([
        'yoda_style' => false,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder($finder)
;
```

**Comment by kubawerlos** [comment]
> I would expect that, setting `yoda_style` to false, the opposite would happen

That's not how the rules work - every fixer is ~not workig~ disabled when set to `false`.

This cames useful e.g. when you want to use Symfony rules, but disable `blank_line_after_opening_tag` rule:
```php
    '@Symfony' => true,
    'blank_line_after_opening_tag' => true,
```

To achieve the non-Yoda style conditions you need config the fixer like this:
```php
    'yoda_style' => [
        'equal' => false,
        'identical' => false,
        'less_and_greater' => false,
    ],
```

**Comment by Luc45** [comment]
Thanks for the clarification, @kubawerlos.

I have opened a PR proposing minor changes to the `yoda_style` sniff documentation: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5286
