### ISSUE TITLE
Next 2.16 release?

### ISSUE THREAD

**Issue by jesseleite** [FriendsOfPHP/PHP-CS-Fixer#5282]
## Support question

We're using php-cs-fixer within [statamic/migrator](https://github.com/statamic/migrator) and have had some issues since 2.16.4 which seem to have been fixed on your master branch.  I'm not sure of how your release process works, but we're curious if there's a timeline for tagging 2.16.8?

PS. Really appreciate all your work on php-cs-fixer! 🤘

**Comment by GrahamCampbell** [comment]
You can just use the dev version in the meanwhile. For example, `^2.16.8` will work if you allow min stability dev, prefer stable.

**Comment by keradus** [comment]
We released 2.15 on Friday and gonna release 2.16 after solving some obstacles (eg one of jobs is currently failing on master).
Thanks for understanding and a good word ;)


I'm closing this thread as it requires no further action of changing codebase. Feel free to continue the discussion (I'm only "closing", not "locking")

**Comment by jesseleite** [comment]
Thank you for tagging 2.17.0! All fixed up here!
