### ISSUE TITLE
Urgent Need To Migrate Off Travis

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#5285]
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/2829600/99884018-e5274b80-2c22-11eb-8a47-0272902894f5.png">

**Comment by keradus** [comment]
Folks, please talk one to another
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5268#issuecomment-731827563
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5183#issuecomment-731828143

On the side, i requested extra credits from Travis CI, it can help at least on the short run

**Comment by GrahamCampbell** [comment]
My PR seems best IMO. The tests pass, without any hacks.

**Comment by sanmai** [comment]
Neither my variant uses hacks. And it's quite shorter and more concise, and thus easier to maintain in the long run. And it doesn't remove any tests. I do believe this approach works better for the good of the community, but if there's a disagreement I'd rather sacrifice my PR for the consensus.

**Comment by GrahamCampbell** [comment]
One of the main problems I have with the other PR is the name of the jobs:

![image](https://user-images.githubusercontent.com/2829600/100083428-61977580-2e41-11eb-8c4b-e2b978dc9f64.png)

vs

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2829600/100083528-825fcb00-2e41-11eb-948f-855438e677c8.png">

NB Failing tests are because the tests are actually failing now, due to no CI on 2.16...

**Comment by GrahamCampbell** [comment]
It looks like PHP 7.0 is not tested on the other PR too?

**Comment by sanmai** [comment]
My bad. Fixed this in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5268/commits/41d6961ac6277cc642673485c3eacc61d416ab96
