### ISSUE TITLE
2.15 branch was removed

### ISSUE THREAD

**Issue by szepeviktor** [FriendsOfPHP/PHP-CS-Fixer#5289]
## Problem report

Hello! My dirty hack relied on the 2.15 branch
https://github.com/szepeviktor/debian-server-tools/blob/470439601838653c2e3f8e313b6bf34583d35b10/webserver/laravel/.php_cs#L45-L50

@keradus Could it be reverted?
The _Europe Round_ release was just 3 days ago...

**Comment by keradus** [comment]
Hey @szepeviktor ,
the 2.15 branch is no longer supported, please update

I strongly discourage from using links soft objects. If you want to ensure the reference will exist over time, use SHA or at least a tag. It's natural that the branches will cease to exist

**Comment by szepeviktor** [comment]
Thank you.

Done.
https://github.com/szepeviktor/debian-server-tools/commit/610fa7998d4d03168b91eee32cf3db21452c3b13#diff-012db5d47c23e9ef56b8e2bf29897c40039894ee5ca8060a201ca8c619c68d26
