### ISSUE TITLE
OrderedClassElementsFixer - Support for PHPUnit Bridge (Symfony)

### ISSUE THREAD

**Issue by ktomk** [FriendsOfPHP/PHP-CS-Fixer#5310]
The [`OrderedClassElementsFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/ClassNotation/OrderedClassElementsFixer.php) allows class (method) ordering for four
specific `phpunit` methods:

* `setUp()`
* `tearDown()`
* `setUpBeforeClass()`
* `tearDownBeforeClass()`

This is very convenient as the methods are placed towards the beginning of the class where they are visible when opening a test-case.

The [PHPUnit Bridge component](https://symfony.com/components/PHPUnit%20Bridge) ([docs](https://symfony.com/doc/current/components/phpunit_bridge.html), [github](https://github.com/symfony/phpunit-bridge)) acts as a proxy between Phpunit and a projects test-suite.

A feature of _PHPUnit Bridge_ is to maintain the same test-suite for different PHPUnit versions. For example write tests for Phpunit 8 or 9 and execute them with Phpunit 6 to run the tests against an older PHP version(s). Phpunit 8 would be incomaptible for example with PHP 5.6 but the test-suite itself must not. This is specifically useful when rolling Phpunit versions in addition to existing Phpunit related PHP-CS-Fixer - fixers that exists to port a test-suite.

It was specifically w/ Phpunit 8 that some backwards incompatible changes on the PHP syntax level were introduced on the above listed OrderedClassElementsFixer `phpunit` methods. To retain compatibility in the test-suite, _PHPUnit Bridge_ offers four in-place/stand-in methods for compatibility:

* `doSetUp()`
* `doTearDown()`
* `doSetUpBeforeClass()`
* `doTearDownBeforeClass()`

As currently the OrderedClassElementsFixer is not aware of these stand-in method names, they are not placed towards the top of the class where their counterparts belong.

I'm adding a PR with an implementation suggestion.

**Comment by SpacePossum** [comment]
closing through https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5311
