### ISSUE TITLE
PHP8 support?

### ISSUE THREAD

**Issue by cviebrock** [FriendsOfPHP/PHP-CS-Fixer#5313]
I noticed a lot of PRs to add support for PHP8 ... however, the `composer.json` file for the package still has the following:

```json
    "require": {
        "php": "^5.6 || ^7.0",
```

So you can't actually _use_ php-cs-fixer under PHP8.

Shouldn't `|| ^8.0` be added to that list?

**Comment by kubawerlos** [comment]
PHP 8 support will be allowed to `composer.json` when it could be safely claimed that PHP CS Fixer fully supports PHP 8.

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5134#issuecomment-684780460 for more details.
