### ISSUE TITLE
NoBreakCommentFixer throw detect broken if statement before throw

### ISSUE THREAD

**Issue by W0rma** [FriendsOfPHP/PHP-CS-Fixer#5322]
## Bug report

Follow-up of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5247

Seems like NoBreakCommentFixer does not detect throw properly if an `if` statement is placed before.

### Code snippet that reproduces the problem

 * `PHP 7.4.12 (cli) (built: Nov 18 2020 09:34:43) ( NTS )`
 * `PHP CS Fixer 2.16.8 Yellow Bird by Fabien Potencier and Dariusz Ruminski`

```php
<?php

// Simplified example

switch ('bla') {
    case X:
        if (true === false) {
            return 'foo';
        }
        throw new \Exception('some msg');
    case Z:
        break;
}
```

```
$ docker-compose run --rm robot-int vendor/bin/php-cs-fixer fix -vvv dieter/test-cs-fixer.php
Runtime: PHP 7.4.12
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) dieter/test-cs-fixer.php (no_break_comment)

Fixed all files in 0.010 seconds, 16.000 MB memory used
```

**Comment by SpacePossum** [comment]
thanks for reporting!

 proposed fix https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5325
