### ISSUE TITLE
Include/require format changed with @PhpCsFixer in v2.17.1?

### ISSUE THREAD

**Issue by ThibautSF** [FriendsOfPHP/PHP-CS-Fixer#5349]
## Support question (& possible bug)

Prior with version 2.17.0 & @PhpCsFixer ruleset, code like the following one remains unformated
```php
require_once '1.php';
require_once '2.php';
```

But since 2.17.1, the exact same code becomes: (line break are added)
```php
require_once '1.php';

require_once '2.php';

```

I can't find any changelog about this modification.

**Comment by keradus** [comment]
could be related to #4831 , @SpacePossum ?
(btw, i see 2.16 not adding the line, but 2.17.0 already adding it (not only 2.17.1)

**Comment by SpacePossum** [comment]
AFAIK this wasn't changed on 2.17.1. This change is done by `blank_line_before_statement`, which you probably run because of the `PHP-CS-Fixer` set, which has been updated in 2.16
