### ISSUE TITLE
ordered_traits fixer should be considered risky

### ISSUE THREAD

**Issue by derrabus** [FriendsOfPHP/PHP-CS-Fixer#5350]
## Bug report

First of all, thank you for all the new fixers that the new 2.17 release shipped with!

I really like the `ordered_traits` fixer and already use it in my projects. However, I'd like to propose to reconsider its classification as a non-risky fixer.

Applying this fixer might change the behavior of the code because it reorders elements provided by those traits. This can especially be seen when serializing such objects. Code that relies on a specific order of properties/methods might break after applying this fixer.

### Code snippet that reproduces the problem

```php
trait A {
    public string $a = 'one';
}

trait B {
    public string $b = 'two';
}

class AB {
    use A;
    use B;
}

class BA {
    use B;
    use A;
}

var_dump(json_encode(new AB));
var_dump(json_encode(new BA));
```

https://3v4l.org/YDb3Q

**Comment by SpacePossum** [comment]
thanks for reporting, please review the linked PR :+1:

**Comment by derrabus** [comment]
Thank you!
