### ISSUE TITLE
phpdoc_no_alias_tag detects bad aliases inside other annotations

### ISSUE THREAD

**Issue by meyerbaptiste** [FriendsOfPHP/PHP-CS-Fixer#5357]
## Bug report

Since PSR-5 `@inheritDoc` support (https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/715ec07b35819547162efddc9736fdf3348aa7aa), `phpdoc_no_alias_tag` detects bad aliases inside other annotations.

### Code snippet that reproduces the problem

Example: https://github.com/api-platform/core/runs/1546298048

```diff
--- Original
+++ New
@@ -42,7 +42,7 @@
      *     attributes={
      *         "jsonld_context"={
      *             "@id"="http://example.com/id",
-     *             "@type"="@id",
+     *             "@var"="@id",
      *             "foo"="bar"
      *         }
      *     },
```

**Comment by Leprechaunz** [comment]
@keradus I think this issue is fixed by PR #5604 and can be closed
