### ISSUE TITLE
Can't run PHP CS Fixer with PHP 8.0 on a PHP 7.4 codebase

### ISSUE THREAD

**Issue by amcsi** [FriendsOfPHP/PHP-CS-Fixer#5375]
## Bug report
Note: this is about just being able to run this tool on a PHP 7.4 codebase; not about fixing PHP 8 code. I know the issue for PHP 8 codebase support is here: #4702.

php-cs-fixer version 2.17.1

  ```php
  <?php
php vendor/bin/php-cs-fixer
# PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.4.*.
  ```

The output comes from here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/php-cs-fixer#L27

If PHP 8 isn't supported for even running php-cs-fixer, then I think it shouldn't list PHP 8 as a supported PHP version in composer.json: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/composer.json#L17

**Comment by keradus** [comment]
We made this decision due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5326#issue-533920155 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5341#issuecomment-742527434
