### ISSUE TITLE
PSRAutoloading Fixer is removing directory structure from the Class name

### ISSUE THREAD

**Issue by jaydiablo** [FriendsOfPHP/PHP-CS-Fixer#5377]
## Bug report

Version `2.17.2` just released and I wanted to test it against a repo as I saw the same issue reported in #5342 and was curious if this new release would fix that.

However, after running this new release against this repo, PHP-CS-Fixer stripped all of the PSR0 prefixes off of every class that it touched.

I believe this is due to the changes in #5348. Version `2.17.1` ran on the same repo does not do this.

For example, here's the autoload in composer:

```json
"autoload": {
        "psr-0": {
            "Doctrine_": "lib/"
        },
        "classmap": [
            "lib/Doctrine.php"
        ]
    },
```

Then in this file: `lib/Doctrine/AuditLog/Listener/Microtime.php` it's doing this:

![Screen Shot 2020-12-17 at 9 58 48 AM](https://user-images.githubusercontent.com/136907/102518807-f9f2d580-404e-11eb-8985-b51d19480b02.png)

This happens to every file in the repo, which obviously breaks everything since the classnames no longer match what's being used elsewhere.

**Comment by GrahamCampbell** [comment]
This is not a bug. Your code is not PSR-0 compliment. You should disable the fixer.

**Comment by SpacePossum** [comment]
Hi @jaydiablo and thanks for your report.

ping @kubawerlos 
should the `dir` be configured here to support fixing to the underscore format? curious if this is regression or expected
I think should still follow 
`Each _ character in the CLASS NAME is converted to a DIRECTORY_SEPARATOR. The _ character has no special meaning in the namespace.`

**Comment by kubawerlos** [comment]
I'm working (slowly, to remind myself PSR-0 and PSR-4 rules with all the details).
My plan has 3 steps:
 - add better tests cases (with the one from this bug and other coming from PSR0/4 official definitions) and fix the bug with one another `if` (as the fixer right now is mostly `if`s
 - migrate old test cases to the new one as the old ones have a weird mocking mechanism
 - refactor fixer itself as currently, it's really messy
