### ISSUE TITLE
"ordered_traits" does mismatch comments

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5381]
## Bug report

CS Fixer version: 2.17.2

### Code snippet that reproduces the problem

```
class TrackableMockSat
{
    use TrackableTrait;
    use DiContainerTrait; // remove once PHP7.2 support is dropped
    use StaticAddToTrait;
}
```

is fixed into:
```
class TrackableMockSat
{
    use DiContainerTrait;
    use StaticAddToTrait; // remove once PHP7.2 support is dropped
    use TrackableTrait;
}
```

which is wrong as comment on the right side is definitely for `DiContainerTrait` and it is not moved

**Comment by SpacePossum** [comment]
This cannot be helped, because always moving the comment might also not be correct. Since there is no way to determine the relation between the comment and trait we cannot do better here.

**Comment by keradus** [comment]
@SpacePossum , can you give example when moving of comment would not be correct?

**Comment by SpacePossum** [comment]
```php
class TrackableMockSat
{
                          // we import these because
    use TrackableTrait;   // these 3 traits are always needed when:
    use DiContainerTrait; // the class is in this namespace and since comments are not bound to code like PHPDocs it
    use StaticAddToTrait; // makes reliable moving not possible also
                          // makes the code more complex just to deal with some rare edge cases where people should fix their comments manually once
}
```

**Comment by julienfalque** [comment]
I would say that the comments are more likely to be encountered in situations like @mvorisek reported than this example. There is no way to handle all cases but I think the fixer can be improved indeed. I don't think this should be a top priority for the maintainers though.

**Comment by SpacePossum** [comment]
Closing as there is no way to know for sure how the comments should be handled.
