### ISSUE TITLE
list_syntax => short should be included in 7.1 migration

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#5389]
## Feature request

https://mlocati.github.io/php-cs-fixer-configurator/#version:2.17|fixer:list_syntax:
> List (array destructuring) assignment should be declared using the configured syntax. Requires PHP >= 7.1.

Usage:

```php
$rules['list_syntax'] = ['syntax' => 'short'];
```

**Comment by keradus** [comment]
Done: #5428
