### ISSUE TITLE
PHP 8 attributes and single_space_after_construct

### ISSUE THREAD

**Issue by hlecorche** [FriendsOfPHP/PHP-CS-Fixer#5403]
## Bug report

Hello, I know PHP-CS-Fixer is not fully compatible with PHP 8 but I found a strange behavior with PHP 8 attributes when `single_space_after_construct` is used (PHP8 attribute support is added in #5284)

 * PHP version: 8.0.0
 * PHP CS Fixer version: 2.17.3
 * Configuration : Only `single_space_after_construct` rule is enabled (with default configuration)

### Code snippet that reproduces the problem

Original file :

 ```php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Attribute\MyAttribute;
use App\Attribute\MyAttribute2;

#[MyAttribute()]
class Class2
{
    #[MyAttribute2]
    private $id;
}
  ```

PHP-CS-Fixer suggestion :

```diff
   1) src/Entity/Class2.php (single_space_after_construct)
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 
-#[MyAttribute()]
-class Class2
+#[MyAttribute()] class Class2
 {
-    #[MyAttribute2]
-    private $id;
+    #[MyAttribute2] private $id;
 }
 

      ----------- end diff -----------
```

**Comment by SpacePossum** [comment]
thanks for reporting!
