### ISSUE TITLE
position error in operator_linebreak

### ISSUE THREAD

**Issue by sy-records** [FriendsOfPHP/PHP-CS-Fixer#5409]
## Bug report

   * PHP version: 7.4.11 
   * PHP CS Fixer version: v2.17.3
   * the configuration (file) you used

```php
        '@PSR2' => true,
        '@Symfony' => true,
        '@DoctrineAnnotation' => true,
        '@PhpCsFixer' => true,
        'multiline_whitespace_before_semicolons' => [
            'strategy' => 'no_multi_line',
        ],
        'object_operator_without_whitespace' => true,
        'operator_linebreak' => [
            'position' => 'end',
        ],
```

### Code snippet that reproduces the problem

```php
function foo($bar, $baz)
{
    return $bar
        || $baz;
}

class ClassA
{
    public function foo()
    {
        return $this;
    }

    public function bar()
    {
        return $this;
    }

    public function do()
    {
        return $this;
    }
}
$class = new ClassA();
$res = $class->foo()
    ->bar()
    ->do();
```

I want to get

```php
function foo($bar, $baz)
{
    return $bar ||
        $baz;
}

class ClassA
{
    public function foo()
    {
        return $this;
    }

    public function bar()
    {
        return $this;
    }

    public function do()
    {
        return $this;
    }
}
$class = new ClassA();
// An error has been generated here. 
$res = $class->foo()->
    bar()->
    do();
```
![image](https://user-images.githubusercontent.com/33931153/104144587-b9446d00-53fe-11eb-9257-93a9b83cf0ac.png)

**Comment by sy-records** [comment]
@kubawerlos Hi, what do you think

**Comment by kubawerlos** [comment]
@sy-records why do you claim it's an error - the fixer is handling all operators as it's name is `operator_linebreak`, not `operator_except_object_operator_linebreak`.

**Comment by sy-records** [comment]
Thanks for the reply. what configuration should I add to the current version so that it doesn't handle `->`

**Comment by kubawerlos** [comment]
Something like this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.3/doc/rules/operator/binary_operator_spaces.rst#example-2

So your config would be:
```php
        'operator_linebreak' => [
            'position' => 'end',
            'operators' => ['->' => null],
        ],
```
Array 'operators' will accept the values `'beginning'`, `'end'` and `null` - this one will make the operator being ignored.
