### ISSUE TITLE
Not beautifying for .PHP files with HTML tags embedded in them?

### ISSUE THREAD

**Issue by derekdinan** [FriendsOfPHP/PHP-CS-Fixer#5413]
So I recently stumbled on this project and so far it's been ultimately useful. I use an Atom package called [Atom-Beautify](https://atom.io/packages/atom-beautify) which basically cleans my code whenever I save the file. 

Now, this has worked in the past for files that are only PHP files but if I want to beautify a .PHP file that has say HTML tags in it, the program simply won't beautify at all.

For example:

**Working:**
```php
<?php
    echo "This works.";
?>
```

**Not working:**
```php
<?php
    // ...
?>

<html>
<body>
    <script>...</script>
    <style>...</style>
    <p>This does not work.</p>
</body>
</html>
```

**Comment by keradus** [comment]
By design, we do not touch non-pure PHP files.
If you need to beautify PHP mixed with HTML,we recommend to take a look into any template system instead.
