### ISSUE TITLE
phpdoc_to_comment fixer is confused by attributes

### ISSUE THREAD

**Issue by derrabus** [FriendsOfPHP/PHP-CS-Fixer#5437]
## Bug report

If I attach a PHPDoc block and an attribute to my class, the `phpdoc_to_comment` fixer wants to fix the PHPDoc block to a regular comment. I think it should not do that.

I have verified this issue with the latest 2.17-dev version.

### Code snippet that reproduces the problem

```php
namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;

/**
 * This is an awesome controller!
 */
#[Route('/my/route')]
final class MyController
{
}
```

**Comment by julienfalque** [comment]
Which version of PHP are you using?

**Comment by derrabus** [comment]
> Which version of PHP are you using?

8.0.1

**Comment by hlecorche** [comment]
I have the same problem with php-cs-fixer 2.18.0 and PHP 8.0.1 (but the problem is'nt present with PHP 7.2 -> 7.4) :

This file is valid :

```php
<?php

namespace App\Attribute;

/**
 * @Annotation
 */
class MyAnnotation2
{
}
```

But this file is invalid :

```php
<?php

namespace App\Attribute;

use Attribute;

/**
 * @Annotation
 */
#[Attribute(Attribute::TARGET_CLASS)]
class MyAnnotation3
{
}
```

```diff
   1) src/Attribute/MyAnnotation3.php (phpdoc_to_comment)
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 
-/**
+/*
  * @Annotation
  */
 #[Attribute(Attribute::TARGET_CLASS)]
 class MyAnnotation3
 {
 }
```

**Comment by keradus** [comment]
@derrabus , would you like to give it a try with PR? ;)

**Comment by derrabus** [comment]
Maybe later this week, but I can't promise anything.
