### ISSUE TITLE
Extra space added after comments inlined in function calls

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#5448]
With the latest version of php-cs-fixer, when parsing e.g. `src/Symfony/Component/Console/Tests/DependencyInjection/AddConsoleCommandPassTest.php`:

![image](https://user-images.githubusercontent.com/243674/105025218-57fb4a00-5a4d-11eb-8706-13352d7f211e.png)

This suggested change is wrong of course.

**Comment by keradus** [comment]
Thanks for report. actually, still for 2.17 line
fix in #5453

**Comment by keradus** [comment]
released as 2.18.1, @nicolas-grekas
