### ISSUE TITLE
Many folders in /tmp

### ISSUE THREAD

**Issue by shyim** [FriendsOfPHP/PHP-CS-Fixer#5452]
## Bug report

* PHP version: 8.0.1
* PHP CS Fixer version: 2.18.0

The tool seems to create files under /tmp and does not cleanup.

```
/tmp via 🐘 v8.0.1
❯ du -sh /tmp/PHP\ CS\ Fixertemp_folder* | wc -l
339
```

I am using WSL2 and this doesn't clean up /tmp by him self.

**Comment by keradus** [comment]
thanks for the report, @shyim

Unfortunately, i was not able to reproduce it using Linux, and I do not use Windows.

Can you help with investigation?
- what is the name pattern within given folder ?
- This can be the starting point - creation of temp file: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.0/src/Linter/ProcessLinter.php#L159
- Also, pls verify why you are getting ProcessLinter and not TokenizerLinter: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.0/src/Linter/Linter.php#L35

**Comment by shyim** [comment]
Thanks for your fast answer.

It seems coming from PhpStorm. I have wiped my /tmp and run the fixer in PhpStorm and the files are there
![grafik](https://user-images.githubusercontent.com/6224096/105098280-1f3d8e00-5aaa-11eb-866a-8e05938de469.png)
![grafik](https://user-images.githubusercontent.com/6224096/105098592-9541f500-5aaa-11eb-8f08-856d8fe550ee.png)


Is this still an issue here or by PhpStorm 🤔

**Comment by keradus** [comment]
what you show here is `tmp` folder having only one, also empty `src` folder. originally, you shown
```
❯ du -sh /tmp/PHP\ CS\ Fixertemp_folder* | wc -l
339
```

does it mean that you have multiple empty PHP CS Fixer folders in `/tmp` ?

-----------------------

can you try to reproduce the issue by directly running PHP CS Fixer,  like `php8 php-cs-fixer fix -v`, while having PhpStorm completely closed?
If it would still create the folders, it's issue on our side and further investigation needed.

If the folders in `/tmp` are created and not cleared up only when used via PHP Storm, then I'm afraid this issue would need to be moved to PHP Storm folks for support.

**Comment by zambodaniel** [comment]
Hi! Same here, also with CodeSniffer, so definitely be a PhpStorm bug
 
![Screenshot from 2021-03-04 13-49-14](https://user-images.githubusercontent.com/3462880/109966478-993f7480-7cf0-11eb-9df2-b16e315eff8a.png)

**Comment by shyim** [comment]
I am closing this here than its an phpstorm only problem
