### ISSUE TITLE
PhpdocTagType - Issue with array shapes

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#5460]
## Bug report

`phpdoc_tag_type` rule removes the closing `}` in PHPDoc array shapes while it shouldn't.

### Code snippet that reproduces the problem

```diff
 <?php
-/** @var array{'foo': bool, 'bar': string} $foo */
+/** @var array{'foo': bool, 'bar': string $foo */
 $foo = [];
```

**Comment by kubawerlos** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5395?

**Comment by julienfalque** [comment]
Likely yes. Let's close for now. Thanks!
