### ISSUE TITLE
class_definition fails with initialising anonymous class

### ISSUE THREAD

**Issue by artursvonda** [FriendsOfPHP/PHP-CS-Fixer#5463]
## Bug report

Found an issue where php-cs-fixer keeps reporting issues with anonymous classes and not fixing them. Managed to reduce the bug to snippet below.

```
> format-php-cs-fixer: php-cs-fixer fix --allow-risky=yes '-vvv' 'src/fixer-test.php'
Executing command (CWD): php-cs-fixer fix --allow-risky=yes '-vvv' 'src/fixer-test.php'
PHP CS Fixer 2.18.1 Remote Void by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.12
Loaded config default from "/var/www/html/app/.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) src/fixer-test.php (class_definition)

Fixed all files in 0.046 seconds, 14.000 MB memory used
```
```
<?php

declare(strict_types=1);

$srcFiles = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->name('*.php')
    ->path(['src/'])
    ->ignoreVCSIgnored(true);

$finder = $srcFiles->append($rootFiles);

$config = new PhpCsFixer\Config();

return $config
    ->setRules([
        'class_definition' => true,
    ])
    ->setFinder($finder);

```

### Code snippet that reproduces the problem

```php
<?php
$var = new class () {
    // content
};
```

**Comment by kubawerlos** [comment]
I cannot reproduce it, your example always is fixed once (space after `class` is removed) and that's it. Can you provide some a failing test case?

**Comment by artursvonda** [comment]
Sorry, I think this was my fault. I thought I had isolated everything while testing but it seems CodeSniffer formatter was applied by IDE after CS Fixer run. Closing the ticket.

**Comment by juuuuuu** [comment]
> I cannot reproduce it, your example always is fixed once (space after `class` is removed) and that's it. Can you provide some a failing test case?

Should the space after `class` be removed?
Looking at the [PSR12 documentation](https://www.php-fig.org/psr/psr-12/#8-anonymous-classes), it's written: 

> [Anonymous Classes] MUST be declared with a space after the [class] keyword

**Comment by SpacePossum** [comment]
Hi @juuuuuu ,

Could you report this as a new FR for PSR12 suport? Currently PHP-CS-Fixer will indeed remove the space, thanks!

**Comment by juuuuuu** [comment]
Sorry for late response, I'll do it.

**Comment by C-Duv** [comment]
> Looking at the [PSR12 documentation](https://www.php-fig.org/psr/psr-12/#8-anonymous-classes), it's written:
> > [Anonymous Classes] MUST be declared with a space after the [class] keyword

I have a similar issue where PHP-CS-Fixer and PHPCS fight over the space between `class` and `($var)` in:

```PHP
$instance = new class ($var) extends \Foo {};
```

It looks like the quoted part of the documentation was removed and I cannot find a clear position.

There was some work in the https://github.com/php-fig/fig-standards/pull/1206 PR that seems to remove the space, but it was not merged.
