### ISSUE TITLE
XSym: command not found

### ISSUE THREAD

**Issue by AprilOneDay** [FriendsOfPHP/PHP-CS-Fixer#5472]
exec :  /d/docker/src/saas-oa/vendor/bin/php-cs-fixer
error:
/d/docker/src/saas-oa/vendor/bin/php-cs-fixer: line 1: XSym: command not found
/d/docker/src/saas-oa/vendor/bin/php-cs-fixer: line 2: 0041: command not found
/d/docker/src/saas-oa/vendor/bin/php-cs-fixer: line 3: 0ac23b4ded071ca0da73e51597affc19: command not found
/d/docker/src/saas-oa/vendor/bin/php-cs-fixer: line 4: ../friendsofphp/php-cs-fixer/php-cs-fixer: No such file or directory

**Comment by keradus** [comment]
not related to PHP CS Fixer itself but to your local development setup.
Please google the error, eg https://stackoverflow.com/questions/53396559/xsym-symbolic-links-cannot-be-used-in-php-on-docker-for-windows
