### ISSUE TITLE
class_attributes_separation doesn't consider trait usages

### ISSUE THREAD

**Issue by jackbentley** [FriendsOfPHP/PHP-CS-Fixer#5490]
## Bug report

The rule `class_attributes_separation` doesn't consider trait `use` statements for blank line seperation.

   * PHP version: `7.4.12`
   * PHP CS Fixer version: `PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski`

### Code snippet that reproduces the problem

```php
class MyClass {
    use MyTrait;
    public const MY_VAR = 1;
    public functionmyFunction() { return true; }
}
```

### Expected

```php
class MyClass
{
    use MyTrait;

    public const MY_VAR = 1;

    public function myFunction()
    {
        return true;
    }
}
```

### Actual

```php
class MyClass
{
    use MyTrait;
    public const MY_VAR = 1;

    public function myFunction()
    {
        return true;
    }
}
```

Note that PHP CS Fixer won't remove the blank line if it's added manually.

**Comment by kubawerlos** [comment]
@jackbentley can you raise a PR with failing test to show the issue you have?

I've added test case:
```
[
            '<?php class MyClass
{
    use MyTrait;

    public const MY_VAR = 1;

    public function myFunction() { return true; }
}',
            '<?php class MyClass
{
    use MyTrait;
    public const MY_VAR = 1;
    public function myFunction() { return true; }
}',
        ]
```

and it works fine.

**Comment by SpacePossum** [comment]
Hi @jackbentley thanks for reporting, thanks @kubawerlos for checking :+1: If any of you have time please review my PR with proposed fix.
