### ISSUE TITLE
Is there a rule to update `'foo'      => 'bar'` to `'foo' => 'bar'`

### ISSUE THREAD

**Issue by hivokas** [FriendsOfPHP/PHP-CS-Fixer#5493]
## Support question

Is there a way to update this:

```
$a = [
    'foo'           => 12,
    'baaaaaaaaaaar' => 13,
];
```

to this:
```
$a = [
    'foo' => 12,
    'baaaaaaaaaaar' => 13,
];
```
?

I've tried the `array_indentation` rule, but it has another purpose so it didn't help me.

**Comment by keradus** [comment]
Closing due to merge of #5494
