### ISSUE TITLE
Whitespace around union types separator

### ISSUE THREAD

**Issue by neochief** [FriendsOfPHP/PHP-CS-Fixer#5495]
## Rule request

Currently, white space around | inside union types behaves according to binary_operator_spaces rule, which is not exactly correct. By default, it inserts spaces around the |, while in 99% of PHP docs, there is no space.

### Code snippet that shows how the rule would fix PHP code

  ```php
- function foo(int | string $bar): int | string
+ function foo(int|string $bar): int|string
  ```

**Comment by neochief** [comment]
This problem was also mentioned in the PHP8.0 integration test file: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5399/files#r552251631

**Comment by b1rdex** [comment]
Temporary solution: `'binary_operator_spaces' => ['operators' => ['|' => null]]`
This will disable `binary_operator_spaces` for `|`.

**Comment by kubawerlos** [comment]
Is removing whitespace around union types a way to go? Is there any recommendation from PSR group or something like that? Or is the source of truth only the RFC: https://wiki.php.net/rfc/union_types_v2?

**Comment by b1rdex** [comment]
> Is removing whitespace around union types a way to go? Is there any recommendation from PSR group or something like that? Or is the source of truth only the RFC: https://wiki.php.net/rfc/union_types_v2?

AFAIK, there is no recommendation regarding formatting the union types. Removing the spaces is opinionated, based on the PHP documentation and the RFC.

I'm not sure about the default behavior and settings, but I propose to split a bitwise pipe token and a union type pipe. This way it won't be affected by the current rules and would allow creating a rule to format the union type pipes.

**Comment by b1rdex** [comment]
PSR-5 mentions PHPDoc union types without a word about spaces: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#details

Related issue in PHP_CodeSniffer: https://github.com/squizlabs/PHP_CodeSniffer/issues/3151

**Comment by vudaltsov** [comment]
Seems like `'binary_operator_spaces' => ['operators' => ['|' => null]]` is still needed in `3.2.0`.

**Comment by kubawerlos** [comment]
@vudaltsov where do you have `3.2.0` from?

If you are referring to `3.1.0` can you share an example of code that got messed whitespaces for union types with `binary_operator_spaces`?

**Comment by vudaltsov** [comment]
@kubawerlos , oh, yes, I meant `3.1.0`. I'll try to make a reproducer.
