### ISSUE TITLE
PHP Attribute in global namespace

### ISSUE THREAD

**Issue by wkania** [FriendsOfPHP/PHP-CS-Fixer#5497]
## Bug report

Tested with dev-master and PHP 8.0.2

Fixer wants to move Attribute to the global namespace by removing the backslash.
```
-#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
+#[Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
```
### Code snippet that reproduces the problem
```
 /**
  * @author Benjamin Eberlei <kontakt@beberlei.de>
  */
 #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
 class UniqueEntity
 {
 }
```
Maybe the problem is in [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/be542fb5db5b026b768b4ffe2f59f2268484a392/src/Fixer/Import/GlobalNamespaceImportFixer.php) class?

**Comment by wkania** [comment]
Now I see there is already a [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5464) for that.

**Comment by keradus** [comment]
Closing as PR got merged
