### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by ruudk** [FriendsOfPHP/PHP-CS-Fixer#5502]
I want to ask a question but the template suggests me to use Gitter.im. I opened it and see that it's not very active. I don't need an answer right away, and I feel that putting it in the chat will just burry it when the next person comes in and drops something.

Wouldn't it be an idea to enable GitHub Discussions? Example: https://github.com/laravel/framework/discussions

**Comment by keradus** [comment]
As you see, opening a thread at github repo doesn't guarantee prompt answer.
GH Discussion were not yet fully rolled-out to public, we got access to it only yesterday. Core team is discussing whether to use it, and how. Thanks for suggestion!
