### ISSUE TITLE
Exit code missmatch

### ISSUE THREAD

**Issue by christophrumpel** [FriendsOfPHP/PHP-CS-Fixer#5503]
## Bug report

PHP: 8.0.2
PHP CS Fixer: 2.18.2
Config: Default

In my application, I use the fixer to format code snippets users can store, and I need to know if a file was fixed / not or not handled due to an error.
The only way I found to check that was through the command's `exit codes`:

```
0 - OK.
1 - General error (or PHP minimal requirement not matched).
4 - Some files have invalid syntax (only in dry-run mode).
8 - Some files need fixing (only in dry-run mode).
16 - Configuration error of the application.
32 - Configuration error of a Fixer.
64 - Exception raised within the application.
```

But I get back `0` for all cases:

* File was not changed -> 0
* File was changed -> 0
* File was incorrect (invalid PHP code) ->0

### Code snippet that reproduces the problem

```shell
vendor/bin/php-cs-fixer fix invalidFile.php
echo $? 
```

It returns exit code `0`, but it should be `1` right?

And here the `invalidFile.php`file:
  ```php
<?php

class {
  ```

Is this correct behavior? I need to handle cases where the file is not valid. Thanks

**Comment by kubawerlos** [comment]
> ```shell
> vendor/bin/php-cs-fixer fix invalidFile.php
> echo $? 
> ```
> 
> It returns exit code `0`, but it should be `1` right?

No, `0` is expected, it is this scenario: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.2/tests/Console/Command/FixCommandExitStatusCalculatorTest.php#L56

**Comment by SpacePossum** [comment]
if you want to detect invalid PHP code in files you might want to try running with the `--dry-run` flag set to true

**Comment by christophrumpel** [comment]
Thanks, I'm currently using the `dry-run` option indeed. Would be cool to have a default exit code for that.
