### ISSUE TITLE
phpdoc_to_comment and @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter

### ISSUE THREAD

**Issue by soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#5505]
### Code snippet that reproduces the problem

```php
/**
 * {@inheritdoc}
 */
protected function configureDatagridFilters(DatagridMapper $datagridMapper): void
{
    $datagridMapper
        ->add('owners', 'doctrine_orm_callback', [
            /** @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter */
            'callback' => static function ($queryBuilder, $alias, $field, $value) {
                // ...
                return $queryBuilder;
            },
            'field_type' => \App\Form\Type\EntityUserType::class,
        ])
    ;
}
```

After appliance:

```diff
diff --git a/src/Admin/ServerAdmin.php b/src/Admin/ServerAdmin.php
index 18f15b8ca..65ad8f356 100644
--- a/src/Admin/ServerAdmin.php
+++ b/src/Admin/ServerAdmin.php
@@ -183,7 +183,7 @@ class ServerAdmin extends AbstractAdmin
     {
         $datagridMapper
             ->add('owners', 'doctrine_orm_callback', [
-                /** @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter */
+                /* @phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter */
```

It looks like to be expected, however, the `@phpcsSupress` annotation needs to be set with `/**` prefix in order to work properly.

To make both tools compatible, we should skip when `@phpcsSupress` is used.

**Comment by WinterSilence** [comment]
@soullivaneuh CS-Fixer can be fix anything, just add `comment_to_phpdoc`)))

**Comment by WinterSilence** [comment]
he true:
> "Structural Element" is a collection of Programming Constructs which MAY be preceded by a DocBlock. The collection contains the following constructs:
    ....
    **variables**, both local and global scope.

**Comment by VincentLanglet** [comment]
I have the same issue with `/** @psalm-suppress */`

**Comment by soullivaneuh** [comment]
Looks to be a good idea. :+1:

**Comment by soullivaneuh** [comment]
It looks to be a good idea. :+1: 

Why not also maintaining a vendor tags list to ignore by default? This will make configuration life much easier! :+1:

**Comment by kubawerlos** [comment]
> Why not also maintaining a vendor tags list to ignore by default?

- will bring additional maintenance effort which already is not small
- will be BC
- why would you assume people would like to want these tags ignored by default?

Personally I don't want to - anytime I see `@phpcsSuppress`, `@psalm-suppress` or similar ones my thoughts are: it's done from the wrong way - tools such as PHPCS, PHPStan, Psalm etc. should be configured in a way the code fulfils the expectations (expressed via configuration), not the other way around. As I had this discussion many times I have this real-life example:

A guy drives too fast on a highway and is stopped by the police office.
Police officer tells him he will be fined, but the driver says "I have immunity", so police officer let's him go as he said he has immunity. Is that right? The guy did not have any immunity, he only said he has.

Or will the police officer verify that what the driver is saying is the truth?

**Comment by VincentLanglet** [comment]
> A guy drives too fast on a highway and is stopped by the police office.
> Police officer tells him he will be fined, but the driver says "I have immunity", so police officer let's him go as he said he has immunity. Is that right? The guy did not have any immunity, he only said he has.
> 
> Or will the police officer verify that what the driver is saying is the truth?

When a policeman control a driver, does he first ask for a driver license or does he first ask to the administration system if the driver has a driver license ?

Here it's the same, you might prefer to annotate the code, where it is, with context and some comments, instead of writing everything in another file, forcing the reader to jump between multiples files.

The same reason why you're writing the phpdoc next to a method/class and not in another file.

**Comment by kubawerlos** [comment]
> When a policeman control a driver, does he first ask for a driver license or does he first ask to the administration system if the driver has a driver license ?

The driving license is a standardized thing - made not by the driver, but given to him - and all drivers show it, even when these stopped for random control.

> The same reason why you're writing the phpdoc next to a method/class and not in another file.

Not really, PHPDocs you write to follow standard, not to violate it. Supressing/ignoring rules in code is like saying "I know the rules, but will not follow them this time", so it's not the same.

**Comment by WinterSilence** [comment]
@kubawerlos it's not BC if not enabled by default
>why would you assume people would like to want these tags ignored by default?

that's guys as minimum

**Comment by kubawerlos** [comment]
> it's not BC if not enabled by default

@WinterSilence I know, but @soullivaneuh wants to have these tags added by default

**Comment by WinterSilence** [comment]
@kubawerlos I'm think he talk about global(affecting on all PhpDoc fixes) ignore list by tags. Need explanations...
