### ISSUE TITLE
Could `single_space_after_construct` be extended with short-open-tags?

### ISSUE THREAD

**Issue by LC-Rikkert** [FriendsOfPHP/PHP-CS-Fixer#5510]
Could `single_space_after_construct` be extended with short-open-tags, so that `<?=$body; ?>` and `<?=    $body; ?>` will both be changed to `<?= $body; ?>`?

**Comment by SpacePossum** [comment]
Hi and thanks for your question,

Currently the [rule](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.19.0/doc/rules/language_construct/single_space_after_construct.rst) already support this through `open_tag_with_echo` 

```
$ php php-cs-fixer fix test.php --dry-run --rules=single_space_after_construct --diff
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
   1) PHP-CS-Fixer/test.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
-<?=   $body; ?>
+<?= $body; ?>
```
