### ISSUE TITLE
Allow choice of quote style in implode_call

### ISSUE THREAD

**Issue by Andrew-Staves-Activ** [FriendsOfPHP/PHP-CS-Fixer#5511]
## Feature request

Could the `implode_call` fixer allow a choice of quote style (between single and double quotes)?

Currently:
`implode($someArray)`

Becomes:
`implode('', $someArray)`

I would like the option to have this produce:
`implode("", $someArray)`

Thanks!

**Comment by kubawerlos** [comment]
It would increase the complexity and maintenance effort - is there any well-recognized standard that this new option would support?

**Comment by Andrew-Staves-Activ** [comment]
No, there's no published/well-recognised standard that I'm aware of (though I haven't looked for one). Using double-quotes predominately is part of the style at the company I work for, that's all.

**Comment by kubawerlos** [comment]
Maybe then creating a custom fixer (which would be basically copying `single_quotes` and swapping `'` with `"`) is the way.

BTW out of curiosity what is the reasoning for double-quotes?

**Comment by Andrew-Staves-Activ** [comment]
Sure, I may see if I can find some time to learn how to create one of those.

It was decided a number of years ago, I believe the reasoning was that double-quotes are more often required (or, at least, helpful) for string interpolation whereas there were fewer situations where single quotes were required. I think double-quotes may also have been more prevalent in the codebase at the time (and are now, obviously).

**Comment by kubawerlos** [comment]
This cookbook may help: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.2/doc/cookbook_fixers.rst

**Comment by Andrew-Staves-Activ** [comment]
Heh, good intro. at least "You want to make a new fixer to PHP CS Fixer and do not know how to start." 
Thanks, I'll check it out.

**Comment by keradus** [comment]
Or, one can extend `single_quote` to have the way of quoting as configuration.

Anyway, as discussed, it should be out of implode_call rule.
Closing due to discussion.
