### ISSUE TITLE
nullable_type_declaration_for_default_null_value causes a parse error on 2.18.3

### ISSUE THREAD

**Issue by vudaltsov** [FriendsOfPHP/PHP-CS-Fixer#5536]
## Bug report

* `PHP 8.0.2 (cli) (built: Feb  4 2021 18:10:29) ( NTS )`
* `PHP CS Fixer 2.18.3 Remote Void by Fabien Potencier and Dariusz Ruminski`
* `php vendor/bin/php-cs-fixer fix --show-progress=estimating-max  -vvv`

With `'nullable_type_declaration_for_default_null_value' => true` the code below produces 

```
[PhpCsFixer\Linter\LintingException] Parse error: syntax error, unexpected token "#[" on line 14.
```

```php
<?php

declare(strict_types=1);

namespace HappyInc\Import\CompanyStructureImport;

use Symfony\Component\Validator\Constraints as Assert;

final class CompanyStructureImportRow
{
    public function __construct(
        #[Assert\Count(min: 1, minMessage: 'Пустая цепочка департаментов.')]
        public array $departmentTitleChain,
        #[Assert\NotBlank(message: 'Пустой email.', allowNull: true)]
        #[Assert\Email(message: 'Некорректный email {{ value }}.')]
        public ?string $email = null,
    ) {
    }
}
```

Disabling `nullable_type_declaration_for_default_null_value` fixes the issue.

**Comment by keradus** [comment]
I think we may not support attributes on parameter level at all.
can you raise a PR to improve the situation, @vudaltsov ?

**Comment by vudaltsov** [comment]
@keradus , I'm pretty busy this month. I will try to find some time, though.

**Comment by kubawerlos** [comment]
This is fixed by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5665.
