### ISSUE TITLE
[2.18.3] Rule 'yoda_style' with value null is broken

### ISSUE THREAD

**Issue by Gounlaf** [FriendsOfPHP/PHP-CS-Fixer#5538]
## Bug report

   * PHP CS Fixer version: **2.18.3**

### Code snippet that reproduces the problem

Using value 'null' for rule 'yoda_style' doesn't work anymore.

>  [yoda_style] Configuration must be an array and may not be empty.  

It's because of commit https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/c39900d551c2cc22fe99ccf9cb2f0c788ddf1aa2

**Comment by Gounlaf** [comment]
#5537 suffer from same root problem. So mine is kind of duplicate. Sorry.

**Comment by keradus** [comment]
Closing as a duplicate then, thanks for pointing @Gounlaf
