### ISSUE TITLE
Custom annotations @type changed into @var

### ISSUE THREAD

**Issue by ivansrdic** [FriendsOfPHP/PHP-CS-Fixer#5544]
## Bug report

PHP - 7.4.16
PHP CS Fixer - 2.17.0 and above (2.6.10 works )

Running php-cs-fixer without any custom config options changes `@type` into `@var` in custom annotations. Two examples which I've encountered.

```php
<?php

use Symfony\Component\Serializer\Annotation as ApiSerializer;

/**
 * @ApiSerializer\DiscriminatorMap(typeProperty="@type", mapping={
 *     "MyClass" = "App\Entity\MyClass"
 * })
 */
class MyClass
{
    /**
     * @ApiSerializer\SerializedName("@type")
     * @ApiSerializer\Groups({
     *     "my_serialization_group"
     * })
     */
    protected $myAtTypeProperty;
}
```

After running php-cs-fixer it is changed into 
```php
<?php

use Symfony\Component\Serializer\Annotation as ApiSerializer;

/**
 * @ApiSerializer\DiscriminatorMap(typeProperty="@var", mapping={
 *     "MyClass" = "App\Entity\MyClass"
 * })
 */
class MyClass
{
    /**
     * @ApiSerializer\SerializedName("@var")
     * @ApiSerializer\Groups({
     *     "my_serialization_group"
     * })
     */
    protected $myAtTypeProperty;
}
```

`@type` is an ApiPlatform default property representing the short class name of the serialized entity. For some

**Comment by keradus** [comment]
hey @ivansrdic , thanks for reporting!
please, provide your configuration to help identifying the issue

also, would you like to suggest a fix for it ?

**Comment by ivansrdic** [comment]
@keradus I've mentioned in the submission that there is no custom configuration used, I just run `bin/php-cs-fixer fix src/Entity/MyClass`

Unfortunately, php-cs-fixer is quite complex and I wasn't able to find what change in 2.17.0 compared to 2.6.10 broke the functionality. I'll try to spend more time on it, but I can't promise anything.
