### ISSUE TITLE
Release 2.18.4 has 2.18.4-DEV in PhpCsFixer\Console\Application::VERSION

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#5556]
Shouldn't [this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.4/src/Console/Application.php#L37) be

```php
    const VERSION = '2.18.4';
```

instead of

```php
    const VERSION = '2.18.4-DEV';
```

?

**Comment by keradus** [comment]
Hey, thanks for spotting. the only way to fix it is to actually release 2.18.5, which is planned anyway, so i gonna close this github issue.

**Comment by mlocati** [comment]
Just a hint for future releases 😉

**Comment by GPHemsley-RELX** [comment]
For reference: 
* 06f764e3cb6d60822d8f5135205f9d32b5508a31 was the commit that was tagged as v2.18.4
* e0326187520ce098bad34a424669cbc09d610613 (the next commit) was the commit that _should have been_ tagged as v2.18.4, as it included the changelog and version bump
