### ISSUE TITLE
Release v3.0.0-beta.1 should be marked as pre-release

### ISSUE THREAD

**Issue by lukasbestle** [FriendsOfPHP/PHP-CS-Fixer#5558]
The release v3.0.0-beta.1 is not marked as a pre-release using the "This is a pre-release" checkbox. This makes tools like the [Setup PHP](https://github.com/shivammathur/setup-php/issues/436) GitHub Action install it automatically.

Please edit the GitHub release and check that box to fix this. Thanks!

**Comment by keradus** [comment]
I marked it as pre-release.
To be honest, we follow semantic versioning and i thought it's enough to indicate whether release is stable or not.
