### ISSUE TITLE
Website is down due to an invalid certificate

### ISSUE THREAD

**Issue by jakzal** [FriendsOfPHP/PHP-CS-Fixer#5565]
## Bug report

The website https://cs.symfony.com/ does not load. 

PHAR cannot be downloaded from https://cs.symfony.com/download/php-cs-fixer-v2.phar

### Code snippet that reproduces the problem

curl -Ls https://cs.symfony.com

```
<html>
<head><title>526 Origin SSL Certificate Error</title></head>
<body bgcolor="white">
<center><h1>526 Origin SSL Certificate Error</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```

**Comment by keradus** [comment]
Hey, we are aware. there is sth going on with github.io pages trying to apply their certificate. we reached out to github support already

**Comment by keradus** [comment]
https://cs.symfony.com/ should be up again,
let's wait till tomorrow to ensure DNS propagation won't change it.

**Comment by jakzal** [comment]
All good now 👍

**Comment by abelardolg** [comment]
Howdy!
How could I solve this issue, please?
Resolving cs.symfony.com (cs.symfony.com)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to cs.symfony.com (cs.symfony.com)|185.199.108.153|:443... connected.
ERROR: The certificate of 'cs.symfony.com' is not trusted.
ERROR: The certificate of 'cs.symfony.com' has expired.

**Comment by keradus** [comment]
Cannot reproduce on my side.

I would suggest to check your docker - maybe configured datetime is wrong or Certificate Authority is outdated.

**Comment by abelardolg** [comment]
Ok. Thanks.
