### ISSUE TITLE
style fixer for class is not backward-compatible

### ISSUE THREAD

**Issue by phil-davis** [FriendsOfPHP/PHP-CS-Fixer#5566]
## Bug report

   * PHP version: 7.4.16
   * PHP CS Fixer version: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.18.4
   * the command used to run PHP CS Fixer (run with `-vvv`)

` php -d zend.enable_gc=0 vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix -v --diff --diff-format udiff --allow-risky yes --dry-run`

```
<?php

$dirToParse = 'apps';
$dirIterator = new DirectoryIterator(__DIR__ . '/' . $dirToParse);

$bundledApps = [
	'comments',
	'dav',
	'encryption',
	'federatedfilesharing',
	'federation',
	'files',
	'files_external',
	'files_sharing',
	'files_trashbin',
	'files_versions',
	'provisioning_api',
	'systemtags',
	'updatenotification'
];

$excludeDirs = [
	'lib/composer',
	'build',
	'apps/files_external/3rdparty',
	'apps-external',
	'data',
	'3rdparty',
];

foreach ($dirIterator as $fileinfo) {
	$filename = $fileinfo->getFilename();
	if ($fileinfo->isDir() && !$fileinfo->isDot() && !in_array($filename, $bundledApps)) {
		$excludeDirs[] = $dirToParse . '/' . $filename;
	}
}

$finder = PhpCsFixer\Finder::create()
	->exclude($excludeDirs)
	->notPath('config/config.php')
	->notPath('config/config.backup.php')
	->notPath('tests/autoconfig*')
	->in(__DIR__);

$config = new OC\CodingStandard\Config();
$config->setFinder($finder);
return $config;
```

### Code snippet that reproduces the problem

PR https://github.com/owncloud/core/pull/38560

The style check against current `owncloud/core` master passes with PHP-CS-Fixer 2.18.3.

But with no change to any settings, it fails with PHP-CS-Fixer 2.18.4.

It now wants to put the `{` on a new line after a `class` statement. That causes us to need to change 2144 files!

**Comment by keradus** [comment]
@phil-davis , can you please provide full bug report, following the template: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/.github/ISSUE_TEMPLATE/bug_report.md ? it makes it way easier if we have minimum code to reproduce the issue

**Comment by phil-davis** [comment]
I missed the config! It is https://github.com/owncloud/coding-standard/blob/master/src/Config.php

```
namespace OC\CodingStandard;

use PhpCsFixer\Config as BaseConfig;

class Config extends BaseConfig {
	public function __construct($name = 'default') {
		parent::__construct('ownCloud coding standard');
		$this->setIndent("\t");
	}

	public function getRules() {
		$rules = [
			'@PSR1' => true,
			// PSR-2
			'braces' => [
				'position_after_functions_and_oop_constructs' => 'same'
			],
			'class_definition' => true,
			'elseif' => true,
			'encoding' => true,
			'full_opening_tag' => true,
			'function_declaration' => true,
			'indentation_type' => true,
			'line_ending' => true,
			'lowercase_constants' => true,
			'lowercase_keywords' => true,
			'method_argument_space' => true,
			'no_break_comment' => true,
			'no_closing_tag' => true,
			'no_spaces_after_function_name' => true,
			'no_spaces_inside_parenthesis' => true,
			'no_trailing_whitespace' => true,
			'no_trailing_whitespace_in_comment' => true,
			'single_blank_line_at_eof' => true,
			'single_class_element_per_statement' => true,
			'single_import_per_statement' => true,
			'single_line_after_imports' => true,
			'switch_case_semicolon_to_colon' => true,
			'switch_case_space' => true,
			'visibility_required' => true,
			// ownCloud specific
			'native_function_invocation' => true,
			'array_syntax' => ['syntax' => 'short'],
			'combine_consecutive_issets' => true,
			'combine_consecutive_unsets' => true,
			'no_extra_consecutive_blank_lines' => true,
			'is_null' => true,
			'yoda_style' => [
				'equal' => false,
				'identical' => false
			],
            // phpunit automated refactorings
            'php_unit_no_expectation_annotation' => true,
            'php_unit_expectation' => true,
            'php_unit_dedicate_assert_internal_type' => true
        ];
		return $rules;
	}
}
```

**Comment by phil-davis** [comment]
@keradus now the challenge is to work out which rule is related to `class` and `interface` declarations needing to have the opening `{` on the same line or on the next line.

I will have a play with a "demo" class and see what I can deduce.

**Comment by phil-davis** [comment]
With a config like this:
```
<?php
/**
 * @author Patrick Jahns <github@patrickjahns.de>
 * @author Thomas Müller <thomas.mueller@tmit.eu>
 *
 * @copyright Copyright (c) 2018, ownCloud GmbH
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

namespace OC\CodingStandard;

use PhpCsFixer\Config as BaseConfig;

class Config extends BaseConfig {
	public function __construct($name = 'default') {
		parent::__construct('ownCloud coding standard');
		$this->setIndent("\t");
	}

	public function getRules() {
		$rules = [
			'@PSR1' => true,
			'class_definition' => true,
        ];
		return $rules;
	}
}
```

And code:
```
<?php
class Controller {
}
```

Run the fixer (v2.18.4):
```
php vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix --diff --dry-run settings/ChangePassword/Controller.php
Loaded config ownCloud coding standard from "/home/phil/git/owncloud/core/.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
   1) settings/ChangePassword/Controller.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
-class Controller {
+class Controller
+{
 }
 

      ----------- end diff -----------


Checked all files in 0.004 seconds, 12.000 MB memory used

```
It wants the `{` to be on a new line.

If I run the same with 2.18.3 it passes (the `{` on the same line is fine)

https://cs.symfony.com/doc/rules/class_notation/class_definition.html indicates that the `class_definition` rule always wants the `{` to be on a new line. So maybe the problem is that the `class_definition` rule was not effective in 2.18.3 and now it is effective.

**Comment by phil-davis** [comment]
In the diffs https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.18.3...v2.18.4 I don't see any obvious change that would make `class_definition` start working. But maybe there is some side-effect of all the `getPriority()` changes?

**Comment by prisis** [comment]
I have kind of the same error, 2.18.3 is working after chaning to 2.18.4 im getting this  
  
Class:

```
<?php

declare(strict_types=1);

/**
 * Copyright (c) 2020-2021 Daniel Bannert
 *
 * For the full copyright and license information, please view
 * the LICENSE.md file that was distributed with this source code.
 *
 * @see https://github.com/narrowspark/automatic-versions
 */

namespace Narrowspark\Automatic\Versions\Contract;

interface Provider
{
    /**
     * Fetch data from a source.
     *
     * @return array<int|string, array>
     */
    public function fetch(): array;
}
```

Error:

```
/var/www/package/src/Contract/Provider.php

                                       
        [RuntimeException]             
        Index invalid or out of range  
                                       

      PhpCsFixer\Tokenizer\Tokens->findOppositeBlockEdge()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Tokens.php at line 470
      PhpCsFixer\Tokenizer\Tokens->findBlockEnd()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php at line 146
      PhpCsFixer\Fixer\Phpdoc\PhpdocAddMissingParamAnnotationFixer->applyFix()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 75
      PhpCsFixer\AbstractFixer->fix()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 190
      PhpCsFixer\Runner\Runner->fixFile()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 132
      PhpCsFixer\Runner\Runner->fix()
        in /var/www/package/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php at line 225
      PhpCsFixer\Console\Command\FixCommand->execute()
        in /var/www/package/vendor/symfony/console/Command/Command.php at line 256
```

Im trying to debug it right now, what change did it

**Comment by prisis** [comment]
Okay i think that i found the error, if i revert the change on src/Fixer/Alias/PowToExponentiationFixer.php   
  
\`\`\`diff  
    public function getPriority()  
   {

       -  return 35;  
       + return -25;  
   }  
\`\`\`  
  
@phil-davis can you try to edit this file?

**Comment by phil-davis** [comment]
> can you try to edit this file?

For any 0 or positive value returned by `getPriority` the "problem/feature" remains (e.g. 0, 5, 15, 25, 42, 99, 111). The `class_definition` rule puts the `{` on a new line.

For a negative value returned by `getPriority` the "problem/feature" does not happen (e.g. -1, -25).

I suspect that for negative priority values, the related fixer does not run at all. But looking at the source code, the priority value is used for sorting the order of fixers. I don't see how the sorting can completely "lose" a fixer from the array of fixers to apply.

IMO for me the change in 2.18.4 is actually a fix. The `class_definition` rule now runs effectively. And actually my code does not meet the rule, and the changes it suggests are the correct ones. The fix is not obvious in the release notes - perhaps the fix is somewhat "accidental" as a result of those priority numbers changing? And that is why I raised this issue - from the release notes I was not expecting a fix like this.

@prisis you are able to cause a RuntimeException. I suspect that that will be some problem in a fixer that is now getting run (and maybe previously never even ran?) It might be best for you to create a separate issue that has the rule set that you are using.

**Comment by cspitzlay** [comment]
FWIW: This change in 2.18.4 breaks the Drupal 8 formatting rules I am using that I get from https://github.com/drupol/phpcsfixer-configs-drupal

Does this mean that the configuration in that project needs to be adapted now and I need to report an issue there, or is this behavior change in a minor update of php-cs-fixer is to be regarded a bug?

**Comment by jotoeri** [comment]
Hm, @phil-davis,

i'm not sure, if it's just your code that does not comply.
Nextcloud explicitely sets `'position_after_functions_and_oop_constructs' => 'same'`, which according to the docs should require the 'inline'-style:
> position_after_functions_and_oop_constructs
whether the opening brace should be placed on "next" or "same" line after classy constructs (non-anonymous classes, interfaces, traits, methods and non-lambda functions).
Allowed values: 'next', 'same'
Default value: 'next'

So it should apply the same rule for classes AND methods, which is obviously not the case...

Greets 🙂

**Comment by kubawerlos** [comment]
@phil-davis @prisis it's already fixed with https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5567, I've [extended](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5577) the priority test to explixitly cover scenario from this issue.

**Comment by jotoeri** [comment]
@kubawerlos Are you planning to release a patch on this?

**Comment by phil-davis** [comment]
Yes, any chance to release 2.18.5 with the current code that is already merged?

**Comment by kubawerlos** [comment]
@jotoeri only @keradus does releases (as we can see at https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases).

**Comment by jotoeri** [comment]
Oups. 🙈 
So well, then @keradus, are you planning for a release to fix that bug...? 😉 🙈

**Comment by keradus** [comment]
please be patient, all of us have a private live and not always can focus on open source
