### ISSUE TITLE
[Question] Is it possible to make single line chained method calls multi line?

### ISSUE THREAD

**Issue by budhajeewa** [FriendsOfPHP/PHP-CS-Fixer#5578]
## Support question

Hey,

I posted this in the Gitter community too: https://gitter.im/PHP-CS-Fixer/Lobby?at=605d54b93b9278255bd40688

Is there a rule to format the following:

```
$object->chainedMethod1()->chainedMethodN();
```

As follows:

```
$object
    ->chainedMethod1()
    ->chainedMethodN()
;
```

**Comment by kubawerlos** [comment]
And there is an answer in to Gitter message:

> no
