### ISSUE TITLE
Rule no_unused_imports bug

### ISSUE THREAD

**Issue by smujaddid** [FriendsOfPHP/PHP-CS-Fixer#5582]
## Bug report
PHP version: 8.0.3
PHP CS Fixer version: PHP CS Fixer 2.18.4-DEV Remote Void
Command used:
```shell
./vendor/bin/php-cs-fixer fix app/Http/Controllers/TestController.php --using-cache=no --dry-run --diff --diff-format=udiff -vvv
```
Configuration file:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([
        __DIR__.'/app',
        __DIR__.'/config',
        __DIR__.'/database',
        __DIR__.'/resources/lang',
        __DIR__.'/routes',
        __DIR__.'/tests',
    ])
    ->exclude([
        'Vendor',
        'api-tests',
        'web-tests',
    ]);

return (new PhpCsFixer\Config())
    ->setFinder($finder)
    ->setRules([
        'no_unused_imports' => true,
// Other rules are removed because they doesn't make difference for the results
    ]);
```

### Code snippet that reproduces the problem
I'm using PHP CS Fixer for my Laravel project with an example of code like this:

```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;

class TestController extends Controller
{
    public function index(Request $request)
    {
        return view('test.dashboard.index');
    }
}
```

### Command Results
```diff
./vendor/bin/php-cs-fixer fix app/Http/Controllers/TestController.php --using-cache=no --dry-run --diff --diff-format=udiff -vvv
PHP CS Fixer 2.18.4-DEV Remote Void by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.3
Loaded config default from "/home/me/works/laravel-project/.php_cs".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) laravel-project/app/Http/Controllers/TestController.php (no_unused_imports)
      ---------- begin diff ----------
--- Original
+++ New
@@ -2,12 +2,7 @@
 
 namespace App\Http\Controllers;
 
-use App\Http\Controllers\Controller;
 use Illuminate\Http\Request;
-use Illuminate\Support\Facades\Auth;
-use Illuminate\Support\Facades\Redirect;
-use Illuminate\Support\Facades\Session;
-use Illuminate\Support\Facades\Validator;
 use Illuminate\Support\Facades\View;
 
 class TestController extends Controller

      ----------- end diff -----------


Checked all files in 0.009 seconds, 24.000 MB memory used
```

### Expected Results
The expected results for `no_unused_imports` is the `use App\Http\Controllers\Controller;` should not be removed and `use Illuminate\Support\Facades\View;` should be removed, like the example below:

```diff
      --------- begin diff ----------
--- Original
+++ New
@@ -2,12 +2,7 @@
 
 namespace App\Http\Controllers;
 
 use App\Http\Controllers\Controller;
 use Illuminate\Http\Request;
-use Illuminate\Support\Facades\Auth;
-use Illuminate\Support\Facades\Redirect;
-use Illuminate\Support\Facades\Session;
-use Illuminate\Support\Facades\Validator;
-use Illuminate\Support\Facades\View;
 
 class TestController extends Controller

      ----------- end diff -----------
```

### The Bug
Notice this line of code
```php
return view('test.dashboard.index');
```

I think because `view` and `Illuminate\Support\Facades\View` is compared with case-insensitive (maybe), the import is not removed.

If I change that line of code to:
```php
return viewx('test.dashboard.index');
```
The import `Illuminate\Support\Facades\View` is definitely removed.

For the import `App\Http\Controllers\Controller` why it is removed, I can't think any possible explanation.

**Comment by tacman** [comment]
I'm also seeing this, but I wasn't seeing it before, so perhaps it's a recent change.

**Comment by kubawerlos** [comment]
@smujaddid `Illuminate\Support\Facades\View` is not removed because the `no_unused_imports` does not differentiate between imports - it does not recognize it's a function call.

Removing `App\Http\Controllers\Controller` is perfectly fine - you are in `App\Http\Controllers` namespace and the `Controller` class is from the same namespace.

**Comment by smujaddid** [comment]
My mistake. You are right. Removing `Controller` is the correct behaviour.

Is there any rule that can enforce case-sensitive imports check for `no_unused_imports`, even if it is `risky`?

**Comment by kubawerlos** [comment]
> Is there any rule that can enforce case-sensitive imports check for `no_unused_imports`, even if it is `risky`?

There is not and I think it's by design as PHP is case insensitive when using/importing classes.
