### ISSUE TITLE
Compiler optimized native function invocation incorrectly detected after nullsafe operator

### ISSUE THREAD

**Issue by tpetry** [FriendsOfPHP/PHP-CS-Fixer#5584]
## Bug report
* PHP version: 8.0.3
* PHP CS Fixer version: 2.18.4-DEV
* the configuration (file) you used:
```php
return (new PhpCsFixer\Config())
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
            ->ignoreDotFiles(true)
            ->ignoreVCS(true)
    )
    ->setRules([
        '@Symfony:risky' => true,
    ]);
```

### Code snippet that reproduces the problem
```php
<?php

declare(strict_types=1);

namespace App;

$this->resource?->count();
```

### What PHP-CS-Fixer is trying to do
* Applied fixers: `native_function_invocation`
```diff
--- Original
+++ New
@@ @@
 
-$this->resource?->count();
+$this->resource?->\count();
```

**Comment by tpetry** [comment]
The root cause of the bug is that currently the source code does not handle `T_NULLSAFE_OBJECT_OPERATOR`, presumably all places containing `T_OBJECT_OPERATOR` could be extended to include `T_NULLSAFE_OBJECT_OPERATOR`?

**Comment by kubawerlos** [comment]
I'm on it: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5586 (quite few fixers, so might not be today 😉).
