### ISSUE TITLE
incompatible with plesk server

### ISSUE THREAD

**Issue by thomstark** [FriendsOfPHP/PHP-CS-Fixer#5591]
I've installed on a Plesk server using simply:

`composer require friendsofphp/php-cs-fixer`

When I try to run it using `./php-cs-fixer -V` or some such, I get the error exception: `undefined index: name` 

Apparently Plesk server must run on PHP 5.4 so I think this is the issue. Is there any workaround for this?

**Comment by thomstark** [comment]
The error is being triggered in ToolInfo.php, line 50

**Comment by thomstark** [comment]
I was able to get `-V` to work by making the following change to ToolInfo.php:

                ```
foreach ($composerInstalled as $packages) {
                if (!is_array($packages))
                {
                    if (in_array($packages['name'], array(self::COMPOSER_PACKAGE_NAME, self::COMPOSER_LEGACY_PACKAGE_NAME), true)) {
                        $this->composerInstallationDetails = $packages;

                        break;
                    }
                }
                else
                {
                    foreach($packages as $package)
                    {
                        if (in_array($package['name'], array(self::COMPOSER_PACKAGE_NAME, self::COMPOSER_LEGACY_PACKAGE_NAME), true)) {
                            $this->composerInstallationDetails = $package;

                            break;
                        }
                    }
                }
            }
```

Now I'm just getting the PHP version error but I can't figure out how to set the environment variable to ignore it. I don't see a .phar file anywhere.

**Comment by thomstark** [comment]
I've added `PHP_CS_FIXER_IGNORE_ENV=1` to `/etc/environment`
And I've added `export PHP_CS_FIXER_IGNORE_ENV=1` to my user's `.bashrc`. 
`printenv PHP_CS_FIXER_IGNORE_ENV` spits out "1" both in VS Code and directly in terminal. 

But I still get the php version error when trying to format in VS Code.

**Comment by thomstark** [comment]
Is there a way I can tell VS Code to run it like so: 

`/opt/plesk/php/7.2/bin/php  /path/to/vendor/friendsofphp/php-cs-fixer`

I tried putting that in the executable path and it just tells me that it's not found and it defaults to the .phar file.

**Comment by kubawerlos** [comment]
@thomstark what is the version of PHP CS Fixer you are running? If it's something compatible for PHP 5.4 I'm afraid it's not supported for years.

> Now I'm just getting the PHP version error but I can't figure out how to set the environment variable to ignore it. I don't see a .phar file anywhere.

Here is how to set env var: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.4/doc/usage.rst#environment-options

PHAR files are always available at https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases

**Comment by keradus** [comment]
As mentioned, PHP CS Fixer does not support PHP 5.4 anymore. Please update PHP CS Fixer to ^2.18

If the env you are using is using PHP 5.4, please consider updating it (is it this plesk you are talking about?: https://support.plesk.com/hc/en-us/articles/115002681053-How-to-change-PHP-version-for-a-domain-in-Plesk- ) or running PHP CS Fixer via docker
