### ISSUE TITLE
[PhpStorm compatibility] Don't fail in case --diff-format option is present

### ISSUE THREAD

**Issue by MaXal** [FriendsOfPHP/PHP-CS-Fixer#5600]
The removal of `--diff-format` leads to broken PhpStorm integration since PhpStorm invokes PHP-CS-Fixer using `--diff-format=udiff`.

To fix this on the PhpStorm side we have to implement versioning for Quality Tools which we don't have right now and for good reasons. PhpStorm support on-the-fly error reporting meaning it runs the tool on each typing so invoking `--version` on each such run will introduce a significant overhead taking into account support of SSH and Docker/Docker Compose execution. 
On the other hand, if we store the version only once that will lead to problems after `composer update` to the newer version. The integration will fail and customers will have to somehow update the version of PHP-CS-Fixer in PhpStorm stored configuration.

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5599

**Comment by keradus** [comment]
:-1: for this change per-se.
I do understand the issue, but I would love to overcome it a different way than introducing tech-debt for 3.0.0.

if I understand right, you are calling `php-cs-fixer fix --diff-format=udiff`. can you call `PHP_CS_FIXER_FUTURE_MODE=1 php-cs-fixer fix` instead? it will give you udiff on v2 and will take no effect on v3

**Comment by derrabus** [comment]
For reference: https://youtrack.jetbrains.com/issue/WI-59598

**Comment by MaXal** [comment]
@keradus Thank you for the solution! It's indeed the best way to solve the issue since it's easy to implement in PhpStorm and doesn't require any change in PHP CS Fixer. 

There is a small chance that some configuration may become broken though if they relied on some deprecated mechanics but that is ok in my opinion.

**Comment by keradus** [comment]
hey, great to hear that!
if you would need any further assistance or discussion, feel free to create new thread or catch me up for real-time talk at http://gitter.im/keradus
