### ISSUE TITLE
Provide a command-line argument to list all existing rulesets

### ISSUE THREAD

**Issue by MaXal** [FriendsOfPHP/PHP-CS-Fixer#5621]
In PhpStorm there is a chooser to run a predefined ruleset but available rulesets are hard-coded since there is no easy way to fetch them from CS-Fixer. 
For now, we have the following standards: `"PSR1", "PSR2", "Symfony", "DoctrineAnnotation", "PHP70Migration", "PHP71Migration"` and looking into https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/2.18/src/RuleSet/Sets it looks like the list is far from complete.

Since we support different versions of PHP-CS-Fixer, a command-line option that outputs the available standards will allow us to list all rulesets instead of a limited list supported by 2.8.0 (the earliest version we support).

**Comment by kubawerlos** [comment]
Hi @MaXal, how would you like to have that list? As a JSON e.g. `["PSR1", "PSR2", "Symfony"]`?

**Comment by keradus** [comment]
@MaXal , please check the PR #5635

**Comment by MaXal** [comment]
Answered in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5635. 
The suggested solution works great in PhpStorm.

**Comment by keradus** [comment]
Thanks @MaXal , great to hear!

yes, the PR was merged to `2.19@dev` line and will be released under `2.19.0` in near future
