### ISSUE TITLE
[3.0] Default config with new name isn't picked up automatically

### ISSUE THREAD

**Issue by Jean85** [FriendsOfPHP/PHP-CS-Fixer#5625]
## Bug report
Upgrade document says that the default names for configuration files are changed. 
The tools still picks up the old one though.

### Code snippet that reproduces the problem
 * Install 3.0-beta.2
 * create a `.php-cs-fixer.dist.php` file with this inside:
```
<?php

return new PhpCsFixer\Config(__FILE__);
```
 * run `vendor/bin/php-cs-fixer fix`
 * You'll see `Loaded config default`
 * Rename file into `.php_cs.dist`
 * run `vendor/bin/php-cs-fixer fix` again
 * You'll see `Loaded config [path]/.php_cs.dist`
```

**Comment by keradus** [comment]
Hey. When you created this bug report, there were NONE 3.0-beta.2 released.
there is branch `3.0.0-beta` (let me remove it to avoid confusion), but it was not synced with `3.0` branch that got configuration filename update.
switch to `3.0@dev` or await for 3.0.0-beta.2 tag (as branch was outdated)
