### ISSUE TITLE
PhpCsFixer\Report\ReportSummary missing in 2.18.6

### ISSUE THREAD

**Issue by scramatte** [FriendsOfPHP/PHP-CS-Fixer#5652]
## Bug report

We are using phpCsFixer with  Laravel-PHP-CS-Fixer. Since r2.18.6  ,  php artisan fixer:fix claims that 
Class "PhpCsFixer\Report\ReportSummary" not found.   And clearly folder Report is missing in PhpCsFix  2.18.6 

PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
PHP CS Fixer 2.18.6 Remote Void by Fabien Potencier and Dariusz Ruminski

### Code snippet that reproduces the problem
php artisan fixer:fix

Class "PhpCsFixer\Report\ReportSummary" not found
at vendor/stechstudio/laravel-php-cs-fixer/src/Console/FixCommand.php:97
     93▕         $progressOutput->printLegend();
     94▕ 
     95▕         $fixEvent = $this->stopwatch->getEvent('fixFiles');
     96▕ 
  ➜  97▕         $reportSummary = new ReportSummary(
     98▕             $changed,
     99▕             $fixEvent->getDuration(),
    100▕             $fixEvent->getMemory(),
    101▕             OutputInterface::VERBOSITY_VERBOSE <= $this->getOutput()->getVerbosity(),

**Comment by kubawerlos** [comment]
> And clearly folder Report is missing in PhpCsFix 2.18.6

In [this PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5639/files) all reports including `ReportSummary` were moved to [new place](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.18.6/src/Console/Report/FixReport/ReportSummary.php).

**Comment by keradus** [comment]
@scramatte , please do not use classes marked as internal

**Comment by kubawerlos** [comment]
To be fair it's fine to use it, but one must remember that internal classes are not covered by BC promise.

**Comment by keradus** [comment]
and then random folks are complaining about an unexpectedly broken library/app that is using PHP CS Fixer as dependency, because that library was messing up with PHP CS Fixer' internal, ending up with but in PHP CS Fixer.... not the best DX for everyone, I must admit

**Comment by kubawerlos** [comment]
If one decides to use it then must know the risk.

I wonder if it's possible to disable using internals from outside of the project (in some reasonable way).
