### ISSUE TITLE
Error when using union types `array|null` on public property

### ISSUE THREAD

**Issue by uyab** [FriendsOfPHP/PHP-CS-Fixer#5659]
## Bug report

   * PHP version: 8.0.3
   * PHP CS Fixer version: 3.0.0-rc.1

```bash
        [PhpCsFixer\Linter\LintingException]
        Parse error: syntax error, unexpected token "public" on line 19.


      Applied fixers: visibility_required
```

### Code snippet that reproduces the problem

```php
<?php

declare(strict_types=1);

namespace Laravolt\Camunda\Dto;

use Spatie\DataTransferObject\Attributes\Strict;
use Spatie\DataTransferObject\DataTransferObject;

#[Strict]
class ProcessInstance extends DataTransferObject
{
    public string $id;

    public string|null $tenantId;

    public string|null $businessKey;

    public array|null $links;

    public string $definitionId;

    public ?string $caseInstanceId;

    public bool $ended;

    public bool $suspended;
}

```

**Comment by uyab** [comment]
There is no issue if I wrote like this: 
```php
public ?array $links;

//or
public null|array $links;
```

**Comment by kubawerlos** [comment]
Hi @uyab, thanks for the report.

I'ts actually not a problem in `visibility_required`, but in one of internal transformers, see the fix in: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5660 (it's adding test for `visibility_required` for regression)- would be great if you could drop a review there.

**Comment by zolex** [comment]
it also happens for other visibility. e.g.

`private array|null $openingHours = null;`

becomes

`private array | public null $openingHours = null;`
