### ISSUE TITLE
@return being removed from docblock when function specifies return

### ISSUE THREAD

**Issue by SirCameron** [FriendsOfPHP/PHP-CS-Fixer#5666]
## Support question

```
/**
      * bla bla bla
-     *
-     * @return bool
      */
     public function blabla(): bool
```

@return bool is being removed.
I'm unable to find a rule to disable this..

**Comment by kubawerlos** [comment]
Run command `php-cs-fixer` with flag `-v` to see what fixers are used for each file.

**Comment by SpacePossum** [comment]
`no_superfluous_phpdoc_tags`
