### ISSUE TITLE
visibility_required doesn't work with PHP 8 union types

### ISSUE THREAD

**Issue by stancl** [FriendsOfPHP/PHP-CS-Fixer#5668]
## Bug report

This fixer seems to add visibility for each listed type. The code below becomes `protected array|public Closure $abc = [];`

Config:

```php
'visibility_required' => [
    'elements' => ['method', 'property']
],
```

### Code snippet that reproduces the problem

```php
class Foo
{
    protected array|Closure $abc = [];
}
```

**Comment by kubawerlos** [comment]
I was fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5660.
