### ISSUE TITLE
3.0.0 method_argument_space removing extra newlines

### ISSUE THREAD

**Issue by donatj** [FriendsOfPHP/PHP-CS-Fixer#5676]
## Bug report

Upgrade to php-cs-fixer 3.0.0 and `method_argument_space` now removes _extra newlines_ from methods.

We use them a fair bit to separate types of arguments.

### Code snippet that reproduces the problem

For instance

```php
	public function newAction(
		AccountMapper $accountMapper,
		GeoStateMapper $geoStateMapper,

		BuildBuildingURLCommand $buildBuildingURLCommand,

		array $GET,
		array $INPUT
	) { … }
```
is transformed into

```php
	public function newAction(
		AccountMapper $accountMapper,
		GeoStateMapper $geoStateMapper,
		BuildBuildingURLCommand $buildBuildingURLCommand,
		array $GET,
		array $INPUT
	) { … }
```

**Comment by keradus** [comment]
it's by purpose, pls check the Upgrade Guide, especially changes to default configuration of rules: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md#changed-default-values-of-options

you may also change the configuration to use config that was a default at 2.x
