### ISSUE TITLE
Wrong deprecation message

### ISSUE THREAD

**Issue by OskarStark** [FriendsOfPHP/PHP-CS-Fixer#5677]
## Bug report

> - Configuration file `.php-cs-fixer.dist.php` is deprecated, rename to `.php-cs-fixer.dist.php`.

### Code snippet that reproduces the problem

I am using 2.19.0 and renamed my file, looks like sth is wrong with the deprecation message 🤔

**Comment by keradus** [comment]
can you provide more details or repo where one can observe this issue?

ad hoc, i struggle to reproduce:
```
ker@dus:~/github/PHP-CS-Fixer λ ll .php*
-rw-rw-r-- 1 d.ruminski d.ruminski    1817 May  4 11:01 .php-cs-fixer.dist.php

ker@dus:~/github/PHP-CS-Fixer λ PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer fix -vvv src/Console/Application.php 
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.3
Loaded config default from "/home/d.ruminski/github/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
.                                                                                                                                                                                                                                                                     1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.062 seconds, 14.000 MB memory used
```

**Comment by OskarStark** [comment]
Oh I do not use `PHP_CS_FIXER_FUTURE_MODE=1`, maybe this is the problem? 🤔

**Comment by keradus** [comment]
I run the command without the FUTURE mode and it worked the same, I still struggle to reproduce. can you give steps / repo example to reproduce? including the command you run and config you have

**Comment by SpacePossum** [comment]
Closing as there is not enough information to continue on, let me know if this should be reopened when it can be worked on :+1:
