### ISSUE TITLE
Can version 3.0 support composer/xdebug-handler v1 and v2

### ISSUE THREAD

**Issue by hostep** [FriendsOfPHP/PHP-CS-Fixer#5682]
## Bug report

Hi folks

I'm trying to update php-cs-fixer to version 3 on an open source magento2 module.
Magento2 however, has a dependency on `composer/composer` which (in the latest version at the time of writing, 2.0.13) has a dependency on `composer/xdebug-handler` with constraint `^1.1`.
Since php-cs-fixer version 3 has changed the constraint for `composer/xdebug-handler` from `^1.4` to `^2.0` [over here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/3cc811deea8d2da55ce936de49ab0f0c128bcf25), we can currently not upgrade php-cs-fixer to version 3.

I would suggest you change your constraint to `^1.4 || ^2.0` which would allow one of both versions to get installed and used.

Are there any objections to this?

Thanks!

### Code snippet that reproduces the problem

1. Clone the `v1-develop` branch from https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker
2. Run `composer install`
3. Run `composer require friendsofphp/php-cs-fixer:"^3.0"`
4. See the following error:

```
  Problem 1
    - Root composer.json requires friendsofphp/php-cs-fixer ^3.0 -> satisfiable by friendsofphp/php-cs-fixer[v3.0.0].
    - friendsofphp/php-cs-fixer v3.0.0 requires composer/xdebug-handler ^2.0 -> found composer/xdebug-handler[2.0.0] but the package is fixed to 1.4.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

**Comment by julienfalque** [comment]
I would argue that PHP CS Fixer shouldn't be part of your module's dependencies in the first place: it's a tool for your project, not something your code actually rely on. There are several better ways to install PHP CS Fixer. The recommended one is to [use a dedicated `composer.json`](https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation).

**Comment by hostep** [comment]
Thanks @julienfalque 

Makes a lot of sense indeed!

However, with this approach I would need to maintain 2 different composer dependency trees per project, which is a little less user friendly.
And especially if we would start doing this with all our other development dependencies in this module or our other projects, then it would escalate rather quickly.

**Comment by julienfalque** [comment]
I do that for most projects I work on and it actually reduces the maintainance burden IMO. Sure, you need to run multiple `composer update` to have everything up-to-date, but then you never have to solve tools' dependencies conflicts such as the one you report here, and conflicts in your own dependencies are less frequent and easier to solve.

On the other hand, making tools as much compatible with all versions of their dependencies as possible would be a much bigger burden for tools contributors. This is quite visible regarding Symfony components in PHP CS Fixer for example: every two years someone requests PHP CS Fixer to be compatible with the latest version while it should remain an internal detail implementation of the tool.

**Comment by hostep** [comment]
Okay, you are convincing me 🙂 

Let's close this issue then

Thanks for the feedback!
