### ISSUE TITLE
Using the PHP file in [vendor dir]/[composer namespace]/php-cs-fixer instead of Unix/Windows script

### ISSUE THREAD

**Issue by DocFX** [FriendsOfPHP/PHP-CS-Fixer#5700]
## Support question

Hello,

Recently a non-backwards compatible change was made from composer + this repo: [](https://getcomposer.org/doc/articles/vendor-binaries.md) composer generates upon install command Unix + Windows binaries in the bin directory of current composer installation (global or local). Default is `vendor/bin`.

There used to be a PHP script generated by `composer install` for php-cs-fixer in that directory, now there's none anymore.

I'm calling php-cs-fixer through a path-specific PHP executable (on Windows, by the way) on a machine that has several PHP binaries. 

So I was doing something like:

`"path/to/php.exe" "path/to/vendor/bin/php-cs-fixer" analyse [options]`

This script used to be PHP, now it's plain Unix script. So I updated the scripts with:

`"path/to/php.exe" "path/to/vendor/bin/friendsofphp/php-cs-fixer" analyse [options]`

**Question: is this sustainable, and the best way to do so? (I can also call it from containers, which is another story ^^)**

I don't know if we can generate PHP scripts in the bin directory anymore.

**Comment by keradus** [comment]
Hey, we didn't check anything on our side. Please check with Composer whether they done any changes.
Also, not sure if you raised the concern at tool you wanted too, as we don't have `analyse` command.

**Comment by DocFX** [comment]
I don't think you understood me. I'm quite in a hurry today. I'll try to explain it better. :)

Up to last week: 
- composer update for latest php-cs-fixer version: vendor/bin/php-cs-fixer is a PHP script

Currently:
- composer update for latest php-cs-fixer version: vendor/bin/php-cs-fixer is a SHELL script

What I'm saying is that calling php-cs-fixer just changed. I think we should be worried about that, but that's another story.

So my question (it's a question) is: **is it OK to use directly the PHP script in `path/to/vendor/bin/friendsofphp/php-cs-fixer`?**

(also, yeah, I'm not using this option, the full command doesn't matter, I'm using `fix --show--progress dots --verbose --config=[config path]` for the record)

**Comment by keradus** [comment]
> So my question (it's a question) is: is it OK to use directly the PHP script in path/to/vendor/bin/friendsofphp/php-cs-fixer?

I don't think the entry file for the package will change name, so calling it from package folder rather than `vendor/bin` should be fine.
In fact, under unix the file in `vendor/bin` is only a symlink
```
ker@dus:/tmp/123qsa/ λ ls -al vendor/bin/php-cs-fixer 
lrwxrwxrwx 1 d.ruminski d.ruminski 41 May  7 17:28 vendor/bin/php-cs-fixer -> ../friendsofphp/php-cs-fixer/php-cs-fixer
```

**Comment by DocFX** [comment]
It does copy a file, hence the tricky behaviour, you can look at Jordi's answer in the linked issue. :)
It's not a PHP script anymore, its a real Unix shell script, which calls your PHP main entry.

https://github.com/composer/composer/issues/9871

Thanks a lot @keradus, for your answer and for this tool, once again! \o/
