### ISSUE TITLE
no_unused_imports does not remove an unused import if the class name is in a (irrelevant) comment

### ISSUE THREAD

**Issue by ABSAhmad** [FriendsOfPHP/PHP-CS-Fixer#5705]
## Bug report

   * PHP version: PHP 8.0.3
   * PHP CS Fixer version: 3.0.0 Constitution (also tested with the latest 2 version which leads to the same problem)
   * the command used to run PHP CS Fixer (run with `-vvv`):

```
Loaded config default from "/<redacted>/.php-cs-fixer.php".
..                                                                                                                         2 / 2 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.006 seconds, 12.000 MB memory used
```

### Code snippet that reproduces the problem

With the following class:

```php
<?php

use Unused;

final class Test
{
    public function __construct()
    {
        /*
         Some comment includes the word unused
        */
    }
}
```

My expectation would be that the `use Unused;` import gets removed but because the word `unused` is used inside a comment even though it's not tagged with `@var` or `@param` so should not be considered as a "use".

For easier reproduction, I've also created a repository that includes the snippets to re-produce the problem https://github.com/ABSAhmad/cs-fixer-unused-use-bug/

When running the `./php-cs-fixer fix -vvv` it states that there were no changes, even though the import `use Unused` inside of `Test.php` should be removed.

**Comment by julienfalque** [comment]
Yes, this is a known issue, see #2814.

**Comment by ABSAhmad** [comment]
Alright, thanks. Weirdly I couldn't find it when I searched for it but good to know 👍
