### ISSUE TITLE
DX: mention new-style-method calls instead of just erroring on the old one in PHP_CS_FIXER_FUTURE_MODE

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#5714]
## Feature request
when using future mode I run into the error:

```
$ PHP_CS_FIXER_FUTURE_MODE=1 vendor/bin/php-cs-fixer fix

In Utils.php line 197:

  PhpCsFixer\Config::create is deprecated since 2.17 and will be removed in 3.0. This check was performed as `PHP_CS_FIXER_FUTURE_MODE` env var is set.


fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [-[--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
```

the upgrade guide tells me that I should use the constructor instead.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/c30fcc75916272dd7bcd99cc489e433901faddb2/UPGRADE-v3.md#L158

it would be great to get the hint on what to use instead already in the CLI when using future mode.
additionally it would be helpful to get a link to the upgrade guide from the CLI - or at least mention that a upgrade guide exists

**Comment by julienfalque** [comment]
Error messages improved in #5746.
