### ISSUE TITLE
Remove "use_arrow_functions" from any ruleset

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5719]
## Feature request

Arrow functions can introduce a lot of mistakes, decreate readability and thus decrease the total code quality. This is a feature request to remove them from `@PHP74Migration:risky` until it is too late.

It should be the developer choose to use arrow function or not.

**Comment by kubawerlos** [comment]
> can introduce a lot of mistakes

such as?

> decreate readability

funny, [RFC](https://wiki.php.net/rfc/arrow_functions_v2) introducing it mentions "closures hard to read and understand"

> It should be the developer choose to use arrow function or not.

and it is, anyone can always disable it.

**Comment by mvorisek** [comment]
Example: https://github.com/atk4/data/compare/1dd3200

Without "use_arrow_functions" it is much more obvious where a `\Closure` is created because of body on new lines.

**Comment by kubawerlos** [comment]
> because of body on new lines

then add new lines back, so arrow function is in separate line. You claim that the code split into 3 lines in more readable than when it's in single line - of course it is.

> So in my opinion, this should be not enabled by default.

In the opinion of the person who added it to `PHP74Migration:risky` it is the opposite and I agree with it.

**Comment by julienfalque** [comment]
Your example seems a bit dishonest to me: using arrow functions does not require to remove newlines, so you could keep something like:

```php
array_map(
    fn ($row) => array_map(
        fn ($v) => $this->getCastValue($v),
        $row
    ),
    $rows
)
```

which I do find slightly easier to read than  

```php
array_map(function ($row) {
    return array_map(function ($v) {
        return $this->getCastValue($v);
    }, $row);
}, $rows)
```

> Autobounding variables decreases code quality as a lot of typos can be overseen.

Using regular anonymous functions does not prevent you from doing typos either. You should rely on static analysis tools and/or tests rather than a specific code style to prevent such errors.

**Comment by mvorisek** [comment]
> Your example seems a bit dishonest to me:

I only applied the rule, this is what almost everyone do :)

**Comment by keradus** [comment]
Closing due to discussion.
We aim to promote best practices and new syntax, yet if anyone doesn't like part of it, they can always disable the rule for their projects
