### ISSUE TITLE
native_function_invocation is prepending slashes to all repeated attributes except for the first use

### ISSUE THREAD

**Issue by davidbyoung** [FriendsOfPHP/PHP-CS-Fixer#5722]
## Bug report

When you have multiple attributes, the 2nd, 3rd, etc attributes are prepended with a `\` when using `^3.0` of PHP-CS-Fixer.

```php
return (new PhpCsFixer\Config())
    ->setRules([
        'native_function_invocation' => ['include' => ['@all']]
    ])
    ->setRiskyAllowed(true)
    ->setFinder(
        PhpCsFixer\Finder::create()->in(__DIR__)
    );
```

This is being invoked with:

```bash
php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --diff
```

### Code snippet that reproduces the problem

```php
<?php
namespace Foo
{
    use Attribute;

    #[Attribute(Attribute::TARGET_CLASS, Attribute::IS_REPEATABLE)]
    class FooAttribute {}
}

namespace Bar
{
    use Foo\FooAttribute;

    #[FooAttribute(), FooAttribute()]
    class Bar {}
}
```

Running the fixer will result in:

```php
<?php
namespace Foo
{
    use Attribute;

    #[Attribute(Attribute::TARGET_CLASS, Attribute::IS_REPEATABLE)]
    class FooAttribute {}
}

namespace Bar
{
    use Foo\FooAttribute;

    #[FooAttribute(), \FooAttribute()]
    class Bar {}
}
```

Notice that `FooAttribute` is escaped on the 2nd instance.  I reproduced this locally in a unit test, and I believe it's because the second `FooAttribute` is not being picked up on as a possible attribute on [this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/src/Tokenizer/Token.php#L400) because the previous token was a `,`, not `#[`.

**Comment by davidbyoung** [comment]
I've updated the example and some insights from a unit test that reproduces the issue.  I am still trying to work my way through the internals to understand how we can make it more context aware.

**Comment by kubawerlos** [comment]
@davidbyoung take a look at the PR ☝🏼 .
