### ISSUE TITLE
Sublime Text 3 sublime-phpcs package  --using-cache=off is getting an error it should be "on" or "off

### ISSUE THREAD

**Issue by skeeith** [FriendsOfPHP/PHP-CS-Fixer#5723]
## Bug report

  Before reporting a bug, make sure PHP CS Fixer is up-to-date.

  Please describe the problem and provide technical details such as:
   * PHP version: 8.0.6
   * PHP CS Fixer version: 3.0.0
   * the command used to run PHP CS Fixer (run with `-vvv`)
   ```
   In ConfigurationResolver.php line 831:

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  Expected "yes" or "no" for option "using-cache", got "off".


Exception trace:
  at C:\Users\gethe\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:831
 PhpCsFixer\Console\ConfigurationResolver->resolveOptionBooleanValue() at C:\Users\gethe\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:448
 PhpCsFixer\Console\ConfigurationResolver->getUsingCache() at C:\Users\gethe\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php:274
 PhpCsFixer\Console\Command\FixCommand->execute() at C:\Users\gethe\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:256
 Symfony\Component\Console\Command\Command->run() at C:\Users\gethe\AppData\Roaming\Composer\vendor\symfony\console\Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\gethe\AppData\Roaming\Composer\vendor\symfony\console\Application.php:290
 Symfony\Component\Console\Application->doRun() at C:\Users\gethe\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Application.php:97
 PhpCsFixer\Console\Application->doRun() at C:\Users\gethe\AppData\Roaming\Composer\vendor\symfony\console\Application.php:166
 Symfony\Component\Console\Application->run() at C:\Users\gethe\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\php-cs-fixer:113
   ```
   * the configuration (file) you used: using a Sublime Text 3 `.phpcsfixer` file
   ```
   return PhpCsFixer\Config::create()->setRules([
    '@PSR1'             => true,
    '@PSR2'             => true,
    'array_syntax'      => [
        'syntax' => 'short'
    ],
    'no_unused_imports' => true
]);
   ```
   
   I'm using Sublime Text 3 `SublimeLinter-PHPCSFixer` package to auto initial this.
   Can you guys add support for legacy "on" and "off" options?

**Comment by kubawerlos** [comment]
> legacy "on" and "off" options

What do you mean? When "on" was option to enable cache? Hint: never, "off" was "working" because in v2 anything except "yes" was resulting with not using cache.

This was deprecated in [2007](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2707), so the package you using had plenty of time to update.

**Comment by skeeith** [comment]
@kubawerlos that's weird cause this was still working last month using v2, it started to spit errors when I updated to v3.  let me check on the Sublime Text 3 package.

**Comment by keradus** [comment]
@skeeith , it was deprecated in v2 and forbidden in v3. that's how major version bump work ;)

**Comment by skeeith** [comment]
@keradus thanks for the heads up man, I'll bring this up to the devs of sublime text part package.
