### ISSUE TITLE
Config with custom ruleset is used even if built-in rule is set for usage in run command

### ISSUE THREAD

**Issue by isfedorov** [FriendsOfPHP/PHP-CS-Fixer#5724]
Create some project and put old-style `.php_cs` config file to the root of project
Install php-cs-fixer v3 using composer like
```
{
  "require": {
    "friendsofphp/php-cs-fixer": "v3.0.0"
  }
}
```
Try to run cs-fixer with built-in ruleset with command like `./vendor/bin/php-cs-fixer fix a.php --rules=@Symfony`
Result:
cs-fixer still will try to read custom ruleset config and will throw an error 
```
In ConfigurationResolver.php line 226:
                                                                            
  Configuration file `.php_cs` is outdated, rename to `.php-cs-fixer.php`.  
                                                                            
```
Expected result:
As far as built-in ruleset is set for analyzes the error should not be shown

**Comment by SpacePossum** [comment]
Hi and thanks for sharing,
The tool gets more configuration from the config file than the rules, as such it will always try to see if there is a config file. The detection of the old style config file is to help people when migrating. I think the scenario you describe effects few people and is better resolved by the user than tried to be handled by the tool, the user knows best what should happen with the old config file, as such I'm closing here.
