### ISSUE TITLE
Add back symfony/* v3.4 support

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5726]
## Feature request

Support removed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/b6a5045e0b9d5ffd19de0efc8a5cd24f72c10b94, but symfony/* v3.4 is LTS and should be still supported as easily compatible.

**Comment by julienfalque** [comment]
I'm definitely against this: Symfony components are an internal implementation detail of PHP CS Fixer. If you don't want conflicts with your own dependencies, [don't install PHP CS Fixer as a dependency of your own code](https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation). Supporting that would create an artificial maintainance burden here.

**Comment by mvorisek** [comment]
Really? What conflicts and extra maintainance?

**Comment by julienfalque** [comment]
If we want to "support" old Symfony versions, we cannot use newer features, or we have to use them conditionnaly, e.g.
```
if ($oldSymfony) {
    oldWayOfDoingStuff();
} else {
    newWayOfDoingStuff();
}
```
If we know we can only have a more recent version, then we don't need those conditions so we can simplify our code. This applies to any dependency. The wider the version ranges, the bigger the maintainance work.

Now the only reason to widen ranges is to allow installation along with other packages that do require e.g. an old version of Symfony components, which is plain wrong IMO: PHP CS Fixer is a tool, your code doesn't need it to run. Again, dependencies of such a tool should remain an internal implementation detail.

Also, Symfony 3.4 is not maintained anymore.

**Comment by mvorisek** [comment]
Symfony 3.4 receives security fixes until Nov 2021 and is clearly the most downloaded version now - https://packagist.org/packages/symfony/symfony/stats

I understand your conditioning, but AFAK there is zero or a very few needed.

> Now the only reason to widen ranges is to allow installation along with other packages that do require e.g. an old version of Symfony components, which is plain wrong IMO: PHP CS Fixer is a tool, your code doesn't need it to run. Again, dependencies of such a tool should remain an internal implementation detail.

Big projects **should** actually require PHP CS Fixer tool directly that is also how a lot of projects (I guess 50%) use it.

**Comment by kubawerlos** [comment]
> Big projects **should** actually require PHP CS Fixer tool directly

Really? Please explain why "should"?

> a lot of projects (I guess 50%) use it.

What is that number from? Are you guessing it to make your point - that's really weak argument.

**Comment by mvorisek** [comment]
> Really? Please explain why "should"?

Because even CS should be versioned (lockable with `composer.lock`)

> > a lot of projects (I guess 50%) use it.

You can browse https://packagist.org/explore/popular and see which projects include this tool in `require-dev`. This option is in the composer exactly for these dev tools :)

**Comment by kubawerlos** [comment]
> Because even CS should be versioned (lockable with `composer.lock`)

Of course it should, but not necessarily via composer.json/composer.lock in project's root - may be different composer.json or PHAR.

> You can browse https://packagist.org/explore/popular and see which projects include this tool in `require-dev`.

Same as above, it does not consider e.g. the usage via [`dev-tools`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v2.5.0/dev-tools/composer.json#L6).

And as Julien said, "don't install PHP CS Fixer as a dependency of your own code", so simply don't do it ;)

**Comment by julienfalque** [comment]
> Because even CS should be versioned (lockable with `composer.lock`)

I totally agree here, this is why I usually use a separate `composer.json` file, as suggested in out installation instructions.
