### ISSUE TITLE
Blank line between class methods

### ISSUE THREAD

**Issue by designermonkey** [FriendsOfPHP/PHP-CS-Fixer#5743]
Is there a rule that will enforce a blank line between class methods?

```
<?php declare(strict_types=1);

class Test
{
    public function test()
    {
    }
    protected function another()
    {
    }
    private function again()
    {
    }
}
```
changes to 
```
<?php declare(strict_types=1);

class Test
{
    public function test()
    {
    }

    protected function another()
    {
    }

    private function again()
    {
    }
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for your question,

The rule you are looking for is called `class_attributes_separation`, please check the docs for details about it [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.19.0/doc/rules/class_notation/class_attributes_separation.rst)
