### ISSUE TITLE
`native_constant_invocation` and pnctl constants on Windows

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5762]
## Bug report

`pnctl` ext is unix only ext.

With `native_constant_invocation` rule enabled, the CS Fixer removes FQ backslashes before constants like `SIGTERM` on Windows, but in linux/CI, constants are added back.

I submit this as a bug, as unix ext only can not be installed on Windows and the https://www.php.net/manual/en/pcntl.constants.php constants should be integrated into CS Fixer directly to produce stable results on both platforms.

**Comment by mvorisek** [comment]
Solved by:

```
        'native_constant_invocation' => [
            'include' => ['SIGHUP', 'SIGINT', 'SIGQUIT', 'SIGKILL', 'SIGTERM'],
        ],
```

maybe worth to pursue by dumping all constants from php-src, otherwise this will always be a compromise, however I have no resources to do so.

**Comment by SpacePossum** [comment]
Hi!
Not sure how this can be fixed, we always assume that the fixer is run in an environment functionally the same as the code it is fixing. So same PHP version and extensions enabled. The added complexity to support fixing for different environment than running the fixer on is something we cannot add to this project I think.
