### ISSUE TITLE
Version 3.0.0 thow exception The "--diff-format" option does not exist.

### ISSUE THREAD

**Issue by netandreus** [FriendsOfPHP/PHP-CS-Fixer#5766]
## Bug report

   * PHP version: PHP 7.4.20 (cli) (built: Jun  3 2021 21:55:37) ( NTS )
   * PHP CS Fixer version: 3.0.0
   * OS: Debian GNU/Linux 10

### Code snippet that reproduces the problem

I'am using php-cs with PHPStorm 2020.3. When php-cs runs code analysis this error occures in PhpStorm log.

```
17:23	PHP CS Fixer
PHP CS Fixer: 
In ArgvInput.php line 201:
[Symfony\Component\Console\Exception\RuntimeException]  
The "--diff-format" option does not exist.              
Exception trace:
at /current/vendor/symfony/console/Input/ArgvInput.php:201
Symfony\Component\Console\Input\ArgvInput->addLongOption() at /current/vendor/symfony/console/Input/ArgvInput.php:143
```

**Comment by julienfalque** [comment]
The `--diff-format` has been removed in version 3.0, the format is always `udiff` now. See [UPGRADE-v3.md](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md#cli-options).

**Comment by netandreus** [comment]
Final solution is:
1. upgrade friendsofphp/php-cs-fixer to ^3.1.0
2. upgrade PHPStorm to 2021.2.1
3. rename .php_cs.dist to .php-cs-fixer.dist.php and  update path it in PHPStorm settings
4. replace ```$config = PhpCsFixer::Config()``` to  ```$config = new PhpCsFixer\Config()```
5. restart PHPStorm and reindex project
