### ISSUE TITLE
Configuration file .php_cs.dist is outdated, rename to `.php-cs-fix.dist

### ISSUE THREAD

**Issue by jasperf** [FriendsOfPHP/PHP-CS-Fixer#5770]
Configuration file .php_cs.dist is outdated, rename to `.php-cs-fixer.dist.php`. So I did. Now I get:
```
Cannot read config file ".php_cs.dist".
```

So which one is it?

**Comment by jasperf** [comment]
Tried `.php_cs` but then I got 

```
In ConfigurationResolver.php line 508:
                                           
  Cannot read config file ".php_cs.dist".  
                                           
```

again.

**Comment by jasperf** [comment]
Changed `.github/workflows/php-cs-fixer.yml` and now I have this error:


```
Fatal error: Uncaught Error: Call to undefined method PhpCsFixer\Config::create() in /github/workspace/.php-cs-fixer.dist.php:142
```

**Comment by jasperf** [comment]
Using this configuration for Laravel now https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200#gistcomment-3755709 and that seems to work.

**Comment by martinharder** [comment]
I have the same issue with sc-fixer version 3.1.0 in symfony.
No matter what file name I use, it doesn't work :(

**Comment by SpacePossum** [comment]
can you share the command you run and the output of the tool? please run with `-vvv` so we get most details

**Comment by martinharder** [comment]
I fixed the issue. It was a PHPStorm issue. External Tools was not accepting the settings and used always the deprecated file name `.php_cs.dist`.
