### ISSUE TITLE
CI: Code Style check failed ?!

### ISSUE THREAD

**Issue by juliusdev** [FriendsOfPHP/PHP-CS-Fixer#5772]
## Support question

Hi,

I'm trying to perform code style check in my Gitlab CI pipeline. 
First I created a job to check the code :

Output on Gitlab Runner :
````
php-cs-fixer fix -v --dry-run
PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.2.0
Loaded config default from "/app/.php-cs-fixer.php".
.........................F.FF........................................................................  101 / 2141 (  5%)
.FFFFFFFF...F......F.F.....F.....................S...................................................  202 / 2141 (  9%)
````
It run in a docker image with PHP 7.2.0.

When I format the code on my local repository and push it to gitlab.

Output php-cs-fix on my local machine :
```
php ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --verbose --show-progress=dots

PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.7
```

Here I expected to have no fix detected. But the ci job has detected many errors and failed. Any idea ?

most fixes are on : braces, method_argument_space

Config
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude(['SwaggerClient-php','vendor'])
    ->ignoreVCSIgnored(true)
    ->files()->name('*.php')
    ->ignoreDotFiles(true)
    ->in(__DIR__)
;

$config = new PhpCsFixer\Config();
return $config->setRules([
        '@PSR2' => true,
        'braces' => ['position_after_functions_and_oop_constructs' => 'same'],
        'strict_param' => false,
    ])
    ->setUsingCache(false)
    ->setFinder($finder)
;
```

**Comment by kubawerlos** [comment]
HI @juliusdev, can you share some code diff (run the command with `--diff`)?

Without it I'd guess 2 possible reasons:
- when PHP CS Fixer is introduced to a new project and makes a lot of changes the priority issue could hit - there are some cases where FixerA must run before FixerB for some code and FixerB must run before FixerA for other code - and PHP CS Fixer is not supporting this (yet?) - running `fix` command multiple times (without cache or with removing cache between runs) is needed in that scenario
- some fixers are run only for specific PHP versions, but usually for PHP greater that some version and you have the opposite situation, but this is still possible

**Comment by keradus** [comment]
yep, choose base line for your project, if you can run the project on 8.0, i would strongly recommend to run the CI on 8.0 as well.
