### ISSUE TITLE
Add a variable casing fixer

### ISSUE THREAD

**Issue by SuperDJ** [FriendsOfPHP/PHP-CS-Fixer#5786]
## Rule request

A fixer for consistent variable casing. This should be configurable with `snake_case` and `camel_case`.

- Change variable casing in code;
- Change variable casing in comments/ docblocks;
- Is considered risky;

### Code snippet that shows how the rule would fix PHP code
Turning 
```php
$fooBar = 'baz';
```
into
```php
$foo_bar = 'baz';
```
with config `snake_case` and vice versa for `camel_case`

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your idea,

I think a proposal for this has been done here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5097

**Comment by SuperDJ** [comment]
@SpacePossum I think it is yes.

**Comment by keradus** [comment]
Then, let me close this one as duplicate ;)
