### ISSUE TITLE
Add consistent variable numbers fixer

### ISSUE THREAD

**Issue by SuperDJ** [FriendsOfPHP/PHP-CS-Fixer#5787]
## Rule request

Add a consistent variable number fixer. This should be configurable with something like `integer` and `spellout` matching [predefined constants](https://www.php.net/manual/en/class.numberformatter.php).

- Change variables in code;
- Change variables in comments and docblocks;
- Is considered risky;
- Should run before #5786  (if that is added);

### Code snippet that shows how the rule would fix PHP code

Config: `integer` turns
```php
$participant_one = 'John';
```
into
```php
$participant_1 = 'John';
```
and `spellout` would do the same vice versa.

**Comment by keradus** [comment]
Hi and thanks for your request.

Is this part of a standard or used by a bigger (F)OSS community? For us that is a condition to add a rule to this project. Otherwise, you can create a custom fixer and use that in your projects. Thanks for understanding.

**Comment by SuperDJ** [comment]
@keradus in that case I guess this should become a custom fixer
