### ISSUE TITLE
Prevent new line before the class opening braces (similar to function/methods  and control blocks)

### ISSUE THREAD

**Issue by salarmehr** [FriendsOfPHP/PHP-CS-Fixer#5795]
I need the following style
```
class Foo {
  public function bar {
  }
}
```
But it's changed to which does add more scrolling without increasing readability. 
```
class Foo
{
  public function bar {
  }
}
```
How can I prevent modifying this or even better ask it to convert the latter to the former?

**Comment by kubawerlos** [comment]
> more scrolling without increasing readability

I'd say it's personal opinion, most people think differently and want to have linebreak before that opening brace.

To prevent adding this linebreak run the fixer with `-v` to see which rule adds it (most likely `brace`) and disable that rule.

To remove it I would advise creating custom fixer.

**Comment by salarmehr** [comment]
I find the answer to my question here 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/basic/braces.rst#position_after_functions_and_oop_constructs

It's so great that we can use One True Brace Style (1TBS) styles for both functions and classes.
