### ISSUE TITLE
Allow `class_attributes_separation` to remove empty lines from interface methods

### ISSUE THREAD

**Issue by xorik** [FriendsOfPHP/PHP-CS-Fixer#5800]
## Rule request

It would be nice if rule `class_attributes_separation` with `['elements' => ['method' => 'one']]`, have an exception for interfaces. So interfaces won't have empty lines between methods.

### Code snippet that shows how the rule would fix PHP code
E.g. before:
```php
<?php

interface A
{
    first(): string;

    second(): int;
}
```
after:
```php
<?php

interface A
{
    first(): string;
    second(): int;
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your idea,

TBH I think there shouldn't be exception based on the classy type like class vs interface vs trait, but more something like this https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5704 so you can configure the rule to act to make the changes as your snippet shows.

**Comment by xorik** [comment]
@SpacePossum 
Sounds good to me. Yes, it shouldn't be connected to interfaces only. I would say it should be possible to remove spaces between any body-less functions. E.g.
```php
<?php
class Baz
{
    abstract function foo();
    abstract function bar();
}
```

**Comment by paulbalandan** [comment]
@SpacePossum I think this can be closed based on your comment https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5704#issuecomment-889736362

**Comment by SpacePossum** [comment]
thanks, I think so as well :) @xorik please checkout the PR of @paulbalandan , changes will also be part of the next releases  :+1:

**Comment by xorik** [comment]
@SpacePossum sorry, I cannot see how mentioned PR fixed my issue 😞

**Comment by SpacePossum** [comment]
can you explain what didn't work when using the code as changed by the PR?

**Comment by xorik** [comment]
I want one empty line between methods with body, and zero empty lines for interfaces (methods without body). E.g:
```php
<?php

// No lines between methods for interfaces
interface A {
    function a();
    function b();
}

// One line between methods for classes
class B implements A
{
    function a()
    {
    ...
    }

    function b()
    {
    ...
    }
}
```

The mentioned PR is about adding empty line if there is a comment before method/property. E.g.
```php
<?php 

class Sample
{
    /** @var int */
    const FOO = 1;

    /** @var int */
    const BAR = 2;

    #[Foo\Baz]
    const BAZ = 3;

    const OTHER = 4;
    const OTHER2 = 5;
}

So it will be the same amount of empty lines in both cases (regardless if there is a body for method or not)

**Comment by SpacePossum** [comment]
can you share the configuration you used on the first example?

**Comment by xorik** [comment]
There is no configuration for that code style. This is what I want to achieve, that's why I created this issue

**Comment by SpacePossum** [comment]
The PR adds a new configuration that was not available when you created the issue, that is why I asked it. If you don't try the with the new PR we cannot know if you issue is still valid.

**Comment by xorik** [comment]
Sorry for the delay. Here's demo:
https://github.com/xorik/cs-fixer-interfaces

You can see with default ruleset for `class_attributes_separation`, it adds an empty line between methods in both cases.

If you look at this branch: https://github.com/xorik/cs-fixer-interfaces/tree/only-meta you can see that I've added
```
'class_attributes_separation' => ['elements' => ['property' => 'only_if_meta']],
```

Now it allows me to remove the line between methods in interface, BUT it also allows to remove line between methods in classes. Which I want to prevent.

So I want to force 1 line between methods with body (for classes), but allow no lines between interface methods.

I hope it's clear.

**Comment by SpacePossum** [comment]
I would try with the option `none` after the next release, given what was patched yesterday. 

Besides that, the logic is not based on `interface` vs `class` or something. We'll also not add this, so please try with option `none` after next release and if it still doesn't do what you want you might have to write a custom fixer yourself for your project.

**Comment by xorik** [comment]
@SpacePossum 
Ok, thanks!
As I said it might be not based on intrface VS class, but based on method with body VS method without body (so for example I can have lot of abstract methods in class).
