### ISSUE TITLE
One-line comments with header_comment

### ISSUE THREAD

**Issue by a-menshchikov** [FriendsOfPHP/PHP-CS-Fixer#5803]
It would be nice if `header_comment` will support adding one-line comments. First of all it will be useful, when you use the [SPDX IDs](https://spdx.dev/ids/) instead of multiline comments for licence purposes.

**Comment by kubawerlos** [comment]
@a-menshchikov something like this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5805?

**Comment by a-menshchikov** [comment]
@kubawerlos yes.
