### ISSUE TITLE
Outdated website

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#581]
The website at http://cs.sensiolabs.org/ is expected to be built usign the readme as source. But it is currently totally outdated. And it does not correspond to the latest stable release either (it is newer).

IMO, there is only 2 meaningful behaviors:
- updating the site only for stable releases.
- updating the site automatically to the latest version.

**Comment by gharlan** [comment]
At the moment http://cs.sensiolabs.org/ shows an outdated version of master branch. That's confusing.
It should show the README of 1.11.

**Comment by keradus** [comment]
it is already requested to show latest stable release.

**Comment by fabpot** [comment]
website updated.

**Comment by stof** [comment]
@fabpot is this automated, or will the same issue happen on each release ?
