### ISSUE TITLE
`yoda_style` rule and `yield` keyword

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#5810]
### Code snippet that reproduces the problem

```php
$fn = static function ($a, $b): Generator {
    return yield $a === $b;
};
```

When the rule `yoda_style` is enabled, it tries to update it as such and it should not:

```php
$fn = static function ($a, $b): Generator {
    return $a === yield $b;
};
```

**Comment by drupol** [comment]
I made a draft PR, but I'm unsure about the fix, some assistance is welcome there.

**Comment by keradus** [comment]
@drupol @SpacePossum , can you confirm #5823 is fixing this issue?

**Comment by SpacePossum** [comment]
yeah should be good now :)  ping me if not @drupol :+1:

**Comment by drupol** [comment]
Thank you it's perfect!
