### ISSUE TITLE
`phpdoc_tag_type` destroys inline `{@see Foo}` annotations when used in `@internal` annotation

### ISSUE THREAD

**Issue by boesing** [FriendsOfPHP/PHP-CS-Fixer#5815]
## Bug report

* PHP version: PHP 8.0.8 (cli) (built: Jul 12 2021 11:13:36) ( NTS )
* PHP CS Fixer version: PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
* the command used to run PHP CS Fixer (run with `-vvv`): vendor/bin/php-cs-fixer -vvv fix --dry-run --diff
* the configuration (file) you used
```php
<?php

$config = new PhpCsFixer\Config('foo');
$config->setRules(['phpdoc_tag_type' => true]);
$config->setUsingCache(false);

$config->getFinder()->in(__DIR__);

return $config;
```

### Code snippet that reproduces the problem

  ```php
<?php

namespace Bar;

use JsonSerializable;

/**
 * @internal Foo Bar {@see JsonSerializable}
 */ 
class Baz
{}
  ```

```
      ---------- begin diff ----------
--- /Users/max/bar/test.php
+++ /Users/max/bar/test.php
@@ -5,7 +5,7 @@
 use JsonSerializable;
 
 /**
- * @internal Foo Bar {@see JsonSerializable}
+ * @internal Foo Bar {@see JsonSerializable
  */ 
 class Baz
 {}

      ----------- end diff -----------
```

**Comment by keradus** [comment]
nice finding, @boesing !
can you open a fixing PR, please?

**Comment by boesing** [comment]
Will try in the next days. Not sure if I have time to acquire enough knowledge to fix the bug as I definitely dont have any experience with the lexer.
