### ISSUE TITLE
braces rule causes `else if` structure to be broken into multiple lines + brace depth

### ISSUE THREAD

**Issue by th3coop** [FriendsOfPHP/PHP-CS-Fixer#5820]
I'll admit that I'm not 100% sure this IS a bug but the reasons I think it is:
1. it doesn't seem like an effect that the rule should have
1. I can't turn it off (or if I can, see point 1 in that I can't tell how I'm supposed to turn it off)

## Bug report
  Please describe the problem and provide technical details such as:
   * PHP version: php -v
     * PHP 7.4.12  
   * PHP CS Fixer version: php-cs-fixer -V
     * PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski (c15377b)
   * the command used to run PHP CS Fixer (run with `-vvv`)
     *  ` php  php-cs-fixer.phar fix path\to\file.php`
   * the configuration (file) you use
     * [php-cs-fixer.txt](https://github.com/FriendsOfPHP/PHP-CS-Fixer/files/6874614/php-cs-fixer.txt)

### Code snippet that reproduces the problem

  ```php
  <?php
if ($blah) {
    echo $blah;
} else if ( $something_else) {
    echo $something_else;
}
  ```
  gets changed to 
```php
<?php
if ($blah) {
    echo $blah;
} else {
     if ( $something_else){
         echo $something_else;
     }
}
```

If you have repeated `else if` conditions it becomes an increasingly indented/embedded if statement.  So this:
```php
if (1) {
   echo 1;
} else if (2) {
   echo 1;
} else if (3) {
   echo 1;
} else if (4) {
   echo 1;
} else if (5) {
   echo 1;
}
```
becomes
```php
if (1) {
   echo 1;
} else {
    if (2) {
        echo 1;
    } else {
        if (3) {
            echo 1;
        } else {
            if (4) {
                echo 1;
            } else {
                if (5) {
                    echo 1;
                }
            }
        }
    }
}
```
Yes that should probably case statement but it demonstrates the issues very nicely

**Comment by keradus** [comment]
it's by design.
the `else` is always creating new block, and here, by accident, that new block appears to be `if`. but for each new block after `else`, we add `{`/`}`

if you don't like that, use syntax you had in mind - the `elseif` token. you can automate that with `elseif` rule.

**Comment by th3coop** [comment]
> by accident, that new block appears to be `if`

What accident?  The code is typed how it's supposed to be.



> if you don't like that, use syntax you had in mind - the `elseif`

I don't understand this.  I never said I use or want to use `elseif`.  Are you saying that the braces rule doesn't support the `else if` syntax at all?

**Comment by SpacePossum** [comment]
Currently the syntax you want (to keep) is not supported by the `braces` rule. As such disabling the changes will require to disable the rule. The `braces` rule is being redone and split up in more dedicated rules so in the future you _might_ get more control about which parts you can disable, please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4884

Please keep the scope of this project in mind. We try to automate CS fixing towards standards like PSR or CS styles of bigger communities, this is not a generic configurable CS fixer out of the box. As such not all CS styles are supported out of the box, but custom rules can always be developed as 3rd party.

**Comment by th3coop** [comment]
HI @SpacePossum,  thanks for the response.  

I understand it's a massive project.  I'm not making any kind of demand here, I'm just reporting a bug :). I followed up because it got closed as not a bug even though it really seems like it is.  I'd be doing you a disservice if I just let that go.  If there is follow up work regarding this that the maintainers are aware of (ie the ticket you shared), that's great!

To be clear though,  I don't want to disable those rules.  Where it applies, I use this formatting in any language I can. It would be better if they could handle `else if`, not immediately inject a new block after the `else`.

**Comment by keradus** [comment]
you think it's a bug because it's not working how you expect.

it's working exactly how creators of the rule expects it to work. `else if` structure, unlike `elseif` structure, is in fact 2 tokens. after single token of `else` the rule is always adding braces, that's the purpose of the rule.


if you don't want to use `elseif` structure that will not cause injection of `{` between `else` and `if`, we don't have any rule that support this style. by purpose.

**Comment by th3coop** [comment]
@keradus i understand your point but I don't think you're listening to mine.  If you don't want to call it a bug then we don't have to call it a bug.  But don't just close the ticket.  If you want to label it as an enhancement request then that's fine.  I do realize that I am just one person and that if there is some place where many people have said "Yes, I want my `if`s to be placed in a lower blocks from my `else`" then I'm happy to see it closed but I just can't imagine that people want this output. This makes the braces rule unusable when writing `else if`, unless of course, as mentioned above, there is a majority of people that want that layout in their code.

**Comment by SpacePossum** [comment]
>This makes the braces rule unusable when writing else if

This is why there is a PR to break up the `braces` rule, it is being worked on. So you can (in the future) use the parts of the `braces` rule you like and leave out the part you don't like.
