### ISSUE TITLE
unary_operator_spaces for all but exclamation mark?

### ISSUE THREAD

**Issue by BenMorel** [FriendsOfPHP/PHP-CS-Fixer#5842]
## Support question

Hi, is there a way to use `unary_operator_spaces` for all of these:

```diff
-$sample ++;
--- $sample;
-$sample = ~  $c;
-function & foo(){}
+$sample++;
+--$sample;
+$sample = ~$c;
+function &foo(){}
```

But not this, I would like to enforce exactly one space:

```diff
-$sample = ! $a;
+$sample = !$a;
```

Not sure if it makes sense, but that's the coding style I've always used so far.

**Comment by BenMorel** [comment]
Note that Doctrine seem to apply this coding style, too:

https://github.com/doctrine/orm/blob/2.9.3/lib/Doctrine/ORM/EntityManager.php#L818

But they're using phpcs.

**Comment by paulbalandan** [comment]
Use `not_operator_with_successor_space`

**Comment by SpacePossum** [comment]
thanks @paulbalandan :+1: 
@BenMorel please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.1/doc/rules/operator/not_operator_with_successor_space.rst :)

**Comment by BenMorel** [comment]
Thanks to both of you, this works perfectly! :+1:
