### ISSUE TITLE
PhpdocTypesOrderFixer false positive

### ISSUE THREAD

**Issue by voku** [FriendsOfPHP/PHP-CS-Fixer#5851]
## Bug report

PHP version: 7.4.22
PHP CS Fixer version: 3.0.2

### Code snippet that reproduces the problem

Example: 

input:
```@param array<string,string|array> $request```

wrong output: array-key and array-value are reversed
```@param array<array|string,string> $request```

**Comment by drupol** [comment]
Duplicate of #5850 I think .

**Comment by voku** [comment]
I can't reproduce the error anymore, so I will close the issue?!
