### ISSUE TITLE
ClassAttributesSeparationFixer false positive when using different spacing

### ISSUE THREAD

**Issue by enumag** [FriendsOfPHP/PHP-CS-Fixer#5852]
## Bug report

PHP version: 7.4.16
PHP CS Fixer version: 3.0.2

### Code snippet that reproduces the problem

It seems `ClassAttributesSeparationFixer` now also supports spacing between `trait_import`. Personally I don't want a space between the use statements so I changed my configuration for this fixer like this (using symplify/easy-coding-standard but I believe it's quite clear anyway):

```php
	$services->set(ClassAttributesSeparationFixer::class)
		->call(
			'configure',
			[
				[
					'elements' => [
						'const' => ClassAttributesSeparationFixer::SPACING_ONE,
						'property' => ClassAttributesSeparationFixer::SPACING_ONE,
						'method' => ClassAttributesSeparationFixer::SPACING_ONE,
						'trait_import' => ClassAttributesSeparationFixer::SPACING_NONE,
					],
				],
			]
		);
```

Basically I want a space between anything but trait imports. The issue is that when there is an import followed by a property this configuration removes the space between them. Here is the screenshot of the diff that ECS generates. See the red minus? This is not desired of course I want to have an empty line after the last trait import (if there is something below it).

![Screenshot from 2021-08-05 11-07-44](https://user-images.githubusercontent.com/539462/128323998-72e63b69-57c8-447c-b68f-359c62a06e88.png)

**Comment by SpacePossum** [comment]
what happens if you configure it to `only_if_meta` or if you set it to `null`?

**Comment by enumag** [comment]
@SpacePossum I can't try only_if_meta because it's not yet released. ECS has php-cs-fixer embedded and prefixed, not installed as a normal composed dependency. If I try null I get this:

```
InvalidOptionsException: Unexpected spacing for element type "", expected any of "none", "one", got "null".
```

**Comment by enumag** [comment]
> You seem to configure it to none, i.e. no space, so it seems valid the space was removed.

Well yes because I want no space between trait imports... But I also configured properties to "one" so there should be a space both above and below a property, right?

**Comment by SpacePossum** [comment]
hmm yes.. there seems to be more to this indeed :+1:
