### ISSUE TITLE
Skip trait imports in ClassAttributesSeparationFixer

### ISSUE THREAD

**Issue by jrmajor** [FriendsOfPHP/PHP-CS-Fixer#5854]
I like my trait imports to have no blank lines between them and all other elements to be separated by one blank line, like this:

```php
abstract class Example
{
    use SomeTrait;
    use AnotherTrait;

    public string $property;

    abstract public function method(): void;
}
```

The `trait_import` configuration option introduced in #5827 is impossible to disable and changes the formatting of this code, even with `none` setting (like in the diff below), meaning I have to disable the entire rule to keep my code style.

```diff
  abstract class Example
  {
      use SomeTrait;
      use AnotherTrait;
-
      public string $property;

      abstract public function method(): void;
  }
```

I'm not sure whether it's desired behavior. In case it's not, this should be treated as a bug report. In case it is, I would like to propose an additional `null` setting, entirely disabling fixing whitespace around trait imports, which would allow me to benefit from fixing separation of other class elements.

```php
['const' => 'one', 'method' => 'one', 'property' => 'one', 'trait_import' => null]
```

Thanks to all maintainers of this great tool!

**Comment by SpacePossum** [comment]
Hi and thanks for the details about the issues. I think it is the same as reported here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5843

**Comment by jrmajor** [comment]
@SpacePossum Looking at the diff provided in the description, I think that #5843 is related to trait imports with braces, not about spacing between trait imports and the rest of the class elements (note that there is a blank line after the last trait import both in “before” and “after” snippet).

**Comment by SpacePossum** [comment]
Check, I'm pretty sure together with https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5852 these are connected. One issue is the priority, the second is how the different elements are separated when not the same type is above or below it. If you can share your configuration it might be easier to verify.

**Comment by jrmajor** [comment]
@SpacePossum #5843 seems like a different problem, but #5852 indeed looks like what I'm experiencing. Sorry for the duplicate, I didn't notice this issue. You can find my configuration [here](https://github.com/jrmajor/php-cs/blob/4ae274e05f13b680313a9b271e77aac3f2d7be7f/rules.php).

**Comment by jrmajor** [comment]
Thank you, @SpacePossum and @keradus!
