### ISSUE TITLE
UPGRADE.md file missing with broken link for php-cs-fixer self-update

### ISSUE THREAD

**Issue by shakaran** [FriendsOfPHP/PHP-CS-Fixer#5878]
## Bug report

From PHP CS Fixer updated (2.18.2 -> v3.0.2)

```
$ php-cs-fixer self-update
A new major version of PHP CS Fixer is available (v3.0.2)
Before upgrading please read https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.2/UPGRADE.md
If you are ready to upgrade run this command with -f
Checking for new minor/patch version...

```
The file https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.2/UPGRADE.md is missing

**Comment by keradus** [comment]
thanks for reporting the issue!

I addressed it in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5881 , but it will be released as 2.19.2, so if you use 2.19.1 or lower, it will still have the bug.

Feel free to propose a PR that would suggest to update to latest MINOR of current MAJOR before bumping the MAJOR
