### ISSUE TITLE
Improve suggestion for 

### ISSUE THREAD

**Issue by shakaran** [FriendsOfPHP/PHP-CS-Fixer#5880]
## Bug report

For version 3, using old rule _lowercase_constants_ says:

```
In ConfigurationResolver.php line 717:
                                                                                             
  The rules contain unknown fixers: "lowercase_constants" (did you mean "lowercase_cast"?).  

```
It should suggest:

`'constant_case' => ['case' => 'lower'],`

**Comment by keradus** [comment]
The option resolver relies on Sf one to look for typo and find closest match.
For rules rename, there is no hinting on code level.
One has to manually rename the rules based on https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md#renamed-rules .

if you want, do not hesitate to propose a PR to suggest this mapping from code directly.
