### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#5891]
Do we have an issue tracking PHP 8.1 support? If not, could we use this issue to track this. My feeling here is that there isn't too much to do to support PHP 8.1 compared to what was required to support 8.0. :)

Changes to support:

* Support for `readonly` properties (both in class property definitions and also constructor property promotion).
* Support for `final` class constants.
* Support for intersection types (⚠️ lexing changes to `&` in PHP 8.1... maybe a transformer required. EDIT: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5861 looks to be exactly adding a transformer).
* Support for enums (definition sytnax only - i don't think there are any changes to parsing enum access - the same as class constant access).

---

Related: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5863.

**Comment by julienfalque** [comment]
👍

I don't remember whether we decided something regarding old versions. I would say this can be an opportunity to drop support for PHP 7.2 and maybe 7.3.

**Comment by GrahamCampbell** [comment]
I don't think that's related. We should be careful with dropping old versions too quickly - in particular dropping PHP 7.4 would be problematic, because not all PHP 7 files are compatible with PHP 8.

**Comment by keradus** [comment]
@GrahamCampbell , would you like to prepare overall list of compatibility topics we need to ensure, similar to what we did for 8.0?

**Comment by GrahamCampbell** [comment]
Of course. I've updated the @keradus. :)

**Comment by SpacePossum** [comment]
see also https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5945 with more TODO items

**Comment by vbasky** [comment]
What's outstanding for the support for PHP 8.1 ?

**Comment by SpacePossum** [comment]
good question, ping @keradus @kubawerlos @julienfalque , please provide points and or lets talk about it tomorrow during check in :)

**Comment by keradus** [comment]
last part, we believe: #6146

**Comment by yakobe** [comment]
Yo. Looks like everything for 8.1 is ready to go. Great stuff 🚀.
Would it be possible to tag a release? Or does it need some more testing etc?

**Comment by keradus** [comment]
@yakobe one more open in https://github.com/FriendsOfPHP/PHP-CS-Fixer/labels/topic%2FPHP8.1
