### ISSUE TITLE
PhpdocToCommentFixer false positive with property promotion

### ISSUE THREAD

**Issue by enumag** [FriendsOfPHP/PHP-CS-Fixer#5893]
## Bug report

![Screenshot from 2021-08-23 13-53-24](https://user-images.githubusercontent.com/539462/130443054-e97c2d03-8236-4fd9-a300-c3e55f42df39.png)

### Code snippet that reproduces the problem

```php
use Symfony\Component\Validator\Constraints as Assert;

class X
{
	public function __construct(
		/**
		 * @Assert\NotBlank()
		 */
		public string $x
	) {
	}
}

```

**Comment by keradus** [comment]
hey @enumag ! sounds valid! would you mind to raise a PR to propose a fix?
