### ISSUE TITLE
@internal and @coversNothing added to non test class

### ISSUE THREAD

**Issue by Seb33300** [FriendsOfPHP/PHP-CS-Fixer#5895]
## Bug report

In my Symfony project, I have an entity named `ProductTest`.
This entity is a real entity used by our project, not related to tests, and extends nothing.

But when I run the `php-cs-fixer fix` command (using `@PhpCsFixer`rule), `@internal` and `@coversNothing` annotations are added to my entity.

``` php
/**
 * @ORM\Entity
 *
 * @internal
 * @coversNothing
 */
class ProductTest
{
    //...
}
```

Is there any way to tell PHP-CS-Fixer where is the tests folder to improve tests classes detection or something?

**Comment by kubawerlos** [comment]
This works as expected, has even a test case for your example: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.2/tests/Indicator/PhpUnitTestCaseIndicatorTest.php#L61

There is currently no way to configure tests directory.

**Comment by Seb33300** [comment]
So this means the expected isn't correct. why closing the issue?

**Comment by Seb33300** [comment]
In your link, the method name is `provideIsPhpUnitClassCases`.
And the class matching is not PhpUnit...

**Comment by kubawerlos** [comment]
> So this means the expected isn't correct. why closing the issue?

Why do you claim expected isn't correct?

My link is to the line 61, which is a test case for `<?php final class MyTest {}` - a class with a name `Test` at the end recognized as test class (the `final` keyword does not matter). [Here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.2/src/Indicator/PhpUnitTestCaseIndicator.php#L32) is a check that is satisfied for any class with name ending with "Test".

**Comment by Seb33300** [comment]
> Why do you claim expected isn't correct?

Because it can match false positive

**Comment by kubawerlos** [comment]
If you change the behaviour it can introduce some false negatives.
