### ISSUE TITLE
binary_operator_spaces and arrow functions (PHP 7.4+)

### ISSUE THREAD

**Issue by stayallive** [FriendsOfPHP/PHP-CS-Fixer#5896]
## Bug report?

PHP version: 8.0.9
PHP CS Fixer version: 3.0.2

### Code snippet that reproduces the problem

Before:

```php
<?php

collect()
    ->map(fn ($arg) => [])
    ->keyBy(fn ($arg) => []);
```

Fixed by php-cs-fixer (`test.php (binary_operator_spaces)`):

```php
<?php

collect()
    ->map(fn ($arg)   => [])
    ->keyBy(fn ($arg) => []);
```

Expected: No changes.

---

`php-cs-fixer` config for `binary_operator_spaces`:

```php
'binary_operator_spaces'  => [
    'operators' => [
        '|'  => null,
        '='  => 'align_single_space',
        '=>' => 'align_single_space',
    ],
],
```

I get why it's doing this, but I can't figure out how to disable this only for arrow functions.

All other `binary_operator_spaces` alignment like for arrays and assignments works like a charm.

**Comment by keradus** [comment]
i don't think `binary_operator_spaces` should touch arrow functions
cc @FriendsOfPHP/php-cs-fixer 

@stayallive , would you like to propose a PR to fix it?

**Comment by stayallive** [comment]
Honestly I like to but I have never worked in this project and it will take me some time figuring it out.

From looking at the tests it is expected (or was at least at some point) that arrow functions be affected since there are test cases for them: 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/ca8aea789c8c61c3fea2fa5928bd9b37878a0566/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php#L2006-L2040

So if it is indeed not expected or should become configurable (I would personally be fine with either) there has to be made some decisions I'm also not comfortable making for the project, so I'll await that and if someone can propose a PR after doing that it would be greatly appreciated. If not, I'll try and see if I can make it happen 😄
