### ISSUE TITLE
Should SingleSpaceAfterConstructFixer fix "if(" ? BracesFixer does.

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#5904]
## Support question

I was surprise when I saw a PR from a fellow colleague pass the build with `if(` in the codebase, while we're using PSR-12 as a coding standard. I expected EasyCodingStandard (and the underlying PHP-CS-Fixer) to report it as wrong and propose `if (` with a space instead.

So I looked at SingleSpaceAfterConstructFixer, tried to include it explicitly in my project, and it still doesn't report any errors. Why is that ?

Thanks for your insights.
gnutix

**Comment by gnutix** [comment]
Relates to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5757

**Comment by gnutix** [comment]
I upgraded ECS to v9.4.40 and it fixed an issue I hadn't noticed : ECS only reported the first error it had found... Now I do have the error about the `if(` reported !

The only remaining issue is why I cannot write `Blob|string $blob /* A blob instance or a blob URI */,` with `SingleSpaceAfterConstructFixer`. :man_shrugging:

**Comment by keradus** [comment]
@gnutix , please provide reproduceable cases using vanilla PHP CS Fixer without any proxy tool as well as version of PHP CS Fixer you are using.
providing only info about proxy tool is adding extra effort on our side to figure out missing details.


anyway, big thanks for raising the issues and ideas. also, do not hesitate to propose how to fix them ;)

**Comment by keradus** [comment]
solved in #5913
