### ISSUE TITLE
[@Symfony] native_function_casing changes case for PHP8 attributes

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#5907]
## Bug report

Hello there. I'm running PHP-CS-Fixer through ECS v9.4.40 (latest version) and importing the Symfony set, which includes `NativeFunctionCasingFixer`. Since I've migrated some code to PHP8, notable annotations to attributes syntax changes, it reports the following change : 

```diff
    ---------- begin diff ----------
@@ -19,7 +19,7 @@
     #[Assert\NotNull, Assert\Type(FileBlob::class)]
-    #[File(mimeTypes: ['application/pdf', 'image/*'])]
+    #[file(mimeTypes: ['application/pdf', 'image/*'])]
     public FileBlob $attachment;
    ----------- end diff -----------

Applied checkers:

 * PhpCsFixer\Fixer\Casing\NativeFunctionCasingFixer
```

### Code snippet that reproduces the problem

We have a custom File validator that extends Symfony's one and use it like so : 

```php
<?php

declare(strict_types=1);

namespace App\SomeModule;

use OurVendor\Symfony\Validator\File;
use Symfony\Component\Validator\Constraints as Assert;

final class SomeClass
{
    #[Assert\NotNull, Assert\Type(FileBlob::class)]
    #[File(mimeTypes: ['application/pdf', 'image/*'])]
    public FileBlob $attachment;
}
```

NativeFunctionCasing should not detect attributes as functions.

**Comment by kubawerlos** [comment]
It will be fixed by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5809 (which needs https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5856), I've added test case to cover this situation in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5909.

So, do not hesitate in making review of the first PR in line: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5856.

**Comment by keradus** [comment]
@gnutix , please always follow the version of PHP CS Fixer. if you are using a proxy tool, it does not bring any information to us which PHP CS Fixer version you are using.

**Comment by gnutix** [comment]
@keradus Do you mean I should explicitly specify `friendsofphp/php-cs-fixer` and `squizlabs/php_codesniffer` in `composer.json`, even though there is already `symplify/easy-coding-standard` which encompasses them ? I'm not sure how it would work, given ECS is distributed as a prefixed package in a PHAR. :man_shrugging: 

Thanks for the fix anyway! :heart:
