### ISSUE TITLE
[@Symfony] binary_operator_spaces adds spaces around pipes in PHP8 union types if array is after the pipe

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#5911]
## Bug report

I'm running ECS 9.4.40 (latest version) with Symfony set. The binary_operator_spaces adds spaces around the pipe in a function's argument using PHP native union types when array is after the pipe.

### Code snippet that reproduces the problem

```php
/**
 * @param callable|callable[] $groupBy
 */
function groupBy(array $array, callable|array $groupBy, bool $preserveKey = false): array
{
    // ...
}
```

results in : 

```diff
    ---------- begin diff ----------
@@ -171,7 +171,7 @@
 /**
  * @param callable|callable[] $groupBy
  */
-function groupBy(array $array, callable|array $groupBy, bool $preserveKey = false): array
+function groupBy(array $array, callable | array $groupBy, bool $preserveKey = false): array
 {
    ----------- end diff -----------

Applied checkers:

 * PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer
```

If I change the function's argument definition to `array|callable $groupBy`, it doesn't trigger the error anymore.

**Comment by kubawerlos** [comment]
@gnutix can you change the issue description, the part "if array is after the pipe" to "if callable is before the pipe"?

You can see that this is the case in the PR with fix: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5912 (see failed tests for 1st commit) - drop a review there too, please.
