### ISSUE TITLE
Case separation between Anonymous functions and Arrow functions

### ISSUE THREAD

**Issue by umbertoloria** [FriendsOfPHP/PHP-CS-Fixer#5916]
## Feature request

Currently, with the configuration `'function_declaration' => ['closure_function_spacing' => 'none']`, I get the following result.

```
$a = function() {
    return 0;
};
$b = fn() => 0;
```

Instead, with `one` I get the following.

```
$a = function () {
    return 0;
};
$b = fn () => 0;
```

Is there a way to split this cases into two separated cases? Like `anonymous_function_spacing` and `arrow_function_spacing`?
I'm asking because I'm trying to create a .dist.php file that is compatible with PhpStorm PSR1/PSR2 scheme format source,
and its behaviour (in formatting PHP code) seems always to place no spaces between `fn` and `(` in arrow function declaration, and instead places a space between `function` and `(`.
This behaviour would be achievable with something - for example - like this.

```
'function_declaration' => [
    'arrow_function_spacing' => 'none',
    'anonymous_function_spacing' => 'one',
]
```

**Comment by keradus** [comment]
I'm not sure if there is big need to distinguish those 2 cases.
maybe rather PhpStorm should enhance arrow functions support and handling of spaces?

anyway, if you provide a possibility to distinguish anon/arrow functions as a PR, I'm +0.5 on it ;)

**Comment by twose** [comment]
This is necessary. PhpStorm default behavior is equal to `['arrow_function_spacing' => 'none', 'anonymous_function_spacing' => 'one']` and it has no code style option for `arrow_function_spacing` so it trouble me now.

**Comment by twose** [comment]
[Example code of arrow function in RFC](https://wiki.php.net/rfc/arrow_functions_v2):
```php
$fn1 = fn($x) => $x + $y;
 
$fn2 = function ($x) use ($y) {
    return $x + $y;
};
```

**Comment by jblotus** [comment]
Interested in splitting this as well

**Comment by jblotus** [comment]
When setting code style from PSR-12 inside intellij, arrow function has no space before parenthesis but closure function keyword does, per twose's example.

Per this comment from Nikita Popov I believe it is worthwhile to never have space before short array parenthesis.
https://www.reddit.com/r/PHP/comments/fctb18/comment/fjd9u6a/?utm_source=share&utm_medium=web2x&context=3

I would be happy to try and implement such a rule but I am not sure where to start on such an undertaking.

**Comment by jblotus** [comment]
Here is my attempt: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6259

**Comment by twose** [comment]
It seems that there is no progress...

**Comment by theodorejb** [comment]
I would also like this feature in order to start using PHP-CS-Fixer.

For closures PSR-12 [only requires a space](https://www.php-fig.org/psr/psr-12/#7-closures) after the `function` keyword specifically, and does not mandate a space after `fn` in arrow functions. Since (as @twose and @jblotus pointed out above), arrow functions were intended to be written without a space after `fn`, PHP-CS-Fixer should support this standard formatting.
