### ISSUE TITLE
PHPDoc parsing broken (`phpdoc_types_order` issue)

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#5921]
I tried the latest ^3.1.0 on loophp/collection and I get:

```diff
-     * @return Closure(Iterator<TKey, T>): Generator<int, array<TKey, T>>
+     * @return Closure(Iterator<TKey, T>): Generator<int, <|array|TKey, T>>
```

```diff
-        /** @var Closure(Iterator<TKey, T>): Generator<int, array<TKey, T>> $pipe */
+        /** @var Closure(Iterator<TKey, T>): Generator<int, <|array|TKey, T>> $pipe */
```

I guess this is a follow-up of: #5834, #5832, #5798

**Comment by drupol** [comment]
Still the same issue with 3.2.1 :(

**Comment by drupol** [comment]
@keradus or @SpacePossum is there an issue open already for this one?

**Comment by drupol** [comment]
I already tried but without success yet. I don't mind having a bit of help on this one.

**Comment by ruudk** [comment]
This is a PR that contains a failing test with a similar case: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5919

**Comment by drupol** [comment]
Still the same issue with 3.3.2:

```diff
-                 * @var Closure(Iterator<TKey, T>): Generator<TKey, T> $callback
+                 * @var Closure(Iterator<TKey, <|T>): Generator|TKey, T> $callback
```

**Comment by julienfalque** [comment]
@drupol Could you please give #6063 a try and see if it fixes the issue?

**Comment by drupol** [comment]
> @drupol Could you please give #6063 a try and see if it fixes the issue?

Works perfectly ! When can we get it merged ? It's been broken since a couple of releases :(

**Comment by SpacePossum** [comment]
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6063
