### ISSUE TITLE
NoUnusedImportsFixer remove used imports

### ISSUE THREAD

**Issue by liquid207** [FriendsOfPHP/PHP-CS-Fixer#5935]
NoUnusedImportsFixer remove used imports that after `|`
   * PHP version: 8.03
   * PHP CS Fixer version: 3.1.0
   * the command used to run PHP CS Fixer: ./vendor/bin/php-cs-fixer fix 'file.php'
   * the configuration (file) you used

### Code snippet that reproduces the problem

```
<?php

use Foo;
use Bar;

abstract class Baz
{
    abstract public function test(): Foo|Bar;
}
```

Expected output:

```
<?php

use Foo;
use Bar;

abstract class Baz
{
    abstract public function test(): Foo|Bar;
}
```

Actual output:

```
<?php

use Foo;

abstract class Baz
{
    abstract public function test(): Foo|Bar;
}
```

**Comment by jrmajor** [comment]
@liquid207 Could you check whether it's still broken in `dev-master` version? I've experienced the same issue, but it seems to be fixed in the `master` branch.

**Comment by SpacePossum** [comment]
it is still an issue, see PR for details : )
