### ISSUE TITLE
Replacing the dir function with the getdir function that does not exist in Php7. 4 no_alias_functions

### ISSUE THREAD

**Issue by eisberg** [FriendsOfPHP/PHP-CS-Fixer#5936]
## Bug report

PHP CS Fixer replaces the **dir** function with **getdir**.  But there is no such function in PHP7. 

   * PHP version: PHP 7.4.21
   * PHP CS Fixer version: PHP CS Fixer 3.1.0 River by Fabien Potencier and Dariusz Ruminski
   * the command used to run PHP CS Fixer: php-cs-fixer fix  --verbose src
   * the configuration:
   
```
[
            '@PhpCsFixer' => true,
            '@Symfony' => true,
            '@Symfony:risky' => true,
            '@PHP71Migration' => true,
            '@DoctrineAnnotation' => true,
            'linebreak_after_opening_tag' => true,
            'no_unreachable_default_argument_value' => true,
            'no_php4_constructor' => true,
            'concat_space' => ['spacing' => 'one'],
            'general_phpdoc_annotation_remove' => ['annotations' => ['author', 'package']],
            'list_syntax' => ['syntax' => 'short'],
            'multiline_whitespace_before_semicolons' => [
                'strategy' => 'no_multi_line',
            ],
        ]
```
 
Rule: `no_alias_functions `

### Code snippet that reproduces the problem

  ```php
  <?php
  $dDir = dir($tmpDir);
  ```
result:

  ```php
  <?php
  $dDir = getdir($tmpDir);
  ```
 
**dir** is really an alias of the **getdir** function. But the original function did not exist until recently due to an error in PHP. The problem with this function is described in detail here https://externals.io/message/113982

From PHP 4.0 until PHP 7.4, only the alias existed: https://3v4l.org/ZHJ9U

**Comment by SpacePossum** [comment]
Thanks for reporting!

So looking at the linked discussion and PR on PHP itself, `getdir` function will be removed in upcoming PHP release and `dir` should be used?

Than we need to update the rule and remove the `dir` to `getdir` mapping.

The rule could only change `getdir` into `dir` for PHP8.0.0 till 8.0.5? (not sure if it is worth adding that logic).
