### ISSUE TITLE
binary_operator_spaces with align_single_space_minimal does not work for arrays in if statements

### ISSUE THREAD

**Issue by nizacegodk** [FriendsOfPHP/PHP-CS-Fixer#5980]
## Bug report

`binary_operator_spaces` with `align_single_space_minimal` does not correctly align array key-value pairs when used with arrays in if statements.

It seems the whole "align" part of the setting is ignored, and only "single_space_minimal" is actually applied.

   * PHP version: `8.0.10`
   * PHP CS Fixer version: `3.1.0`
   * the command used to run PHP CS Fixer: `vendor/bin/php-cs-fixer fix -vvv`

### Configuration

```php
<?php

use PhpCsFixer\Config;

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/app')
    ->in(__DIR__ . '/routes')
    ->in(__DIR__ . '/tests');

return (new Config())
    ->setFinder($finder)
    ->setRiskyAllowed(false)
    ->setHideProgress(false)
    ->setUsingCache(true)
    ->setRules([
        'binary_operator_spaces' => ['operators' => ['=>' => 'align_single_space_minimal']],
    ]);

```

### Code snippet that reproduces the problem

  ```php
  <?php
  if ($this->save([
      'bar'        => 'baz',
      'barbarbar'     => 'baz',
  ])) {
      // Do the work
  }
  ```

Is fixed to

  ```php
  <?php
  if ($this->save([
      'bar' => 'baz',
      'barbarbar' => 'baz',
  ])) {
      // Do the work
  }
  ```

Where the expected output would be:

  ```php
  <?php
  if ($this->save([
      'bar'       => 'baz',
      'barbarbar' => 'baz',
  ])) {
      // Do the work
  }
  ```

**Comment by liquid207** [comment]
I noticed this issue caused by [code](https://github.com/liquid207/PHP-CS-Fixer/blob/a2d5d6f14e47713f6470e72d9d5b87487adc6bfa/src/Fixer/Operator/BinaryOperatorSpacesFixer.php#L576-L576), code in `foreach`, `for`, `while`, `if` and `switch` will be skipped. Can you explain why you did this? @SpacePossum
