### ISSUE TITLE
Fixer proposal: remove `@final` annotation from blocks already marked as final

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#5985]
Example that doesn't need the final annotation anymore:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/2829600/132575614-8151686b-2b76-427a-8119-050c0e525be7.png">

We could automate the removal of this. Simiarly for final methods, constants (php 8.1), etc.

**Comment by drupol** [comment]
Oh yes, nice idea :)

**Comment by julienfalque** [comment]
This could be part of `no_superfluous_phpdoc_tags`.
