### ISSUE TITLE
no_empty_comment for phpdoc?

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#5994]
## Feature request

After running `no_superfluous_phpdoc_tags` the following diffs are all over;

```diff
    /**
-     * @return string
     */
```

Im wondering if the remaining `/***/` could be cleaned up somehow ... (?)

_(PHP CS Fixer 3.1.0 River by Fabien Potencier and Dariusz Ruminski (cf4cedb))_

**Comment by julienfalque** [comment]
This should already be handled by [`no_empty_phpdoc`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/phpdoc/no_empty_phpdoc.rst), did you enable it?

**Comment by ro0NL** [comment]
I was manually mass fixing files. Simply missed the rule (as we enable `@PhpCsFixer). Thanks :100:
