### ISSUE TITLE
Add a flag to the `class_attributes_separation` configuration to have a blank line only after the last trait import

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfPHP/PHP-CS-Fixer#6013]
## Feature request

With the upgrade of PHP-CS-Fixer from version 3.0.0 to version 3.1.0, the tool (rightfully) [added blank lines in between multiple trait imports](https://github.com/MyIntervals/emogrifier/pull/1106/files).

In our project, we like having the trait imports as a single block with a blank line below it, but not between each import. Like this:

```php
final class StringContainsCssCountTest extends TestCase
{
    use CssDataProviders;
    use TestStringConstraint;

    /**
     * @test
     *
     * @param string $needle
     * @param string $haystack
     *
     * @dataProvider provideCssNeedleNotFoundInHaystack
     */
    public function matchesHaystackNotContainingNeedleWithZeroCount(string $needle, string $haystack): void
    {…}
}
```

So I'd like to request a flag that prohibits blank lines in between trait imports, but enforces a blank line between the last trait import and the first "other thing" in a class.

**Comment by SpacePossum** [comment]
if you use `trait_import => none` configuration in _next_ release, this will do what you want :+1:
