### ISSUE TITLE
Describe RuleSet exclusively

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfPHP/PHP-CS-Fixer#6017]
For mass codebase migration, i like to have a list of exclusive rules per RuleSet. So we can tick off rules as we go.

I tried to get Symfony's rules as follow;

```
php-cs-fixer.phar describe '@Symfony,-@PSR12'

In DescribeCommand.php line 127:
                                     
  Set "@Symfony,-@PSR12" not found.  
```

Perhaps a `describe --exclusive` is more elegant. WDYT?

**Comment by SpacePossum** [comment]
Hi and thanks for the suggestion!

Sounds good to me, I think I get what you want here. Not sure about the `exclusive` name because if the SF set would disable a rule from the other set, should the rule still be listed it in the output?

**Comment by ro0NL** [comment]
I'm not sure what internals could be blocking :) for my tool to work an overview of rules per group is sufficient, eg.

```
#PSR12
braces
...

#Symfony
...
```

Our target ruleset is `PhpCsFixer` :) but i 'd like to have a sense in what context (ruleset) a rule belongs to,  and we started with PSR (our lowest ruleset).

Basically i'd like to deduplicate rulesets fast :D

However im not sure i understand this output

```
$ var/php-cs-fixer.phar describe @PSR2 | grep '* braces' -A1
 * braces
   | The body of each structure MUST be enclosed by braces. Braces should be properly placed. Body of braces should be properly indented.
$ var/php-cs-fixer.phar describe @PSR12 | grep '* braces' -A1
 * braces
   | The body of each structure MUST be enclosed by braces. Braces should be properly placed. Body of braces should be properly indented.
$ var/php-cs-fixer.phar describe @PSR1 | grep '* encoding' -A1
 * encoding
   | PHP code MUST use only UTF-8 without BOM (remove BOM).
$ var/php-cs-fixer.phar describe @PSR2 | grep '* encoding' -A1
```

I expected encoding to be present in PSR2 :thinking:

**Comment by SpacePossum** [comment]
`encoding` is in the PSR1 set and the PSR1 set is in the PSR2 set ;)

For the overview, I was wondering, for example `@PhpCsFixer` set disables `'single_line_throw' => false` , should I list this in the over or should it only list the rules it does add?

**Comment by ro0NL** [comment]
I see. Depends on how far we take this :)

Perhaps a more rich output that groups `Inherited RuleSets, Disabled Rules, Added Rules`. Alternatively we could run eg. `describe --exclusive` that skips inherited rulesets (or just hints about them), effectively we'd then only show `Added Rules`  IIUC.

**Comment by ro0NL** [comment]
> encoding is in the PSR1 set and the PSR1 set is in the PSR2 set ;)

right, actually `braces` is defined in PSR12 with different config compared to PSR2 :+1: i definitely need a way to get those (leading) default configs per rule fast :) ("just" `braces: true` is still on my pending list)

**Comment by SpacePossum** [comment]
maybe `$ php php-cs-fixer list-sets --format=json` could be extended to include the individual rules per set, would that help?

**Comment by ro0NL** [comment]
Yes :+1: the goal is to infer disabled rules and config overrides.

**Comment by ro0NL** [comment]
Another nice addition would be eg. `$ php php-cs-fixer list-sets PhpCsFixer` to limit sets to inherited ones only.
