### ISSUE TITLE
`no_unused_imports` false positive when used in union return type

### ISSUE THREAD

**Issue by dmason30** [FriendsOfPHP/PHP-CS-Fixer#6024]
## Bug report

   * PHP version: 8.0
   * PHP CS Fixer version: 3.1

**Config**
```php
'no_unused_imports' => true,
```

### Code snippet that reproduces the problem

**Scenario A**
On the below code snippet the `use Illuminate\Database\Query\Builder as QueryBuilder;` line is removed incorrectly.
```php
<?php

namespace App\Models\Queries;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Query\Builder as QueryBuilder; // <-- Incorrectly removed 

abstract class Query
{
    abstract protected function query(): Builder|QueryBuilder;
}
```

**Scenario B**
If you flip the union around then the line `use Illuminate\Database\Eloquent\Builder;` is incorrectly removed.
```php
<?php

namespace App\Models\Queries;

use Illuminate\Database\Eloquent\Builder; // <-- Incorrectly removed 
use Illuminate\Database\Query\Builder as QueryBuilder; 

abstract class Query
{
    abstract protected function query(): QueryBuilder|Builder;
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

The issue seems the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5944 , which should be resolved in the upcoming release. Please let me know if it isn't and I'll reopen :)
