### ISSUE TITLE
Allow PHPCBF to read froma PHPCS output

### ISSUE THREAD

**Issue by BRafols** [FriendsOfPHP/PHP-CS-Fixer#6025]
## Feature request

Currently, we can use `phpcs` to lint files and `phpcbf` to lint & fix.

It would be very handy to add a new option onto `phpcbf` called `from-report` that only fixes the issues in the report.

This would allow for the following use case:
- Run `phpcs` and output the report in a `json` file
- Use a custom script that filters out some if these issues (for example running `sarb`)
- Pass the output to `phpcbf` which will, when used with above option, only fix the issues in the filtered file

I can help with this, but would need some help from mantainers so they guide me in the correct direction

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your idea. This project is not `phpcs` nor `phpcbf` related, are you sure you have a request you want to make here?

**Comment by BRafols** [comment]
My bad, I got confused. 

Thanks for the headsup

**Comment by BRafols** [comment]
My bad, I got confused. 

Thanks for the headsup
