### ISSUE TITLE
Too large string with named arguments was splitted and Fixer marked as an error 

### ISSUE THREAD

**Issue by diosby** [FriendsOfPHP/PHP-CS-Fixer#6039]
## Bug report

I have a too large string:

```php
        throw new UnauthorizedHttpException(challenge: static::ACCESS_IS_FORBIDDEN, message: static::ACCESS_IS_FORBIDDEN, code: 403);
```

I've formatted it to make it shortly.

But CS have marked it as an error and suggest to fix it from

```php
private function throwUnauthrorizedException(): void
     {
        throw new UnauthorizedHttpException(
            challenge: static::ACCESS_IS_FORBIDDEN,
            message: static::ACCESS_IS_FORBIDDEN,
            code: 403
        );
        
     }
```

to

```php
private function throwUnauthrorizedException(): void
     {
        throw new UnauthorizedHttpException(challenge: static::ACCESS_IS_FORBIDDEN, message: static::ACCESS_IS_FORBIDDEN, code: 403);
     }
```

![Screenshot from 2021-09-28 18-17-52](https://user-images.githubusercontent.com/19969187/135117327-afe31b2f-0956-4346-a130-b17054a1a822.png)

I expect to CS doesn't suggest this change. 

Thank you.

**Comment by kubawerlos** [comment]
> I expect to CS doesn't suggest this change.

So run PHP CS Fixer with `-v` to learn what fixer is doing that, disable it and do not report fixer fixing code as a bug...

**Comment by keradus** [comment]
as an addition - it's basically coming from one of the rules that you have enabled in your config. you may want to groom your config to not include the rule for this change. 
I guess you enabled `@Symfony` ruleset (the rule came from their standards)
