### ISSUE TITLE
Need `ordered_class_elements` custom order

### ISSUE THREAD

**Issue by dongm2ez** [FriendsOfPHP/PHP-CS-Fixer#6041]
## Feature request

Sometimes we want to arrange in code that requires some customization, such as some places that don't want to be sorted or that developers define sorting themselves, but this fixer doesn't provide relevant customization options or features

I want to be able to provide such customization, possibly in code like this:

```PHP
<?php

class A {
    // @phpcs-ignore-order Not sort
    public function b() {}
    private function g() {}
    public function c() {}
    protected function d() {}
    public function d() {}
    // @phpcs-ignore-order

    public function j() {}
    public function f() {}
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your idea,

This project aims to provide a tool to fix CS towards popular standards, it is not by design a generic CS fixing tool. Your use case seems a good fix a 3rd party fixer you can share with the developers involved, however this is not something we want here as part of the core rules.

**Comment by kubawerlos** [comment]
@dongm2ez if you decide to go with custom fixer feel free to copy https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v3.0.2/dev-tools/src/Fixer/OrderedClassElementsInternalFixer.php and modify to your needs.

**Comment by dongm2ez** [comment]
> @dongm2ez if you decide to go with custom fixer feel free to copy https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v3.0.2/dev-tools/src/Fixer/OrderedClassElementsInternalFixer.php and modify to your needs.

Thank you！@kubawerlos
