### ISSUE TITLE
force_alternative_syntax

### ISSUE THREAD

**Issue by ngdangtu-vn** [FriendsOfPHP/PHP-CS-Fixer#6046]
## Rule request

I really like alternative syntax of PHP control structure. So I would like to propose `force_alternative_syntax` rule. Its job make sure long control structure syntax use alternative. In detail it would be:

```PHP
return (new PhpCsFixer\Config())->setRules([
	// set true to use default config below
	'force_alternative_syntax' => true,

	// Force specific case to alternative syntax
	'force_alternative_syntax' => [
		// integer, tell the fixer how deep it should convert
		// 0 => only the parent
		// 1 => parent and the child(ren)
		// 2 => parent -> child(ren) -> grandchild(ren)
		'nest_depth' => 9, // I don't think there is anyone out there would dare to pass 3...

		// if nest, where syntax should start: true = from parent | false = from child
		'convert_from_parent' => true,

		// if syntax only costs a line: false = tradition | true = alternative
		'one_line' => false,
		
		// if syntax costs more than 2 lines: true = alternative | false = tradition
		'multiple_lines' => true,
		
		// add whitespace between the colon and the brace : false = no space | true = 1 whitespace
		'whitespace_before_colon' => false,
	],
]);
```

### Code snippet that shows how the rule would fix PHP code

**Case**: `'force_alternative_syntax' => true`

```diff
--- Original
+++ New

$cond = false;
$i = 0;

if ($cond) var_dump($cond);

- if ($cond) {
+ if ($cond):
   $cond = false;
   var_dump($cond);
- }
+ endif;

- while ($cond) :
+ while ($cond):
   $i += 1;
   $cond = $i == 100;
- }
+endwhile;

- while ($cond): $cond = true; endwhile;
+ while ($cond) $cond = true;

- while ($cond) {
+ while ($cond):
   $i += 1;
-    if ($cond) {
+    if ($cond):
       $cond = false;
       var_dump($cond);
-    }
+    endif;
   $cond = $i == 100;
- }
+endwhile;
```

**Case**: `'force_alternative_syntax' => ['nest_depth' => 0, 'convert_from_parent' => false]`

In this case, the nest direction is started from the inside.

```diff
--- Original
+++ New
while ($cond) {
   $i += 1;
-    if ($cond) {
+    if ($cond):
       $cond = false;
       var_dump($cond);
-    }
+    endif;
   $cond = $i == 100;
}
```

How does everyone think? Please tell me if I miss sth.

**Comment by julienfalque** [comment]
IMO using this syntax is not a widespread practice, even for templating. For now I would suggest implementing this in a third-party package rather than here.

**Comment by ngdangtu-vn** [comment]
I think it is very good for readability. It's especially in nest code. But you mention 3rd-party pkgs... What is it? I only see custom rulesets, never heard about pkg before.

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your very detailed idea.

Currently I know of no widely used CS standard within the PHP community that uses the suggested CS. As such it is not really in the scope of this project itself and therefore I'll close this this issue. As Julien suggested you can still make the fixer/rule and use it within this tool as a 3rd party fixer. Please check out the docs:
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/cookbook_fixers.rst
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/custom_rules.rst

or have a look at other 3rd party rule providers to see how they do it, good luck!
