### ISSUE TITLE
Short syntax lists in `for`/`foreach` loop declarations are seen as arrays

### ISSUE THREAD

**Issue by jacekciach** [FriendsOfPHP/PHP-CS-Fixer#6062]
## Bug report

It seems that in `for`/`foreach` declarations PHP-CS-Fixer does not recognize `as [/*...*/]` as a list, but as an array.

The `array_syntax` fixer configured with "long" syntax incorrectly tries to fix "short" syntax lists in `for`/`foreach` declarations.
The "short" list syntax `[/*...*/]` is wrongly replaced with `array(/*...*/)` - which produces an incorrect PHP code.

See: https://www.php.net/manual/en/function.list.php

* PHP version tested: `7.2.34`, `7.3.29`, `7.4.15`, `8.0.11` (all run from official PHP docker images: `php:*-alpine`)
* PHP-CS-Fixer version: `3.2.1`
* the command used to run PHP CS Fixer: `vendor/bin/php-cs-fixer fix --dry-run -vvv --diff --using-cache=no`
* the configuration file `.php-cs-fixer.dist.php` used:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/testcase')
;

$config = new PhpCsFixer\Config();
return $config->setRules([
        'array_syntax' => [
            'syntax' => 'long',
        ],
        'list_syntax' => [
            'syntax' => 'long',
        ],
    ])
    ->setFinder($finder)
;
```

### Code snippet `test.php` that reproduces the problem
```php
<?php

foreach ($iterable as [
    'a' => $a,
    'b' => $b,
]) {
    // do something
}

foreach ($iterable as [
    $a,
    $b,
]) {
    // do something
}

$result = $pdo->query("SELECT id, name FROM employees");
while ([$id, $name] = $result->fetch(PDO::FETCH_NUM)) {
    echo "id: $id, name: $name\n";
}

[$a, $b] = $array;

[
    $a,
    $b,
] = $array;
```

### It gives the output (PHP 8.0.11)

(in other tested PHP versions the `LintingException` message differs):

```diff
Files that were not fixed due to errors reported during linting after fixing:
   1) /tmp/test/testcase/test.php

                                                                                                           
        [PhpCsFixer\Linter\LintingException]                                                               
        Parse error: syntax error, unexpected token ")", expecting "->" or "?->" or "{" or "[" on line 6.  
                                                                                                           

      Applied fixers: list_syntax, array_syntax
      ---------- begin diff ----------
--- /tmp/test/testcase/test.php
+++ /tmp/test/testcase/test.php
@@ -1,27 +1,27 @@
 <?php
 
-foreach ($iterable as [
+foreach ($iterable as array(
     'a' => $a,
     'b' => $b,
-]) {
+)) {
     // do something
 }
 
-foreach ($iterable as [
+foreach ($iterable as array(
     $a,
     $b,
-]) {
+)) {
     // do something
 }
 
 $result = $pdo->query("SELECT id, name FROM employees");
-while ([$id, $name] = $result->fetch(PDO::FETCH_NUM)) {
+while (list($id, $name) = $result->fetch(PDO::FETCH_NUM)) {
     echo "id: $id, name: $name\n";
 }
 
-[$a, $b] = $array;
+list($a, $b) = $array;
 
-[
+list(
     $a,
     $b,
-] = $array;
+) = $array;

      ----------- end diff -----------
```

### What is expected

The "short" list syntax in the `foreach` loops should be replaced with a "long" list syntax: `list(/*...*/)`.

### Workaround
One needs to modify the code by hand:
```php
<?php

foreach ($iterable as list(
    'a' => $a,
    'b' => $b,
)) {
    // do something
}

// ...
```

### Additional notices

Enabling only `list_syntax` with "long" syntax (without `array_syntax`) - makes PHP-CS-Fixer ignore `foreach` loops in `test.php`.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

I think https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6064 should cover/fix the issue. Please give it a try and let me know :+1:

**Comment by jacekciach** [comment]
> Hi and thanks for reporting!
> 
> I think #6064 should cover/fix the issue. Please give it a try and let me know +1

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6064#issuecomment-939288560
