### ISSUE TITLE
Fatal error: Class PhpCsFixer\Fixer\StringNotation\StringLengthToEmptyFixer

### ISSUE THREAD

**Issue by lfouks** [FriendsOfPHP/PHP-CS-Fixer#6071]
Hello,

I got this errror, when i run php-cs-fixer since this week:

`Fatal error: Class PhpCsFixer\Fixer\StringNotation\StringLengthToEmptyFixer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PhpCsFixer\Fixer\FixerInterface::isCandidate) in /builds/agsi/free-work-back/vendor/friendsofphp/php-cs-fixer/src/Fixer/StringNotation/StringLengthToEmptyFixer.php on line 25`

  Please describe the problem and provide technical details such as:
   * PHP version: 7.4.24
   * PHP CS Fixer version: 3.2.1
   * the command used to run PHP CS Fixer: `php vendor/bin/php-cs-fixer fix --verbose --diff --dry-run --format=gitlab`
   * the configuration:

    `
    return (new Config())
    ->setRiskyAllowed(true)
    ->registerCustomFixers(new PhpCsFixerCustomFixers\Fixers())
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'doctrine_annotation_array_assignment' => ['operator' => '='],
        'doctrine_annotation_braces' => ['syntax' => 'with_braces', 'ignored_tags' => DOCTRINE_IGNORED_TAGS],
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'class_definition' => ['single_line' => false],
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'compact_nullable_typehint' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => false,
        'general_phpdoc_annotation_remove' => ['annotations' => ['author']],
        'linebreak_after_opening_tag' => true,
        'mb_str_functions' => false,
        'multiline_comment_opening_closing' => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'new_line_for_chained_calls'],
        'native_function_invocation' => true,
        'no_alternative_syntax' => true,
        'no_null_property_initialization' => true,
        'no_php4_constructor' => true,
        'echo_tag_syntax' => true,
        'no_superfluous_elseif' => true,
        'no_superfluous_phpdoc_tags' => true,
        'no_unreachable_default_argument_value' => true,
        'no_unset_on_property' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_class_elements' => false,
        'ordered_imports' => true,
        'php_unit_dedicate_assert' => true,
        'php_unit_strict' => true,
        'php_unit_set_up_tear_down_visibility' => true,
        'phpdoc_add_missing_param_annotation' => false,
        'phpdoc_order' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
        'pow_to_exponentiation' => true,
        'random_api_migration' => true,
        'return_assignment' => true,
        'self_accessor' => false,
        'semicolon_after_instruction' => true,
        'simplified_null_return' => false,
        'single_line_throw' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'string_line_ending' => true,
        'ternary_to_null_coalescing' => true,
        'void_return' => true,
        'yoda_style' => true,
        'no_useless_sprintf' => true,
        PhpCsFixerCustomFixers\Fixer\CommentSurroundedBySpacesFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\DataProviderNameFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\DataProviderReturnTypeFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\InternalClassCasingFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoDuplicatedImportsFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\MultilineCommentOpeningClosingAloneFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoCommentedOutCodeFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoDoctrineMigrationsGeneratedCommentFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoImportFromGlobalNamespaceFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoLeadingSlashInGlobalNamespaceFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoPhpStormGeneratedCommentFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoReferenceInFunctionDefinitionFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoSuperfluousConcatenationFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoUselessCommentFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoUselessDoctrineRepositoryCommentFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpdocNoSuperfluousParamFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpdocParamOrderFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpdocParamTypeFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpUnitNoUselessReturnFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\SingleSpaceAfterStatementFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\SingleSpaceBeforeStatementFixer::name() => true,
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/var/.php_cs.cache')
`

Cheers,

**Comment by nandi95** [comment]
Experiencing the same in github actions but not locally

**Comment by SpacePossum** [comment]
anyone got an idea where to start the bug-hunt on this?

**Comment by kubawerlos** [comment]
Method `isCandidate` is in `AbstractFunctionReferenceFixer`, but only since PHP CS Fixer 3.2.0, so I guess the autoloader somehow loaded it from old version while using `StringLengthToEmptyFixer` from new one.

@lfouks @nandi95 can you check it? Add
```php
var_dump((new \ReflectionClass('PhpCsFixer\Fixer\StringNotation\StringLengthToEmptyFixer'))->getFileName());
var_dump((new \ReflectionClass('PhpCsFixer\AbstractFunctionReferenceFixer'))->getFileName());
```
somewhere (`.php-cs-fixer.php` is a good place) to see where both classes come from?

**Comment by SpacePossum** [comment]
I suggest closing the issue as there nothing to go on and there is no response from the author of the issue.
