### ISSUE TITLE
Separate class atribute blocks with blank line

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#6075]
## Feature request

Although there is the [`class_attributes_separation`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/d5c737c2e18ba502b75b44832b31fe627f82e307/doc/rules/class_notation/class_attributes_separation.rst) fixer to keep similar class attributes separated by a blank line, there seems to be no fixer that would keep such attributes together, but keeps _blocks_ of dissimilar attributes separated by a blank line. That is, there is no way to fix the following:

```diff
class A {
    use Foo;
    use Bar;
+
    const FOO = 'FOO';
    const BAR = 'BAR';
+
    $foo = 'foo';
    $bar = 'bar';
}
```

**Comment by Bilge** [comment]
Just making a note that once again I wanted this feature. A tool added a trait import, but it's stuck to a backing field.

```diff
+    use Query;
     private Statement $statement;
```

There isn't a fixer to keep distinct blocks separate, unless I also agree to separating all trait imports between themselves as well. I don't want to put blank lines between each trait import, just between the block of imports.

**Comment by Bilge** [comment]
As a matter of fact, adding `'trait_import' => 'one'` doesn't even address this because this fixer only applies blank lines _before_ elements, therefore it has to be a rule for properties instead, which has a large and unwanted impact on the entire code base, whether `one` or `only_if_meta` is specified. 

I rather think this issue should be reopened. Just because the existing options are already confusing doesn't seem like a compelling reason to reject this issue, especially since there is no such requirement that any solution would have to be integrated into any existing fixer.

**Comment by SpacePossum** [comment]
>There isn't a fixer to keep distinct blocks separate, unless I also agree to separating all trait imports between themselves as well.

there are two options that do this, "none" and "one".

But before I go write a whole thing here, could you do me a solid favor and write an PHP example that you want to fix, like a before and after? 

I don't need all the context and what not, just that, an example of before and after and I'll try to find the config for you. If I cannot, than and only than, I might understand what people want here and reconsider opening.

Like you give an example, I show you the way to fix and yet still not happy, so no, no reopen until there is an example, thanks
