### ISSUE TITLE
Inline rule skip directives

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#6091]
## Feature request

Sometimes it may be desirable to skip a rule for a particular line. For example, whilst `strict_comparison` may usually be desirable, since some PHP internal objects, such as `DateTime`, have overloaded equality operators, it may be desirable to ignore such "loose" comparisons in these situations.

```php
// @ignore strict_comparison
new DateTime('midnight') == $otherDate->modify('midnight')
```

**Comment by SpacePossum** [comment]
good idea :+1:  yet duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4512 as such closing
