### ISSUE TITLE
"Use" annotation is converted to simple documentation

### ISSUE THREAD

**Issue by adpeyre** [FriendsOfPHP/PHP-CS-Fixer#6092]
Hi !

## Bug report
   - PHP CS Fixer version: 3.2.1
   - Rule: phpdoc_to_comment 

"Use" annotation is converted to simple documentation by PHP CS Fixer.

### Code snippet that reproduces the problem

  ```php
  <?php
  class Test {
     /**
     * @use AutoDiscoveredValuesTrait<string>
     */
    use AutoDiscoveredValuesTrait;

  }
  ```

is tranformed into:

  ```php
  <?php
  class Test {
     /*
     * @use AutoDiscoveredValuesTrait<string>
     */
    use AutoDiscoveredValuesTrait;

  }

**Comment by kubawerlos** [comment]
What kind of standard is this? This is expected behaviour as all supported PHPDoc tags are listed here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.2.1/src/DocBlock/Tag.php#L31-L35

**Comment by adpeyre** [comment]
I had to use this annotation for phpstan.
It's maybe bad but I followed the example given by phpstan. https://github.com/phpstan/phpstan-src/blob/master/tests/PHPStan/Analyser/data/generic-traits.php#L215

**Comment by kubawerlos** [comment]
Where can we see this example? There is nothing about `@use` here: https://phpstan.org/blog/generics-in-php-using-phpdocs

**Comment by RobinDev** [comment]
Same need.

I need to use it when I `use` a templated trait.

Eg: 

```php
/**
 * @template T of object 
 */
trait Example
{
}

class Demo
{
    /** @use Example<ADefinedObject> */
   use Example;
}

**Comment by SpacePossum** [comment]
yes please @RobinDev ;
you want need to update;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/src/Tokenizer/Analyzer/CommentsAnalyzer.php#L109
with
```
        if ($tokens[$nextIndex]->isGivenKind(CT::T_USE_TRAIT)) {
            return true;
        }
```
and update the unit test of the `CommentsAnalyzer`, the unittest of fixer `PhpdocToCommentFixer` and the unit test of `CommentToPhpdocFixer`

**Comment by JoyceBabu** [comment]
I have created PR as suggested by @SpacePossum.

@RobinDev I should have asked first. Hope you don't mind.
