### ISSUE TITLE
Code Inspection does not separate issues by which line they appear on

### ISSUE THREAD

**Issue by tjmurray** [FriendsOfPHP/PHP-CS-Fixer#6098]
I'm using php-cs-fixer (v3.2.1) integrated with PhpStorm (2021.2.3), and unlike other code inspection tools, php-cs-fixer doesn't identify which problems related to which code lines. 

For example, on Line 41 of my file, I am presented with the following warning from PHP CS Fixer:

``` 
L41: PHP CS Fixer: indentation_type, elseif, single_space_after_construct, braces, function_declaration, method_argument_space, no_spaces_after_function_name, no_spaces_inside_parenthesis, array_syntax, concat_space, increment_style, no_alias_language_construct_call, no_singleline_whitespace_before_semicolons, no_whitespace_before_comma_in_array, phpdoc_summary, single_quote, trailing_comma_in_multiline, ternary_operator_spaces, lowercase_keywords, no_trailing_whitespace, no_trailing_whitespace_in_comment, space_after_semicolon, no_whitespace_in_blank_line, no_blank_lines_after_phpdoc, no_extra_blank_lines, binary_operator_spaces, phpdoc_trim_consecutive_blank_line_separation, single_blank_line_at_eof
  ```

i.e. it is merging all warnings across the entire file into a single list, and presenting this long list at every line where there is a warning. Thus this same long/master list gets presented hundreds of times, without being able to identify which issue is from which line.

Whereas the behaviour users need is
``` 
...
L41: PHP CS Fixer: indentation_type
L43: PHP CS Fixer: single_space_after_construct
...
  ```

i.e. just presenting the issue(s) relevant to that line.

Most grateful to know:
- Is this expected behaviour, or is something wrong with my setup?
- If it is expected behaviour, please can we add this as a feature request?

Attaching below a screenshot to show how php-cs-fixer compares to other code inspection tools on my IDE with regard to this topic
<img width="1280" alt="Screenshot 2021-11-08 at 20 05 10" src="https://user-images.githubusercontent.com/30073348/140810992-1500c684-a76c-4ccb-a4cb-a932fe90a2cb.png">

**Comment by SpacePossum** [comment]
Hi and thanks for your detailed report and for using the tool!

Given the design of the tool we are not able to give a report based on linenumbers. We give results on a file level as multiple blocks of code might have be moved around, deleted or added, all during various passes. This makes it impossible to generate a meaningful 2D result in the form of linenumbers. 
I would suggest not given the linenumbers themselves to much thought but to look on the full file diff.
