### ISSUE TITLE
function_typehint_space fixer adds extra spaces on PHP 8.1

### ISSUE THREAD

**Issue by spideyfusion** [FriendsOfPHP/PHP-CS-Fixer#6100]
## Bug report

The [function_typehint_space](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/function_notation/function_typehint_space.rst) fixer adds an extra space for variables passed by reference under PHP 8.1.

* PHP version: 8.1 RC5
* PHP CS Fixer version: 3.2.1

### Code snippet that reproduces the problem

# Input
```php
public function spend(&$field, string$value): void
{
    // ...
}
```

# Output
```php
public function spend(& $field, string $value): void
{
    // ...
}
```

# Expected
```php
public function spend(&$field, string $value): void
{
    // ...
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,

Changes to the tokenizing of code in PHP8.1 has caused this issue. This PHP8.1 is being addressed and discussed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5776
