### ISSUE TITLE
types_spaces removes spaces around multi-catch exceptions

### ISSUE THREAD

**Issue by cl1ck** [FriendsOfPHP/PHP-CS-Fixer#6102]
## Bug report

   * PHP version: 8.0.12
   * PHP CS Fixer version:3.2.1 
   
When types_spaces is set to ['space' => 'none'] PHP CS Fixer incorrectly removes the spaces around [multi-catch exceptions](https://wiki.php.net/rfc/multiple-catch). 

### Code snippet that reproduces the problem

  ```php
<?php

try {
    do_something();
} catch (InvalidArgumentException | RuntimeException $multiCatch) {
    // do nothing
}
```

```diff
      ---------- begin diff ----------
--- /var/www/app/test.php
+++ /var/www/app/test.php
@@ -2,6 +2,6 @@

 try {
     do_something();
-} catch (InvalidArgumentException | RuntimeException $multiCatch) {
+} catch (InvalidArgumentException|RuntimeException $multiCatch) {
     // do nothing
 }

      ----------- end diff -----------
```

**Comment by SpacePossum** [comment]
IIUC for PSR12 we would need some kind of configuration to make sure there is a single space around the `|` for multiple exception types in the catch statement
