### ISSUE TITLE
Transforming some expressions to combined assignments

### ISSUE THREAD

**Issue by elfring** [FriendsOfPHP/PHP-CS-Fixer#6120]
## Feature request
The PHP programming language supports also [the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators").
:thought_balloon: I propose to search for places where variable names can be replaced by combined assignments.
How do you think about to offer corresponding source code analyses and transformations? :thinking:

**Comment by SpacePossum** [comment]
Thanks for suggesting!
I think it is the same as idea as here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3515 , as such closing as a duplicate.

**Comment by elfring** [comment]
:thought_balloon: I became curious how the support for a rule like “[long_to_shorthand_operator](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/60f6820e555660d794873ea6e51e32afae9694de/doc/rules/operator/long_to_shorthand_operator.rst "LongToShorthandOperator - introduction")” will evolve further.

Some programming languages provide special support for the application of advanced regular expressions.
Thus I got the impression that something can be achieved also with a Perl command for such a source code analysis and transformation pattern (in addition to [the “Slevomat Coding Standard”](https://github.com/slevomat/coding-standard#slevomatcodingstandardoperatorsrequirecombinedassignmentoperator- "Requirement")).
The code adjustment safety can be increased by the reuse of more sophisticated software technologies, can't it? :thinking:
