### ISSUE TITLE
Missing rule sets

### ISSUE THREAD

**Issue by riccardobosini** [FriendsOfPHP/PHP-CS-Fixer#6124]
### Description

Sometimes the PSR-12 label in the rule sets drop-down is missing and it can not be selected.
How does it happen? What is the reason?

### Step to reproduce

1. Starting a new php project
2. Add cs-fixer to the composer.json
3. Update composer
4. Open phpStorm settings
5. Go to Editor > Inspections > cs-fixer
6. Try to select PSR-12 in the rule sets drop-down

**Comment by keradus** [comment]
I could only recommend to ensure that you use newest PHP CS Fixer and it's installed in moment you go to IDE settings. If so and the issue is still there, report to your IDE provider.
