### ISSUE TITLE
Feature request: Opt-out of `final_class` for some classes

### ISSUE THREAD

**Issue by d-luk** [FriendsOfPHP/PHP-CS-Fixer#6126]
## Feature request

I am using the [`final_class`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/class_notation/final_class.rst) rule, which is very useful, but for some classes I would like to explicitly disable this fix.

The reason for this is that we are using [PHPUnit mocks](https://phpunit.readthedocs.io/en/9.5/test-doubles.html#mock-objects), which requires the class to be subclassable. We could also solve this by adding interfaces for each of these classes, but that would require us to create an interface for almost every single class in our system, so we would prefer not to do that.

### Possible solution

I noticed that the `final_internal_class` rule includes an [`annotation_exclude`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/class_notation/final_internal_class.rst#annotation_exclude) option. Having a similar option for `final_class` would be perfect.

**Comment by SpacePossum** [comment]
HI and thanks for sharing your idea,

The `final_class` is an alias for `final_internal_class`, it is the exact same thing with the exception that `final_class` does not allow for exceptions while `final_internal_class` does. As such I would recommend swapping out `final_class` in favor of `final_internal_class` in your configuration.

**Comment by d-luk** [comment]
@SpacePossum Based on my testing it does not seem to be an alias, because `final_internal_class` only applies a fix for classes that are marked as `@internal`, which our classes are not. This is why we have to use `final_class` instead of `final_internal_class`.

I have also tried using the [`consider_absent_docblock_as_internal_class`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/class_notation/final_internal_class.rst#consider_absent_docblock_as_internal_class) option, but this also isn't great because even though it will work for classes without a docblock, we still have to add this `@internal` annotation for classes that already have a docblock.

What I would like is a way to enforce that a class is either marked `final` or `@final`, regardless of whether they're `@internal` or not.

**Comment by SpacePossum** [comment]
Here you can see that `final_class` does nothing else than delegating to `final_internal_class` with some hardcoded configuration:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.3.2/src/Fixer/ClassNotation/FinalClassFixer.php#L55

**Comment by d-luk** [comment]
@SpacePossum I didn't know that setting `annotation_include` to an empty array would do that. That indeed solves my problem, thanks!

**Comment by SpacePossum** [comment]
good to hear, thanks for letting me know! :+1:  :)
