### ISSUE TITLE
braces: configure to keep opening brace on same line for classes

### ISSUE THREAD

**Issue by tenzap** [FriendsOfPHP/PHP-CS-Fixer#6134]
Would it be possible to make braces fixer (even) more configurable?

I used it with the "default" configuration, but would like to add an exception on class declaration. For this case I would like it to be on the same line:

PHP CodeSniffer can do this with rule "Generic.Classes.OpeningBraceSameLine"

It would look like this (everything like default, except for class opening)

```diff
--- Original
+++ New
 <?php

class Foo {
-    public function bar($baz) {
-        if ($baz = 900) echo "Hello!";
+    public function bar($baz)
+    {
+        if ($baz = 900) {
+            echo "Hello!";
+        }

-        if ($baz = 9000)
+        if ($baz = 9000) {
             echo "Wait!";
+        }

-        if ($baz == true)
-        {
+        if ($baz == true) {
             echo "Why?";
-        }
-        else
-        {
+        } else {
             echo "Ha?";
         }

-        if (is_array($baz))
-            foreach ($baz as $b)
-            {
+        if (is_array($baz)) {
+            foreach ($baz as $b) {
                 echo $b;
             }
+        }
     }
 }
```

Or is there any easy way to override a rule in the config file?

This is with v3.3.2

**Comment by SpacePossum** [comment]
Can you try `curly_braces_position` ;  https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/doc/rules/basic/curly_braces_position.rst  
I think it has all the options you need now @tenzap

**Comment by julienfalque** [comment]
Yep, the `classes_opening_brace` option should do what you want.
