### ISSUE TITLE
Not compatible with symfony/event-dispatcher 6.0.0

### ISSUE THREAD

**Issue by achmedislamic** [FriendsOfPHP/PHP-CS-Fixer#6140]
The latest php-cs-fixer isn't compatible with event-dispatcher version 6.0.0. I currently don't have a skill to submit PR and I hope someone will fix it. I currently install the 5.4 version.

**Comment by julienfalque** [comment]
Already handled in #6095.

Meanwhile, if you installed PHP CS Fixer among your app's dependencies, I suggest you install it differently, e.g. using a dedicated composer.json file to avoid conflicts.
