### ISSUE TITLE
no_trailing_comma_in_singleline for method calls and argument list

### ISSUE THREAD

**Issue by xorik** [FriendsOfPHP/PHP-CS-Fixer#6141]
## Rule request

CS fixer has rules `no_trailing_comma_in_singleline` for array and list, but not for method calls and method arguments

### Code snippet that shows how the rule would fix PHP code

Before:
  ```php
  <?php
  public function convert(array $content, ): string
  {
     $this->foo($content, );
  }
  ```

After:
  ```php
  <?php
  public function convert(array $content): string
  {
     $this->foo($content);
  }
  ```

**Comment by SpacePossum** [comment]
we are also missing for after `use` `<?php $a = static function() use ($a, $b, ){};` and `<?php function foo ($a,){}` , so basically any form of function signature.
