### ISSUE TITLE
php-cs-fixer doesn't have php 8.1 as a valid php version for use.

### ISSUE THREAD

**Issue by bobstrecansky** [FriendsOfPHP/PHP-CS-Fixer#6145]
We are using php-cs-fixer in https://github.com/open-telemetry/opentelemetry-php/

We are currently attempting to add PHP 8.1 to our testing matrix, and we noticed that when we attempted to run php-cs-fixer on php 8.1 code, we got an error:

```
Run vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --stop-on-violation --using-cache=no -vvv
PHP needs to be a minimum version of PHP 7.2.5 and maximum version of PHP 8.0.*.
Current PHP version: 8.1.0.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at https://github.com/FriendsOfPHP/PHP-CS-Fixer .
Error: Process completed with exit code 1.
```

I believe that php 8.1 needs to be added to the composer.json here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json#L17

I have created the following PR to attempt to address this:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6144

**Comment by keradus** [comment]
PHP 8.1 is not fully supported yet - #5891 - due to BC breaking changes in PHP 8.1 internal tokenizer and new language syntax.

closing as duplicate.
