### ISSUE TITLE
Version 4 BC idea list

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#6155]
Hi all,

Basically I would like to share a list of v4 BC ideas I got. Mainly to get feedback and see what others think.

------

I would like to have custom tokens for all different types of usages of the following symbols.

`:` :
 - `goto`
 - alternative syntax control structure
 - before return type hint in function signature (`T_TYPE_COLON`, listed here for completeness)
 - named argument (`CT::T_NAMED_ARGUMENT_COLON`, listed here for completeness)
 - in use of `switch-case`

`&`:
 - pass by reference in signature and  reference variable name (`$b = &$a;`)
 - bitwise operator
 - type intersect (`CT::T_TYPE_INTERSECTION`, listed here for completeness)
 - return reference (`CT::T_RETURN_REF`, listed here for completeness)

`|` :
 - bitwise operator
 - type alternation ([CT::T_TYPE_ALTERNATION, listed here for completeness)

------

I would like the exit code to changed when a file got fixed or needs fixing. If the fix is done successful the tool currently ends with exit code 0 unless running with the `dry-run` flag, I would like this exception to go away and not exit with code 0.

------

In general to have a look at single use classes to see if it makes sense to not merge these (for example `NamespacedStringTokenGenerator` ) with the caller/use class.

------

Deprecate FinalClassFixer in favor of FinalInternalClassFixer  - https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6128
Drop alternative syntax by default for all build in fixers - https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6003

------

start looking for external library managing types parsing for PHPDocs

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6063#discussion_r731317220

------

CT type of the `enum` `case` vs. `swtich` `case`

**Comment by kubawerlos** [comment]
This ☝🏼 and the priorities.

I'm thinking about creating in `v3` new interface like:
```php
interface NewFixerInterface extends FixerInfertace
{
    public function getFixersToRunAfter(): array {}
}
```
and deprecate `FixerInfertace::getPriority` - in 4.0 `NewFixerInterface` will be removed and `getFixersToRunAfter` will go to `FixerInfertace` to replace `getPriority`.

The runner then will get the list of fixers somehow sorted (like we have the fixer that always run first) and after running every fixer will have a list of fixers still to run and will update that list with `getFixersToRunAfter` results.

This will solve problem of circular priorities which now cannot be addressed. But, it will bring new problems - performance (how much will that slow down the fixer? Some fixers might need to run multiple times) and how to handle situation when set of fixers reverts each others and are still on a list of fixers to be run?

---------------

Or, maybe we do not want to have `getFixersToRunAfter`, but `getFixersToRunBefore` (similarly it will replace `getPriority` in `v4`) - and we build the set to run with the information which fixer "blocks" which (when fixer is unblocking other fixers) - this way we keep the same performance, but will still have circular dependencies problem. This solution basically replace numbers from `getPriority` with list of fixers.

**Comment by keradus** [comment]
proposal - let's create a label/milestone marker for BC breaks and have a way to discuss each idea separately. otherwise it will be a mess with constant changing of WHICH bc break we discuss

**Comment by kubawerlos** [comment]
@SpacePossum for the transformers what about BC break for the interface? `NameQualifiedTransformer` is a killer for large files, such as https://raw.githubusercontent.com/sabbelasichon/typo3-rector/v0.11.32/config/composer/typo3-87-composer-packages-extensions.php

It's not a problem if 4.0 will be fot PHP 8+ only.

**Comment by WinterSilence** [comment]
1. Mark fixes supports alternative syntax like as "risky rule" (i.e. "alt syntax rule") because in most case alternative syntax using only in "views" files and views don't mix syntaxes.

2. Need high-level API/tools for working with code as with abstraction. 
2.1. Create high-level API to parse PHP code as nested tree or use something like [AST parser](https://github.com/nikic/php-parser).
2.2. Get parent/context `Reflection` for AST leaves (namespace, class/interface/trait or function/method)
2.3. Get `Reflection` for AST leaves of native PHP stuff by [stubs](https://github.com/JetBrains/phpstorm-stubs) (if function/class not exists in using version of PHP)
