### ISSUE TITLE
Not expected output with `FunctionTypehintSpaceFixer`

### ISSUE THREAD

**Issue by tarlepp** [FriendsOfPHP/PHP-CS-Fixer#6164]
## Bug report
 * PHP version: PHP 8.1.0 (cli) (built: Dec  2 2021 12:28:12) (NTS)
 * PHP CS Fixer version: PHP CS Fixer 3.4.0 Si! by Fabien Potencier and Dariusz Ruminski

I'm seeing following "error" after I updated to PHP 8.1, if I'm using PHP 7.4 I don't see this issue.

```php
-    public function afterFindOne(string &$id, ?EntityInterface $entity = null): void
+    public function afterFindOne(string & $id, ?EntityInterface $entity = null): void

Applied checkers:

 * PhpCsFixer\Fixer\FunctionNotation\FunctionTypehintSpaceFixer
```

I would expected that kind of code change is not needed - or is there some option for this?

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,

It is strange as 3.4.0 was aimed to fix PHP8.1 issues and locally I cannot reproduce this;

```
PHP CS Fixer 3.4.0 Si! by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.1.0beta3
```

**Comment by kubawerlos** [comment]
I cannot reproduce it as well. We have https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/tests/Fixer/FunctionNotation/FunctionTypehintSpaceFixerTest.php#L70 to prove the space is not added after `&`.

**Comment by tarlepp** [comment]
Thanks for replies @SpacePossum and @kubawerlos - I did some deeper analyzis and looks like this is an error on my end.

I'm using ECS and looks like itself doesn't use the correct version of PHP CS fixer - and I was confused to show that `3.4.0` version because I did have this installed globally...

Closing this now, but really big thanks to both of you for quick answers!

**Comment by SpacePossum** [comment]
thanks for reporting back @tarlepp ,nice to see this resolved :) :+1:
