### ISSUE TITLE
GitlabReporter: Output format mismatch with specification

### ISSUE THREAD

**Issue by TeroBlaZe** [FriendsOfPHP/PHP-CS-Fixer#6166]
## Bug report

According to the spec https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#issues the Gitlab reporter is missing some required fields.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/56d83994b67d384d4809637b4bce2a5a6d71d15b/src/Console/Report/FixReport/GitlabReporter.php#L44-L51

For this reason Gitlab's checkstyle report doesn't work properly always showing "No changes to code quality".

**Comment by keradus** [comment]
Hey, PHP CS Fixer does not track the numbers at all, as the main goal of tool is to fix violations and not ask user to manually do so. If you want to add this feature, please raise a technical RFC how you would like to add line-numbers to Checksum format.
(hint: the closest place to check modified line is produced udiff

**Comment by Clement-B** [comment]
@TeroBlaZe Just submit this bug #6175, maybe you were expecting the same issue ?

**Comment by TeroBlaZe** [comment]
> @TeroBlaZe Just submit this bug #6175, maybe you were expecting the same issue ?

Yes. That is exactly what I meant. It seems you find exact reason why Gitlab didn't show details.

**Comment by keradus** [comment]
closing as duplicate then
