### ISSUE TITLE
Rule `php_unit_dedicate_assert` should not use `assertInternalType` anymore.

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#6179]
Hi,

I just noticed that PHP CS Fixer replace this:

```diff
-        self::assertTrue(is_resource($file));
+        self::assertInternalType('resource', $file);
```

However, the method `TestCase::assertInternalType` does not exist anymore in PHPUnit, [it has been deprecated](https://github.com/sebastianbergmann/phpunit/issues/3369).

On top of that, if just like me you're using the function [`is_resource`](https://www.php.net/manual/en/function.is-resource.php) to check if a resource is open or not, then replacing it with `TestCase::assertInternalType` is wrong because it doesn't check that specific thing. Why? Because `TestCase::assertInternalType` is based on [`getType()`](https://www.php.net/manual/en/function.gettype.php) and does not check the status of the resource.

**Comment by keradus** [comment]
Thanks for the report!

Looks like we have a new feature of `assertInternalType` -> `assertIsResource` ;)

I believe it's a quirk that you checked the resources was open, to be honest. Looks like you check the side effect

**Comment by keradus** [comment]
actually we have that rule already: `php_unit_dedicate_assert_internal_type`.
how you decided to use `php_unit_dedicate_assert` only?

**Comment by drupol** [comment]
Hi Darius,

Actually I was testing if the resource was still open or not, this is why I why using:

```php
self::assertTrue(is_resource($file));
```

For the rest of your questions, I'll get back to you as soon as possible.

**Comment by drupol** [comment]
@keradus both rules are existing, I can then use one or another, no ?

**Comment by SpacePossum** [comment]
if you want this;
```diff
-        self::assertTrue(is_resource($file));
+        self::assertIsResource($file);

```

you'll need both `php_unit_dedicate_assert` and `php_unit_dedicate_assert_internal_type`

**Comment by drupol** [comment]
But that's the thing, this is definitely wrong because it has a different meaning.

When using the function [`is_resource`](https://www.php.net/manual/en/function.is-resource.php) to check if a resource is open or not, then replacing it with `TestCase::assertInternalType` is wrong because it doesn't check that specific thing.

`TestCase::assertInternalType` is based on [`getType()`](https://www.php.net/manual/en/function.gettype.php) and does not check the status of the resource.

**Comment by SpacePossum** [comment]
but replacing with `assertIsResource` is correct, or also not?

**Comment by drupol** [comment]
* `assertIsResource`: assert that a variable is a `resource`, nothing else. It is based on `gettype()` only.
* `\is_resource()`: assert that a variable is a `resource` (`gettype`) AND that the `resource` is open or closed. (https://www.php.net/manual/en/function.is-resource.php)

For me these two are completely different and should not be mixed.

**Comment by SpacePossum** [comment]
ok, check, I see now :+1: 
for reference https://github.com/sebastianbergmann/phpunit/blob/9.5.13/src/Framework/Constraint/Type/IsType.php#L189

not sure how to proceed, no longer do the change, or do the change but update the docs about this, any preferences by anyone?

**Comment by drupol** [comment]
IMHO: I would just no longer do the change.

**Comment by SpacePossum** [comment]
sounds good to me, can you prepare a PR for it maybe? let me know if not, no problem than I'll put it on my backlog

**Comment by drupol** [comment]
I will try... I don't promise you anything.
