### ISSUE TITLE
How to make comments not indented?

### ISSUE THREAD

**Issue by Yurunsoft** [FriendsOfPHP/PHP-CS-Fixer#6208]
## Support question

How to make comments not indented?

**code:**

```php
<?php

declare(strict_types=1);

function test(bool $a)
{
// test-1
    if ($a) {
        return 1;
    } else {
        return 0;
    }
// test-2
}
```

**fix in `3.4.0`:**

```shell
<?php

declare(strict_types=1);

function test(bool $a)
{
    // test-1
    if ($a) {
        return 1;
    } else {
        return 0;
    }
    // test-2
}

```

**expected:**

```php
<?php

declare(strict_types=1);

function test(bool $a)
{
// test-1
    if ($a) {
        return 1;
    } else {
        return 0;
    }
// test-2
}
```

**Comment by SpacePossum** [comment]
Hi,
This change is done by the `braces` rule, so if you don't want this change to happen you would have to disable that rule.
The style with the not-indent comments is not something we actively (going to) support.

If you want more details I about what is going on I suggest to run the tool with `-vvv` to get all the details about applied rules.
Thanks for your question, good luck!
