### ISSUE TITLE
position_after_control_structures

### ISSUE THREAD

**Issue by LTaooo** [FriendsOfPHP/PHP-CS-Fixer#6226]
## Feature request

How to not write braces when the if statement has only one line

`if($a) $b = 1;`

**Comment by SpacePossum** [comment]
Hi, 
Currently we do have a rule to do this.
We do not know of bigger community that uses this style or widely applied standard that defines it. As such we advice to either not use this style or create a 3rd party/custom rule for this. 
Thanks for your question!
