### ISSUE TITLE
types_spaces rule, spacing between types in a catch block and PSR-12 compatibility?

### ISSUE THREAD

**Issue by webignition** [FriendsOfPHP/PHP-CS-Fixer#6228]
Consider the following example:

```php
class Foo
{
    public function go(string|int $input): void
    {
        try {
            // ...
        } catch (\RuntimeException | \LogicException $exception) {
            // ...
        }
    }
}
```

The [`types_spaces`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/whitespace/types_spaces.rst#rule-types_spaces) rule will, by default, remove spaces between types in composite (union, intersection) types. Having no spaces between types within composite types seems to be the de-facto standard as presented in the [union types v2 rfc](https://wiki.php.net/rfc/union_types_v2).

This rule also removes spaces between [multiple exception types in a single catch block](https://www.php.net/manual/en/language.exceptions.php#language.exceptions.catch). The above example shows the code before such spaces are removed and shows the code as PSR-12 would like it to be.

The `types_spaces` rule handles the composite types aspect just fine but then breaks PSR-12 catch block type spacing.

Finally my question: 

Is there a way to configure php-cs-fixer such that `string | int` is always fixed to `string|int` but `\RuntimeException | \LogicException`, only when in a catch block, is left as-is?

**Comment by webignition** [comment]
My preference would be for `types_spaces` being split into two rules. My reason is that the catching of multiple exceptions within a single catch block (`catch (FooException | BarException)`) does not constitute a union type and instead it merely looks awfully like one (which does introduce a little understandable confusion).

In support of this:

- The ability to catch multiple exception types in a single catch block (`catch (FooException | BarException)`) was introduced in PHP 7.1. This predates the introduction of union types in PHP 8.0. This may suggest that `catch (FooException | BarException)` is not utilising a union type but merely uses the same syntax. By definition, this was not a union type when introduced (perhaps).

- The [Union Types 2.0 RFC](https://wiki.php.net/rfc/union_types_v2) makes no mention of catch blocks, despite otherwise providing a variety of precise example usages. This may also suggest that `catch (FooException | BarException)` is not utilising a union type.

- PHP 8.1 introduced intersection types. In all cases where a union type is syntactically valid (`function foobar(Foo|Bar $x)` an intersection type is syntactically valid (`function foobar(Foo&Bar $x)`. In PHP 8.1, `catch (FooException & BarException)` is not valid. That the pipe character cannot be swapped with an ampersand character without producing invalid code also suggests that `catch (FooException | BarException)` is not utilising a union type.

It may be the case that treating the `FooException | BarException` within a catch block as being a union type when perhaps it is not may lead to future issues where other considerations may apply only to union and intersection types. Whether this is a reasonable concern I can't say since my familiarity with the php-cs-fixer codebase is minimal to say the least.

In practical terms I'd be happy with whatever requires the least amount of effort for things to work nicely!

**Comment by julienfalque** [comment]
I don't really see the point of determining whether `Foo | Bar` is a union type when used in a `catch`. IMO it is, at least practically, and thus the same style as with other usages should be applied. But I understand that following PSR-12 examples' specific style can be preferred. I think the easiest solution would be a dedicated option as @SpacePossum suggested.

**Comment by VincentLanglet** [comment]
> My preference would be for types_spaces being split into two rules.

I agree, but I'm afraid it would be considered as a BC-break when the option could be BC.

I'll try to take a look at

**Comment by SpacePossum** [comment]
options are no BC breaks as long as the default of the new option makes the rule act as it is currently doing, i.e. it would be a way to opt-in on your new logic

**Comment by SpacePossum** [comment]
Closing as duplicated of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6102
Proposed fix here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6312 , review is much welcome
