### ISSUE TITLE
`nullable_type_declaration_for_default_null_value` should not fix readonly constructor promoted properties if set to false

### ISSUE THREAD

**Issue by devmrcl** [FriendsOfPHP/PHP-CS-Fixer#6239]
### Rule
`'nullable_type_declaration_for_default_null_value' => ['use_nullable_type_declaration' => false]`

### Description
Latest version 3.5 "fixes" readonly promoted properties with the given rule.   
Rule should not touch the code like with non-readonly promoted properties.

### Code snippet that reproduces the problem

  ```php
  class SomeClass
  {
     public function __construct(
        public ?string $string = null,
        public readonly ?string $readonlyString = null,
     ){}
  }
  ```

Diff output
  ```php
public function __construct(
           public ?string $string = null,
-        public readonly ?string $readonlyString = null,
+        public readonly string $readonlyString = null,
)
```

### Possible fix

Add check for `T_READONLY`

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/333f15e07c866e33e2765e84ba1e0b88e6a3af3b/src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php#L139-L152

**Comment by SpacePossum** [comment]
Thanks for reporting @devmrcl , proposed fix is here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6265 , please review if you want : )
