### ISSUE TITLE
no_superfluous_phpdoc_tags removes phpdoc entry if ... used in method signature

### ISSUE THREAD

**Issue by sakarikl** [FriendsOfPHP/PHP-CS-Fixer#6240]
## Bug report

PHP CS Fixer 3.5.0 The Creation by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.14

### Code snippet that reproduces the problem

```php
<?php

/**
 * @param int    $value This is a comment.
 * @param string ...$values This is information.
 */
function test(int $value, string ...$values)
{
}

```

is changed to

```php
<?php

/**
 * @param int $value This is a comment.
 */
function test(int $value, string ...$values)
{
}

```

**Comment by sakarikl** [comment]
```php
<?php

/**
 * @param int $value  This is a comment.
 * @param $second This is information.
 */
function test($value, &$second)
{
}
```

is also converted to 

```php
<?php

/**
 * @param int $value This is a comment.
 */
function test($value, &$second)
{
}

```

**Comment by donatj** [comment]
Just hit this myself just now. It's doing the same thing for `&$param`

![image](https://user-images.githubusercontent.com/133747/149576749-60ff84d6-92bb-497a-a7a8-77125b9bbb91.png)

**Comment by kubawerlos** [comment]
Indeed, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6241 addresses both, reference and splat operator.
