### ISSUE TITLE
nullable_type_declaration_for_default_null_value does not support readonly peroperties

### ISSUE THREAD

**Issue by vudaltsov** [FriendsOfPHP/PHP-CS-Fixer#6247]
## Bug report

PHP 8.1.1
PHP CS Fixer 3.4.0 Si!

### Code snippet that reproduces the problem

```php
final class A
{
    public function __construct(
        private readonly ?int $b = null,
    ) {
    }
}
```

gives error `[PhpCsFixer\Linter\LintingException] Parse error: syntax error, unexpected token "readonly" on line 10.`

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,

I think this is fixed in version 3.5 (just tested on 3.4, 3.5 and master), 
please update and try again, 
let me know if this doesn't tell I'll reopen this.
