### ISSUE TITLE
Use of named parameters

### ISSUE THREAD

**Issue by jdescelliers** [FriendsOfPHP/PHP-CS-Fixer#6255]
Hi,

ever since named params existed, I found useful to use them as it makes passing parameters without having to know their order.

Is there any plans to implement this?

**Comment by SpacePossum** [comment]
I'm closing this as there is no response from the author and not enough information to move this forward.

**Comment by jdescelliers** [comment]
To enforce usage of named parameters on every function.

**Comment by nesl247** [comment]
Any chance this can be reopened? I would love to see enforcement of named parameters in our code base.

**Comment by kubawerlos** [comment]
@nesl247 no need for reopening, you can simply raise PR with the feature.

**Comment by julienfalque** [comment]
Actually I'm not sure this is even possible: the current implementation of PHP CS Fixer does not allow it to perform reflection on the symbols in the code, it only processes tokens on a per-file basis.

**Comment by savinmikhail** [comment]
Hi guys, I just created Rector rule to do this. Check it out: https://github.com/savinmikhail/AddNamedArgumentsRector

**Comment by keradus** [comment]
Thanks for sharing!
for those who will use it, please ensure you rely on names that are covered under BC promise. lot of libraries are not counting argument names under BC promise
