### ISSUE TITLE
Jetbrains integration does not validate anymore in v3.5.0

### ISSUE THREAD

**Issue by florianajir** [FriendsOfPHP/PHP-CS-Fixer#6260]
## Bug report
The validate button return is not valid anymore. Don't know if it's related but there's a repeated instability bug during inspection.

**Comment by keradus** [comment]
Does it happen to you on all files, or only on concrete file to be checked?
If all files, please reach out to provider of your IDE or plugin, if integration is via plugin.
If single fail is failing only, please share the problematic file and your PHP CS Fixer config file, could be that Fixer is crashing on it.

**Comment by florianajir** [comment]
Seems to be working today, idk if un update of the plugin has been made but issue is not relevant anymore,
Thanks for you reply, have a good day
