### ISSUE TITLE
ClassReferenceNameCasingFixer description is misleading

### ISSUE THREAD

**Issue by caugner** [FriendsOfPHP/PHP-CS-Fixer#6276]
## Bug report

The description states:

> When referencing a class it must be written using the correct casing.

However, according to [this comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3969#issuecomment-1030641773), it only affects **internal** classes.

To avoid wrong expectations, the description should state:

> When referencing an *internal* class it must be written using the correct casing.

### Code snippet that reproduces the problem

(n/a)

**Comment by SpacePossum** [comment]
Hi and thank for sharing your experience,

I'm ok if the description is a bit more explicit, can you open a PR with the improvement?
