### ISSUE TITLE
version 3.6.0 class_reference_name_casing will lowercase the constant

### ISSUE THREAD

**Issue by bbsweb** [FriendsOfPHP/PHP-CS-Fixer#6278]
## Bug report

PHP CS Fixer version: v3.6.0 Roe Deer
PHP version: 8.1.2
PHP ext: swoole

It works well in version 3.5, but when update to 3.6.0 it breaks my code.
because of the config `'class_reference_name_casing' => true` in the ruleset `@PhpCsFixer`

```php
<?php

declare(strict_types=1);

return [
    - 'mode' => SWOOLE_PROCESS,
    + 'mode' => swoole_process,
];
```

( `SWOOLE_PROCESS` is a constant defined by php swoole extentsion )

I dont know why it will change `SWOOLE_PROCESS` to `swoole_process`

**Comment by SpacePossum** [comment]
Thanks fro reporting :+1: ,
a fix has been merged for it and will ship in the release
