### ISSUE TITLE
class_reference_name_casing is confused by class with the same name

### ISSUE THREAD

**Issue by VincentLanglet** [FriendsOfPHP/PHP-CS-Fixer#6282]
## Bug report

Hi @SpacePossum, there is another bug with the `class_reference_name_casing` rule.

In the following automatic PR there is a false positive error from PHP CS Fixer
https://github.com/sonata-project/exporter/pull/572

### Code snippet that reproduces the problem

  ```php
  <?php

use Sonata\Exporter\Writer\XmlWriter;

$services->set('sonata.exporter.writer.xml', XmlWriter::class);
  ```

The fixer is proposing to change to `XMLWriter::class` because of the native class https://www.php.net/manual/fr/book.xmlwriter.php

**Comment by SpacePossum** [comment]
thanks for reporting, please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6283

**Comment by VincentLanglet** [comment]
Thanks a lot @SpacePossum. Will a 3.6.1 version be planned ?
