### ISSUE TITLE
Specifying a destination directory

### ISSUE THREAD

**Issue by onet4** [FriendsOfPHP/PHP-CS-Fixer#6297]
## Support question

Is there a way to specify an output directory for formatted code files?

**Comment by SpacePossum** [comment]
Hi,

There is no such option, you can find all options in the docs;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/doc/usage.rst

The tool will write back in the files it fixed, or you can run it in dry-run and use any type of reporting and/or use the `dff` option to generate a nice udiff.
