### ISSUE TITLE
Store formatted code in a variable in a PHP script

### ISSUE THREAD

**Issue by onet4** [FriendsOfPHP/PHP-CS-Fixer#6299]
## Support question

I know PHP CS Fixer is designed to be run from console but is there a way to run it within a PHP script and store formatted code to a variable by passing a string of PHP code? 

Something like,

```php
$phpCsFixer = new \PhpCsFixer\Application();
$fixedCode  = $phpCsFixer->getFormatted( $codeToFix );
```

**Comment by onet4** [comment]
Yes. Thanks for the link. So it seems not possible as it now stands.

**Comment by SpacePossum** [comment]
Currently, it is, but it is not easiest API as discussed in 5728. The fixer itself reads a fie to string, fixes it and writes that string back to file, so it can be done. Lets keep the talks in one ticket though :+1:
