### ISSUE TITLE
`public` is always added to constants despite the `visibility_required` rule

### ISSUE THREAD

**Issue by onet4** [FriendsOfPHP/PHP-CS-Fixer#6311]
## Bug report

It seems `visibility_required` always adds `public` to constants in spite of a set rule.

### Code to Format

```php
<?php
class Test {
    const FOO = 'bar';
}
```

with the following rule

```php
    'visibility_required' => [
        ['elements' => ['method', 'property']],  // `const` is omitted
    ],
```

### Actual Result
```
<?php

class Test
{
    public const FOO = 'bar';
}
```

### Expected Result
```
<?php

class Test
{
    const FOO = 'bar';
}
```

## Environment
- PHP 7.4.19
- PHP 8.0.9
- PHP CS Fixer 3.6.0 Roe Deer by Fabien Potencier and Dariusz Ruminski.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting,

I cannot replicate the issue on latest `master`, however I did notice that your configuration is a bit off.
The option is wrapped in a second array, I think it should be:

```
    'visibility_required' => 
        ['elements' => ['method', 'property']],  // `const` is omitted
    ,
```

Can you update the config and re-run the tool with `-vvv` added and share the output?

**Comment by onet4** [comment]
Indeed, the posted rule had an error but even though it is corrected as follows, still I get the same result.

```php
    'visibility_required' => [
        'elements' => ['method', 'property'],
    ],
```

**Comment by onet4** [comment]
Sorry, it is working fine. I was merging the rule with the default options and it was the cause.

**Comment by SpacePossum** [comment]
Thanks for letting us know :+1:   : )
