### ISSUE TITLE
binary_operator_spaces and intersection types

### ISSUE THREAD

**Issue by a-menshchikov** [FriendsOfPHP/PHP-CS-Fixer#6317]
PHP version: 8.1.3
PHP-CS-Fixer version: 3.6.0

### Code snippet that reproduces the problem

```php
<?php
function test(A&B $var): void
{}
```

An intersection type `A&B` should not be separated by space according `binary_operator_spaces` rule, but now that is.

**Comment by SpacePossum** [comment]
Thanks for reporting.
I've made a proposal to fix the issue here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6318 , if you can and want please review :)

**Comment by a-menshchikov** [comment]
@SpacePossum thank you!
I have checked it and it works. :+1:

**Comment by SpacePossum** [comment]
I think this issue can be closed since https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6414 was merged
