### ISSUE TITLE
const "ERROR" gets lowercased to "Error"

### ISSUE THREAD

**Issue by W0rma** [FriendsOfPHP/PHP-CS-Fixer#6330]
## Bug report

PHP CS Fixer version: v3.7.0
PHP Version: 8.0.16
Config: `'class_reference_name_casing' => true`

```
<?php

const ERROR = 'error';
const INFO = 'info';

function foo(string $bar): void
{
    echo $bar;
}

foo(ERROR);
foo(INFO);
```

The rule `class_reference_name_casing` changes `foo(ERROR)` to `foo(Error)`.
`foo(INFO)` is _not_ changed.

Before v3.6.0 `foo(ERROR)` was not changed as well.

**Comment by SpacePossum** [comment]
thanks for reporting, proposed fix is here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6331

**Comment by W0rma** [comment]
Wow, that was fast!

I can confirm that the PR solves the issue in my project.
