### ISSUE TITLE
Brew issue Upgrading  3.6.0 -> 3.7.0

### ISSUE THREAD

**Issue by carlos-andres** [FriendsOfPHP/PHP-CS-Fixer#6332]
### Code snippet that reproduces the problem
 
```shell
brew upgrade
```

I just try to upgrade PHP-CS-Fixer Version using brew on MacOs Big Sur, all my other dependencies are updated but got this issue as see on the image attached.

tks for any help in this case (i don't want unistall existing php with my custom dev settings)

<img width="750" alt="image" src="https://user-images.githubusercontent.com/5489747/157274876-5d12c6cc-8b12-405e-a84d-f3bb6d292b6d.png">

**Comment by keradus** [comment]
Hey @carlos-andres !
I'm afraid we cannot help here - we are not the provider of the brew formula. Please reach out to it's provider.
