### ISSUE TITLE
Opening brace on next line ignored for multiline function declaration and if-statements 

### ISSUE THREAD

**Issue by SuperDJ** [FriendsOfPHP/PHP-CS-Fixer#6341]
## Bug report

- PHP: 8.0
- php-cs-fixer: 3.7
- config:

```php
'braces'                                           => [
            'allow_single_line_anonymous_class_with_empty_body' => false,
            'allow_single_line_closure'                         => false,
            'position_after_functions_and_oop_constructs'       => 'next',
            'position_after_control_structures'                 => 'next',
            'position_after_anonymous_constructs'               => 'next',
        ],
```

### Code snippet that reproduces the problem

**Provided and expected**
```php
function example(
  $argument_1,
  $argument_2
): void 
{
   if(
      (is_numeric($argument_1) && $argument_1 >= 10) ||
      (is_numeric($argument_2) && $argument_2 <= 10) 
   ) 
   {
   }
}
```
**Output:**
```php
function example(
  $argument_1,
  $argument_2
): void {
   if(
      (is_numeric($argument_1) && $argument_1 >= 10) ||
      (is_numeric($argument_2) && $argument_2 <= 10)
   ) {
   }
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for taking the time to open this issue.

The `braces` rule has been refactored and the change you see is now the responsibility of `curly_braces_position`.
The new option of it have been named `next_line_unless_newline_at_signature_end`  to clarify what it will do.

The CS you expect/want is not supported in the core of this project. It is not likely support will be added as the CS is not part of standard or bigger (F)OSS community we know.

I suggest closing this issue (cc @julienfalque )
