### ISSUE TITLE
It appears that -> is seen as a operator when method chaining

### ISSUE THREAD

**Issue by SuperDJ** [FriendsOfPHP/PHP-CS-Fixer#6342]
## Bug report

- PHP: 8.0
- php-cs-fixer: 3.7
- config:
```php
'operator_linebreak' => [
            'position'      => 'end',
        ]
```

### Code snippet that reproduces the problem

**Provided and expected**
```php
<?php
$methods
   ->foo()
  ->bar();
```

**Output**
```php
<?php
$methods->
  foo()->
  bar();
```

There is a workaround, although I'm not quite sure about possible other issues it causes:
```php
'operator_linebreak' => [
           'only_booleans' => true,
            'position'      => 'end',
        ]
```

**Comment by kubawerlos** [comment]
> It appears that -> is seen as a operator when method chaining

Yes, object operator is seen as an operator, because it is an operator.

**Comment by SuperDJ** [comment]
@kubawerlos Perhaps it's a good idea to add the operators in the `operator_linebreak` rule docs.

**Comment by kubawerlos** [comment]
@SuperDJ could be, do not hesitate with raising PR.
