### ISSUE TITLE
PHP versions greater than 8.0.* are unsupported

### ISSUE THREAD

**Issue by jamesrweb** [FriendsOfPHP/PHP-CS-Fixer#6353]
## Bug report

When running the fixer with a PHP version greater than `8.0.*` an exception is thrown with the following message:

```text
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 8.0.*.
Current PHP version: 8.1.3.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at https://github.com/FriendsOfPHP/PHP-CS-Fixer .
```

I would expect any version greater than or equal to `7.4.*` to be supported personally and since `8.0.*` is supported, I think that the supported versions should actually be `7.4.*` to `8.*.*` since minor and patch versions shouldn't break the formatting rules currently in place.

### Code snippet that reproduces the problem

Execute the fixer on any PHP version greater than `8.0.*`.

**Comment by kubawerlos** [comment]
Please, update your PHP CS Fixer version, in the latest release all 8 series version that are below 8.2.0 are supported: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.8.0/php-cs-fixer#L43

> since minor and patch versions shouldn't break the formatting rules currently in place

I'm sorry, are you new to PHP or not aware how new features are introduced? All new minor releases in 7 and 8 series introduced  new operators, tokens or syntax changes - see dedicated tests for PHP versions here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v3.8.0/tests/Fixtures/Integration/misc

**Comment by keradus** [comment]
it's very easy to fall into trap that PHP as a language follow SEMVER, especially for the interface of sth that is used only by very few projects like PHP tokenizer - no worry @jamesrweb , i fall into that trap myself one day ;)

Like Kuba said, just upgrade the Fixer and it will solve 8.1.x compatibility for you. But for each upcoming 8.x.0, we will need to put effort to make it compatible each time

**Comment by jamesrweb** [comment]
@keradus @kubawerlos I have been using PHP for abut a decade now but there is a lot of inconsistency, yes. I was assuming since the PHP 7 move that SEMVER was to be respected but clearly not. Either way, thanks for the feedback and input 😄!

**Comment by kubawerlos** [comment]
@jamesrweb if PHP follow SEMVER we'd have bigger version than in Java 😄
