### ISSUE TITLE
Why stream into stdErr when writing the getLongVersion from Application class?

### ISSUE THREAD

**Issue by iammati** [FriendsOfPHP/PHP-CS-Fixer#6364]
## Support question

_Since I'm not owning a Gitter account nor want to create one just for this one simple question I hope it'll be fine._

This is more likely a generic question rather than requesting any kind of support.
I'm writing a little php-linter as npm-package and noted that - when executing via JS the `php-cs-fixer fix` command - some version-related output is streamed into stderr instead of stdout and I'd like to know why.

![image](https://user-images.githubusercontent.com/41418763/163287955-608c6725-2470-4b2f-aa46-d16122aec3ac.png)

I can work around that, no problem at all, but I'm wondering out of curiosity or whether it's necessary or if there's a flag to prevent that output be written at all into stderr's stream?

Thanks in advance.

**Comment by keradus** [comment]
There's a convention across multiple tools that stderr is used for errors, warnings, but also debugs or any meta content. Here we followed it, so one can grab stdout of fix command and no need to strip out the extra content. If you want to grab the outxome from command, I suggest to use well defined format , with its spec provided and that is behind BC break promise ( https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master/doc/schemas/fix ).
