### ISSUE TITLE
Trailing commas for match cases

### ISSUE THREAD

**Issue by krzysztofrewak** [FriendsOfPHP/PHP-CS-Fixer#6370]
## Feature request

Right now TrailingCommaInMultilineFixer can fix missing trailing commas in arrays, arguments and parameters. It should be appliable to match cases in PHP >= 8.0.

For example the following code:
```php
$message = match ($statusCode) {
    200, 300 => null,
    400 => 'not found',
    500 => 'server error',
    default => 'unknown status code'
};
```

should be fixed into:
```php
$message = match ($statusCode) {
    200, 300 => null,
    400 => 'not found',
    500 => 'server error',
    default => 'unknown status code',
};
```

**Comment by SpacePossum** [comment]
Thanks for this suggestion,. if you can please try out https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6376 and let me know what you think :+1:
