### ISSUE TITLE
Error in FullOpeningTagFixer with php <8.0

### ISSUE THREAD

**Issue by AndryG** [FriendsOfPHP/PHP-CS-Fixer#6372]
$ ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php -vvv
    PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
    PHP runtime: 7.4.6

        [TypeError]
        strtolower() expects parameter 1 to be string, bool given

      strtolower()
        in /home/bk/proj/bk/vendor/friendsofphp/php-cs-fixer/src/Fixer/PhpTag/FullOpeningTagFixer.php at line 94
      PhpCsFixer\Fixer\PhpTag\FullOpeningTagFixer->applyFix()
        in /home/bk/proj/bk/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 75
      PhpCsFixer\AbstractFixer->fix()
        in /home/bk/proj/bk/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 167
      PhpCsFixer\Runner\Runner->fixFile()
        in /home/bk/proj/bk/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 111
      PhpCsFixer\Runner\Runner->fix()
        in /home/bk/proj/bk/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php at line 305
      PhpCsFixer\Console\Command\FixCommand->execute()
        in /home/bk/proj/bk/vendor/symfony/console/Command/Command.php at line 298
 

See code: (php-cs-fixer/src/Fixer/PhpTag/FullOpeningTagFixer.php at line 94)

```php
                if ('<?php' !== strtolower(substr($content, $tokensOldContentLength, 5))) {
                    $tokenContent = '<? ';
                }
```

Reading help substr https://www.php.net/manual/ru/function.substr.php

> $rest = substr("abcdef", 4, -4);  // returns ""; prior to PHP 8.0.0, false was returned

**I propose to add a typecast of the function substr()**

```php
                if ('<?php' !== strtolower((string)substr($content, $tokensOldContentLength, 5))) {
                    $tokenContent = '<? ';
                }
```

**Comment by SpacePossum** [comment]
Thanks for reporting, if you can would you please test if the proposed PR resolve the issue? If you can, please share example code that triggers this bug, it will help a lot, thanks.
