### ISSUE TITLE
Consider HEREDOC/NOWDOC as indentation block (separate indentation of end tag)

### ISSUE THREAD

**Issue by havvg** [FriendsOfPHP/PHP-CS-Fixer#6378]
## Rule request

The ending of a HEREDOC should be in line with the initial code line (variable assignment, return statement,…).

Currently the end is always in line with the content of the HEREDOC,

### Code snippet that shows how the rule would fix PHP code

  ```php
<?php

class Foo
{
    public function before()
    {
        $sql = <<<SQL
            SELECT id 
            FROM users;
            SQL;
    }

    public function after()
    {
        $sql = <<<SQL
            SELECT id 
            FROM users;
        SQL;
    }
}
```

**Comment by mvorisek** [comment]
this should be closed, as it would change the value - https://3v4l.org/Ata40

the end indentation determines the stripped content indentation from the string block

**Comment by julienfalque** [comment]
I agree. In some cases (like in the example above), stripping more or less spaces should have no impact on the behavior of the code, but sometimes it will, and the tool would have no way to determine if changing the indentation is safe.

**Comment by havvg** [comment]
Thanks for your response, I understand perception.

Sorry for my late reply, I was on vacations for a few weeks.

Just one note that immediately came into my made: changing `strlen` to `mb_strlen` is also changing the behaviour of the code. That's what tests are for. I need to revert a couple of those replacements every time, I run the CS-Fixer on the whole project rather than e.g. changed files, only ;-)
