### ISSUE TITLE
Namespace declaration isn't being corrected.

### ISSUE THREAD

**Issue by hannesvdvreken** [FriendsOfPHP/PHP-CS-Fixer#641]
<?php namespace Vendor\Namespace;

is not being converted to

    <?php
    namespace Vendor\Namespace;

Allthough I can't find it in the PSR-1 or PSR-2 CS guides, I remember that `namespace Vendor\Namespace` is supposed to go on the next line.

**Comment by joshhornby** [comment]
I can also confirm running this doesn't work on Laravel projects.

```php-cs-fixer fix app/ --fixers=line_after_namespace```

I expected that this would drop all the namespaces down so they are not level with the <?php tag

**Comment by ceeram** [comment]
I would suggest to handle this in a separate fixer. For instance one that ensures a newline after opening php tag.

**Comment by keradus** [comment]
`line_after_namespace` is `There MUST be one blank line after the namespace declaration.`.
This won't add blank line between opening tag and namespace. This would require new fixer that is already requested by this feature request.

**Comment by hannesvdvreken** [comment]
@ceeram Wanted to reply exactly that.

**Comment by ceeram** [comment]
I can take care of the newline after opening tag of that is a desired
solution.
Op 26 feb. 2015 14:20 schreef "Hannes Van De Vreken" <
notifications@github.com>:

**Comment by keradus** [comment]
See some movement here. Maybe someone is willing to create that fixer  ? :)

**Comment by GrahamCampbell** [comment]
@keradus Looks like @ceeram wants to do it:

> I can take care of adding a newline after opening tag fixer, if that is a desired solution.

**Comment by keradus** [comment]
Great. I looks like his msg was sending when I was already typing mine ;)

**Comment by ceeram** [comment]
Im on it then.

**Comment by keradus** [comment]
Cool :)

**Comment by ceeram** [comment]
See #1030

**Comment by joshhornby** [comment]
:+1: Great work, can't wait for this to be merged. Thank you @ceeram

**Comment by joshhornby** [comment]
Any update on this?

**Comment by GrahamCampbell** [comment]
This is done in 1.6.0. This issue can be closed.

**Comment by joshhornby** [comment]
:+1: great!
