### ISSUE TITLE
Custom PHP8 attribute breaks indentation if in same line

### ISSUE THREAD

**Issue by CodeBrauer** [FriendsOfPHP/PHP-CS-Fixer#6421]
## Bug report

```bash
PHP CS Fixer 3.8.0
PHP runtime: 8.1.6
php vendor/bin/php-cs-fixer fix --verbose --show-progress=dots
```

Config:
```
'@DoctrineAnnotation' => true,
'@Symfony' => true,
'yoda_style' => false,
'array_indentation' => true,
'concat_space' => [
    'spacing' => 'one',
],
'method_argument_space' => [
    'on_multiline' => 'ensure_fully_multiline',
],
'global_namespace_import' => [
    'import_classes' => true,
    'import_constants' => null,
    'import_functions' => null,
],
'self_accessor' => false,
```

### Code snippet that reproduces the problem

```php
class A extends B
{
    #[Pure] public function __construct()
    {
        parent::__construct($message);
    }
}
```

Result:
```php
class A extends B
{
    #[Pure]
 public function __construct()
 {
     parent::__construct($message);
 }
}

```

Expected:
```php
class A extends B
{
    #[Pure]
    public function __construct()
    {
        parent::__construct($message);
    }
}

```

I know that attribute normally should be in a separate line, however, this is also the default setting of PHPStorm. (Settings → Editor → Code Style → PHP → Wrapping and Braces → "Attributes": "Do not wrap"

**Comment by julienfalque** [comment]
Can you try with `dev-master` instead of `3.8.0`? The indentation, which was previously handled by `braces` rule, has been rewritten into a dedicated `statement_indentation` rule. Maybe the issue is already gone with this rewrite.

**Comment by CodeBrauer** [comment]
> Can you try with `dev-master` instead of `3.8.0`?

The result did not change using `dev-master`.

**Comment by julienfalque** [comment]
See #6429.

**Comment by sdellarosa** [comment]
Hi all, I'm still having the same issue, even when I use the same config as in the initial report.

Should this have been fixed?
