### ISSUE TITLE
@return before @throws in phpdoc_order

### ISSUE THREAD

**Issue by BenMorel** [FriendsOfPHP/PHP-CS-Fixer#6422]
## Feature request

Would it be possible to get **`@return` before `@throws`** in the `phpdoc_order` rule?

Sorry if this has been asked before, I've been unable to find a related issue or PR.

**Comment by SpacePossum** [comment]
will be fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6466

**Comment by julienfalque** [comment]
Duplicate of #1602.
