### ISSUE TITLE
Empty line after last `case` in enum is removed

### ISSUE THREAD

**Issue by jgrygierek** [FriendsOfPHP/PHP-CS-Fixer#6430]
## Bug report

When I run php cs fixer empty line after last `case` statement is removed. But it should not.

![obraz](https://user-images.githubusercontent.com/3065409/174453039-f778937d-78e3-451e-a505-250506a0b274.png)

### Code snippet that reproduces the problem

PHP: `8.1`

Configuration:

```return (new PhpCsFixer\Config())
    ->setRules(
        [
            '@PSR1' => true,
            '@PSR12' => true,
            '@Symfony' => true,
            '@Symfony:risky' => true,
            '@PHP81Migration' => true,
            '@PHP80Migration:risky' => true,
            'concat_space' => ['spacing' => 'one'],
            'global_namespace_import' => ['import_classes' => true],
            'native_function_invocation' => false,
        ]
    )
    ->setFinder($finder)
    ->setRiskyAllowed(true);
```
Package version:  `"friendsofphp/php-cs-fixer": "^3.8",`

**Comment by SpacePossum** [comment]
Hi and thanks for opening this issue. I believe what you describe here is the same as this issue:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6214

As such I recommend closing this issue as duplicate.
If it is not, please fill in the issue template to provide all details in text format, thanks!

**Comment by jgrygierek** [comment]
Ok, thanks, it seems like the same issue.
