### ISSUE TITLE
Laravel started publishing a CS named "Pint"

### ISSUE THREAD

**Issue by szepeviktor** [FriendsOfPHP/PHP-CS-Fixer#6437]
## Feature request

This is how to copy it `pint-laravel-preset.php`

```php
<?php

namespace App\Factories
{
    class ConfigurationFactory
    {
        public static function preset(array $array): array
        {
            return $array;
        }
    }
}

namespace
{
    $pintPresetUrl = 'https://github.com/laravel/pint/raw/main/resources/presets/laravel.php';
    $pintLocalCache = '.php-cs-fixer.laravel.cache';
    if (! is_file($pintLocalCache)) {
        copy($pintPresetUrl, $pintLocalCache);
    }

    return require $pintLocalCache;
}
```

This is how to use it `.php-cs-fixer.php`

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([
        __DIR__ . '/app',
        __DIR__ . '/config',
        __DIR__ . '/database',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ])
;

$config = new PhpCsFixer\Config();
return $config->setRules(require __DIR__ . '/pint-laravel-preset.php')
    ->setRiskyAllowed(true)
    ->setFinder($finder)
;
```

Start 🏎️ `vendor/bin/php-cs-fixer fix`

**Comment by keradus** [comment]
hey @szepeviktor !
to be honest, i'm not really sure what is your suggestion. Could you elaborate?

If you are only announcing yet-another-wrapper over PHP CS Fixer, thanks for letting us know and I think we can close the ticket.

If you believe that there are some improvements the tool can do to be easier to use, fully agree, don't hesitate to propose/implement them!

If I failed to guess your intention, please elaborate 😅

**Comment by szepeviktor** [comment]
> If I failed to guess your intention, please elaborate 😅

Yes: it is impossible to find _nothing_!

Could you describe a way to implement this downloaded ruleset in PHP CS Fixer?

If it is not possible then please point out a package that I can start with to release `szepeviktor/php-cs-fixer-laravel-ruleset`. Thank you!

**Comment by keradus** [comment]
The so far approach we so of other ppl/vendor were to create custom repo with their custom/predefined ruleset, like https://github.com/ergebnis/php-cs-fixer-config/blob/main/src/RuleSet/Php81.php 

if you would like to bring other way to support custom ruleset, please do not hesitate to propose a RFC/PR

**Comment by szepeviktor** [comment]
Thank you.

Something is cooking https://github.com/szepeviktor/php-cs-fixer-laravel-ruleset
