### ISSUE TITLE
 PHPStorm  with  "Quality Tools"-> "PHP CS Fixer"->"PHP CS Fixer path"->Validate version info failed!

### ISSUE THREAD

**Issue by nilyang** [FriendsOfPHP/PHP-CS-Fixer#6460]
## Support question
 PHPStorm  with  "Quality Tools"-> "PHP CS Fixer"->"PHP CS Fixer path"->Validate failed!

When I use PHPStorm  with  Quality Tools PHP CS Fixer,
```
PHPStorm->Settings->PHP->Quality Tools->PHP CS Fixer->Configuration "..."Button->PHP CS Fixer path->Validate
```
I Configured the "PHP CS Fixer"'s path ,and click the Validate button,then I got the error message:

```
Cannot determine tool version, got 'PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.PHP runtime: 7.4.3'
```

When I try to modfy the source code 

```
Console/Application.php:132
....
"\nPHP runtime: <info>".PHP_VERSION.'</info>',
....
```
I have try two way to fix the problem:

1.  delete the 'PHP runtime 'info

I delete the line  `"\nPHP runtime: <info>".PHP_VERSION.'</info>',`, and then click the `Validate` button,then the validate is succeed!

```
OK, PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
```
2. modifiy the "PHP runtime" info:
I replace the `\n` to space ` `  

```
before:
`"\nPHP runtime: <info>".PHP_VERSION.'</info>',`  

after:
`" PHP runtime: <info>".PHP_VERSION.'</info>',` 
```

Then click the "Validate" button, I got the succeed tips!
```
OK, PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski. PHP runtime: 7.4.23
```

At last, I find that ,the PHPStorm version validate button not allow "\n" in version info!

**Comment by keradus** [comment]
can you please report this to PHPStorm directly, @nilyang ?

**Comment by jrmajor** [comment]
Seems it has been reported: https://youtrack.jetbrains.com/issue/WI-65005/Cannot-determine-tool-version-PHP-CS-Fixer-350. Does updating PhpStorm to 2021.3.2 fix your issue?

**Comment by nilyang** [comment]
Thanks @jrmajor ,the problem fixed.

**Comment by nilyang** [comment]
> can you please report this to PHPStorm directly, @nilyang ?

Okay. I understand. Thanks very much.
