### ISSUE TITLE
Set permissions for GitHub

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#6464]
following https://github.com/twigphp/Twig/pull/3713/files and others, is this something we want or need?

**Comment by julienfalque** [comment]
According to [this article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) and the [events documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target), this security issue only applies to `pull_request_target` and we don't seem to use it so I think we don't need it for now. But it's something we must be careful with so maybe we can add it now anyway? /cc @keradus

**Comment by keradus** [comment]
to my understanding, risk is only for action types that we are not using. but if any of you want to play future-safe and propose a PR, i would not be against it

**Comment by keradus** [comment]
closed by #6644
