### ISSUE TITLE
If without arrows

### ISSUE THREAD

**Issue by PH7-Jack** [FriendsOfPHP/PHP-CS-Fixer#6469]
I'm wondering to know if this syntax is possible to use with the php-cs-fixer. Thanks for this amazing package
![image](https://user-images.githubusercontent.com/38913462/178189070-91f73684-47f6-4295-8e14-d0071ca8de76.png)

**Comment by jrmajor** [comment]
There is no fixer that can help you maintain this style, but you can still use PHP-CS-Fixer with `braces` fixer disabled and use other fixers.

Only rules that are followed by larger open source communities are accepted, which I don't think this one is, so it's unlikely that there will be a dedicated fixer for this style. `braces` fixer, however, is being split (#4884), so soon it will be enough to disable `control_structure_braces` and probably `no_multiple_statements_per_line`.

**Comment by PH7-Jack** [comment]
@jrmajor You solved my issue. Thanks 

https://mlocati.github.io/php-cs-fixer-configurator/#version:3.9|fixer:control_structure_braces
