### ISSUE TITLE
Incorrect continuation indentation with 3.9.x

### ISSUE THREAD

**Issue by bobvandevijver** [FriendsOfPHP/PHP-CS-Fixer#6496]
## Bug report

The wrong continuation indentation is being applied since 3.9.x. Instead of the expected 4, it is now 2. 

Also tested with latest `master`, no changes unfortunately.

### Code snippet that reproduces the problem

All details can be found on the `renovate/friendsofphp-php-cs-fixer-3.x` branch on https://github.com/Drenso/symfony-oidc/tree/renovate/friendsofphp-php-cs-fixer-3.x. See https://github.com/Drenso/symfony-oidc/commit/443de599380a20a122cb22e69e08a0309b06210f for the changeset generated with our CI.

**Comment by bobvandevijver** [comment]
The configuration specifies 2 for the normal indent, not the continuation indent :) Normally, the continuation indent is twice the normal indent.

Also note that the changeset I linked is purely caused by the upgrade of cs-fixer 3.8 to 3.9. The behaviour regarding continuation indent has changed between these two minors.

**Comment by julienfalque** [comment]
Currently PHP CS Fixer has no configuration for "continuation indent" and never had. Yes, the behavior has changed, such lines were never fixed before, but this was more of an oversight than a feature.

**Comment by bobvandevijver** [comment]
That is too bad to hear. I would consider writing the functionality myself, but my previous attempt to add a fix for this repo has been completely untouched for 4 months for now, so there is not a lot of motivation to do so...

**Comment by julienfalque** [comment]
Sorry about that. Sadly we don't have much free time to handle all the contributions but you're very welcome to implement this.

**Comment by keradus** [comment]
Can you bring a proper report to help me understand the topic?

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blame/aacc80403c402675af50b89364269bf410b3486d/.github/ISSUE_TEMPLATE/bug_report.md#L20

especially:
   * PHP CS Fixer version and PHP runtime: php-cs-fixer -V
   * the command used to run PHP CS Fixer (run with `-vvv`)
   * the configuration (file) you used

and

Provide a minimal code snippet **before** running PHP CS Fixer. If relevant,
  also provide the **expected output**, the **actual output** and/or the error that
  occurred, if any.

**Comment by bobvandevijver** [comment]
Well, everything you ask for is already here, but to summarize: 3.9.0 started touching continuation indent and replace it with the configured normal indent. Before 3.9.0, it did not touch continuation indented lines at all.

For the linked repository, the following holds:

| Item | Value |
| --- | --- | 
| PHP-CS-Fixer | 3.9.4 |
| PHP Version | 8.0.13 |
| Command | vendor/bin/php-cs-fixer fix |
| Config | https://github.com/Drenso/symfony-oidc/blob/renovate/friendsofphp-php-cs-fixer-3.x/.php-cs-fixer.dist.php |

Snippets, as already included in the updated tests:

### Before
```php
<?php
foo(
  $bar,
   $baz
    );
```

### After (with two spaces indent)
```php
<?php
foo(
  $bar,
  $baz
);
```

### Expected (with four spaces continuation indent)
```php
<?php
foo(
    $bar,
    $baz
);
```

Or, if you like, on a full file:

| Item | Value |
| --- | --- |
| Before | https://github.com/Drenso/symfony-oidc/blob/05dffc894722a1039e082070b8037fc843da1290/src/OidcClient.php |
| Result | https://github.com/Drenso/symfony-oidc/commit/443de599380a20a122cb22e69e08a0309b06210f |
| Expected | https://github.com/Drenso/symfony-oidc/compare/22181ecc06b47b1422deebb64f08f174bf892148...618d2b348ee4cb76cc80f12da96e1b2632ba84ab (only other changes from 3.8 to 3.9 are shown now, which are fine) |

**Comment by SpacePossum** [comment]
I wonder if we want to support having an "initial" indentation followed by a "continuation" indentation.

Is this common practice in some (bigger) (F)OSS community or part of some standard?
Just curious, but for now I've some reservations on supporting this.

To me it looks like it would open up for things like "initial indent is tab, but after that it is 2 spaces", which I feel is not something we want to support.

**Comment by bobvandevijver** [comment]
Continuation indent is available and enabled by default in all IDEA products ([docs](https://www.jetbrains.com/help/idea/code-style-sql-tabs-and-indents.html), which means PhpStorm uses it as well. That is how I know it, and it allow for much better readability (although the latter is obviously a personal opinion 🙂).

EditorConfig supports it: https://github.com/editorconfig/editorconfig-jetbrains/issues/57

> To me it looks like it would open up for things like "initial indent is tab, but after that it is 2 spaces", which I feel is not something we want to support.

Well, that is indeed possible with the changes I submitted now, but obviously it would be quite easy to block such a scenario. But is is that something you should be bothered by? If the users want to use it that way, why not?

Another option would be to change the parameter to a bool, which simply configures the continuation indent as twice the normal indent when set to true.

**Comment by keradus** [comment]
> Well, everything you ask for is already here, (...)
> Or, if you like, on a full file:

that's exactly the part i didn't want - big files, big diff, trying to figure out what exactly you mean. Thanks for sharing the the minimum snippets

**Comment by keradus** [comment]
I fail to see the issue.

### with your config as-is, v3.8.0:

no changes at all

### with your config as-is, v3.9.5:

```
ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ ./php-cs-fixer fix --dry-run --diff x.php -vvv
PHP CS Fixer 3.9.5 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.6
Loaded config default from "/Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                                                           1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) PHP-CS-Fixer/x.php (braces, blank_line_after_opening_tag)
      ---------- begin diff ----------
--- /Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/x.php
+++ /Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/x.php
@@ -1,5 +1,6 @@
 <?php
+
 foo(
   $bar,
-   $baz
-    );
+  $baz
+);

      ----------- end diff -----------
```

### with your config modified with `->setIndent('    ')`, v3.9.5:

```
ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ ./php-cs-fixer fix --dry-run --diff x.php -vvv
PHP CS Fixer 3.9.5 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.6
Loaded config default from "/Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                                                           1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) PHP-CS-Fixer/x.php (braces, blank_line_after_opening_tag)
      ---------- begin diff ----------
--- /Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/x.php
+++ /Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/x.php
@@ -1,5 +1,6 @@
 <?php
+
 foo(
-  $bar,
-   $baz
-    );
+    $bar,
+    $baz
+);

      ----------- end diff -----------

```

**Comment by keradus** [comment]
I rather see this ticket to not raise incorrect behaviour, but your wish to have a possibility of having regular indent different than continuation indent.
I didn't met this case in practice, and it's complicating a lot of things - not sure if it's worth the effort to add this to all fixers and maintain it. I would be with @SpacePossum here and 👎🏻 for such feature from my side.

**Comment by bobvandevijver** [comment]
> I rather see this ticket to not raise incorrect behaviour, but your wish to have a possibility of having regular indent different than continuation indent.

Well, I opened it convinced it worked in 3.8, to only learn in this ticket it actually was an oversight (hence the bug report). Most formatting is already done by PhpStorm during save for me, using the EditorConfig that is in the repository, but now PHP-CS-Fixer can no longer be configured to behave equally...

> I didn't met this case in practice, and it's complicating a lot of things - not sure if it's worth the effort to add this to all fixers and maintain it.

I obviously am not that familiar with the code base, but most changes I made were related to the configuration file and the cache implementation. I've checked where the indent configuration is used, which resulted in only three fixers where it would really matter, where the `StatementIndentationFixer` would be the most complex one. And even there, it should be pretty clear once you understand the fixer there.

Anyways, it's too bad to hear that this feature might not be added, especially after @julienfalque basically said it would be "very welcome" to add it 😔

**Comment by keradus** [comment]
3.8 was not touching the code, 3.9 started fixing it. Indeed, in a way that you did not expect.



Having the "continuation indentation" as a separated setting would mean:
- we are OK to have "continuation indentation" and "indentation" fixer different -> I'm (and Space) not convinced if it's good idea, so far only you raised the need for it. I would love to see high amount of impacted users and demand for this feature, as it's bringing extra complexity.
  - my main argument is "best practice" and "global standards". PHP CS Fixer is not to handle each variant of code style - we aim to unify and spread best variant. PSR-12 is saying that indentation is 4 spaces, as easy as that - nothing about continuation indentation, no non-4-spaces indentation in examples, even those that you would classified as continuation indentation.
- we need to validate _all_ the fixers we have - you said you tried to identify them, review of it would get tricky
- what about custom fixers (out of this repo)? if we have a new option, if they will not update to respect it, they will apply a wrong indentation if the user decides to have non-default one. I consider it to be a BC breaker.

I agree it's very unfortunate that you run the PR and we figured out different opinions about eagerness of having this code only later - big sorry for that. Nevertheless, big kudos for raising a PR with the proposal, I bet it was not trivial to figure out all the steps there!

I'm sharing my opinion and reasoning above. I'm not blocking the feature, but don't want to make any feature (this or other) for sake of single user.
I would love to understand the need of this feature: how big is a demand of users for it? is there any well-defined PHP standard (PHP-FIG?) for it?
Also, maybe @julienfalque you can share your arguments for having it in, would be great.

**Comment by bobvandevijver** [comment]
> we need to validate all the fixers we have - you said you tried to identify them, review of it would get tricky

Fair enough, to give a bit more insight: I looked where the indent was actually retrieved and applied on places where continuation indent would be relevant. The changes in the MR are all places I found this way.

> I consider it to be a BC breaker.

I personally might already consider the change from 3.8 to 3.9 a BC break, but I absolutely agree that a high level configuration change like this (touching cache keys as well) is a BC break, even though it should not break (famous last words) for users using the default configuration.

> how big is a demand of users for it?

Couldn't tell you, except that it is used in [PhpStorm](https://www.jetbrains.com/help/phpstorm/settings-code-style-php.html#php-specific-formatting-settings-for-spaces).

> PSR-12 is saying that indentation is 4 spaces, as easy as that - nothing about continuation indentation, no non-4-spaces indentation in examples, even those that you would classified as continuation indentation.
> is there any well-defined PHP standard (PHP-FIG?) for it?

[PSR-12](https://www.php-fig.org/psr/psr-12/) allows for continuation indent between parentheses (note the "at least once"): 

`"Expressions in parentheses MAY be split across multiple lines, where each subsequent line is indented at least once."`

This would be a strong case to change the configuration for continuation indent from the current string into a multiplier.

However (and this is not helping my case as I like continuation indent especially there) it also specifies the following:

`"Argument lists MAY be split across multiple lines, where each subsequent line is indented once"`

A bit conflicting if you ask me 😔

**Comment by julienfalque** [comment]
I'm sorry, I realize I confused this with another feature from PhpStorm I do use: soft-wraps additional indent, which is not written in the file on save. I actually agree with @keradus and @SpacePossum: having extra indentation for statement continuation seems to be an edge case and I don't think it's worth making `statement_indentation` even more complex.

**Comment by keradus** [comment]
While I appreciate the effort you put into this feature, I decided to reject this feature to be merged into the mainline of this project, for now.

For now, you may disable the rule you don't like in your config, register your fixer as a custom one locally, or adjust your style to follow the widely used standard.

I will re-consider this decision if this feature will get more support from a wide user audience or become part of PHP fig guideline.
