### ISSUE TITLE
Error during linting after fixing

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#6498]
## Bug report

```
Files that were not fixed due to errors reported during linting after fixing:
   1) /__w/ui/ui/src/Console.php
Error: Process completed with exit code 64.
```

### Code snippet that reproduces the problem

file: https://github.com/atk4/ui/blob/7d84adb005439c2adbf27faa71086e21a12af9ce/src/Console.php

config: https://github.com/atk4/ui/blob/7d84adb005439c2adbf27faa71086e21a12af9ce/.php-cs-fixer.dist.php

the file itself should be valid: https://3v4l.org/QkrPb

CI: https://github.com/atk4/ui/runs/7405399049

Such issue is present probably since v3.9.1, v3.8.x was fixing/passing the file without any issues.

**Comment by mvorisek** [comment]
It seems the following file is enought to reproduce:

```
<?php

$object::{$method}(...$args);
```

**Comment by SpacePossum** [comment]
Thanks for reporting and sorry for the inconvenience,
What you experience here has the same root issue reported here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6472

I'm in the process of writing a fix for that.

**Comment by mvorisek** [comment]
This issue fails atk4/ui CI, and as the fix is already integrated, would it be possible to tag a new release?

**Comment by SpacePossum** [comment]
it is in https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.9.5 , or maybe I misunderstand?

**Comment by mvorisek** [comment]
Technically I have posted it sooner than it was tagged, but it does not matter, it is all perfect now, thank you for caring!
