### ISSUE TITLE
Semicolon on the next line is indented wrongly since v3.9.0

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#6512]
### Code snippet that reproduces the problem

```
        $desc = 'x'
            . 'y'
            ; // comment
```

is indented to:

```diff
   3) xxx/src/Ui/Form/Control/MyUpload.php (braces)
      ---------- begin diff ----------
--- /builds/mvorisek/xxx/src/Ui/Form/Control/MyUpload.php
+++ /builds/mvorisek/xxx/src/Ui/Form/Control/MyUpload.php
@@ -180,7 +180,7 @@
         $desc = 'x'
             . 'y'
-            ; // comment
+        ; // comment
```

This issue is present since v3.9.0. (probably, as in v3.8.x it was fine and in v3.9.5 it is newly wrong as described)

**Comment by SpacePossum** [comment]
I cannot reproduce this, it really helps us all if the bug-template gets filled out a bit more as it will show details like which rule does this change.

**Comment by mvorisek** [comment]
The rule is visible in the diff. I reproduced it now in CI:

- file: https://github.com/atk4/data/commit/329900b60de966eed36afac98ec84231b6345685
- config: https://github.com/atk4/data/blob/329900b60de966eed36afac98ec84231b6345685/.php-cs-fixer.dist.php
- CI: https://github.com/atk4/data/runs/7467211551

**Comment by julienfalque** [comment]
Actually this is intentional, see for example [this test case](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f63eb5df381eebf2c09a5ed3e1cbe75bde87494e/tests/Fixer/Whitespace/StatementIndentationFixerTest.php#L459=). The idea is to have the statement's ending character (usually `;`) indented like the beginning of that statement when it's on its own line.

**Comment by mvorisek** [comment]
Thank you for the feedback. This was an edge case in our code base, but if it is desired, I am closing this issue.
