### ISSUE TITLE
Indentation breaks in v3.9.x (mixed html/php file)

### ISSUE THREAD

**Issue by fabiofdsantos** [FriendsOfPHP/PHP-CS-Fixer#6513]
## Bug report

It was working properly in v3.8. The bug occurs in v3.9 (incl. v3.9.5).

### Code snippet that reproduces the problem

<img width="946" alt="image" src="https://user-images.githubusercontent.com/8303937/180427614-fb53f883-c4fd-403d-b1bf-a0ae4574c56c.png">

<img width="945" alt="image" src="https://user-images.githubusercontent.com/8303937/180427665-6bbd62fa-b8d5-44fc-9da3-cf8138e7b33e.png">

**Comment by keradus** [comment]
I strongly discourage to use mixed php/html files.
The tool is not designed to work with them, as well.

**Comment by SvenRtbg** [comment]
@keradus If working on HTML files is having incorrect results or is not supported, then the codefixer should stop working on these files as soon as HTML is encountered, and maybe emit an error or warning about that fact. Previously php-cs-fixer did create correct results that also the "phpcs" checker agreed upon, and that is true for basically all past versions of these tools.

I know indentation is ugly, and I see there are still even uglier cases when combining arbitrary rules and expecting "correct" output - still something changed to the worse in the "braces" rule part in 3.9.x, with 3.9.1 being a very bad offender, and 3.9.2 up to 3.9.5 still messing up the HTML mix.

**Comment by SvenRtbg** [comment]
Also, this has already been reported in #6470, I experience roughly the same.

**Comment by keradus** [comment]
@SvenRtbg , it's heavy work to support mixed HTML file and it was always causing us problems, while we were never explicitly claiming the support.
I agree we can explicitly claim lack of support - https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6517 , raised few days ago

**Comment by fabiofdsantos** [comment]
I agree to stop checking mixed html/php by default as we have `php-cs-fixer` in our ci/cd pipelines and it sometimes starts to mess around..
