### ISSUE TITLE
(binary_operator_spaces) Unexpected fix for anonymous functions

### ISSUE THREAD

**Issue by 27cm** [FriendsOfPHP/PHP-CS-Fixer#6514]
## Bug report

Fixer binary_operator_spaces fix wrong operators around anonymous functions.

PHP CS Fixer 3.9.4 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.10

Enabled binary_operator_spaces with `'operators' => ['=' => 'align_single_space', ...]`

### Code snippet that reproduces the problem

```php
$vehicleType = function ($value) {
    $vehicleType = SomeClass::method($value);
    return $vehicleType->field;
};
```

binary_operator_spaces makes this:

```php
$vehicleType     = function ($value) {
    $vehicleType = SomeClass::method($value);
    return $vehicleType->field;
};
```

**Comment by VincentLanglet** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6510

**Comment by VincentLanglet** [comment]
Can you try https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6515 ?
