### ISSUE TITLE
`no_superfluous_phpdoc_tags` does not behave consistently

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#6528]
## Bug report

Please see the diff below. I would expect the superfluous `@var array` removed in both cases. It does not matter if the property description is following the `@var` inline or above it. Phpdoc property description is defined/started by `/**`, not by `@var`.

### Code snippet that reproduces the problem

Currently only the description above `@var` is removed, which is inconsistent. Description declared following the `@var` inline has exactly the same meaning.

![image](https://user-images.githubusercontent.com/2228672/182021274-620b6975-c4b1-4563-a829-aee810f5eb1c.png)

### Expected result

I would expect the following result:

```
    /** Some description. */
    public array $order = [];

    /**
     * Some description.
     */
    private array $data = [];
```

**Comment by julienfalque** [comment]
This is expected: the rule does not remove PHPDocs when they have a description.
