### ISSUE TITLE
Constant names are incorrectly converted to lower case

### ISSUE THREAD

**Issue by Yurunsoft** [FriendsOfPHP/PHP-CS-Fixer#6534]
## Bug report

I'm using Swoole and php-cs-fixer is incorrectly converting the constant `SWOOLE_PROCESS` to lowercase `swoole_process`

`swoole_process` is also a class name, but I don't know the cause of the problem.

PHP CS Fixer 3.9.5

### Code snippet that reproduces the problem

**code:**

```php
<?php

declare(strict_types=1);

var_dump(\SWOOLE_PROCESS);
var_dump($a ?? \SWOOLE_PROCESS);
var_dump(\SWOOLE_BASE);
var_dump($a ?? \SWOOLE_BASE);

```

`./vendor/bin/php-cs-fixer fix --dry-run --diff test.php`

```shell
   1) test.php
      ---------- begin diff ----------
--- /mnt/d/projects/imi/imi-2.1/test.php
+++ /mnt/d/projects/imi/imi-2.1/test.php
@@ -3,6 +3,6 @@
 declare(strict_types=1);
 
 var_dump(\SWOOLE_PROCESS);
-var_dump($a ?? \SWOOLE_PROCESS);
+var_dump($a ?? \swoole_process);
 var_dump(\SWOOLE_BASE);
 var_dump($a ?? \SWOOLE_BASE);

      ----------- end diff -----------
```

**Comment by SpacePossum** [comment]
please fill in the bug report template as it was presented to you when you filed this issue, it is not for us, it is there _for you_ to allow us to help _you_ , thanks

**Comment by julienfalque** [comment]
I could not reproduce the bug. Please try again with latest `master` and, if the bug still happens, reopen this issue with all asked details to help us reproduce it.
