### ISSUE TITLE
PSR-12: wrong fix when instanciating an anonymous class

### ISSUE THREAD

**Issue by guvra** [FriendsOfPHP/PHP-CS-Fixer#6536]
## Bug report

When instanciating an anonymous class, php-cs-fixer adds parentheses after the `class` keyword, which contradicts the PSR-12 rule defined here: https://www.php-fig.org/psr/psr-12/#8-anonymous-classes

Additional information:

- PHP CS Fixer version and PHP runtime:
    ```
    PHP CS Fixer 3.9.5 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
    PHP runtime: 7.4.3
    ```
- Command to use to reproduce the issue:
    ```
    vendor/bin/php-cs-fixer fix test.php --rules=@PSR12 --dry-run --diff -vvv
    ```
- Configuration file to use: none

### Code snippet that reproduces the problem

test.php:

```php
<?php

$test = new class {
    // ...
};

```

### Expected behavior

Nothing to fix.

### Actual behavior

```diff
   1) test.php (new_with_braces, class_definition)
      ---------- begin diff ----------
--- /home/guvra/test.php
+++ /home/guvra/test.php
@@ -1,5 +1,5 @@
 <?php
 
-$test = new class {
+$test = new class () {
     // ...
 };

      ----------- end diff -----------


Checked all files in 0.006 seconds, 14.000 MB memory used
```

**Comment by SpacePossum** [comment]
This is likely done by `class_definition`, however it is not done `@PSR12`.

If you want this fix, please fill in the bug report template, it is there so we can help you, if you don't want to fill it in I can only assume you don't want help either.

**Comment by guvra** [comment]
@SpacePossum I've updated the issue description to match the template and with additional relevant information (e.g. command to run, and output of the command).

The culprit is most probably `new_with_braces`.

**Comment by guvra** [comment]
FYI it will be enforced in PER:
https://github.com/php-fig/per-coding-style/pull/37/files

**Comment by julienfalque** [comment]
Given the discussions, I would say that PSR-12 intended to enforce parentheses even without arguments, but provided examples inconsistent with that rule. I propose to keep `@PSR12` unchanged.

**Comment by VincentLanglet** [comment]
> Given the discussions, I would say that PSR-12 intended to enforce parentheses even without arguments, but provided examples inconsistent with that rule. I propose to keep `@PSR12` unchanged.

Then this issue can be closed, no ?

**Comment by guvra** [comment]
You probably can, but please keep in mind that this rule will be enforced in the upcoming PER standard: https://github.com/php-fig/per-coding-style/blob/master/spec.md#8-anonymous-classes.

> If the anonymous class has no arguments, the () after class MUST be omitted.

This is something to keep in mind if you plan to implement the PER standard into php-cs-fixer in the future.
