### ISSUE TITLE
Blank lines around statement 

### ISSUE THREAD

**Issue by Disservin** [FriendsOfPHP/PHP-CS-Fixer#6543]
## Feature request
Hi,

I am looking for a feature that would convert this
```php

$isTrue = true;
if ($isTrue) {
    // do something
}
$var = "test";
```

into 

```php

$isTrue = true;

if ($isTrue) {
    // do something
}

$var = "test";
```

so a feature that adds new a new line and removes blank lines (if there are more than one) around various control structures. Similar can be achieved with `blank_line_before_statement` but in the case of variables, there is no possible way to achieve that. <br>
I also know that php-cs-fixer isnt there to fix everyones niche coding styles but I think this one is more or less widely used. (Please correct me if I'm wrong and there is actually a way to achieve this without a new feature)

**Comment by VincentLanglet** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1122

**Comment by Disservin** [comment]
> Duplicate of #1122

Ah thanks I’ll close this
