### ISSUE TITLE
Phar file with symfony/console 6.x?

### ISSUE THREAD

**Issue by voku** [FriendsOfPHP/PHP-CS-Fixer#6552]
## Support question

I always use the phar file (currently v3.9.5) of php-cs-fixer, but after update from php 7.4 to 8.0 I could not use it anymore, because it seems like it's using symfony/console 5.x. Is there a way to fix that, can I build the phar with new dependencies for myself? 🤔 

---

`Fatal error: Declaration of Symfony\Component\Console\Style\OutputStyle::write(iterable|string $messages, bool $newline = false, int $type = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, bool $newline = false, int $options = 0)`

**Comment by kubawerlos** [comment]
> I could not use it anymore

What is the problem? symfony/console 5.x is compatible with PHP 8.0

**Comment by voku** [comment]
> > I could not use it anymore
> 
> What is the problem? symfony/console 5.x is compatible with PHP 8.0

Thanks for the info, then I will keep the old version of symfony/console until I need to update. :)
