### ISSUE TITLE
Can formatting rules be configured?

### ISSUE THREAD

**Issue by ppazos** [FriendsOfPHP/PHP-CS-Fixer#6556]
I need a slightly custom format config (indentation, spaces after clauses, and enters on code blocks, but I'm not sure if I can configure these rules:

1. 3 space indentation, no tabs
2. if(....) => if (....) // added space after the if
3. if (...) { => if (...)
{ // code block starts on next line, also ends on next line after the last clause in the block: if (...)
{
  ...
  ...
}

Thanks!

**Comment by jrmajor** [comment]
1. Use `PhpCsFixer\Config::setIndent()` (see the last code snippet in [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f888d6652bce81b3eea81b8cc00c740f66f449e6/doc/config.rst) manual).
2. [`single_space_after_construct`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/d5ad7953163683402ca98c89e843ae3b2c1b5a5c/doc/rules/language_construct/single_space_after_construct.rst) should work for that.
3. Try [`curly_braces_position`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/b71e51fa2ee0a20462da9bad123743b4c7aa8036/doc/rules/basic/curly_braces_position.rst) with `['control_structures_opening_brace' => 'next_line_unless_newline_at_signature_end']`.

Hope that helps :)

**Comment by kubawerlos** [comment]
@jrmajor it won't work because of this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/src/WhitespacesFixerConfig.php#L28

@ppazos can you share the motivation for using 3 spaces for an indent? AFAIK no at least fairly popular library/project is using it, it is against PSRs and you have to admit will be surprise for anyone seeing it (that might be an issue if you want it in a project with other developers). Wouldn't be the good practice (and I'm assuming you want to have these as you are here, using PHP CS Fixer) to have indent that "reasonable"?

**Comment by ppazos** [comment]
@kubawerlos all our projects, PHP,, java, groovy, etc have 3 space indentation. We are consistent with ourselves.

**Comment by kubawerlos** [comment]
@ppazos any of these encourages 3 space indent?

**Comment by ppazos** [comment]
@kubawerlos all our projects, PHP,, java, groovy, etc have 3 space indentation. We are consistent with ourselves.

**Comment by ppazos** [comment]
All of them, is our coding standard. @kubawerlos  that is why I asked for "custom" rules.

**Comment by ppazos** [comment]
@kubawerlos checking your link, I can see the answer to my question is custom indentation can't be configured since the accepted indentation options are hardcoded there https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/src/WhitespacesFixerConfig.php#L28

So I'll close this questions and check with other formatters, thanks!

**Comment by kubawerlos** [comment]
For the 3 spaces indent could be tricky to achieve and definitely time consuming as all indent related fixers would need have test for new indent option.
