### ISSUE TITLE
spaces in array declaration not normalized

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#6560]
## Bug report

see https://github.com/atk4/ui/blob/d138bca5b6e697eabb5e017395eebd0b38037432/src/Table/Column.php#L103

config: https://github.com/atk4/ui/blob/d138bca5b6e697eabb5e017395eebd0b38037432/.php-cs-fixer.dist.php

### Code snippet that reproduces the problem

![image](https://user-images.githubusercontent.com/2228672/185505503-9c1b2c5a-a9fd-47da-bbfa-88efc0ff7b31.png)

the normalization had to be done manually, but I would expect it to be done by the PHP CS Fixer

**Comment by kubawerlos** [comment]
Option `ensure_single_space` from [`whitespace_after_comma_in_array`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/doc/rules/array_notation/whitespace_after_comma_in_array.rst#ensure_single_space) is what you are looking for.

**Comment by mvorisek** [comment]
> Option `ensure_single_space` from [`whitespace_after_comma_in_array`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/doc/rules/array_notation/whitespace_after_comma_in_array.rst#ensure_single_space) is what you are looking for.

we use `PhpCsFixer` ruleset which should enable this by default - https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.10.0/doc/rules/array_notation/whitespace_after_comma_in_array.rst

I see the option is present since v3.10, thus I am closing this issue now and will recheck with this new release.
