### ISSUE TITLE
`date_time_create_from_format_call` should be marked risky

### ISSUE THREAD

**Issue by donatj** [FriendsOfPHP/PHP-CS-Fixer#6574]
## Bug report

`date_time_create_from_format_call` should be marked as risky because it fundamentally changes the result.

We actually had code for checking license expirations, boling down to `if( time() - \DateTime::createFromFormat('Y-m-d', '2022-02-11')->getTimestamp() > ONE_WEEK) {…}` that depended on the non-`!` behaviour and this burnt us.

### Code snippet that reproduces the problem

The return values do not match

https://3v4l.org/SvBZc

```php
<?php

echo \DateTime::createFromFormat('Y-m-d', '2022-02-11')->format('r');
echo "\n";
echo \DateTime::createFromFormat('!Y-m-d', '2022-02-11')->format('r');

```

**Comment by SpacePossum** [comment]
Thanks for reporting, marking the rule as `risky` sounds good to me :+1:
