### ISSUE TITLE
`no_unneeded_control_parentheses` /w `negative_instanceof` does not fix instanceof static

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#6586]
## Bug report

CI: https://github.com/atk4/data/commit/43280db56dc3612e9f37e468d4a61b40a015f522
config: https://github.com/atk4/data/blob/43280db56dc3612e9f37e468d4a61b40a015f522/.php-cs-fixer.dist.php (using `@PhpCsFixer` which have `no_unneeded_control_parentheses` rule /w `negative_instanceof` enabled)

### Code snippet that reproduces the problem

```
class Condition
{
    public function __construct($key, $operator = null, $value = null)
    {
        if (!($key instanceof static)) {
            throw new Exception('Only Scope can contain another conditions');
        }
    }
}
```

**Comment by SpacePossum** [comment]
Why is it that you always refuse to help us out by not filling in the template? I just really curious because I would like to know how we could improve the template. For now I just don't have to time to the investigation.

**Comment by mvorisek** [comment]
I have posted full PHP CS Fixer config and CI link showing the given example is unfixed currently. PHP CS Fixer version is the latest and visible in the CI pipeline - https://github.com/atk4/data/runs/8031042536?check_suite_focus=true#step:10:7.

What info are you missing the report?

**Comment by SpacePossum** [comment]
I'm not saying anything is missing, I asked what is wrong with the template for you that makes you not want to follow it?

**Comment by mvorisek** [comment]
I found repro link (to a specific commit, not to a branch!) better as they provide proof the issue is really reproducible.

I also found this helpfull when the report cannot be reproduced, when there is a git link, it can be investigated /wo having to ask for more details as the full data are present.

**Comment by SpacePossum** [comment]
I find the less useful, it takes more time for the readers.

**Comment by julienfalque** [comment]
> it can be investigated /wo having to ask for more details as the full data are present.

That's the thing: all the data is there but not all the data are relevant, so instead of looking for missing details, we have to filter out superfluous ones. Some details might still be missing like version of PHP CS Fixer used, which I have no idea where to find easily.

**Comment by SpacePossum** [comment]
this can be closed

**Comment by mvorisek** [comment]
This issue is
```
if (!($key instanceof Class)) {
```

is fixed correctly but
```
if (!($key instanceof static)) {
```
is not.

**Comment by SpacePossum** [comment]
it is https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6587/files#diff-a2d4cffd0de539119338e23b2bb2a920285abeb49301d31c39ba3c2bb134834dR1073

**Comment by mvorisek** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6587 PR opened & merged yesterday, thanks!, yes, this PR can be closed then
