### ISSUE TITLE
[PHP8.2] Run CI workflow on 8.2

### ISSUE THREAD

**Issue by Wirone** [FriendsOfPHP/PHP-CS-Fixer#6603]
The goal of this task is to run CI workflow on PHP8.2 (new matrix items).

Before actual 8.2 release these actions must be non-blocking (allowed failure) in order to allow working on further issues related to changes introduced in PHP 8.2. After providing full support for 8.2, those actions must be changed to required (non-failure).

**Comment by kubawerlos** [comment]
This is not the first PHP major or minor release in the history of PHP CS Fixer 😉 

This is already being taken care in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6558 - do not hesitate to leave your review there.

**Comment by Wirone** [comment]
@kubawerlos I talked with @keradus the other day and we decided to try with milestone with separate issues, to track all changes related to 8.2 in one place. I finally sat down to do it 😅 It does not conflict with #6558, that PR should have proper description to link it with this issue, so I would keep this one opened and close it when this support actually is done in Github Actions.

**Comment by kubawerlos** [comment]
You can do similar we had with PHP 8.1, which is a single issue (being kind of epic): https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5891 - will not be much more for PHP 8.2 than is in that one. 

I see milestones reflect versions: https://github.com/FriendsOfPHP/PHP-CS-Fixer/milestones?state=closed, not supported PHP versions, are we sure we want mix them?

> It does not conflict with https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6558, that PR should have a proper description to link it with this issue

What's wrong with the description? Looks fine. There is no need to have both issue and PR.

**Comment by Wirone** [comment]
> What's wrong with the description? Looks fine.

`No description provided.` 😅 There should be "Fixes #6603" to link PR to issue. 

> There is no need to have both issue and PR.

It depends. Issue can define some concern to solve, that can be delivered through multiple PRs. So again: milestone would group all tasks related to PHP 8.2, PRs should point to issues. With such structure it's easy to track remaining work, issue can be a living checklist for one concern while PRs can provide changes, even in smaller chunks.

Let's wait for @keradus 😉

**Comment by kubawerlos** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6558 was created before this issue, so was not possible to link to it.

> It depends. Issue can define some concern to solve, that can be delivered through multiple PRs.

Of course, I meant there is no need to have both for every issue, like this one. If PR is already created then creating an issue does not bring any value.

**Comment by Wirone** [comment]
> #6558 was created before this issue, so was not possible to link to it.

But it's possible now 😉 Author or maintainers can edit description and add reference to the issue.

> If PR is already created then creating an issue does not bring any value.

The value is clear: issue can be used as a place for discussion about scope, while PR is mainly for technical discussion about delivered changes. Issues most probably are better for release notes (since they have kind: bugfix / feature; since multiple PRs can be related to one issue and there's no need to list all of them in the release notes).

But to be fair: I'm rather Gitlab+Jira user, and I don't know project's current workflow and processes, so I don't want to force solutions here. I just discuss 🤷 😉

**Comment by SpacePossum** [comment]
Yeah I general it is a good idea to have an `issue` for discussion and than move on to a PR for technical implementation and discuss the implementation over there. I think most of us here agree on this.
In this case however, I think there is no much need for an issue and discussion in an `issue` as it is pretty clear as what needs to be done and since there is already a PR for it I think the discussion can continue there. So no need to go back to discussion it here as well in this case ;)
