### ISSUE TITLE
How to write test for team custom fixer rule?

### ISSUE THREAD

**Issue by kayw-geek** [FriendsOfPHP/PHP-CS-Fixer#6645]
We extended the `PhpCsFixer\AbstractFixer` class to realize some only applied for custom rule of ourselves team, these rules were work great, but we cannot to write test for them, because this `PHPCSFixer` package haven't the `tests` directory.

Do you have any good solution for the question?
 
maybe you can split the `tests` directory to a standalone package?

**Comment by WinterSilence** [comment]
> because this PHPCSFixer package haven't the tests directory.

What's you mean? The directory https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master/tests is exists.
You can extends `PhpCsFixer\Tests\AbstractFixerTest` to tests of your extended class.

**Comment by kubawerlos** [comment]
> What's you mean? The directory https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master/tests is exists. You can extends `PhpCsFixer\Tests\AbstractFixerTest` to tests of your extended class.

Directory `tests` is absent when you install PHP CS Fixer as a dependency from [`dist`](https://getcomposer.org/doc/06-config.md#preferred-install).

@kayw-geek you have to install PHP CS Fixer from sources and add tests to your `autoload-dev`.

Recently there was a discussion about this on Gitter: https://gitter.im/PHP-CS-Fixer/Lobby?at=63041694f4d7a323de71393d with the solution [linked](https://github.com/elyby/php-code-style/commit/18806e41e217a4c9d707d69ea134a182c38a6475#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) in the last message.

**Comment by WinterSilence** [comment]
@kayw-geek (based on @kubawerlos comment) update self `composer.json` to install PHP CS Fixer from sources:
~~~json
{
    "config": {
        "preferred-install": {
            "friendsofphp/php-cs-fixer": "source"
        }
    }
}
~~~

**Comment by kayw-geek** [comment]
> 
@kubawerlos @WinterSilence 
Thank you very much.
Oh, blame me for not being familiar with the usage of this composer, thank you help my team solve the problem.
