### ISSUE TITLE
`no_trailing_whitespace_in_comment` and question mark comment

### ISSUE THREAD

**Issue by Phenix789** [FriendsOfPHP/PHP-CS-Fixer#6656]
## Bug report

The `no_trailing_whitespace_in_comment` fixer remove last space on "one line php comment".  

In my project, I still have some php template and sometime, I open/close php tag to write a comment.  
And trailing space are remove without trouble (even if it could be great to keep it).  
But, if the comment finish with a question mark, the php close tag are not anymore interpreted.

Version
```
PHP CS Fixer 3.8.0
PHP runtime: 8.1.10
```

Rules sets
```php
'@PHP80Migration' => true,
'@Symfony' => true,
```

### Code snippet that reproduces the problem

```php
<?php // Simple comment ?>
<?php // This is a comment finishing with a question mark ? ?>
```
will be fixed to
```php
<?php // Simple comment?> -> OK
<?php // This is a comment finishing with a question mark ??> -> KO
```

**Comment by keradus** [comment]
wow, very interesting case indeed!

**Comment by keradus** [comment]
> But, if the comment finish with a question mark, the php close tag are not anymore interpreted.

can you elaborate on that, @Phenix789 ? PHP parser properly understand `//comment ??>` as `//comment ?` and `?>`
https://3v4l.org/SbvWu#v8.1.10

**Comment by Phenix789** [comment]
After more few tests, effectively the PHP parser properly understand `// comment ??>` .  
I had an other bug in my file and PHPStorm show me this line as error

![image](https://user-images.githubusercontent.com/330834/195818828-ab0ac05a-b93b-4626-87db-9823410e3ab9.png)

I opened an issue a bit quickly.  
I close this issue and thank for your time.
