### ISSUE TITLE
Superfluous blank lines with `no_superfluous_phpdoc_tags`

### ISSUE THREAD

**Issue by lupinitylabs** [FriendsOfPHP/PHP-CS-Fixer#6670]
## Bug report

Version Info:
PHP CS Fixer 3.12.0 Oliva
PHP runtime: 8.1.8

Command line: `vendor/bin/php-cs-fixer fix foo.php`

Config file:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('somedir')
;

$config = new PhpCsFixer\Config();
return $config->setRules([
        '@PSR12' => true,
	'no_superfluous_phpdoc_tags' => true,
    ])
    ->setFinder($finder);
```

When run with the `no_superfluous_phpdoc_tags` option, PHP CS Fixer leaves superfluous blank lines in phpdoc comments when removing a single superfluous param:

![grafik](https://user-images.githubusercontent.com/17774818/198607996-55864343-04d7-44b7-b077-1b7fa8b239ad.png)

Instead, I would expect it to remove one of the blank lines along with the last removed phpdoc line.

### Code snippet that reproduces the problem

```php
  <?php

    class Foo {
        /**
         * Validate and create a newly registered user.
         *
         * @param  array  $input
         *
         * @throws ValidationException
         */
        public function create(array $input): User
        {
        }
    }
```

**Comment by julienfalque** [comment]
You can enable the [`phpdoc_trim_consecutive_blank_line_separation`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/phpdoc/phpdoc_trim_consecutive_blank_line_separation.rst) rule to prevent that.

**Comment by lupinitylabs** [comment]
Nice! Thanks, I missed that rule. 👍
