### ISSUE TITLE
Blacklisting indentation has no effect

### ISSUE THREAD

**Issue by Alex-PK** [FriendsOfPHP/PHP-CS-Fixer#720]
I am trying to activate all the fixes but the indentation one. This is the command line:

php-cs-fixer.phar fix --fixers="-indentation" --verbose --dry-run --diff ./

But it's ignoring the indentation blacklist, and changing all tabs to spaces.

**Comment by gabrielpreston** [comment]
Just ran into this problem yesterday when trying this out as a replacement for phptidy. Would love to see this fixed, but haven't delved into it enough to see what it might take.

**Comment by GrahamCampbell** [comment]
This isn't a bug. You just need to disable the braces fixer as well as the indention fixer.

**Comment by gabrielpreston** [comment]
That's not the greatest solution, what if I want to have the braces corrected as well?

**Comment by GrahamCampbell** [comment]
Correcting braces includes checking their contents is correctly indented.

**Comment by GrahamCampbell** [comment]
Tabs for indentation is incorrect.

**Comment by gabrielpreston** [comment]
Correct, but why bother allowing you to not use a fixer then? Some company's have their own standards that deviate from full PSR compliance, which I believe is why this project allows you to do things like -<fixer> so you can completely customize what form of compliance you need for your project.

**Comment by keradus** [comment]
It is strongly recommend to follow PSR.

This tool does not support using tabs in code or Win line ending. It can convert them to be cool with PSR, but when you decided to not doing that you can sometimes get some fancy results

**Comment by keradus** [comment]
Closing due to discussion and the fact of thread is dead for 3 months.
