### ISSUE TITLE
PHP CS Fixer remove used use statement

### ISSUE THREAD

**Issue by dunglas** [FriendsOfPHP/PHP-CS-Fixer#729]
When working with Doctrine Extensions traits, annotations used in the trait must be imported in the class that use the trait.

Sample code:

``` php
namespace Acme;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity
 */
class Test
{
    use TimestampableEntity;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;
}
```

`Gedmo` annotations are not used in the parent class but they are in the trait (see https://github.com/Atlantic18/DoctrineExtensions/blob/v2.3.9/lib/Gedmo/Timestampable/Traits/TimestampableEntity.php).
PHP CS Fixer remove the following line:
`use Gedmo\Mapping\Annotation as Gedmo;`

As a workaround, the annotation can be imported directly in the trait (it's done in the `master` branch for Doctrine extensions).

**Comment by TomasVotruba** [comment]
Any solution to this in current 2.4 version? Thank you

**Comment by julienfalque** [comment]
Like mentioned in this discussion, the behavior of PHP CS Fixer is correct. If you're using Doctrine Annotation, please update it. If you're not using it and you faced a bug, please open a new issue.

**Comment by TomasVotruba** [comment]
I mean is there any fixer that removes unused use statements?

**Comment by julienfalque** [comment]
Yes: `no_unused_imports`.

**Comment by TomasVotruba** [comment]
Ah, thanks!

**Comment by keradus** [comment]
good thing there is a readme file... or website...

**Comment by TomasVotruba** [comment]
Good one ;) 

I looked for "remove unused statements"
