### ISSUE TITLE
Spaces are added between the case and the colon after an upgrade

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#7502]
Hello there,

After the latest vendor upgrades in my project (including `symplify/easy-coding-standard` 12.0.8 => 12.0.11), the following kind of changes started being reported : 

```diff
    ---------- begin diff ----------
@@ -72,7 +72,7 @@
                     }
                     break;

-                default:
+                default :
                     throw new LogicException('...');
             }
         }
    ----------- end diff -----------
```

Applied checkers:

 * PhpCsFixer\Fixer\Alias\ArrayPushFixer
 * PhpCsFixer\Fixer\Casing\IntegerLiteralCaseFixer
 * PhpCsFixer\Fixer\ControlStructure\SwitchCaseSpaceFixer
 * PhpCsFixer\Fixer\FunctionNotation\NativeFunctionInvocationFixer
 * PhpCsFixer\Fixer\Import\GlobalNamespaceImportFixer
 * PhpCsFixer\Fixer\Operator\TernaryOperatorSpacesFixer

I first tried to disable `PhpCsFixer\Fixer\ControlStructure\SwitchCaseSpaceFixer`, but the change was still reported. After trial and error, the culprit seems to be `NativeFunctionInvocationFixer` ; if I disable it, the issue does not occur anymore.

I can't understand why or how that could happen. Would you have any idea ?
Thanks for your help.

**Comment by keradus** [comment]
I would say more - please provide full details that are requested on bug-report template - otherwise, we would be only guessing what's going on here, and this is not easing anyone to help with the issue.

ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.md

**Comment by gnutix** [comment]
@gabrielpioto @luizfernandow You :+1: the issue, do you have the same one ? What's your setup ? Could we find the common denominator ?

**Comment by gnutix** [comment]
The issue cannot be reproduced after upgrading from/to :

* `squizlabs/php_codesniffer`: 3.7.2 => 3.8.1
* `symplify/easy-coding-standard`: 12.0.8 => 12.1.10
