### ISSUE TITLE
[PHP8.3] "final public const string JOURNEY" leads to "Class constants must be uppercase"

### ISSUE THREAD

**Issue by ralusnom** [FriendsOfPHP/PHP-CS-Fixer#7511]
**sorry, i was confused about CS and CS.** 

## Description

In IntelliJ IDEA phpcs, incorrectly flags valid PHP code as an warning. Specifically, it misinterprets the type of class constants. For example, declaring a constant like `final public const string JOURNEY;` results in an error message from  stating 

"phpcs: Class constants must be uppercase; expected STRING but found string".

It seems that phpcs is incorrectly checking the type declaration (`string`) instead of the constant name (`JOURNEY`).

## Code snippet that reproduces the problem

```php
<?php
// Erroneous code snippet
final public const string JOURNEY;
```

**Comment by Wirone** [comment]
@ralusnom actually it should be reported [here](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues) because of squizlabs/PHP_CodeSniffer#3932.
