### ISSUE TITLE
PHP 5.3: trim content after __HALT_COMPILER

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#760]
Ugly bug at PHP 5.3

```php
<?php

$code = '<?php $x=1; __halt_compiler(); AFTER';
$tokens = token_get_all($code);

echo "TOTAL: " . count($tokens);
var_dump($tokens);
```

[on 5.3.29](http://codepad.viper-7.com/RBv0q6)

[on 5.4.33](http://codepad.viper-7.com/gC6JmW)

We can't do much with that particular PHP's bug.

It was [proposed](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/754#issuecomment-64034741) to ignore files containing __HALT_COMPILER on PHP 5.3 - because it is better to leave file alone instead of destroy it by remove some of it's content.

Any suggestions / opinions?

**Comment by stof** [comment]
@keradus I think this is quite important (and should probably still go in 1.4)

**Comment by keradus** [comment]
@stof if anyone can implement it I will be more than happy to merge it into 1.4.
Willing to send a PR? ;)

**Comment by stof** [comment]
PR sent

**Comment by keradus** [comment]
Nice ;)

**Comment by GrahamCampbell** [comment]
Can this be closed now?

**Comment by keradus** [comment]
Closing due to merge of #945
