### ISSUE TITLE
Wrapped array elements indentation not fixed.

### ISSUE THREAD

**Issue by jian-wu** [FriendsOfPHP/PHP-CS-Fixer#770]
Hi, 

I came across an issue where elements in array that are wrapped with double indentation, which isn't fixed by the fixer.

```
<?php
// expected
$var = array(
    'a' => 1,
    'b' => 2,
);
// actual
$var = array(
        'a' => 1,
        'b' => 2,
);
```

I've tried adding this case to the indentation fixer but it does not fail on unit test.

Can someone please verify or let me know it's not an issue?

Thanks.

**Comment by harikt** [comment]
I have something similar.

The code was having tabs and when I ran to convert to psr-2 it changed to spaces . But there is 8 spaces. See

```php
return $this->render(
            'AcmeShopBundle:Random:index.html.twig',
array(
'number' => $number
                )
        );
```

the above code is very ugly and it is unable to make it look nice :( .

**Comment by keradus** [comment]
Closing due to amazing work of #3135 by @julienfalque
