### ISSUE TITLE
Indentation count lost after comment in code

### ISSUE THREAD

**Issue by gimler** [FriendsOfPHP/PHP-CS-Fixer#774]
every time there is a comment with `//` he lost the intenation count

examples
```
                $this->optionen = "nn"; // default: kein Gutscheinkonto, Kreditrahmen nicht nutzen
         $this->user_id = 0;
```
```
            // ATTENTION
       // my comment
       //
```

**Comment by dereuromark** [comment]
This should be reopened then until the fixer is working properly.

**Comment by keradus** [comment]
Bug is reported with it testcase as PR. Do we really need to have thing reported twice?
Let assume #935 as replacement of #774 ;)

**Comment by dereuromark** [comment]
All right :)
