### ISSUE TITLE
Issues with multiline_array_trailing_comma

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#788]
Concerning the second file here:

![](http://i.imgur.com/Hin8hmQ.png)

The array that was modified was not a multiline array, but was treated as one.

**Comment by dereuromark** [comment]
I also got an noise `, ` added where it should not have happened
```php
$x = [
    1 => 2,
    3 => [1, 3]]
```
becomes
```php
$x = [
    1 => 2,
    3 => [1, 3, ]]
```

but it should stay as it is. A trailing comma may only be added if there is not a bracket following directly afterwards. A different fixer would have to take care of fixing the array structure first.

**Comment by keradus** [comment]
Writing in issue closed year ago isn't best way to raise an issue...
Consider you want to find all issues and fix some - this one is already closed!

**Comment by dereuromark** [comment]
I can also open a new one, no problem.
