### ISSUE TITLE
Constructor Not Being Indented Correctly

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#797]
I just ran php-cs-fixer on symfony's 2.6, branch, and found it corrected the indentation on only some functions:

https://github.com/GrahamCampbell/symfony/commit/b25bc38c9898fdf0dec69158938e6ea19a0e26fe#diff-59433ee1eeb1e828c36bb517135f09e5R44

The constructor is incorrectly indented like the other functions, but php-cs-fixer didn't change the indentation.

**Comment by SpacePossum** [comment]
ping @GrahamCampbell :)

**Comment by SpacePossum** [comment]
Tested on master and still an issue. This happens only when the PHPDoc indent is of as well and all methods are effected (i.e. not only constructors).
For ref. this is a duplicate issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2176

**Comment by keradus** [comment]
Fixed, will be released soon. thanks to @julienfalque !
