### ISSUE TITLE
BracesFixer has too many responsibilities

### ISSUE THREAD

**Issue by ceeram** [FriendsOfPHP/PHP-CS-Fixer#823]
For instance #797 is also caused by this fixer, which i would not expect. The braces fixer seems to also fix proper indentation for other things, which imo should be a separate fixer

**Comment by keradus** [comment]
It may be easier to split if one fixer could make another one as dependency (can't run without it)

**Comment by GrahamCampbell** [comment]
Yeh, that could make things easier.

**Comment by keradus** [comment]
Issue is reported for 2 years. As it's valid, it's not an easy task to do. Closing to clean up the things.
Even after that, if one is feeling ready for the task - feel free to contribute !

**Comment by julienfalque** [comment]
I'm reopening because this still causes a lot of bug reports/feature requests related to this.

**Comment by julienfalque** [comment]
I've started working on this issue.
