### ISSUE TITLE
Feature request: preincrementation

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#831]
It would be cool to have a preincrementation fixer that changes `$i++` into `++$i`.

Of course it must not change all code cases, eg `$tab[$i++]` should not be changed

**Comment by stof** [comment]
other cases which should not be changed: 

- ``($i++)`` (it can be a function call argument, or other things more complex for which the return value is used)
- function arguments
- assignments: ``$a = $i++``
- previous or next meaningful token being an operator: ``$a + $i++`` or ``$i++ + $a``

**Comment by gharlan** [comment]
I'm working on this.

Should these cases be converted?

```php
$foo->bar++;
$foo[$bar]++;
```

**Comment by Anahkiasen** [comment]
Couldn't that be dangerous for cases where the values are returned? Like if someone is relying on the value being returned and _then_ incremented? Not saying it's smart to return an increment in the first place, but I could see that as breaking

**Comment by gharlan** [comment]
> Couldn't that be dangerous for cases where the values are returned?

Those cases won't be converted.

**Comment by dereuromark** [comment]
> Should these cases be converted?

Sure, why not.

**Comment by gharlan** [comment]
I'm not sure if they are less readable.

```php
++$foo->bar;
++$foo[$bar];
```

And they are harder to fix. ;) (but it is possible, of course)

**Comment by dereuromark** [comment]
Yeah looks like it.

Hm, thinking about it:
Personally, I have nothing against `$something++;` in code as long as its a one liner (no side effects).
Then it doesnt matter if you increment pre or post.
And incrementing post sure does somethings read better.

The only place where order really matters is inside operations, and then you can't automatically fix it anyway without breaking things.

**Comment by keradus** [comment]
pre vs post - CS thing is to use one in all places, when we dont rely on pre vs post matter.
So if pre/post is the standalone expression it should be always in same form, like always pre. If not (sometimes pre, sometimes post) then this will be not a standard and need no fixer for it.

If we want to standardize it (:+1:) pre should be used whenever possible (faster, uses less memory, even precompiling into bytecode change it that way).

**Comment by shinokada** [comment]
How to run php-cs-fixer without this feature? I don't want to change `$i++` to `++$i`.

**Comment by GrahamCampbell** [comment]
Please checkout the docs on the readme. You can just exclude this fixer.

**Comment by namluu** [comment]
Hi @GrahamCampbell 
How to exclude the "pre_increment" fix by command line? I don't want to fix it in a loop, since the start item is 1 instead of 0

**Comment by SpacePossum** [comment]
Hi @namluu,

Please see the README (https://github.com/FriendsOfPHP/PHP-CS-Fixer) and search for `blacklist`:
```
You can also blacklist the fixers you don't want by placing a dash in front of the fixer name, if this is more convenient, using -name_of_fixer:

$ php php-cs-fixer.phar fix /path/to/dir --fixers=-pre_increment
```

**Comment by namluu** [comment]
Thanks @SpacePossum . That what I looking for (y)

**Comment by gharlan** [comment]
> I don't want to fix it in a loop, since the start item is 1 instead of 0

So it would change code behavior? This should not be happen. Could you give us an example?

**Comment by namluu** [comment]
Hi @gharlan 
I've checked again. Sorry for my mistake.
You're right. It doesn't change code behavior.
Thanks a lot for your fast help
