### ISSUE TITLE
Show info about loaded config file and progress on xml/json output

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#839]
Currently that messages break xml/json format.

Ref : #826

**Comment by sstok** [comment]
Is this one still relevant? I don't think its possible to show progress with JSON as this needs to clear the screen buffer. Just outputting when its done should be enough, or you need use a JSON output per line and require to parse per line.

**Comment by stof** [comment]
@keradus the solution would be to write these information messages to stderr, keeping stdout for the actual command output (i.e. something you would pipe to the next command).

See https://github.com/composer/composer/issues/3795 (and links given in it to other issues) for some discussion about the similar change done in Composer

**Comment by keradus** [comment]
One day it corrupt xml/json output. The output was fixed (stop showing info).
The question do we want to care about it is relevant.

**Comment by keradus** [comment]
Closing as done
