### ISSUE TITLE
Better token parsing

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfPHP/PHP-CS-Fixer#859]
While writing some custom sniffers I was surprised how bad the original PHP token parsing is (Note: by PHP itself - not criticizing the lib here!).
It parses most of the PHP tokens as just text, without a proper "token id" etc:

     'content' => ')',
     'id' => NULL,
     'isArray' => false,
     'line' => NULL,

It would be good if the php-cs-fixer parser here on top would enhance the result to allow making the fixer classes itself less complex.

Currently, way too many tokens are not too usable out of the box right now, or we need to compare strings instead of the functionality they provide / their semantic meaning in that context:

```php
if ($tokens[$leftIndex]->getContent() === ')') {
	continue;
}
// Is ) now part of a method declaration or a (x+y) operations binder etc? 
```

 This makes the code often times more complicated, as well.

Sometimes, I added this inside the fixers to be able to work with it in a clean way:
```php
// Why are those two (apart from many more) not included in the PHP token constants?
// Seems like PHP itself really has some catching up to do.
define('T_GREATER_THAN', 1024);
define('T_LESS_THAN', 1025);

// Fix incomplete token parsing
if ($tokens[$comparisonIndex]->getContent() === '<') {
	$tokens[$comparisonIndex]->override(array(T_LESS_THAN, '<', $tokens[$comparisonIndex]->getLine()));
}
if ($tokens[$comparisonIndex]->getContent() === '>') {
	$tokens[$comparisonIndex]->override(array(T_GREATER_THAN, '>', $tokens[$comparisonIndex]->getLine()));
}

...
// Now we can use the complete list of operation token ids
$tokensToCheck = array(T_IS_IDENTICAL, T_IS_NOT_IDENTICAL, T_IS_EQUAL, T_IS_NOT_EQUAL, T_GREATER_THAN, T_LESS_THAN,
			T_IS_GREATER_OR_EQUAL, T_IS_SMALLER_OR_EQUAL);
if (!in_array($tokens[$comparisonIndex]->getId(), $tokensToCheck, true)) {
	continue;
}
```

a) We should, like phpcs(f) does, provide more constants on top of the existing ones, shimming older PHP versions, if required, in the process:
```php
// Some PHP 5.5 tokens, replicated for lower versions.
if (defined('T_FINALLY') === false) {
	define('T_FINALLY', 1059);
}
if (defined('T_YIELD') === false) {
	define('T_YIELD', 1065);
}
// Some PHP 5.6 tokens, replicated for lower versions.
if (defined('T_ELLIPSIS') === false) {
	define('T_ELLIPSIS', 1066);
}
```

Less `id => null` means better way of working with the tokens inside the fixers. Especially when some chars can mean different things in different contexts.
```php
if ($tokens[$leftIndex]->getId() === T_OPEN_PARENTHESES) {
    continue;
}
// Now it is clear
```

b) We could pre-parse the token list and add more information to them, e.g. where the scope closer or parentheses openers/closers are and complete the line numbers where missing. This would take out the logic overhead in the fixers, as well, that need that information.
Alternatively we could provide such methods in the Tokens class:

    public function findMatchingOpener()
    public function findMatchingCloser()

etc.

The better the token parser, the easier and maintainable the fixers IMO.
What do you think?

**Comment by keradus** [comment]
Thanks for discussion.

Parsing was discussed sufficiently, some idea was rejected, some was already done via Transformers.

Candidate approach was moved into separate thread: #984
