### ISSUE TITLE
Change way of setting fixers that should be run

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#866]
Ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/805#issuecomment-66501096
> Just my two cents on the current situation. I think fixers shouldn't be in a level, they should just have a name, and then you would have groups of fixers with names too, and potentially groups of groups (I'd suggest some way of distinguishing them to avoid name clashes), and one of these groups would be the default group.
> 
> It would also make it a lot easier to say in the config: ->fixers(['@psr2', 'fixer-x']) if I want only psr-2 without psr-1 fixers (that may not make sense but you get my point). You could also have a @psr group that includes ['@psr0', '@psr1', '@psr2'] for example. And different themed groups maybe like @alignthings could include align_double_arrow and align_equals and any new alignment-related added in the future. Fixers could be in multiple groups too this way.
> 
> What I don't like right now is I can't trust the symfony/default level to not add new fixers I don't like, so I have to list all fixers I want to use explicitly, but then if new fixers are added I may miss them. So if I could "trust" the @psr group because I know for sure that any new fixer there will be ok with me, that would already shorten the list greatly :)
> 
> (by @Seldaek)

**Comment by stof** [comment]
This looks like an interesting approach.

**Comment by keradus** [comment]
This issue may be here for a long time, but is not abandoned!
See #1383

**Comment by keradus** [comment]
Closing due to merge of #1383
