### ISSUE TITLE
Improve speed: FixerInterface change

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#867]
Currently:
`FixerInterface::fix(SplFileInfo $file, $content)`

I would made it:
`FixerInterface::fix(SplFileInfo $file, Tokens $tokens)`

Yes, it is a BC breaker for 2.0.

What happens now - file content is passed into next and next fixer - each of them receive full code as string and create Tokens from it - it is quite ok due to internal Tokens::$cache.
But at end of work of single fixer - the code it transformed back into string to compare if strings changed - and if yes then the PHP CS Fixer know that the file was changed by fixer.
That means we regenerate full content for each fixer.

Proposed change will release us of that performance lack, but then we will need to observe Tokens to detect if whole collection or just one collection element changed.

What do you think ?

//cc @dericofilho

**Comment by gharlan** [comment]
I would like if we could remove the `SplFileInfo` parameter.

Maybe `$tokens->getFileInfo()`? I'm not sure...

**Comment by keradus** [comment]
Hiding `SplFileInfo` under `Tokens` won't change the interface so much.
OK, indeed, the method prototype will be changed, but we will still pass both information to the method.

**Comment by stof** [comment]
@keradus this brings again the question whether the risky PSR-0 fixer should be kept (which is fixing things in the wrong way most of the time btw). My vote on the question has not changed since years (Remove it). If it gets removed, we could get rid of the SplFileInfo.

**Comment by gharlan** [comment]
@stof :+1:

**Comment by funivan** [comment]
:+1: on this and on removing splfileinfo
