### ISSUE TITLE
[Proposal] Array Un-Align Fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#882]
Does the reverse of our array align fixer, and makes sure array elements are not aligned up.

I'd be happy to write this for the contrib level to hopefully go into 1.5.

**Comment by ptcong** [comment]
:+1: 
@GrahamCampbell  i have tried with symfony level but nothing happen.

**Comment by keradus** [comment]
Nothing happen because this is only *proposal* of fixer at Symfony level.

**Comment by GrahamCampbell** [comment]
If nobody does this by July/August, I'll take it on. :)

**Comment by ptcong** [comment]
nearly 1 year after the issue created, it's too long @GrahamCampbell , could you start it now ?

**Comment by keradus** [comment]
It would be great to have it done indeed, but please remember @ptcong, everyone of us spend his free time to work on this project, and we simply need to use some kind of prioritization.

If you want that fixer done please simply consider helping creating it ([guide](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.7/COOKBOOK-FIXERS.md)).

**Comment by ptcong** [comment]
@keradus ya, i know, but i mean, after 1 years, still have nobody take it then @GrahamCampbell  should take it nearly if he have free time, don't need to wait others take it.

**Comment by GrahamCampbell** [comment]
@ptcong No, I'm telling you I will do it then. I'm not bringing it forward. If you want to write it first, then that's fine by me. I just won't be doing it any earlier.

**Comment by keradus** [comment]
Implemented in #1167 and #1168

**Comment by keradus** [comment]
Closing due to merge of both PRs

**Comment by pliashkou** [comment]
Guys, just wondering, what is the reason of implementing these fixers and why alignment is not correct?

**Comment by GrahamCampbell** [comment]
> why alignment is not correct?

It makes more sense to not align to reduce diff sizes and prevent merge conflicts.
