### ISSUE TITLE
Improving Fixer Names In 2.0

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#889]
Here are my ideas. Please discuss! :)

| Current Name                       | Proposed Name                      |
|------------------------------------|------------------------------------|
| eof_ending                         | single_eol_at_eof                  |
| function_call_space                | no_spaces_after_method_name        |
| function_declaration               | closure_definition_spacing         |
| linefeed                           | unix_line_endings                  |
| multiple_use                       | single_statement_per_import        |
| parenthesis                        | no_spaces_inside_parenthesis       |
| trailing_spaces                    | no_trailing_whitespace             |
| visibility                         | visibility_required                |
| double_arrow_multiline_whitespaces | double_arrow_multiline_whitespace  |
| duplicate_semicolon                | no_duplicate_semicolons            |
| multiline_array_trailing_comma     | trailing_comma_multiline_array     |
| namespace_no_leading_whitespace    | no_leading_namespace_whitespace    |
| single_array_no_trailing_comma     | no_trailing_comma_single_array     |
| multiline_spaces_before_semicolon  | no_whitespace_before_semicolons    |

**Comment by keradus** [comment]
This thread is very important.
We need to come back here after new pack of phpdoc fixers will be merged.

**Comment by gharlan** [comment]
`UnaryOperatorsSpacesFixer` vs. `OperatorsSpacesFixer` vs. `TernarySpacesFixer`..

**Comment by keradus** [comment]
@GrahamCampbell could you apply @stof's and @gharlan's propositions in first msg please?

**Comment by keradus** [comment]
`visibility` vs `visibility_required`
this fixer does not only add missing visibility, but also handle sequence of visibility, abstract, static...

**Comment by GrahamCampbell** [comment]
It also changes things like `var $foo;` to `public $foo;`.

**Comment by GrahamCampbell** [comment]
> this fixer does not only add missing visibility, but also handle sequence of visibility, abstract, static...

Could we abstract the order changing stuff to another fixer?

**Comment by keradus** [comment]
That would be great, but then:
- fixer that does ordering will need to be enhanced to support non-perfect syntax (eg without visibility) or force that extracted fixers to run
- sb will need to split the fixer

Both take time, and while idea is cool, the simply renaming is less time consuming.

**Comment by SpacePossum** [comment]
I like the proposal from @GrahamCampbell for the new names :+1: , but  Im with stof and ceeram.

>> Shall we also discuss names of fixers about blanklines

>Yeh. I think we should go with empty rather than blank everywhere. :)

I like `empty` over `blank`. One thing to consider is that PSR-2 (AFAIK the only PSR dealing with `blank`/`empty` lines) uses `blank line` throughout. It might be confusing for users to name this different here then it is called in the PSR?

**Comment by dereuromark** [comment]
As per https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1360
there is a mistake in the initial post
```
"double_arrow_multiline_whitespaces" 
should be 
"double_arrow_no_multiline_whitespace"
´``

Also see the other semantic tips.

**Comment by SpacePossum** [comment]
some class name renaming suggestions

current | new
----------|-----------
NoEmptyLinesAfterPhpdocsFixer | NoBlankLinesAfterPhpdocsFixer
ExtraEmptyLinesFixer | ExtraBlankLinesFixer 
RemoveLinesBetweenUsesFixer | RemoveBlankLinesBetweenUsesFixer 
BlanklineAfterOpenTagFixer | BlankLineAfterOpenTagFixer


no changes needed:
NoBlankLinesAfterClassOpeningFixer
NoBlankLinesBeforeNamespaceFixer
SingleBlankLineBeforeNamespaceFixer

**Comment by stof** [comment]
I think fixer renaming should be handled in the most BC way possible:

- add a way for fixers to specify an alternate name in 1.x (allowing fixers to provide their new names in 1.x already). 
- rename the classes in 2.x and keep the old 1.x name as an alternate name for now

The config resolver would build a map of alternate names to real names and replace alternate names with their real names when finding them in the ``--fixers`` option.

This would allow a more user-friendly upgrade path. What do you think @keradus @GrahamCampbell ?

**Comment by keradus** [comment]
1. Why the fixers option, but not in .php_cs file?
2. Upgrade from 1.x to 2.x will not be easy and one way or another user will still must to change a lot of things, I do not see big benefits for introducing that. We have too many non-good part of code which we cannot change to not break BC and we are changing most of them in 2.x, so it would be great to not introduce them there too.

**Comment by dereuromark** [comment]
I agree.
A simple mapping list (old => new) should suffice for everyone to update their sniff names in use.

**Comment by keradus** [comment]
I think 2.x is quite ready for such renames. Could anyone propose a complete renames table?

**Comment by Soullivaneuh** [comment]
@keradus Is a BC planned for this? Would be better.

@GrahamCampbell I suppose you will add it on your aliases fixers for StyleCI, isn't it?

**Comment by GrahamCampbell** [comment]
Yeh, I will. :)

**Comment by keradus** [comment]
Anyone willing to create full list of needed changes ?
I will be more than happy to finally get it done!

**Comment by keradus** [comment]
Anyone? :(

**Comment by GrahamCampbell** [comment]
I will. ;)

**Comment by keradus** [comment]
great to hear !

**Comment by GrahamCampbell** [comment]
How does this look?

| Current Name                               | Proposed Name                        |
|--------------------------------------------|--------------------------------------|
| blankline_after_open_tag_fixer             | blank_line_after_opening_tag         |
| double_arrow_multiline_whitespaces         | double_arrow_no_multiline_whitespace |
| duplicate_semicolon                        | no_duplicate_semicolons              |
| eof_ending                                 | single_eol_at_eof                    |
| extra_empty_lines                          | extra_blank_lines                    |
| function_call_space                        | no_spaces_after_method_name          |
| linefeed                                   | unix_line_endings                    |
| logical_not_operators_with_spaces          | not_operators_with_spaces            |
| logical_not_operators_with_successor_space | not_operator_with_successor_space    |
| multiline_array_trailing_comma             | trailing_comma_multiline_array       |
| multiline_spaces_before_semicolon          | no_whitespace_before_semicolons      |
| multiple_use                               | single_import_per_statement          |
| namespace_no_leading_whitespace            | no_leading_namespace_whitespace      |
| newline_after_open_tag                     | line_after_opening_tag               |
| no_empty_lines_after_phpdocs               | no_blank_lines_after_phpdoc          |
| operators_spaces                           | binary_operator_spaces               |
| parenthesis                                | no_spaces_inside_parenthesis         |
| remove_lines_between_uses                  | remove_blank_lines_between_uses      |
| return                                     | line_after_return                    |
| single_array_no_trailing_comma             | no_trailing_comma_single_array       |
| ternary_spaces                             | ternary_operator_spaces              |
| trailing_spaces                            | no_trailing_whitespace               |
| unary_operators_spaces                     | unary_operator_spaces                |
| visibility                                 | visibility_required                  |

**Comment by SpacePossum** [comment]
`return` -> `line_after_return`
should be `line_before_return`

**Comment by GrahamCampbell** [comment]
Ah, yes. I'll update that in-place.

**Comment by keradus** [comment]
Please, could you combine it with the table in first post? (to have one full list)

**Comment by GrahamCampbell** [comment]
It is combined?

**Comment by GrahamCampbell** [comment]
Do you want me to update the original table?

**Comment by keradus** [comment]
Ohhh, I treated first one as main one.

**Comment by keradus** [comment]
| GrahamCampbell's Proposal                  | Keradus' Proposal                              |
|--------------------------------------------|--------------------------------------------|
| no_spaces_after_method_name                | no_spaces_after_function_name              |
| line_before_return                         | blank_line_before_return                   |
| line_after_opening_tag                     | linebreak_after_opening_tag                |
| no_trailing_comma_single_array             | no_trailing_comma_in_singleline_array      |
| trailing_comma_multiline_array             | trailing_comma_in_multiline_array          |
| remove_blank_lines_between_uses            | no_blank_lines_between_uses                |
| no_whitespace_before_semicolons            | no_multiline_whitespaces_before_semicolons |
| double_arrow_no_multiline_whitespace       | double_arrow_no_multiline_whitespaces      |
| no_leading_namespace_whitespace            | no_leading_namespace_whitespaces           |
| no_trailing_whitespace                     | no_trailing_whitespaces                    |
| not_operators_with_spaces                  | not_operators_with_space                   |
| extra_blank_lines                          | no_extra_consecutive_blank_lines           |

**Comment by keradus** [comment]
| Current Name                              | Keradus' Proposal                     |
|-------------------------------------------|---------------------------------------|
| short_tag                                 | full_opening_tag                      |
| short_echo_tag                            | no_short_echo_tag                     |
| php_closing_tag                           | no_closing_tag                        |
| indentation                               | no_tabs                               |
| line_after_namespace                      | blank_line_after_namespace            |
| ordered_use                               | ordered_imports                       |
| php4_constructor                          | no_php4_constructor                   |
| short_bool_cast                           | no_short_bool_cast                    |
| standardize_not_equal                     | standardize_not_equals                |
| array_element_no_space_before_comma       | no_whitespace_before_comma_in_array   |
| array_element_white_space_after_comma     | whitespace_after_comma_in_array       |
| empty_return                              | simplified_null_return                |
| unused_use                                | no_unused_use                         |
| unneeded_control_parentheses              | no_unneeded_control_parentheses       |
| list_commas                               | no_trailing_comma_in_list_call        |
| method_argument_default_value             | no_unreachable_default_argument_value |
| remove_leading_slash_use                  | no_leading_import_slash               |
| spaces_before_semicolon                   | no_singleline_whitespaces_before_semicolons |
| spaces_after_semicolon                    | space_after_semicolon                 |
| object_operator                           | object_operator_without_whitespaces   |

**Comment by GrahamCampbell** [comment]
> whitespaces

That doesn't make sense because whitespace is already plural.

**Comment by gharlan** [comment]
> no_unused_use

Why "use" and not "import" like in `ordered_imports` and `no_leading_import_slash`?

**Comment by GrahamCampbell** [comment]
Because it's for traits too. Or, do we say "import" for them too? I never really know, lol.

**Comment by keradus** [comment]
> whitespaces

updated

**Comment by keradus** [comment]
Any other thoughts ?

**Comment by gharlan** [comment]
Is your list an addition to the list of @GrahamCampbell or your complete proposal?

**Comment by GrahamCampbell** [comment]
Well, it's missing some from my list.

**Comment by keradus** [comment]
> Is your list an addition to the list of @GrahamCampbell or your complete proposal?

Two tables
- first with @GrahamCampbell 's proposals that, in my opinion, could be tweaked (so not every position - if sth is missing then its ok for me).
- second as an addition to @GrahamCampbell 's proposals

**Comment by GrahamCampbell** [comment]
Can we build a complete list, with the 1st column alphabetically sorted, like mine was?

**Comment by keradus** [comment]
https://docs.google.com/spreadsheets/d/18LwW5JGQbTYIJRkIbSHvvO_b3IRlVze7sa6zohBGDms/edit?usp=sharing
?

**Comment by gharlan** [comment]
@keradus sorry, I'm still not sure if I understand your proposal correctly.
Example: `blankline_after_open_tag` (empty field in your column): do you think the proposed name by @GrahamCampbell is good, or do you think the fixer should not be renamed?

**Comment by keradus** [comment]
is good, if you have some nice idea to sth mark it (without duplicating whole name) feel free!

**Comment by gharlan** [comment]
> Current (1.x) names

btw: I think we should not look only to current 1.x names, maybe there are some new fixers in 2.x which should be renamed, too.

**Comment by keradus** [comment]
good point, we could change it when we have such sample
(list does not contains all fixers, just the ones we want to rename)

**Comment by GrahamCampbell** [comment]
I was looking at the current 2.x names when I made my list.

**Comment by keradus** [comment]
ok

**Comment by keradus** [comment]
OK, So I assume that names on the most-right is OK.

**Comment by GrahamCampbell** [comment]
Sure, go for it. If we have any other issues with them, they can always be raised later. This will never happen otherwise.

**Comment by gharlan** [comment]
I can offer to create the pr. Or will you do this, @keradus ?

**Comment by keradus** [comment]
I have already started it, but have very little time now. Will try to send sth this night

**Comment by SpacePossum** [comment]
Over at https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1613#discussion_r49101573 a little discussion has held about using plural or not for fixer names.
Maybe have it here?
The case is; some fixers use plural for what the fixers fix, for example `braces` and `lowercase_constants` while other don't , like `linefeed` and `class_definition`.
Do we want to normalize this as well, or is this a non-issue?

**Comment by keradus** [comment]
Any thoughts on that ?
