### ISSUE TITLE
[PSR-2] Preserve blank line after control structure opening brace

### ISSUE THREAD

**Issue by marcaube** [FriendsOfPHP/PHP-CS-Fixer#890]
I may be mistaken, but I can't find a rule in the [PSR-2 standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#5-control-structures) that says there **must not** be a blank line after the opening brace `{` of a control structure.

It is my understanding that the following code should be perfectly valid ...

```php
if ($foo) {

    // The blank line helps with legibility in nested control structures
    if ($bar) {
        // if body
    }

    // if body
}
```

**Comment by keradus** [comment]
Closing due to merge of #895
