### ISSUE TITLE
AlignEqualsFixer break Token consistency

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#905]
AlignEqualsFixer break Token consistency.
Token suppose to be one of `token_get_all` element.

So take a look:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Contrib/AlignEqualsFixer.php#L52

Here, the simple `=` Token is changed into `____=` Token (_ for space), which is nor `T_WHITESPACE` nor `=`.
It should be to separated tokens. We need to edit previous token if it is a whitespace or add new token if not.

**Comment by keradus** [comment]
Idea of that fixers is to mark placeholders in first step and resolve them in second.
May be tricky to change it...

I deal with it differently in #902 , please see changes in `AbstractAlignFixer`, `AlignDoubleArrowFixer` and `AlignEqualsFixer`

**Comment by stof** [comment]
@keradus producing an invalid Token in the cached Tokens collection is still an issue IMO. It could do weird things for next fixers. So we need to investigate whether backporting your refactoring to 1.5 is needed or no.

**Comment by keradus** [comment]
It produced an invalid token temporary, on the end of `fix` method all tokens are valid.

**Comment by keradus** [comment]
It just marked tokens as `changed` on my #902, but on 1.x line tokens aren't marked as `changed` yet
