### ISSUE TITLE
Add The Ability To Mark Fixers As Conflicting

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#910]
We need a way to stop fixers such as the concatenation fixers as incompatible with each other, and prevent them from being run at the same time.

It would also be useful to allow fixers that depend on each other, and thus fixer Y can only be run if fixer X is enabled.

**Comment by keradus** [comment]
Anyone willing to make PR for this?
I think that mark the fixers as conflicting is enough for us, at least for now.

We have FixerFactory which could handle it.

Perhaps @SpacePossum ?

**Comment by SpacePossum** [comment]
I might give it a try, if I make it it will be this week as after that I have to focus on other (non PHP) development.

Btw. I was thinking about something and wonder what others think about it. What if we would mark some fixers as `reversible` (on 2.x line). That way some conflicts can be avoided by merging some of the fixers into one fixer that can be ran in reverse. For example;

Fixer | When ran in reversed acts as
------------ | -------------
SingleBlankLineBeforeNamespaceFixer | NoSingleBlankLineBeforeNamespaceFixer
concat_without_spaces | concat_with_spaces
phpdoc_type_to_var | phpdoc_var_to_type

There are others as well. 
Using configuration you could set the fixer to ran in reverse. From the command line we could do something like `fixers=~concat_without_spaces`.
It won't fix all conflicts, but quite some and it might reduce the code base a bit.

**Comment by keradus** [comment]
It would not resolve conflicts at all (at least I can't see it).

If one one ruleset: `{concat_without_spaces: true, concat_with_spaces: true}` then the knowledge of the fact that they are reversable doesn't help.

Also, turning off fixer (like `-foo`) is sth different than wanting the reverse fixer (eg `~foo`), but then one must to know that there is a reverse fixer, so he could as well simply use that explicitly.

**Comment by SpacePossum** [comment]
> {concat_without_spaces: true, concat_with_spaces: true}

The idea is no longer having those two fixers, but 1, which you could run in reverse.
So configure something like;
`{ concat_spaces: true}`
or 
`{ concat_spaces : reverse}`
or leave out the fixing at all
`{ concat_spaces : false}`

**Comment by keradus** [comment]
ref #1443
