### ISSUE TITLE
We Need A Way To Get All Imports For A Namespace

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#918]
I propose we introduce an `Import` class too. The import class needs to contain the fully qualified name, and the aliased name.

We then need another class that will return `Import[]` when given a namespace. This would be a massively useful abstraction, to be used by the unused use fixer, and a fqn docblock fixer I want to write.

**Comment by keradus** [comment]
No hearing on that and it would only refactor code - no new feature.
Closing PR as dead.

(But still, if anyone is willing to do so go ahead!)
