### ISSUE TITLE
Braces Fixer Proposals

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#920]
It would be cool to have two contrib level fixers to do the following:

1. A fixer to pull all opening braces on the same line.
2. A fixer to pull all opening braces on a new line.

**Comment by keradus** [comment]
@GrahamCampbell , which one braces does Laravel use currently ?

**Comment by GrahamCampbell** [comment]
Laravel now completely follows psr2.

**Comment by GrahamCampbell** [comment]
Infact, I can get you a list of fixers we use:

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.1/.php_cs

**Comment by keradus** [comment]
Great, closing.
For sure it would be easier to have @PSR2 group or even @Laravel group - maybe with lock file ;P
