### ISSUE TITLE
function join() and list($content, ) should not be check...

### ISSUE THREAD

**Issue by samsonasik** [FriendsOfPHP/PHP-CS-Fixer#930]
I think when using 'querybuilder' like : 
```php
public function join()
{
   // ...
}
```
the join() function should not be check and changed to implode. see my comment at : https://github.com/zendframework/zf2/pull/7079#discussion-diff-22297825 
and about : 
```php
list($content, ) = ...
```
should not be check too, see my comment at https://github.com/zendframework/zf2/pull/7079#discussion-diff-22298615 that  space not removed, then "parenthesis" cs, but when it removed, it makes another error : "method_argument_space".

**Comment by keradus** [comment]
Yeah, that is why issue reports shouldn't be closed so willingly.
This issue contains in facts 2 issues. First one is fixed already, but not the second one.

Please see solution at #952

//cc @samsonasik @GrahamCampbell @stof

**Comment by samsonasik** [comment]
@keradus thank you ;)
