### ISSUE TITLE
Issues installing PHP-CS-Fixer

### ISSUE THREAD

**Issue by paquitodev** [FriendsOfPHP/PHP-CS-Fixer#931]
Hi,
I'm trying to setup `php-cs-fixer` globally under a Centos 6.6 server and I'm doing something wrong since I can't get `php-cs-fixer` at command line in console. This is the steps I've follow to install it:

 - Run the command: `./composer global require fabpot/php-cs-fixer` and that installed some vendors under `/root`/.composer/vendor` where `php-cs-fixer` is 
 - Add this line at the end of `/root/.bash_profile` file: `export PATH="$PATH:$HOME/.composer/vendor/bin"`

What I'm doing wrong? Why I can't execute the command from console?

**Comment by keradus** [comment]
@paquitodev If any other tools installed via composer works for you, for example phpunit ?

**Comment by paquitodev** [comment]
@keradus I don't know why but I just restart my server and all is working now, I'll close the issue

**Comment by keradus** [comment]
Great to hear!
