### ISSUE TITLE
Proposal: mark fixer as "risky" (change meaning of code)

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#942]
What do you think about marking fixers as risky?

Currently: psr0, strict, strict_param.
In future fixer that trim all trailing spaces (even inside string content), as PSR2 requires.

Then that fixer will run only if risky fixers are allowed by config/cli.

Then, in future, one may run all PSR2 fixers safely without changing meaning of code or run all PSR2 fixers with that risky flag and then apply all PSR2 rules, even if they change code meaning.

**Comment by stof** [comment]
There should indeed be a way to mark them as risky (and no risky fixer should run by default)

**Comment by sstok** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
Proposal A:

non-dryRun mode:
- CLI arg is needed to use risky fixers
- without CLI arg risky fixers are omitted (with notice to user)
(as you can see, it's not configurable on ConfigInterface level)

dryRun mode:
- always use selected risky fixers

------------------------

Proposal B:

non-dryRun mode:
- with CLI/ConfigInterface option enabled run risky fixers
- without CLI/ConfigInterface option enabled and still fixers choosen - raise configuration error

dryRun mode:
- same as non-dryRun mode

**Comment by gharlan** [comment]
B :+1:

**Comment by stof** [comment]
IMO, dry-run mode should not change the list of fixers compared to non-dry-run. Otherwise you don't get a real dry-run mode (the changes will be different)

**Comment by gharlan** [comment]
Agree. That's the main reason for my vote for B.

**Comment by keradus** [comment]
Cool, then decided. I thought that too - already have an implementation for that (but based on PR with rules&sets), thanks!

**Comment by keradus** [comment]
https://github.com/keradus/PHP-CS-Fixer/commit/894f657

**Comment by keradus** [comment]
Ref #1416

**Comment by keradus** [comment]
Closed thanks to #1416
