### ISSUE TITLE
Files that were not fixed due to internal error

### ISSUE THREAD

**Issue by egeloen** [FriendsOfPHP/PHP-CS-Fixer#947]
Hey!

I just try to fix the CS on one of my projects, and I get the following errors whereas the file is well formatted and the tests about it are green:

``` bash
Files that were not fixed due to internal error:
   1) HttpAdapterFactory.php
```

The file is located at https://github.com/egeloen/ivory-http-adapter/blob/master/src/HttpAdapterFactory.php

My PHP CS Fixer version:

``` bash
PHP CS Fixer version 1.3 by Fabien Potencier (653cefb)
```

**Comment by keradus** [comment]
Do you set any level/config as CLI args/config file ?

**Comment by egeloen** [comment]
No, I just do a `php-cs-fixer fix ./src` in the referenced project.

**Comment by keradus** [comment]
Thanks for your report.
Failing case extracted into test case: #948

**Comment by keradus** [comment]
Closing due to merge of #948

**Comment by egeloen** [comment]
@keradus Thanks!

**Comment by keradus** [comment]
Remember that you can see the change at 1.4-dev, not 1.3 (last stable)

**Comment by eusonlito** [comment]
Hi, same again using PHP CS Fixer version 1.7

File to fix: https://github.com/eusonlito/braintree_php/blob/master/src/Braintree/Error/ValidationErrorCollection.php

Error:
```
php-cs-fixer -vvv fix src/Braintree/Error/ValidationErrorCollection.php

E
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[1.002 s] ./src/Braintree/Error/ValidationErrorCollection.php

Fixed all files in 1.011 seconds, 5.750 MB memory used

Files that were not fixed due to internal error:
   1) ./src/Braintree/Error/ValidationErrorCollection.php
```

Thanks :)

**Comment by keradus** [comment]
Please do not report new issues inside old, closed one.
Please, create a separate issue for it.
Then I will try to fix it this evening ! :D

**Comment by eusonlito** [comment]
Ok, no problem. As a bug with same subject I didn't want to create repeated issues :)
