### ISSUE TITLE
Optimized fully qualified class names fixer

### ISSUE THREAD

**Issue by orlangur** [FriendsOfPHP/PHP-CS-Fixer#959]
There are few trivial fixers already polishing `use` statements:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Contrib/OrderedUseFixer.php
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Symfony/UnusedUseFixer.php
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Symfony/RemoveLeadingSlashUseFixer.php
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Fixer/Symfony/RemoveLinesBetweenUsesFixer.php

I would like to solve problem which PHP Refactoring Browser [claims to solve](https://github.com/QafooLabs/php-refactoring-browser#optimize-use-statements): replace all fully qualified class names in code with shorter form and add corresponding `use` statements. Troubles with their solution: produced code is syntactically incorrect (`use` statements added between `class` and brace), PHPDoc blocks and methods type-hinting are ignored.

Did somebody try to implement something like that with PHP-CS-Fixer? Maybe it's not a good idea to try it and solution should be based on something different (PHP Manipulator/PHP Code Beautifier and Fixer/PHP Parser etc.) or there is a ready-to-use IDE plugin solving this?

Thanks in advance.

**Comment by stof** [comment]
Adding use statements for classes being referenced by FQCN is not an easy task:

- you need to take into account existing use statements to avoid conflicts
- you need to take into account all classes existing in the same namespace in other files to avoid conflicts

In summary, this is more a refactoring of the code than a CS fix. So IMO, it is out of the scope of this project (and I can tell you it will be a pain, because this is not what this project is aimed to do and so it does not give you the relevant tools for that).
Fixing the bug in the PHP Refactoring Browser is probably a better idea.

Regarding the IDE support, PhpStorm is able to do that already AFAIK (I don't know about other IDEs as I haven't used them since years)

**Comment by orlangur** [comment]
> take into account all classes existing in the same namespace in other files to avoid conflicts

Correct, finalizing iteration would add aliases for all colliding class names.

> PhpStorm is able to do that already AFAIK

Could you provide more details, please? I know there is an inspection regarding FQN usages, but did not find an automated refactoring option yet.

**Comment by keradus** [comment]
> > take into account all classes existing in the same namespace in other files to avoid conflicts
> 
> Correct, finalizing iteration would add aliases for all colliding class names.

And that isn't possible for now - PHP CS Fixer works on file-context, don't know what classes are in different files.

**Comment by stof** [comment]
> Could you provide more details, please? I know there is an inspection regarding FQN usages, but did not find an automated refactoring option yet.

Actually no. PhpStorm has an inspection to detect all such places, so it can report them all. And it has a quick fix to add the use statement for such places. But I haven't found a way to tell it to apply the quick fix in all places.

**Comment by orlangur** [comment]
> In summary, this is more a refactoring of the code than a CS fix

It could be called "unsafe fixer" - like other ones which change semantics of code. With #918 in hand and few other high-level operations implemented, like "replace class name", "get class names mentioned in PHPDoc and type-hinting" does not seem a very hard issue to me. Just want to assure that I'm not overlooking something.

> PHP CS Fixer works on file-context, don't know what classes are in different files.

I see, that's a problem :-S So, problem could be solved by fixer + fixer of collisions as another one-time script but cannot be added to PHP CS Fixer itself.

**Comment by keradus** [comment]
> We Need A Way To Get All Imports For A Namespace

This isn't what you thinking.
If won't provide all classes under that namespace but all imports via `import` in
`namespace Foo { import Bar; import Baz; }`

**Comment by GrahamCampbell** [comment]
I was planning on implementing this sort of fixer to fix docblock annotations too where fqns were used unnecessarily.

**Comment by orlangur** [comment]
> This isn't what you thinking.

I thought correctly: I need list of all imports in scope of current file for "fixer" part and "fixer of collisions" part would require some knowledge regarding all classes in namespace.

>  PHP CS Fixer works on file-context, don't know what classes are in different files.

Without such knowledge such fixer would be unsafe, but if we, for example, autoload all classes in namespace first it would be possible to autogenerate suitable aliases.

**Comment by keradus** [comment]
> > This isn't what you thinking.
> 
> I thought correctly: I need list of all imports in scope of current file for "fixer" part and "fixer of collisions" part would require some knowledge regarding all classes in namespace.

I was talking about such lack of classes from other files.


> Without such knowledge such fixer would be unsafe, but if we, for example, autoload all classes in namespace first it would be possible to autogenerate suitable aliases.

No. The fixer may don't have access for whole project. Take a scale like Symfony or ZF. You won't run fix on whole dir, but just take files that was changed. If you use it as web service then you download only that few files, not whole repo.
I am totally against doing such thing.

**Comment by orlangur** [comment]
Ok, producing fatal error for unsafe fixer is way too much compared to just changing semantics a bit in other unsafe fixers.

Thanks for the feedback! Should [stick](https://github.com/magento/magento2/issues/872#issuecomment-68098378) to PHP Parser approach maybe.
