### ISSUE TITLE
American or British English

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#966]
Hi!
One non-dev question ;)
Do we want to follow AE or BE ?
eg `TokensAnalyzer` vs `TokensAnalyser`

I would use BE.

**Comment by keradus** [comment]
From what I can remember fabbot fix AE `thru` into BE `through`.

**Comment by GrahamCampbell** [comment]
:+1: for British english.

**Comment by keradus** [comment]
`Tokenizer` vs `Tokeniser` ?

**Comment by GrahamCampbell** [comment]
`Tokeniser` would be the gb version. :)

**Comment by stof** [comment]
AFAIK, the Symfony codebase is using AE.

and from what I can see, ``thru`` vs ``through`` is nt about AE vs BE. ``thru`` is marked as an informal spelling for ``through`` according to my quick search. but it does not mean that ``through`` is not used in AE (it means that BE does not like it though)

**Comment by keradus** [comment]
Closing then.
Thanks for opinion.
We will follow Symfony, as our... ancestor ? :)
