### ISSUE TITLE
"Fixed all files" message when using --dry-run parameter

### ISSUE THREAD

**Issue by eduardocasas** [FriendsOfPHP/PHP-CS-Fixer#967]
When adding the `--dry-run` parameter to display all the fixes the console output keeps displaying the "Fixed all files" message. I think this issue should be corrected as it is quite confusing, especially for new users.

Using the 1.3 version.

**Comment by keradus** [comment]
Hi!
Would you propose a better message?
Maybe sth like "Check all files..." ?

**Comment by localheinz** [comment]
How about 

```
Would have fixed all files
```

?

**Comment by SpacePossum** [comment]
I think this one is fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1516, but please let me know if you think not so @localheinz :)

**Comment by keradus** [comment]
It is. Closing
