### ISSUE TITLE
Support for array dereferencing and class member access on instantiation

### ISSUE THREAD

**Issue by eduardocasas** [FriendsOfPHP/PHP-CS-Fixer#968]
When I try to fix a file which contains an array dereferencing and/or a class member access on instantiation I get an empty result. PHP CS Fixer doesn't seem to work with these features.

Using the 1.3 version.

**Comment by keradus** [comment]
Could you provide a test case for it? Perhaps as PR?

**Comment by keradus** [comment]
ping @eduardocasas

**Comment by gharlan** [comment]
ping @eduardocasas

**Comment by gharlan** [comment]
Hmm, no feedback, should we close this?

**Comment by keradus** [comment]
Closing as not suitable
