### ISSUE TITLE
Files having an 'include' statement are not scanned

### ISSUE THREAD

**Issue by Zzortell** [FriendsOfPHP/PHP-CS-Fixer#982]
Hi !
When a file state an 'include', php-cs-fixer fix command doesn't analyse at all the file (but none error is thrown).

PS: This is entirely independant of using the 'include' fixer.

**Comment by keradus** [comment]
That's odd.
Could you provide a detailed description with file example ?

**Comment by Zzortell** [comment]
Ok, as soon as I find the time.

**Comment by stof** [comment]
@Zzortell any news ?

**Comment by Zzortell** [comment]
Wow, I completely forgot. And I'm a little busy currently, I will try to keep this in mind.

**Comment by keradus** [comment]
Closing due to cannot reproduce
