### ISSUE TITLE
'multiline_array_trailing_comma' fixer doesn't work with the short syntax

### ISSUE THREAD

**Issue by Zzortell** [FriendsOfPHP/PHP-CS-Fixer#983]
Hi !
The 'multiline_array_trailing_comma' fixer doesn't work if you have :
``` php
return [
	'é' => 5,
	5 => 'é'
];
```

**Comment by keradus** [comment]
What version are you using?
Is it a phar file or you are using tool installed other way? If the second please run `php-cs-fixer --version`

**Comment by Zzortell** [comment]
Installed globally with Composer. php-cs-fixer --version : 1.5-DEV

**Comment by keradus** [comment]
Thanks for that info.
Fixed in #990 !

**Comment by keradus** [comment]
Closing due to merge of #990
