### ISSUE TITLE
Try candidate approach

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#984]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/859#issuecomment-67036131 by @dericofilho 

> Another thing that might be useful is to check before loop if the fixer is a candidate to fix. Check this out:
> https://github.com/dericofilho/php.tools/blob/master/Core/RemoveIncludeParentheses.php#L3-L9
> 
> If the fixer could be tested for candidacy to execution before being executed, then the 20 loops for fixers could be lessened as well.

**Comment by dericofilho** [comment]
Please note that with the release of php.tools 6.0, this file has been changed to a new place:

https://github.com/dericofilho/php.tools/blob/master/src/Core/RemoveIncludeParentheses.php#L3-L9

**Comment by keradus** [comment]
Thanks for update!

BTW, are you online at gitter.im ?

**Comment by dericofilho** [comment]
No. But I may enter there if necessary.

**Comment by keradus** [comment]
You are welcome ;)

**Comment by stof** [comment]
The issue is that this can be reliable only if you check for candidacy after running the previous filters (because the previous filter might introduce a reason for this fixer to run), meaning we would not win much (we would have to analyze the found tokens for each fixer, which would even slow down things because each fixer only cares about a very small subset of this info). This would probably be even more noticeable in 2.0 where all fixers are running on the Tokens collection directly

**Comment by dericofilho** [comment]
The name is "candidate" for a reason, the same reason it is not named as "filter", "check", "test" or similar. The candidate idea aims to return positive and false positives cases - while refusing surely known negative cases. So the idea of testing candidacy is defeated if the aim is perfect accuracy. 

It is the same idea of bloom filter: it might be there, or surely not be there. 

And, what's the point of chaining Fixers, aren't they supposed to be atomic? Thus, being atomic, it also means that candidates can be evaluated all against the original code. 

An example is the else+if to elseif case: if the original code has else+if, and the fixer in question addresses elseif, the right thing to do is to test for all of them: else, if, and elseif. These three might be false positives, but surely no loop will be wasted looking for these three tokens when only others tokens exist.

**Comment by keradus** [comment]
Closing due to #1140 PR
