### ISSUE TITLE
Transfomers are performance bottleneck - Suggested Fix

### ISSUE THREAD

**Issue by dericofilho** [FriendsOfPHP/PHP-CS-Fixer#987]
Hello,

Few weeks ago, I made a research about fundamental flaws in PHP-CS-Fixer. I have made extensive changes into PHP-CS-Fixer code - but I decided not PR them as I would not have time to battle all the energy and time consuming review process you guys have here.

Among all problems, transformers were heaviest part - single transformations took place in several loops. I changed that. Now there are only two loops, and all transformations happen inside them. 

It should be straightforward for any maintainer to take this [gist](https://gist.github.com/dericofilho/7460e435b2193a2f20cb) and incorporate these changes.

The transformers are still atomic - they just happen in less loops.

I hope it helps you guys.

**Comment by keradus** [comment]
Hi!
Looks a little outdated, eg we already merged curly braces transformers into one.

Testing on current master and [test branch](https://github.com/keradus/PHP-CS-Fixer/tree/master-test)

```bash
[keradus@keradus 23:19 ~/github/PHP-CS-Fixer]$ . benchmark.sh master master master master-test master-test master-test
master mean:2.9262 total:29.262 rounds:10
master mean:2.9384 total:29.384 rounds:10
master mean:2.9259 total:29.259 rounds:10
master-test mean:2.8469 total:28.469 rounds:10
master-test mean:2.8486 total:28.486 rounds:10
master-test mean:2.839 total:28.39 rounds:10
```

Only 3 percent boost was noticed, did it work better for you ?

**Comment by dericofilho** [comment]
php-cs-fixer when fixes itself it is always faster - given the wrong impression about speed. 

you have to change the CS of php-cs-fixer into something different than PSR1/2 to really see the difference. In my scripts I did something along these lines: 
```
BASE="77ccc4c51b59544eb8ab59b5bf616e653cdce49a"

cp .php_cs.dist.orig .php_cs.dist.bkp

git branch -D test
git checkout -b test
git reset --hard "77ccc4c51b59544eb8ab59b5bf616e653cdce49a"
php composer.phar dump-autoload
mv .php_cs.dist.bkp .php_cs.dist
php fmt.php Symfony/
time php php-cs-fixer -vvv fix .
git reset --hard
git checkout master
php composer.phar dump-autoload
php fmt.php CS/
time php php-cs-fixer -vvv fix .
git reset --hard
```

Note how I use php.tools to change PHP-CS-Fixer code to K&R, and only then I timed the performance.

if you git-pull current PHP-CS-Fixer master, normalize into a different standard first, then you're going to get the difference (note the second execution is faster because the code is already formatted):
```
PHP-CS-Fixer-performance $ php -i | grep -i 'xdebug support' && echo "Found" || echo "Disabled"
Disabled

PHP-CS-Fixer-performance $ grep "Linter" .php_cs.dist
    ->setUsingLinter(false)

PHP-CS-Fixer-performance $ git checkout Symfony/
PHP-CS-Fixer-performance $ php fmt.php --no-backup Symfony/
Formatting ...
Symfony/
Starting 4 workers ...

 177 files total
Took 2.35s

PHP-CS-Fixer-performance $ php fmt.php --psr1 --psr2 --no-backup Symfony/
Formatting ...
Symfony/
Starting 4 workers ...

 177 files total
Took 2.55s

PHP-CS-Fixer-performance $ git checkout Symfony/
PHP-CS-Fixer-performance $ php fmt.php --no-backup Symfony/
Formatting ...
Symfony/
Starting 4 workers ...

 177 files total
Took 2.08s

PHP-CS-Fixer-performance $ php php-cs-fixer fix Symfony/
   1) CS/AbstractAlignFixer.php
  ...
 174) CS/Utils.php
Fixed all files in 44.927 seconds, 10.000 MB memory used

PHP-CS-Fixer-performance $ php php-cs-fixer fix Symfony/
Fixed all files in 22.770 seconds, 9.000 MB memory used
```

**Comment by keradus** [comment]
Fact that file need to be fixed or not affects performance of each fixers.
It does not affect performance of Transformers, didn't it ?

**Comment by dericofilho** [comment]
> Fact that file need to be fixed or not affects performance of each fixers.
It does not affect performance of Transformers, didn't it ?

This needs to be falsified through profiling - my personal impression is that you are right. Yet, the performance varied greatly against 1.5. As 2.0(master) does not Tokens::fromCode/generateCode anymore, it might be the case it is not influencing anymore.

**Comment by keradus** [comment]
Then the difference is not that big, but still it's worth to take it.

I don't like idea of one file doing it all, I will work on it and send a PR next week and ask for your opinion ;)

**Comment by dericofilho** [comment]
Nice. The important is the concept - I bet you can implement it much better than I can.

**Comment by keradus** [comment]
The implementation can't be much different. As you said we focus on concept, and concept is simple - put what we can into one loop.

**Comment by keradus** [comment]
The one little problem is that some normalizers need to iterate forward, while other need to iterate backwards.

**Comment by keradus** [comment]
not, stuck somewhere else :/

**Comment by dericofilho** [comment]
2 loops are still better than 6.

**Comment by keradus** [comment]
Yeah, just stuck with non-passing tests https://github.com/keradus/PHP-CS-Fixer/tree/2.0-transformers

**Comment by keradus** [comment]
OK, have some idea ;)
Break was great idea ;)

**Comment by keradus** [comment]
Closing due to merge of #1007.
Thank you @dericofilho !
