### ISSUE TITLE
cs problem with indentation inside a docblock

### ISSUE THREAD

**Issue by cordoval** [FriendsOfPHP/PHP-CS-Fixer#993]
```
     *     min = "1",
-     *     max = "45",
-     *     minMessage = "Your username be at least {{ limit }} characters length",
-     *     maxMessage = "Your username cannot be longer than {{ limit }} characters lengt
h"
-     * )
+     *             min = "1",
+     *             max = "45",
+     *             minMessage = "Your username be at least {{ limit }} characters length"
,
+     *             maxMessage = "Your username cannot be longer than {{ limit }} characte
rs length"
+     *             )
```

**Comment by GrahamCampbell** [comment]
What version please? Also, a slightly larger code sample would be very useful.

**Comment by cordoval** [comment]
latest tagged phar, the example code is a simple annotation where you have @Some(a=1,b=2) yet you format it breaking lines. It happens all the time.

**Comment by keradus** [comment]
I'm a bug?

Please provide valid PHP code (eg whole docblock) instead of diff.
I can see nothing in that diff.

**Comment by cordoval** [comment]
he he :baby: @keradus, it is a bug. What the difference can make a comma :baby: 

```
   /**
      * @var ArrayCollection
      * @ORM\ManyToMany(targetEntity="Network")
      * @ORM\JoinTable(name="pcna_invitation_networks")
      * @Assert\Count(
-     *                      min = "1",
-     *                      minMessage = "You must specify at least one network"
-     *                      )
+     *     min = "1",
+     *     minMessage = "You must specify at least one network"
+     *  )
      */
     protected $networks;
```

**Comment by GrahamCampbell** [comment]
> heh what ugly colors github has set for php

That's because it's not valid php.

**Comment by cordoval** [comment]
@keradus any news on this please? not trying to push, just wander what can be done as this keeps happening over and over

**Comment by stof** [comment]
@cordoval does it also happen if you separate the ``@var`` phpdoc tag from the annotations with an empty phpdoc line ?

**Comment by cordoval** [comment]
just ran it @stof your guess is correct, it only happens in this case. Should i close?

**Comment by GrahamCampbell** [comment]
> it only happens in this case. Should i close?

My upcoming phpdoc fixers fix this case btw.

**Comment by cordoval** [comment]
closing
